/* ctype.c --- character type definitions array */

/*
** since prime's ascii always has high bit set,
** the first 128 elements cannot match anything.
*/

/* purposely misspell to decrease chance of conflict */
int _chr_tipe[] = {
0,                      /* for EOF -- see defs in <ctype.h> */
0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
_cn,
_cn,
_cn,
_cn,
_cn,
_cn,
_cn,
_cn,
_cn,
_cn|_sp,
_cn|_sp,
_cn|_sp,
_cn|_sp,
_cn|_sp,
_cn,
_cn,
_cn,
_cn,
_cn,
_cn,
_cn,
_cn,
_cn,
_cn,
_cn,
_cn,
_cn,
_cn,
_cn,
_cn,
_cn,
_cn,
_sp|_pr,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_di|_xd|_gr|_pr,
_di|_xd|_gr|_pr,
_di|_xd|_gr|_pr,
_di|_xd|_gr|_pr,
_di|_xd|_gr|_pr,
_di|_xd|_gr|_pr,
_di|_xd|_gr|_pr,
_di|_xd|_gr|_pr,
_di|_xd|_gr|_pr,
_di|_xd|_gr|_pr,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_up|_xd,
_gr|_pr|_up|_xd,
_gr|_pr|_up|_xd,
_gr|_pr|_up|_xd,
_gr|_pr|_up|_xd,
_gr|_pr|_up|_xd,
_gr|_pr|_up,
_gr|_pr|_up,
_gr|_pr|_up,
_gr|_pr|_up,
_gr|_pr|_up,
_gr|_pr|_up,
_gr|_pr|_up,
_gr|_pr|_up,
_gr|_pr|_up,
_gr|_pr|_up,
_gr|_pr|_up,
_gr|_pr|_up,
_gr|_pr|_up,
_gr|_pr|_up,
_gr|_pr|_up,
_gr|_pr|_up,
_gr|_pr|_up,
_gr|_pr|_up,
_gr|_pr|_up,
_gr|_pr|_up,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_lo|_xd,
_gr|_pr|_lo|_xd,
_gr|_pr|_lo|_xd,
_gr|_pr|_lo|_xd,
_gr|_pr|_lo|_xd,
_gr|_pr|_lo|_xd,
_gr|_pr|_lo,
_gr|_pr|_lo,
_gr|_pr|_lo,
_gr|_pr|_lo,
_gr|_pr|_lo,
_gr|_pr|_lo,
_gr|_pr|_lo,
_gr|_pr|_lo,
_gr|_pr|_lo,
_gr|_pr|_lo,
_gr|_pr|_lo,
_gr|_pr|_lo,
_gr|_pr|_lo,
_gr|_pr|_lo,
_gr|_pr|_lo,
_gr|_pr|_lo,
_gr|_pr|_lo,
_gr|_pr|_lo,
_gr|_pr|_lo,
_gr|_pr|_lo,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_gr|_pr|_pu,
_cn };
