

            swt (2) --- return to Software Tools Subsystem           03/25/82


            _C_a_l_l_i_n_g _I_n_f_o_r_m_a_t_i_o_n

                 subroutine swt

                 Library:  vswtlb (standard Subsystem library)


            _F_u_n_c_t_i_o_n

                 'Swt'  is  called by all Subsystem programs to return to the
                 Subsystem command interpreter.


            _I_m_p_l_e_m_e_n_t_a_t_i_o_n

                 'Swt' calls 'rtn$$'  to  return  to  the  Subsystem  command
                 interpreter.


            _C_a_l_l_s

                 rtn$$


            _S_e_e _A_l_s_o

                 call$$ (6)































            swt (2)                       - 1 -                       swt (2)


