i$9 9ARCOM "0Usage: ar -(a[d]|d|p|t|u[d]|x)[v] <archive> {<fi: :le>}"Fadptuxv n<ign>"Varchive not alteredacj: :a@FQ@	Cacla@acnA@Q@HA@	BCacla@acpA@	@ : :,aSrARCOM act,aKrARCOM 	A
acla@V(Q	AQ	A1Q	A9 95Q	A9=acla@>Q	A
"Q	A
#acvQ@HA@#A@"Q9 9	AQ	AWQ	A[Q	A_cacla@dQ	A
"acxQ@H: :A@"SQ	AQ	AwQ	A{acla@Q	A
"aczQ@H: :A@A@"sQ	A
acla@Q	A
"Q	A
#ac|Q@HA@#A@"Q< <	A
acla@.Q	A
"ac~Q@HA@"*Q	A
"aczQ@HA@A@"=-Q: :	A.Q	ATQ	AtQ	AQ	A+Q	A>acla@Jac: :!}i!i!fi!pi!xi!x$ARCOM !t#GETARG!p#PARSCL!r#ERROR !v. .#DELARG!z#GETFNS!|#APPEND!~#TABLE !#EXTRA0!#UPDATE!#DELETE!#SWT 
 
"%R$0&\$ ACOPY 9 9		QKAQ
	@Q	"MQQ
QQ'
	@acQ@
A@Q	@9 9	"AacQ@
A@"Q	@!QQ		*QKQ'86Q	@: :	#acQ@
A@#Q	@	"AacQ@
A@"Q	@	"MQQF7QQ		! Z!#READF !#WRITEF
 
"%4$0&=4$ ADDFIL: :"*s: can't add*n		ac Q	@A@	"Cac"A@a@Q	@Qk	@9 9
QK	A/ac$A@"QJac&Q	@Q@JQ@
ac(Q@
Q	@ac*Q	@ac,A@"Q	@9 9ac.A@"		!q!}=!=!(#FSIZE !$#OPEN!&#PRINT !*#MAKHDR!,#PUTLIN !.#FLUSH$!0#FCOPY !2#CLOSE 
 
"%p$0&9D$ AMOVE : :" can't replace archive with *s*n!		ac0Q	@A@	"; ;	%ac2Q	@A@	#
		$"	$#ac4A@a@Q	@ac6A@; ;ac8A@"A@#ac:A@"ac:A@#ac<Q	@		!q!}9!!9!8#CREATE$ $!6#OPEN!:#PRINT !<#ERROR !>#FCOPY !@#CLOSE !B#REMOVE
 
"%*$0&z$ APPEND9 9ARCOM "*s: already in archive*n"**s*n"0archive 9 9not altered"D*s: can't remove*n	,aKXARCOM 	A			9 9	acZQ	@A@	"Cac\Q	@ac^A@"Q@
Q@JQ@J	%
!ac`Q@J9 9	@HCacbA@a@Q@J,akdARCOM 	@'acfA@"Q@J 	A#t#,aKhARCOM < <	AQK	A
	#C9AD,aGjARCOM QLacbA@a@*Q	@LD	#C9AD,aGjARCOM QL: :	aclQ	@LA@",a
@dARCOM @	A#,agXARCOM j;;acnA@",aKdARCOM 	A
; ;acpa@0qQK	A
	A#C9AD,aGjARCOM 	QLacrQ	@L	CacbA@a@D8 8Q	@L		A#,agXARCOM ||zv		!q!u!}!!!p9 9$ARCOM !n$ARCOM !^$ARCOM !j$ARCOM !f#FILARG!d#GETHDR!x#REMOVE!`#OPEN!b#CANT!h #PRINT !l#FSKIP !r#ADDFIL!t#CLOSE !v#ERROR 
 
"%r$0&S`$ DELETE9 9ARCOM "arctemp.=pid="delete by name only"2arch9 9ive not altered	,aKFARCOM 	A	acHa@	acJQ	@A@	"C5 5acLQ	@	acNa@A@	#CacLa@ acPA@"A@#A@Q	@; ;,a
@RARCOM acTA@"acTA@#,aKRARCOM 	AacV<,aKRARCOM 	AacXa@5 5Q	@BacZa@acHa@2I		!}S!S!dS!J$ARCOM !V: :$ARCOM !R#CREATE!N#OPEN!L#ERROR !P#CANT!T#REPLA0!X#CLOSE !Z#NOTFO0!\#AMOVE !^#REMOVE
 
"%*$0&Fd$ EXTRA09 9ARCOM "*s*n"*s: can't create*n"*premature EOF< <		ac8Q	@A@	"Cac:Q	@
	can't open temporary file for extraction. QK: :	Cac<A@	@HCac>A@	#Cac@C@80		#=)acBA@"9 9	Q@
Q@
Q@J	%
MacDQ@
	AacFA@"Q@JRQK	A
acHA@5 5a@Q@
]QK	%kacJQ@
A@	#j	#CacHA@a@Q@
; ;,akLARCOM 	@acFA@"Q@JuacNA@"A@#Q@JQ'J,akLARCOM 	@acP: :a@*QK	%
 acRA@#Y@LQK	Cac<A@	@HC)acT: :A@#acVA@#A@acXA@#0,aKLARCOM 	AacZB		!q!u!}!; ;F!!!F!pF!T$ARCOM !@#OPEN!R#CREATE!F#MKTEMP!L#FILARG!J#GETHDR< <!D#ISATTY!V#ACOPY !B#CANT!H#ERROR !N#FSKIP !P#PRINT !X#REMARK!Z#CLOSE !\#REWIND!^#FCOPY  !`#RMTEMP!b#NOTFO0
 
"%p$0&)$ FILARG; ;ARCOM 	,aKARCOM 	A		A"		A#C9AD,aGARCOM QacQ	@Q	@	@HC7 7	At#,aSARCOM 	"		A#,agARCOM &			@ "	!$ARCOM !$ARCOM ! $ARCOM !#EQUAL 
 
"%*$0&" FSIZE / /	acQ	@acQ	@QacQ	@Q		!#MARKF !#WIND!#REWIND
 
"%("0&
" FSKIP  	acQ	@Q	@A@		!!#SEEKF 
 
"%("0&f$ GETFNS9 9ARCOM "'can't handle more than *i file names*n"8*s: 9 9duplicate file name*nacRA@Q@A@	BC	@ ,aSTARCOM 		; ;
	AQ	"	("@	"%	@@ t",aSVARCOM 	"C9AD,aGXARCOM 	QacZQ	@8 8Q@	BC-.		$"2acZQ@Q@	%=3ac\A@a@A@: :,ak^ARCOM 	@<	"@H,aSTARCOM 	A"	("@N	",agTARCOM T	B#	(#9 9	@X	#,agTARCOM 	@"C9AD,aGXARCOM Q	#C9AD,aGXARCOM 	Qac`Q	@9 9Q	@	@HCac\A@a@8Q	@,ak^ARCOM 	@vY^OU		!q!9 9!!!\$ARCOM !Z$ARCOM !X$ARCOM !b$ARCOM !d#EQUAL !^#GFNARG!V#GETARG !`#PRINT 
 
"%,$0&XR& GETHDR9 9ARCOM "#HD#:"###H:"archive not in proper form: :at":###H:	ac@Q	@Q	@A@	BC		"		A#	acBQ	@A@#9 9Q@A@	$	acDQ@a@	AacDQ@a@	A#acFa@,akHARCOM 	@	"9 9		+	acDQ@a@:	@HCacJQ	@>acBQ	@A@#Q	@A@acLQ	@A@#QS	9 9		"	!~!X!X!@X!L$ARCOM !H#EQUAL !D#GETLIN!F#GETWRD!P#CTOL !J#REMARK!N#CONVE0
 
"%2&0&@& GETWRD9 9	QK	@HADQK	C	Qk		A"QK	@HADQK	A
	%	%9 9QK		$"	@!	"@H#QK	@HADQK	t#QSQk	@("#	" 	@HAD@ QS	"@H$	!
! 
 
"%2&0&'f$ GETDA0: :"0JanFebMarAprMayJunJulAugSepOctNovDec"@: :	!%)-"N*s-*,2s-19*,2s		ac^A@Q@	A"ac`Q@: :A@"	#t#aK@	ADaGQacbQ	@A@a@NQ	@Q@Q@
		!'!'!b #CTOI!`#DATE!d#ENCODE
 
"%4$0&2" MAKHDR: :"#HD#:"*s *s  *l  *s  *s*n	ac*Q@
ac,A@Q@ac.9 9Q	@A@a@a@Q	@Q	@Q@
Q@		!!@!,#GETDA0!.#DATE!0#ENCODE
 
"%B"0&#2$ NOTFO0: :ARCOM "*s: not in archive*n	A"	("@	",ag&ARCOM 	@; ;	t",aK(ARCOM 	A	"C9AD,aG*ARCOM Qac,A@a@Q	@,ak.ARCOM 	@- -		!q#!,$ARCOM !*$ARCOM !($ARCOM !0$ARCOM !.#PRINT 
 
"%&$0&P8" REPLA0: :"*s*n"premature EOF	ac$Q	@Q@Q@PQ@P	%ac&9 9Q@P	@HCQK		A
ac(A@a@Q@PQK	Cac*Q@PQ	@Q	@%: :ac,Q	@Q@Pac.Q@Q	@ac0Q	@Q	@Q@PQ'PGQk	@ac2a@F< <4		!u!P!u!*#FILARG!(#GETHDR!4#ACOPY !,#PRINT !.#ADDFIL!0#FSKIP  !2#PUTLIN!6#REMARK
 
"%t"0&7$$ TABLE ; ;ARCOM 		acQ	@A@	"CacQ	@
acA@"Q@Q@FQ@F	%ac: :Q@F	@HCacQ@Q	@"acA@"Q@F,aKARCOM 	Aac3		!: :}!7!7! $ARCOM !#FILARG!#GETHDR!#OPEN!#CANT!#TPRINT!#FSKIP !" #NOTFO0
 
"%l$0&Q.$ TPRINT: :"*s*n"*s *s *-6s *s*n	A"ac&Q	@A@"Q@A@ac&Q	@9 9A@"Q@A@QK	Aac(A@a@Q@ac&Q	@A@"Q@A@ac&Q	@9 9-A@"Q@A@ac&Q	@A@"Q@A@ac(A@a@Q@Q@Q@Q@#		!uQ !	Q!Q!Q!*#GETWRD!,#PRINT 
 
"%L$0&*n& UPDATE9 9ARCOM "arctemp.=pid="*s*n"$*s: can't remove*n: :"8archive not altered		acLQ	@A@	"CacNQ	@A@	"; ;
	"CacPQ	@	acNa@A@	#CacPa@#acRA@"A@#A@Q	@9 9,a
@TARCOM 	A$	($@6	$,agVARCOM 	@t$,aKXARCOM 	AQK	A
8 8	$C9AD,aGZARCOM Q
ac\A@a@Q	@
F	$C9AD,aGZARCOM Q
ac^Q	@
A@#; ;,a
@TARCOM 	At$,aSXARCOM B7<ac`A@"ac`A@#,aKTARCOM 	Aacba@; ;Q	@QK	A
	A$	($@	$,agVARCOM 	@C9AD,aGZARCOM 	Q
acdQ	@
9 9	Cac\A@a@$Q	@
uacda@acfa@8 		!q!u: :!}*!*!u*!`$ARCOM !^$ARCOM !\$ARCOM !Z$ARCOM !j#REMOVE!R#OPEN0 0!T#CREATE!V#CANT!X#REPLA0!b#PRINT !d#ADDFIL!f#CLOSE !h#AMOVE !l#ERROR 
 
"%2&0&`<$ CONVE09 9"#HD#:"*s *s  *s  *s-*s-*s  *s*n	A"	ac0Q	@A@"; ;9Q@A@ac0Q	@A@"Q@A@ac0Q	@A@"Q@A@ac0Q	@A@"Q@A@ac0Q	@; ;9A@"Q@A@ac0Q	@A@"Q@"A@ac0Q	@A@"Q@A@ac2Q	@A@a@a@Q@9 9Q@Q@Q@Q@"Q@		!!!`!	!`!`!@`!8 #GETWRD!:#ENCODE
 
"%L$0&