2(9 9	A"	"@D"	: missing name. acA@"Q@dA@	%	"B#acA@#9 9Q@A@	BCacQ@dA@acC@'	: bad pathname. 2acA@A@ac9 9Q@dQ@TQ@dA@	CacQ@dA@acC@3M	A$%	($@(%@[	t$QK: :	A
	CQK	A
g	($mk	: cannot move file to new directory.o	t$QK9 9	CacQ@A@acC@pn	t$QK	t%QS1\d	@ t%QS1	A$	($@; ;	$%	@		t$QS $	*s: already exists*n. +	A$acQ@2A@$Q@A@ac9 9Q@TA@
Q@A@
A@&	&CacA@C@,Q@R	*s: not found*n.\	&C9 9acA@C@]Q@dhac A@A@&A@A@A@A@q[	Usage: c9 9
n old new {old new}.	"@HCacC@ac"!	  !q!}!!!9 9!!!!
 !!!!/!@!#GETARG!&#GETTO ! #PUTLIN!"' '#ERROR !$#FOLLOW!(#CTOP!*#CNAM$$!,#PRINT !.#ERRPR$!0#SWT 
 
"%(0&