$&: :COMCOM	acacQ@,a
@COMCOM	"acQ@f,a
@COMCOM	#	$"	#C: :		$"	$#!acQ@fA@acQ@f,a
@COMCOM	BC! 		9 9	$"5	#C4acQ@A@acQ@,a
@COMCOM	BC807	acQ@Q@f9 9	$    acQ@A@acQ@,a
@COMCOM	"    acQ@A@acQ@,a
@COMCOM9 9	"acQ@f,a
@COMCOM	#    ]acQ@fA@acQ@f,a
@COMCOM	#rO	$@D%9 9	LP^sGac,a
@COMCOMac,a
@COMCOMac!!!: :!!#GETLIN!#COMPA0!$COMCOM!$COMCOM!#GETPA0!#OUTPUT! #CLOSE !"#SWT 
 
"%r&0&&$ COMPA09 9	A"	("@	"@HADQKQg	A	@ #	           	"@HADQKQg 		#	A#!	#	!&
 
"%*$0&(& GETPA06 6COMCOM	A",aSCOMCOM,aSCOMCOM,aSCOMCOMacA@"Q@A@	BC		5 5,aSCOMCOM		,aSCOMCOM		Q	C	("@@ ,aSCOMCOM,aSCOMCOM; ;,aSCOMCOM		#	(#@*	t#QK	A
	$	A,aSCOMCOM	A,aSCOMCOM9 97	A,aSCOMCOM;3	$%L48<?+1acA@"Q@A@	BC: :		,aSCOMCOM		,aSCOMCOM		S	acQ@A@,aSCOMCOM	CacQ@: :e	("@acA@"Q@A@	BC		,aSCOMCOMv	acQ@A@,aSCOMCOM8 8	CacQ@z		!t!v!}!!!f!-!0! 2 2$COMCOM!"$COMCOM!$COMCOM!$COMCOM!$COMCOM!#GETARG!$#OPEN!&#CANT
 
"%&0&4$$ OUTPUT5 5COMCOM"*#x"*#x	Qw,aKCOMCOM	A
QK	": :,aKCOMCOM	A
acA@a@A@,aKCOMCOM	A
acA@a@A@9 9
	"@H#L%	ac Q	@A@		!u4!4!$COMCOM!  $COMCOM!$COMCOM!#PRINT !"#PUTLIN
 
"%*$0&