Nv(9 9"i<ri>k<rs>m<rs>o<rs>"&Usage: cset [-i <int> | -k 9 9(<key> | -m <mnemonic>] [-o (i | k | m)]"j
Usage: cse9 97t [-i <int> | -k <key> | -m <mnemonic>] [-o (i | k | m)9 9]".0Usage: cset [-i <int> | -k <key> | -m <mnemonic>9 9] [-o (i | k | m)]"rUsage: cset [-i <int> | -k <key9 9$> | -m <mnemonic>] [-o (i | k | m)]"6Usage: cset [-9 95i <int> | -k <key> | -m <mnemonic>] [-o (i | k | m)]9 9"z*i*n"*s*n"*s*n" *i decimal, *,8i octal: :/, *,16i hex.  keycode = *-2s, mnemonic = *s.*nacRa@9 9Q@	CacTa@&Q	A
Q
	AQ	AacTa@j; ;Q
	A
Q	A
acTa@.&"acVA@Q@HA@	%7acT9 9a@r6+Q	A
Q(	ADQGQPacXQ	@PQ@HA@acZQ@HA@QH	C9 9	A"XQH	C		"`QH	C		"hacTa@6k9 9c[>		"p			#A7	#QGLQRac\A@#Q	@R	#%
	%	9 9		QL	#C		QM	#QM	@ QN		#QL	@ QM: :	#9@ADQGLQRac^Q@LA@Q	@RA@	A#%	;ttQ	A
Q"	$A	%	: :CE		$F	$%%	OO	%N	@P			$@H%R>Q
	A
Q$; ;	ADQGQPacXQ	@PQ@HA@QH	CacZQ@HA@o				$@H%		#9@ADQGLQR: :	ac`Q@HQ	@R	@HC	#$%	A#%{{[Q	A
Q&	AD9 9QGQPacXQ	@PQ@HA@acZQ@HA@			$@H%		#A7	#QGLQTac`Q@HQ	@T	@H9 9	C	#$%D	A#%O55H			$	%OW	"&	$#	(#@9 9Y	#$%	@acbA@a@zA@#Z^	$#	(#@l	#$%	@9@ADQGL; ;QPacbA@a@Q	@Pmqi	$#	(#@	#$%	@A7	#QGLQPacbA@; ;a@Q	@P	$#	(#@	#$%	@9@ADQGLQPA7	#QGLQVacbA@9 9a@A@#A@#A@#Q	@PQ	@V $V	&LWjDacd!u!}9 9!N!!!!N!@N!	!
 !#N!^N!i!: :kN!mN!!f#GETARG!p#EQUAL !b#PARSCL!d#ERROR !h#CTOC!j#MAPSTR!l#CTOMN !n #SCOPY !r#PRINT !t#SWT 
 
"%(0&