&"7 7DIFFC0.`C8.`C79C6pC5pC4pC3pC2pC1ac,aK	DIFFC0	Cac9 9,aK	DIFFC0	Cacacacacacac 	ac"!!!8 8$	DIFFC0!#INITI0!#SIMPL0!#BINAR0!#LOAD!#PAIR!#GROW! #LABEL !"#REPORT!$#SWT 
 
"%""0&	0& ENTER 9 9DIFFC0.`C8.`C79C6pC5pC4pC3pC2pC1	acQ	@	"t",aKC6	##A
	t#; ;,aKC7	$A7$,aG~C8	QjacQ	@j,a
@DIFFC0	A@acQ@,a
@DIFFC0ac9 9Q	@Q@	@HC	$%	-	t#,aK C7	#
	too many unique lines; symbol table ov: :erflow. 6		,ag"DIFFC0	@ac$C@7Q,aK"DIFFC0	$B,aS"DIFFC0acQ	@: :	"t",aKC6,aw&DIFFC0,aS C7	$,aSC7,aK&DIFFC0	t",aSC6	@D,aS&DIFFC0: :ac(,a
@DIFFC0ac*,a
@DIFFC0A7$,aS~C8ac,Q	@,a
@DIFFC0	$%	!9 9	!p	!$C6!"$C7!$C7!$~C8!($DIFFC0!$$DIFFC0!$DIFFC0!#HASH!,( (#MARKF ! #EQUAL !#SEEKF !#GETLIN!&#ERROR !*#WIND!.#PUTLIN
 
"%&0&5d, GENLI09 9DIFFC0.`C8.`C79C6pC5pC4pC3pC2pC1"   *4i *4i|"*cd *4i: : *4x|"*
*cd *4io|"4*ci *4x *4i|"B
*ci *4in|: :		"#	A$		%A&		'A(		'	(		%	&; ;	t",aKLC1	A	t#,aKNC2	A$)	At",agLC11	t#,aKNC2	@HC09 96	At",agLC1?<	t#,aKNC2	%E>D	At",agLC1MJ9 9	t#,aKNC2	@HCLR		t",agLC1[X	t#,aKNC2	@HCZ`9 9		,aKP
DIFFC0	@HCacRA@A@h	("@(#@o	t",aKLC1	A	t#: :,aKNC2	AxacTQ@,a
@VDIFFC0	)A,agP
DIFFC0	#A*"@H+acXA@; ;a@A@+A@*acZQ@A@
acTQ@,a
@\DIFFC0	)p}	acRA@A@9 9	("@0	t",aKLC1	@HCacTQ@,a
@VDIFFC0	)A,agP
DIFFC0FC	": :	A*acXA@a@A@'A@*E	"@H*acXA@a@*A@'A@*SacZQ@A@18 88acRA@A@	(#@o	t#,aKNC2	@HCacTQ@,a
@\DIFFC0	)A9 9,agP
DIFFC0	#A*acXA@a@4A@%A@*	#@H*acXA@a@BA@%9 9A@*acZQ@A@pwh	(L('	&L.)9 9!u5!!5!
! 5!c5!R$C1!T$C2!\$DIFFC0!b$DIFFC0   !V$
DIFFC0!Z#GETLIN!X#PUTCH !^#PRINT !`#PUTLIN
 
"%,0&=b( GENRE09 9DIFFC0.`C8.`C79C6pC5pC4pC3pC2pC1"[cc]mc |*n"[cc]mc*n9 9"&[cc]mc ***n"2	[cc]mc*n"<[cc]mc |*n"H[c: :c]mc*n		"#	("@(#@acRQ@,a
@TDIFFC0	$acVQ@A@acXA@9 9a@	A%acXA@a@acXA@a@&acXA@a@2	A&%		&4acX9 9A@a@<		%acXA@a@H5	t",aKZC1	A	t#,aK\C2	AN5 5S	At",agZC1[	t#,aK\C2	@HCZ`	At",agZC1if	t#7 7,aK\C2	%oh&n	At",agZC1wt	t#,aK\C2	@HCv6|		t": :,agZC1	t#,aK\C2	@HCI
HI		8	("@	t",aKZC1: :	@HCA	(#@	t#,aK\C2	@HCacRQ@,a
@TDIFFC0	$acV9 9Q@A@!	&L5910	%LB7!u=!!& &=!^$C1!`$C2!X$DIFFC0!V#GETLIN!Z#PUTLIN!\#PRINT 
 
"%(0&oF, GENSC09 9DIFFC0.`C8.`C79C6pC5pC4pC3pC2pC1"*ia*n".*n"*i,*; ;id*n"$	*i,*ic*n"..*n"2w*n		"#@ $	("@(#@ac6: :Q@,a
@8DIFFC0	%	$"@H&ac:A@a@A@&	A'ac:A@a@	($$< <	A)		$"&@H*&(@H&ac:A@a@A@&A@*	$($*		)-		$"&@H*&(@H&ac:: :A@a@$A@&A@*	$($	' ac:A@a@.	($$D	t",aK<C1	A	t#9 9,aK>C2	Apu	At",ag<C1}	t#,aK>C2	@HC|	At",ag<C19 9	t#,aK>C2	%    
+	At",ag<C1	t#,aK>C2	@HC: :E		t",ag<C1'$	t#,aK>C2	@HC&k,jk	ac:A@a@2		9 9G	@ (	("@8	At",ag<C1B?	((9A`	@ (	(#@H	At#: :,ag>C2RO	((ac6Q@,a
@8DIFFC0	%ac@Q@A@IQE	)L9 9.Hcb	'L!ai!uo!!o!@$C1!B$C2!<$DIFFC0!:                                                                   GETLIN!>#PRINT !D#PUTLIN
 
"%,0&

H$ GROW: :DIFFC0.`C8.`C79C6pC5pC4pC3pC2pC1	A"	("@	",agDIFFC0	t": :,aKC4	#A,aKC4	A	t#,a_C3	C	"B,aSC3	#Bt",aSC49 9	,aKDIFFC0	"	"@H"&	A$",	t",aKC4	#A,aK~C4	A5 5	t#,a_~C3	C7	"@H,aS~C3	#@Ht",aS~C4<3'-		!$~C3! $C3!$~C4!$C4!$C4!$DIFFC0
 
"%$$0&

$ HASH2 2	@ "A#	(#@	#@HADQK	A
	""		"AM=@B"	!9
 
"%($0&<& INITI09 9DIFFC0.`C8.`C79C6pC5pC4pC3pC2pC1	A,aS	DIFFC0	@ ,aS
DIFFC0	A"ac: :	A@Q@A@	%Q	CacQ@A@		#	(#@ 	t#QK	A
: :	$		,aS	DIFFC0		,aS	DIFFC0-	A,aS	DIFFC01		,aS	DIFFC059 9		,aS	DIFFC09	A,aS
DIFFC0=)	$%L*.2JKLMNO9 9PQRSTU6:VY>ZacA!'		"acA@"Q@A@	B: :	C			,aSDIFFC0		
,aSDIFFC0k	acQ@A@,aSDIFFC0	Cac 6 6Q@}	("@acA@"Q@A@	BC			,aSDIFFC0	acQ@A@: :,aSDIFFC0	Cac Q@	("@racA@"Q@A@	%/ac.	ca: :n't open temporary file.1	A,aS"DIFFC0,aS$DIFFC0ac&A@,aS(DIFFC0	Cac*: :C@2L	can't open temporary file.Qac&A@,aS,DIFFC0	Cac*C@Rg	ca9 9n't open temporary file.lac&A@,aS.DIFFC0	Cac*C@m		!
t!	v!6 6}!!!!!!!-!4!a!0$DIFFC0!.9 9$DIFFC0!&$DIFFC0!($DIFFC0!4$DIFFC0!8$DIFFC0!:$DIFFC0!$	DIFFC0!$
DIFFC0!2' '#MKTEMP!*#OPEN! #GETARG!"#MAPSTR!$#USAGE !,#CANT!6#ERROR 
 
"%Z&0&h& LABEL 9 9DIFFC0.`C8.`C79C6pC5pC4pC3pC2pC1"Old_xref (*i) = *i, New_7 7xref (*i) = *i*n":in label:  can't happen		"#t"8 8,aKRC3	$t#,aKTC4	%	At",aSVC1	""	At#,aSXC2	##	@ t"9 9,aSVC1	("@t#,aSXC2	(#%	At#,aSXC2	##At%,aSVC1	t",aSVC1	""At$9 9,aSXC2&,aKZDIFFC0	$"	@,aK\DIFFC0	$#>	@C	",agZDIFFC09 9I	$AJM	#,ag\DIFFC0R	%ASV	$#C	%"C[; ;_	",agZDIFFC0	@#,ag\DIFFC0d	@'iac^A@a@A@"A@$A@#A@%9 9ac`a@::		,aSbC1,awZDIFFC0,aSVC1,aSdC2,aw\DIFFC0,aSXC26 6		!q!!X$C1!d$C1!Z$C2!f$C2!T$C3!V$C4!^$DIFFC0!\ $DIFFC0!`#PRINT !b#ERROR 
 
"%&&0&

4& LOAD9 9DIFFC0.`C8.`C79C6pC5pC4pC3pC2pC1	A"@ t",aSC6	A"%	A#@ t#; ;,aSC1,aSC2	A#%		#	(#@	old file too large to handle. ac: :Q@,a
@DIFFC0	%8		$#
:acC@ ;acQ@,a
@DIFFC0ac Q@9 9	$t$,akC1	@#,aS"C5	$At#,aS$C37	#,aS&DIFFC0		#	(#@]	9 9new file too large to handle. `acQ@,a
@(DIFFC0	%y		$#
{acC@a|9 9acQ@,a
@*DIFFC0ac Q@	$t$,akC2	@At#,aS,C4^x	#,aS.DIFFC09 9		!!!p!9!$C1!$C2!($C3!0$C4!&$C5!$C6!2; ;$DIFFC0!*$DIFFC0!$DIFFC0!,$DIFFC0!"$DIFFC0!.$DIFFC0!$#ENTER !#GETLIN!#ERROR  ! #PUTLIN
 
"%&0&

7$$ PAIR: :DIFFC0.`C8.`C79C6pC5pC4pC3pC2pC1		"	("@	",agDIFFC0	t"6 6,aKC4	A#At#,agC1,aKC2	@HC,aKC5	t",aSC4	AD": :,aSC3		A,aSC4,aSC3,aK DIFFC0,awDIFFC0,aSC4,aKDIFFC07 7,aw DIFFC0,aSC3		!7!$C1!$C2!$C3! $C3!$C4!$C4! $C5!$DIFFC0!"$DIFFC0
 
"%$$0&. $ REPORT6 6DIFFC0.`C8.`C79C6pC5pC4pC3pC2pC1ac,a
@DIFFC0ac,a
@DIFFC09 9,aK	DIFFC0	"    acacac                           	in report:  can't happen. 	"L9 9
acC@		!$DIFFC0!$DIFFC0!$	DIFFC0!#REWIND!#GENLI0!#GENRE0! #GENSC0!#ERROR 
 
"%$$0&cj& SIMPL09 9DIFFC0.`C8.`C79C6pC5pC4pC3pC2pC1"*5i*n*8x*s*8x*s" dif9 9	ferent*n",different*n"8eof on old file*n"Je: :of on new file*n	@ "ac\Q@,a
@^DIFFC0	#ac\Q@f,a
@`DIFFC0	$9 9		$#	$$	("@	acbQ@Q@f	A,aKd
DIFFC0	@HC7 7acfA@a@A@"Q@Q@f'	acfA@a@ 		4"	#$C		@9 9,aKd
DIFFC0	AacfA@a@,E	#BCacfA@a@8P	$BCacf9 9A@a@J[WL		!u!c!`$DIFFC0!b$DIFFC0!f$
DIFFC0!d#EQUAL !^#GETLIN !h#PRINT 
 
"%r&0&@& BINAR09 9DIFFC0.`C8.`C79C6pC5pC4pC3pC2pC1"*10l: *6,-8,0i *6,-8,0i*9 9n"*different*n"6different*n"B*10l: *6,-8,0i9 9 *6,-8,0i*n"\eof on old file*n"neof on new file: :*nAQacQ@A@,a
@DIFFC0	"	acQ@A@,a
@DIFFC0	#"C; ;	"%	A$t$QGQQGQQK        Qg        0,aK
DIFFC0	@HC9 9	$MQQacA@a@Q@Q	@Q	@4	acA@a@*		G/	A$$"U 9 9 	"MQQ	"#C		_,aK
DIFFC0	AacA@a@6		d		; ;	$"p	$#so	"$#u	%	"v	#%	#z	A$t$QGQQGQQK        ; ;Qg        	$MQQacA@a@BQ@Q	@Q	@	A$$%(r	"BC9 9acA@a@\+	#BCacA@a@n62		!u!>!>" "!$DIFFC0!$DIFFC0!
$
DIFFC0!#READF !#PRINT 
 
"%.&0&" USAGE - -	Usage:  diff [-{b|c|d|r|s|v}] [old_file [new_file]].acC@!#ERROR 
 
"%""0&