"< <acA@Q@A@	BCac
acQ@ac!!!#GETARG!#GENER0 !#INTER0!#SWT 
 
"%""0&4 GENER09 9"5cmdfhdfhd4000floppymhd32mhd4000mhd8smd9 9"F	#,2"PTypes are:*n"^ *s"bfixed9 9"h
removable"rtop"vbottom"~head numbers must: : be non-negative"  can't have more than *i heads*n9 9"@starting head must be even"\odd head must be last: :"r*,-8i*n	@ "#	$Disk type: *s.aczA@C@Q@	BC		; ;ac|Q@A@ac~a@Fa@A@Q@	%BCacA@a@P	A%	(%@5	%a'F: :	@t%aKF	ADaGQfacA@a@^Q	@f6;acA@A@,	t%aKE	AD9 9aK	$T	$%`	C	A&Fixed or removable part? *s.eaczA@C@fQ@9 9	BC		~ac|Q@A@		$	A#		acQ@a@b	%9 9acQ@a@h	% 
eb	@ &!	$'		#Top or bottom surface: *; ;s.)aczA@C@*Q@	BC		Aac|Q@A@acQ@a@r	@HC	@ #< <Q	acQ@a@v	@HC	A#]T	#%d)	&A
	
32, 64 or 96 MB: *i.hacz: :	A@C@iA@(	BC		}	(%	%	%		h	(
(g	: :	80 or 300 MB: *i. aczA@C@A@(	BC		"	(%(	%+'*	(; ;	)	A*		*1		*4		*7.	)%
?/	%B2	%E5	%H: :8:	First head (0- ): *i. Number of heads: *i.HaczA@C@IA@"	%
iaczA@: :C@TA@#	%ths		t	"A	#Ax{aca@~|	#"*C9 9acA@a@ A@*	"?
aca@@	#"$*	#?
aca@\9 9$H%	&A
	"
")d&	'@H+L'''e-	Contro9 9	ller (0 or 1): *i.7aczA@C@8A@,	BC		N	,A7	%7	@Unit (0-3): 9 9*i. VaczA@C@WA@-	BC		i	-AV	%V	@#.$C=/,C90#C91: :	"C510/.2$@HC	-22	-C?22acA@a@rA@2		!p!q!9 9u!v!!!!!!
!!! 9 9!0!@!P!	`!x!!
!,!!#EQUAL !#INPUT  !#STRBSR!#MAPSTR!#PRINT !#PUTCH !#REMARK
 
"%40&\J, INTER09 9"#Controller 4000 moving head disk*n"4Controller 409 900 fixed head disk*n"VFloppy disk*n"d
Controller9 9* 4003 moving head disk (8 sector/track)*n"Controll9 9er 4003 fixed head disk*n":Controller 4003 moving h9 9ead disk (32 sector/track)*n"pController 4004 "9 9cartridge module disk "(fixed part)*n"*(remova9 9ble part)*n">storage module disk*n"Tunrecogniza9 9ble disk type"n   controller *i, unit *i*n"
   9 9&first head: *i, number of heads: *i*n	*s: can't recognize a 9 9disk number*n.	A"ac4Q	@A@"A@	#"@HADQK	A
ac6A@C@Q	@		%: :	#A5$#%#A9%&#A9'#A=(@HC	#)E	#A?)I	(*ac6A@	a@9 97ac6A@	a@4Wac6A@	a@V^ac6A@	a@deac6A@	a@lac6A@	a@:: :sac6A@	a@pac8A@
A@"A@	%ac6A@	a@	#0ac6A@	a@	$9 9	$	ac6A@	a@*	ac6A@	a@>%zP	*B+LQX_: :fmt{ac:a@T		,ac6A@	a@nA@'A@)	(%
MM	%L	@N9 9ac6A@	a@
A@$A@&P		!p!q!	u!\!!
\!!7 7!!\!\!x!\!!B#GCTOI !F#GETARG!D#PRINT !H#REMARK
 
"%0,0&