L$9 9"5JanuaryFebruaryMarchAprilMayJun9 97eJulyAugustSeptemberOctoberNovember9 9December"&SundayMondayTuesdayWednesda9 9 yThursdayFridaySaturday"N*2l:*2,,0l *,2p, *; ;s, *s *l, *l.*n	@QAQAQ	B>	AQ
A;	AGQ: :	B>GQacpQ@A@Q	QQ	QQ	QQ	B("Q	B`: :	9@"QQ	B("Q	B`9@"QQ	B("Q	B`9@"QQ	M=MQ9 9A;	AQQ	M	QQQ	MQQ	MQQ	M	QQA'9 9|		#Q	ACG{Q}		#GQ'Q	BQ; ;Q	%	QQGQQ	MQ	@QQ	QQ9 9	MQ	@Q,	QQQ	M=	MQ;	A	QQQ	M=	@Q	M=
M; ;Q;	A	QQQ	M=
@Q	M=MQ;
	A	QQQ	M=@Q	MQ;9 9	A	QQQ	9@@DM=M	QQQ	MQ	EA?	C	G!QA;	At9 9aG~QQG;	At'aGQacrA@a@NQ@Q@A@#Q	@Q	@Q@Q@act9 9!00!AM!PM!u<!!!<!	!
<!<<!
d!; ;<!	!l<        
        ]<Lm!~#TIMDAT !#PRINT !#SWT 
 
"%D$0&