Vn&: :1HELPC0"-c"-d"-f"-g" -i"$?*"(-7 7p",-s"0-u"4general help"Bgeneral		; ;,aSJ0HELPC0		"	,aSLHELPC0	@ ,aSNHELPC0	A,aSPHELPC0	@ ,aSRHELPC0,aSTHELPC08 8	A#	(#@acVA@#,a
@THELPC0A@	%#acX,a
@THELPC0A@acZ; ;,a
@THELPC0a@	@HC	A"1acZ,a
@THELPC0a@	@HC	@ ,aSJ0HELPC0: :=acZ,a
@THELPC0a@	@HC		"JacZ,a
@THELPC0a@	@HC: :		"VacZ,a
@THELPC0a@ 	@HCac\a@$	$BCac^jbacZ: :,a
@THELPC0a@(	@HC	A,aSLHELPC0vacZ,a
@THELPC0a@,	@HC		9 9	"acZ,a
@THELPC0a@0	@HC	A,aSRHELPC0		Sorry, no help is : :
available for *s*n. ac`,a
@THELPC0A@"	$AacbA@C@,a
@THELPC00: :	$BCac^
=9zmYMA4"	#@HCacda@4,a
@THELPC0	A@ac`a@B5 5A@	$Dac^!q!V!!!!V!eV!,!\; ;$HELPC0!T$HELPC0!V$HELPC0!X$HELPC0!Z$HELPC0!R$0HELPC0!^#GETARG!b#EQUAL !h#LOOKUP !d#LOCAT0!`#MAPSTR!f#SWT !j#PRINT !l#CTOC
 
"%&&0&P& LOOKUP: :	QK	"acQ	@	#AacQ	@	#AacQ	@	#acQ	@	#9 9acQ	@	#acQ	@	#$acQ	@	#*	"@D$L
+< <%7	in look_up:  can't happen.<acC@=0	#	!#LOCAU0!#LOCAV0!#LOCAT0!#LOCAW0 !#ERROR 
 
"%,&0&UR$ LOCAU09 9"=doc=/fman/s1/&.d""=doc=/fman/s3/&.d"4=doc=/f: :man/s5/&.d	acFa@Q	@Q@A@acHQ@A@	"CacFa@"Q	@9 9Q@A@acHQ@A@	"CacFa@4Q	@Q@A@acHQ@A@	"C	@ : :	#	<(acJA@"	BCacLA@"		#	FacLA@"	A#	!}!U! U!,!L#OPEN!N#DISPL0!J#SUBST0!P#CLOSE 
 
"%T$0&UR$ LOCAV09 9"=doc=/fman/s2/&.d""=doc=/fman/s4/&.d"4=doc=/f: :man/s6/&.d	acFa@Q	@Q@A@acHQ@A@	"CacFa@"Q	@9 9Q@A@acHQ@A@	"CacFa@4Q	@Q@A@acHQ@A@	"C	@ : :	#	<(acJA@"	BCacLA@"		#	FacLA@"	A#	!}!U! U!,!L#OPEN!N#DISPL0!J#SUBST0!P#CLOSE 
 
"%T$0&-,$ LOCAW09 9"=doc=/help/&.d	ac a@Q	@Q@A@ac"Q@A@	"C	@ : :	#	ac$A@"	BCac&A@"		#	ac&A@"	A#	!}!-!- !,!&#OPEN!(#DISPL0!$#SUBST0!*#CLOSE 
 
"%T$0&x( LOCAT09 91HELPC0"*s:  ill-formed pattern*n"*=doc=/fman/conten9 9ts">cannot open index file *s*n"Z=doc=/fman/con9 9tents"n?*"rhelp index [**i+] more ? "help 9 9index [**i$] more ? "&*s [**i+] more ? "8*s [**9 9i$] more ? 	A"acJQ	@A@A@Q@	CacLA@a@Q	@	"	9 9	acNa@*A@	#CacLA@a@>a@Z#	cannot create scratch file for help : :entry.-acPA@	$CacRC@.JacTQ@\A@#A@	%ZacVQ@\A@9 9Q@0A@acXQ@0A@acZQ@0Q@	@HCac\Q@\A@$	CY{rO|9 9ac^A@#ac`A@$acbQ	@a@n	@HCacdQ@A@a@racdQ@A@a@: :	A%&	(%@#	%@H't'QK	A
	&%0QK	t&QS3		C			QS4	(&: :	@9	(&@1$-	@ t&!QS3acdQ@A@a@&Q@4acdQ@A@a@8Q@4acf: :A@$Q@Q@A@
A@,a
@h0HELPC0	BC		"j	cannot close scratch file.macj: :A@$	CacRC@n!q!u!}!!!!!
: :!e!	*!+!,!t$0HELPC0!r#PAGE!Z#OPEN!V#MAKPAT!f#MATCH !h#DISPM0!`; ;#GETLIN!n#EQUAL !\#MKTEMP!v#RMTEMP!X#PRINT !^#ERROR !b#SCOPY !d#MAPSTR!j#CLOSE !l#REWIND !p#ENCODE
 
"%(0&I( SUBST09 9	A"#"@H$t$QK	A
	#
Qg	QK	%	#@H%QK	t%QS	("@(#: :!	("@A&	(&@'	&@H$t$QK	A
	#Qg	15	@H%QK	t%QS 	(#((6"	#@HAD@ QS		!&
 
"%4(0&O
& DISPL09 91HELPC0"_F_u_n_c_t_i_o_n
"*_D_e_s_c_r_9 9i_p_t_i_o_n
"N*s [**i+] more ? "`	*s [**i$]; ;	 more ? 	cannot create scratch file for help entry.,aKrHELPC0	AactA@9 9	"CacvC@"acxQ@0Q	@A@	%2,aKrHELPC0	@HCaczQ@<: :a@	%@aczQ@<a@*	%I?H1I6,aKrHELPC0	@HCac|Q@0; ;A@	CJXO	ac|Q@0A@"	CYcZ'd,aKrHELPC0	A9 9ac~A@"	A#$	(#@q	t#,aKHELPC0	A
	$%{,aKHELPC0	t$QS; ;	C		QS	($@	($@|rx	cannot close scratch file.	@ t$	QSacQ@\: :*A@a@NQ@acQ@A@a@`Q@acA@"Q@\Q@A@	A@,a
@0HELPC0	%ac9 9A@"	CacvC@Hi	%	!u!}!O!!O!	O!e: :O!*O!+!,!
$HELPC0!|$HELPC0!$0HELPC0!#GETLIN!#DISPM0!#EQUAL !" "#PAGE!~#MKTEMP!#RMTEMP!#ERROR !#REWIND!#ENCODE
 
"%Z&0&
p& DISPM09 91HELPC0	,aKHELPC0	@HCacQ	@Q	@		"	QK	C,aKHELPC0	@H; ;	C		"		A,aSHELPC0	@ ,aSHELPC0	A#$	($@&	$@HADQK9 9	A
	C	#@H#2	#@H%$@HADQK	t%QS	(#@6'/	#@HAD@ QS; ;	A$$%O	@HADQK	%XP	A
W	($MMY	$@HADQGQacQ	@Q	@9 9,akHELPC0	@	"	!~p!!!
p!$HELPC0!$HELPC0!$HELPC0! #PUTLIN
 
"%.&0&