2h
&: :"4Usage: iota [-f <format>] [<lower_lim>] <upper_lim>: :"Df<rs>"J*i	acNa@DQ@	CacPa@Q	%Q4; ;Q	ADQGQ.acRa@JQ	@.A@	BQ4Q4           acTA@Q@HA@	BCacP9 9a@2	A"#acVQ@HA@#A@	$t#QKG	A
acPa@GacTA@Q@HA@9 9	%W	$"A#acVQ@HA@#A@	$t#QKG	A
acPa@hV	"$$o	#: :	(#@r	#$$	@Q	ADQGQ.acXA@Q	@.A@#acZA@A@sw9 9p	"#	#@H#	$$#	@Q	ADQGQ.acXA@Q	@.A@#acZA@A@9 9ac\!u!}!2!!2!
2!f!
2!H2/ /!^#GETARG!`#GCTOI !X#PARSCL!\#CTOC!Z#ERROR !b#PRINT !d#PUTCH !f#SWT 
 
"%V&0&
