
,9 9"5Usage: lacl [-l] [-b [-a]] [-p] [-t] [-c] [-v] {<path9 9name>}"LCannot list acl for '*s'*n"hspecificac9 95atdefault specificdefault acatis an acatpriority9 9"(
 -8"0#l<f>a<f>b<f>c<f>p<f>t<f>v<f>n<ign>"T*: :n"X "Z*s "^by *s "f*s "j ("n); ;"p*s*n	acva@0Q@	Cacxa@Q	A
"Q	A
#Q	A
A	"9 9	$Q	A
%Q	A
A	%	A&Q	A
A	&A	"	&Q	A	"A14: :acza@TQ@xA@5acza@XQ@xA@>	#A
		'I	A'L	AQ|: :	ac|Q@Q@|	(ac~acxa@Y	()L\ZgacQ@Q@DA@: :	CacA@a@LQ@sacQ@DA@'A@*	CacA@a@LQ@; ;acQ@HQ@|A@+Q@x	CacA@a@LQ@	#A
		+)	$A
ac9 9	A@a@ZQ@D.	"A	$A
Q	A
<9@A	#ABacA@a@^9 9Q@HEQ	A
acA@a@fQ@HRN	"AQ	A]a	$A
; ;	acA@a@je	t+aK)	ADaGgQ4acQ	@4A@	$A
acA@a@n|bac9 9A@Q@x	&A
acA@a@pQ@|&|`	*@HCac
A@A@R!q; ;!u!}!!!!!!4!#MKSACL!#GFNARG!#GTACL$/ /!
#EXPAND!#PARSCL!#ERROR !#CTOC!#SWT !#PRINT !#PUTLIN!#FOLLOW
 
"%b,0&
