2*9 9	@ "A#	(#@	too many files or insertion strings.acA@#Q@A@	%%9 9		$#
'acC@(Q	CQ	%7	%:619	At#QSe	#; ;	9@ADQGfQiLacQ@A@Q	@iLA@:	@ t#QSeacQ@A@	t#QSe	C: :acQ@a	At#QSe	""Q$	#@HC	@ Qf			Qf	AQf	@ Qg; ;		
Qg	AQg		#	"p	there must be at least one input file.	#@H$"AacC@: : 	@ %@ &A#	(#@+	#$$	@t#QKe	@HC	#9@ADQGfQiL	t&QGfQiN9 9		&'acQ	@iLQ	@iNA@'	&&7	t#QKe	@HCQGeQiLacQ@Q	@iL	(BC9 9		t#QSe	(%@"$%	@of	t(QK	C	@ QSx	t&QGf: :QiL		&'acQ@Q	@iLA@'	&&rXR,0		t&QSf	@ QSgacQ@fA@'9 9qac !
t!u!	v!}!!!!!d!f!
!< <-!I!i!! #GETARG!,#GETLIN!*#CTOC!&#OPEN!"#ERROR !$#SCOPY !(#CANT!.#PUTLIN !0#SWT 
 
"%iz*0&