HB9 9}DS$MEMLF$COM"-- *s --*n"*s: not found*n",=GaTec: :h="6yes	A"ac:A@	@ ,aS<LF$COM	A,aS>LF$COM	#$ac@A@#8 8,a
@BLF$COMA@,aSDLF$COM	(#@ac@A@#,a
@BLF$COMA@,aSDLF$COM9 9,aKDLF$COM	%
+acFA@%,aKHLF$COM	AacJ,a
@BLF$COMA@	%<29 9;	A&<	A'@*	#$C	@ ,aSBLF$COM,aSDLF$COM		'9 9CHP,aKLLF$COM	A
acNA@a@,a
@BLF$COMU	@ ,aSPLF$COMacR9 9A@	(t(,aGT	DS$MEMQjacV,a
@BLF$COMQ	@j,a
@PLF$COM,a
@XLF$COMA@	)< <
acZA@(,aK\LF$COM	A	t(,aK^
DS$MEM	B`C
acZA@(,aK`LF$COM< <	A
	A*                                            aKbLF$COM	A,aKdLF$COM	A	A+,aKfLF$COM9 9	A,aKhLF$COM	A$(,aKjLF$COM	A
aclA@(,a
@BLF$COM-	t(: :,aG^
DS$MEMQjacnQ	@jA@	Q@A@
aclA@(Q@4acZA@()	A,N: :x	)-L
~yacZA@(Ra},aKfLF$COM	A,aKhLF$COM	A< <	A.f	A/bQ?acRA@	(t(,aGT	DS$MEMQjacp,a
@BLF$COM8 8Q	@jA@0	@DC,aK`LF$COM	A
		*,aKbLF$COM	A
		+ ; ;,aKjLF$COM	A
aclA@(,a
@BLF$COM	t(,aG^
DS$MEMQjacnQ	@jA@	Q@B; ;A@
aclA@(Q@B		/l	0A
acFA@17	acNA@a@,a
@BLF$COM: :<acZA@(n4	A,ag>LF$COMNacrA@A@	A,aS>LF$COMO7 7JQ	@ t(,aStDS$MEM,aSvDS$MEM,aK<LF$COM	A	(,aS<LF$COMd9 9,aK<LF$COM	2l	2A
	3,aKxLF$COM	(AD,aGzDS$MEMQj,aKxLF$COM	29 9	AD,aGzDS$MEMQlac|Q	@jQ	@l,a
@~LF$COM	A4,aK                                                                            F$COM	A
	4A4	4A
9 9	t2,aKtDS$MEM	2	t2,aKvDS$MEM	2mo	4A
	(t3,aStDS$MEM8 8!	(t3,aSvDS$MEM&hZ	@ ,aS\LF$COM,aSLF$COM,aSHLF$COM9 9,aS	LF$COM,aS
LF$COM,aSjLF$COM,aSLLF$COM,aSLF$COM,aSbLF$COM,aSdLF$COM; ;,aS
LF$COM,aS                                                                            F$COM,aSfLF$COM,aSLF$COM,aS`LF$COM,aShLF$COM	aca@,Q@9 9A@	%YacQ@a@6	A
X`	@ ,aSLF$COMa	A,aSLF$COMe9 9	A,aSXLF$COM		,aSxLF$COM		,aS~LF$COM	A#	(#@tac@A@#Q@A@	%: :Q	%           		5	(5@
	t5QK	A
	%	%9 9	t5QK	A
QK	CC,aS                                                                            F$COM	(5@A6                           (	@ 6*		7	6 6	8t5QK	9	A,aS\LF$COM	A,aSLF$COM9	A,aSHLF$COM=	A; ;,aSjLF$COMA	A,aSLF$COME	A,aS
LF$COM,aS
LF$COM,aSLF$COM,aSLF$COM; ;,aS	LF$COM,aS`LF$COM,aSbLF$COMI	A,aSLF$COM		7	8Y	A,aShLF$COMa< <	A,aSbLF$COM		7	8e	A,aS
LF$COM		7A8m	A,aSdLF$COMu	A,aS                                                                            F$COM9 9y	A,aSfLF$COM	(5@	acQ@A@5,aSXLF$COM	5@H5}	A,aS
LF$COM	A: :,aS	LF$COM	A,aSLLF$COM	A,aS`LF$COM		785	9:L6:5 5(>(B+-./FJZbfnvz~0!	6A
	7; ;,aSxLF$COM	8,aS~LF$COM@)u,aKXLF$COM	A			,aSXLF$COML9 9,         t(,aKDS$MEM	C,aG^
DS$MEMQj,aGDS$MEMQl,aGDS$MEM: :QnacQ	@jA@	Q	@lQ	@nA@%	%A
	@ ;(AD	,aSDS$MEM,aSDS$MEM	A;%: :uusX	@ ;(AD	,aSDS$MEM,aSDS$MEM	A;%Q
: :	t(,aG^
DS$MEMQjacA@Q	@jA@	A@<A@=A@>	>A	t(,aG DS$MEMQj	=5 5	?#ac"A@<A@?Q	@jacA@A@A@A@<A@=A@>*	@ t(,aS DS$MEM9 9,aS$DS$MEMIi,aK<LF$COM	A
,aKjLF$COM	A
,aKDLF$COM	B: :	@,aKDLF$COM	A,awDLF$COM,aK&LF$COM	%ia		t@,aS&LF$COM	(@@h9 9Y	A@oac(,a
@<LF$COM,a
@BLF$COMA@@UQac*	+L!}; ;m	'LDQPI@+RP	*LzjY	/Lm: :5!  !q!u!}!!!!!!!9 9!!!!	 !*!
A!f!
!        -!.!/!\9 9!`!!@!}!!$LF$COM!$LF$COM!l$LF$COM!t$LF$COM!Z9 9$LF$COM!X$LF$COM!x$LF$COM!$LF$COM!d$LF$COM! $	LF$COM!"$
LF$COM!$LF$COM!h9 9$LF$COM!$$LF$COM!$LF$COM!~$LF$COM!&$LF$COM!$                                                                            F$COM!.$LF$COM!$LF$COM!(9 9$LF$COM!|$LF$COM!$LF$COM!`$LF$COM!B$LF$COM!^$LF$COM!$DS$MEM!$DS$MEM!9 9$DS$MEM!<$DS$MEM!@$DS$MEM!4$DS$MEM!6$DS$MEM!p$	DS$MEM!z$
DS$MEM!2$DS$MEM!\: :#GETARG!f#FOLLOW!r#TSCAN$!#FINFO$!#COMPA0!*#EXPAND!,#EQUAL !0#CTOI!n#DSGET !V#DSINIT9 9!b#AT$HOM!j#PRINT !v#DSFREE!#PUTEN0!
#UPKFN$!#PUTCH !8#GPAS$$!:#SRCH$$!>#FSIZE !D
 
#PRINU0!F#SWT 
 
"%2B0&!$ COMPA0: :	@ "A#@HADQK	M@ Q
QK	M@ Q
	@"A
	A#	Qg	" 		
 
"%0$0&& FSIZE 9 9	@QSQK	%		%acA@Q	@A@"A@#A@$	$A	#C?9 9	MQSQK	C#AQ
acA@Q	@Q@
A@A@A@A@A@$: :	$A
'&AQ
acA@Q	@Q@
A@G@8A@A@$	$A
A@	$%\9 9		[QK	C,AQ
acA@Q	@Q@
A@A@Q	@A@A@$QKAQS: :aAQ
acA@Q	@Q@
A@Q	@A@A@$~!		!!!!' '!!{P !#SGDR$$!#RDEN$$!#PRWF$$
 
"%2&0&O $ PRINU07 7}DS$MEMLF$COM	Qw,aGDS$MEMQ
QK
	A
acQ	@
Q	@Q	@
Qw; ;,aG
DS$MEMQ
QK	@HADQGQ		Q_	"acQ	@
A@Q	@A@"acQ	@Q	@: :Qw,aGDS$MEMQQK	A
acQ	@Q	@Q	@>acQ	@	@ QS		! 6 6O!O!#PRINU0!$DS$MEM!$DS$MEM!$
DS$MEM!#UPKFN$!#PUTEN0!#DSFREE
 
"%2$0&iZ0 PUTEN09 9}DS$MEMLF$COM"spc "sam "dam ""sgs "(sgd9 9 ".ufd "4act ":??? "@   /   "H*2,,0: :u*i/*i/*i *i:*i:*i "b*7,6h"h*7,6h"n*8l "t< <sys "zn-1 "n+1 "n+n "|  	A",aK
LF$COM; ;	A
Qw,aKDS$MEM	3aca@A@Q@A@"Qw,aKDS$MEM	#; ;9aca@A@Q@A@"aca@A@Q@A@")aca@"A@Q@A@"4aca@(; ;-A@Q@A@"?aca@.A@Q@A@"Jaca@4A@Q@A@"U	#B$L9 9*5@KVkaca@:A@Q@A@"`	"",aKLF$COM	A
ac9 9a@@A@Q@A@"Qw,aKDS$MEM	%"@D&%C		t&QS	%7		t&9 9QS	&@H&	%6		t&QS	&@H&&	%5		t&QS0	"&%C9 9		t&QS<	%=		t&QS	(&@D	%>		t&QS	(&@M	%?		t&9 9QSVA		t"QS	"	"},aKLF$COM	A
Qw,aKDS$MEM	%,aKDS$MEM	'9 9	t"QGQl	'M=
@C>('M=
M=@)'M=*%A7+%,%A;
-ac Q	@lA@a@HA@-A@,; ;A@+A@*A@)A@(	""e,aK"LF$COM	A
	t"	QGQlQw,aG$DS$MEMQnac ; ;Q	@lA@	a@bQ	@n	""',aK&LF$COM	A
	t"	QGQlQw,aG(DS$MEMQnac ; ;Q	@lA@	a@hQ	@n	""B,aK*LF$COM	A
	t"	QGQlQw,aG,DS$MEMQnac : :Q	@lA@a@nQ	@n	""],aK.LF$COM	A
Qw,aKDS$MEM	.aca@tA@9 9*Q@A@"aca@zA@Q@A@"
aca@A@Q@A@"	.A
	%           ': :	%*aca@A@Q@A@" 	""x,aK0	LF$COM	A
Qw,aKDS$MEM9 9	1		t"QS@		t"QSEQw,aKDS$MEM	2		t"QSO		t"9 9QST		t"QS	"":	@ t"	QSac2Q	@	"",aK4LF$COM	A,aK6LF$COM: :	A
	A&	(&@t	&,ag8LF$COMzac:a@A@u{ac:Q@A@ac:8 8Q	@A@ac<A@A@q,aK>LF$COM	%	/M=@@H/A/"@H%	@9 9,aK>LF$COM	$/-ac<A@A@,ak>LF$COM**.(	ac<A@A@	A9 9,aS>LF$COM9ac:Q@A@ac:Q	@A@	"@H,a[>LF$COM,aS>LF$COMm9 9ac:Q@A@ac:Q	@A@ac<A@A@U		!ui!i!!i!9 9!	i!
i!i!
i!i!!<!Ni!
! i9 9!ai!di!mi!ri!ti!wi!!        !!!6 6i!R$LF$COM!X$LF$COM!N$LF$COM!J$	LF$COM!*$
LF$COM!H$LF$COM!<$LF$COM!09 9$LF$COM!P$LF$COM!4$LF$COM!D$LF$COM!@$LF$COM!F$DS$MEM!>$DS$MEM!B$DS$MEM!29 9$DS$MEM!,$DS$MEM!6$DS$MEM!8$DS$MEM!.#SCOPY !:#ENCODE!L#LENGTH!T#PUTLIN!V#PUTCH 
 
"% 00&