o>&9 9"=varsdir=/"u.logac"a@A@Q@A@	B"t"QGQ		9 9	"#ac$A@Q	@A@#	BCac"a@A@Q@A@"	ac&Q@A@	$C: :ac(Q@2		*n*n*s  *s  *s*n. 7!ac*A@$ac,A@Q@ac,A@Q@zac,A@Q@
: :$ac.A@$C@8Q@zQ@Q@
ac0A@A@$ac2A@$ac4!v!}o!!!; ;!o!fo!.#OPEN!,#GETARG!*#SCOPY !0#CANT!2#WIND!4#DATE!6#PRINT !8#FCOPY  !:#CLOSE !<#SWT 
 
"%,&0&