V2&: :}DS$MEMRCMACROuCLOOK CDEFIO"v"t"s"u"r"9 9q"p"o" [-e]"&Usage: macro [-e]"8d: :efine"@incr"Fsubstr"Nifelse"Vincl"\d9 9ivert"ddnl"h	undefine"r()	acva@ Q@	C7 7acxa@&	@ ,aSzCDEFIO,aS|CLOOK ac~A@	A,aSuCDEFIO		,awuCDEFIO; ;,aSuCDEFIO	A,aSCDEFIO		,awCDEFIO,aSCDEFIOaca@8a@aca@@a@ac7 73a@Fa@aca@Na@aca@Va@aca@\a@aca@da@aca@ha@	@ : :,aS
CMACRO	A",aSCMACRO	acQ@dA@	#acQ@dA@	#d	#%p	8 8	CacQ@dQ@@	A
acQ@dz	
call stack overflow.,ak
CMACRO	@	< <,ag
CMACRO
acxC@	",aw
CMACROQS+ac,a
@CMACROQ@HA@"	"ac; ;Q@@acA@ac,a
@CMACROQ@HA@"	"acQ@dacA@ac,a
@CMACROQ@H: :A@"	"	acQ@dA@	#acQ@d	#%	
Vaca@rU	@ ,aw
CMACROQSO9 9r	#
C	A$	acQ@dA@	#
C	($qo	#C	$@H$A8 8{v	EOF in string.~	#BCacxC@	}racQ@df|c8 8,aK
CMACRO	A
acQ@d	#	C,aw
CMACROQKO	AacQ@d&9 9,aw
CMACROQkO/ 	#C,aw
CMACROQKO	@HQSO	A
acQ@d9 9=acA@,aw
CMACROQG+QJ	"@H%acQ@HQ	@JA@%,aw
CMACROQK+	"t"9 9QKG,aSCMACRO,aK
CMACRO	@H,aS
CMACROB4	#C,aw
CMACROQKO; ;	@HCkacA@ac,a
@CMACROQ@HA@"	"r	#CQ	A
acA@#: :acA@#acQ@d g0_eo	unexpected EOF. ,aK
CMACRO	A
8 8acxC@#,aKCDEFIO	@H,aSCDEFIO(	A,agCDEFIO1,awCDEFIO; ;,aGCDEFIOQJacQ	@J)2,aKuCDEFIO	@H,aSuCDEFIO>	A,aguCDEFIO: :G,awuCDEFIO,aGuCDEFIOQJacQ	@J?Hac !V!u!v!}!9 9!V!V!fV!	(!)!,V!@V!
[!]V!}!
9 9$CDEFIO!$uCDEFIO!$uCDEFIO!$CDEFIO!$CDEFIO!$CLOOK !$CMACRO!$CMACRO!: :#GETTOK! #LOOKUP!$#PUSH!#PARSCL!#ERROR !#DSINIT!#INSTAL!"#PUTTOK!&#PUTCHR!(#PBSTR  !*#EVAL!,#NGETC !.#CLOSE !0#SWT 
 
"%r&0&R& GETTOK: :	A"	("@	"Qg		@HADQGQacQ	@	#acA@#	$%	%9 9!	%$ 
#$	token too long. &QK	$"	@acC@'2	": :	%=;	@HADQGQacQ	@	"@H"	$<	@ t"QS	$	!R!R!" "0!_!a!#NGETC !#TYPE!#ERROR !#PUTBAK
 
"%.&0&D( LOOKUP: :}DS$MEMRCMACROuCLOOK CDEFIO	,aKCLOOK 	"	"@H"	"A	t",aKCLOOK 9 9	#A$	($@         $@H%t%QK	t#,agDS$MEM 	A
	(#!	$@H%9 9	t%QK	t#,a_DS$MEM	C	#B%ac,a
@DS$MEM	A@%Q	@A@	A&	// /
	@ &	!D!$CLOOK !$CLOOK !$DS$MEM!$DS$MEM!#SCOPY 
 
"%.(0&S&& INSTAL; ;}DS$MEMRCMACROuCLOOK CDEFIO	: too many definitions. acQ	@		,agCLOOK 5 5	@acQ	@A@acC@		acQ	@	B"acQ	@	"B#acA@#	$9 9,akCLOOK 	@,awCLOOK ,aSCLOOK 	acQ	@A@,a
@ DS$MEMA@$	"$#ac8 8Q	@A@,a
@ DS$MEMA@#		!qS!S!tS!$CLOOK ! $CLOOK !$* *$DS$MEM!#LENGTH!#DSGET !#UNINS0!#PUTLIN!#REMARK!"#SCOPY 
 
"%,&0&

"$ PUSH: :	
arg stack overflow. 		QgacC@QK	@HAD	QKQSQK	B"	!	 	d!#ERROR 
 
"%.$0&$ PUTTOK2 2	A"	("@	"@HAD	QGQQK	A

acQ	@		!#PUTCHR
 
"%*$0&3 " PUTCHR9 9RCMACROuCLOOK CDEFIO	,aKCMACRO	A,awCDEFIO,aGCDEFIO	QacQ	@6 6Q	@	evaluation stack overflow.		,agCMACRO
#acC@$QK: :,awCMACRO,aSCMACRO,akCMACRO	@         	!P!$CDEFIO!$CDEFIO!$CMACRO! $CMACRO!$CMACRO!#PUTCH !#ERROR 
 
"%("0&

H:* EVAL: :RCMACROuCLOOK CDEFIO"0123456789	QK	@HADQK	"t",aKCMACRO	#: :8acQ	@Q	@Q	@ac Q	@Q	@Q	@ac"Q	@Q	@Q	@ac$Q	@Q	@Q	@9 91'ac&Q	@Q	@Q	@0ac(Q	@Q	@Q	@9ac*Bac,Q	@Q	@Q	@E	#$9 9	L	FC:1(	t",aGCMACRO	Q
ac.Q	@
	"@H%	%@H%h	"9 9	$%n	t%,aK0CMACRO	%v,aGCMACROQ
ac2Q	@
u	t%,aKCMACRO: :	Cac2A@	%@H%	t%,aGCMACROQ
ac4a@Q	@
	@H&AQKQ_9 9	&C	&Q[	B'@HADQK	(t(,aGCMACRO	Q
ac6Q	@
"	%@H%~io6 6	%"C	t%,aGCMACRO	Q
ac2Q	@
=N		!H!$H!2$CMACRO!; ;$CMACRO!6#INDEX !0#LENGTH! #DODEF !"#DOINCR!$#DOSUB !&#DOIF!(#DOINC0!*#DODIV0!,#DODNL  !.#DOUND0!4#PUTBAK!8#PBSTR 
 
"%6*0&'$ DODEF 9 9RCMACROuCLOOK CDEFIO	QKQ_	@HCQK	BADQK	"QK	@DADQK	#t"5 5,aGCMACROQ
	t#,aGCMACROQacQ	@
Q	@		!$CMACRO!#INSTAL
 
"%2$0&$ DOINCR9 9RCMACROuCLOOK CDEFIO	QK	BADQK	"ac,a
@CMACROA@"	B#acA@# 		!$CMACRO!#CTOI!#PBNUM 
 
"%.$0& $ PBNUM 9 9"0123456789	QK	""M=@#t#aGQacQ	@	"M="A		! 
!#PUTBAK
 
"%*$0&k & DOSUB : :RCMACROuCLOOK CDEFIO	QKQ_	%		QKQ_	%		": :QK	ADQK	#ac,a
@CMACROA@#	"QK	@DADQK	#QK	BADQK9 9	$ac,a
@CMACROA@#	$@H%$C	t$,aGCMACRO	Q
acQ	@
	$%C:	t%; ;,aGCMACROQ
acQ	@
acA@"	%@H#	#@H#X	%$#	@t#,aGCMACROQ
: :acQ	@
Y^G		!!k!fk!$CMACRO!$CMACRO!#CTOI!#LENGTH! #F$MI11!#PUTBAK
 
"%2&0&

L& DOIF< <RCMACROuCLOOK CDEFIO	QKQ_	%		QK	BADQK	"QK	@DADQK; ;	#QK	ADQK	$QK	ADQK	%t",aGCMACROQ
	t#,aGCMACROQac: :Q	@
Q	@	@HC	t$,aGCMACROQacQ	@7	t%,aGCMACRO	Q
acQ	@
& &A		!!!L!$CMACRO!#EQUAL !#PBSTR 
 
"%4&0&I$ NGETC 9 9RCMACROuCLOOK CDEFIO	,aKCDEFIO	A,awCDEFIO,aKCDEFIOQS	A6 6,aSCDEFIO,awuCDEFIO,aGuCDEFIOQacQ	@Q	@,awCDEFIO,aSCDEFIO9 9,aKuCDEFIO	%$QK	BC#(),awuCDEFIO,aGuCDEFIOQac: :Q	@,aKuCDEFIO	@H,aSuCDEFIO*QK	%@,aKCDEFIO	@H,aSCDEFIO: :?QK	"	!I!I!$CDEFIO!$CDEFIO!$uCDEFIO!$uCDEFIO!#GETCH ! #CLOSE 
 
"%*$0&$ PBSTR 9 9	acQ	@	"	"@H"	"A	@HADQGQacQ	@		!#LENGTH! #PUTBAK
 
"%*$0&%" PUTBAK9 9RCMACROuCLOOK CDEFIO	too many characters pushed back.,akCDEFIO	@	,agCDEFIO: :
acC@QK,awCDEFIO,aSCDEFIO		!t%!$CDEFIO!$CDEFIO! #ERROR 
 
"%&"0&? $ DOINC0: :RCMACROuCLOOK CDEFIO	QKQ_	%			: can't open include. 	QK	B9 9	ADQK	"t",aGCMACROQ
acQ	@
A@	#CacQ	@
A@acC@
*6 6,akuCDEFIO	@#,awuCDEFIO,aSuCDEFIO5		!q!}?!!?!% %$uCDEFIO!$uCDEFIO!$CMACRO!#OPEN!#PUTLIN!#REMARK
 
"%0$0&&$ DODIV0: :RCMACROuCLOOK CDEFIO	QK	BADQK	"t",aKCMACRO	A	A,agCDEFIO: :,awCDEFIO,aGCDEFIO	Q
acQ	@
,aKCDEFIO	@H,aSCDEFIO         		: : :too many output files."		,agCDEFIO	@t",aGCMACROQ
acQ	@
A@acC@#: :		2QKQ_	@HC	t",aGCMACROQ
acQ	@
A@	#J	t",aGCMACRO; ;Q
acQ	@
A@	#W	: can't open for output.d	#C	t",aGCMACROQ
ac: :Q	@
A@acC@etac A@#,akCDEFIO	@#,awCDEFIO,aSCDEFIO		!9 9q!}!!
!$CDEFIO!$CDEFIO!$CMACRO!"#OPEN! #CREATE!#CLOSE  !#PUTLIN!#REMARK!$#WIND
 
"%0$0&$ DODNL : :acA@"	"%	%	%
acA@"		!	!
! !#NGETC  !#PUTBAK
 
"%$$0&>& UNINS0: :RCMACROuCLOOK CDEFIO}DS$MEM	,aKCLOOK 	"	"@H"	"A	t",aGCLOOK : :QQK	#t#,aGDS$MEMQacQ	@Q	@	@HCacQ	@	"B$	($@(	$: :,agCLOOK 	@t$,aKCLOOK ,aSCLOOK ).,aKCLOOK 	@H,aSCLOOK 		 0 0
		!$DS$MEM!$CLOOK !$CLOOK !$CLOOK !#EQUAL !#DSFREE
 
"%.&0&$ DOUND06 6RCMACROuCLOOK CDEFIO	QK	BADQK	"t",aGCMACRO	Q
acQ	@
		! $CMACRO!#UNINS0
 
"%0$0&