v&9 9"p"$Usage:  mail [ -p ] { <user name> }"6*s:  9 9addressee unknown*n"Pcan't create temporary file9 9	acla@Q@	Cacna@acpA@Q@HA@	BCQ	A
"acrA@": :	A#	(#@#acpA@#Q@HA@	%
1actQ@H	CacvA@a@6: :Q@Hacx7$0aczA@	$Cacna@PJ	ac|A@A@$	A#	(#@W9 9acpA@#Q@HA@	%eac~A@$acA@$Q@HXdacA@$ acx!q9 9!v!}!v!v!v!fv!x#GETARG!#MKTEMP!|#VFYUSR!t#PARSCL0 0!v#ERROR !z#RECEI0!~#PRINT !#SWT !#FCOPY !#REWIND!#SENDM0!
#RMTEMP
 
"%T&0&np& RECEI09 9"=mail=/=user="=mailfile="*[*i] more? "6[9 9END] ">Save mail (y) ? 		acPa@A@	"%QK	@H; ;	CacRA@"A@acTA@"a@*a@6A@A@A@acVA@a@>acXQ@: :A@	%4Q	CB#Q		CB#A3?acZA@"acPa@A@
	$C9 9ac\A@"ac^a@Nac`A@$acRA@"A@$ac\A@$@ac\A@"acba@
		9 9!q!r!u!}!n!!!
n!n!Nn!	nn!\7 7#OPEN!d#GETLIN!^#FCOPY !`#PAGE!b#PRINT !f#REWIND!h#CLOSE !j#CANT!l#WIND!n#REMOVE
 
"%&0&Pr$ SENDM09 9"=user="
=mail=/*s""can't open *s's mailbox*n: :"<*n*nFrom *s at *s on *s:*n*n	acZa@Q@NA@ac\A@9 9Q@ac\A@Q@p	@ Quac^Q@&A@a@Q	@ac`Q@&A@	"CacbA@: :a@"Q	@		+'acdA@"acbA@"a@<Q@NQ@pQ@acfQ	@A@"achA@"		!q9 9!}P!!P!P!!!(P!h#OPEN!b#EXPAND!d#DATE!f#ENCODE!j #PRINT !l#WIND!n#FCOPY !p#CLOSE 
 
"%$0&