d(9 9(MT$BUF MT$COM"+Usage: mt [<unit>] [-p <pos>] [-(r|w) [-b <9 9#block>] [-c <conv>] {<file>}] [-v]"^p<rs>b<rs>c<rs>9 9
n<ign>rwv"x*i recovered i/o errors" (*i CRC co9 9rrections)ac&,a
@(MT$COM	Cac*a@ac,A@"	C	A#9 9           	ac.a@^Q@	Cac*a@Q         A
Q	A
%ac*a@)	@ ; ;,aS0MT$COM		,aS2MT$COM		,aS4MT$COM	@ ,aS6MT$COM,aS8MT$COM,aS:MT$COMQ5 5	A
	A,aS:MT$COMAQ	A
Q	ADQGQHac<Q	@H,a
@2MT$COM: :,a
@4MT$COM	CH		#ZQ	A
Q	ADQGQHac>Q	@H,a
@0MT$COM9 9	Ca		#]q	A,ag0MT$COM{x,a[4MT$COM	M=,aS4MT$COMzac@9 9,a
@0MT$COM,a
@2MT$COM,a
@4MT$COM	C		#tQ	A
Q)	ADQG: :QHacBQ	@HA@$A@%A@&	%'acDA@$A@%A@&	%2&1		#29 9,aGFMT$BUF,aSHMT$COM,aGJMT$BUF,aSLMT$COMQ         A
acNA@	"A: :Q	A
acNA@	"KG	"C		#5T,aK8MT$COM	A
acPA@	a@x9 9,a
@8MT$COM,aK6MT$COM	A
acPA@	a@,a
@6MT$COMg	acRA@
A@	[acT9 9W	acVA@acT	#L^u6X~!	q!}!!!!8 8!!!P!

! !h!T$MT$COM!X$MT$COM!R$MT$BUF!V9 9$MT$BUF!<$MT$COM!@$MT$COM!>$MT$COM!B$MT$COM!D$MT$COM!4$MT$COM!F$MT$COM!H; ;#BLKSP0!J#CONVS0!L#CHECK0!8#CHECL0!N#POSSP0!P#POSIT0!Z#READW0!2#UNITS0!:#PARSCL!6#ERROR  !\#PRINT !^#PUTCH !`#SWT !b#SETERR
 
"%r(0&$ ASCII09 9"57-./%<=2&?'@Z{[lP}M]\Nk`Kapqrst9 97uvwxyz^L~no|ABCDEFGHIQRSTUVWXYbcdefghiJ`O_my	9 9"#$%&'()@jP!	A"@H#t#QK	ADaK	t#QS	A"Qg 		!
 
"%*$0&:F$ BLKSP0< <".syntax:  -b <record size>[/<blocking factor>]	A"ac>; ;	Q	@A@"QS	"@HADQK	%	%	("@ac>Q	@A@"Q{	@QS: :QKQS$	"@HADQK	A
ac@a@		#	/		#	!}!~:!. !/:!B#CTOI!D#REMARK
 
"%.$0&!:& CHECK0; ;"!maximum block size is *i bytes*n	QK	@HC		"	#9 9		"#
	"Qgac2A@a@A@#		$			$	!q!}!~!!                                        !!(!8#PRINT 
 
"%0&0&eL$ POSSP0< <"0syntax:  -p [+|-]<file number>[/<block number>]	QK9 9	%	%	QK	C	AQS		QS		"		@ 9 9QS	A"ac@Q	@A@"QS	AQK	A'	AQS+	"@HADQK	%79 9	%:69	("@ac@Q	@A@"QS	:	@ QS	EQK		AQK	A9 9L	AQS	P	"@HADQK	A
acBa@		#	Z		#	!}!~!e!" "e!+!-!.!/e!H#CTOI!J#REMARK
 
"%0$0&*4$ CHECL0: :(MT$BUF MT$COM"units are *i to *i*n	@ QSac&A@a@A@: :A@		"	,aK(MT$COM	A	%	@ac*Q	@	#ac,A@#	%'; ;		"	!q!}!~*!*!*!.$MT$COM!2#MTSCH0!0#MTSTAT!,#PRINT 
 
"%($0&/D& CONVS0: :",syntax:  -c (a[scii] | b[inary] | e[bcdic])	QK	": :	@ QS	AQS		QS	"#L
		"#L9 9	"#ac<a@		$			$	!}!~/!/!@/!`/ !B#REMARK
 
"%,&0&$ EBCDI09 9"5?	??????????????
?????????9 97??????? ?????????[.<(+]&?????????!$*);^-/????????|,9 97%_>??????????`:#@'="?abcdefghi???????jklmnopqr???????~s9 97tuvwxyz??????????????????????{ABCDEFGHI??????}JKLMNOPQR; ;&??????\?STUVWXYZ??????0123456789??????	A"@H#t#QK	ADaK 	t#QS	A"	Qg		
 
"%*$0&.60 GETBUF: :(MT$BUF MT$COM	,aKMT$COM	@HCQK	"ac,a
@MT$BUF,a
@MT$COMQ	@6 6	#A			$		#,agMT$COM	B#@ t#,aSMT$BUF,aKMT$COM9 9,aSMT$COMac,a
@MT$BUF,a
@MT$COMQ	@	#A			$	3	#,agMT$COM9 9:	B#@ t#,aSMT$BUF7;,aKMT$COM,aS MT$COM(		"L
)G; ;QK	%	@ &,aK"MT$COM	&&T	&,agMT$COM\	t&,aGMT$BUF9 9Qac$Q	@Q	@,a
@"MT$COM	BC]mUn	&A		$	r,aKMT$COM: :	'		(A)t),aKMT$BUF	,aSMT$BUF	A)$&
}}		(ac&,a
@MT$BUF9 9A@&
y	'B*Lz	&,agMT$COM	B&(t&,aSMT$BUF: : ,aKMT$COM,aSMT$COM	@ &,aK"MT$COM	&&/	&,agMT$COM7	t&9 9,aGMT$BUFQac$Q	@Q	@,a
@"MT$COM	BC8H0I	&A		$	M: :,aKMT$COM	+		(A)t),aKMT$BUF	,aSMT$BUF	A)$&eXX		(ac&6 6,a
@MT$BUFA@&eT	+B,LUfun	&,agMT$COMz	B&(t&< <,aSMT$BUFw{,aKMT$COM,aS MT$COM,Q	%LR-MQ7,aG(~MT$COM: :QQw,aG*MT$COMQac,A@A@Q	@Q	@A@A@-A@.		$	!~!,5 5!!,! !@!,$!0$~MT$COM! $MT$BUF!$MT$BUF!&9 9$MT$BUF!$$MT$BUF!2$MT$COM!"$MT$COM!($MT$COM!$MT$COM!$MT$COM!*$MT$COM! #READF !,#READLN!.#ASCII0!4#PRWF$$
 
"%:00&:$ MTSCH0; ;"drive is off line""drive is not ready	ac6a@6 6
ac6a@"		"	QK	9	8		"	!}!~!8#REMARK
 
"%($0&
( MTCHE09 9(MT$BUF MT$COM"Block *5,-10i:"  Unrecovered". VPE9 9"4 RUN": CRC"@ LRC"F DMA"L UNC"R : :RAW	QK	C="t",aGX|MT$COM	Q
acZQ	@
	t",aK\}MT$COM	QSac^Q	@	7 7	C		#	QK	A	AQw,aS`MT$COMQK	C=AD,aKb~MT$COMQw9 9,aSdMT$COM		#	!	@ $A%acfA@	A&	A%%E77	A%	acfA@ach: :Q	@	<acfA@acfA@P		&>	A%%	bFFQK	@HC	A$	&[9 9f	acjA@a@,a
@lMT$COM	A'acna@ 	@ Qw,aS`MT$COM		#	vQK9 9	0acpa@.A@QK	1acpa@4A@QK	2acpa@:A@; ;QK	3acpa@@A@$QK	4acpa@FA@.QK	5acpa@LA@< <8QK	6acpa@RA@BkacrQ	@Q	@A@$QK	C="t",aGX|MT$COMQ
: :acZQ	@
	t",aK\}MT$COM	QSac^Q	@	C		#	jQK	A,aktMT$COM5 5	@$A
,akvMT$COM	@x	AQw,aS`MT$COMQK	C=AD,aKb~MT$COMQw9 9,aSdMT$COM		#	r	&L?\lIw!~!q!}!~!7 7!!!!
!b$|MT$COM!f$}MT$COM!l$~MT$COM!n$MT$COM!j9 9$MT$COM!v$MT$COM!$MT$COM!~$MT$COM!h#MTSCH0!r#MTSTAT!d#MTWAIT!p#MTSKI0!t#PRINT  !x#REMARK!z#PUTLIN!|#MTIO
 
"%4(0&


I"& MTIO: :(MT$BUF MT$COM	QK	"		#,aKMT$COM	@HC		$		$QK	A
: :	$$Qw,aKMT$COM	#,aKMT$COM	@HC		$"		$%: :	"L(Q7,aG~MT$COMQ
QK	C=AD,aG|MT$COMQac,a
@MT$COM8 8Q	@
A@#A@$Q	@		!!!D!D!E!E!$~MT$COM!$|MT$COM! $MT$COM!$MT$COM! $MT$COM!#T$MT
 
"%4&0&M$& MTREAD: :(MT$BUF MT$COM	A,aSMT$COM	"acA@A@"A@acA@A@"A@#	%	#; ;	7acA@#	$		#:acA@#	C*	acacA@#	"%ac9 9A@A@%A@acA@"Q	@	"",akMT$COM+		$	!}M!M!9 9M!!$MT$COM!#ONEOFR!#ONEOVR!#MTCHE0!#MTIO!#MTREW0! #NEWRE0!"#PUTBUF
 
"%*&0&" MTREW0: :(MT$BUF MT$COM	AQac,a
@MT$COMQ@A@A@a@		!                                                                    $MT$COM!#T$MT
 
"%$"0& $ MTSKJ0: :(MT$BUF MT$COM	QK	@HC		"		"	AQac,a
@MT$COMQ@' '	A@A@"a@		!!$@!$!$MT$COM!#T$MT
 
"%*$0& $ MTSKI0: :(MT$BUF MT$COM	QK	BC		"		"	AQac,a
@MT$COMQ@' '	A@A@"a@		!!d@!d!$MT$COM!#T$MT
 
"%*$0&) $ MTSTAT: :(MT$BUF MT$COM		AQac,a
@MT$COMQ@A@A@a@a         ;acac: :,a
@MT$COMQ@A@A@a@aQS	"	!!)!$MT$COM!#T$MT! #MTREW0
 
"%*$0&$ MTWAIT 	QK	A

acA@"		!#MTSTAT
 
"%($0&e&( MTWRI09 9(MT$BUF MT$COM	A,aSMT$COM	"	acA@"Q	@	##%acA@A@"A@	"9 9	$	acA@$Q	@	#acA@A@"A@%	C		&	,	%:	#BCac9 9A@%	C6=acA@%	%F>E		&	Fac	#%
PacA@: :O		&	T2	"",akMT$COMacA@%	&	!}!~!e!9 9!e!!$MT$COM!#GETBUF!#MTCHE0!#ONEOFW! #ONEOVW!#MTIO!"#MTREW0!$ #NEWRE0
 
"%,(0&" MTFMA08 8(MT$BUF MT$COM	AQac,a
@MT$COMQ@A@A@a@		!                                 $! $MT$COM!#T$MT
 
"%$"0&>j$ NEWRE09 9(MT$BUF MT$COM"	unit: *i"tape is at end of reel"2t: :ape is write protected"Jtape is in mid file	ac^9 9A@a@,a
@`MT$COM	BCacba@acba@2acba@J9 9acdA@"	%%	":QK	@HC	"=,/QK	@HC	"A5; ;9;		!v!}>!>!d$MT$COM!b#INPUT !h#CHECL0!f#REMARK
 
"%($0&$ ONEOFR 	@ QS		"	!~
 
"%($0&#$ ONEOFW; ;	acacacQ	@	"acA@"	C		#	acA@acQ	@	"acA@"& &	#	!}!#!#MTSTAT!#MTSCH0!#MTFMA0!#MTSKJ0
 
"%($0&$ ONEOVR 	@ QS		"	!~
 
"%($0&$ ONEOVW. .	acacacQ	@	"acA@"	#	!#MTSCH0!#MTSTAT!#MTFMA0
 
"%($0&]( POSIT09 9(MT$BUF MT$COM"end of tape"end of tape"(	end of fi: :le"4end of tape"@end of tape"Lend of file9 9"Xbeginning of tape"jbeginning of tape"|beginni: :ng of file	QK	"ac	A#	(#@		#QgacA@$	%9 9acA@%	C		&		$:aca@		&	"acA@
	A#	(#; ;	@1	#Qg7acA@$	%acA@%	C		&	Daca@aca@(: :MR		&	H	$:I	A$#[	$7\N_acA@28	A#	(#9 9	@i	#Qg	@acA@$	%acA@%	C		&	|	$:aca@4		9 9	&	acA@jo	A#	(#@         #Qg	@acA@$	%acA@%	C9 9		&	$aca@@aca@L-2		&	(	$:)	A$#;	$7<9 9.?acA@fQK	AQK	A
JNacA@O	A#	(#9 9	@V	#Qg	@acA@$	%acA@%	C		&	i	$<aca@X		: :	&	oacA@W\QK	AacA@$	<
acA@	A#	(#@: :	#Qg	@acA@$	%acA@%	C		&	 aca@jaca@|)9 9.		&	$	$<%	A$#7	$78*;acA@
F	"@D'L: :GgBacA@$	%acA@%	C		&	V		&	!}!~!]!) )]!#MTSTAT!#MTSCH0!#MTREW0!#REMARK!#MTSKJ0!#MTSKI0
 
"%2(0&N(& PUTBUF: :(MT$BUF MT$COM	,aKMT$COM	@HCQK	"ac,a
@MT$BUF,a
@MT$COMQ	@9 9ac,a
@MT$BUF,a
@MT$COMQ	@		"L
QK	#5 5,aKMT$COM	A	A$	($@,	$,agMT$COM	@t$,aKMT$BUFA
9 9,aSMT$BUF-2)ac,a
@MT$BUF,a
@MT$COM<	@ $,aK MT$COM	$: :	$E,aK MT$COM	$,agMT$COM	@t$,aGMT$BUFQac"Q	@Q	@,a
@ MT$COM: :FO,aKMT$COM	$$ec	t$,aGMT$BUFQ,aKMT$COM	$%	ac"Q	@Q	@: :A@%d,aKMT$COM	A	A$	($@}	$,agMT$COM	@t$,aK$MT$BUF; ;A
,aS$MT$BUF~zac,a
@MT$BUF,a
@MT$COM	@ $,aK MT$COM; ;	$$,aK MT$COM	$,agMT$COM	@t$,aGMT$BUFQac"Q	@Q	@,a
@ MT$COM: : ,aKMT$COM	$$64	t$,aGMT$BUFQ,aKMT$COM	$%	ac"Q	@Q	@8 8A@%5v%	#L&wG!		!N!$MT$BUF!$MT$BUF!&$MT$BUF!4 4$MT$BUF!$MT$COM!$MT$COM!$MT$COM!"$MT$COM!#WRITEF! #EBCDI0!$#WRITE0
 
"%.&0&r>* READW09 9(MT$BUF MT$COM"tape is at end of reel"(tape is not wri9 9table">tape is in mid-file"R*s: bad file name*n9 9"f/dev/stdin1"r/dev/stdout1"/dev/stdin2: :"/dev/stdout2"/dev/stdin3"&/dev/stdout3"4*: :s: can't create*n"H*s: *i blocks read from tape*n9 9"h*s: can't open*n"z*s: *i blocks written to tape *9 9n	acA@"	:aca@	#	QK	@HCaca@(aca@>9 9	"=	A
         	$AQj	$%-ac Q@Q@j	%,9 9ac"A@a@RQ@		$QK	@HCac$a@rA@Q@A@ac$a@A@: :Q@A@Qac$a@&A@Q@A@\F	ac&Q@a@f	AGac&Q@a@	AR; ;	ac&Q@a@	A]g	ac(Q@A@	&C		$ac"A@a@4Q@	ac*: :A@&	$ac,A@&	A,ag.MT$COM$!,a_0MT$COM	A'ac"A@a@HQ@A@'; ;#E	ac2Q@A@	&Cac"A@a@hQ@		$<ac4A@&	$ac,: :A@&	A,ag.MT$COMWT,a_0MT$COM	A'ac"A@a@zQ@A@'VG2@4: :	%(L6A5e)5	$#!q!}!~r!!r!r: :!r!8$MT$COM!6$MT$COM!(#GFNARG!0#CREATE!:#OPEN!2#MTREAD!<#MTWRI0!$#MTSTAT!. #EQUAL !&#REMARK!*#PRINT !,#SCOPY !4#CLOSE 
 
"%*0&H$ READLN: :!	QK	B"acQ	@Q	@A@"	#	A
	#@HCQK	CacQ	@: :Q	@A@"	#	#%(%		'	#@HADQK	C	@ #@H#0	A6	#0 0Qg<	B#@HAD	QS9=	#	!H!
! H!#GETLIN
 
"%.$0&.$ UNITS09 9	acA@Q@A@	%Q	%    	A"acQ@A@"QS	t"QK	A
9 9		#	acA@	@ QS'		#	!}!~!.!.! !-!#CTOI!#GETARG!#DELARG
 
"%($0&,$ WRITE0< <	QK	"	"@H"	"A	@HADQK	%
           	t"QK	#@ QS1 1	acQ	@Q	@	#t"QSacA@Q	@		!
! !#PUTLIN!#PUTCH 
 
"%.$0&