SJ&9 9"p i"*Usage:  news [ -p ] { -i | <article no> }9 9">=news=/index"L=news=/articles/art*s"b=news=/d9 9elivery/=user="z=news=/delivery/=user="[*i] mo9 9re? "[END] 	ac&a@Q@	Cac(a@		can't open '=news=9 9/index'.Q	A
ac*a@>A@	"Cac(C@(	"#A$	A%; ;	(%@4	Article *s could not be found*n.7ac,A@%Q@HA@	%Sac.Q@.A@a@L; ;Q@Hac*Q@.A@	"Cac0A@C@8Q@Hf	"#	$1o5R	%@HC: :Q	Ayac*a@bA@	"%	#	$t	save news? .ac0A@C@ac2: :	Q@.A@Q.	%$	%	'#&ac4a@z'}ac6Q	A
ac89 9A@#A@
1ac:A@#a@a@A@A@
A@8ac<A@#K	$L2u: :L!q!r!
u!}!S!!!S!S!fS!	N: :S!nS!6#OPEN!8#GETARG!:#ENCODE!2#PARSCL!4#ERROR !<#PRINT !>#GETLIN!@#REMOVE!B #SWT !D#FCOPY !F#PAGE!H#CLOSE 
 
"%:&0&