| (9 9"=doc=/hist/history"$Usage: phist {-b <author> | -9 9f <date> | -s <subject> | -q}"`b<rs>f<rs>s<rs>i<rs>: :q	A"Q	A
Q"	ADQGQFacvQ	@FA@	#	acva@A@9 9	#	history file not available. 	#CacxC@/aczQ@HA@#QH	%?9 9	CaczQ@.A@#	%KAQ.	CJaczQ@A@#	%YOQ	C9 9X]	history file contains apocryphal information. _ac|A@#acxC@`^Q	A
9 9ac~Q@.A@Q@zA@acQ@zA@Q	A
ac~Q@A@Q@`A@ac9 9Q@`A@Q	A
acQ@`Q@z	A*2Q	A
acQ@HQ@H	A
: :73?Q	A
acQ@zQ@H	AD@LMacQ@HA@#N	*n9 9*sBy: *sRe: *s. VQ	A
acA@C@WQ@IQ@/Q@acQ@HA@#c	*2n*; ;	s*nBy: *sRe: *s*n.wacA@C@xQ@IQ@/Q@aczQ@HA@#QH	CacA@A@: :Q@IaczQ@HA@#vU:>ac|A@#	ac
a@`Q@	Cacxa@$9 97	: bad author pattern. <Q	A
Q	ADQGQFacQ	@FA@A@	Q@H	: :	CQ	ADQGQFacQ	@FA@
acxC@=_K	: bad date. qQ	A
	A: :	$Q	ADQGQFacQ	@FA@$A@%A@&A@'	CQ	ADQGQFacQ	@F: :	A@
acxC@r	&MQF	%MA;	AQJ	'MA;	A	QJQFQH{	: ; ;
bad subject pattern.;Q	A
Q,	ADQGQFacQ	@FA@A@	Q@z	CQ,: :	ADQGQFacQ	@FA@
acxC@<^J.acp!
q!u!}!9 9!	!!t!!!#!$!*t   *s.  ,d3'!#OPEN!; ;#READB0!#MATCH !#MAKPAT!#PARSDT!#PRECE0!#PARSCL!#ERROR !#CLOSE !
#SCOPY !#MAPSTR !#SKIPE0!#PRINT !#PUTLIN!#SWT 
 
"%t(0&$ READB0+ +		acQ	@Q	@	"BC		QS
	"	!!#GETLIN
 
"%*$0&" SKIPE0# #	acQ	@Q	@QK	%		!#!#READB0
 
"%("0&2( PRECE09 9		acQ	@A@	B"acQ	@A@"A@#A@$A@%	$MQ	#MA;	AQ	%3 3	MA;	A	QQQ_	C@&	! .d#'!#INDEX !#PARSDT
 
"%2(0&