{:&: :"=news=/index	can't open index file.	aca@A@	"Cac C@: :	A#	(#@ac"A@#Q@A@	%*ac$Q@Q@f	$C
ac&A@): :3	ac(Q@fA@"	%Cac*A@$ac&A@8B	ac,A@$A@%	Cac*A@$; ;ac&A@KT	ac.A@$A@%	Cac*A@$ac&A@]fac*A@$oac0: :A@"ac2!}!{!{!f{!h!(#GETARG!.#INDEX0!2#ARCHI0!4#DELIV0) )!*#REFOR0!$#OPEN!&#ERROR !,#SETERR!0#RMTEMP!6#CLOSE !8#SWT 
 
"%r&0&i@$ ARCHI0: :"=news=/articles/art*i"&*2n	can't open archive copy file. 9 9ac*Q	@ac,Q@A@a@Q	@ac.Q@A@	"Cac0C@		#	(	Articl9 9
e *i by *s on *s*2n.0*ac2A@Q@lac2A@Q@ac4A@"C@1Q	@Q@lQ@ac6Q	@: :A@"ac4A@"a@&ac8A@"		#	!}!~i!i!i!fi!4#CREATE* *!0#REWIND!2#ENCODE!6#REMARK!8#DATE!:#PRINT !<#FCOPY !>#CLOSE 
 
"%R$0&<X( DELIV0: :"=news=/subscribers"$=news=/delivery/"6*2n	; ;	can't open subscriber list. 	ac:a@A@	"Cac<C@		#		ac>A@Q@9 9ac>A@Q@ac@a@$A@Q@(A@	B$	acBQ@.A@"	%acBQ@.A@"	%@: :	%%L	@ t%	QS-acDQ@.	%WAV	
*s: can't deliver*n.X	ac@Q@.A@9 9Q@(A@$ac:Q@(A@	&CacFA@C@YQ@.		#	v	Article *i by *s on *s*29 9n.3acHQ	@acJA@&acFA@&C@Q	@Q@Q@acLQ	@A@&acFA@&a@6acN: :A@&AKacNA@"		#	!q!}!~!<!!!<!<: :!J#GETLIN!H#SCOPY !L#VFYUSR!B#OPEN!D#REMARK!F#DATE!N#PRINT !P#REWIND!R#WIND!T#FCOPY  !V#CLOSE 
 
"%<(0&e<& INDEX09 9"*4i. *s *s *,5s *s	ac$Q	@ac&Q@Q	@	%	A"ac(9 9Q@A@"	B#	Headline too long: *s.ac*A@Q@ac*A@Q@ac*A@9 9Q@vac,Q@A@a@A@#Q@vQ@Q@Q	@	$Cac.A@C@Q	@		%	L9 9ac0Q@Q	@ac2Q	@	#%	!q!}!e!!!e!P!f1 1e!0#CTOI!.#GETLIN!4#ENCODE!,#REWIND!2#DATE!6#PRINT !8#PUTLIN!:#FLUSH$
 
"%H&0&wF, REFOR09 9" *s" *#x*#,,-x*2n""*#n"& *s	*s: cannot o9 9pen*n.	ac*Q	@A@	"Cac,A@C@Q	@		#		can't open temporary fil9 9e. ac.A@	$Cac0C@!		#	5	ac2Q@A@"	%%
Gac4Q@	A
9 9F=L		*s: empty file*n. N	%BCac,A@C@OQ	@ac6A@$		#	[	A&t&9 9QK	C	(&mmr!ac8Q@A@&Q	@A@ac,A@$a@Q@ac:Q@	@H'; ;	'@H'	'A	t'QK	%	'&B(&@H)ac,A@$a@A@); ;A@(ac2Q@A@"	%%
8ac4Q@	A
7.=	@ *%%
Eac4Q@	@HC: :	(*MK	*Aac,A@$a@"A@*Q	@ *ac,A@$a@&Q@N	ac2Q@A@"9 9	%ADac<A@"ac>A@$	$#	!q!}!w!!w! w!8: :#GETLIN!:#ALLBL0!@#LENGTH!4#MKTEMP!0#OPEN!2#PRINT !6#REMARK!<#RMTEMP!>#SCOPY !B#CLOSE  !D#REWIND
 
"%,0&$ ALLBL09 9	A"	("@	"@HADQK	A
	%	%	@ #		A#	! 
! 
 
"%($0&