fx
&9 9"Old password: *s""New password: *s"4	Reenter n: :!ew password for verification: *s	The new passwords do not match. : :ac^A@	"ac^A@ac`A@a@Q@	%%acbA@A@	A#	acdQ@A@#: :Q@VA@ac`A@a@"Q@	%BacbA@A@ac`A@a@4Q@f	%Sacb: :A@A@acfQ@Q@f	AachC@`	A#acdQ@A@#Q@LA@acjQ@VQ@L9 9A@$	$%	One of the passwords was illegal@.. |achC@}	The old password did n9 9ot match the actual password@.. achC@	Disk is write protected@. See system administrator: :@.. 5achC@64{	%%Z|	%]	%`5URA$	ac^A@"acl!@9 9!u!v!f!!	f!f!8f!
f!h#DUPLX$!p#EQUAL !j! !#INPUT !l#PUTCH !n#CTOV!r#ERROR !t#CHG$PW!v#SWT 
 
"%&0&
