9r(9 9"3Usage: quota [-s <quota value>] [-v] {<file_spec>}9 9"D-s<rs> n<ign>v"Timproper quota value"j*s: can9 9't get quota information*n"*s: not a quota directo9 9ry*n"(*6l/*6l (*,-10l)": | *s"@*n"D*s: 9 9can't set quota*n	acZa@DQ@	Cac\a@Q	A
	A: :	"Q,	ADQGQac^Q	@A@"A@Q|Q,	ADQGQac`Q	@	#"@H#C: :Q|	A48ac\a@T9	AQacbQ@HQ@	$ac\a@H	$; ;	%LJIUQ	AacdA@Q@HQ@|A@"A@&	C	&@HCacf9 9A@a@jQ@HmacfA@a@Q@HviacfA@a@(Q@Q@Q@Q: :	A
acfA@a@:Q@H	acfA@a@@ZachA@Q@HQ@|A@"A@"	9 9	CacfA@a@DQ@H-NAIacj!q!u!}9!9!99 9!
9!j#GFDATA!n#SFDATA!h#GFNARG!f#LENGTH!d#GCTOL !`#PARSCL!b#ERROR !l#PRINT !p #SWT 
 
"%:(0&