
(9 9"=news=/index"-q""Usage:  retract [-q] { <art9 9icle number> }"L*s: not an article number*n	can'9 9	t open index file.	acha@A@	"CacjC@	acla@Q@	Cacj: :a@""Q	A
	A#*	@ #-	A$	($@2acnA@$Q@HA@	%@: :	A%	acpQ@HA@%	&t%QKG	A
acrA@a@LQ@HactA@?MacvA@&9 9A@"	C
actA@ZcacxA@&	C
actA@ho	aczA@&A@#	C9 9
actA@t}3	ac|A@"ac~!q!}!
!
!f
!9 9h!t#GETARG!|#REMOV0!~#REMOW0!#REMOX0!v#CTOI!n#OPEN!r#PARSCL!p#ERROR !x#PRINT !z #SETERR!#CLOSE !#SWT 
 
"%V(0&,$ REMOW0: :"=news=/articles/art*i	ac&Q@A@a@Q	@ac(Q@		"	! ~!f!(#ENCODE!*#REMOVE
 
"%$0&N

, REMOX09 9"=news=/subscribers"$=news=/delivery/*s"8Artic9 9$le #*i was retracted by *s on *s*2n	can't open subscriber list; ;. 	acba@A@	"CacdC@		#		can't open temporary file.!acfA@; ;	$CacdC@"		#	6achA@Q@lachA@Q@tacjQ@A@"	%acjQ@< <A@"	%Q	%%]	@ t%	QSaclQ@	%hRg	
*s: can't retract*n.iacn: :Q@A@a@$Q@acbQ@A@	&CacpA@C@jQ@		#		acrA@$act: :A@$	A'	(A%acrA@$acrA@&actA@&acvA@$A@&acxA@& acx9 9	A@&aczQ@7R\acxA@"		#		@ (	acjQ@A@&	%%TQ	%: :YS	((@X	%%_Q	C			)	ac|Q@A@)	*Q_	C^p	((: :	@cac~Q@A@$acjQ@A@&	%[q	%BCQK	AacpA@$a@8Q	@: :Q@lQ@t	((@		acjQ@A@&	%%#Q	%("'	%%-: :	((@ac~Q@A@$acjQ@A@&	%>Q	C	((@Bac~Q@A@$5=: :,L!q!}!~!N!N!!!	N!fN!: :AN!t#GETLIN!v#VFYUSR!#CTOI!l#OPEN!p#MKTEMP!n#REMARK!r#DATE!x#ENCODE!z#PRINT !|# ##REWIND!~#TRUNC !#FCOPY !#CLOSE !#REMOVE!#PUTLIN
 
"%&,0&
4h( REMOV09 9"*i: article not found*n"(SYSTEM"0*i: article 9 9not yours*n	can't open temporary file.acHQ	@acJA@Q@acLA@9 9	"CacNC@		#	 	acPQ@Q	@	BCacRA@a@Q	@		#	0	A$; ;	acTQ@A@$	%Q_	CHacVQ@A@"(I	($@t$QK	C	($S9 9SX	A&	(&@($@^	&%e	t$QK	%mf	t&QSk_l	@ t&QSk: :	acXQ@lQ@	AacXQ@a@(	A|acRA@a@0Q	@		#		acZQ	@A@"9 9*acHQ	@acHA@"ac\Q	@acZA@"Q	@ac^Q	@ac`A@"QK	#	!q!}4; ;!4!!4! 4!Z#CTOI!V#GETLIN!^#EQUAL !R#MKTEMP!N#REWIND!P#DATE!T#REMARK% %!X#PRINT !\#PUTLIN!`#FCOPY !b#TRUNC !d#FLUSH$!f#RMTEMP
 
"%X(0&