pJ
(9 9"5Usage: sacl <pathname> [<acl list>] [-l <pathname> | 9 9-a <acat>]"PCannot set ACL as specified."nObjec9 9+t specified after the "-a" is not an acat."a<rs>l<: :rs>"*.acat	ac0a@Q@	Cac2a@ac4A@Q@NA@	B9 9	Cac2a@	A"	#t"QGQ		"$ac4A@#Q	@A@$	%BC3	%9 9	B""	t"QS	(#  4	@ t"QSQ	A
Q	A

Gac2a@KQ; ;	A
Q%	ADQGQac6A@Q@NQ@A@&Q	@	Cac2a@PjTQ: :	A
Q	ADQGQac8Q	@Q@HA@	A"	("@	t"QKG	A
	"9 9	%ac2a@n         t"$QGBQac8Q	@Q@|A@ac:Q@|A@ac<Q@|a@*: :	%
3ac2a@n2	Could not add object to acat. 7ac6A@Q@NA@	A@&Q@H	; ;	Cac2C@8Usac6A@Q@NQ@A@&A@		Cac2a@PiZoPac>; ;!}p!	!!p!!!	p! p!4p!Ip!>#GETARG) )!@#SFDATA!F#EQUAL !:#PARSCL!<#ERROR !B#CTOC!D#MAPSTR!H#SWT 
 
"%,(0&
