Ij*9 9"5Usage: sema -(c | d | n | w | t | o [-i <int>]) (<sem9 9a> | <path>)"Rc<f>d<f>n<f>o<f>w<f>t<f>i<oi>"p*i9 9!: initial value greater than 0*n"*i*n"*i*n9 9" no available semaphores*n":*s: invalid semaphore 9 9name*n"X*s: semaphore overflow*n"r*s: on a remo9 9
te disk*n"
*s: file not found*n" *s: can't open: : semaphore*n	ac<a@RQ@	Cac>a@	@ "Q	A
	("@9 9Q	A
	("@Q	A
	("@Q	A
	("@$Q	A
	("@*: :Q	A
	("@0	"%
7ac>a@6Q	A
Q	A
Q"	#B; ;ac>a@F>	@ #K	#Aac@A@a@pA@#ac>A@P	A$	acBA@$Q@H; ;A@	%j	@ %QH	%q	%uu	%t	@pvx	A"acD; ;	Q@HA@"A@		%yQ	A
acFA@%A@&Q	A
acHA@%A@&Q9 9	A
acJA@%A@&Q	A
acLA@%A@&&Q	A
acNA@%A@&	"9 9	&Aac@A@
a@A@":0Q	A
acPQ@HA@	'%
QacRA@'	(%; ;YacTA@(A@A@%A@#A@&X		&eP		&hacVA@'	&Aac@9 9	A@
a@A@%qF	&Cac@A@a@ }	&Cac@A@a@:Q@H9 9	&Cac@A@a@XQ@H	&Cac@A@a@rQ@H"	&Cac@9 9A@a@
Q@H/	&A
ac@A@a@ Q@H;8+ 	($__iacX!. 9 9!q!
u!}!I!I!!	
I!I!&!)!2I!: :-!0!4!9I!R#GETARG!T#GCTOI !^#SEM$TS!`#OPEN!b#MAPFD !L#PARSCL!N#ERROR 0 0!P#PRINT !V#SEM$CL!X#SEM$DR!Z#SEM$NF!\#SEM$WT!d#SEM$OU!f#CLOSE !h#SWT 
 
"%&*0&