{>
&9 9"-i"-x"-i"-xac A@Q@A@	BCac"
: :ac$Q@A@ac&Q@a@	@HC	A"	ac&Q@a@	@HC	@ "': :ac"*ac A@Q@A@	BCac"7	start pattern is ill-formed.:ac(Q@; ;	A@A@Q@f	Cac*C@;Uac A@Q@A@	BC	@ #dac$Q@: :A@ac&Q@a@	@HC	A$v	ac&Q@a@	@HC	@ $ac": :yac A@Q@A@	BCac"	end pattern is ill-formed.ac(Q@A@A@9 9Q@	Cac*C@/	A#g	@ %	ac,Q@A@	%A	A$%FC	#C< <ac.Q@Q@	@HCH	$@HCac0Q@A@	U@Qac0Q@A@	Eac.: :Q@Q@f	@HC	A%"Cac0Q@A@	qlc8\ac2!	u!v!}!9 9!!!!!{!{!8#MATCH !2#MAKPAT!*#GETARG!6#GETLIN!0" "#EQUAL !,#USAGE !.#MAPSTR!4#ERROR !:#PUTLIN!<#SWT 
 
"%&0&
" USAGE - -	Usage:  slice (-i|-x) <start_pat> (-i|-x) <end_pat>.acC@!#ERROR 
 
"%""0&