N<$: :"
_st_count	Usage:  st_profile [<count_file>] <source_file>.acA@Q@A@: :	BCacC@#acA@Q@fA@	BCacQ@A@Q@fA@aca@A@: :Q@A@2	ac Q@A@	"Cac"Q@P	ac Q@fA@	#Cac$A@": :ac"Q@f^	          . gac&A@"A@Q@2	%yQ2	ACac(A@C@h9 9|ac(A@A@Q@2	premature end of source file. ac*A@A@ac*A@9 9A@ac,Q@LA@#	BC
ac.C@x0ac0Q@LA@g5ac$A@#ac$A@": :ac2!u!}!G!!G!f! G!|G	*10l.   s*l9 9. !(#OPEN!.#INPUT !"#GETARG!4#GETLIN!$#ERROR !&#SCOPY !*#CANT!,#CLOSE !0#PRINT !2 #PUTCH !6#REMARK!8#PUTLIN!:#SWT 
 
"%X$0&