" 	acacac!#OPTIO0!#SADIS0!#SWT 
 
"%""0&J$ OPTIO05 5>VALCOMOPTCOM	@ ,aSOPTCOM	A,aSOPTCOM	@ ,aSOPTCOM	A,aSOPTCOM	@ 5 5,aSOPTCOM,aSOPTCOM,aSOPTCOM,aSOPTCOM,aS OPTCOM	A,aS"	OPTCOM		: :,aS$
OPTCOM	@ ,aS&OPTCOMac(A@Q@A@	%+Q	C*	@ ,aSOPTCOM9 9,aSOPTCOM,aSOPTCOM,aSOPTCOM,aSOPTCOM,aSOPTCOM,aSOPTCOM,aSOPTCOM; ;,aS OPTCOM,aS"	OPTCOM,aS&OPTCOM		"	("@I	t"QK	A
	%T	%W9 9SV	A,aSOPTCOMW	t"QK	%b	%	ead	A,aSOPTCOM: :e	t"QK	%
p	%sor	A,aSOPTCOMs	t"QK	%~5 5	%}	A,aSOPTCOM	t"QK	%	%	A; ;,aSOPTCOM	t"QK	%	%           	A,aSOPTCOM	t"QK: :	%(	%+'*	A,aSOPTCOM+	t"QK	%6	%9589 9	A,aSOPTCOM9	t"QK	%D	%GCF	A,aS OPTCOMG	t"9 9QK	C	A,aS"	OPTCOM	""	ac*Q@A@",aS$
OPTCOM	A		,aS$
OPTCOM9 9`	"@H"Q	t"QK	%n	%qmp	A,aS&OPTCOMq	Usage:9 9  stats [-(t|a|m|s|v|h|l|r|q|n|%<int>)].vac,C@wugK=/!wi[JP/		!9 9!!!
!2!f!%!-!	A!        H!L!M!N!Q!R9 9!S!T!V!a!h!l!
m!n!q!r!s!t!v!,9 9$OPTCOM!.$OPTCOM!0$OPTCOM!2$OPTCOM!4$OPTCOM!6$OPTCOM!8$OPTCOM!:$OPTCOM!<, ,$OPTCOM!>$	OPTCOM!@$
OPTCOM!B$OPTCOM!D#GETARG!F#CTOI!H#ERROR 
 
"%
$0&<, SADIS09 9>VALCOMOPTCOM	AQ	Q	,aKOPTCOM	A
",aK	OPTCOM	A
A	"	#A,aS>VALCOM9 9,ak>VALCOM	@acA@A@Q@	%"Q	Q	Q	Q	Q;	Q	Q	9 9,aK>VALCOM	@HCQ	Q	Q	4Q	Q'	CAQ	BQ	Q'	5 5JQ	KE;	#A
Q	,a7>VALCOM,aS|VALCOMP!,aK>VALCOM	@H7 7,aS>VALCOM	A		^Q	ac,a
@>VALCOMQ	Q;	A;Q	Q	Q;	Q	9 9,aK>VALCOM	AZ@Q;	Q	Q	Q	 	A,ag>VALCOM,a_>VALCOM	$Q	 ac9 9A@$	A|Q	 ,aKOPTCOM	@HCacA@ac A@A@Q@,aK"OPTCOM	@H9 9	CacA@ac A@A@,a
@>VALCOM&,aK$OPTCOM	@HCacA@ac A@: :G@Q@7,aK&OPTCOM	@HCacA@ac A@G@AQ@H,aK(OPTCOM	@HC9 9acA@ac A@G@RQ@Y,aK*OPTCOM	@HCacA@Q	Q	Q	ac A@6 6G@cQ@j	variance. },aK,OPTCOM	@HCacC@~ac A@G@zQ@ : :,aK.OPTCOM	@HCacA@Q	 as0Q	ac A@G@Q@,aK	OPTCOM	@HC9 9ac2,aK4
OPTCOM	AZQ$AQ?$A	@AY%,aK4
OPTCOM	&A'	('@E	*2i%< <        . H	'$%R,aK6OPTCOM	Aac A@C@IA@&W,aK>VALCOM	8'<%AZG<9 9	@AYC>AD,aG|VALCOMQ&ac A@G@(Q	@&,aK4
OPTCOM	&&FS/	A,agOPTCOM9 9	(,aK>VALCOM	AZG;fG	@AY)A'	',ag>VALCOM	@*A+('9 9	@',ag>VALCOM	@A7	',aK|VALCOMA7	*,ag|VALCOM*')*; ;	(++	+$(42	(*)3	acA@A7	),aG|VALCOM	Q&ac A@9 9G@tQ	@&		!u!v!K	@8dG*d*n.   0*i*n.   ;aver9 9age.]high.   ;mode.   nrange.  *size.   std dev.total.  k@9 9*f. Llow.! $OPTCOM!($OPTCOM!$OPTCOM!2$OPTCOM!0$OPTCOM!,$OPTCOM9 9!*$OPTCOM!.$OPTCOM!:$OPTCOM!$	OPTCOM!8$
OPTCOM!&$OPTCOM!$|VALCOM!$>VALCOM# #!#INPUT !#D$61!"#LABEL !$#PRINT !4#DSQR$X!6#SORT
 
"%T,0&*$ LABEL : :>VALCOMOPTCOM	,aKOPTCOM	AacA@A@Q	@acQ	@A@Q@A@	"9 9	("@	"%	@acA@A@		!u'!
'!f! !.'   
*p. !$OPTCOM!#PTOC!#PRINT !#PUTCH 
 
"%$0&

E& SORT< <>VALCOMOPTCOM,aK>VALCOM	M="	"M="	"A	B#	(#@	#,ag>VALCOM: :	@"$	$"$	$A	"%A7	$,aK|VALCOMA7	%,ag|VALCOM	@9 9*A7	$,aK|VALCOMQ	A7	%,aK|VALCOMA7	$,aS|VALCOMQ	A7	%,aS|VALCOM& &,		!E!$|VALCOM!$>VALCOM
 
"%*&0&