cJ49 9SWT$TPfHSWT$CM"+Usage: template [-a|-r] [-l{usv}]  { <strin: :g> }"@alrsuv"H*s*n"N*nUser Templates:*n"b9 9*nSystem Templates:*n"x=utemplate="*s: may not9 9 contain '='*n"*s: missing definition*n"8*s: d9 9uplicate name*n"Nfile not altered"`=utemplate=9 9"l*s: not in template file*n	aca@@Q@	Cac
a@: :Q	A
"Q	A
#"A	#A	A"Q	A
Q         A
 ac
a@$9 9Q	A
	A$,Q         A
	A%4Q	A	A&<89 90Q	A
	A'Cac?	A(	((@KacA@(Q@|A@	%Y: :acQ@|Q@HA@acA@a@HQ@HLXF	"A
Q	A
acA@a@N6 6qac,a
@L'SWT$CM,a
@LLSWT$CMm	#A
Q	A
acA@a@bac9 9,a
@SWT$TP,a
@&SWT$TP/	A)	can't open user template file.aca@x; ;A@	*Cac
C@.	can't create temporary file.3ac A@	+Cac
C@4: :I	ac"Q@bA@*	%Wac$Q@bQ@HQ@H	%bac&A@,Q@HA@	%ma: :lac(Q@bA@+m	,B-!acA@-Q@HA@ac*Q@HQ@HA@+ac,A@,ac,; ;A@,tNVac.A@*ac.A@+ac0A@+A@*ac2A@+	A,	,@D,%acA@,: :Q@HA@	%4	,B-acA@-Q@HA@ac*Q@HQ@HA@*&3	ac4A@*ac69 9A@*ac8	@ .A/	/@D/WacA@/Q@HA@	%fac:Q@HA@	A
: :acA@	a@Q@H	(.@m	/B-acA@-Q@HA@
	BCacA@	a@Q@H	(.: :	@	/@D0	0@D0acA@0Q@HA@	%"ac<Q@HQ@H	A
acA@	9 9a@8Q@H	(.@)!Xe	.A
ac
a@N87	can't open user template9 9 file.>	aca@`A@	1Cac
C@?W	can't open temporary file.\ac A@9 9	2Cac
C@]q	ac"Q@HA@1	%ac$Q@HQ@.Q@.	BCac(Q@H< <A@2	ac&A@3Q@.A@
	BCac(Q@HA@2ac,A@3"v~ac.; ;'A@2ac.A@1ac4A@1ac0A@2A@1ac2A@2ac6A@1ac8	A3	(3@FacA@3; ;Q@HA@	%TacA@	a@lQ@HGSj@=R0           G]89 9!	q!u!}!c!
!!c!f!c!4c!=c!: :#PARSCL!#GETARG!"$L'SWT$CM!$$LLSWT$CM!&$SWT$TP!($&SWT$TP!*#OPEN!,#MKTEMP!.#GETLIN!09 9#GTEMP !2#TARG!H#EQUAL !F#INDEX !#ERROR !#SWT !#EXPAND!#PRINT ! #PRINT0!4#PUTLIN1 1!6#PTEMP !8#DELARG!:#REWIND!<#FCOPY !>#RMTEMP!@#TRUNC !B#CLOSE !D#LDTMP$
 
"%b40&7$ PRINT0: :	A"@HADQK	#	#@HADQK	#	#A
	t#QK	A	#BADQGQ	t#9 9QK	@HADQGQacQ	@Q	@A@	         A"%6		!u7!% !#PTEMP 
 
"%.$0&($ PTEMP ; ;"   *s*#t*s*n	acQ	@	Bac A@	"M=@"A"ac"Q	@a@Q	@, ,A@"Q	@		!!!!"#LENGTH!&#PRINT !$#F$MA11
 
"%.$0&

/$ TARG: :			Qg	"	A"	AQS	"Q[QSacQ	@Q@
A@; ;	%acQ	@Q@
	A
QK	#	&		#	!/!!!#GETARG !#EQUAL 
 
"%.$0&