1$: :acA@Q@A@	BCac
	A"	("@acA@"Q@A@	%9 9Q	CacQ@A@""acQ@)                           ac!1!1!$ $!-!#GETARG!#DISPL0!#DOOPT !#DOTERM!#SWT 
 
"%$$0&($" DOTERM9 9"help"?	acQ	@A@aca@Q	@	%aca@Q	@	%: :acacQ	@	@HC#ac $		!(! #TTYP$V! #EQUAL !#MAPSTR!#TTYP$L!"#USAGE 
 
"%&"0&, DOOPT 9 9fHSWT$CM"0breakechoenbeoferaseescapeinhkill9 97lcase	lfnewline
nobreaknoechonoinhnolcase9 97nolfnosenovthnoxoffnoxonretypesevthxoff9 9xon"4',29=FOW^gmsz	 "N: unrecognize: :d mnemonic	acfQ	@A@acha@4a@A@Q	@	"BCacj	t"< <aK3	ADaK	#
aclA@		$A%$		$	%)*	A&	',aSnSWT$CM6 60		&3	',aSpSWT$CM7		(A)>		&:	',aSrSWT$CMD	@ 9 9,aSta
SWT$CMK		$	%/OaclA@U		(	)CZ	A,aSta
SWT$CM`		(	7 7	)_d		$	%Tj		&G	',aSvSWT$CMp		(	)iw			&s	'9 9,aSxSWT$CM}		
&	',aSzSWT$CM	@ ,aS|aSWT$CM	@ ,aS~a	SWT$CM9 9	A,aS|aSWT$CM	A,aS~a	SWT$CM	#L %+18?ELPV[9 9aekkqxx~		Qk	@acQ	@Q@A@	BC: :acjE	A*acQ@A@*A@	'CacQ@A@aca@NU|ac: :A@A	(,aS
aSWT$CMac,a
@
aSWT$CMo	$A+acA@	+,aS
aSWT$CMac9 9,a
@
aSWT$CM`	&L4;Ht}|	%L
*0Upm	)L: :
D`j}!!q!}!!!!!!!	!
9 9!! !@!|$SWT$CM!$SWT$CM!$SWT$CM!$SWT$CM!~$SWT$CM!$SWT$CM; ;!
$aSWT$CM!$a	SWT$CM!$a
SWT$CM!$aSWT$CM!v#STRBSR!#DUPLX$!#GETARG!#MNTOC !t#MAPSTR !x#USAGE !z#BREAK$!#PUTLIN!#ERROR 
 
"%6,0&f & DISPL09 9fHSWT$CM"
type *s  "buffer *i*n"&-erase *s  -esca9 9pe *s  -kill *s  "H -retype *s  -eof *s  -newline *s9 9*n"l*#g*s  "t-echo"z-lf"~-noxoff"-: :noinh"*#g*s  "-noecho"-nolf"$-xoff9 9"*-inh"0-nose  "8-se  ">	-novth  "H-vth 9 9 "P-nolcase  "\	-lcase  "f-break"n-nobre8 8akacxA@	"aczA@A@#ac|,a
@~aSWT$CMA@	@HCacA@a@: :,a
@~aSWT$CM	"B($acA@a@A@$ac,a
@SWT$CMQ@ac,a
@SWT$CMQ@: :ac,a
@SWT$CMQ@ac,a
@
SWT$CMQ@ac,a
@SWT$CMQ@ac,a
@SWT$CM9 9'Q@acA@a@&Q@Q@Q@acA@a@HQ@Q@Q@	A%	"C?"(%@e	%: :	%	@"A	%B$acA@a@lA@$a@ta@za@~a@r	%B$acA@9 9a@A@$a@a@a@$a@*fm,aKaSWT$CM	AacA@a@0ac: :A@a@8%,aKa	SWT$CM	AacA@a@>/	acA@a@H6,aKa
SWT$CM	@H9 9	CacA@a@PA	acA@a@\H	#AacA@a@fQacA@9 9a@nX	acA@A@		!!u!f!f!f!f!
f9 9!$SWT$CM!$SWT$CM!$SWT$CM!$SWT$CM!$SWT$CM!$SWT$CM!$aSWT$CM!$a	SWT$CM3 3!$a
SWT$CM!$aSWT$CM!#DUPLX$!
#CTOMN !#CHKSTR!#BREAK$!#PRINT !#PUTCH 
 
"%>&0&>" USAGE 9 9	5Usage: term [ ? | <term type> | { <option> } ].    <option> ::= -erase <char>  | -kill <char> | -newline <9 97char>.              | -retype <char> | -eof <char>  | -escape <char>.               | -[no]break | -[no]echo |9 97 -[no]lcase | -[no]lf.              | -[no]xoff  | -[no]xon  | -[no]se    | -[no]vth.               | -[no]inh8 8. $acC@acC@acC@9acC@YacC@xacC@		!#REMARK!#ERROR 
 
"%""0&