D`&9 9"=gossip=/***3,,0i""=gossip=/*s	Usage: to (<user name> | <9 9user number>) [<message>].ac.A@Q@JA@	BCac0C@%	A"	ac2Q@JA@"; ;	#"%7	#%	@@HC9=	bad user number.?ac0C@@>	ac4Q@
A@9 9a@A@#6	bad user name.Wac6Q@J	C
ac0C@Xe	ac4Q@
A@9 9a@"Q@JjV	can't open temporary file.uac8A@Q@4ac8A@Q@@ac8A@Q@<9 9ac8A@Q@ac:Q@Qac<A@	$Cac0C@v(	*2nFrom *s (*s) at *,5s on9 9 *s@.*2n. -ac>A@$C@.Q@4Q@<Q@@Q@		"	("@Pac.A@"Q@VA@		%
; ;^ac>A@$A@Q@VQ]	"%kac@A@A@$j	acBA@A@$qacD; ;A@$	@ "	("@~	"%acFQ@
A@	%%acHA@%acBA@$A@%acJ; ;A@%acLA@$acNacPA@	User is busy@. Try later@.. (acLA@$ac0C@)9 9!v!}!
?!!!!!?!
?!!!*!	f!9 9!
?c*s .&t!H#MAPUP !T#OPEN!J#MKTEMP!<#GETARG!D#VFYUSR!@#CTOI!>9 9#ERROR !B#ENCODE!F#DATE!L#PRINT !N#PUTCH !P#FCOPY !R#REWIND!V#WIND!X#CLOSE !Z#RMTEMP !\#SWT !^#SLEEP$
 
"%&0&