ZD
&: :"2Usage: touch [-d <date>] [-t <time>] {<pathname>}"B: :d<rs>t<rs>n<ign>"T invalid format in date argument9 9"t invalid format in time argument"*s: can't touch*: :n	ac&a@BQ@	Cac(a@ac*A@Q@Q	%
Q4Q	AD9 9QGQlac,Q@Q	@lA@	BQ4Q4ac*A@Q@Q	%
9Q4Q-: :	ADQGQlac,Q@Q	@lA@	BQ4Q48	A"Q	ADQGQlac.Q	@lA@"; ;	Q@IQ@JQ@H	%
gac(a@Tf	A"Q-	ADQGQlac0Q	@lA@"Q@n	%: :ac(a@t~Qn	EA?	@QK	MG;	AQn	BQn	EA?	@QL: :	9@MQn	B@QM	AQac2Q@NQ@	#ac(a@-	#$L/9 9.:ac4A@Q@NQ@HA@%Q@	Cac6A@a@Q@NJ3&.ac89 9!q!}!~V!!V!!V!<V!HV<: :!<#GFNARG!>#SFDATA!:#PARSTM!8#PARSDT!0#PARSCL!6#CTOC!2#ERROR !4#DATE!@#PRINT !B#SWT 
 
"%&0&
