Jr&9 9CTSORT<DS$MEM"v"Usage: tsort [ -v ]"&*s*s","9 9*s,*s" input error*n"B*s*n	acHa@Q@	CacJa@: :acLA@acNA@,aSPCTSORT	@ ,awPCTSORT,aSRDS$MEM,aSTDS$MEM,aKVDS$MEM: :	AD@ ,aSRDS$MEM	A,awPCTSORT,aSXDS$MEM	@ ,aSZDS$MEMac\A@a@&Q@.Q@H	B: :	C8Q.	A
QH	A
=Aac^A@a@,Q@.Q@HBac`Q@.9 9	"ac`Q@H	#At",aSZDS$MEM	"$#`acbA@"A@#	A_gMhacN9 9A@	$t#,aKTDS$MEM	t$,aSRDS$MEM	",aSTDS$MEM	$t#,aSTDS$MEMi,9	@ %9 9,aKPCTSORT	"	t",aKRDS$MEM	"	t",aKRDS$MEM	A
,aKXDS$MEM	@HC9 9	A%acdA@"	A	%A	t",aKRDS$MEM	AacfA@"9 9#Q	A	t",aKZDS$MEM	%2+1	t",aKVDS$MEM	AD,aGRDS$MEMQ: :ac^A@a@BQ	@2	At",aSXDS$MEM}ach!q!u!v!}J!8 8!J!J!<J!X$CTSORT!Z$DS$MEM!\$DS$MEM!^$DS$MEM!`$DS$MEM!b< <$DS$MEM!V#DSGET !h#INDEX !d#INPUT !j#PRESE0!l#ANYPR0!P#PARSCL!R#ERROR !T#DSINIT!f#PRINT  !n#FINDL0!p#SWT 
 
"%<&0&$ PRESE0< <CTSORT<DS$MEM	Qw,aKDS$MEM	"	t",aKDS$MEM	"	"A
	t",aKDS$MEM' 'Q_	C	A#		@ #	!$DS$MEM!$DS$MEM
 
"%*$0&$ ANYPR0< <CTSORT<DS$MEM	Qw,aKDS$MEM	"	t",aKDS$MEM	"	"A
	t",aKDS$MEM5 5	AD,aKDS$MEM	@HC	A#		@ #	!$DS$MEM!$DS$MEM!$DS$MEM
 
"%($0&a&& INDEX 7 7CTSORT<DS$MEM	,aKCTSORT	"	t",aKDS$MEM	"	t",aKDS$MEM	A
: :,aKDS$MEM	AD,aGDS$MEMQacQ	@Q	@	@HC	"#	acQ	@	B9 9	$acA@$	%acA@	t",aSDS$MEM	%,aSDS$MEM		,aSDS$MEM,aKDS$MEM8 8	AD@ ,aSDS$MEM	t",aKDS$MEM	AD@ ,aSDS$MEM	t",aKDS$MEM	ADA,aSDS$MEM	t"9 9,aKDS$MEM	AD,aGDS$MEMQac Q	@Q	@A@	"#	!a!!fa!9 9$CTSORT!$DS$MEM!"$DS$MEM!$DS$MEM! $DS$MEM!#DSGET !#LENGTH!#EQUAL !$#CTOC
 
"%,&0&T& FINDL09 9CTSORT<DS$MEM"cycle (in reverse order):"*error 1"2< < *s"6error 2	,aK>CTSORT	"	t",aK@DS$MEM	"	t",aK@DS$MEM9 9	A
,aKBDS$MEM	@HC	acDA@a@	t",aKBDS$MEM	@HC		< <,aSBDS$MEM,aKFDS$MEM	#	t#,aK@DS$MEM	#'	#AacHa@*.	t#,aKFDS$MEM; ;	"t",aKBDS$MEM	%=<(= 	t",aKBDS$MEM	C		,aSBDS$MEM< <,aKJDS$MEM	AD,aG@DS$MEMQacDA@a@2Q	@	t",aKFDS$MEM	#	t#,aK@DS$MEM; ;	#\	#AacHa@6c	t#,aKFDS$MEM	"t",aKBDS$MEM	%rq]r@7 7E	acLA@A@,aK>CTSORT	$	t$,aK@DS$MEM	$~	t$,aK@DS$MEM	A
9 9,aKBDS$MEM	%		,aSBDS$MEM	"QS		!q!!!: :!!
!D$CTSORT!F$DS$MEM!L$DS$MEM!P$DS$MEM!H$DS$MEM!J#PRINT !N #ERROR !R#PUTCH 
 
"%,&0&