@H"9 9INTCOM"*s.ct1"*s.ct2" *s.ct3ac(A@Q@A@	%: :ac(A@Q@fA@	BC
	usage:  interp filename_prefix. ac*C@: :	interp:  can't open *s*n. ,ac,Q@fA@a@Q@ac.Q@fA@,aS0INTCOM	C9 9ac2A@C@-Q@fac4N	interp:  can't open *s*n. Y	A,aS6INTCOM	ac,Q@fA@9 9a@Q@ac.Q@fA@,aS8INTCOM	Cac2A@C@ZQ@fac4~	interp:  can9 9't open *s*n. 		A,aS:INTCOMac,Q@fA@a@ Q@ac.Q@fA@,aS<INTCOM	C: :ac2A@C@
Q@fac4.	A,aS>INTCOMac@ac4!q!}!@!!; ;@!f@!6$INTCOM!>$INTCOM!B$INTCOM!<$INTCOM!@$INTCOM!D$INTCOM!.#GETARG# #!4#OPEN!0#ERROR !2#ENCODE!8#PRINT !:#SWT !F#DISPL0
 
"%n"0&$ DISPL09 9INTCOM""*n*n######  Module *i  ######*n*n"2	Entry Poi9 9	nts:*n*n"D*nStatic Data Definitions:*n*n"d*nPro9 9cedure Definitions:*n*n	A"	("@	missing MODULE_OP in entry poi: :nts.acA@#,a
@INTCOM,a
@INTCOM	%"	#%&!acA@a@A@"	#5 5	%2ac
C@acA@,a
@INTCOM,a
@INTCOM1acA@#,a
@INTCOM; ;,a
@INTCOM	%I	#CHL	                                                                                                             issing MODULE_OP in static data. N	ac
C@Oac9 9A@,a
@INTCOM,a
@INTCOMMacA@#,a
@INTCOM,a
@INTCOM	%w	#C: :vz	missing MODULE_OP in procedures.|ac
C@}acA@,a
@INTCOM,a
@INTCOM9 9{	missing NULL_OP in entry points.acA@a@2ac,a
@INTCOM,a
@INTCOMA@#9 9	#%<ac
C@acA@,a
@INTCOM,a
@INTCOM;	missing NULL_OP in static data: :. HacA@a@Dac,a
@INTCOM,a
@INTCOMA@#	#%kac
C@IacA@< <,a
@INTCOM,a
@INTCOMj	missing NULL_OP in procedures.wacA@a@dac,a
@INTCOM: :,a
@INTCOMA@#	#%ac
C@xacA@,a
@INTCOM,a
@INTCOM%	7 7missing NULL_OP at end of entry points. &	#%
?ac
C@'>acA@#,a
@INTCOM: :,a
@INTCOM	%N	#CMQ	missing NULL_OP at end of static data.Sac
C@T9 9RacA@#,a
@INTCOM,a
@INTCOM	%v	#Cuy	
missing NULL_OP at e7 7	nd of procedures. {ac
C@|z		!u!! !'!$INTCOM!9 9$INTCOM!$INTCOM!
$INTCOM!$INTCOM!$INTCOM!#GET !#PRINT !#ERRMSG!#SKIPTO !#DISPM0
 
"%$$0&;4$ DISPN09 9INTCOM"object id *i, '*s'*n	missing object id in entry point declaration; ;. ac&A@",a
@(INTCOM,a
@*INTCOM	BCac,C@		"ac.Q@,a
@(INTCOM: :,a
@*INTCOMac0A@a@A@"Q@		!u;!*$INTCOM!,$INTCOM!(#GET !.#ERRMSG !0#GETST0!2#PRINT 
 
"%
$0&If$ DISPO09 9"int"	unsigned"long"$long unsigned"2f9 9loating"<long floating"Jstowed"Runknown (*i; ;)	QK	",ac`a@A@ac`a@A@ac`a@A@ac`a@$A@9 9#ac`a@2A@ ac`a@<A@'ac`a@JA@.	"L!(& &/acbA@a@RQ	@5		!uI!b#PUTLIN!d#PRINT 
 
"%($0&C"" DISPM0: :INTCOM	acQ	@Q	@Q	@	%QK	CQK,a_INTCOM	Cac9 9QK,a_INTCOM	CacQK,a_INTCOM	Cac(	interp6 6:  can't possibly happen. ,acC@-+"		!C!;!$INTCOM!* *$INTCOM!$INTCOM!#GET !#DISPN0!#DISPP0!#DISPQ0! #ERROR 
 
"%,"0&  R" DISPR09 9"5addaaaddandaaandassignbreakcasecomplconstcon9 97vertdeclare_statdefaultdefine_dynmdefine_statderef9 97divaadivdo_loopeqfor_loopgegotogtifindexinit9 97ializerlabellelshiftaalshiftltmodulemulaamulne9 97gnextnenotnullobjectoraaorpostdecpostincprede9 97cpreincproc_call_argproc_callproc_defn_argproc_def9 97nreftoremaaremreturnrshiftaarshiftsandselectse9 97qsorsubaasubswitchundefine_dynmwhile_loopxoraax9 97orzero_initializerfieldcheck_rangecheck_uppercheck9 9_lower"+H"'-3;HP\hntx ,25>EHOUY]beinuz: :})3AKQW[bkrw~%06:KQ]i	QwaK	ADaGQacNQ	@ A@		!u                                 P#PUTLIN
 
"%("0&yN* DISPQ0: :INTCOM"-procedure '*s', object id *i; *i arguments*n">9 9!   argument, object id *i, mode "`, pass-by-value, 9 9"r, pass-by-reference, ", illegal disposition : :(*i), "&size *,-10i*nac4A@",a
@6INTCOM,a
@8INTCOM	%< <	"C
	missing PROC_DEFN in procedure stream.ac:C@ac<A@,a
@6INTCOM< <,a
@8INTCOM	missing object id in procedure definition.0ac4A@#,a
@6INTCOM,a
@8INTCOM: :	BCac:C@1		P	missing number-of-arguments in proc defn. Vac4A@$,a
@6INTCOM: :,a
@8INTCOM	BCac:C@W		vac>Q@,a
@6INTCOM,a
@8INTCOM	ac@A@a@: :	Q@A@#A@$	                                                                                                             issing argument object id number.ac4A@%,a
@6INTCOM,a
@8INTCOM	%9 9-	%C,ac4A@#,a
@6INTCOM,a
@8INTCOM	BCac:C@         	;	missin: :g argument data mode. Aac4A@&,a
@6INTCOM,a
@8INTCOM	BCac:C@B		Z	mi9 9ssing argument disposition. `ac4A@',a
@6INTCOM,a
@8INTCOM	BCac:C@a		z9 9	missing argument length.ac4A@(,a
@6INTCOM,a
@8INTCOM	BCac:C@		9 9ac@A@a@>A@#acBA@&	'Aac@A@a@`+	'@HCac@A@a@r9 96ac@A@a@A@'=2ac@A@a@&A@(0	missing NULL at end of procedure par: :ameters.O	%%
jac:C@P		i	@ ,aSDINTCOMacF,a
@6INTCOM,a
@8INTCOM		; ;!u!y!'y!1!2y!<$INTCOM!>$INTCOM!J$INTCOM!:#GET !@#ERRMSG !B#SKIPTO!D#GETST0!F#PRINT !H#DISPO0!L#DISPS0
 
"%*0&
" DISPP06 6INTCOM	@ ,aSINTCOMac,a
@INTCOM,a
@INTCOM		!$INTCOM!$INTCOM! $INTCOM!#DISPS0
 
"%""0&u0
, DISPS09 9INTCOM"0	
9 979 97 !"9 97#$%&'()*+,-./9 9701234567899 97:;<=>?@ABCDE9 9FGH"hH#'*/37<AEJOSX^cfkqw|9 9+	 $',037<AFKPUZ_fmqv{~ %*-16;?ELR"2*i*n9 9"8constant, mode "H
, size *i"R, value:*n"^*9 9	,-8,0i*n"h	, value "r*i*n"x*,-10i"*l*n9 9"	*,-10l*n"*r*n"*d*n"*i*n""'*s'*n9 9	premature end of tree.acA@"Q	@Q	@	BCacC@			"%""9 9	%!	@#	bad operator in tree. &acA@a@2A@"acC@'		%	"9 9	#	premature end of tree.BacA@$Q	@Q	@	BCacC@C		X	premat9 9ure end of tree.^acacA@a@8acA@$acA@%Q	@Q	@	BCacC@_		: :acA@a@HA@%	$CacA@a@R,aKINTCOM	@D,aSINTCOM	@ &	(&: :	@	premature end of tree."	&$%2acacA@$Q	@Q	@	BCacC@#		; ;>acA@a@^A@$ 1,aKINTCOM	@H,aSINTCOM           	acA@a@h	%%^9 9^	%]	@_	bogus constant length.bacA@A@acC@c		a	A&; ;	(&@{	premature end of tree.~	&$%	@t&QGQ
acQ	@
Q	@Q	@	BC9 9acC@		|	$'$acA@a@rQ@acA@a@xQ@/acA@9 92a@Q@8acA@a@Q@AacA@a@Q@JacA@a@Q@S&	'L: :'90BKT\R		acacA@acA@A@		acacA@acA@: :A@,aKINTCOM	@D,aSINTCOM	ac Q	@Q	@,aKINTCOM	@H,aSINTCOMac Q	@9 9Q	@		A	interp:  table inconsistency at *i*n. 	#%	/B	%2g	%5t	t"7 7aKh	(t(aK	$"?acA@C@A@"ac">acacA@"acA@A@9 9,aKINTCOM	@D,aSINTCOM	(B)	()@]	t)aK	A
	*	premature end 9 9of tree.gacA@$Q	@Q	@	BCacC@h		}acacA@a@A@$	9 9premature end of tree.acA@$Q	@Q	@	BCacC@		$acacA@$ac9 90A@A@ac Q	@Q	@6ac$a@*Q	@Q	@acacA@a@"a@*=f	*L: :gg7>W	bad table element in get_tree.ZacC@[P^d,aKINTCOM9 9	@H,aSINTCOM		!q!uu!u!u!u!		u!'u!;: :u!Hu!
u!*#DISPS0!$$INTCOM!#GET !#ERRMSG!#PRINT ! #STEP!"#DISPO0!& #PUTCH !(#DISPR0!,#SWT !.#GETST0
 
"%8,0&
" ERRMSG9 9INTCOM	interp *i/*i/*i: *p*n.	acA@C@,a
@INTCOM,a
@INTCOM,a
@INTCOM( (Q	@		!q!$INTCOM!$INTCOM!$INTCOM!#PRINT 
 
"%&"0&

$ GET 9 9	acQ	@A@Q	@	BC		QS		"	Qk	@A"	!!!( !#READF 
 
"%.$0&$ GETST09 9	expected length of string.acA@"Q	@Q	@	BCacC@	@ QS			"9 9	A	%$	@&	unreasonable string length. )acC@*	@ QS		(	A#: :	(#@B	bogus string length or premature end of module. E	#$"	@@HAD	QGQ
ac9 9	Q	@
Q	@Q	@	BCacC@F	@ QS
		rC`	#@HAD@ QS		!e!
 
#GET !#ERRMSG
 
"%0$0&$ SKIPTO2 2	acA@"Q	@Q	@	%	"	Qg    		!!#GET 
 
"%.$0&

~$ STEP9 9INTCOM"0                                                : :6                                                     9 9,aKvINTCOMacxA@	"AADaGuQaczQ	@A@		!u!<!x$INTCOM !|#PUTLIN!z#F$MI11
 
"%&$0&