Y(9 9"5Usage: fixp [-mu | -ml] [-u] [-z] [-cl | -cd] [<in_pa9 9th> [<out_path>]]"Xm<rs>u<f>z<f>c<rs>"lu"nl: :"pd"rl	acta@XQ@	Cacva@Q	A
	A"9 9	@ "Q	A
	A#	@ #Q	A
Q&	ADQGQ|acxQ	@|: :A@Q@HA@aczQ@Ha@l	@HC		$<	aczQ@Ha@n	@HC	A$H9 9acva@K?"Q	A
Q	ADQGQ|acxQ	@|A@Q@HA@aczQ@Ha@p9 9	@HC		%m	aczQ@Ha@r	@HC	A%yacva@|pSac|A@; ;Q@HA@	%ac~Q@HA@	&CacQ@H		&	ac|A@Q@H9 9A@	%(ac~Q@HA@	'CacQ@H1'		'6	Problem in fixp.: :9acA@&A@'A@$A@"A@%A@#	%
SacvC@:Rac!u!v!}!9 9Y!!Y!4Y!#OPEN!#GETARG!
#FIXP!#EQUAL !|#PARSCL!~#ERROR ! #SCOPY !#CANT!#SWT 
 
"%&(0&