:J&J9 9QUIT$ "ok, "QUIT$ "Terminal type '*s' not supp9 9orted"<*s*#x"B "D*c"H                 T9 9otal"` Change"h                    Total Change : :/ Sec"Up Time:   *5i:*2,,0i:*5,2,0r",*7,2r"29 9Disk Accesses:  *8l *6l *5,1r"PUser Time: *5i:*2,,09 9
i:*5,2,0r"n*7,2r"tPage Faults:    *8l *6l *5,1r9 9"I/O Time:  *5i:*2,,0i:*5,2,0r"0*7,2r"6Buf9 9fer Hit Rate: *7,2r% *5l *5,1r"XName   Pid  Cp Tota9 9l  dCpu  Pct  Mem |"Name   Pid  Cp Total  dCpu  Pc9 9	t  Mem |"(Name   Pid Time  dCp  Pct| "DName   P9 9id Time  dCp  Pct| "`Name   Pid Time  dCp  Pct| 9 9"|Name   Pid  Mem  dCp  Pct| "Name   Pid  Mem  dCp9 9  Pct| "4Name   Pid  Mem  dCp  Pct| "P	Available9 9 commands are:"hl   Use LONG format"|
s   Use SH9 9ORT format"m   Use SHORT MEMORY format".c   CL9 9EAR screen and redraw data"P	q      \"Z	cntrl-p >9 9  Quit"j	BREAK  /"tx   Execute a PRIMOS command9 9"?   Display this information"0Type any characte9 9r to continue	A*	A+acPA@	A,		+	A-	A.9 9	A/
	Usage: mon [<sample interval>]. acRA@Q@"A@	%6	A; ;	0acTQ@"A@0G;		AQ,n	AA
acVC@D5AQ,nIacXa@Q@PA@; ;acZQ@P	1aG\Q,paQ,rQ,pQ,uQ,ras^ac`A@,a
@bQUIT$ 	ac`A@A@5 5acdQ@f	%~acfA@a@Q@facVA@	}achA@Q@dacjA@		
< <,aSl		,aSn         @ 2A3@ 4	@ 55MQ,pQ',nacPA@Q,pG.	@5acp9 9A@6	A
#acrA@7	2AactA@7	78	7,aSl	A2	acvQ@dA@9 9a@<Q@PQ@eacjA@	19LacjA@		7
aac\Q@,xh	A:	A4H9 9	8%xn	%{b	;LIIiI	M
m,aKl9 9	<		,aSn           5		,aSn           5	<=L	 !"#5< <A	7>acxa@BQ@dA@9	9@H9	19aczQ@dA@9Q@dQ@e4	@ 291B?ac|; ;'Q@"Q@dA@1A@?aczQ@dA@Q@dQ@eacjA@ac~A@	@ac~A@acA@3A@: :acQ@"A@ac~A@@A(	>                AL)B	>%5	(9@	acvQ@dA@9: :a@DA@7yacjA@5ac,a
@Q@BA@acQ@Q@A@acQ@Q@ : :A@,aK
	9@?acQ@nQ@nA@?,aGQ,pac
A@Q@,pA@A@BA@; ;	A09@ADQGCQ,zac
A@Q@,zA@A@BA@0	A0,ag
iNNQQ,pac
A@; ;$Q@,pA@A@BA@QQ,pac
A@Q@,pA@A@BA@,aGQ,pac
A@Q@,pA@9 9A@BA@	@ ,aS$acvA@A@a@HacvA@A@a@`acvA@A@a@h6 6	AC,aK	AZQ,|,aKQF	A]Q?,|Q,~,aKQH	A]Q?,|Q,9 9,aK	A]A?Q,,aK	AZQ;,Q,,aK	A]Q?,|Q,,aK	A]Q?,|Q,: :,aK'QJQ,
Q
QQ,QQQQQQQ,Q,	A]	Q?,Q,Q,
: :	A]	Q?,Q,Q,	A]*Q,|Q?,Q,QQ,Q'%#QQ,pQ,|A;Q,|Q,p9 9	A]Q,Q,|Q?,Q,$AQ,:acQ@,A@DA@EQ@,acvA@A@a@; ;*A@DA@EQ@,acA@acvA@A@a@,Q@,acvA@A@a@2,a
@	Q@,
Q@,ac; ;9Q@,A@DA@EQ@,acvA@A@a@PA@DA@EQ@,acA@acvA@A@a@nQ@,acv; ;9A@A@a@tQ@
Q@,Q@,acQ@,A@DA@EQ@,acvA@A@a@A@DA@EQ@,ac< <)A@acvA@A@a@0Q@,~acvA@A@a@6Q@,Q@,Q@,7,aKQD	A]G?S: :Q,|,aK	AZ-Q,Q;,|Q,QQQQQ
QQQQQQQ8 8*QQ"Q$Q&Q(Q*Q,Q.Q0Q2Q4Q6Q8Q:	A]	G?bQ;,Q,; ;,aS8,aKl	F(acvA@A@a@XacA@acvA@A@a@acvA@: :8A@a@(acA@acvA@A@a@DacvA@A@a@`DacvA@A@a@|acA@9 9acvA@A@a@acvA@A@a@4a/	FGL	0b	E
~9 9	@ ,aS 0ac"A@A@Q@Q@"ac"A@A@Q@Q@$ac"A@A@Q@Q@&ac"; ;9A@A@Q@Q@(ac"A@A@Q@
Q@*ac"A@A@Q@Q@,ac"A@A@Q@Q@.; ;9ac"A@A@Q@Q@0ac"A@A@Q@Q@2ac"A@A@Q@Q@4ac"A@A@Q@; ;!Q@6ac"A@A@Q@Q@8ac"A@A@Q@Q@:	A09@ADQKD	AQGGQ,QGg9 9Q,zQGgQ,ac"Q	@,A@0Q	@,zQ	@,	A0,ag
7,aKn         @H,a[ 	M9 9,an         3Qd	@H?aczA@3A@A@?Q@e	2AaczQ@dA@Q@dQ@eQ	4; ;	A
acjA@	@ 4^acjA@e	2AacQ@dA@l	9B?acQ@d: :A@?p0aczA@A@Q@dQ@eacxa@PA@A@acxa@hA@A@ acxa@|A@; ;9A@ acxa@A@A@ acxa@.A@A@ acxa@PA@!A@ acxa@ZA@"A@ acxa@j; ;9A@#A@ acxa@tA@$A@ acxa@A@A@ acxa@0A@%A@acjA@acrA@Hacz: :A@A@Q@dQ@eq	+Ls!	. y!q!}!~!!!9 9!!!!!!!!!"	!#
!$!!!%y9 9!y! !y!y!"y!)!+!7!Py!!!: :y!?y!cy!k!
ly!y! y<,d$zD9 9Amlc    &Clock   Disk1   
Disk2   0Farnet  Idle1   Idle2   NMpc1    X7 7Mpc2    bPlot    lRing    :Smlc    vSpare   2t?hKu0!,$!.< <$
!<$!4$!:$!6$!8$!>$!2$!F$!$QUIT$ !$!$                                 D$!x#GETARG; ;!
#VTINIT!$#DUPLX$!#LENGTH!#MAPDN !#CHKINP!z#CTOL!#MKONU$!#QUIT!v#SLEEP$!|#ERROR ; ;!~#CTOC!#BREAK$!#PRINT !#VTINFO!#VTUPD !#T1IN!#VTPRT !#VTPUTL! #VTCLR !"#VTGETL) )!&#VTMOVE!(#SYS$$ !*#MOVE$ !0#GMETR$!@#HMS !B#VTPAD !H#PPS 
 
"%,jJ0&&

L, PPS 9 9"-*,6h *3i *3i:*2,,0i:*2,,0i *5,2r *5,2r *3i |">*9 9,6h *3i *3i*c *4,1r *4,1r|"Z*,6h *3i *4i *4,1r *4,1: :r|	QK	AC		QKQ_		A]A?Q,aKt	AZQQ;QQK9 9	A]G?Q;QQA;,avQacxQ@A@"A@#Q@Q	@AY$,aKz	M: :,a|         %,aKz	M,a|         @&	M,a|         8&@B',aK~	(Qw,aGQ9 9&acA@%A@'a@Q	@Q	@A@"A@#A@$Q@Q@Q	@	"A	#A	$)	*; ;v	#)	*{s	")	*#acA@%A@'a@>Q	@Q	@A@)A@*Q@Q@pQw9 9,aG QacA@%A@'a@ZQ	@Q	@Q	@Q@Q@Q	(+L	R:: :;<=q>2acA@,akz	@	!H!P!QH!hH!k!m< <H!sH$dz!$!|$!$!$                                 $!~$!#HMS !
#VTPRT !#VTPAD 
 
"%F,0&

"" HMS : :	QKA?	@AYQS	AZ	G;Q_A?	AX@AYQSacQ	@G@QS			p	 	x!#AMOD
 
"%."0&

" QUIT: :QUIT$ 	acA@,a
@QUIT$ acac!!$QUIT$ !#BREAK$!#VTSTOP!#SWT 
 
"%&"0&