[cc]mc |
.hd fsubc "interface to Prime DBMS Fortran subschema compiler" 08/27/84
[cc]mc
fsubc <input file>
         [-l [<listing file>]]
         [-z <FSUBS option>]
.ds
'Fsubc' serves as the Subsystem interface to the Prime DBMS
Fortran subschema compiler (FSUBS).
It examines its option specifications and checks them for consistency,
provides Subsystem-compatible default file names for the listing
and output files as needed, and then produces a
Primos FSUBS command and causes it to be executed.
.sp
The "-l" option is used to select the name of the file to receive the
listing generated by the compiler.
If a file name follows the option, then that file receives the listing.
If the "-l" option is specified without a file name following it
or is not specified,
a default filename is constructed from the input filename by changing
its suffix to ".l".
.nh
For example, if the input filename is "gonzo.fsub", the listing file will
be "gonzo.l";
if the input filename is "bar", the listing file will be "bar.l".
.hy
.sp
The input filename must be a disk file name (conventionally
ending in ".fsub").
.sp
In summary, then, the default command line for compiling a file named
"file.fsub" is
.sp
.nf
     fsubc  file.fsub  -l file.l
.sp
which corresponds to the FSUBS command
.sp
     fsubs -i *>file.fsub -l *>file.l
.sp
.fi
.es
fsubc file.fsub
fsubc payroll.fsub -l l_payroll
fsubc funnyprog.fsub -z"-newopt"
.me
.in +5
.ti -5
"Usage: fsubc ..." for invalid option syntax.
.ti -5
"missing input file name" if no input filename could be found.
.ti -5
"<name>: unreasonable input file name" if an attempt was made to read
from the null device or the line printer spooler.
.ti -5
"Sorry, the listing file must be a disk file" if the listing
file was directed to a device file.
.in -5
.bu
'Fsubc' pays no attention to standard ports.

There is no way to avoid getting a listing file.
.sa
[cc]mc |
ddlc (1), f77c (1), fc (1), fdmlc (1), ld (1), bind (3)
[cc]mc
