.hd st_profile "statement-level profile" 03/25/82
st_profile  [ <count_file> ]  <source_code_file>
.ds
'St_profile' is used to convert the profiling information generated
by a Ratfor program processed with the "-c" option into a readable
report.
The optional <count_file> argument is the name of a statement_level
profile data file generated by a profiled program; if omitted,
the default name of "_st_profile" is assumed.
The <source_code_file> argument is the name of the file containing
the Ratfor source code for the program being profiled.
.es
st_profile rp.r
st_profile guide_profile fmt.r
.fl
_st_profile is the default <count_file>.
.me
"Usage: st_profile ..." if no arguments given.
.br
"can't open" if files are inaccessible.
.bu
See Reference Manual entry for 'rp'.
.sp
Seems to leave out the last line of source code.
.sa
rp (1), profile (1), c$init (6), c$incr (6), c$end (6)
