.hd systat "check on Subsystem status directories" 03/20/80
systat
.ds
'Systat' is a shell program which contains
commands to list the contents of the gossip
directory (names of users with pending messages from the
'to' command), and the mail directory (names of users
with undelivered mail).
.es
systat
.fl
=gossip= for messages from 'to'
.br
=mail= for messages from 'mail'
.sa
mail (1), to (1), lf (1)
