42"< <$cCDMACHac	A,aSCDMACH,akCDMACH	@,aKCDMACH,agCDMACH	@ac: :ac,aK	CDMACH	C,aK
CDMACH	Aacac ac",aK
CDMACH	A
9 9ac$&ac&ac(ac*ac,ac.!@!$CDMACH!$CDMACH!$	CDMACH!< <$
CDMACH!#INITI0!#INITJ0!#MICRQ0! #EXECU0!"#ADDES0!$#BARRE0!&#EXECV0!(#TERMI0!*#TRACH0 !,#SELEC0!.#TERMJ0!0#SWT 
 
"%""0&rZ$ ADDES0: :$cCDMACH"" in adder_op: can't happen: :ac:ac<,aK>%CDMACHQ,aK@'CDMACHQ,aKBMCDMACH	",aKDNCDMACH	A
8 8	acFQ@Q@,aSH)CDMACHQQ,aSH)CDMACHQacJQ@A9 9,aSH)CDMACH#QG+Q,aSH)CDMACH.QAQ,aKDNCDMACH	A
acF: :Q@Q@,aSH)CDMACHAQQ,aSH)CDMACHJ7QQG2,aSH)CDMACH: :QQacJQ@Q,aKDNCDMACH	A
acFQ@Q@,aSH)CDMACHfQQ9 9,aSH)CDMACHoZQQ,aSH)CDMACHvQGWQ,aSH)CDMACH}QG9 9acJQ@,aSH)CDMACHQacJQ@G
QQQacJQ@,aSH)CDMACH5 5	QQQ,aKDNCDMACH	A
acFQ@Q@,aSH)CDMACH0QQ; ;,aSH)CDMACH9&QQ,aSH)CDMACH@QG;	BQ,aKDNCDMACH	A
acF5 5Q@Q@,aSH)CDMACHRQQ,aSH)CDMACH[GQGacJQ@9 9,aSH)CDMACHbQacJQ@,aSH)CDMACHmQ	BQ,aKDNCDMACH	A
acF9 9Q@Q@,aSH)CDMACHQQ,aSH)CDMACHv	"B#L           $/; ; 8R[w~'AHcnwacLa@ ,awBMCDMACHaK	AQQ9 9,aWH)CDMACH,aSN+CDMACHQQ,aKN+CDMACHQQQQacJQ@acJQ@< <,aSP-CDMACH.	@,aSN+CDMACH,aSP-CDMACHO,aKH)CDMACH	A,aSR0CDMACH,aKH)CDMACH9 9GK	CJ,aST1CDMACH,aKH)CDMACHGf	CC,aSV2CDMACH,aKP-CDMACH	A,aSX/CDMACH		7 7d]!>$%CDMACH!@$'CDMACH!H$)CDMACH!N$+CDMACH!P$-CDMACH!X$/CDMACH!R: :$0CDMACH!T$1CDMACH!V$2CDMACH!B$MCDMACH!D$NCDMACH!F#ADDWI0!:#XINPV0!<#YINPV0!J#F$OR77 !L#ERROR 
 
"%,$0&+& ADDWI09 9	@QQK	@"QK		@#A$@H%#"B(acA@%	MQQ		"B`"#B`#A$%( Q		!+!#F$LS
 
"%.&0&D@& BARRE07 7$cCDMACH"in barrel_switch: can't happen,aK0OCDMACH	"5 5,aK2)CDMACH,aS44CDMACH,aK2)CDMACHac6,a
@83CDMACH,aS44CDMACH		9 9,a_83CDMACH	#,aK2)CDMACHac:A@#,aS44CDMACH                                            aK2)CDMACHac6,a
@83CDMACH: :Q		,a_83CDMACH	#,aK2)CDMACH	ac:A@#Q,aS44CDMACH	"B$L: :	ac<a@5		! D!4$)CDMACH!:$3CDMACH!6$4CDMACH!2$OCDMACH!8#F$RS71 !<#F$LS71!>#ERROR 
 
"%(&0&YJ( CONDJ0: :$cCDMACH""in condition_adjust: can't happen	4"QKQ_	B: :	#	Q_	$QKac2A@$ac4A@#	t",aG6CDMACHQAQAQCw	%9 9	&	A,aS8?CDMACH(	A,aS:=CDMACH,	@ ,aS<<CDMACH,aS:=CDMACH0	A9 9,aS>GCDMACH6	A,aS@@CDMACH:	A,aS<<CDMACH>	A,aSB>CDMACHB'	&B'7 7	L	()-17;?CacDa@F		!!
!Y!:$CDMACH!@9 9$<CDMACH!>$=CDMACH!F$>CDMACH!<$?CDMACH!D$@CDMACH!B$GCDMACH!6#F$RS!8#F$RT!H#ERROR 
 
"%.(0&d( DUMPS09 9$cCDMACH",*nS-memory dump -- Enter <return> to quit*n"<9 9Starting address (1-2048): *i"ZEnding address      9 9
     : *i"xEnding address out of range"Address9 9es in backward order"0Smem (*i)*13t= "@*-15,-8l: :"J*-15lacPA@	A
"A
acRA@a@	"A
acTA@A@9 9acVA@a@<A@#	#%$$	%#	@%'acVA@a@ZA@$	$%; ;66	%5	@7acXa@x9	$$#AacXa@>B	@ %#&%?9 9	acTA@A@NacRA@a@0A@&,aKZ$bCDMACH	A
A7&,aG\ZCDMACHQacR: :A@a@@Q	@`A7&,aG\ZCDMACHQacRA@a@JQ	@o	(%@A&$$KK9 9	%M=@%acTA@A@G(		!u!v!!!
3 3!!b$ZCDMACH!`$$bCDMACH!V#ISATTY!X#PRINT !Z#PUTCH !\#INPUT !^#REMARK
 
"%*(0&)*" EXECV08 8$cCDMACHacac,aKCDMACH	A
,aKCDMACH	A		,aSCDMACH		9 9,aSCDMACHacac,aKCDMACH,aS CDMACH,aK"CDMACH	A
,aKCDMACH	A9 9"ac$ac&#		!!)!$CDMACH!"$CDMACH! $CDMACH!$CDMACH3 3!$$CDMACH!$CDMACH!#NANOG0!#SETCO0!#UPDAT0!#UPDAU0!&#CONDJ0!(#MEMDE0
 
"%""0&h,& EXECU07 7$cCDMACH	4"QKQ_	B#	Q_	$QKacA@$acA@#	t"	,aSCDMACH: :,aKCDMACH	A
,aG	CDMACHQAQAQCw	%,aG	CDMACHQA: :QAQCw	C>%,aS3CDMACH,aKCDMACH	A
,aG	CDMACH	QAQ: :	AQCw,aS!CDMACHB,aK CDMACH	A
,aG	CDMACHQAQAQ: :Cw,aS"CDMACHV		!!h!!!!	!h!$CDMACH! : :$	CDMACH!$CDMACH!$$CDMACH!($CDMACH!*$CDMACH!&$!CDMACH!"$3CDMACH!#F$RS!#F$RT
 
"%,&0&L$ INITI09 9$cCDMACH"Begin execution at address: *i"0Number of cl9 9ock cycles to simulate: *i"XNumber of cycles betwee9 9n traces: *i"|Begin tracing at address: *i"End9 9 tracing at address: *i"6Print S-memory and registe9 9rs in octal? *s"`"Dump S-memory upon termination? *s5 5ac	@ ,aSHCDMACH,aSICDMACH,aS
JCDMACH,aSKCDMACH,aSLCDMACH	@ 7 7,aSNCDMACH	@ ,aSMCDMACH,aSOCDMACH	@ ,aSQCDMACH,aSRCDMACH,aSSCDMACH	@ ; ;,aSTCDMACH	@ ,aS[CDMACH,aS PCDMACH,aS"YCDMACH,aS$ZCDMACH,aS&WCDMACH,aS(XCDMACH5 5	@ ,aS*VCDMACH,aS,UCDMACH	@,aS.CDMACH,aS0CDMACH,aS2CDMACH,aS4CDMACH; ;,aS6#CDMACH,aS8:CDMACH	@ ,aS:3CDMACH,aS<!CDMACH,aS>"CDMACH,aS@6CDMACH,aSB7CDMACH; ;,aSD8CDMACH,aSF9CDMACH	@ ,aSH<CDMACH,aSJ=CDMACH,aSL>CDMACH,aSN?CDMACH,aSP@CDMACH9 9,aSRACDMACH,aSTBCDMACH,aSVCCDMACH,aSXDCDMACH,aSZECDMACH,aS\FCDMACH,aS^GCDMACH9 9	@ ,aS`CDMACH		,aSbCDMACH,aSdCDMACH	@ ,aSfCDMACH,aShCDMACH	acjA@a@5 5,a
@lCDMACH,aKlCDMACH,aSnCDMACH	acjA@a@0,a
@pCDMACH	acjA@a@X: :,a
@r$`CDMACH	acjA@a@|,a
@t$^CDMACH	acjA@a@,a
@v$_CDMACHacjA@a@6Q@; ;Q	CC"Q	CCA	",aSx$bCDMACHacjA@a@`Q@Q	CC"Q	CCA	"5 5,aSz$aCDMACHac|		!!vL!YL!yL!j$CDMACH!l$CDMACH!t9 9$CDMACH!f$CDMACH!h$CDMACH!r$CDMACH!d$CDMACH!p$CDMACH!2$CDMACH!4$CDMACH!69 9$CDMACH!8$CDMACH!@$!CDMACH!B$"CDMACH!:$#CDMACH!>$3CDMACH!D$6CDMACH!F$7CDMACH!H9 9$8CDMACH!J$9CDMACH!<$:CDMACH!L$<CDMACH!N$=CDMACH!P$>CDMACH!R$?CDMACH!T$@CDMACH!V9 9$ACDMACH!X$BCDMACH!Z$CCDMACH!\$DCDMACH!^$ECDMACH!`$FCDMACH!b$GCDMACH!
$HCDMACH!9 9$ICDMACH!$JCDMACH!$KCDMACH!$LCDMACH!$MCDMACH!$OCDMACH! $TCDMACH!0$UCDMACH!.9 9$VCDMACH!$NCDMACH!$$PCDMACH!$QCDMACH!$RCDMACH!$SCDMACH!*$WCDMACH!,$XCDMACH!&9 9$YCDMACH!($ZCDMACH!"$[CDMACH!x$$^CDMACH!z$$_CDMACH!v$$`CDMACH!~$$aCDMACH!|$$bCDMACH!                                                                   INITK0!n#INPUT !#INITL0
 
"%
$0&1P
* INITK0< <$cCDMACH"Usage: dmach <hex file>	4"QKPQ_N	B#	Q_P	$QKL9 9ac(A@$ac*A@#	t"ac,A@Q@A@	BCac.a@!	ac0Q@A@	%: :	Cac2Q@/	ac4Q@fA@%	%=	A&ac6Q@fA@&A@	't',aG8\CDMACH; ;'QRac6Q@fA@&A@QSRQRQLAQNAQPCw	CQRQLAQN5 5	AQPCw	(ac6Q@fA@&A@A7	(,aS:\CDMACHac6Q@fA@&A@A7	(9 9,aS<]CDMACHac6Q@fA@&A@A7	(,aS>^CDMACHac6Q@fA@&A@A7	(,aS@_CDMACH: :g4<		t',aSB]CDMACHacDA@%		!}!1!1!!!!9 91!f1!@!B$\CDMACH!L$]CDMACH!D$\CDMACH!F$]CDMACH!H$^CDMACH!J$_CDMACH3 3!:#OPEN!>#GETLIN!@#GCTOI !6#GETARG!2#F$RS!4#F$RT!8#ERROR !<#CANT!N#CLOSE 
 
"%~*0&
kT& INITL09 9$cCDMACH",*nLoad S-memory -- Enter <return> to quit*n"<9 9Starting address (1-2048): *i"ZEnding address      9 9
     : *i"xEnding address out of range"Address: :es in backward order"0Smem (*i)*13t= "@*lacD; ;A@	A
"A
acFA@a@	"A
acHA@A@acJA@a@<A@#	#%$: :$	%#	@%'acJA@a@ZA@$	$%66	%5	@78 8acLa@x9	$$#AacLa@>B	#%"A
acFA@a@0A@%LA7%9 9,aGNZCDMACHQacJA@a@@Q	@	A%$$iIIG(		!vk!k0 0!
k!!R$ZCDMACH!H#ISATTY!J#PRINT !L#PUTCH !N#INPUT !P#REMARK
 
"%(&0&" INITJ09 9$cCDMACH,aKCDMACH,aSCDMACH,aKCCDMACH	A
,aK$\CDMACH,aS#CDMACH		!" "$CDMACH!$CDMACH!$$\CDMACH!$#CDMACH!$CCDMACH
 
"%""0&^& MEMDE09 9$cCDMACH")*nError -- Bad external operation (*i)*n":*n9 9)Error -- S-memory address out of range*n"f	*nError -9 9- Memory not ready for read*n"*nError -- Memory no: :t ready for write*n	4"QKQ_	B#	Q_	$QKac6A@$ac8: :A@#	t",aG:                                                                   DMACHQAQAQCw	%A		'	%%-	%05 5,	%3/	%62ac<A@a@A@%		5	%%C	%FBE: :,aK>6CDMACH	B ,aW@8CDMACH,aSB9CDMACHF,aKD7CDMACH	B ,aW@8CDMACH,aSB9CDMACH: :N,aKB9CDMACH	%\\	%[	@]ac<A@a@:acFacH_	%%n< <	%qmp,aKJCDMACH	A
ac<A@a@fu,a7B9CDMACH,aKLZCDMACH,aSN$\CDMACH8 8,aKPCDMACH	@D,aSJCDMACHq,aKRCDMACH	A
ac<A@a@,aKT:CDMACH9 9,a7B9CDMACH,aSLZCDMACH,aKPCDMACH	@D,aSRCDMACH		!u!!!5 5!!!!!X$CDMACH!R$CDMACH!Z$CDMACH!B$                                                                   DMACH!T: :$ZCDMACH!V$$\CDMACH!F$6CDMACH!L$7CDMACH!H$8CDMACH!J$9CDMACH!\$:CDMACH!>#F$RS!@#F$RT !D#PRINT !N#TERMJ0!P#SWT 
 
"%,&0&%,& MICRQ06 6$cCDMACH	4"QKQ_	B#	Q_	$QKacA@$acA@#	t",awCDMACH9 9,aK\CDMACH,aS	CDMACH,aG	CDMACHQAQAQCw	CC,aS
CDMACH	A
9 9	@ ,aSCDMACH,aSCDMACH,aS CDMACH,aG	CDMACHQAQAQCw9 9,aS"CDMACH0,aG	CDMACHQAQAQCw	@HCC%,aG	CDMACHQ: :AQAQCw	AA	%,aSCDMACH,aG	CDMACHQAQAQCw; ;	CC%,aG	CDMACHQAQAQCw	@HCCA	%,aSCDMACH,aG	CDMACHQ: :AQAQCw	CC,aS CDMACHH		!!!!!!!5 5!%!$CDMACH!*$CDMACH! $	CDMACH!"$
CDMACH!$$CDMACH!&$CDMACH!( $CDMACH!$\CDMACH!#F$RS!#F$RT
 
"%,&0&p4& NANOG06 6$cCDMACH	4"QKQ_	B#	Q_	$QKacA@$acA@#	t",a7CDMACH9 9,aK\CDMACH,aSCDMACH,aK]CDMACH,aSCDMACH,aK^CDMACH,aS CDMACH,aK"_CDMACH; ;,aS$                                                                   DMACH,aGCDMACHQAQAQCw,aS&CDMACH,aGCDMACHQA7 7QAQCw	@HCC,aS(CDMACH,aGCDMACHQAQAQCw	@HCC9 9,aS*CDMACH,aGCDMACHQAQAQCw	@HCC,aS,CDMACH		!p!: :!!!!p!$CDMACH!$CDMACH!"$CDMACH!&$CDMACH!*$                                                                   DMACH!,9 9$CDMACH!.$CDMACH!0$CDMACH!2$CDMACH!$\CDMACH! $]CDMACH!$$^CDMACH!($_CDMACH!	 	#F$RS!#F$RT
 
"%,&0&-:" PRINT09 9$cCDMACH"Phase *i Mpcr: *-4i*n"&Clock: *-5i*4xA1: *-19 971,-8l*4xB   : *-11,-8l*4xCtr: *-4,-8i*4xBr1: *-4,-8i*n9 9"r3Mpcr : *-5i*4xA2: *-11,-8l*4xMir : *-11,-8l*4xLit: 9 9*-4,-8i*4xBr2: *-4,-8i*n">Ampcr: *-5i*4xA3: *-11,-89 93l*4xBmar: *-11,-8i*4xSar: *-4,-8i*4xMar: *-4,-8i*n"
9 97Clock: *-5i*4xA1: *-11l*4xB   : *-11l*4xCtr: *-4i*4xBr19 9	: *-4i*n"J)Mpcr : *-5i*4xA2: *-11l*4xMir : *-11l*4xL9 9it: *-4i*4xBr2: *-4i*n"
Ampcr: *-5i*4xA3: *-11l*4xB9 9%mar: *-11i*4xSar: *-4i*4xMar: *-4i*n"JMst  Lst  Abt9 97  Aov  Cov  Sai  Rdc  Gc1  Gc2  Lc1  Lc2  Lc3  Ex1  Ex29 9  Ex3  Int*n"% *i*4x*i*4x*i*4x*i*4x*i*4x*i*4x*i*4x*: :i*4x"F(*i*4x*i*4x*i*4x*i*4x*i*4x*i*4x*i*4x*i*nacn: :A@A@,aKpCDMACH	%acrA@a@,a
@tCDMACH,a
@pCDMACH
,aKv$bCDMACH; ;	A
acrA@a@&,a
@xCDMACH,a
@zCDMACH,a
@|CDMACH,a
@~"CDMACH,a
@6CDMACHacr: :A@a@r,a
@CDMACH,a
@CDMACH,a
@:CDMACH,a
@!CDMACH,a
@
7CDMACH	acrA@a@>8 8,a
@CDMACH,a
@CDMACH,a
@9CDMACH,a
@3CDMACH,a
@8CDMACH	acrA@a@
; ;,a
@xCDMACH,a
@zCDMACH,a
@|CDMACH,a
@~"CDMACH,a
@6CDMACH	acrA@a@J,a
@CDMACH; ;,a
@CDMACH,a
@:CDMACH,a
@!CDMACH,a
@
7CDMACH	acrA@a@
,a
@CDMACH,a
@CDMACH6 6,a
@9CDMACH,a
@3CDMACH,a
@8CDMACHIacrA@a@JacrA@a@,a
@0CDMACH9 9,a
@1CDMACH,a
@2CDMACH,a
@/CDMACH,a
@ACDMACH,a
@ BCDMACH,a
@"CCDMACH,a
@$<CDMACH; ;	acrA@a@F,a
@&=CDMACH,a
@(>CDMACH,a
@*?CDMACH,a
@,@CDMACH,a
@.DCDMACH,a
@0ECDMACH: :,a
@2FCDMACH,a
@4GCDMACH		!!u-!
-!|$CDMACH!x$CDMACH!t$CDMACH!9 9$CDMACH!$CDMACH!~$CDMACH!$CDMACH!$CDMACH!$CDMACH!$!CDMACH!$"CDMACH! 9 9$/CDMACH!$0CDMACH!$1CDMACH!$2CDMACH!$3CDMACH!$6CDMACH!$7CDMACH!$8CDMACH!9 9$9CDMACH!
$:CDMACH!($<CDMACH!*$=CDMACH!,$>CDMACH!.$?CDMACH!0$@CDMACH!"$ACDMACH!$< <$BCDMACH!&$CCDMACH!2$DCDMACH!4$ECDMACH!6$FCDMACH!8$GCDMACH!z$$bCDMACH!r#PUTCH !v#PRINT 
 
"%""0&R* SELEC09 9$cCDMACH"*in select_successor_address: can't happen	4": :QKQ_	B#	Q_	$QKac:A@$ac<A@#	t",aK>
CDMACH	A,ak@CDMACH: :	@,aK@CDMACH,aSBCDMACH,aKDCDMACH	A
,aGFCDMACHQAQA6 6QCw	%&,aGFCDMACHQAQAQCw	%6	%&5 5,ak@CDMACHIL,aK@CDMACH,aSHCDMACH	B,aS@CDMACHM,aK@CDMACH	@D6 6,aS@CDMACHU,aKHCDMACH	B,aS@CDMACH[,aKHCDMACH	B,aSBCDMACHa< <,aK@CDMACH	',aKHCDMACH	B,aS@CDMACH	',aSHCDMACHg,aKHCDMACH	@D,aS@CDMACH6 6sH	&B(L	IJNV\bhtacJa@y	%%,aK@CDMACH9 9,aSBCDMACH"		!!!!!!H$CDMACH!D$
CDMACH!L$CDMACH& &!J$CDMACH!N$CDMACH!F$CDMACH!@#F$RS!B#F$RT!P#ERROR 
 
"%0*0&X& SETCO07 7$cCDMACH"in set_condition: can't happen,aK0CDMACH	"9 9,aK2<CDMACH	#,aK4=CDMACH	#,aK6>CDMACH	#@ ,aS6>CDMACH,aK8?CDMACH6 6	#@ ,aS8?CDMACH,aK:0CDMACH	#,aK<1CDMACH	#,aK>2CDMACH	#!: :,aK@/CDMACH	#%,aKBACDMACH	#@ ,aSBACDMACH),aKDBCDMACH	#@ ,aSDBCDMACH08 8,aKFCCDMACH	#@ ,aSFCCDMACH7,aKH@CDMACH	#@ ,aSH@CDMACH>,aKJDCDMACH	#@ 8 8,aSJDCDMACHE,aKLGCDMACH	#@ ,aSLGCDMACHL,aKNECDMACH	#@ ,aSNECDMACHS9 9,aKPFCDMACH	#@ ,aSPFCDMACHZ	"B$L           "&*18?9 9FMT[acRa@a,aKTCDMACH	A
	#,aSVCDMACH~	#A,aSVCDMACH8 8		!0$CDMACH!T$CDMACH!V$CDMACH!@$/CDMACH!:$0CDMACH!<$1CDMACH!>$2CDMACH!29 9$<CDMACH!4$=CDMACH!6$>CDMACH!8$?CDMACH!H$@CDMACH!B$ACDMACH!D$BCDMACH!F$CCDMACH!J! !$DCDMACH!N$ECDMACH!P$FCDMACH!L$GCDMACH!R#ERROR 
 
"%&&0&" TERMI0; ;$cCDMACH,aKCDMACH	B,a_CDMACH	C	A,aSCCDMACH	@ ,aSCDMACH,aKCDMACH8 8	B,a_CDMACH	C	A,aSBCDMACH	@ ,aSCDMACH		!$CDMACH!$CDMACH! $CDMACH!$BCDMACH!$CCDMACH
 
"%""0&D" TERMJ09 9$cCDMACH"**nEnd of Simulation - Machine State is:*nac:: :	A@a@ac<,aK>$aCDMACH	A
ac@		!u!@$$aCDMACH!<#PRINT !>#PRINT0!B #DUMPS0
 
"%""0&" TRACH0< <$cCDMACH,aKCDMACH,ag$^CDMACH,ag$_CDMACH	@,aKCDMACH	M,a$`CDMACH7 7	@A	ac		!$CDMACH!$CDMACH!$$^CDMACH!$$_CDMACH!$$`CDMACH!#PRINT0
 
"%""0&VD$ UPDAV0; ;$cCDMACH"#in update_b_register: can't happen,aK4TCDMACH	"9 9	@,aS6CDMACH,aK8)CDMACH,aS6CDMACH	@,aS6CDMACH,aK8)CDMACH; ;ac:,a
@<4CDMACH,aS6CDMACH                                            aK<4CDMACH,aS6CDMACH,aK>#CDMACH,aS6CDMACH6 6,aK@:CDMACH,aS6CDMACH$,aK>#CDMACHac:,a
@<4CDMACH,aS6CDMACH): :,aK@:CDMACHac:,a
@<4CDMACH,aS6CDMACH2	"B#L           CDEFG6 6	 %*3HacBa@;		!6$CDMACH!>$#CDMACH!8$)CDMACH!<   $4CDMACH!@$:CDMACH!4$TCDMACH!:#F$OR77!B#ERROR 
 
"%$$0&>:$ UPDAW08 8$cCDMACH"in update_ctr: can't happen,aK,VCDMACH	"	@ 9 9,aS.ACDMACH,aK0!CDMACH	AB(,aS2"CDMACH,ak2"CDMACH	@	,ag2"CDMACH	@ ; ;,aS2"CDMACH	A,aS.ACDMACH	@ ,aS.ACDMACH,aK44CDMACHAA	@,aS2"CDMACH9 9	"B#Lac6a@*		!9$&!2$!CDMACH# #!4$"CDMACH!6$4CDMACH!0$ACDMACH!.$VCDMACH!8#ERROR 
 
"%$$0&b<" UPDAT0: :$cCDMACH,aKQCDMACH	A
,aK4CDMACH,aSCDMACH,aKRCDMACH	A
,aK4CDMACH; ;,aSCDMACH,aKSCDMACH	A
,aK4CDMACH,aSCDMACHac,aK [CDMACH	A
8 8,aK4CDMACH,aS":CDMACH,aK$PCDMACH	A
,aK4CDMACHA	@,aS&CDMACH%5 5,aK(WCDMACH	A
,aK4CDMACH	@8A	@,aS*6CDMACH0,aK,XCDMACH	A
5 5,aK4CDMACH	@8G5	@,aS.7CDMACH<,aK0YCDMACH	A
,aK2ZCDMACH	A
: :,aK4!CDMACH,aS68CDMACHL,aK4CDMACHGA	@,aS68CDMACHQHac8ac:		U5 5)!&$CDMACH!$CDMACH!$CDMACH!$CDMACH!4$!CDMACH!$4CDMACH!*9 9$6CDMACH!.$7CDMACH!6$8CDMACH!"$:CDMACH!$$PCDMACH!$QCDMACH!$RCDMACH!$SCDMACH!(4 4$WCDMACH!,$XCDMACH!0$YCDMACH!2$ZCDMACH! $[CDMACH!#UPDAV0!8#UPDAW0!:#UPDAX0
 
"%""0&R& UPDAU0: :$cCDMACH	4"QKQ_	B#	Q_	$QKacA@$acA@#	t",aGCDMACHQ< <AQAQCw,aSHCDMACH,aGCDMACHQAQAQCw,aSICDMACH9 9,aGCDMACHQAQAQCw,aSJCDMACH,aGCDMACHQAQA; ;QCw,aSKCDMACH,aGCDMACHQAQAQCw,aSLCDMACH,aGCDMACH9 9QA	QA
QCw,aS MCDMACH,aG"CDMACHQAQAQCw	%9 9,aGCDMACHQAQAQCw	C?%,aS$OCDMACH,aG"CDMACH	QAQ9 9	AQCw,aS&TCDMACH,aG"CDMACHQA
QAQCw,aS(VCDMACH	@HC9 9,aG"CDMACHQAQAQCw	@HC:		,aS(VCDMACHK,aG*                                                                   DMACH9 9QAQAQCw,aS,UCDMACH,aGCDMACHQAQAQCw	@H9 9	CC,aS.NCDMACH,aG"CDMACHQAQAQCw	@HCC,aS0QCDMACH,aG"CDMACH: :QAQAQCw	@HCC,aS2RCDMACH,aG"CDMACHQAQAQCw: :	@HCC,aS4SCDMACH,aG"CDMACHQAQAQCw	@HCC,aS6[CDMACH,aG"CDMACH: :QAQAQCw	@HCC,aS8PCDMACH,aG"CDMACHQAQAQCw: :	@HCC,aS:YCDMACH,aG"CDMACHQAQAQCw	@HCC,aS<ZCDMACH,aG"CDMACH: :QAQAQCw	@HCC,aS>WCDMACH,aG"CDMACHQA	QA	QCw: :	@HCC,aS@XCDMACH		!!!!!!!!	!
!!	8 8!!!
!!$$CDMACH!2$CDMACH!:$                                                                   DMACH!&$HCDMACH!($ICDMACH!*9 9$JCDMACH!,$KCDMACH!.$LCDMACH!0$MCDMACH!4$OCDMACH!6$TCDMACH!<$UCDMACH!8$VCDMACH!>9 9$NCDMACH!H$PCDMACH!@$QCDMACH!B$RCDMACH!D$SCDMACH!N$WCDMACH!P$XCDMACH!J$YCDMACH!L $ZCDMACH!F$[CDMACH! #F$RS!"#F$RT
 
"%,&0&66& UPDAX08 8$cCDMACH"in update_sar: can't happen,aK,UCDMACH	"		< <,a_.3CDMACH,aS.3CDMACH,aK04CDMACHAQ		A#,aK04CDMACH	@?Q	#MQ9 9QA	@,aS.3CDMACH
	"B$Lac2a@$		!2! ( (2 !0$3CDMACH!2$4CDMACH!.$UCDMACH!4#ERROR 
 
"%*&0&KB$ XINPV0: :$cCDMACH" in x_input_select: can't happen,aK0HCDMACH	"	@< <,aS2%CDMACH,aK4!CDMACH	M,aS2%CDMACH,aK6#CDMACH,aS2%CDMACH,aK8"CDMACH9 9	M@B ,aS2%CDMACH,aK8"CDMACH	M@B Q,aK4!CDMACH	MQ,aS2%CDMACH: :,aK:CDMACH,aS2%CDMACH),aK<CDMACH,aS2%CDMACH.,aK>CDMACH,aS2%CDMACH35 5	"B#L	*/4ac@a@8		!:$CDMACH!<$CDMACH!>/ /$CDMACH!4$!CDMACH!8$"CDMACH!6$#CDMACH!2$%CDMACH!0$HCDMACH!@#ERROR 
 
"%&$0&.( YINPW09 9$cCDMACH"0in y_input_from_masked_b_register: can't happen: :"@0in y_input_from_masked_b_register: can't happen"p< <0in y_input_from_masked_b_register: can't happen,aK JCDMACH: :	"	@Q,aK"CDMACH	@Q,aK"CDMACHA	@QAQ; ;	"B#Lac$a@,aK&KCDMACH	$	@Q,aK"CDMACH5 5AQ1-	$B%L
.2ac$a@@8,aK(LCDMACH	&	@Q; ;,aK"CDMACHAQK,aK"CDMACHGGOQR	A@DQ[G	&B'LH: :LS\ac$a@p`	QQQ,aS*'CDMACH		!wVX1 15~!$$CDMACH!,$'CDMACH!"$JCDMACH!($KCDMACH!*$LCDMACH!&#ERROR 
 
"%.(0&JB$ YINPV0; ;$cCDMACH" in y_input_select: can't happen,aK0ICDMACH	"ac28 8,aK4!CDMACH	M,aS6'CDMACH,aK8#CDMACH,aS6'CDMACH,aK:"CDMACH	M@B : :,aS6'CDMACHac2,aK:"CDMACH	M@B Q,aK4!CDMACH	MQ,aS6'CDMACH9 9,aK<CDMACH	M,aS6'CDMACH+,aK>9CDMACH	M,aS6'CDMACH1	"B#L	6 6,2ac@a@7		!<$CDMACH!4$!CDMACH!:$"CDMACH!8$#CDMACH!6   $'CDMACH!>$9CDMACH!0$ICDMACH!2#YINPW0!@#ERROR 
 
"%&$0&