mx69 9SOLCOM"QUIT$ "Congratulations, You won!".Sorry...9 9"8Play again? !aGFQaQQQQasHacJacLA@: :	@ ,aSNSOLCOM	@ ,aSPzSOLCOMacRacTacVacXacZ,aKNSOLCOM	A
",aK\{SOLCOM; ;	Aac^-ac`A@4	4A	
acLa@7acLa@.<0acba@8acdA@: :$A@A@acfA@A@A@achQ@A@A@A@Q	%d	%
gacjacl9 9acn!!!m!m!m!Ym!ym!X$zSOLCOM!d${SOLCOM9 9!V$SOLCOM!P#MKONU$!N#QUITF0!R#INITI0!T#MESSA0!Z#SETGA0!\#SHUFF0!^#DEAL!`#DISPL0!b9 9#TURN!f#TALLY !h#COUNT0!j#PROMPT!l#VTENB !n#VTREAD!p#VTGETL!r#LOGRE0!t#VTSTOP!v#SWT 
 
"%@60&$ ADDCA0< <SOLCOM	Q7,aKNSOLCOM	B,aSNSOLCOMQK	9@",aKOSOLCOM	t",aS}SOLCOMQK7 7,aS~SOLCOMQKQ7,aSOSOLCOM		!!$}SOLCOM!$~SOLCOM!$NSOLCOM! $OSOLCOM
 
"%*$0&$ CARDI09 9SOLCOM	QK	9@AD,aK~SOLCOM	",aKwSOLCOMQg	"%	%0 0	@	A#		@ #	!!!!$~SOLCOM!$wSOLCOM
 
"%($0&C( CHECK07 7SOLCOM	QK	9@AD,aKSOLCOM	M=",aKSOLCOM	M=@#,aK~SOLCOM	$Q7; ;,aKjSOLCOM	A		@ %Q7,aKkSOLCOM	9@AD,aKSOLCOM	M=@%	"Q_: :	C	#%@HC.A7$,aKOSOLCOMQ_	C3;	@ &	<	A&	!C!& &C!$~SOLCOM!$SOLCOM!$OSOLCOM!$jSOLCOM!$kSOLCOM
 
"%.(0&*& CHECL0: :SOLCOM	QK	9@AD,aKSOLCOM	M=@"%	@ #		A$	($@	$%8 8	@A7$,aKNSOLCOM	A		$QS	A#		@ #	!!!!*! $SOLCOM!$NSOLCOM
 
"%,&0&G( CHECM0: :SOLCOM"	Q7,aKNSOLCOM	A		@ "	QK	9@AD,aKSOLCOM	M9 9	=#,aKSOLCOM	M=@$Q7,aKOSOLCOM	9@AD,aKSOLCOM	M=%Q7,aKOSOLCOM9 9	9@AD,aKSOLCOM	M=@&t%aK	t#ag;	&$@HC:?	@ "	@	A"	!   G!G!$SOLCOM!$NSOLCOM!$OSOLCOM
 
"%.(0&$ COUNT09 9SOLCOM	,aKvSOLCOM,a[tSOLCOMQS	A"QKA7",a[\SOLCOMQS	A"%# #		!!$\SOLCOM!$tSOLCOM!$vSOLCOM
 
"%($0&

T"& DEAL9 9SOLCOM	@ ,aStSOLCOM,aSvSOLCOM	A"@ A7",aSNSOLCOM,aS\SOLCOM	A"%: :	A"@ A7",aSjSOLCOM	A"%!		"	"@H"#	"AacA@"A@: :$)	A"	acA@A@"	"B#	(#@<		$#DD	#$acA@A@$=C9 9	A"%S22		!!T!T!4!$NSOLCOM!$\SOLCOM!$jSOLCOM! $tSOLCOM!$vSOLCOM!#ADDCA0! #MOVEC0
 
"%&&0&vp( DISPL0: :SOLCOM"   "(*2i)"*2i"(*i) "$    "*: :   ".    "4(*i)":   ">   	acBA@Q@	@ < <QacDQ@A@A@	A"A7",aKFjSOLCOM	A,aGHkSOLCOMQ
	"@H9@#acJ9 9A@A@#Q	@
	"@H9@#acDa@A@A@#+	A"%@acLA@A@8 8a@,a
@NtSOLCOMacLA@A@a@,a
@PzSOLCOM,aKRvSOLCOM	AacJA@A@	; ;,a
@TwSOLCOM	A,agRvSOLCOMc,a_RvSOLCOM	A$acLA@A@
a@A@$dacD; ;a@$A@A@
sWacDa@*A@A@	acDa@.A@A@
|	A"	("@	"%< <	@@H9@%A7",aKV\SOLCOM	A,aGV\SOLCOMQacLA@A@%a@4Q	@ acD; ;	a@:A@A@%/A7",aKXOSOLCOM	&,aKZNSOLCOM	'	'@H'@	'A	$acJ9 9	A@$A@%A@&	&9@AD,aK\}SOLCOM	&AFA7",aKZNSOLCOM	B'	('@_	'%: :	@$acDa@>A@$A@%`ac^A@		!!!!!v!: :!v!v!v!!)v!<!C!	D!
Hv!l$}SOLCOM!j9 9$NSOLCOM!h$OSOLCOM!f$\SOLCOM!V$jSOLCOM!X$kSOLCOM!^$tSOLCOM!b$vSOLCOM!d$wSOLCOM!`# #$zSOLCOM!R#DATE!T#VTPUTL!Z#DISPM0!\#VTPRT !n#VTUPD 
 
"%6(0&98& DISPM09 9SOLCOM"shdc"A23456789TJQK"$*c*c*c	QK	9@AD9 9,aK,SOLCOM	M=",aK,SOLCOM	M=@#"%	%,aK.~SOLCOM	$: :,aK0SOLCOM	$	t#aGQ
	t"aGQac2Q	@Q	@a@$Q	@
Q	@A@$		!* *!9!9!0$SOLCOM!2$~SOLCOM!4$SOLCOM!6#VTPRT 
 
"%4&0&> $ FLIPS0: :SOLCOM,aKtSOLCOM	A	,aK{SOLCOM	A
,akzSOLCOM	@,aKvSOLCOM	Aac; ;A@A@,aKtSOLCOM	A		A,aSSOLCOM		,aK{SOLCOM	AacA@9 9A@!	A"	("@+	"%	@,aKtSOLCOM	A0acA@A@,5(		8 8!!!>!$tSOLCOM!$vSOLCOM!$zSOLCOM!${SOLCOM!$SOLCOM!#MOVEC0
 
"%$$0&B$ INITI09 9SOLCOM"#Terminal type '*s' not supported*n"4Solitair9 9e">Stack:"FAces:"Ltimes thru:"XLayout:9 9"`
Commands:"j <return> -> flip stack" <card>9 9[<card>] -> move"    one card to another"2 i<r9 9ed><blk>   ->   set"J       color indicators"b < <x   ->   exit the game"z<ctrl/q> -> redraw gameac: :Q@	%acA@a@Q@acA@acA@A@acQ@	@"acA@"; ;		,aS~SOLCOM		,aS SOLCOM	@ ,aS"}SOLCOM,aS$|SOLCOM	A,aS&{SOLCOM	ac(a@4A@; ;9A@ac(a@>A@A@	ac(a@FA@A@
ac(a@LA@A@ac(a@XA@A@ac(a@`; ;9A@A@ac(a@jA@A@ac(a@A@A@ac(a@A@A@ac(a@2A@A@ac(9 9'a@JA@A@ac(a@bA@A@ac(a@zA@A@ac*A@		!. !q!~9 9!!!!!
!	!!        !!!!7 7!     !!!0!	;! !*!<${SOLCOM!:$|SOLCOM!89 9$}SOLCOM!4$~SOLCOM!6$SOLCOM!(#VTINIT!0#READC0!*#PRINT !,#ERROR !.#VTOPT !2#RND !> #VTPUTL!@#VTUPD 
 
"%.$0&_.( INTER09 9SOLCOM"SHDC"A23456789TJQK	QK	@HADQK	CQk; ;	QK	@HADQGQac$Q	@	"	ac&a@A@"	#Qk	@QK	@HADQK9 9	C	Qk%%-QK	@HADQGQac$Q	@	"	ac&a@A@"	$Qk	@#9 9	A
	$A
KN		%O	$@H9@#AD,aK(SOLCOM	%R	%&	!_! _! _!,$SOLCOM!*#INDEX !(#MAPUP 
 
"%0(0&:B$ LOGRE0: :SOLCOM"//games/sol.log" *#s *6i *s *s*n,aK0}SOLCOM	A; ;			ac2a@A@	"%%ac4A@Q@ac4A@Q@
ac4A@Q@ac6A@": :ac8A@"a@ A@Q@,a
@0}SOLCOMQ@Q@
ac:A@"		!}:!!!- -:! :!6$}SOLCOM!8#OPEN!:#DATE!<#WIND!>#PRINT !@#CLOSE 
 
"%Z$0&" MESSA0; ;"*80s	acA@A@a@Q	@acA@		!!!!#VTPRT  !#VTUPD 
 
"%&"0&

@x* MOVE9 9SOLCOM"You can't move that card"*Move is ambiguous9 9"<Move is impossible"PMove is illegal	ac`Q	@9 9	Aacba@		"	QK	BCQK	9@AD,aKdSOLCOM	M=#,aKdSOLCOM	M9 9	=@$	acfQ	@A@%	@HCachQ	@A@%+	$@HC	#&achQ	@A@&9 96	@ %'	acjQ	@A@#	@HC	('@#%L	A(	aclQ	@A@(	@HC	('@(%\; ;	A(%gSSacba@*acba@<lq		"	g	A$'zzh	$'m	@ach9 9Q	@A@%@2QK	9@AD,aKn~SOLCOM	%&%	%         @acjQ	@9 9A@&	A
	%%##	%"	@	aclQ	@A@%	A
$.achQ	@9 9A@%-acba@P		"	5		"	!}!~@!@!!!!; ;!@!v$~SOLCOM!l$SOLCOM!n#CHECL0!r#CHECK0!t#CHECM0!h#CARDI0!j#MESSA0!p#MOVES0
 
"%0*0&$ MOVEC08 8SOLCOM		acQ	@A@"	%
acA@"Q	@			!                                 #REMOV0!#ADDCA0
 
"%*$0&C$ MOVES0: :SOLCOM	@ ,aSxSOLCOMQK	9@AD,aK~SOLCOM	"A7",aKOSOLCOM
Qgac< <A@"A@	acA@"Q	@,aKxSOLCOM	AacA@Q	@!$A7",aKNSOLCOM9 9	A		"%771	%6	@#	acA@#A@"8		!C!!!% %C!$~SOLCOM!$NSOLCOM!$OSOLCOM!$xSOLCOM!#MOVEC0
 
"%*$0& $$ PROMPT9 9"*80s	acA@A@a@Q	@acA@acQ	@	B"acA@A@"ac9 9A@		!! !!P !#LENGTH!#VTPRT !#VTUPD ! #VTMOVE!"#VTPAD 
 
"%($0&" QUITF09 9SOLCOM	,aK{SOLCOM	Aac	acacac!${SOLCOM!#TALLY !#LOGRE0!
 
#VTSTOP!#SWT 
 
"%&"0&" READC00 0	acQ@A@Q	9@Q	MQSQ
		!!<!#TIMDAT
 
"%."0&#$ REMOV09 9SOLCOM	Q7,aKNSOLCOM	A			QSQ7,aKNSOLCOM	@H,aSNSOLCOM: :,aKOSOLCOMQS	9@AD,aK}SOLCOMQ7,aSOSOLCOM
QK	"	!#!# !$}SOLCOM!$NSOLCOM!$OSOLCOM
 
"%*$0&7@" SETGA0; ;SOLCOM"(c)asino or (r)egular game? ac.a@ac0A@A@A@< <ac2A@A@A@ac4Q@A@A@A@Q	%#	%&"%	@ ,aS6{SOLCOM9 9&	A,aS6{SOLCOM*ac0A@A@A@		!!!7!7!. .7!C7!c7!>${SOLCOM!6#PROMPT!8#VTENB !:#VTREAD!<#VTGETL
 
"%$"0&$
4 SHUFF05 5SOLCOM	A&	$A'$"A(&9@)"t),aSSOLCOM	acA@A@	t),aS}SOLCOM		: :,aS~SOLCOM	(&@"B"A(%)			$$A'%2	A*	(*@4	*%99 9	A+	(+@=	+%5	@	acA@A@	,	acA@A@	-A.:		"A*t"9 9,aKSOLCOM	M=',aKSOLCOM	M=@('@H9@(AD*,aSSOLCOM	""A*%wXX		7 7T	,9@/t/,aK}SOLCOM	0,aKSOLCOM	1-9@2t2,aK}SOLCOM	t/,aS}SOLCOM	0t29 9,aS}SOLCOM,aKSOLCOM	t/,aSSOLCOM	1t2,aSSOLCOM>!!!!; ;!!                                 !4!h!$}SOLCOM! $~SOLCOM!$SOLCOM!"$SOLCOM!#UNIFO0
 
"%440&
v
& TALLY 9 9SOLCOM"Casino results:  Games: *i",
Won $*-6i"6L9 9
ost $*-5i"Bwon"Flost"LYou *s $*i,akX|SOLCOM9 9	@acZA@"	"A
	@ "A#"A7#,a[\jSOLCOM	"A#%			"	"; ;	9@$,a[^}SOLCOM,aS^}SOLCOMac`A@A@a@,a
@X|SOLCOM,aK^}SOLCOM	Aac`; ;	A@A@a@,,a
@^}SOLCOM3,aK^}SOLCOM	A%ac`A@A@a@6A@%>acba@B: :Q@fA@acba@FQ@fA@V_	$A%acdQ@A@a@LQ@fA@%acfQ@: :M	$A	N	AWachA@t	A,aSj{SOLCOM		!!!!!9 9!2!4!C!f!f$jSOLCOM!t${SOLCOM!b$|SOLCOM!h$}SOLCOM!d#COUNT0!j #VTPRT !l#CTOC!n#ENCODE!p#MESSA0!r#VTUPD 
 
"%&0&


d& TURN9 9SOLCOM"Card to move: " Enter cards in form <rank><s9 9uit>-acBa@acDA@A@A@acFA@A@A@acHQ@A@A@A@	A: :	"t"QK	C	("  	A,aSJSOLCOM	t"QK	A
	%514		: :,aSL~SOLCOM		,aSNSOLCOM,5	t"QK,aSL~SOLCOMQK,aSNSOLCOM<acPF< <IacRA@%	t"QK	%U)	%X)	%	[-	%
^-	A
G	A#acT9 9Q@A@#	$%lacTQ@A@#	%	acVA@$A@%	@DC
acRA@NkacR: :a@ {		!!!!
!!! !*!
I!9 9X!	i!x!X$~SOLCOM!Z$SOLCOM!V$SOLCOM!`#INTER0!b#MOVE!N#PROMPT!P #VTENB !R#VTREAD!T#VTGETL!\#FLIPS0!^#MESSA0
 
"%&0&$ UNIFO09 9	acA@QQKQ_	AZ	Q;QQK	AZQA	@AY"	!@ !#RND 
 
"%,$0&