&
* ALLOC : :DSMEM$	QK	@D"	#%in alloc: out of storage space. type 'c' or 'i' for char or integer dump. 9 9	t#,aKDSMEM$	$AacC@acC@acA@%A@		%CB&%CB&AacA@7 7J		%CB&%CB&AacA@YO	
program terminated. ^acC@_2	"t$8 8,agDSMEM$	@q	$#s	t$,aKDSMEM$	"'%},aKDSMEM$	t#: :,aSDSMEM$	$(~	't$,aSDSMEM$	$("t(,aSDSMEM$	(@D)	!r!9 9!!0!C!I!a!c!i!$DSMEM$!$$DSMEM$!#REMARK!#GETCH  ! #DSDUMP!"#ERROR 
 
"%.*0&


Q( FREE; ;DSMEM$	QK	@H"t",aKDSMEM$	#	$t$,aKDSMEM$	%"CA&%A
&A	%$: :	%A&#"%CBA	&	A	#t%,a[DSMEM$	#,aKDSMEM$	t",aSDSMEM$%	%: :	t",aSDSMEM$0	$t$,a[DSMEM$	"C	#,a[DSMEM$,aSDSMEM$	t",aKDSMEM$7 7	t$,aSDSMEM$;	"t$,aSDSMEM$	#t",aSDSMEM$G		!!$DSMEM$! $DSMEM$
 
"%,(0&& DSDUMP: :DSMEM$	** DYNAMIC STORAGE DUMP ***n. *5i   *i words in use*n.		"acA@C@acA@9 9	C@A@A@	t",aKDSMEM$	#*5i   *i words available*n. 3	#A
	t#,aGDSMEM$9 9QacA@C@4A@#Q	@	#t#,a[DSMEM$	$$,a_DSMEM$	CD%$t#,a_DSMEM$	CC: :A	%	AacA@$Q	@Yf	t#,aKDSMEM$	#3D		** END DUMP ***n. sac8 8A@C@t		!q!!!!$DSMEM$!$DSMEM$!#PRINT !#DSDBIU
 
"%,&0&& DSDBIU9 9DSMEM$	*5i   *i words in use*n.Qw,aGDSMEM$QacA@C@Q	@Q	@	@ : :	"QKQw,a[DSMEM$	#QK	C		$+		$.QK	@DQSQk9 9	@6	          . :QK	$#D	"AacA@C@;HQK	CQw9 9,aGDSMEM$QacA@A@Q	@SQK	CQw,aGDSMEM$Qac: :	A@A@Q	@gb	("@$$"	@@ "	acA@A@z7E	"A
acA@G@9 9		!q!!2!0!a_ *10i.  s*c. *n. !$DSMEM$ !$DSMEM$!#PRINT 
 
"%.&0&8$ DSINIT9 9DSMEM$	in dsinit: unreasonably small memory size.QK	%
acC@		"@ t": :,aSDSMEM$		,aSDSMEM$	"QK	t",aSDSMEM$	@ ,aSDSMEM$QK,aSDSMEM$) )		!}8!!!!$DSMEM$!$DSMEM$!#ERROR 
 
"%($0&