kd:9 9VSP$COM"PQRSTUVWXYZ[\]^_" @ABCDEFGHIJKLMNO"0c<ri>h9 9<ri>jl<ri>n<ign>sv<ri>x"NUsage: sprint {-c <copies>9 95|-h <horiz>|-j|-l <length>|-s|-v <vert>|-x} [<file>]9 9"illegal horizontal spacing":illegal vertical spac9 9ing"TQUIT$ "X*s: can't open*n"j*s: can't open*9 9n"|QUIT$ aca@0,a
@SP$COM	Caca@N,aKSP$COM	%8 8	A,aS*SP$COM                                            aK
SP$COM	%		,aS3SP$COM,aKSP$COM	A
9 9,aK/SP$COM	A	%$	@&aca@( ,aK#SP$COM	A
,aK=SP$COM9 9	%77	%6	@8aca@::0acA@,a
@
SP$COM	aGQjaT7 7QlQjQoQlasacA@	4A
	5acA@5	6ac A@A@A@	A9 9,aS"SP$COM,aS$SP$COM	@ ,aS&SP$COM,aS(SP$COM,aS*SP$COM	@ ,aS,	SP$COMac.9 9A@	,ak(SP$COM	@,aK0%SP$COM	Aac.A@
,ak(SP$COM	@,aK2 SP$COM	A
; ;,aK,	SP$COM	A
ac4A@6	%	@ ,aS(SP$COM	@ ,aS,	SP$COMac.A@: :ac4A@6	%,%+	AQfac6Q@Q@f	7ac8Q@A@,aS:SP$COM9 9	%C	A8	(8@E	8,ag*SP$COM	@,aKSP$COM	A
,aK/SP$COM	AD9 9aK ,aS<SP$COMP		,aS<SP$COMX,aK<SP$COM	%aac.A@ac.A@< <ac.,a
@<SP$COM,aK(SP$COM	,aS(SP$COM`,aK#SP$COM	A
,aK=SP$COM	ADaK8 8,aS>SP$COMu		,aS>SP$COM},aK>SP$COM	%ac.A@ac.A@ac.5 5,a
@>SP$COM,aK(SP$COM	,aS(SP$COMac@acB,a
@:SP$COMFKacD9 9,a
@:SP$COMBacFA@a@XQ@"acFA@a@jQ@+7	7                9L,87 740<acHA@	acJa@|,aK,	SP$COM	A
ac4A@6	%QJPI; ;,aK:SP$COM	%WacD,a
@:SP$COMVac A@A@A@acA@4	6acLBB9 9!@k!q!v!}!!!!!!        k!!k!6 6Bk!Zk!!!
!	!k!4k!]k!$SP$COM!9 9$SP$COM!$$SP$COM! $SP$COM!H$ SP$COM!($#SP$COM!F$%SP$COM!$*SP$COM!&$/SP$COM!"9 9$3SP$COM!*$=SP$COM!8$SP$COM!:$SP$COM!>$SP$COM!P$SP$COM!@$SP$COM!<$SP$COM!R: :$SP$COM!T$SP$COM!B$	SP$COM!.$
SP$COM!4#DUPLX$!L#GFNARG!N#OPEN!0#QUITU0!2#MKONU$!9 9#PARSCL!J#T1IN!#ERROR !,#MKLB$F!6#SETDE0!D#T1OU!V#SPRINT!X#REWIND!Z#CLOSE !\#PRINT  !^#OUTCH !`#RVONU$!b#SWT 
 
"%,:0&*.* SPRINT9 9VSP$COMacQ@A@"A@#A@$	%	$A
acA@	$,a_SP$COM	%8 8,aKSP$COM	#%CacA@acA@,aKSP$COM	@D,aSSP$COM	A,aSSP$COM: :,aKSP$COM	$$
4acA@$,aKSP$COM	,aSSP$COM	$,aSSP$COM3	"&9 9	&@H&B	#$&	@@ '&(	(@H(N	t(QK	C	('OOW	'%`: :^,a_SP$COM	A%acA@%,aKSP$COM	,aSSP$COM,aKSP$COM	',aSSP$COM; ;	(&_,aKSP$COM	A	t&QGQhacQ	@hw	t&QK	C,akSP$COMC: :C	t&QK	%    	%,aKSP$COM	@H,aSSP$COMCHacA@9 9acA@acA@	,aKSP$COM	@D,aSSP$COM	@ ,aSSP$COM,aKSP$COM	$#; ;
4acA@#,aKSP$COM	,aSSP$COM	#,aSSP$COM3	#&	(&@B	&$"< <	@@ '&(	((@M	t(QK	C	('NNU	'%^\,a[SP$COM	%ac; ;A@%,aKSP$COM	,aSSP$COM	',a[SP$COM,aSSP$COM	(&],aKSP$COM	A; ;	t&QGQhacQ	@ht	t&QK	C,aKSP$COM	@H,aSSP$COMC	t&QK; ;	%	%,akSP$COM	@CGacA@,aKSP$COM	A
: :	A,ag SP$COM
#acA@
$		!*!!
!!!
!
!: :! !<!	>*!*$SP$COM! $SP$COM!,$SP$COM!$$SP$COM!&$SP$COM!#INBUF  !#OUTCH !"#T1OU!(#POSIT0
 
"%*0&& INBUF ; ;VSP$COM	acQ	@,a
@SP$COM	"%		#		"@HADQK	%	"%; ;	t"QGQacQ	@,a
@SP$COM	$BC(	$"")	"@HQSQK: :	@HQS2QK	A	@HADQK	%C3;C	AQSQk	@GQKQg: :	@@HADQK	%XHOX	@ QS		A%	(%@^	%Qg	@@HADQK	: :	CQK		@HQS	_l	%@HADQK	%{	%~z	%}Qk		@_< <d	"#	!!
!!K!!
! !!$SP$COM!#GETLIN
 
"%4&0&WHF& OUTCH 9 9VSP$COM"`    '"/   J",J   /9 9-



"D- 

'"P(   /"\o
|9 9"d+o


@    >^    `


"|-9 9
  ''  "$I-
  ''  "8
^ 9 9   `    ^    `"ZO-"`O="f-
9 9



$"v

'

'"_
-_





9 9''         '




''   "DJ   )9 9"R$J"Zc  -


-
"nc  -


-9 9	_
"<



-">



-" =  >9 9"*__







 -  |"J
_9 9_







 -/  |"lJ  - /"|J    9 9/"/    J"=/""=<


9 9"0<

<">:,"D'   '"PS|9 9"VPQRSTUVWXYZ[\]^_		,agfSP$COM	@achA@,aKj	SP$COM	A
9 9aclA@"	%	A,aSj	SP$COMacnA@	@ ,aSfSP$COMachA@; ;QK	C,akfSP$COM	@acnA@,aKp SP$COM	A
,aKj	SP$COM	A
acl9 9A@"	%?8>7	@ ,aSfSP$COM	@ ,aSj	SP$COMacnA@aclA@"	%Q< <JP3	A,aSrSP$COM	@ ,aStSP$COM(QK	C,akrSP$COM	@,aKv3SP$COM9 9,agrSP$COMe,akfSP$COM	@acnA@,aKp SP$COM	A
,aKj	SP$COM	A
: :aclA@"	%}v|u	@ ,aSfSP$COM	@ ,aSj	SP$COMacnA@aclA@"	%9 9q	A,aSrSP$COM	@ ,aStSP$COMf,aktSP$COM	@],aKtSP$COM; ;	A
acx,a
@tSP$COM,aKfSP$COM	,aSfSP$COM	@ ,aStSP$COMQK	#acn9 9A@	acnA@
acnA@,aKfSP$COM	,aSfSP$COMacnA@,akfSP$COM@G: :acnA@,akfSP$COM
HOacnA@,akfSP$COMPWacnA@	acnA@acnA@: :,aKfSP$COM	,aSfSP$COMXacza@jacnA@	acnA@acnA@,aKfSP$COM	9 9,aSfSP$COMoacnA@	acnA@acnA@,aKfSP$COM	,aSfSP$COMacnA@	9 9acnA@acnA@,aKfSP$COM	,aSfSP$COMacnA@,akfSP$COM%,acz6 6a@f-acnA@,akfSP$COM29acnA@	acnA@acnA@,aKfSP$COM	: :,aSfSP$COM:acnA@,akfSP$COMLSacza@ZTacza@`Yacza@v^acn; ;A@,akfSP$COM
cjacnA@,akfSP$COM
kracnA@,akfSP$COMszacn< <A@	acnA@acnA@,aKfSP$COM	,aSfSP$COM{acza@acnA@,akfSP$COM: :
acnA@,akfSP$COM!acza@P"acnA@                                            akfSP$COM
'.acnA@	9 9acnA@acnA@,aKfSP$COM	,aSfSP$COM/acza@AacnA@,akfSP$COM: :
FMacnA@,akfSP$COM
NUacnA@,akfSP$COMV]acza@8^acnA@	9 9acnA@acnA@,aKfSP$COM	,aSfSP$COMcacnA@,akfSP$COMu|acn; ;A@	acnA@ acnA@,aKfSP$COM	,aSfSP$COM}acnA@!acnA@"acnA@#acn: :!A@!acnA@"acnA@$acnA@!acnA@%acnA@&,akfSP$COM	@acnA@'acnA@'; ;acnA@	acnA@(acnA@,aKfSP$COM	,aSfSP$COMacnA@!acnA@%,aKfSP$COM9 9	),aSfSP$COMacnA@!acnA@*,aKfSP$COM	@D,aSfSP$COM,aK|SP$COM	%+o: :acnA@!acnA@"acn,a
@|SP$COM,aKfSP$COM	,aSfSP$COMn,aK~SP$COM	%+6 6    acnA@!acnA@"acn,a
@~SP$COM,aKfSP$COM	,aSfSP$COMacnA@,; ;,akfSP$COMacnA@	acnA@-acnA@,aKfSP$COM	,aSfSP$COMacnA@.9 9,akfSP$COM/6acza@D7acnA@/,akfSP$COM<Cacza@\Dacza@dI9 9acza@RNacnA@0,akfSP$COM SZacza@[acza@$`acnA@	acnA@09 9acnA@,aKfSP$COM	,aSfSP$COMeacnA@1,akfSP$COMw~acnA@	acn9 9	A@2acnA@,aKfSP$COM	,aSfSP$COMacnA@3,akfSP$COM
    acnA@!; ;9acnA@"acnA@#acnA@!acnA@"acnA@$acnA@!acnA@%acnA@	acnA@acn; ;A@,aKfSP$COM	,aSfSP$COMacnA@'acnA@'acnA@4,akfSP$COM	@acnA@!9 9acnA@%,aKfSP$COM	),aSfSP$COMacnA@!acnA@*,aKfSP$COM	@D,aSfSP$COM9 9,aK|SP$COM	%+yacnA@!acnA@"acn,a
@|SP$COM,aKfSP$COM	,aSfSP$COM; ;x,aK~SP$COM	%+acnA@!acnA@"acn,a
@~SP$COM,aKfSP$COM	,aSfSP$COM; ;acnA@,,akfSP$COM(&acnA@!acnA@"acnA@#acnA@!acnA@"acnA@$: :acnA@!acnA@%acnA@5,akfSP$COM	@acnA@'acnA@'acnA@	acnA@4acn: :A@,aKfSP$COM	,aSfSP$COMacnA@!acnA@%,aKfSP$COM	),aSfSP$COMacn; ;	A@!acnA@*,aKfSP$COM	@D,aSfSP$COM,aK|SP$COM	%+acnA@!acnA@"acn; ;,a
@|SP$COM,aKfSP$COM	,aSfSP$COM,aK~SP$COM	%+acnA@!acnA@"acn: :,a
@~SP$COM,aKfSP$COM	,aSfSP$COMacnA@,,akfSP$COM'4acnA@!acn9 9-A@"acnA@#acnA@!acnA@"acnA@$acnA@!acnA@%acnA@6,akfSP$COM	@9 9acnA@'acnA@'acnA@	acnA@7acnA@,aKfSP$COM	,aSfSP$COMacnA@!9 9acnA@%,aKfSP$COM	),aSfSP$COMacnA@!acnA@*,aKfSP$COM	@D,aSfSP$COM9 9,aK|SP$COM	%+acnA@!acnA@"acn,a
@|SP$COM,aKfSP$COM	,aSfSP$COM; ;,aK~SP$COM	%++acnA@!acnA@"acn,a
@~SP$COM,aKfSP$COM	,aSfSP$COM; ;*acnA@,,akfSP$COM5BacnA@	acnA@8acnA@,aKfSP$COM	,aSfSP$COM: :CacnA@	acnA@9acnA@,aKfSP$COM	,aSfSP$COM    UacnA@	acnA@acn6 6A@,aKfSP$COM	,aSfSP$COMgacnA@	acnA@5acnA@,aKfSP$COM	8 8,aSfSP$COM$yacza@,acza@DacnA@	acnA@acnA@,aKfSP$COM	9 9,aSfSP$COMacnA@	acnA@:acnA@,aKfSP$COM	,aSfSP$COM'acza@Z: :89acza@n>acza@Cacza@Hacza@ Macza@*Racza@JWacza@l; ;9\acza@|aacza@facza@kacza@"pacza@0uacnA@	acnA@7acn6 6A@,aKfSP$COM	,aSfSP$COMzacnA@	acnA@4acnA@,aKfSP$COM	; ;,aSfSP$COMacnA@6,akfSP$COM
%acnA@5,akfSP$COM&-acnA@	acn: :	A@acnA@,aKfSP$COM	,aSfSP$COM.acnA@	acnA@;acnA@,aKfSP$COM; ;	,aSfSP$COM@acnA@	acnA@<acnA@,aKfSP$COM	,aSfSP$COMRacnA@	5 5acnA@acnA@,aKfSP$COM	,aSfSP$COMdacnA@	acnA@=acnA@: :,aKfSP$COM	,aSfSP$COMvacnA@	acnA@.acnA@,aKfSP$COM	,aSfSP$COM: :acnA@	acnA@>acnA@,aKfSP$COM	,aSfSP$COM    acnA@	acnA@?acn6 6A@,aKfSP$COM	,aSfSP$COM,acnA@	acnA@acnA@,aKfSP$COM	9 9,aSfSP$COM>acnA@	acnA@acnA@,aKfSP$COM	,aSfSP$COMPacza@>< <2bacza@Dgacza@PlacnA@!acnA@%qacnA@!acnA@"acnA@$,aKSP$COM: :	AacnA@',aKfSP$COM	@,aSfSP$COM
acnA@!acnA@%,aKfSP$COM	A9 9,aSfSP$COMacnA@!acnA@*,aKfSP$COM	@D,aSfSP$COM,aK|SP$COM	%+4: :acnA@!acnA@"acn,a
@|SP$COM,aKfSP$COM	,aSfSP$COM3,aK~SP$COM	%+J9 9    zacnA@!acnA@"acn,a
@~SP$COM,aKfSP$COM	,aSfSP$COMIacnA@!acn9 9	A@"acnA@$,aKSP$COM	AacnA@!acnA@%,aKfSP$COM	A,aSfSP$COM5 5kacnA@',aKfSP$COM	@,aSfSP$COMyacnA@!acnA@*,aKfSP$COM	@D9 9,aSfSP$COM,aK|SP$COM	%+acnA@!acnA@"acn,a
@|SP$COM,aKfSP$COM	9 9,aSfSP$COM,aK~SP$COM	%++[acnA@!acnA@"acn,a
@~SP$COM,aKfSP$COM: :	,aSfSP$COM*.	#B$L{\	#C$L_/ASew	-?Qc: :8hmU(6DW_Vhz:(?DNAQT&'k: :8ZdtrvMOJ=v0(xBa3SlIg]/IO: :6p{YU_l|;GE8d~#f0\.bqX                           W: :QK	DCE%QK	EC@A	%	AQwaKF,aS~SP$COM	%+=acnA@!acnA@"9 9acn,a
@~SP$COM,aKfSP$COM	,aSfSP$COM<3acnQ	@,akfSP$COM	@N<9 9X		!+!!W!!@!AW!B	!'
W!)W!EW!D9 9!C W!"!3$!&W!;!8<!7>W!4@!A!B!-C!D9 9!E!F!G!H!I!9J!K!L!M!        N!O!P!;Q!=R9 9!
S!.T!?U! V!<W!0X!>Y!Z!([!1\!:]!5^!2_!6`9 9!o!&~!!!W!
!!	!!!!, W!%9W!*9 9=W!#@W!KW!$SW!/YW!"]W!kW!6$ SP$COM!<$3SP$COM!8; ;$SP$COM!,$SP$COM!F$SP$COM!:$SP$COM!B$SP$COM!D$SP$COM!0$	SP$COM!2#T1IN!.#BREAK$ !4#T1OU!>#POSIU0!@#PLOTS0
 
"%*&0&FW2$ PLOTS0; ;VSP$COM	*acA@acA@acA@acA@acA@acA@acA@,aKSP$COM9 9	,aSSP$COM,aKSP$COM	@HCacA@acA@,aKSP$COM	@D,aSSP$COM&; ;	A"	("@6	"@HADQK	A
		,agSP$COM	@,aK	SP$COM	A
acA@#9 9	%PIH	A,aS	SP$COMOacA@		@ ,aSSP$COMC	"@HADQK	
C6 6acA@acA@,aKSP$COM	@D,aSSP$COM7b	"@HADQGQacQ	@< <,akSP$COM	@7?,aKSP$COM	@HCacA@acA@,aKSP$COM	@D,aSSP$COM: :acA@acA@,aKSP$COM	@D,aSSP$COM,aKSP$COM	%$acA@ac9 9A@ac,a
@SP$COM,aKSP$COM	,aSSP$COM#,aKSP$COM	%
:acA@< <	acA@ac,a
@SP$COM,aKSP$COM	,aSSP$COM9acA@,akSP$COM	@ac9 9A@         	!!        !W!!!
!H!	!!! !99 9!<!=!>!AW!P!]W!&$SP$COM!($SP$COM!.$SP$COM!0$SP$COM !*$	SP$COM!,#T1IN!"#BREAK$!$#T1OU
 
"%*$0&C>$ POSIT0: :" @ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_	QK	%	@	"; ;QK	%	@	"QK	%	@	"QK	%	@	"QK; ;	%	@		"$		
"( ac0A@ac0A@"QK	@HM=@ADaGQac0Q	@9 9		! !@!`!!! C!P!Q!R!S!	T!
UC!< #T1OU
 
"%*$0&78& POSIU0< <" @ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_	QK	""%	@	#t"aK; ;	$@ "		#"%	@M=@ADaK	$@ "a/	$"" 	ac0A@ac04 4	A@#ac0A@$	"A		!! !?!7!Z![7!6#T1OU
 
"%*&0&
" QUITU04 4VSP$COM		acA@ac,a
@
SP$COM		!

!$
SP$COM!#T1OU!#PL1$NL
 
"%&"0&*" SETDE0; ;"*,-8udelay *i *i *i	ac$Q@
A@a@Q	@Q	@Q	@ac&Q@
A@ 		!}!f!&#ENCODE!(#SYS$$ 
 
"%"0&