[cc]mc |
.hd dble$m "create a longreal from a longint" 04/27/83
longreal function dble$m (l)
longint l
.sp
Library: vswtmath (Subsystem mathematical library)
.fs
The 'dble$m' function implements something akin to the Fortran 66
'dble' function, or the Fortran 77 'dreal' function.  It takes
as an argument a 32 bit integer and returns a double precision
floating point number of the same value.  This function should
always be used when converting 32 bit integers to double precision
real numbers because the code generated by some of the compilers
will (potentially) lose up to 8 bits of mantissa precision.
.im
The algorithm involved was derived from known register structure;
see the source code for specifics.
.sa
.ul
SWT Math Library User's Guide
[cc]mc
