W,$: :"iedacA@Q@fA@	%Qf	C
acacQ@g	"9 9	aca@A@"	#acacA@Q@A@	BCac-acA@A@Q@: :"acA@Q@A@	BCCac A@A@Q@8	#L	 #9acL9 9ac"!u!v!W!!W!f!-W! #MAPDN !#GETARG!"#INDEX  !#USAGE !$#INITI0!&#SEND!(#RECEI0!*#SWT 
 
"%p$0&" USAGE 0 0	Usage:  rsa (-i | -e correspondent | -d). 	acC@ac!#REMARK!#SWT 
 
"%""0&V& INITI09 9"=varsdir=/.rsa_encipher"(a/r",=varsdir=/.rsa_9 9	decipher"Da"F*s=$all $rest=r"V*s=$all $rest: :=0	cannot create encryption parameters file. 	acfa@A@	"CachC@		: :	cannot create decryption parameters file. %	acfa@,A@	#CacjA@"achC@&9 9		DaclQ@nQ@pQ@rQpQ;n	AQtacnA@"A@Q@rQ@tQpAQvQn; ;GjQ;v	A0QvacpQ@rQ@vQxacnA@#G@bQ@xQ@tacjA@"acjA@#acra@; ;9a@(acra@,a@DactA@Q@LacvQ@fA@a@FQ@LacvQ@A@a@VQ@LacxA@: :a@Q@fA@$A@acxA@a@,Q@A@$A@		!}O!O!O!O9 9!fO*l,*l*n.p!v#INVMOD!l#CREATE!n#REMARK!p#CLOSE !r#GETPR0!t#PRINT  !x#SPROT$!z#DATE!|#ENCODE!~#SFDATA
 
"% &0&6" GETPR0: :	6acacA@A@Q
acQ@
QSacG@G@Q
acQ@
QSacA@A@6 6Q
acQ@
QS		6"7$7!#RANDOM!#PRIME !#RANDO0
 
"%."0&& RANDO0: :	acQ@A@	@ "A#"t#Q[	"A#%			"A$acA@$		!
!#TIMDAT !#RND 
 
"%0&0&" RANDOM7 7	acA@QQKQ_	A]	Q;QQK	A]Q	@A[Q		!!#RND 
 
"%,"0&

3" SEND9 9	acQ	@Q@
Q@	@DCacQ	@Q	@Q@
Q@	RSA enciphering file missi* *	ng or unreadable. acC@		!#GETEN0!#ENCIP0!#REMARK
 
"%0"0&V6& GETEN0: :"=vars=/"/.rsa_encipher	ac(a@A@Q@
A@ac*Q@
9 9	B"ac(Q	@A@Q@
A@"ac*Q@
	B"ac(a@A@Q@
A@"ac,Q@
A@	#%; ;5ac.A@#A@Q	@Q	@	%B4A		$B		$E	#%
Lac0A@#: :K	$	!}!~!R!R:*,,,l*l.!.#LENGTH!2#INPUT !0#OPEN!,#SCOPY !4 #CLOSE 
 
"%&0&&$ ENCIP0: :		acA@"Q	@	%
	"M QacQ@Q	@Q	@	QacQ	@A@Q@	" "		!"*l*n.   !#GETCH !#PWRMOD!#PRINT 
 
"%2$0&1" RECEI09 9		acQ@
Q@	@DCacQ	@Q	@Q@
Q@		RSA deciphering file missing or ' 'unreadable. acC@		!#GETDE0!#DECIP0!#REMARK
 
"%0"0&,2$ GETDE0; ;"=varsdir=/.rsa_decipher		ac(a@A@	"%ac*A@"A@9 9Q	@Q	@	%
		#		#	"%
"ac,A@"!	#	!}!' '~!(!(*,,,l*l.!.#INPUT !,#OPEN!0#CLOSE 
 
"%*$0&$ DECIP09 9		acQ@Q	@	%
acQ@Q	@Q	@		@"acA@"Q	@			! !#GETCI0!#PWRMOD!#PUTCH 
 
"%2$0&$ GETCI0   	acQ	@A@Q	@	"	*l. !#INPUT 
 
"%*$0&