X&: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM"V1.1": :[-afguy] [-d<ign>] [-i<ign>]"4*s.c":*s.ck"@*; ;s.ct*i	Usage: cc [-afguy] { -I<dir> | -D<name>[=<val>] } <inf>.acHa@,a
@JMISCOM: :	CacLC@%	@ ,aSNPPCOM 	A"	("@/	Too many -I directories!. 2acP7 7	A@"Q@A@	%KQ	C0acRQ@	C0Q	A
,awNPPCOM : :,aGTPPCOM Q6		,a_NPPCOM 	#acVQ@Q	@6A@#	B,a[NPPCOM ,aSNPPCOM 	9 9	CacLC@3tacXA@"	"@H"Z	Directory name expected.	acXA@"acP; ;	A@"Q@A@	BCacLC@	Too many -I directories!. !,awNPPCOM ,aGTPPCOM 9 9Q6		,a_NPPCOM 	#acVQ@Q	@6A@#	B,a[NPPCOM ,aSNPPCOM 	CacL9 9C@"HacXA@"	"@H"0J	@ ,aSZ.PPCOM 	A"	("@Z	Too many -D argu9 9ments!. ]acPA@"Q@A@	%uQ	C[acRQ@	C[Q	A
8 8,awZ.PPCOM ,aG\/PPCOM Q6		,a_Z.PPCOM 	#acVQ@Q	@6A@#	B,a[Z.PPCOM 9 9,aSZ.PPCOM 	CacLC@^acXA@"	"@H"	Identifier expected after -D. 5 5+acXA@"acPA@"Q@A@	BCacLC@,I	Too many -D arguments!. N8 8,awZ.PPCOM ,aG\/PPCOM Q6		,a_Z.PPCOM 	#acVQ@Q	@6A@#	B,a[Z.PPCOM : :,aSZ.PPCOM 	CacLC@OtacXA@"	"@H"*[t	AQ2ac^Q@Q@2	%: :ac`Q@A@acbQ@	@H$t$QK	CQK		CQK	A#	@ QS: :'Q	
CQ	C/Q	C4Q	C9Q	
C>acVQ@Q@f9 9A@	@ QCacdQ@fA@a@4Q@O		*s: can't open*n. Z	acfQ@fA@9 9	%CachA@C@[Q@fm		*s: can't open*n. w,aKj(MISCOM	A
acdQ@L9 9A@a@:Q@aclQ@LA@,aSn\MISCOM	CacpA@%achA@C@xQ@L; ;	A,aSr[MISCOM,akr[MISCOM	@*		*s: can't open*n. .,aKr[MISCOM	%	@acd: :Q@LA@a@@Q@,a
@r[MISCOM	aclQ@LA@,awr[MISCOM,aStWMISCOM,aKtWMISCOM	9 9	C+achA@C@/Q@L,aKr[MISCOM	@H,aSr[MISCOM,aKr[MISCOM	@H,aSr[MISCOM; ;e,aKr[MISCOM	A,awr[MISCOM,aGtWMISCOMQ6acpQ	@6fn,aKj(MISCOM	A
6 6acp,a
@n\MISCOM}acpA@%;	acvacVQ@f,a
@xMISCOM	A@aczA@%: :,aKJMISCOM	A
,aK|]MISCOM	Aac~A@acpA@%,aKj(MISCOM	A
acp; ;,a
@n\MISCOM(		,aSr[MISCOMacA@	A,aSr[MISCOMacA@		,aSr[MISCOMac: :A@	A$	($@D	$%	@,awr[MISCOM,aGtWMISCOMQ6acpQ	@6Eac9 9!q!}!X!!!X!'X!f!X!-!.!
/6 6X!        HX!	c!d!eX!iX!vX!,!hX!b$PPCOM !n9 9$.PPCOM !h$PPCOM !p$/PPCOM !$[MISCOM!$]MISCOM!$MISCOM!^$MISCOM!~$(MISCOM!; ;$WMISCOM!$\MISCOM!z#OPEN!#CREATE!r#GFNARG!v#LENGTH!d#GETARG!j#CTOC!f#MAPDN !\#PARSCL9 9!`#ERROR !l#DELARG!t#MAPSTR!x#ENCODE!|#PRINT !#CLOSE !
#INITI0!#PROCE0!#SETERR!
 
#OUTOP0!#SWT 
 
"%^&0&F$ PROCE09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM"=cdefs=9 9"
#include 	,aK"MISCOM	Aac$A@ac$A@ac&a@ac$A@9 9ac&a@	A,aS(\INCOM QK,aw(\INCOM ,aS*VINCOM 	@ ,aS,QINCOM ac.ac.: :,aK0LEXCOM	Cac.)-		,aS2[MISCOMac4A@	A,aS2[MISCOMac4A@		6 6,aS2[MISCOMac4A@	Parser failure. Fac6A@"	"@HCac8C@GA@V: :,aK0LEXCOM	Cac.]a,aK0LEXCOM	BCFac:		,aS2[MISCOMac4A@	A: :,aS2[MISCOMac4A@		,aS2[MISCOM	ac4A@ac<		!!!! 5 5!'!
!'!;!8$LEXCOM!4$QINCOM !0$\INCOM !2$VINCOM !:9 9$[MISCOM!*$MISCOM!,#PUTBA0!.#PUTBC0!6#GETSYM!<#OUTOP0!>#EXTER0!@#SYNERR!B#OUTDE0!D #CLEAN0
 
"%($0&