B
& ENTET09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	QK	A: :		QK		"	t",aKDS$MEM	"		Named parameters not allowed in this declaration. 9 9	"A
	t",aKDS$MEM	A

	AD,aGDS$MEM	QacQ	@,a
@HMISCOMA@ac9 9C@A@
*	Illegal storage class for a parameter.DQK	#QK	$AQgd: :a	$#g	#%kfQw,aGDS$MEM	QacQ	@,a
@HMISCOM	A@acC@E9 9A@	A#j	Functions cannot be passed as parameters. Qw,aKDS$MEM	CQw: :,aGDS$MEM	QacQ	@,a
@HMISCOMA@acC@A@acQ	@A@A@ac9 9Q	@cQw,aKDS$MEM	C,aKDS$MEMQSacQ	@acQ	@A@A@D: :	Identifier defined twice. U	#C	t$,aGDS$MEMQac Q	@A@"A@	@HC: :	t",aKDS$MEM,a_"IDCOM 	CvacC@VA@}	t$,aGDS$MEMQac$Q	@Q	@9 9A@#Q	@,a
@"IDCOM A@A@QSf,aK"IDCOM 	@HCQw,aKDS$MEM	9 9	CQK	@HC'	#%1	%40	%736	Invalid storage class on a: : function definition. 8	t$,aGDS$MEM	QacQ	@,a
@HMISCOMA@acC@9A@	A9 9	#7	t$,aGDS$MEMQac Q	@A@"A@	Aac&A@	%ac$Q	@Q	@A@#< <Q	@,a
@"IDCOM A@%A@QSt	Function defined twice in this file.	t",aK(DS$MEM9 9	@HC	t$,aGDS$MEM	QacQ	@,a
@HMISCOMA@acC@A@ac*A@"A@#: :Q	@A@QS%	Declaration conflicts with previous declaration.F	t",aGDS$MEMQ9 9	ac,Q	@Q	@	AacC@GA@k	#@HC	t",aK.DS$MEM	#u	EXTERN6 6 function may not be redeclared STATIC. {	t",aK.DS$MEM	CacC@|A@z	t": :,aK0DS$MEM	Aac&A@	t",aS0DS$MEM#ac*A@"A@#Q	@A@QSE,9 9Qw,aKDS$MEM	C	#%C	%FB	%	IEH		Invalid storage cl9 9ass on a function declaration.J	t$,aGDS$MEM	QacQ	@,a
@HMISCOM	A@acC@K8 8A@	A#I	t$,aGDS$MEMQac Q	@A@"A@	Aac$Q	@Q	@A@#Q	@9 9,a
@"IDCOM A@A@QSQK	Qw,aS2DS$MEM	@ QS		Function defined twice; ; in this file.#	t",aK(DS$MEM	@HC	t$,aGDS$MEM	QacQ	@,a
@HMISCOMA@9 9acC@$A@ac*A@"A@#Q	@A@QS;	Declaration conflicts with previous declar7 7ation.\	t",aGDS$MEMQac,Q	@Q	@	AacC@]A@	#@HC	t": :,aK.DS$MEM	#	t",aG(DS$MEMQac*A@"A@#Q	@Q	@QSQw,aK2DS$MEM	A9 9QK	,aS2DS$MEM	@ QS	&[">	#%3	%625	Invalid stor: :age class on an external declaration. 7	t$,aGDS$MEM	QacQ	@,a
@HMISCOMA@ac9 9C@8A@	A#6	t$,aGDS$MEMQac Q	@A@"A@	A	#Cac$Q	@9 9	Q	@A@#Q	@,a
@"IDCOM A@A@QSx	#	C	t$,aGDS$MEMQac&; ;A@	%ac$Q	@Q	@A@#Q	@,a
@"IDCOM A@%A@	QS	t$,aGDS$MEMQ9 9ac&A@	%ac$Q	@Q	@A@#Q	@,a
@"IDCOM 	A@%A@QS,t	Declar7 7ation conflicts with previous declaration.J	t",aGDS$MEMQac,Q	@Q	@	A	t$; ;,aGDS$MEM	QacQ	@,a
@HMISCOMA@acC@KA@o	#C	t",aG(DS$MEM: :Qac*A@"A@#Q	@Q	@QS		t",ag.DS$MEM ,a_.DS$MEM	C8 8,aK(DS$MEM	A
#(	Identifier defined twice. )	t$,aGDS$MEM	QacQ	@9 9,a
@HMISCOMA@acC@*A@'	t",aK0DS$MEM	Aac&A@	t",aS0DS$MEMN9 9	#	Cac*A@"A@#Q	@A@	QSYac*A@"A@#Q	@A@QSfI.79 9 Qw,aKDS$MEM	C	#%	%~	%		Invalid storag; ;                                                                                                      class on a function declaration.	t$,aGDS$MEM	QacQ	@,a
@HMISCOM	A@acC@; ;A@	A#	t$,aGDS$MEMQac Q	@A@"A@	Aac$Q	@Q	@A@#Q	@A@: :A@A@QSac$Q	@Q	@A@#Q	@,a
@"IDCOM A@A@QSQK	Qw,aS2DS$MEM5 5	@ QS	B	Function defined twice. q	t",aKDS$MEM,a_"IDCOM 	C	t$9 9,aGDS$MEM	QacQ	@,a
@HMISCOMA@acC@rA@	
Declaration conflict7 7s with previous declaration.	t$,aGDS$MEMQac Q	@A@"A@A@	@HC	t"9 9,aGDS$MEMQac,Q	@Q	@	AacC@A@P	#@HC	t",aK.DS$MEM	#; ;Z	STATIC function may not be redeclared EXTERN. `	t",aK.DS$MEM		CacC@aA@7 7}_	t",aG(DS$MEMQac*A@"A@#Q	@Q	@QSQw,aK2DS$MEM	AQK	9 9,aS2DS$MEM	@ QS	C	Function declared at level other than 1.#ac4C@$"p; ;z	#@HC		#@	t$,aGDS$MEMQac Q	@A@"A@	A	#Cac$Q	@: :$Q	@A@#Q	@A@A@A@QSac$Q	@Q	@A@#Q	@,a
@"IDCOM A@A@QS; ;U	t$,aGDS$MEM	Qac&A@	%ac$Q	@Q	@A@#Q	@,a
@"IDCOM 	A@%A@QS9 9zQ	Identifier defined twice at current level.	t",aKDS$MEM,a_"IDCOM 	C	t$9 9,aGDS$MEM	QacQ	@,a
@HMISCOMA@acC@A@4	
Declaration conflict9 9s with previous declaration.I	#C	t$,aGDS$MEMQac Q	@A@"A@A@	@HC; ;e	t",aGDS$MEMQac,Q	@Q	@	AacQ	@,a
@HMISCOMA@acC@JA@9 9w	#C	t$,aGDS$MEM!Qac$Q	@Q	@A@#Q	@A@A@A@QSac$: :Q	@Q	@A@#Q	@,a
@"IDCOM A@A@QS	t$,aGDS$MEM	Qac&A@	%: :ac$Q	@Q	@A@#Q	@,a
@"IDCOM 	A@%A@QSAH<s	ac6A@$QK		A
< <Qw	,aGDS$MEMQQK	A
ac6Q	@oQw	,aKDS$MEM	"ac6Q	@		"QS	8 8be		!!!!!!	!!!!H!,9 9$IDCOM !$DS$MEM!$DS$MEM!8$DS$MEM!$$DS$MEM!:$DS$MEM!2$DS$MEM!<$DS$MEM! ; ;$HMISCOM!*#FINDS0!6#COMPA0!0#NEWOBJ!.#NEWSYM!4#OLDSYM!#CTOC!"#SYNERR!&#CREAT0!(#MODIF0 !>#FATAL0!@#DSFREE
 
"%@&0&
9:& ENTEX09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	QK	A9 9			Functions cannot be part of a 'struct'. Qw,aKDS$MEM	CacC@A@; ;acQ	@A@A@!	Parameters not allowed in struct member.0QK	A
acC@1A@9 9QK	A
Qw,aKDS$MEM	"acQ	@	"QSORHQw,aGDS$MEMQ: :acQ	@A@"A@	@HC	t",aKDS$MEM,a_IDCOM 	Cp,aKDS$MEM	#	; ;Identifier already defined as struct tag. |Qw,aGDS$MEM	QacQ	@,a
@ HMISCOMA@5 5acC@}A@	t",aG"DS$MEMQac$Q	@Qac$Q	@	Q';8	t"9 9,aG&DS$MEMQac(Q	@Q	@	A
:&G	Struct member conflicts with previous definiti9 9on. IQw,aGDS$MEM	QacQ	@,a
@ HMISCOMA@acC@JA@H{	#@H$9 9	L'|~wacQ	@	"QS		wQK	"Qw,aGDS$MEMQac*< <Q	@A@,a
@IDCOM QSacA@"QKQw,aS&DS$MEM		,aS,DS$MEM	A,aS.DS$MEM: :	@ ,aS0DS$MEM,aG"DS$MEMQac2Q	@Q	@			!!9!9!!5 59!H9!"$IDCOM !$DS$MEM!,$DS$MEM!4$DS$MEM!$DS$MEM!2$DS$MEM!6: :$DS$MEM!($DS$MEM!&$HMISCOM! #FINDS0!.#COMPA0!0#MAKES0!*#GETLO0!#SYNERR!#CREAT0! #DSFREE!$#CTOC!8#PUTLO0
 
"%8&0&," DECLC0< <cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	ac,a
@LEXCOM9 9,a
@LEXCOMA@	A
	A,awLEXCOM,agDS$MEM
           ac,a
@LEXCOM6 6A@A@,aSLEXCOM		,awLEXCOM,aSDS$MEM,aKMODCOM,aSDS$MEMQK9 9,aS DS$MEMac"A@,awLEXCOM,aS$DS$MEM			Label already declared but not as la9 9bel.3,awLEXCOM,aKDS$MEM,agMODCOMPac&C@4A@		O	Label alread< <y declared. W	A,awLEXCOM,ag DS$MEM	liQ_	Ckac&C@XA@o	AQg9 9|y,awLEXCOM,aS DS$MEM{		!!!!!$LEXCOM!< <$LEXCOM!"$DS$MEM!$DS$MEM!$DS$MEM!$$DS$MEM!($DS$MEM! $MODCOM!#FINDS0!#MAKES0 !&#NEWOBJ!*#SYNERR
 
"%&"0&($ CHECL09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Identifier not9 9 declared.ac,a
@LEXCOM,a
@LEXCOMQ	@	AacC@A@acA@9 9,awLEXCOM,aKDS$MEM	C,aGDS$MEMQacQ	@)		Identifier is not 9 9a variable. 3,awLEXCOM,aKDS$MEM	%J	%MIacC@4A@acA@< <L,awLEXCOM,aKDS$MEM	@HC,aKDS$MEM	A^acA@,awLEXCOM,aSDS$MEM: :	A,ag DS$MEMnac,a
@LEXCOM	A@"Q	@A@	@HCo	t",aKDS$MEM	A|: :,awLEXCOM,aKDS$MEM	t",aSDS$MEMbac",a
@LEXCOMW2"		!!!: :!!$LEXCOM!$LEXCOM!$DS$MEM!$$DS$MEM! $DS$MEM!#FINDS0!"#NEWOBJ !#SYNERR!#GENINT!&#GENOQ0
 
"%*$0&d*$ CLEAN05 5cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	@ "ac9 9,a
@IDCOM 	Q@A@"A@	#ac,a
@IDCOM 	Q@A@"A@	#	Undefined 7 7label.	#A
	t#,aKDS$MEM,a_MODCOM	C,aKDS$MEM	A+acQ@7 7,a
@HMISCOMA@acC@A@/	Declared as parameter but not in parameter list.>	t#9 9,aKDS$MEM	AacQ@,a
@HMISCOMA@acC@?A@[	'Enum' referenced but 7 7not defined.j	t#,aK DS$MEM	C,aKDS$MEM	AD,aK"DS$MEM	AacQ@; ;,a
@HMISCOMA@acC@kA@$	@ "ac,a
@IDCOM 	Q@A@"A@	#ac6 6,a
@IDCOM 	Q@A@"A@	#%	'Struct' referenced but not defined.1	#A
	t#; ;,aK DS$MEM	C&,aKDS$MEM	AD,aK"DS$MEM	A&acQ@,a
@HMISCOMA@ac5 5C@2A@&F		!!!d!!d!Hd!$IDCOM !&: :$DS$MEM!$DS$MEM!$DS$MEM!($DS$MEM!$MODCOM!"$HMISCOM!#ACCES0! #CTOC!$#SYNERR
 
"%l$0&0$ CHECM0< <cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM,aKMODCOM	"ac: :A@"A@A@ac,a
@LEXCOM,a
@LEXCOMA@	Aac,a
@LEXCOM,aSLEXCOM; ;ac,a
@LEXCOMA@"A@A@A@A@,awLEXCOM,aKDS$MEM	AD,aK DS$MEM5 5	C3	Usage conflicts with previous declaration.5,awLEXCOM,aK DS$MEM; ;,a_"IDCOM 	Cac$C@6A@Rac,a
@LEXCOM,aSLEXCOMac,a
@LEXCOM8 8A@"A@A@A@A@Y4),awLEXCOM,aK&DS$MEM	Aac(A@,awLEXCOM5 5,aS&DS$MEM	A,ag DS$MEMac,a
@LEXCOM	A@#A@A@	@HC	t#9 9,aK&DS$MEM	A,awLEXCOM,aK&DS$MEM	t#,aS&DS$MEMsac*,a
@LEXCOM		: :!!!!!$LEXCOM!$LEXCOM!&$IDCOM !"$DS$MEM!$$DS$MEM!*7 7$DS$MEM!$MODCOM!#FINDS0!,#NEWOBJ!#SDUPL !#CREAT0! #ENTET0!(#SYNERR!.#GENOQ0
 
"%$$0&X" ALLOC09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	acQ	@	A: :			Data object may not have zero size. Qw,aGDS$MEMQacQ	@Q	AC9 9acC@	A@(	Data object may not be larger than 65535 words. 0AQ'	@4 4	acC@1A@M/		!VJ!$DS$MEM!#ISSTO0!#SIZEO0!#SYNERR
 
"%*"0&0" ALLOD0< <cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Qw,aKDS$MEM< <	C,aGDS$MEMQacQ	@Q[QacQ	@Q@Qw,aGDS$MEMQ9 9acQ	@Qg'acQ	@Q	@(		!0!$DS$MEM!$DS$MEM!#GETLO0! #PUTLO0
 
"%,"0&$ WSIZE 9 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	QKA	E A?	@"	
 
"%($0&5,& ALLOE09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM"#temp*i9 9	acA@	"acQ@A@a@A@"acQ@Q	@A@A@,a
@IDCOM A@": :A@	#ac A@#ac"A@	t#,aG$DS$MEM	Qac&Q	@	#$	!5!5!; ;!'5!"$IDCOM !($DS$MEM!#NEWOBJ! #NEWSYM!#ENCODE!$#OUTVAR!&#OUTOP0!*#OUTSI0
 
"%@&0&