" CKFND0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	,aK(MISCOM	A
8 8Qw,aKDS$MEM	@HC			acQ	@A@		!d!$DS$MEM! $(MISCOM!#CKPUU0
 
"%&"0&" CKFNC0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	,aK(MISCOM	A
8 8Qw,aKDS$MEM	@HC			acQ	@A@		!i!$DS$MEM! $(MISCOM!#CKPUU0
 
"%&"0&_>$ CKPUU0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM"# " 9 9*c *s "*i/" *i	ac$,a
@&\MISCOMa@	@ "	("@	9 9	"Qw,a[(DS$MEM	AD,aG*DS$MEMQQK	A
	"%
ac,Q	@	#ac.: :A@#,a
@&\MISCOM
ac$,a
@&\MISCOMa@Q	@,a
@0MISCOM	A"	("@6	"6 6,ag2\INCOM <	t",aG4QINCOM Qac$,a
@&\MISCOMa@Q	@7=ac$5 5,a
@&\MISCOMa@ ,a
@6LEXCOMQw,aG8DS$MEM	Qac:Q	@		!_!89 9$LEXCOM!6$QINCOM !4$\INCOM !,$DS$MEM!:$DS$MEM!*$DS$MEM!2$MISCOM!($\MISCOM!& #PRINT !0#PUTCH !.#MAPDN !<#CKPUT0
 
"%,$0&" CKFNA0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	,aK(MISCOM	A4 4		Qw,aGDS$MEM	QacQ	@		!$DS$MEM!$(MISCOM!#CKPUT0
 
"%("0&J(& CKPUT0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM"*i":< <*l	QK	"	t",aKDS$MEM	"	"A
Q_	CacA@,a
@\MISCOM: :acA@,a
@\MISCOM	t",aGDS$MEMQac ,a
@\MISCOM	a@Q	@QK: :	#	t",aG"DS$MEMQac ,a
@\MISCOMa@Q	@-	#$L..B: :D..E		!
J! J!/J!$DS$MEM!"$DS$MEM!&$DS$MEM!  $\MISCOM!#PUTCH !$#PRINT 
 
"%,&0&" CKFNE0; ;cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM,aK(MISCOM	A0 0		acA@,a
@\MISCOM		!
!$(MISCOM!$\MISCOM!#PUTCH 
 
"%""0&