$ ISNUL0< <cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Qw,aKDS$MEM8 8	AD,aGDS$MEMQQw,aGDS$MEMQacQ	@Q	@	A	A"		@ "	! $DS$MEM!$DS$MEM!#CONVT0
 
"%,$0&" GENCA0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM		acacQ	@ 		!#GENMA0!#CONVO0
 
"%&"0&p"& GENCO0< <cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Qw,aKDS$MEM9 9	"acA@#	t#,aKDS$MEM	AD,aKDS$MEM	$	"%	%	%: :	%	%"!	Pointer will be truncated in conversion.#acC@$A@"	9 9'Double' will be truncated in conversion. ?	"%Y>	%\XacC@@A@[         $%: :	L?ibacQ	@		!!!p!!!	!
p! $DS$MEM!$DS$MEM!#ESTOP !#SYNERR! #CONVO0
 
"%*&0&4( CONVO09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Illegal type c9 9onversion.acA@"	"t",aKDS$MEM	#	acA@#Q	@	$BCacC@A@ 9 9	$A	t",aKDS$MEM	C)QK,aSDS$MEMacA@"/	t",aKDS$MEM	8 8	C	$%C>	%FBEacA@	%	t%,aSDS$MEM	@ ,aSDS$MEM	"7 7,aS DS$MEMQK,aSDS$MEM		,aS"DS$MEMacA@%F	A&	(&@d	t": :,aK$DS$MEM	AD&,agDS$MEM	@t",a[$DS$MEM	AD,aKDS$MEM	t&QSenac&: :A@$Q@Q@QK	t",aSDS$MEMac(A@"ac*A@"Q	@Q@acA@"a8		!~6 6!!!!!!
! $DS$MEM!$DS$MEM!*$DS$MEM!&: :$DS$MEM!($DS$MEM!,$DS$MEM!#CONVT0!#ESPOP !$#DSGET !#SYNERR!"#ESPUSH!.#CONVC0!0 #DROPL0!2#PUTLI0
 
"%4(0&U|$ CONVT09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM"9 97	9 97		
9 97                                                                                                                               : :4~                                                                                                                               ~~~	: :QKQ_	C	@ "acrQ	@	@HCacrQ	@	@HCactQ	@Qact6 6Q	@Q''$	@ "&Qw,aKvDS$MEM	%22	%1	@Qw9 9,aKvDS$MEM	%==3	%<	@>		"@Qw,aKvDS$MEM	9@Qw: :,a[vDS$MEM	ADaK	"C)		"#	!U!U!U!z$DS$MEM!v#ISAGG0!x #SIZEO0
 
"%,$0&).8 CONVC09 9"ARITH$"ctype=*i*n	aG QaQQQQas"	A4@H< <	ADQK	t4QS		A4%	 QK	5Q	
QQ	
	A[Q(Q	
	AYQ; ;.ac$Q@
	A[QQQ4ac$Q@
	A[Q@Q
	@Q	HQ
	@A[Q9 9NQ
	@AYQUac&Q@
	@A[QQQ\ac&Q@
	@A[QiQ
	A]9 9	@Q	rQ
	A]QyQ
	@QQ
	AZ@Q	Q
	AZQQ
; ;	MQ	@ QQ
QQ
Q	@ Q
Q
	A]@Q	 Q
Q	@ Q
: :Q
	A]Q.	@ QQ
Q;	@ QQ
QCQ
	BA]@Q	KQ
: :	BA]QT#	in conv_const: bogus value in conv_tbl. ]	5L$)/5AIO9 92V]jsz!/<DLUac(A@a@Q	@ac*C@^\	A49 9	@H6t4QK	t6QS	A4%(		!q)!)!$#MKONU$!"#ARITH0!&#DABS !(#ABS !*#PRINT !,#FATAL0
 
"%R80&'& GETLI0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	A"	("@8 8	"Qg	@Qw,aKDS$MEM	AD",agDS$MEM		@@H#"Qw,a[DS$MEM	AD& &,aKDS$MEM	t#QS	"@H$	!$DS$MEM!$DS$MEM
 
"%0&0&0& PUTLI0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM		acQ	@Q
: :acQ@
	"B#	acA@#Qw,aSDS$MEM	AD",aSDS$MEM	A$Qw,a[DS$MEM	#: :	$@HADQK	t#,aSDS$MEM	A$$"/		!$DS$MEM!$DS$MEM!#WSIZE !#DSGET  !#SIZEO0
 
"%2&0&" DROPL0< <cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Qw,aGDS$MEM$ $QQK	A
acQ	@
		!$DS$MEM!#DSFREE
 
"%("0&>L@ FOLDC09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM"ARITH$"; ;p=*i, m=*i*n	'aG"QaQQQQas$ac&Q	@Q@
A@QK: :	A
ac&Q	@Q@A@Qw,aK(DS$MEM	AD,aK*DS$MEM	4Qw,aK,DS$MEM; ;	5QQ
QQQ
Q:Q
	AQAQ
	MQ?QGQ
Q9 9	CCQOQ
Q	CDQWQ
Q	CEQ_Q
Q	CAQgQ
ac.9 9Q@QoQ
Q	C@QxQQ;
	@QQ
	AQQ
Q	CB9 9Q	@ QQ
	A	AQQQ	
Q!Q
	MQ?	@Q(9 9Q
ac0Q@Q1	@ QQ
	A
:Q	A
A	AQE	AQQ
	A: :IQ	AP	@ QTQ
QQXQQ
Q_3	5@H6LC4;: :8mopBqstuvwxyHzP|X~`hpy: :8
	") 2;!$J; ;%Y')*+`,	A7fQw,aK,DS$MEM	8QQ
Q1QQ
9 9Q>Q
	AQEQ
	M@ QQ	MQQ	EQ?	@QKQ
9 9Q	CCQ_Q	M@ QQ
	M@ Q	CDQgQ	M@ QQ
	M@ : :Q	CEQwQ	M@ QQ
	M@ Q	CAQQ
ac.Q@QQ9 9	M@ QQ
	M@ Q	C@Q QQ;
	@Q0Q
	AQ8Q
Q9 9	CBQ>	@ QQ
	AF	AQMQQ	
QQQ
	M@ QQ	M; ;QQ	EQ?	C@QXQ
ac0Q@Qm	@ QQ
	A
vQ	A
}; ;	AQ	AQQ
	AQ	A	@ QQ
QQQQ
Q: :7	8@H9LC,8?)+,F-/012345L6`8h:x: :8<>?@A!CF19G?GJMNROQRSTUVWX9 9 YYZ\nw]`acefgh		70"Qw,aK,DS$MEM	:9 9&QQ
QmQQ
QzQ
AQQ
	EQ?QQ
Q9 9	CCQQ
Q	CDQQ
Q	CEQ Q
Q	CAQ(Q
ac29 9Q@Q0Q
Q	C@Q9QQ;
	AQAQ
	BQIQ
Q	CB: :QO	@ QQ
	ACW	AQ^Qac4Q@
QbQ
	EQ?	CQ9 9kQ
ac6Q@Qt	@ QQ
	AB}Q	AB	AQ	AQQ
: :	ACQ	AC	@ QQ
QQQQ
Q"s	:@H;LCt: :8{02346789:;<	=?A!CEFG)H1:: :8JMBJNPXQTUcVXYZ[\]^_`lacu~dg: :hjlmn#o		7l)Qw,aK,DS$MEM	<QQ
QtQ9 9Q
QQ
GQQ
	EQ?QQ
Q	CCQQ
Q	CD9 9QQ
Q	CEQ'Q
Q	CAQ/Q
ac2Q@Q7Q
Q	C@9 9Q@QQ;
	AQHQ
	BQPQ
Q	CBQV	@ QQ
	AC9 9^	AQeQac4Q@
QiQ
	EQ?	CQrQ
ac6Q@Q{; ;	@ QQ
	ABQ	AB	AQ	AQQ
	ACQ	AC	@ Q: :Q
QQ"QQ
Q)z	<@H=LC{79:	;=>?: :8@ABCDF H(JLMN0O8AQTIQUW_X[: :6\j]_`abcdefgshj|kno#qstu*v; ;		7s0Qw,aK,DS$MEM	>Q	Q	
Q	{Q	
Q?	Q	Q	
Q		BKQ: :Q	
Q		BLQQ	
Q		BMQQ	
Q		BIQ'Q	
Q		BHQ< </Q	Q;	
Q	7Q	
	A|Q	>Q	
Q		BJQD	@ QQ
	AL	AQ9 9Sac8Q@
Q@	@Q	W	@ QQ
	A
aQ	A
h	AQl	AQ: :Q
	ApQ	Aw	@ Q{Q	
Q	Q		>%	?L/	: :8 (08?EM"%&'()*+: : ,-./01X245b68q9;		7z-	4L...6 6.n22u|LuN.P	in fold_const: bogus mode encountered.RQw: :,aG(DS$MEMQac:A@a@Q	@Q	@ac<C@S@	ac>Q	@Qw,aG(DS$MEMQ9 9ac@Q	@Q	@Q@QKQw,aS(DS$MEM		?	Operation is not legal on specified data typ: :es. acBC@A@2	7L1mt{@3!q<!<!!9 9!!<!<!0$DS$MEM!4$DS$MEM!2$DS$MEM!,#MKONU$!*#ARITH0!.: :#GETLI0!6#F$LS!8#F$RS!:#F$LS71!<#F$OR77!>#F$RS71!@#AMOD!B#PRINT !D#FATAL0!F#DROPL0!H #PUTLI0!J#SYNERR
 
"%`@0&#" ARITH07 7	Arithmetic exception occured in constant operation. 	acC@A@		!!#SYNERR
 
"%&"0&