T<& INITI09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM!"as9 9m"auto"break" case"&char",continu9 9e"6default">do"Bdouble"Jelse"Pentry9 9"Venum"\extern"dfloat"jfor"nfortran: :"vgoto"|if"int"long"
	register": :return"short""sizeof"*static"2struct9 9":switch"Btypedef"Junion"P	unsigned"Zwhi9 9le"`define"hundef"ninclude"vline"|i9 9f"ifdef"ifndef"else"endif"__LI< <NE__!"$	__FILE__!".1	@ ,aS0LEXCOM,aS2LEXCOM; ;,aS4LEXCOM,aS6LEXCOM,aS8NLEXCOM,aS:LEXCOM,aS<HMISCOM,aS>]MISCOM		,aS@QINCOM 5 5	@ ,aw@QINCOM ,aSBINCOM 	acDA@A@,a
@FMISCOMA@acHA@acJA@: :,aSLIDCOM 	@ ,aSNIDCOM ,aSP4IDCOM acJA@,aSRPPCOM acT,a
@LIDCOM a@; ;A@acT,a
@LIDCOM 	a@A@acT,a
@LIDCOM 	a@A@	acT,a
@LIDCOM a@ A@
; ;acT,a
@LIDCOM 	a@&A@acT,a
@LIDCOM 	a@,A@acT,a
@LIDCOM 	a@6A@acT7 7,a
@LIDCOM 	a@>A@acT,a
@LIDCOM 	a@BA@acT,a
@LIDCOM 	a@JA@acT7 7,a
@LIDCOM 	a@PA@acT,a
@LIDCOM 	a@VA@acT,a
@LIDCOM 	a@\A@acT7 7,a
@LIDCOM 	a@dA@acT,a
@LIDCOM 	a@jA@acT,a
@LIDCOM 	a@nA@acT7 7,a
@LIDCOM 	a@vA@acT,a
@LIDCOM 	a@|A@acT,a
@LIDCOM 	a@A@acT7 7,a
@LIDCOM 	a@A@acT,a
@LIDCOM 	a@
A@acT,a
@LIDCOM 	a@A@acT7 7,a
@LIDCOM 	a@A@acT,a
@LIDCOM 	a@"A@acT,a
@LIDCOM 	a@*A@acT7 7,a
@LIDCOM 	a@2A@ acT,a
@LIDCOM 	a@:A@!acT,a
@LIDCOM 	a@BA@"acT7 7,a
@LIDCOM 	a@JA@#acT,a
@LIDCOM 	a@PA@$acT,a
@LIDCOM 	a@ZA@%acT7 7,a
@RPPCOM 	a@`A@&acT,a
@RPPCOM 	a@hA@'acT,a
@RPPCOM 	a@nA@(acT7 7,a
@RPPCOM 	a@vA@)acT,a
@RPPCOM 	a@|A@acT,a
@RPPCOM 	a@A@*acT: :,a
@RPPCOM 	a@A@+acT,a
@RPPCOM 	a@A@acT,a
@RPPCOM a@A@,acVA@9 9	"acXa@A@-A@"acVA@	"acXa@$A@.A@"	A#	t#,aGZ.PPCOM Qf: :ac\Q	@f	B##	#,ag^.PPCOM $	$	($@'	t$,aKZ.PPCOM 	%/0	A
9 9/(1	t$,aKZ.PPCOM 	%/9	t#,aGZ.PPCOM 	QfacVa@.	"	acXQ	@fA@0: :A@"8	t#,aGZ.PPCOM Qf	$#B"ac`Q	@fQ@A@"	t$,aGb/PPCOM QfacV: :Q	@f	"acXQ@A@0A@"%	A,aSd,PARCOM,aSf_PARCOM,aShdEXPCOM,aSjeEXPCOM7 7,aSlIDCOM ,aSn6MODCOM	@ ,aSpMODCOM	acrA@A@1,aStMODCOM	@ ,awtMODCOM9 9,aSvDS$MEM,aSxDS$MEM,aSzDS$MEM,aKtMODCOM,aS|MODCOMac~,a
@tMODCOMA@; ;A@1,aSMODCOMac~,a
@tMODCOMA@2A@1,aSMODCOMac~,a
@tMODCOMA@3A@17 7,aSMODCOMac~,a
@tMODCOMA@4A@1,aSMODCOMac~,a
@tMODCOMA@5A@17 7,aSMODCOMac~,a
@tMODCOMA@6A@1,aS
MODCOMac~,a
@tMODCOMA@7A@17 7,aSMODCOMac~,a
@tMODCOMA@8A@1,aSMODCOMac~,a
@tMODCOMA@9A@18 8,aS	MODCOMac~,a
@tMODCOMA@:A@1,aS
MODCOM,aK|MODCOM,aSMODCOMac: :,a
@MODCOMA@;A@1		!.}!-~!0!1!!2!!3!4!59 9!9!:!6	!7
!;!8!/=!h!!!	!
!9 9!!
!&!!!!,!        !                                 !!!!9 9!*!+!!(!!)!!!! !!!"! #!!$9 9!"%!'&!#'!$(!%)!u0!n$LEXCOM!t$NLEXCOM!l$LEXCOM!p$LEXCOM!r9 9$LEXCOM!v$LEXCOM!~$INCOM !|$QINCOM !$.PPCOM !$PPCOM !$.PPCOM !$/PPCOM !9 9$IDCOM !
$IDCOM !$4IDCOM !($IDCOM !2$DS$MEM!4$DS$MEM!6$DS$MEM! $,PARCOM!"9 9$_PARCOM!8$MODCOM!<$MODCOM!@$MODCOM!B$MODCOM!D$MODCOM!F$MODCOM!H$MODCOM!J9 9$MODCOM!P$MODCOM!L$	MODCOM!N$
MODCOM!>$MODCOM!0$MODCOM!,$MODCOM!*$6MODCOM!$: :$dEXPCOM!&$eEXPCOM!z$]MISCOM!$MISCOM!x$HMISCOM!#MKTABL!:#ENTEW0!#SDUPL !#SCOPY * *!#DSINIT!#ENTEU0!#INSTA0!#LENGTH!#CTOC!.#MAKEM0!R#CREAT0
 
"%&0&<" ENTEU0. .			Q
QKQ	@ QacQ	@Q@
Q	@		!!#ENTER 
 
"%0"0&