_(( SYNERR9 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM"*5i"9 9*5i" (*s): " Warning: *p",
<NEWLINE>"6<9 9EOF>"<*s*s.*n"D*s'*s' *s.*n"R*s'*s'*n*10x*s: :.*n"dToo many errors -- giving up.	A"#	(#@	#9 9,ag\INCOM 
	t"QGkQR	t#,aGQINCOM QT		"$acQ	@RA@$a@Q	@T9 9	""	t"QGkQR		"$acQ	@RA@$a@,a
@LEXCOM	""t"QGkQR		"9 9	$acQ	@RA@$a@,a
@
MISCOM	""QK	@HCacQ@A@a@ Q	@	%: :RacQ	@A@Q@A@	%^ac,a
@HMISCOM	&A,aKLEXCOM	Cac: :a@,,a
@HMISCOMA@	&u,aKLEXCOM	BCaca@6,a
@HMISCOMA@	&9 9,awLEXCOM,aKLEXCOM	Aac,a
@LEXCOM,a
@HMISCOMA@	&p9 9	&AacA@a@<Q@lQ@ 	"&%%	@acA@a@DQ@l,a
@HMISCOM: :Q@0acA@a@RQ@l,a
@HMISCOMQ@>+QK	A,ak]MISCOM	@N: :		,ag]MISCOM
Uaca@dV	@ ,aSHMISCOM		!q_!2!I_!f!6 6
_!._!H_! $LEXCOM!$LEXCOM!$LEXCOM!$LEXCOM!$QINCOM !
9 9$\INCOM !$$]MISCOM!$MISCOM!$HMISCOM!#ENCODE!#CTOC!#PTOC!#LENGTH!"#PRINT !& #ERROR 
 
"%~(0&" FATAL0< <	Compilation terminated. acQ	@A@acC@acA@ac!!h!#SYNERR !#REMARK!#SETERR!#SWT 
 
"%&"0&$ SDUPL 9 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	acQ	@	B: :	"acA@"	#	acQ	@A@,a
@DS$MEMA@#	#	!!$DS$MEM!#LENGTH! #DSGET !#SCOPY 
 
"%($0&" SSALL09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Semantic stack5 5 overflow.QK,a[,PARCOM,aS,PARCOM	CacC@		!,! $,PARCOM!#FATAL0
 
"%&"0&" SSDEA09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Semantic stack7 7 underflow. ,aK,PARCOMQ_,aS,PARCOM	%
acC@		!! $,PARCOM!#FATAL0
 
"%&"0&!" CSPUSH9 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Control stack 5 5overflow. ,ak_PARCOM	@	,ag_PARCOM
acC@QK,aw_PARCOM% %,aS,PARCOM		!1!!$,PARCOM!$_PARCOM!#FATAL0
 
"%&"0&" CSPOP 9 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Control stack un: :derflow.,aK_PARCOM	@H,aS_PARCOM	%
acC@		!!$_PARCOM! #FATAL0
 
"%""0&" SKIPTO< <cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	,aKLEXCOMQg6 6	%
	%		ac		!                                 ;                                 $LEXCOM!#GETSYM
 
"%&"0&"" ESPUSH9 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Expression sta5 5ck overflow.		,agdEXPCOM
acC@QK,awdEXPCOM,aSEXPCOM& &,akdEXPCOM	@	!d"!$EXPCOM!$dEXPCOM!#FATAL0
 
"%&"0&/$ ESPOP 9 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Expression sta5 5ck underflow. ,aKdEXPCOM	@H,aSdEXPCOM	%acC@A@	@ QS	A7 7,aSdEXPCOM,awdEXPCOM,aKEXPCOMQS$QK	"	!!/! $EXPCOM!$dEXPCOM!#SYNERR
 
"%($0&	$ ESTOP 8 8cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	,awdEXPCOM ,aK~EXPCOMQS	"	!$~EXPCOM!$dEXPCOM
 
"%($0&	$ NEWOBJ: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	,aKeEXPCOM	" 	B,aSeEXPCOM	"	!$eEXPCOM
 
"%($0&!$ ISSTO0< <cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Qw,aKDS$MEM9 9	%	%,aKDS$MEM	AD,aKDS$MEM	%
Qw,aKDS$MEM	BC7 7	@ "		A"	!!!!!!$DS$MEM!$DS$MEM!$DS$MEM! $DS$MEM
 
"%($0&$$ ISLVA0< <cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Qw,aKDS$MEM5 5	C,aKDS$MEM	@HCQw,aKDS$MEM	@HC,aKDS$MEM	AD8 8,aKDS$MEM	%	A"		@ "	!!$!$DS$MEM!$DS$MEM! $DS$MEM!$DS$MEM
 
"%($0&!$ ISARI0< <cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Qw,aKDS$MEM: :	AD,aKDS$MEM	"	A#			"L










 	@ #	!$DS$MEM!$DS$MEM
 
"%($0&!$ ISINT < <cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Qw,aKDS$MEM: :	AD,aKDS$MEM	"	A#			"L








 	@ #	!$DS$MEM!$DS$MEM
 
"%($0&$ ISPOI0< <cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Qw,aKDS$MEM/ /	AD,aKDS$MEM	C	A"	
	@ "	!                                 $DS$MEM!$DS$MEM
 
"%($0&$ ISCON0< <cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Qw,aKDS$MEM 	C	A"		@ "	!!$DS$MEM
 
"%($0&$ ISAGG0< <cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Qw,aKDS$MEM. .	%	%
	A"		@ "	!!     !$DS$MEM
 
"%($0&" PUTLO0 	QKQS		
 
"%("0&" GETLO0 	QKQ		
 
"%("0&