J" ALIGN0< <cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Qw,aKDS$MEM: :	%
QKA	EA?Q	B<QSQw,aGDS$MEMQacQ	@G': :	$"QK	EG? 	CQacQ	@QA'75QKG	EG?(Q	B<4 4QS6#		!D:=3 !$DS$MEM!$DS$MEM!#GETLO0
 
"%,"0&@& SIZEO0; ;cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	A"A@DQQK8 8	#At"QSQQ			CONTROL STACK OVERFLOW. 		$"@acC@#	("@t#9 9,aKDS$MEM	$	@QQ	B<Q3Q	B;Q9Q	B:Q?	t#; ;,aGDS$MEMQacQ	@Q;	AQE	t#,aGDS$MEMQacQ	@Q;	AQ7 7T	t#,aGDS$MEMQacQ	@Q;	AQ	t#,aKDS$MEM	#	t"QS	t#: :,aGDS$MEMQacQ	@Q;	AQc/	$L4444:44::@: :{:d40FU000	!	CONTROL STACK UNDERFLOW."	"@H"A	acC@#39 9	t"QK	L""!@!@!$DS$MEM!$DS$MEM!$DS$MEM!#GETLO0 !#ERROR 
 
"%D&0&.&$ MAKEM09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	acA@	": :,aKMODCOM	t",aSDS$MEM	",aSMODCOMQK,aSDS$MEM,aGDS$MEMQQK	M9 9QacQ	@Q@	@ t",aSDS$MEM,aSDS$MEM,aS DS$MEM,aS"DS$MEM	"#	!6 6.!$DS$MEM! $DS$MEM!"$DS$MEM!$DS$MEM!$DS$MEM!$$DS$MEM!$DS$MEM! $MODCOM!#DSGET !#PUTLO0
 
"%.$0& $ ENTEW0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM		acQ	@Q	@9 9	"Qw,aKDS$MEM	t",aSDS$MEM	@ ,aSDS$MEMQw,aKDS$MEM	t",aSDS$MEM- -	"Qw,aSDS$MEM	#	!$DS$MEM!$DS$MEM!$DS$MEM!#MAKEM0
 
"%.$0&$ ENTER0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM		acQ	@Q	@7 7	"QK	t",aSDS$MEM	@ ,aSDS$MEMQw,aKDS$MEM	t",aSDS$MEM	"Qw' ',aSDS$MEM	#	!$DS$MEM!$DS$MEM!$DS$MEM!#MAKEM0
 
"%.$0&+$ FINDM09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	QK	": :	t",aKDS$MEM	"	"A
	t",aKDS$MEMQ_	C,aGDS$MEM	Q
acQ	@
9 9Q
QK	M	Q'
%	"#		@ #	!$DS$MEM!$DS$MEM!$DS$MEM!#GETLO0
 
"%0$0&.$ CREAT0< <cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Qw,aKDS$MEM9 9	AacQ	@Q	@Q	@QSQw,aKDS$MEM	"acA@"Q	@Q	@QS	A1 1acA@"Q	@Q	@QS"         	!$DS$MEM!#FINDM0!#ENTER0!#ENTEW0
 
"%.$0& & COMPA0< <cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	A"QK	#QK9 9	$At"QS	@ %		CONTROL STACK OVERFLOW.          	$"@acC@ 	("'	A9 9	%	@ %	@ %	A%	@ %	(	#$$<)	A
,	$A
,	t#,aKDS$MEM	t$,agDS$MEM8 8/J/	%M2	%P	%SO	%VRU	t#,aGDS$MEMQ	t$< <,aGDS$MEMQacQ	@QacQ	@Q'oV5n	t#,aKDS$MEM	#t$,aKDS$MEM9 9	$	t"QS    }	CONTROL STACK UNDERFLOW.~	"@H"A	acC@	t"QK	L9 9}~!!!!!                                 !$DS$MEM!$DS$MEM!$DS$MEM !#GETLO0!#ERROR 
 
"%D&0&%" SAVEM09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Modes nested t8 8oo deeply.		,ag6MODCOM
acC@QK,aw6MODCOM,aSMODCOMQK5 5,aS!MODCOM,ak6MODCOM	@	!%!$MODCOM!$!MODCOM!$6MODCOM!#FATAL0
 
"%("0&"$ CREAU0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	,aK6MODCOM	@H: :	"	"@H"	"A	t",aGMODCOMQ,aG!MODCOMQacQ	@Q	@Q	@* *	A,aS6MODCOM		!$MODCOM!$!MODCOM!$6MODCOM!#CREAT0
 
"%,$0&.$ MODIF0< <cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Qw,aKDS$MEM9 9	"Qw,aKDS$MEMQSacQ	@A@A@,aKMODCOMQS,aKMODCOM9 9QS	"%$	#L
)*+		!!.!!% %.!$DS$MEM!$DS$MEM!$MODCOM!$MODCOM!#CREAT0
 
"%($0&