" EMPTY  		QS		!
 
"%&"0&R $ TYPEO0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	,aKLEXCOM	": :		QS	"#L&$; ;& !"#$&)+.0,aKLEXCOM	Cac9 9,a
@LEXCOM,a
@LEXCOMA@	@HC7,awLEXCOM,aKDS$MEM	CB		QS: :I	AQSM		!R!R!R!!R!$LEXCOM!$LEXCOM! $LEXCOM!$DS$MEM!#FINDS0
 
"%($0&~$
$ NOTSU0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	,aKLEXCOM	"9 9	AQS	"%	#L	": :	#L	"#L
$-.	"#L&/8:: :8<>?@ABCDFHIKLMNOQRSTVWX9 9Y,aKLEXCOM	Cac,a
@LEXCOM,a
@LEXCOMA@	@HC,awLEXCOM: :,aKDS$MEM	Cj		QSq	AQSu_		QSy		!~!~7 7!~!~! ~!z~!i!!~!$LEXCOM!$LEXCOM!  $LEXCOM!"$DS$MEM!#FINDS0
 
"%($0&
" NOTST0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	,aKLEXCOM	%9 9	%		AQS			QS		!!!}! $LEXCOM
 
"%&"0&d0& INITJ08 8cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	,aw,PARCOM: :,aK~PARCOM	"t",aKDS$MEM	%	%	@HC,aKDS$MEM	@HC    5 5	A#	@ #	Identifier cannot be initalized.	@ $%acA@"	A	t": :,aKDS$MEM	AD,aGDS$MEM	QacQ	@,a
@ HMISCOMA@ac"C@A@6ac$	t"9 9,aG&DS$MEMQac(Q	@A@$A@%A@#ac*		QS		!d!!d!8 8Hd! $DS$MEM!*$DS$MEM!$DS$MEM!$DS$MEM!$DS$MEM!$~PARCOM!$,PARCOM!$) )$HMISCOM!#ISSTO0!"#CTOC!&#SYNERR!(#OUTIP0!,#INITR !.#OUTIO0
 
"%,&0&	:
& INITR : :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM"0	Ri: :
ght brace required. Qk	@Qw,aKDS$MEM	C,aKLEXCOM	CacQk9 9	@acQ	@Q	@Q	@Q	@	,aKLEXCOM	%0acC@A@/ac6QK; ;	@HQSacQ	@Q	@Q	@Q	@	>	Right brace required. JQw,aKDS$MEM: :	C,aKLEXCOM	CacQk	@acQ	@Q	@Q	@Q	@	,aKLEXCOM	%v9 9acC@KA@uac|QK	@HQSaacQ	@Q	@Q	@Q	@	\: :	Can't initialize union with no members. Qw,aKDS$MEM	C,aKDS$MEM	"A8 8acC@A@0	t",aK DS$MEM	AD,aG DS$MEMQac"Q	@Q	@Q	@Q	@		t": :,aK DS$MEM	AD,aG DS$MEMQac$Q	@Qac&Q@	#ac$Q	@Qac&Q@	#9 9	$$Aac(A@a@A@ac*,a
@,MODCOM	$@H$ik7+		Fields cannot be i9 9nitialized. }Qw,aKDS$MEM	CacC@~A@	Functions cannot be initia6 6lized.Qw,aKDS$MEM	CacC@A@2	Right brace required. :9 9,aKLEXCOM	CacQk	@ac.Q	@Q	@Q	@Q	@	,aKLEXCOM	%_ac7 7C@;A@^aceQK	@HQSJac.Q	@Q	@Q	@Q	@	m9|I: :,aKLEXCOM		CQK	A|acQK	@HQS		!	!!!7 7!!     	!	,	!{!}	!	!,#INITR !$LEXCOM!*$DS$MEM!: :$DS$MEM!($DS$MEM!6$MODCOM!0#WSIZE !.#SIZEO0! #GETSYM!"#ARRAY0!$#SYNERR!&#STRUG0!2                                                                   GENLIT!4#OUTIN0!8#SCALA0
 
"%4&0&
r>$ SCALA09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM"0"0; ;	,aKLEXCOM	CacA@a@A@acA@"	"C,aKLEXCOM: :	%	%	%""	Illegal token in initializer. #	acC@$A@!; ;	"%=acA@a@A@<acacQ	@QK		@HCac A@#	t#,aK"DS$MEM9 9	C,aK$DS$MEM	CY,aK&DS$MEM	AD,aK(DS$MEM	C	t#,aK*DS$MEM	AD: :,aK&DS$MEM	AD,aK(DS$MEM	%	s^	%
vrfv	t#,aK*DS$MEM	#Tuac,: :A@#	A	t#,aK"DS$MEM	C,aK$DS$MEM	C,aK&DS$MEM	AD,aK(DS$MEM9 9	C	t#,aK*DS$MEM	AD,aK&DS$MEM	AD,aK(DS$MEM	%	!	%
$ #	t#5 5,aK*DS$MEM	AD,aK"DS$MEM	%.	%1-$1	t#,aK"DS$MEM	C9 9,aK$DS$MEM	C7,aK*DS$MEM	AD,aK"DS$MEM	%E	%HD<H	SEG on: :ly allows '&object' and const exprs as static inits.I	acC@JA@G0Oac.Q	@		!9 9!r!r!!
!!	!
r!3r!,r!;r!}9 9r!r!"$LEXCOM!0$DS$MEM!4$DS$MEM!2$DS$MEM!6$DS$MEM!8$DS$MEM!:#ISCON0+ +!$#GENLIT!&#EXPR0 !(#SYNERR!*#GENMA0!,#GENCO0!.#ESTOP !<#OUTIN0
 
"%0$0&!D( ARRAY0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM"0	On< <ly the first array bound may be omitted.Qw,aGDS$MEMQTacQ	@TQV	AC	AQg; ;$(acC@A@)Qw,aKDS$MEM	"t",aKDS$MEM	%;	%>:	%A: :=	%D@	%GC	%JFI,aKLEXCOM	C	A,agLEXCOMOS9 9T,aKLEXCOM	%[UJZac ,a
@LEXCOM,a
@"LEXCOM,a
@LEXCOMac$; ;A@#	t#,aG&DS$MEMQTac(Q	@TQTac*Q@T	$QV	ACQK	%{	@Qw; ;,aKDS$MEMQSac,Q	@A@	A@$	String constant too large for array.	$MQ'V9 9*(acC@A@)ac.Q	@ac(Q	@QTac*Q@T	%$$%
Aac A@
9 9	a@A@ac.,a
@0MODCOMac(,a
@0MODCOM	QTac*Q@T	$$?Bac2[9 9	@ &	(&@a	&MQ'VkkQV	AC,aKLEXCOM	%tn	%wsj9 9wQw,aGDS$MEMQTac4Q	@TQ	@Q	@Q	@	bvQV	ACQK	%	@: :Qw,aKDS$MEMQSac,Q	@A@	A@&^		!!!!!!!7 7!!	!!;!!}!!}!
!!!0$LEXCOM!,$LEXCOM!*; ;$LEXCOM!&$DS$MEM!4$DS$MEM!($DS$MEM! $DS$MEM!>$MODCOM!8#WSIZE !6#SIZEO0!"#GETLO0+ +!$#SYNERR!.#GENLIT!2#ESTOP !:#CREAT0!<#OUTIN0!@#GETSYM!B#INITR 
 
"%(0&"$ STRUG0< <cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Qw,aKDS$MEM; ;	"	t",aKDS$MEM	"	"A
	t",aKDS$MEM	AD,aGDS$MEMQacQ	@Q	@) )Q	@Q	@			!$DS$MEM!$DS$MEM!$DS$MEM!#INITR 
 
"%2$0&L& NEXTI0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	,aKLEXCOM	": :	A#		"$L#(9 9 "$%'(*+,,aKLEXCOM	Cac,a
@NLEXCOM9 9,a
@LEXCOMA@	@HC3,awLEXCOM,aKDS$MEM	C>	A#	E	@ #	!L3 3!L!!L!$NLEXCOM!$LEXCOM!$LEXCOM!$DS$MEM!#FINDS0
 
"%*&0&