60& CPREP0; ;cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOMacQ@	"%: :	%	C			"CacQ@Q@,a
@PPCOM 	A
	Un9 9recognized # statement. 	acC@A@		Q	#acac9ac<ac: :?ac Bac"E	
#if not implemented.IacC@JA@Hac$Z6	#$L:: :6dF]ehijklm@CI=n[suvwxyz{|7}; ;	Bogus IDPTR in Pp_tbl entry.ac&C@g	Garbage following preprocessor statement. ac(9 9Q@	%/acC@A@.		!6!
! !#6!!
6!< <$PPCOM !.#SKIPW0!#LOOKUP!#DGETS0!#SYNERR!#REMOV0! #ENTES0!"#OPENI0!$#PROCG0!&#PROCH0 !(#GOBBL0!*#RESET0!,#FATAL0
 
"%r&0&5$ PROCG09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Only identifiers; ; may appear after #ifdef. acQ@	"%	%!acC@A@ acQ@9 9Q@,a
@IDCOM 	Aac1'		!5! 5!5!$IDCOM !#LOOKUP !#DGETS0!#SYNERR!#GOBBL0
 
"%p$0&6$ PROCH09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Only identifiers; ; may appear after #ifndef.acQ@	"%	%!acC@A@ acQ@: :Q@,a
@IDCOM 	@HCac2'		!6! 6!6!$IDCOM !#LOOKUP !#DGETS0!#SYNERR!#GOBBL0
 
"%p$0&s"
$ GOBBL09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOMacQ@	"@ #9 9	Unmatched #if@.@.@. statement.	"%	BCacC@A@		acQ@	"7 7	"%/	%2.1acQ@	"+2	"CacQ@Q@; ;,a
@PPCOM 	A
<GQ	%M	%PLO	#APSQ	%Z: :	%]Y	%`\_	(#b`Q	C	#@H#hcFacQ@	"9 9T		!s! !#s!!!!!!s! $PPCOM  !#LOOKUP!#DGETS0!#SYNERR
 
"%p$0&
T0& RESET09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Integer required9 9 after #line. acQ@	"%acC@A@	Integer required after #line. 8 8	A#	acQ@A@#	$t#QK	A
acC@ A@<,aK\INCOM 	A	$: :,aw\INCOM ,aSQINCOM GCacQ@	"C
acA@T	"CacQ@8 8,a
@MISCOMA@	#@ t#,aS MISCOM]	"C	A#	(#@r	#%	@: :,aw"QINCOM ,aK$INCOM 	A
	%,ak"QINCOM ~ac&A@%	%%w	%9 9	%	%t#,aS MISCOMs         Missing ending bracket in #line.	@ t#; ;,aS MISCOM	%%1acC@A@0o	File name must follow integer in #line. 8ac9 9C@9A@7kY		!!T!
!"!HT!!T!,$INCOM !*: :$QINCOM ! $QINCOM !$\INCOM !($MISCOM!&$MISCOM!#CTOI!$#CTOC!#SKIPW0!#SYNERR!" #PUTBA0!.#REFIL0
 
"%n&0&BL( OPENI0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM"=incl=9 9	#Includes nested too deeply.		,ag\INCOM 	@acC@acQ@4	"% 9 9	%#	%&"%	"C		#@ $*	"#A$/	A%	(%@6: :	%%	@,awQINCOM ,aK INCOM 	A
	&,akQINCOM FBac"A@&G	&9 9	$#P;	%SO	%VRV	&t%QS7U	                                                                             issing ending bracket in #include: :. \	@ t%QS	&$#wac$C@]A@v&	"	C	A$ac&Q@5Q@A@
	%9 9	@ t%QS	File name must follow #include. 	ac$C@A@		}		'$@HC8 8	ac(Q@A@	'/	A%	t%,aG*PPCOM 	Q|ac,Q	@|	B%%9	'C	%: :,ag.PPCOM IM	t%,aG*PPCOM Q|ac0Q	@|A@	@DC:ac(Q@A@	'ac09 9A@A@:N	'Cac0a@A@	@DCnac(Q@A@	'	ac0A@A@w9 9	Can't open #include file. 	'Cac&Q@,a
@2HMISCOMA@ac$C@A@		: :ac4,a
@6MISCOM,aw\INCOM ,aS8]MISCOMac&Q@,a
@6MISCOMA@
,ak\INCOM 	@9 9	@ ,aw\INCOM ,aS:QINCOM 	',aS<VINCOM 		!}B!!!B!B7 7!
!"!'!
4!<B!>!HB!	B!.$INCOM !,$QINCOM !H9 9$QINCOM !&$\INCOM !J$VINCOM !<$PPCOM !8$PPCOM !D$MISCOM!@$HMISCOM!F$]MISCOM!>3 3#FOLLOW!*#SKIPW0!:#LENGTH!4#CTOC!6#OPEN!B#SDUPL !(#FATAL0!0#REFIL0!2#SYNERR
 
"%&(0&;" REMOV09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Identifier must 9 9follow '#undef'.acQ@	%acC@A@			acQ@Q@H,a
@IDCOM : :	A
QH	@HC(-		.acQ@IacQ@,a
@IDCOM 		!;!;& &!$IDCOM !#SKIPW0!#LOOKUP!#SYNERR!#DSFREE!#DELETE
 
"%6"0&-6
& INVOK0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM"*i"": :*s"	uQK	@DCacQ@A@a@,a
@LEXCOMacQ@			uQK9 9	CacQ@A@a@,a
@ MISCOMacQ@			@ "	uQg1ac"Q@l: :A@"2	A#uQK	$	($@?	t$,aK$DS$MEM	A
	%J	t#QS	(#9 9NI	($@t$,aK$DS$MEM	$"	@ADQKk	AD,aG$DS$MEMQ	t#QGQ		#%; ;ac&Q	@Q	@A@%	##VO	result of define invocation too long. r		$#@	@ac(C@s9 9A@F	@ t#	QSacQ@	A$	($@	$$"	@t$QGkQac*Q	@8 8 		!}-!!!!-!g!h!i!-!&$LEXCOM!.0 0$DS$MEM!*$MISCOM!0#CTOC!$#ENCODE!(#PUTBC0!,#GETAC0!2#SYNERR!4#DSFREE
 
"%6&0&
V&& ENTES09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	only identifiers9 9 may be defined.acQ@h	"%acC@A@		acQ@0	"Cac; ;A@#A@$	C		0acQ@0	"'		$@ #7acQ@0acA@#	%C: :		GacQ@hA@$A@%acA@		!}!!V!
!(V!V!/ /#SKIPW0!#GETFO0!#DGETS0! #GETDE0!#SYNERR!#PUTBC0!"#INSTA0!$#PUTBA0
 
"%&0&)" INSTA0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM		acQ	@Q@
; ;,a
@IDCOM 	@HCQ
	@HCacQ@	AQ
QKQQKQacQ	@Q@
$ $,a
@IDCOM 		!$IDCOM !#LOOKUP!#DSFREE!#ENTER 
 
"%0"0&K0( DGETS08 8cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	,awQINCOM 7 7,aKINCOM 	A
	",akQINCOM 
acA@"	"#	"QS		$: :,awQINCOM ,aKINCOM 	A
	",akQINCOM !acA@""	"%,,9 9	%+	@-	"%55	%4	@/6	"%>>	%=	@8?; ;	"%FA	%IEH	token too long. J	$@HAD"QS	($@		$$	@acC@K: :A@
I],awQINCOM ,aKINCOM 	A
	",akQINCOM ''kacA@"'e; ;	$@HAD@ 	QSacA@"		%	"QS		$,awQINCOM ,aKINCOM 	A
	",akQINCOM 9 9                           acA@"	Token too long. 	"%%%	%$	@$@HAD"QS	($: :	@		$$	@acC@A@
&2,awQINCOM ,aKINCOM 	A
	",akQINCOM 9 9@acA@":	$@HAD@ 	QSacA@"		%	,awQINCOM ,aKINCOM 	A
: :	",akQINCOM a]acA@"b	"Cj		QS	"uQS	@ uQS; ;		%	,awQINCOM ,aKINCOM 	A
	",akQINCOM acA@"	"                                                                   : :,awQINCOM ,aKINCOM 	A
	",akQINCOM acA@"	"%            	%9 9#,awQINCOM ,aKINCOM 	A
	",akQINCOM (acA@""	: :missing trailing comment delimiter. 3	"BCacC@4A@
I,awQINCOM ,aKINCOM : :	A
	",akQINCOM ZVacA@"[	"CacA@"		": :	#%p	&LM*zk: :8X ": :8#%: :@	"QS	@ uQS	"%	!!
!!K!
!$!        *!.!/7 7!0!9!A!	H!Z!\!_!a!zK!!!K!( $INCOM !&$QINCOM !*#REFIL0!,#SYNERR!.#PUTBA0
 
"%,(0&	"$ GETFO09 9		acA@QS	@ 	QSacQ@
	"QK	A	"C		#		define for9 9mal parameters must be identifiers. 	"%6acC@A@acQ	@		#	5	commas9 9 must separate define formal parameters.CQk	@QKQacQ@
Q@Q	@acQ@
	"9 9	%r	%uqacC@DA@acQ	@		#	t	"C
		#	!}!~	7 7!	!!)!,	!!#SKIPW0!#MKTABL!#SYNERR!#RMTABL! #ENTER 
 
"%v$0&$ SKIPW0* *	acQ	@	"%		%	#	!	! !#DGETS0
 
"%($0&$& GETDE0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	A"@ Qac; ;Q@p	#	Missing right paren or EOF in define text.acC@A@QK	A
ac; ;	Q@pQ@lQ	@	@HC,			QpQnQq	@ Qr7	#%G	%J(	%M; ;)B	
definition too long.MacQ@p	$"CacC@NA@I`	acQ@pA@: :Q@A@"	$""gQK	A
acQ	@yacQ@	%	!!!; ;!
!h!!#DGETS0!#LOOKUP!#LENGTH!"#SDUPL !#SYNERR!#SCOPY ! #RMTABL
 
"%^&0&V $ GETAC0; ;	acQ@n	"%		%	%	@ 	QSacQ@n			AQSQk: :	@QK	%	@acQ@	"QK	@H#acQ@	t#QS	"BC		!	9 9Too many actual parameters specified. 8	acC@9A@		QS		!V! !	!' ' !(V!#DGETS0!#COLLE0!#SDUPL !#PUTBC0!#SYNERR
 
"%Z$0&7"
* COLLE09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	A"@ QS	#: :		$acQ@	%	$C	(#@	$C	#@H#A	$C9 9		$ $	$C		$+'	$C		$.2	$C		$95	$9 9	C<	#A	@	unbalanced paren or EOF in define actual parameter list.E	acC@FA@9 9D	%%mE	&L!rst/uy=zC	define actual pa9 9	rameter too long. |acQ@	'"CacC@}A@hacQ@A@Q	@A@": :	'""	Q	C			(	0		(	!	~!!!7! !!!+ +"!'!,7!h7!#LENGTH!#DGETS0!#SYNERR! #SCOPY 
 
"%v*0&
