Y& FINDS09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	acQ	@		A
; ;,aKIDCOM 	"QK		"
	"@H"	"A	t",aGIDCOM Qac; ;	Q	@Q@Q	@	#	t",aG3IDCOM QacQ	@Q@Q	@	#$3	#@HCQ< <QS	A$	QK	@HC	t",aKIDCOM 	A
CHQK	@HC	t",aK3IDCOM 4 4	A
N%S	@ $	!$IDCOM !$3IDCOM !$IDCOM !#LOOKUP!#MISSIN
 
"%8&0&q"$ RECOR0; ;cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM			Q
QKQ6 6QKQw,aSDS$MEM,aKDS$MEM	"Qw,aKIDCOM 	AacA@Qw8 8,aSIDCOM Qw,aGIDCOM QacQ	@Q@
Q	@Qw,aSDS$MEMQw: :,aK3IDCOM 	AacA@Qw,aS3IDCOM 8Qw,aG3IDCOM QacQ	@Q@
9 9Q	@Qw,aSDS$MEM2         "L33Y	in record_sym: can't happe9 9n.]acC@^S		!q!$IDCOM !$3IDCOM !$DS$MEM!$DS$MEM!$DS$MEM !#ENTER !#MKTABL! #ERROR 
 
"%4$0&4*$ MAKES09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	acA@	"5 5QK	t",aSDS$MEM	@ ,aSDS$MEM	A,aSDS$MEM	@ ,aSDS$MEM,aSDS$MEM: :,aSDS$MEM,aSDS$MEM,aS DS$MEM,aG"DS$MEMQ
ac$Q	@
A@ac&Q	@A@"Q	@7 7	"#	!
1%!$DS$MEM!$DS$MEM!$DS$MEM!$DS$MEM!$DS$MEM!- -$DS$MEM! $DS$MEM!"$DS$MEM!$$DS$MEM!#DSGET !&#PUTLO0!(#RECOR0
 
"%0$0&"" ENTEV09 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	Scopes nested to; ;o deeply. ,akIDCOM 	@	,agIDCOM 
acC@	@ ,awIDCOM ,aSIDCOM , ,,aS3IDCOM 		!4"!$IDCOM !$3IDCOM !$IDCOM !#FATAL0
 
"%""0&&& EXITLL6 6cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM,awIDCOM 9 9,aKIDCOM 	A
	@ ",awIDCOM ,aGIDCOM QLacQ	@LQ@Q@A@"	%9 9Q	AD,aKDS$MEM	A
	#	$##	#A
	t#,aGDS$MEMQLQKL	A
7 7acQ	@L1	t#,aKDS$MEM	$acA@#$(!acQ@,awIDCOM 5 5,aGIDCOM 	QLacQ	@L,awIDCOM ,aK 3IDCOM 	A
	@ ",awIDCOM 5 5,aG 3IDCOM QLacQ	@LQ@Q@A@"	%iacQ@Vh,awIDCOM 9 9,aG 3IDCOM 	QLacQ	@LS	Lexic level 0 exited. x,aKIDCOM 	@H,aSIDCOM 	%: :

ac"C@y		!                                                                  $IDCOM !"$3IDCOM !$IDCOM !$DS$MEM!% %$DS$MEM!$DS$MEM!#SCTABL!#DSFREE! #RMTABL!$#FATAL0
 
"%t&0&D$ ACCES0: :cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	QK		@HC9 9Qw,aGIDCOM QQK	A
acQ	@Q	@Q@Q	@	%	@ "	: :Q	"	Qw,aG3IDCOM QQK	A
acQ	@Q	@Q@Q	@	%<.* *;	@ "	<Q	"	!D!$IDCOM !$3IDCOM !#SCTABL
 
"%6$0&H$$ NEWSYM9 9cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	acQ	@	A
: :acQ	@A@Q	@	"acQ	@Q	@Q	@	"QK	t",aSDS$MEMQK5 5,aSDS$MEMQK		@HC	@ ,aSDS$MEM'		t",aSDS$MEM+QK	t": :,aSDS$MEMQK,aSDS$MEM,aGDS$MEMQac Q	@A@	"#	!F!F< <B!$DS$MEM!$DS$MEM!$DS$MEM!$DS$MEM!$DS$MEM! $DS$MEM!#MAKES0!#MISSIN !"#PUTLO0
 
"%>$0&$ OLDSYM7 7cMISCOMjEXPCOM7MODCOM`PARCOMu0DS$MEMfIDCOM [PPCOM ]INCOM LEXCOM	QKQw8 8,aSDS$MEMQK,aSDS$MEMQK	,aSDS$MEMQK	"	!$DS$MEM!$DS$MEM! $DS$MEM
 
"%0$0&