

            ddlc (1) --- interface to Prime DBMS schema compiler     08/11/81


            _U_s_a_g_e

                 ddlc <input file>
                          [-l [<listing file>]]
                          [-z <SCHEMA option>]


            _D_e_s_c_r_i_p_t_i_o_n

                 'Ddlc'  serves  as the Subsystem interface to the Prime DBMS
                 schema  compiler   (SCHEMA).    It   examines   its   option
                 specifications  and  checks  them  for consistency, provides
                 Subsystem-compatible default file names for the listing  and
                 output  files  as  needed, and then produces a Primos SCHEMA
                 command and causes it to be executed.

                 The "-l" option is used to select the name of  the  file  to
                 receive  the  listing  generated by the compiler.  If a file
                 name  follows  the  option,  then  that  file  receives  the
                 listing.   If  the  "-l"  option is specified without a file
                 name following it or is not specified, a default filename is
                 constructed from the input filename by changing  its  suffix
                 to ".l".  For example, if the input filename is "gonzo.ddl",
                 the listing file will be "gonzo.l"; if the input filename is
                 "bar", the listing file will be "bar.l".

                 The  input filename must be a disk file name (conventionally
                 ending in ".ddl").

                 In summary, then, the default command line for  compiling  a
                 file named "file.ddl" is

                      ddlc  file.ddl  -l file.l

                 which corresponds to the SCHEMA command

                      schema -i *>file.ddl -l *>file.l



            _E_x_a_m_p_l_e_s

                 ddlc file.ddl
                 ddlc payroll.ddl -l l_payroll
                 ddlc funnyschema.ddl -z"-newopt"


            _M_e_s_s_a_g_e_s

                 "Usage:  ddlc ..."  for invalid option syntax.
                 "missing  input  file  name"  if  no input filename could be
                      found.
                 "<name>:  unreasonable input file name" if  an  attempt  was
                      made  to  read from the null device or the line printer
                      spooler.
                 "Sorry, the listing file must be a disk file" if the listing


            ddlc (1)                      - 1 -                      ddlc (1)




            ddlc (1) --- interface to Prime DBMS schema compiler     08/11/81


                      file was directed to a device file.


            _B_u_g_s

                 'Ddlc' pays no attention to standard ports.
                 
                 There is no way to avoid getting a listing file.


            _S_e_e _A_l_s_o

                 cdmlc (1), csubc (1), fdmlc (1), fsubc (1)













































            ddlc (1)                      - 2 -                      ddlc (1)


