"t(9 9"5aargaargsaargstoccasedcdhdatehdayxdbgvdeclare9 97vdeclaredmdropbdumphechocelifcelsecesachevalce9 97xitcfisforgetcgotoshistcifmindexhinstallationcl9 97abelhlinehlogin_nameanargscoutxprimosaquotecrepe9 97atssetsshbshtraceqstopmsubstrmtakecthenhtimecu9 9ntilvvarsxvpsdcwhenxx"<.$).7AGMSY_ekqu}	9 9")/;BGOV^cgpv~
#)"l_search_rule"z	^int,^var9 9,&,=lbin=/&,=bin=/&"^int*n" ^int*n"(^var*n9 9"0*s*n"6*s: not found in *s*nacLA@Q@A@	%9 9acNa@lQ@2A@	BCacPa@zA@Q@2A@
	Usage: which <co: :mmand>. !acRC@" 	A"	("@4	t"QK1	A
	A#	("@(#@>	t"QK19 9	%I	A
H	t#QSK?J	@ t#QSK	t"QK1	A	"@H"WQL	C9 9QM	C_QN	CdQO	CiacTa@<a@A@Q@	$%}QP	: :	C	t$aK;	ADaGQacVQ@QQ	@	AacXA@	a@acZ           acX; ;	A@	a@ acZ|nQL	CQM	
C(QN	C-QO	C2acN9 9	Q@A@$A@	%CacXA@	a@(acZB7	A$%	(%@O	t%QKK	A
9 9	$%VYQKK	%`	t$QSe	($d_	t$QGeQ		$&ac\Q@9 9Q	@A@&	$$ePZ	@ t$QSeac^Q@fA@	'%ac`A@'acXA@	a@0: :Q@facZK#5;acXA@a@6Q@Q@2acZ!q!	u!}!"!9 9"!f!g"!&"!,!/"!^"!a"!i"!n"!r9 9"!t"!
v"!p#OPEN!^#GETARG!`#SVGET !f#STRBSR!h#INDEX !n#CTOC!b#SCOPY !d #ERROR !j#PRINT !l#SWT !r#CLOSE 
 
"%B(0&