# build --- build the short call library (shortlb)

   declare _search_rule = "^int,^var,=bin=/&"

   pmac shortlb.s

   >> cto | x
   edb shortlb.b shortlb
   BRIEF
   RFL
   COPY ALL
   SFL
   ET
   QUIT
-EOF
