C     MACHAR.F.I --- INSERTS FOR FORTRAN 66 TESTS
C
C        Eugene Spafford
C        SWT Math Library Test Support
C        School of Information and Computer Science
C        Georgia Institute of Technology
C        Atlanta, GA  30332
C
C
      INTEGER*4 IBETA,IT,IRND,NGRD,MACHEP,MAXEXP,MINEXP,NEGEP,IEXP
      REAL EPS,EPSNEG,XMAX,XMIN
      COMMON /MACHCM/ IBETA,IT,IRND,NGRD,MACHEP,MAXEXP,MINEXP,NEGEP,
     $EPS,EPSNEG,XMAX,XMIN,IEXP
C
      INTEGER*4 I,I1,K1,K2,K3,N,J
      REAL ZERO,ONE,TWO,THREE,FIVE,HALF,AIT,PI,A,B,BETA,ALBETA,DEL
      REAL Z,ZZ,Y,X,XN,R6,R7,W,TEN,EIGHT,TENTH,C,X1,XL,FOUR
C
      PARAMETER (ZERO = 0.0,ONE = 1.0,TWO = 2.0,THREE = 3.0)
      PARAMETER (FIVE = 5.0,HALF = 0.5,PI = 3.14159265)
      PARAMETER (XN = 5000.0,I1 = 0,TEN = 10.0)
      PARAMETER (EIGHT = 8.0,TENTH = 0.1,FOUR = 4.0)
C
      REAL XEXP,XALOG,XSQRT,RANDX,RANDL,XPOWER
      REAL ABS,AMAX1,FLOAT,SIGN
      INTEGER LT,INT
C
      DATA N/5000/
