q*&: :9LFO$CM	@ ,aS8LFO$CM,aGLFO$CM!QfacA@Q@fA@A@"A@acA@Q@A@9 9	BC	A#acA@#	A#,ag
LFO$CM+	A$	($@.acA@$: :Q@A@	%<	A%	acQ@A@%	#%II,ag
LFO$CMH	@acA@#9 9K	#A	A%	(%@W	t%	QGQfQKf	A
acQ	@fQSfXbac : :Q@TQ/;+ac"!!!!q!q!$8LFO$CM!$LFO$CM! . .$
LFO$CM!#GETARG!"#CTOI!#GMETR$!#LISTI0!$#MAPUP !&#LISTU0!(#SWT 
 
"%&0&b$ LISTI0: :9LFO$CM"*s (*i) cp = *r, io = *r*n",ID"0HD"4C5 5D	ac8Q	@A@Q@A@A@"A@#	#%	%		; ;,aG:LFO$CMQjac<A@Q@jA@A@#Q	@,aK>LFO$CM	AZQl,aK@1LFO$CM	A]Q;l9 9A?Qn,aKBLFO$CM	AZQl,aKD3LFO$CM	A]	Q?lQpacF,a
@H                                                                            FO$CMA@Q@; ;A@,aKJ8LFO$CM	A
acLA@A@	O	A,aSJ8LFO$CMVacNA@	a@Q@Q	@9 9*Q@nQ@pacPQ	@A@
a@,acPQ	@A@a@0acPQ	@A@a@4	@ "	acRA@"Q@: :A@acPQ	@A@"Q@	A"%		!	u!!!
! !5 5+!f!!!!
!
! !&3z!X$8LFO$CM!H: :$LFO$CM!L$LFO$CM!P$LFO$CM!V$                                                                            FO$CM!N$1LFO$CM!R$3LFO$CM!F#GETUPN!J#GMETR$!T#PTOC !Z#PUTCH !\#PRINT !^#LISTJ0!`#ITOC
 
"%$0&<R$ LISTJ09 9"   *-3s = *s*n" !   *-3s = pathname not obtainable: :*n	acDQ	@Q	@Q@>A@A@"A@#	#AacFQ@>A@Q@>A@acHQ@>9 9Q@
A@acJA@a@Q	@Q@
         #CacJA@a@ Q	@2.		!u<0 0!<!&! <!!!J#GETUPN!L#PTOC!N#MKPA$ !P#PRINT 
 
"%b$0&I(& LISTU09 99LFO$CM	A"	("@	",ag
LFO$CM	@acA@"A@Q@A@A@#A@$	$< <	%	% ,aGLFO$CMQjacA@Q@jA@A@$A@"ac,a
@                                                                            FO$CMA@9 9Q@A@acQ@Q	@	@HCacA@"B			!I!!
I!: : !+!f! !&!$LFO$CM!$
LFO$CM!"$                                                                            FO$CM!$#STRCMP!#GETUPN!#GMETR$ ! #PTOC!&#LISTI0
 
"%&0&