@@(9 9u0DS$MEMiOBUFC0INCOM LEXCOMHOPTCOM"bilpu	                                                                                     sage: xref {-{b | i | l | p | u}}9 9 {<file>}.aca@,a
@OPTCOM	CacC@	acacA@	"acA@; ;	#	$"4	$#736	can't create temporary files. 8acC@97	AQ4ac : :Q@Q@4	$		*s: can't open*n. X	ac"Q@A@	%Cac$A@C@YQ@9 9kac&A@%A@"ac(A@%,aK*OPTCOM	A
ac,A@A@t	*s: can'9 9t open*n. 
ac$A@C@Q@	V	$&L
XWOW	ac.A@"ac0: :A@"A@#ac2A@"ac4A@#A@ac2A@#ac6!q!u!}@!!!: :@!@!*#OPEN!&#MKTEMP!(#GFNARG! $OPTCOM!2$OPTCOM!#PARSCL!"#ERROR !$#INITC05 5!,#PRINT !.#BUILD0!0#CLOSE !4#PUTCH !6#REWIND!8#SORT!:#RMTEMP!<#PRINT0!>#SWT 
 
"%`(0&[" INITC09 9u0DS$MEMiOBUFC0INCOM LEXCOMHOPTCOM"string"linkage" pro: :cedure"*
recursive"4forward"<local"Bif: :"Felse"Lfor"Pwhile"Vrepeat"^until"dc9 9ase"jdo"nreturn"vbreak"|next"stop9 9"goto"call"end"include" define9 9"(	undefine"2select":when"@ifany"Fcontin9 9ue"Pcomplex"X
precision"blogical"jimplic9 9it"t
parameter"~	external"
dimension"int: :eger"equivalence"&	function"0subroutine"<9 9common"Ddata"Jtrace"Psave"Vreal"\do: :uble"d
blockdata"nstackheader"z
shortcall		; ;,aSyINCOM 	@ ,awyINCOM ,aSINCOM 	A,aSfOBUFC0,aS
gOBUFC0		,aShOBUFC0ac; ;	A@acA@,aSJLEXCOM'aca@aca@aca@ aca@*aca@4aca@<ac; ;9a@Baca@Faca@Laca@Paca@Vaca@^aca@daca@jaca@naca@v; ;9aca@|aca@aca@aca@aca@aca@aca@ aca@(aca@2ac; ;9a@:aca@@aca@Faca@Paca@Xaca@baca@jaca@taca@~aca@; ;9aca@aca@aca@&aca@0aca@<aca@Daca@Jaca@Paca@Vac8 8a@\aca@daca@naca@z		![!L[![!u0!$JLEXCOM!
4 4$INCOM !$yINCOM !$fOBUFC0!$gOBUFC0!$hOBUFC0!#DSINIT!#MKTABL!#ENTER0
 
"%""0&$ ENTER09 9u0DS$MEMiOBUFC0INCOM LEXCOMHOPTCOM	A!	acQ	@A@",a
@JLEXCOM		!$JLEXCOM !#ENTER 
 
"%($0&6$ SYNERR9 9u0DS$MEMiOBUFC0INCOM LEXCOMHOPTCOM		acA@A@,a
@zINCOM 		"	("@; ;	",agINCOM 	@t",aGyINCOM QjacA@A@Q	@j         : *p@.*n. !ac5 5	A@C@"Q	@		!q0!0@.*i.   *i. !$yINCOM !$zINCOM ! $INCOM !#PRINT 
 
"%$0&