nP( GETSYM8 8u0DS$MEMiOBUFC0INCOM LEXCOMHOPTCOM"0123456789abcdefABCDEF	@ 9 9,aS(HLEXCOM,aS*LEXCOM,aS,KLEXCOMac.A@"ac0A@"	"#	@ $,ak(HLEXCOM	@9 9	",aw(HLEXCOM,aS2LEXCOM	%	($@t$,aS4JLEXCOMac.A@"	"%--9 9	%,	@.	"%66	%5	@7	"%??	%>	@@< <	"%G	%
Jac6A@"	@ ,aw(HLEXCOM,aS*LEXCOM	t$,aS,KLEXCOM	A,aS8ILEXCOM: :	"%__	%^	@,ak(HLEXCOM	@,aw(HLEXCOM,aS2LEXCOMac.A@"Z`: :		$"sp,ak(HLEXCOM	@,aw(HLEXCOM,aS2LEXCOMac.A@"	%	ac:a@A@%	A
; ;,ak(HLEXCOM	@",aw(HLEXCOM,aS2LEXCOMzr	@ ,aw(HLEXCOM,aS*LEXCOMac69 9A@"			,aS8ILEXCOMY		
,aS8ILEXCOM	"&Quoted literal too long.",ak(HLEXCOM	@: :		,ag(HLEXCOM	@ac<C@#5	Unmatched quote.<	",aw(HLEXCOM,aS2LEXCOM5 5	Cac<C@=ac6A@"	&"Lac.A@"	&C"W,ak(HLEXCOM	@"8 8,aw(HLEXCOM,aS2LEXCOMac.A@"	C	"%m	@,ak(HLEXCOM	@,aw(HLEXCOM9 9,aS2LEXCOMpac6A@"	@ ,aw(HLEXCOM,aS*LEXCOM;         #'LZ	
: :8ZZZZZZZZZZ !"#$%: :8&AB: :8CDE9 9F	",aS8ILEXCOM,aS*LEXCOM	@ ,aS>LEXCOM	A,aS(HLEXCOMl		!z n9 9!
!	n!
!!!$!0n!9!An!H!Z!_!an7 7!r!zn!B$LEXCOM!:$LEXCOM!N$LEXCOM!D$JLEXCOM!<$KLEXCOM!8$HLEXCOM!H$ $$ILEXCOM!J#INDEX !>#NGETCH!@#SKIPB0!F#PUTBA0!L#SYNERR
 
"%((0&'" SKIPB09 9	QK	CacQ	@acQ	@QK	CacQ	@acQ	@QK	C+ +QK	%&		!
! !#!#OUTCH !#NGETCH
 
"%&"0&L$$ NGETCH; ;u0DS$MEMiOBUFC0INCOM LEXCOMHOPTCOM	,awyINCOM ,aKINCOM 	A
	",akyINCOM 7 7
,aKINCOM 	%		"QS	@ ,aSINCOM 		,aSyINCOM 	"	; ;,awINCOM ,aG~INCOM Qac,a
@INCOM Q	@	%,,awINCOM ,akyINCOM 9 90+,awINCOM ,aG~INCOM 	QacQ	@,aKINCOM 	@H,aSINCOM 16 6,aKINCOM 	"	,aSyINCOM 	"QS!L!L!!     L!5 5$INCOM !$INCOM !$yINCOM ! $yINCOM !$INCOM !$~INCOM !#GETLIN!"#CLOSE 
 
"%*$0&&" PUTBA07 7u0DS$MEMiOBUFC0INCOM LEXCOMHOPTCOM	,aKyINCOM 	@H,aSyINCOM 	@HCQK8 8,awyINCOM ,aSINCOM 	too many characters pushed back.acC@                           		! $INCOM !$yINCOM !#ERROR 
 
"%&"0&$ PUTBB0; ;u0DS$MEMiOBUFC0INCOM LEXCOMHOPTCOM	acQ	@	"	"@H"	"A	@HADQG QacQ	@		!#LENGTH!#PUTBA0
 
"%*$0&