sF$ BUILD06 6u0DS$MEMiOBUFC0INCOM LEXCOMHOPTCOM"include	A,aSINCOM QK< <,awINCOM ,aS~INCOM 	@ ,aSyINCOM ac,aK ILEXCOM	@HCac",a
@$KLEXCOMA@"9 9,a
@&JLEXCOM	@HCac(,aK*OPTCOM	A
ac,,a
@.LEXCOMa@	A
$acac0< <,a
@.LEXCOM,aK ILEXCOM	@HCac2,a
@.LEXCOM	A@Q@A@	#@ t#QS7ac27 7,a
@.LEXCOM	A@Q@A@G	includes nested too deeply. Racac0,a
@.LEXCOM9 9,aK ILEXCOM	CR		,agINCOM 	@ac4C@So	can't open include file.Fi8 8le name: *s*n.v,akINCOM 	@@ ,awINCOM ,aSyINCOM 	ac6Q@A@,awINCOM 9 9,aS~INCOM ,aK~INCOM 	C,aKINCOM 	@H,aSINCOM ac4C@wac8A@C@6 6Q@!u,	*s,*6i*n. 4	ac8Q	@C@5,a
@$KLEXCOM,a
@:gOBUFC0ac0; ;,a
@.LEXCOM3	*s,*6i*n. I,aK<OPTCOM	A
,aK ILEXCOM	CRac8Q	@9 9C@J,a
@.LEXCOM,a
@:gOBUFC0ac0,a
@.LEXCOMWac0,a
@.LEXCOMfHac5 5,aK ILEXCOM	BC		!q!}s!!!!s!
s!29 9$OPTCOM!D$OPTCOM!6$LEXCOM!,$KLEXCOM!($ILEXCOM!.$JLEXCOM!$$yINCOM ! $INCOM !"< <$~INCOM !B$gOBUFC0!*#LOOKUP!4#EQUAL !:#SCOPY !>#OPEN!&#GETSYM!0#OUTPU0!8#OUTSTR!<#SYNERR !@#PRINT 
 
"%^$0&#" OUTPU09 9u0DS$MEMiOBUFC0INCOM LEXCOMHOPTCOM,aKOPTCOM	A
ac,a
@LEXCOMQ@ac; ;Q@,aKOPTCOM	A
ac,a
@LEXCOMQ@acQ@ac,a
@LEXCOM- -		!$OPTCOM!$OPTCOM!$LEXCOM!#BOLDF0!#OUTSTR!#UNDER0
 
"%"0&/& BOLDF0: :	A"#	(#@	#@H$t$QK	A
	"@H%QK	t%QS		t"QS	"B%t$QK% %	t%QS	""	"@HAD@ QS		!/!
 
"%,&0&-& UNDER0; ;	A"#	(#@	#@H$t$QK	A
	"@HAD	QS		t"QS	"B%t$QK	t%QS# #	""	"@HAD@ QS		!-!!_
 
"%,&0&" OUTCH 5 5u0DS$MEMiOBUFC0INCOM LEXCOMHOPTCOM	QK	Cac,aKfOBUFC08 8,aghOBUFC0QK,awfOBUFC0,aSOBUFC0,akfOBUFC0	@		!
! $OBUFC0!$fOBUFC0!$hOBUFC0!#DUMPB0
 
"%&"0&'$ OUTSTR9 9u0DS$MEMiOBUFC0INCOM LEXCOMHOPTCOM	A"	("@	"@HADQK	A
	C6 6ac,aKfOBUFC0,aghOBUFC0	"@HADQK,awfOBUFC0,aSOBUFC06 6,akfOBUFC0	@		!
'!$OBUFC0!$fOBUFC0!$hOBUFC0!#DUMPB0
 
"%($0&8$$ DUMPB09 9u0DS$MEMiOBUFC0INCOM LEXCOMHOPTCOM"  	A,agINCOM ,a_INCOM 5 5	A"acA@A@A@"	aca@A@         *4i: *s*n.	@ ,awfOBUFC05 5,aSOBUFC0	acA@C@,a
@gOBUFC0,a
@ OBUFC0	A,aSfOBUFC0,a[gOBUFC06 6,aSgOBUFC0		!u5*i .!$INCOM !$OBUFC0!"$OBUFC0!$fOBUFC0!  $gOBUFC0!#PRINT !#PUTLIN
 
"%$$0&:( PRINT0; ;u0DS$MEMiOBUFC0INCOM LEXCOMHOPTCOM"*,,,s*i"*,,,s*i	@ Qj9 9ac Q	@a@Q@A@"	##%ac"Q@A@ac$Q@	$ac$Q@	@HM=B9@; ;ac&A@	%$B&	(&@0	&$%	@ac(A@A@15		'ac*Q@A@Q@j; ;A@ac,Q@Q@j	@HC	#%WR,aK.hOBUFC0	$'Zac(A@A@	A&ac(9 9A@A@	A&%pcc		'[ac0A@A@A@"	''ac Q	@a@Q@A@": :	#JVac(A@A@		!u!                                                                                                   !                                 ; ;
!         w*6i.!6$hOBUFC0!(#INPUT !4#EQUAL !*#PUTLIN!,#LENGTH!.#F$MA11!0#PUTCH  !2#SCOPY !8#PRINT 
 
"%x(0&