j4&: :zJUNK	acacA@,a
@JUNKA@	%	A"#	(#@	t",aGJUNKQ: :		"$acA@#Q	@A@$	%&ac,a
@JUNK	B"	t",aSJUNK	("                               %	@ : :,aS                                                                          UNKacac,a
@ yJUNKac"A@	A
,a7$JUNK,aG&|JUNK	Qac(A@9 9A@Q	@Aac*,a
@JUNKA@	%Z	@ ,aS                                                                          UNKacac,a
@ yJUNK8 8QYPac,!u!v!f!f!f! fM*f*n.   !,$|JUNK! ; ;$                                                                          UNK!*$JUNK!&$yJUNK!$JUNK!$JUNK!0#GETLIN!#GETARG!#LENGTH!(#SOUND !#INITI0 !"#GETCH0!$#EXPRE0!.#PRINT !2#SWT 
 
"%(&0&w & EXPRE09 9zJUNK	ac,a
@yJUNK,aKyJUNK	"		QS			"%    	,aKyJUNK	@H9 9	Cac,a
@yJUNK,aKyJUNK	#		QS			#%&,aKyJUNK	%9 9+	$		,aSyJUNK,	$%5-0,aKyJUNK	C	A,aSyJUNK; ;,aKJUNK	C		,aSyJUNKA,aKyJUNK	@HC,aKJUNK	A		,aSyJUNK9 9M	*c: unrecognized command*n. R	acA@C@S,a
@JUNKQI,aKyJUNK	%n6 6		QS		m9,aKyJUNKQS		!qw!!!w!
! $yJUNK!$JUNK!#CONST0!#COMMA0!#PRINT 
 
"%*&0&P$" CONST0: :zJUNK	,aKJUNK	Cac	A,aSyJUNK,aKJUNK	C		,aSyJUNK: :ac,a
@JUNK,a
@                                                                          UNK	Q	acQ@,aK                                                                          UNK	@H,aS                                                                          UNKac,aKyJUNK< <	@HC,aKJUNK	%22	%1	@	,aSyJUNKac,a
@JUNK,a
@                                                                          UNKQ	: :acQ@,aK                                                                          UNK	@H,aS                                                                          UNKac3+,aKyJUNKQS		!P! !.1 1!0!9! $                                                                          UNK!$yJUNK!$JUNK!$JUNK!#CTOD!#GETCH0!"#PUSH
 
"%*"0&R6$ COMMA0: :zJUNK	,aKJUNK	Cac	A,aSyJUNK,aKJUNK	C		,aSyJUNK: :acA@	A
,a7JUNK,aG|JUNKQacA@A@Q	@ac,aKyJUNK: :	@HC,aKJUNK	C		,aSyJUNK	A"	("@9	",agJUNK	@A7	"9 9,aG|JUNKQacA@G@%Q	@:?ac3,aKyJUNK	@HC,aKJUNK	C5 5		,aSyJUNKacA@	A
,a7JUNK,aKxJUNK,a[|JUNK,aSxJUNK5 5,aKJUNK	@H,aSJUNKdac[,aKyJUNK	@HC,aKJUNK	C		9 9,aSyJUNKacA@	A
,a7JUNK,aKxJUNK,a_|JUNK,aSxJUNK,aKJUNK	@H: :,aSJUNKac},aKyJUNK	@HC,aKJUNK		C		,aSyJUNKacA@: :	A
,a7JUNK,aKxJUNK,a{|JUNK,aSxJUNK,aKJUNK	@H,aSJUNK(ac7 7,aKyJUNK	@HC,aKJUNK	
C		,aSyJUNKacA@	A
,a7JUNK; ;,aKxJUNK,a|JUNK,aSxJUNK,aKJUNK	@H,aSJUNKJacA,aKyJUNK	@HC5 5,aKJUNK	C		,aSyJUNKacA@	A
,a7JUNK,aG|JUNKQ5 5,aKxJUNKac Q	@,a7JUNK,aSxJUNK,aKJUNK	@H,aSJUNKlacc9 9,aKyJUNK	@HC,aKJUNK	C		,aSyJUNKacA@	A
,aKJUNK	@H5 5,aSJUNKac,aKyJUNK	@HC,aKJUNK	C		,aSyJUNK	@ : :,aSJUNKac',aKyJUNK	@HC,aKJUNK	C		,aSyJUNKacA@	A
8 8,a7JUNK,aKxJUNK,ag|JUNKIA,aSxJUNKJA,a7JUNK9 9,aSxJUNKO,aKJUNK	@H,aSJUNKBac9,aKyJUNK	@HC,aKJUNK	C8 8		,aSyJUNKacA@	A
,a7JUNK,aKxJUNK,ag|JUNK	yvGL9 9,aSxJUNKxGQ,a7JUNK,aSxJUNK},aKJUNK	@H,aSJUNKoacf7 7,aKyJUNK	@HC,aKJUNK	C		,aSyJUNKacA@	A
,a7JUNK7 7,aK|JUNK,agxJUNK$Gz,aSxJUNK%G,a7JUNK,aSxJUNK*5 5,aKJUNK	@H,aSJUNKac,aKyJUNK	@HC,aKJUNK	                                                                   		: :,aSyJUNKacA@	A
,a7JUNK,aK|JUNK	BK#,aKxJUNK	BKA	#	AG'9 9,aSxJUNKWG,,a7JUNK,aSxJUNK\,aKJUNK	@H,aSJUNKJacA7 7,aKyJUNK	@HC,aKJUNK	C		,aSyJUNKacA@	A
,a7JUNK: :,aK|JUNK	BK#,aKxJUNK	BK#AGY,aSxJUNKG^,a7JUNK,aSxJUNK7 7,aKJUNK	@H,aSJUNK|acs,aKyJUNK	@HC,aKJUNK	C		: :,aSyJUNKacA@	A
,a7JUNK,aK|JUNK	C
G,aS|JUNK3G
9 9,a7JUNK,aS|JUNK8-ac$n<a4"^<xV.,aKyJUNKQS		!uF9 9!!!F! !        &!	*!+!-!
/!<!=!>!D!6 6P!^!d!p!|!~FL*d*n.   5:@!2$xJUNK!.. .$|JUNK!,$JUNK!($yJUNK!$$JUNK!*#SOUND !&#GETCH0!0#PRINT !4#E$66
 
"%*$0&

!" PUSH6 6zJUNK	stack overflow. 		,agJUNK	@acC@		,aSyJUNK: :,akJUNK	@QK,a7JUNK,aS|JUNK		!!!d!!$|JUNK!$JUNK! $yJUNK!#REMARK
 
"%&"0&$ SOUND : :zJUNK	stack underflow.,aKJUNKQgacC@	@ "	,aSyJUNK	A   	"	"	!!$JUNK!$yJUNK!#REMARK
 
"%($0&
" GETCH07 7zJUNK,ak                                                                          UNK	@,aw                                                                          UNK,aKJUNK,aSJUNK		!$                                                                          UNK!$JUNK!$JUNK
 
"%""0&" INITI0 zJUNK	@ ,aSJUNK		!$JUNK
 
"%""0&