.hd phone "find someone's telephone number" 06/12/82
phone [<person> | <business>]
.ds
'Phone' finds the telephone number (or numbers) belonging to a
given person or business, provided the number has been placed
in the on-line phone directory.
.sp
If no person or business is given, the entire phone directory
is listed.
.es
phone ack radio
phone ed rupp
phone
.fl
=phonelist= for directory of telephone numbers
.bu
Locally supported.
