>>=DPROCESS_ARG P_INDEX NSHELL_COMMANDSFILEQ O_FLAGCC_OPTS FC_OPTS }USAGE qBUILDLIB<<LIBLIST PASS_ON fSET_LANG                                                                                C_OPTS 1MAIN[BUILDFILE 	LIBQFILELISTTAILRP_OPTS LANGOUTPUTC_FLAGLIBTAIL PMA_OPTS= =!





(((((

#MAPDN #PRINTF? ?#EXIT#STRLEN#MALLOC#ERROR #C$IOCM#FPUTS 	AAAAAK"	"	@H	CA#> >	A	#AA7#Ak%AKA	CA7#Ak%AA(A#A	@(A= =-A#A	@%A@#-	(#	@	#	"	CA#		!1%*"main>	= =G0AAA7%Ak"AwAKA	LSTVW? ?XYZ[\]^A	L`hijklm? ?norKOBd g	AAAqA7%Ak"AwAK	A
< <A7%Ak"GwAGA(A#A	@(AAK%	B	C?	ADAk"A= =A(G#A	@(Ak%	@G|s	AAA7%Ak"tAK	A
A7%Ak"= =tAGAA7AK%	B	C?	ADAK"AAk%	@BG+RA7%Ak"t= =AK	A
A7%Ak"tAGAAYAK%	B	C?	ADAK"AAk%	@d> >GPaA7%Ak"tAK	A
A7%Ak"tAGAA{AK%	B	C?	AD> >AK"AAk%	@Gr_A7%Ak"tAK	A
A7%Ak"tAGA? ?AAK%	B	C?	ADAK"A           Ak%	@(GUA7%Ak"tAK	A
A7%> >Ak"tAGAA?AK%	B	C?	ADAK"AAk%	@JG6bA7%Ak"> >tAK	A
A7%Ak"tAGAAaAK%	B	C?	ADAK"AAk%	@> >lGXpA7%Ak"tAK	A
A7%Ak"tAGA(A#A	@(A? ?AK%	B	C?	ADAk"AA(G#A	@(Ak%	@GztA7%AK"A(A	B= =A	@H	C?	ADA(ASG&:		!D@%>*"process_arg<	G)A< <AAc'A	@"	'	@H	ADAK"A	CA	BA	@H	C?	ADA"AS		P< <Ac)A@A%	@AwAS%A"AS%	'	@H	ADAK"tAS%Ak%	'	@H	AD	@ = =ASAA	ACA%AAN.faA%t
AS> >A%A		![>%<*"	buildfile	GAAAc)A@A%	@? ?tAS%A"AS%A	ACA%AA"1A%tAS7A%? ?A		!q%*"buildlibCG<AAA	ACG#N!d< <,eclare _search_rule = '^int,^var,=ebin=/&'
QAc#A@A? ?AAtAKA	Ldeghijklm> >noq_ar!3rp %s.r %s
vAkAA#Ac#A@3< <A	@#A
@f!?fc %s.f %s | x
AkAA#Ac#A@?A	@#A
@> >Ap!Opc %s.p %s | x
AkAA#Ac#A@OA	@#A
@           Gs? ?!_pmac %s.s %s | x
$AkAA#Ac#A@_A	@#A
@G#c!qcc? ? %s %s.c | sh
4AkAA#Ac#A@qA
@A	@#G3bGCt!i> >n shell_commands: can't happenFAc+A@GEKt
AKAZ> >A	AC[A	A
		Y!"ld -u [Ac#A@"			A!)-b b? ?Ac#A@)Aa			@H	C!--a lAc#A@-kgAAA!1%s.< <b vAkAA#Ac#A@1A	@#t
AKAuA	ACvA> >A	A!7-l %s Ak	AA#Ac#A@7A	@#tAK	A	           A	> >	AC	@ 	"A!>%s ,A7"AGA#Ac#A@>A	@#	("	@+	"A? ?	C,A	AAKAB!B-o %s GAc#A@BA
@!I| x
MAc#< <A@I		!ND%C&shell_commandsR	G$AAAK"	"Ac!A@"? ?A	Lfgijklmnopqs< <bbt	A	Ae	@ 	G{r	Gu8	Gh
	Gv? ?G#PG		!fT%R&"set_lang           GAA!{Usage: compil? ?=e {<input_files>} [-c] [-m <language>]
              [-C<'cc? ?=' options>] [-R<'rp' options>]
              [-F<'fc' option? ?=s>] [-S<'pmac' options>]
              [-P<'pc' options>] [{> >2-l <library>}]
              [-o <output_file>]
({(0(e((O< <
	@ 	"AA7"AGqA#AwAG-A%Ac/A	@#A	@%	("	@A7"/ /AKq	ACAc%C@u		!}%(usage<# 0