

2N4MAIN9 9fHSWT$CM"	=bin=/sh"
=varsfile="You must have a 9 9"profile directory in the VARS ufd"Hto run the Subsy9 9stem.  Please have your system"xadministrator creat9 9e one for you.".vars" Can't open .VARS in your9 9 profile directory."LPlease check your password and9 9 try again."v	*s*n*s*n"_search_rule"^int,^9 9var,&,=lbin=/&,=bin=/&",=extra=/numsg":=mail=/=9 9user="HYou have mail"V=news=/delivery/=user=9 9"nThere is news"|*s: not found*n"*s: can't inv9 9oke*n" 
=varsdir="*
Password:"4batch":_ci9 97_name_eof_erase_escape_kill_newline_retype_kill_: :resp_prt_dest_prt_form"

$-5@J".vars" 9 9,Can't open .VARS in your profile directory."LPlease; ;$ check your password and try again.acvacxaczA@"ac|A@: :Q@2Q@ A@A@#Q2	@HCQ4	2(	0,Q5	A,aS~`SWT$CM.ac; ;A@A@A@A@#	A$4acA@%	%CE&%@HC@A	&	A	@ ,aSSWT$CM9 9P	%CE&%C@A	&	A	A,aSSWT$CM_	A,aSSWT$CMcT	A'	A(: :#acaca@A@Q@:A@ac
a@
Q@"Q@:Q@:	Caca@aca@Hac; ;a@x		acQ@"	@HC	A)	aca@A@	*Caca@ aca@L; ;		&acA@*a@va@a@acA@*aca@,A@	*%HacA@*A@acA@*: :G$acA@A@aca@:A@A@A@A@A@A@A@	@HCaca@Hlac: :a@VA@A@A@A@A@A@A@	@HCaca@nac
Q@:Q@"Q@:Q@:	%9 9
acQ@"	A
acA@a@|Q@:			acQ@"A@	Cac9 9A@a@Q@:/	ac A@	A@8		iac"A@a@ Q@A@+Q@f	%O9 9	@ ,aS$LSWT$CMjN	"%Wac&,a
@$LSWT$CMA@
	A
V^ac(A@	,: :A
	-ac(A@-acA@a@*ac*Q@A@	+ac A@	A@ac(A@,	+%; ;	@ t+QSac,Q@A@ac.Q@,a
@$LSWT$CMA@
_jl,aKSWT$CM	@HC; ;ac0a@4m	"Aac2Q@L	@HC&ac0Q@L	@HC-4ac4Q@L	@HC9 9<	ac6Q@LA@=5m	aca@A@	.Caca@ aca@L		N; ;	ac*Q@TA@.	/BCa	/A	@ t/QSSeac8a@a@:A@Q@T	0ac*9 9Q@TA@.	/A	@ t/QSS}ac:A@0Q@TQ@:XbacA@.RA	@ 1(1@19 9,a_~`SWT$CM	Cac<A@A@A@A@1A@2A@3	3CB!@!9 9}!!!!-!!!!
-!-! -!A!; ;F-!	
-8PAUSE   !$SWT$CM!4$LSWT$CM!$`SWT$CM!#GETTO !#FINDF$!,#FILTST< <!.#CALL$$!8#DUPLX$!&#OPEN! #CREATE!:#GETLIN!6#CHKSTR!2#GFDATA!B#TTYP$R!@#TTYP$V!D#TTYP$F9 9!F#TTYP$Q!H#STRLSR!#FIXLIB!#ICOMN$!
#FIRST$!#RDTK$$!#COMI$$!#UTYPE$!#LDTMP$!: :#SCOPY !#REMARK!"#PRINT !$#CLOSE !(#FCOPY !*#FOLLOW!0#PUTCH !<#MAPSTR!>#CTOC!J#INITV0 !L#SRCH$$
 
%r40& 
$INITV0; ;fHSWT$CM	A"Q_	A#acQ	@Q	@A@acQ	@A@"A@,aSSWT$CM 9 9acQ	@A@"A@,aSSWT$CM+acQ	@A@"A@,aSSWT$CM6acQ	@A@"; ;A@,aS
SWT$CMAacQ	@A@"A@,aSSWT$CMLacQ	@A@"A@,aSSWT$CM: :WacQ	@,a
@                                                                                   WT$CMA@bacQ	@,a
@LSWT$CMA@kacQ	@,a
@LSWT$CM9 9A@	t	#L!,7BMXclu}		!		!     !!: :!f!!!
!!!!$SWT$CM!$SWT$CM!$SWT$CM!4 4$SWT$CM!$SWT$CM!$SWT$CM!$                                                                                   WT$CM!$LSWT$CM!$LSWT$CM!#MNTOC !
#CTOC
 
%.$0&
