X.L9 9QUIT$ "QUIT$ "ANY$"Terminal type '*s' not suppor9 9ted":ok,*#x"B "D*c"H                 To9 9tal"` Change"h!                   Total Change /9 9 Sec"Up Time:   *5i:*2,,0i:*5,2,0r",*7,2r"29 9Disk Accesses:  *8l *6l *5,1r"PUser Time: *5i:*2,,09 9
i:*5,2,0r"n*7,2r"tPage Faults:    *8l *6l *5,1r9 9"I/O Time:  *5i:*2,,0i:*5,2,0r"0*7,2r"6Buf9 9fer Hit Rate: *7,2r% *5l *5,1r"XName   Pid  Cp Tota9 9l  dCpu  Pct  Mem |"Name   Pid  Cp Total  dCpu  Pc9 9	t  Mem |"(Name   Pid Time  dCp  Pct| "DName   P9 9id Time  dCp  Pct| "`Name   Pid Time  dCp  Pct| 9 9"|Name   Pid  Mem  dCp  Pct| "Name   Pid  Mem  dCp9 9  Pct| "4Name   Pid  Mem  dCp  Pct| "P	Available9 9 commands are:"hl   Use LONG format"|
s   Use SH9 9ORT format"m   Use SHORT MEMORY format".c   CL9 9EAR screen and redraw data"P	q      \"Z	cntrl-p >9 9  Quit"j	BREAK  /"tx   Execute a PRIMOS command9 9"?   Display this information"0Type any characte9 9r to continue	A*	A+acPA@	A,		+	A-	A.: :	A/
	Usage: mon [<sample interval>]. 	@ ,aSRQUIT$ acTA@Q@"A@9 9	%9	A0acVQ@"A@0G;		AQd	AAacXC@G	Illegal system specifi9 9ed. LacTA@Q@"A@	%e	A0acZQ@"A@0Q@PA@	0	ac\A@Q@P9 9A@0,a
@RQUIT$ ,aKRQUIT$ 	AacXC@Md8AQd	Can't crea: :te slave on remote system.	,aKRQUIT$ 	A
ac^,a
@RQUIT$ 	A
acXC@
%aG`; ;-QfaQhQfQkQhasbaQhQfQkQhasbacdA@,a
@fQUIT$ acd9 9A@A@achQ@\	%YacjA@	a@Q@\acXA@
XaclA@Q@ZacnA@9 9		,aSp		,aSr         @ 1A2@ 3	@ 44MQfQ'dacPA@QfG		@; ;	4actA@5	A
acvA@6	1AacxA@6	67	6,aSp	A1aczA@9 9A@a@:Q@[acnA@		8'acnA@		6
:ac`Q@nA	A9	A3#9 9	7%QG	%T;	:L$$Z[B\$^`ab(cF,aKp: :	;		,aSr           		,aSr           lh	;<L	imxyz{m|p; ;	6=ac|a@BA@A@8	8@H8		8ac~A@A@8A@Q@[	@ 18                >ac; ;'Q@"A@A@A@>ac~A@A@A@Q@[acnA@acA@	?acA@acA@2A@: :acQ@"A@acA@?	=@L	=%^X	(8@	aczA@A@8; ;a@DA@6QacnA@~~Lac,a
@
Q@BA@acQ@Q@8 8A@acQ@Q@ A@,aK
	9@>acQ@dQ@dA@>,aKRQUIT$ 	A; ;,aG
QfacA@Q@fA@A@AA@	A09@ADQGJQpacA@Q@pA@A@AA@0: :	A0,ag
0G,,QQfacA@Q@fA@A@AA@QQfacA@Q@fA@; ;A@AA@,aGQfacA@Q@fA@A@AA@	@ ,aS,aG
Qfac; ;A@,a
@RQUIT$ -A@A@A@BA@A@A@Q@fA@A@A@A@A@A@AA@A@9 9	A@A@A@	A09@ADQGJQpacA@,a
@RQUIT$ G@A@A@BA@A@A@; ;$Q@pA@A@A@A@A@A@AA@A@A@0A@A@	A0,ag
c**QQf; ;acA@,a
@RQUIT$ *G@9A@A@BA@A@A@Q@fA@A@A@A@A@A@AA@; ;A@A@A@A@QQfacA@,a
@RQUIT$ G@nA@A@BA@A@A@Q@fA@; ;A@A@A@A@A@AA@A@A@A@A@,aG	QfacA@,a
@RQUIT$ G@: :3A@A@BA@A@A@Q@fA@A@A@A@A@A@AA@A@A@A@A@z9 9$aczA@A@a@HaczA@A@a@`aczA@A@a@h	AC,aK	AZQr: :,aKQF	A]Q?rQt,aKQH	A]Q?rQv,aK	A]A?Qx,aK	AZ9 9Q;xQz,aK	A]Q?rQ|,aK	A]Q?rQ~,aKQJQQ
QQ; ;QQQQQQQQ	A]	Q?vQQ	A]	Q?vQQ	A]QrQ?v9 9$Q
QQQ'vtQQfQrA;QrQf	A]QxQrQ?xQu; ;AQ0ac Q@~A@DA@EQ@aczA@A@a@A@DA@EQ@ac"A@ aczA@; ;A@a@,Q@vaczA@A@a@2,a
@Q@Q@ac Q@zA@DA@EQ@aczA@A@; ;9a@PA@DA@EQ@ac"A@ aczA@A@a@nQ@aczA@A@a@tQ@
Q@Q@ac ; ;9Q@|A@DA@EQ@aczA@A@a@A@DA@EQ@ac"A@ aczA@A@a@0Q@tacz; ;A@A@a@6Q@Q@Q@
,aKQD	A]G?$Qr,aK	AZ	QxQ;rQ; ;9QQQQQ
QQQQQQQQQ"Q$Q&Q(Q*Q,: :Q.Q0Q2Q4Q6Q8Q:	A]	G?3Q;xQ,aS$,aKp	Facz: :8A@A@a@Xac"A@ aczA@A@a@aczA@A@a@(ac"A@ aczA@A@!: :8a@DaczA@A@"a@`aczA@A@a@|ac"A@ aczA@A@!a@aczA@A@"; ;a@42	FGL	3WXYZ[O	@ ,aS&ac(A@A@Q@Q@"; ;9ac(A@A@Q@Q@$ac(A@A@Q@Q@&ac(A@A@Q@Q@(ac(A@A@Q@
; ;9Q@*ac(A@A@Q@Q@,ac(A@A@Q@Q@.ac(A@A@Q@Q@0ac(A@A@; ;9Q@Q@2ac(A@A@Q@Q@4ac(A@A@Q@Q@6ac(A@A@Q@Q@8ac(A@9 9	A@Q@Q@:	A09@ADQKK	#HQKK	$HIAQGLQQG\QpQG\Qac(9 9Q	@A@0Q	@pQ	@q	A0,ag
cc,aKr         @H,a[&	M,ar         %2ac~9 9A@2A@A@&Q@[	1Aac~A@A@A@Q@[%	3A
acnA@	@ 329 9acnA@9	1AacQ@ZA@@	8B>	acA@A@>GIac~A@; ;9A@Q@ZQ@[ac|a@PA@A@'ac|a@hA@A@(ac|a@|A@A@(ac|a@A@A@(; ;9ac|a@.A@%A@(ac|a@PA@)A@(ac|a@ZA@*A@(ac|a@jA@A@(ac|a@tA@+: :8A@(ac|a@A@A@(ac|a@0A@,A@'acnA@acvA@Jac~A@A@Q@ZQ@[: :m	+LHpFJ|	,Q{!$T!
9 9. T!	q!        }!~!!!!!!!!!%!)9 9!*	!
!+!!!,T!'!&!T!(!!!T!9 9T!"T!)!"7!@! PT!!!T!?T!cT!9 9k!lT!T!@!! !#@T}duzAmlc    w9 9Clock   QDisk1   [Disk2   Farnet  JGMETR$  cIdle1   mIdle2   Mpc1    )7 7Mpc2    3Plot    =Ring    Smlc    GSpare   tBhu0!8$!:9 9$
!J$!B$!H$!D$!F$!L$!>$!T$!$QUIT$ !$! $                                 $QUIT$ 9 9!R$!#GETARG!#VTINIT!0#DUPLX$!#R$ALOC!#CTOP!&#MAPDN !"#CHKINP!#CTOL!#MKONU$; ;!#QUIT!~#SLEEP$!#ERROR !
#NPXPRC!#BREAK$!#PRINT !#VTINFO!#VTUPD !$#T1IN!(#VTPRT < <!*#VTPUTL!,#VTCLR !.#VTGETL!2#VTMOVE!4#SYS$$ !6#MOVE$ !<#GMETR$!@#R$CALL!N#HMS !P#VTPAD  !V#PPS 
 
"%bL0&.

L, PPS 9 9"-*,6h *3i *3i:*2,,0i:*2,,0i *5,2r *5,2r *3i |">*9 9,6h *3i *3i*c *4,1r *4,1r|"Z*,6h *3i *4i *4,1r *4,1: :r|	QK	AC		QKQ_		A]A?Q,aKt	AZQQ;QQK9 9	A]G?Q;QQA;,avQacxQ@A@"A@#Q@Q	@AY$,aKz	M: :,a|         %,aKz	M,a|         @&	M,a|         8&@B',aK~	(Qw,aGQ9 9&acA@%A@'a@Q	@Q	@A@"A@#A@$Q@Q@Q	@	"A	#A	$)	*: :v	#)	*{s	")	* acA@%A@'a@>Q	@Q	@A@)A@*Q@Q@p9 9Qw,aG QacA@%A@'a@ZQ	@Q	@Q	@Q@Q@Q	(+L	R: ::;<=q>2acA@,akz	@	!H!P!QH!hH!k: :!mH!sH$dz!$!|$!$!$                                 $!~$!#HMS !
#VTPRT  !#VTPAD 
 
"%F,0&

"" HMS : :	QKA?	@AYQS	AZ	G;Q_A?	AX@AYQSacQ	@G@QS			p	 	x!#AMOD
 
"%."0&

" QUIT7 7QUIT$ 	acA@,a
@QUIT$ ac,a
@QUIT$ acac!!$QUIT$ ! $QUIT$ !#BREAK$!#R$RLS !#VTSTOP!#SWT 
 
"%&"0&