9L4: :"Usage:  moot [-a <name>]"*QUIT$ ".a<rs>aG4QH: :a*QJQHQMQJas6ac8ac:a@.Q@	Cac<a@Q	A
Q9 9	ADQGQHac>Q	@H"ac@acBacDacF.acH!}9!6#BHNDLR!8#MKONU$6 6!<#PARSCL!:#INITLZ!>#ERROR !@#CHECK0!B#LOGIN !D#DOCMDS!F#LOGOUT!H#CLEAN !J#SWT 
 
"%40&v
$ AUTHOR9 9jMISCO0zCUCOM0dFILCO0"&nAdd ConferencesnDelete Conferences9 97nAdd MembersnDelete MembersyList ConferencesyLi9 97st UsersyEnter Text	ySubmit Conference Entries
ySub9 97mit Personal NotesnChange AuthorizationsyReview Con9 97ference EntriesyReview Personal NotesyJoin Conferen9 97cesyList Conference MembersyAbility to Log InnDel9 9
ete Users"T(6GZgt(@\t!5	You are not permitted to change auth: :orizations. ,aKfCUCOM0	CachC@		acjA@Q@Q	A		,	: :That is not the name of a Moot user..aclQ@2A@acnQ@2Q@acpQ@2A@,a
@rfFILCO0: :A@	BCachC@/		Y	 User is currently logged in; authorization. may not be changed. _9 9actQ@fA@Q@2A@Qh	CachC@`achC@v				"	("@aT9 9	B"C	t"aKS	#t##aGQ0aGQ2aGQ4acvQ	@0Q	@2Q	@4Q@f"	A5 5	"	("@A	Sorry, new authorizations must be a subset. of your own.D	"%	@t"9 9,aKxCUCOM0	CQKe	CjachC@EachC@[		oBc		User disappeared w9 9hile permissions were changing. zaczacpQ@2A@,a
@rfFILCO0A@	BCac|ach: :C@{		"	User logged in@.@.@.authorizations may not change.*actQ@LA@Q@2A@QN9 9	Cac|achC@+		Rac~Q@fA@Q@2A@acQ@2A@,a
@rfFILCO0A@9 9ac|		!!!q!q!q!n!oq!yq&User: ; ; .!z$fFILCO0!$CUCOM0!n$CUCOM0!x#GETENT!p#ERRMSG!r#ASK !t#INIENT!v#PUTKEY!|#GETDAT !~#GETYN !#LOCK!#UNLOCK!#PUTDAT!#UPDENT
 
"%Z$0&" BHNDLR$ $jMISCO0zCUCOM0dFILCO0	A,aShMISCO0		!$hMISCO0
 
"%&"0&<n
( CHECK09 9jMISCO0zCUCOM0dFILCO0"*s*n"The following conferences ar: :e active:*n">     *s	@ "acFA@	#acHQ@A@acJQ@9 9Q	@acHQ@jA@acLacN,a
@PFILCO0A@	$	acRQ@4A@$	%BC,	@ : :	t%QS3Q4	CacJQ@jQ@5acTQ@jA@,a
@PFILCO0A@	%	acVQ@A@; ;Q@jA@	A%	acXQ@A@%	&acVQ@A@Q@jA@acTQ@A@Q@A@	%r9 9    acVQ@A@Q@A@	A%	acXQ@A@%	$&acZA@#a@Q@5	("@q: :6#-	ac\A@$ac^	"AacZA@	a@ac`A@#acRQ@A@#	%.acZ9 9A@	a@>Q@%-acbA@#		!	u!!!<!!<!< <<!a!c<!g<!Z$FILCO0!b#CTOI!^#GETENT!\#GETLIN!X#OPEN!P#MKTEMP!R#INIENT0 0!T#PUTKEY!V#LOCK!`#GETDAT!d#PRINT !f#CLOSE !h#UNLOCK!j#REWIND!l#RMTEMP
 
"%Z(0&
$h
( CKMESG9 9jMISCO0zCUCOM0dFILCO0"&You have seen *i messages out of *i.*n; ;,aK8MISCO0	A
ac:Q@fA@ac<Q@f,a
@>fCUCOM0	ac@Q@fA@,a
@BFILCO08 8A@	BC		acDQ@A@Q@fA@	A"	acFQ@A@"	#	acDQ@A@9 9,a
@H|CUCOM0A@	A"	acFQ@A@"	$$#FacJA@a@A@$A@#G	$$#: :U	B%	acLA@%A@#VR	acDQ@A@,a
@N~CUCOM0A@	A"	acFQ@A@"9 9	$acPacR,a
@T~FILCO0A@	&CacV		}	acXQ@A@&	"acZA@&	A: :	"	acFQ@A@"	#acV	$$#	B%	ac\A@%A@#		!u!}$!8 8$!!!!
$!c$!i$!L$FILCO0!^$~FILCO0!H$fCUCOM0!X< <$~CUCOM0!R$|CUCOM0!B$MISCO0!P#CTOI!b#GETLIN!J#GETENT!\#OPEN!D#INIENT!F#PUTKEY!N#GETDAT$ $!T#PRINT !V#REVCES!Z#LOCK!`#UNLOCK!d#CLOSE !f#REVPNS
 
"%X(0&
" CLEAN + +jMISCO0zCUCOM0dFILCO0ac,a
@FILCO0		!$FILCO0!#REMOVE
 
"%""0&<
$ DOCMDS9 9jMISCO0zCUCOM0dFILCO0"&add conferencedelete conferencead9 97d memberdelete memberlist conferenceslist users9 97list membersenteredit	joinindex
reviewsubmit9 9'authorizestatusmaillettercquit"L$0?Q]krx: :~ (.6	@ ,aS`hMISCO0,akbiMISCO0	@A,agbiMISCO0	,aSbiMISCO0acd; ;
acfA@a@La@	"(achacjaclacn!acp$acr'act*acv9 91-acx0acz3ac|6ac~9ac<ac?acBacEacH	"@D#: :	Lf4L"%(+.147:=@CFISefghij: :8klmnopqrstuvwxyz{|}~: :8	
 !"9 9&#$%&'()*+,-./01234L5KL		@.. 9 9!`$hMISCO0!b$iMISCO0!f#GETCMD!d#CKMESG!h#MKCONF!j#RMCONF!l#MKMEMB!n#RMMEMB!p#LCONFS< <!r#LUSERS!t#MKTEXT!v#EDITB0!x#JOIN!z#REVCEN!|#LMEMB !~#SUBCEN!#AUTHOR!#STATUS!#SUBPN  !#REVPN !#INDEX 
 
"%$$0&)$ EDITB0; ;jMISCO0zCUCOM0dFILCO0	No entry has been made. ac,a
@FILCO0A@	"Cac: :C@			acA@"ac,a
@FILCO0A@A@		!u!v!})!)! $FILCO0!#OPEN!#ERRMSG!#CLOSE !#EDIT
 
"%$$0&" ERRMSG6 6jMISCO0zCUCOM0dFILCO0	acQ	@	@ ,awgMISCO0,aSMISCO0		!$MISCO0! $gMISCO0!#REMARK
 
"%&"0&G&
( INDEX 9 9jMISCO0zCUCOM0dFILCO0"$ No.*11tName*41tSubject*72tDate*n*n9 9"4*4,4s *16,16s *46,46s *8,8s.*n"Tpage *i; continue: :? "hpage *i (final page) 	You are not currently in a conference.< <,aK~MISCO0	AacC@			:  can't open.acA@	"acac,a
@2CUCOM0; ;A@	#Cac
,a
@2CUCOM0A@acC@ac		5acA@"a@acQ@fA@#: :	$%S	@ t$QSeQf	%$acQ@fA@Q@LA@acQ@fA@Q@2A@e9 97acQ@fA@Q@A@pacQ@fA@Q@A@{acA@"a@4Q@LQ@2Q@Q@; ;Z	%&L[| !fq"R	$BCIacA@#acac: :A@"acA@"a@Ta@hA@A@	A@acA@"		!q!	u!}!G!!: :!G!G!G!`G!$2CUCOM0!$MISCO0!#OPEN!#MKTEMP!#GETLIN; ;!
#ERRMSG!#LOCK!#PUTLIN!#UNLOCK!#PRINT !#SCOPY !#CLOSE ! #REWIND!"#PAGE!$#RMTEMP
 
"%&(0&
mJ$ INITLZ9 9jMISCO0zCUCOM0dFILCO0"=extra=/moot.u/conferences",=extra: :=/moot.u/master_userlist"L=extra=/moot.u/pn_index9 9"d=extra=/moot.u/pn_text"|=extra=/moot.u/pn_number7 7	@ ,aShMISCO0	A"	t",aSCUCOM0	A"%		,aSCUCOM0,aSCUCOM06 6,aSCUCOM0,aS CUCOM0,aS"CUCOM0	@ ,aS$&CUCOM0ac&,a
@(~CUCOM0A@ac&: :,a
@*|CUCOM0A@ac,a@A@,a
@.FILCO0A@ac,a@,A@,a
@0fFILCO0A@ac,: :a@LA@,a
@2LFILCO0A@ac,a@dA@,a
@42FILCO0A@ac,a@|A@,a
@6~FILCO0: :A@ac8,a
@:FILCO0A@	A,aS<gMISCO0	@ ,aw<gMISCO0,aS>MISCO0	A,aS@iMISCO09 9		!m!!m!m!fm!nm!y!6$FILCO0!8$fFILCO0!:9 9$LFILCO0!<$2FILCO0!B$FILCO0!>$~FILCO0!0$~CUCOM0!2$|CUCOM0! $CUCOM0!"$CUCOM0!$9 9$CUCOM0!&$CUCOM0!($CUCOM0!*$CUCOM0!,$&CUCOM0!F$MISCO0!D$gMISCO0!$hMISCO0!H $iMISCO0!.#INIENT!4#SCOPY !@#SCRATF
 
"%$$0&

B
& JOIN; ;jMISCO0zCUCOM0dFILCO0	You are not permitted to join conferences.,aK!CUCOM0	Cac9 9C@			Conference: .  acacQ@fA@acC@!Q@Q	A		9	: :That is not the name of an active conference. ;acQ@fQ@acQ@fA@,a
@FILCO0A@9 9	BCacC@<		eac Q@f,a
@"fCUCOM0ac$,a
@&CUCOM0A@Q@fA@ac$: :,a
@(2CUCOM0A@Q@fA@ac$,a
@*LCUCOM0A@Q@fA@ac,ac.,a
@&CUCOM0A@5 5	"%
ac0A@"ac.,a
@(2CUCOM0A@	#%
)ac0A@#(ac.9 9,a
@*LCUCOM0A@	$%
7ac0A@$6ac2		$"A	$#D@	$$GC9 9F	System security is preventing access to that conference.HacC@I		G	You are not a 9 9member of that conference.jac,a
@4|CUCOM0A@,a
@*LCUCOM0A@	BCacC@k9 9			A,aS6MISCO0		!}!!!!!e!f!g!8 8n!($FILCO0!,$fCUCOM0!4$LCUCOM0!2$2CUCOM0!0$CUCOM0!>$|CUCOM0!$!CUCOM0!@: :$MISCO0!&#GETENT!8#OPEN!#ERRMSG!#UPDCEN! #INIENT!"#ASK !$#PUTKEY!*#GETKEY!.#GETDAT !6#LOCK!:#CLOSE !<#UNLOCK
 
"%V&0&
y4$ LCONFS9 9jMISCO0zCUCOM0dFILCO0	You are not permitted to list active conferences. ,aKCUCOM0	C9 9acC@			can't open conference list. $acA@	"acac,a
@FILCO0: :A@	#CacC@%		C!acA@#A@"acA@#ac ac"A@"ac$Q@A@"	%: :bQ	Cac&Q@A@f,aK(hMISCO0	@HCaqYrac*A@"		: :!u!}!y!y!y!a!n!"$FILCO0!$CUCOM0!0$hMISCO0!,9 9#GETLIN!#MKTEMP! #OPEN!#ERRMSG!#LOCK!$#FCOPY !&#CLOSE !(#UNLOCK!*#REWIND!.#PUTLIN !2#RMTEMP
 
"%
$0&8R& LMEMB : :jMISCO0zCUCOM0dFILCO0"*s*30t "*s*5t " *s*15t 	Yo< <u are not permitted to list conference members. ,aK("CUCOM0	Cac*C@		,aK,MISCO09 9	Aac.		'	can't open users list.+ac0A@	"ac2ac4,a
@6LCUCOM0A@: :	#Cac*C@,		G!ac8A@#A@"ac:A@#ac<ac>A@"ac@Q@A@"	$%g9 9,aKBhMISCO0	%lfklQ	C	@ t$QSacDA@a@Q@9 9	ac@Q@A@"	$@ t$QSacDA@a@Q@ac@Q@A@"	$@ t$QSacDA@a@ : :Q@ac@Q@A@"	$	acFQ@A@r]macHA@"		!q!u!}!; ;8!8!8!a!n8!>$LCUCOM0!0$"CUCOM0!4$MISCO0!J$hMISCO0!H#GETLIN; ;!8#MKTEMP!<#OPEN!2#ERRMSG!6#LUSERS!:#LOCK!@#FCOPY !B#CLOSE !D#UNLOCK!F#REWIND!L#PRINT  !N#PUTLIN!P#RMTEMP
 
"%&0&2V$ LOGIN 9 9jMISCO0zCUCOM0dFILCO0	&Please enter your name:  .The data base is locked --- please ask for assista: :nce.acC@Q@Q	A
ac,a
@~CUCOM0Q@acA@A@"	%Bac9 9A@acA@A@"	%
OacC@NA	Ah, an unfamiliar name@.. If you would like the 9 97name you just specified.to be the name by which Moot will identify you. (the management recommends calling nam9 97e followed. by last name, both capitalized), please verify. by typing 'y':  . Very well@.  Please reenter Moot; ;	 and try again@.. Sacac,a
@~CUCOM0A@,a
@ fFILCO0A@	BCac"A@A@: :,a
@~CUCOM0A@	@QLac$Q@LQ@ac"Q@A@,a
@~CUCOM0A@ac&Q@ac": :Q@A@,a
@~CUCOM0A@		,aS(CUCOM0ac",a
@*CUCOM0A@,a
@~CUCOM0A@; ;ac,,a
@~CUCOM0A@,a
@ fFILCO0!A@ac.ac0C@Tac0C@aac0C@xac0C@ac0: :C@)acC@AQ@Q	%	U	%
XTac0C@Jac2,a
@~CUCOM0	Q@ac4Q@9 9,a
@ fFILCO0A@ac6W	$Please enter a secret password, which will be.required to reenter the Mo9 9
ot in the future: . lac0C@mac8A@	#ac8A@acC@Q@fac8A@#ac0A@< <ac:Q@fac"Q@fA@,a
@~CUCOM0A@q	You are not permitted to log in now.Eac<9 9,a
@*CUCOM0A@,a
@~CUCOM0A@,aK(CUCOM0	Cac.acC@Ff	Please e; ;)nter your password: . Your password was incorrect.Please recheck it and try again.m		,aS(CUCOM0ac": :,a
@*CUCOM0A@,a
@~CUCOM0A@ac>,a
@~CUCOM0A@,a
@ fFILCO0	A@ac.ac8: :A@	#*ac8A@acC@nQ@fac8A@#ac0A@ac:Q@fac<Q@A@,a
@~CUCOM09 9A@ac@Q@fQ@	Aac0C@}ac0C@			,aS(CUCOM0ac",a
@*CUCOM0A@9 9,a
@~CUCOM0A@ac>,a
@~CUCOM0A@,a
@ fFILCO0A@ac6`D	Welcome to the M5 5oot@..			,aS(CUCOM0ac",a
@*CUCOM0A@,a
@~CUCOM0	A@ac0C@	@ 9 9,aSBMISCO0ac2,a
@~CUCOM0,a
@DCUCOM0ac,a
@F|CUCOM0,a
@DCUCOM0		!. !9 9@!!!/!/!
Y!d!h!i!n!o!	y/E; ;!.$fFILCO0!R$CUCOM0!"$~CUCOM0!T$|CUCOM0!8$CUCOM0!6$CUCOM0!P$MISCO0!,#GETENT; ;!N#EQUAL !F#DUPLX$!$#SEM$TS!#ASK ! #PUTKEY!&#SLEEP$!(#ERROR !*#LOCK!0#PUTDAT!2#FMTOC < <!4#GETTIM!:#MAKENT!<#UNLOCK!>#REMARK!@#GETKEY!B#DELENT!D#SWT !H#PWCRYP!J#GETDAT!L#UPDENT
 
"%r$0& " LOGOUT: :jMISCO0zCUCOM0dFILCO0acacQ@acQ@A@,a
@~CUCOM0A@ac,a
@~CUCOM09 9A@,a
@fFILCO0A@		!!!d!$fFILCO0!$~CUCOM0!#UPDCEN!                                                                   GETTIM!#PUTDAT!#UPDENT
 
"%"0&0>& LUSERS6 6jMISCO0zCUCOM0dFILCO0"*s*30t	You are not permitted to list Moot users. 9 9,aKCUCOM0	CacC@			can't open users list. acA@	"acac : :,a
@"fFILCO0A@	#CacC@!		<ac$A@#A@"ac&A@#ac(ac*A@"ac,9 9Q@A@"	$%\,aK.hMISCO0	%a[`aQ	C	@ t$QS: :ac0A@a@Q@ac,Q@A@"	$Q	Cac2Q@A@	ac,Q@A@"	$; ;Q	Cac2Q@A@           	ac,Q@A@"	$Q	Cac2Q@A@#gR6 6bac4A@"		!u!}!0!0!0!a!d!n0!*< <$fFILCO0! $CUCOM0!6$hMISCO0!4#GETLIN!$#MKTEMP!(#OPEN!"#ERRMSG!&#LOCK!,#FCOPY !.#CLOSE  !0#UNLOCK!2#REWIND!8#PRINT !:#PUTLIN!<#RMTEMP
 
"%&0&N$ MKCONF: :jMISCO0zCUCOM0dFILCO0"open"closed"0" yes	Yo9 9u are not permitted to make conferences.,aK$CUCOM0	Cac&C@			A conference8 8 by that name already exists.  $ac(Q@fA@ac*A@Q@ac,Q@fQ@ac.Q@fA@9 9,a
@0FILCO0A@	%
Uac&C@!		T	Access (open or closed): .Access must be 'open' : :or 'closed'.Zac*C@[Q@ac2Q@a@	Aac2Q@a@	Aac&C@h		9 9	5File for storage of text: . File for storage of index: .File for storage of user list: .Is the information9 9
 above acceptable? .*ac4Q@A@Q@fA@ac4a@A@Q@fA@ac6Q@ac4Q@; ;9A@Q@fA@ac*C@Q@ac4Q@A@Q@fA@ac*C@#Q@ac4Q@A@Q@fA@9 9*ac*C@1Q@ac4Q@A@	Q@fA@ac*C@AQ@ac2Q@a@ 	A		3ac89 9Q@A@Q@fA@ac:Q@A@
	"Cac<Q@Hac>A@"ac8Q@A@Q@f9 9A@ac:Q@A@
	"Cac<Q@dac>A@"ac8Q@A@	Q@fA@ac:Q@: :A@
	"Cac<Q@ac>A@"ac@Q@fA@,a
@0FILCO0A@		!}!9 9!!
!!b!c!d!e!f!	g!n?Ti< <tle: .!<$FILCO0!0$CUCOM0!:#GETENT!>#EQUNAM!F#CREATE!2#ERRMSG!4#INIENT!6#ASK !8#PUTKEY$ $!@#PUTDAT!B#GETTIM!D#GETDAT!H#CANT!J#CLOSE !L#MAKENT
 
"%T$0&\J
" MKMEMB: :jMISCO0zCUCOM0dFILCO0"0"	observer"participant	Yo9 9u are not permitted to add members to conferences.,aK(CUCOM0	Cac*C@			Co9 9nference name: .%ac,Q@fA@ac.C@&Q@Q	A		>	That is not the name o; ;f an active conference. @ac0Q@fQ@ac2Q@fA@,a
@4FILCO0A@	BCac*C@A9 9		j	User name: .pac,Q@0A@ac.C@qQ@Q	A			The user is al; ;                                                                                                                  eady a member of the conference. ac0Q@0Q@ac2Q@0A@Q@KA@	%
4ac*C@	9 9		3	Warning:  there is no Moot user by that name. 9	ac2Q@0A@,a
@6fFILCO0A@	B: :	Cac*C@:]ac8a@A@Q@0A@	'Observer' or 'participant' status? . lac.9 9C@mQ@ac:Q@a@	Aac:Q@a@	A		Please enter 'obse: :rver' or 'participant'. ac*C@lac8Q@A@Q@0A@ac8A@A@Q@0A@: :ac<Q@A@Q@fA@ac>Q@0A@Q@A@		!!!\!\!: :\!c!d\!g\!n\!>$FILCO0!@$fFILCO0!2$CUCOM0!<#GETENT!D#EQUNAM* *!4#ERRMSG!6#INIENT!8#ASK !:#PUTKEY!B#PUTDAT!F#GETDAT!H#MAKENT
 
"%j"0&
,$ MKTEXT; ;jMISCO0zCUCOM0dFILCO0	You are not permitted to enter text.,aKCUCOM0	CacC@< <			can't open temporary file for text storage. ac,a
@FILCO0ac,a
@FILCO0A@9 9	"CacC@		A	Subject: .Reference entries: .GacC@HQ@acQ@A@"; ;9acA@A@"acC@MQ@acQ@A@"acA@A@"ac A@ac"A@A@"ac$A@": :		!v!}
!
!
!n
~Text:.  !$FILCO0!$CUCOM0!#CREATE!. .#ERRMSG!#REMOVE! #ASK !"#PUTLIN!$#PUTCH !&#REMARK!(#FCOPY !*#CLOSE 
 
"%
$0&.& REVCEN; ;jMISCO0zCUCOM0dFILCO0	You are not currently in a conference.,aKMISCO0	AacC@: :			You are not permitted to review conference entries. ,aKCUCOM0	CacC@		: :<	Entry or range of entries: .Entries are specified by number.B	acC@CQ@	A"acQ@9 9A@"	#AacC@Q		q	Entries are specified by number.w	t"QK	C	("@: :	acQ@A@"	$AacC@x			#$$#!	$"	#$$acA@#3 3A@$		!-!n!$CUCOM0!$MISCO0!#CTOI!#ERRMSG!#ASK !#REVCES
 
"%&0&Y,* REVCES9 9jMISCO0zCUCOM0dFILCO0"
*n*n[*i] "*s, *sRe:  *sCross-Refe9 9rence:  *s*n">page *i; continue? "Rpage *i (fin; ;
al page) 	Entry number specified is out of range. achQ	@Q@A@acjQ@R9 9A@aclQ@RQ@acnQ@RA@,a
@p2CUCOM0A@	BCacrC@		6	Fatal 9 9error --- can't open text storage file. <actQ@A@Q@RA@acvQ@Q@hacxA@	"9 9aczac|,a
@~CUCOM0A@	#CacacC@=tacQ@hA@#acQ@A@#9 9	$%,aKhMISCO0	%
Q	%		&	ac
Q@A@&	': :	Qg$"	@H'                           #acA@"a@A@'	@ t$QSacQ@A@Q@6A@/; ;9acQ@A@Q@A@>acQ@A@Q@A@IacQ@A@Q@lA@TacA@": :!a@Q@6Q@lQ@Q@acQ@A@"acQ@A@#	$Q	Cn_	%	(L: :U
0?`J&acA@#acacA@"acA@"9 9a@>a@RA@
A@A@actQ@A@,a
@|CUCOM0A@	A&	ac
Q@A@&	)$': :@achA@'Q@A@acQ@A@,a
@|CUCOM0A@AacA@"		!u!}!9 9Y!!!!!!Y!
Y!	`Y!cY!iY!; ;z!~$2CUCOM0!$CUCOM0!&$|CUCOM0!$hMISCO0!#CTOI!|#GETENT!#GETLIN!
#OPEN!#MKTEMP< <!v#ITOC0F!x#INIENT!z#PUTKEY!#ERRMSG!#GETDAT!#CTOFM !#LOCK!#UNLOCK!#ERROR !#SEEKF 0 0!#PRINT !#SCOPY !#PUTLIN! #CLOSE !"#REWIND!$#PAGE!(#PUTDAT!*#RMTEMP
 
"%*0&& REVPN ; ;jMISCO0zCUCOM0dFILCO0	You are not permitted to review personal notes. ,aK CUCOM0	C; ;acC@			 Note number or range of numbers: .Notes are specified by number.#	acC@$Q@: :	A"	acQ@A@"	#AacC@5		T	Notes are specified by number.Z	t"QK	9 9	C	("@	acQ@A@"	$AacC@[		z	#$$	$o	#$4 4	acA@#A@$		!-!n!$ CUCOM0!#CTOI!#ERRMSG!#ASK !#REVPNS
 
"%&0&o0* REVPNS9 9jMISCO0zCUCOM0dFILCO0"&*n*n[*i] *s, *sRe:  *sCross-reference:9 9  *s*n">page *i; continue? "Rpage *i (final pag9 9e) 	Note number specified is out of range.	achQ@A@,a
@j~CUCOM0A@	A7 7	"	aclQ@A@"	#'acnQ	@Q@A@acpQ@RA@acrQ@RQ@actQ@RA@9 9,a
@vLFILCO0A@	BCacxC@		H	Fatal error --- can't open text storage file. N9 9achQ@A@Q@RA@aczQ@Q@Nac|A@	$ac~ac,a
@2FILCO0A@	%C9 9acacC@OacQ@NA@%ac
Q@A@%	&%,aKhMISCO0	%"9 9!"Q	'		"	aclQ@A@"	(Q_	C#4	#acA@(; ;	#	@ t&QSacQ@A@Q@A@<	@ t&	QSacQ@,a
@CUCOM0	AQ9 9	%]ac
Q@A@%	&X\WKacQ@A@Q@A@eacQ@A@Q@h9 97A@pacQ@A@Q@lA@{acA@$a@A@(Q@Q@lQ@Q@hacQ@A@$9 9	ac
Q@A@%	&Q	C'	'	)L           (0|13456=f9 9
q7<L=)5$acA@%acacA@$acA@$a@>a@RA@
A@A@9 9ac A@$acnA@#Q@A@ac"Q@A@,a
@j~CUCOM0A@		!u!}!o8 8!!!o!!o!
o!	`o!io!z!$LFILCO0!9 9$2FILCO0! $CUCOM0!v$~CUCOM0!$hMISCO0!x#CTOI!#GETENT!#GETLIN!#EQUNAM!#OPEN!: :#MKTEMP!t#GETDAT!z#ITOC0F!|#INIENT!~#PUTKEY!#ERRMSG!#CTOFM !
#LOCK!#UNLOCK!#ERROR < <!#SEEKF !#F$MA11!#SCOPY !"#PRINT !$#PUTLIN!&#CLOSE !(#REWIND!*#PAGE!,#RMTEMP!.#PUTDAT
 
"%z*0&%," RMCONF9 9jMISCO0zCUCOM0dFILCO0	You are not permitted to remove conferences.,aKCUCOM0	C9 9acC@				Conference name: .!acQ@fA@acC@"Q@Q	A		:< <	That is not the name of an active conference. <acQ@fQ@acQ@fA@,a
@FILCO0A@9 9	BCacC@=		f'acQ@A@Q@fA@ac Q@acQ@A@Q@fA@ac 9 9'Q@acQ@A@Q@fA@ac Q@ac"Q@fQ@ac$Q@,a
@FILCO0A@		!; ;%!%!e!f!g!n!"$FILCO0!$CUCOM0! #GETENT!#ERRMSG!#INIENT$ $!#ASK !#PUTKEY!$#GETDAT!&#REMOVE!(#GETKEY!*#DELENT
 
"%R"0&&" RMMEMB: :jMISCO0zCUCOM0dFILCO0	You are not permitted to remove members from conferences. ,aKCUCOM0: :	CacC@		"		Conference name: .(acQ@fA@acC@)Q@0Q0	A< <		A	That is not the name of an active conference. CacQ@fQ@0acQ@fA@,a
@FILCO0: :A@	BCacC@D		m	User name: .sacC@tQ@0Q0	A		ac9 9Q@A@Q@fA@ac Q@0Q@A@		!!!g!n! $FILCO0!/ /$CUCOM0!#GETENT!#ERRMSG!#INIENT!#ASK !#PUTKEY!"#GETDAT!$#DELENT
 
"%8"0&
$ STATUS9 9jMISCO0zCUCOM0dFILCO0"Present:*n"     *s"$	*nYou are9 9 in conference '*s'*n"D*nYou are not in a conferenc8 8e at this time*n	Cannot open master userlist.acrA@	"actacv; ;,a
@xfFILCO0A@	#Caczac|C@			ac~Q@A@#	%0Q	C: :acQ@A@Q@fA@4Q	CQ	CacQ@fA@"ID?'/: :!acA@#aczacA@"acA@a@ac~Q@A@"	%jacA@a@Q@ai9 9ac
A@",aKMISCO0	A
acA@a@$,a
@fCUCOM0z	acA@a@D		6 6!u!}!!!!!a!n!o!$fFILCO0!; ;$fCUCOM0!$MISCO0!#GETLIN!#OPEN!|#MKTEMP!~#LOCK!#UNLOCK!#ERRMSG!
#SCOPY !#PUTLIN !#CLOSE !#REWIND!#PRINT !#RMTEMP
 
"%p$0&
V& SUBCEN9 9jMISCO0zCUCOM0dFILCO0"	observer"*s*n" *c*s"&*c*n: :",*i*n	You are not currently in a conference.,aK2MISCO0	Aac4C@9 9			You are not permitted to submit text. ,aK6CUCOM0	Cac4C@		5	No9 9 entry has been made. ;ac8,a
@:FILCO0A@	"Cac4C@<		Q	You have 'ob9 9server' status only; you cannot submit. W	ac<Q@A@,a
@>|CUCOM0A@ac@Q@a@	A
: :ac4C@X			fatal error --- can't open conference text file.	acBac8,a
@DCUCOM09 9A@	#CacFacHC@
-	fatal error --- can't get conference entry. 4acJA@#; ;acLQ@fA@acNQ@f,a
@PfCUCOM0	acRQ@fA@,a
@TFILCO0A@	BCacFacH: :C@5gac<Q@A@Q@fA@	A$	acVQ@A@$	B%acXA@%Q@A@acZQ@; ;A@Q@fA@acZQ@A@,a
@>|CUCOM0A@ac\Q@fA@,a
@TFILCO0	A@acLQ@0; ;A@	acNQ@0Q@acZ,a
@^CUCOM0A@
Q@0A@	ac`Q@A@"	$acZQ@A@Q@0; ;A@	ac`Q@A@"	$*acZQ@A@Q@0A@	acbQ@acZQ@A@Q@0A@	acdA@#: :$QacfQ@Q@acZQ@A@Q@0A@	achQ@0A@	,a
@j2CUCOM0A@	A$	($; ;	@	$%		@9@ADQGJQaclA@#a@Q	@                           	ac`Q@A@"	%0acl: :A@#a@ A@Q@'/'aclA@#a@&A@acnA@"acnA@#acFaclA@a@,A@%9 9		!u!}!!!!!!!	!V!fV!c!: :dV!i!
j!k!        l!m!nV!z!h$FILCO0!N$FILCO0!r$CUCOM0!d9 9$fCUCOM0!~$2CUCOM0!X$CUCOM0!R$|CUCOM0!J$CUCOM0!F$MISCO0!L#OPEN!f#GETENT!j#CTOI; ;!t#GETLIN!T#EQUNAM!x#MARKF !H#ERRMSG!P#GETDAT!V#LOCK!Z#UNLOCK!\#ERROR !^#WIND!`#INIENT7 7!b#PUTKEY!l#ITOC0F!n#PUTDAT!p#UPDENT!v#GETTIM!z#FMTOC !|#MAKENT!#PRINT !#CLOSE 
 
"%<&0&.t( SUBPN : :jMISCO0zCUCOM0dFILCO0"*s*n"*s*n"*c*n""*i*n	9 9You are not permitted to send personal notes. ,aK(CUCOM0	Cac*C@			Addres9 9see: ."ac,Q@fA@ac.C@#Q@Q	A		8	That name does not correspond to: : a Moot user. :ac0Q@fQ@ac2Q@fA@,a
@4fFILCO0A@	BCac*C@;		d; ;	No entry has been made. jac6Q@A@Q@fA@ac8,a
@:FILCO0A@	"Cac*; ;C@k		
	Personal note key file is unavailable.ac<ac8,a
@>~FILCO0A@	#C: :	ac@acBC@                           /	Fatal error --- cannot open text file.6	acDQ@A@#	$A%acFQ@9 9A@%	B&0acHA@&Q@A@acJA@#acLA@#a@Q@acNA@#ac0Q@fQ@ac8; ;,a
@P2FILCO0A@	'Cac@acBC@7	acRA@'ac6,a
@TCUCOM0	A@Q@fA@; ;	acDQ@A@"	$ac6Q@A@Q@fA@acDQ@A@"	$ac6Q@A@	Q@fA@acV; ;9Q@ac6Q@A@
Q@fA@acXA@'Q0acZQ@0Q@ac6Q@A@Q@fA@ac\Q@f: :A@,a
@^LFILCO0A@	A$	($@i	$%	@9@ADQGQ0acLA@'a@Q	@09 9jn		QacDQ@A@"	%ac`Q@A@'acLA@'a@A@acN: :A@'ac@acLA@a@"A@&acNA@"		!        u!}!!!.!.!7 7!.!f.!
d!i!j!k!l!	m!n!p.!z!F< <$fFILCO0!p$LFILCO0!b$2FILCO0!L$FILCO0!P$~FILCO0!f$CUCOM0!:$CUCOM0!D#GETENT!V#GETLIN9 9!X#CTOI!J#OPEN!j#MARKF !<#ERRMSG!>#INIENT!@#ASK !B#PUTKEY!H#PUTDAT!N#LOCK!R#UNLOCK< <!T#ERROR !Z#ITOC0F!\#REWIND!^#PRINT !`#CLOSE !d#WIND!h#GETTIM!l#FMTOC !n#MAKENT!r#PUTLIN
 
"%Z(0&  " UPDCEN; ;jMISCO0zCUCOM0dFILCO0,aKMISCO0	A
acQ@acQ@A@,a
@|CUCOM0A@ac9 9,a
@|CUCOM0A@,a
@LCUCOM0A@	@ ,aSMISCO0		!! !d !& &$LCUCOM0!$|CUCOM0!$MISCO0!#GETTIM!#PUTDAT!#UPDENT
 
"%"0&I0& DELENT; ;	acQ@pA@QK	@HCac	:  can't open.	acQ	@A@	"Cac< <Q	@A@acC@QK	@HCac.			can't open scratch file for deletion. 2ac9 9Q@pA@	#CacA@"acC@3QK	@HCac\		O	ac Q@
A@"	$; ;	BCacA@"acA@#ac"Q@pQK	@HCacz		iQ
	Cac$Q	@: :Q@	A
ac Q@
A@"	$BCQ
	CacQ@
A@#ac&A@"A@#: :
acQ@
A@#`'acA@"ac"Q	@acA@#ac(Q@pQ	@QK	@HC: :acE		!q!}I!I!I!f!a!#OPEN!"#CREATE!&#GETLIN!*: :#EQUNAM!#SCRATF!#LOCK!#PUTLIN!#ERRMSG! #UNLOCK!$#CLOSE !(#REMOVE!,#FCOPY !.#RENAME
 
"%|&0&-$ GETDAT9 9	@ QS		"	("@	"Qg		@9@#ADQKQ_	C	#ADQGQ8 8acQ	@A@Q	@A@				!!-!!!f!#SCOPY 
 
"%2$0&,
& GETENT; ;	QK		@HCac	:  can't open.	acQ	@A@	"CacQ	@A@ac: :C@			#QK		@HCac*	#		acQ@A@"	$BC		#	acA@"QK	9 9	@HCacC-8Q	C/	@ t$QS	uQGQracQ	@rQ@	A
/: :ac Q@A@Q	@A@		%	(%@i	%Qg	@9@ADQGQracQ	@rA@": :	$BCo	%9@$AD@ QSj	%@H#	acA@"QK		@HCac-!: :!!q!}!!!!f!a!#OPEN!$#GETLIN!(#EQUNAM!" "#LOCK!#PUTLIN! #ERRMSG!"#UNLOCK!&#CLOSE !*#SCOPY 
 
"%&0&
" GETKEY( (	uQGQacQ	@A@Q	@A@		!                                 #SCOPY 
 
"%*"0&$ INIENT: :	A"	("@	"Qg	@9@#AD	QS	#AD@ QS			QS		! !!f!0!a
 
"%*$0&

$$ LOCK9 9	fatal error --- mutual exclusion failure. 	acA@A@"	"A
acC@		! !#SEM$WT!#ERROR 
 
"%$$0&X,$ MAKENT: :"*s*n	QK		@HCac	:  can't open for update. 	acQ	@A@	"9 9	CacacQ	@A@acC@	ac A@"	A#	(#@3	#Qg	@9 9	9@ADQGQac"A@"a@Q	@49ac$A@",QK		@HCacT		!: :!q!}X!X!fX!#OPEN!#LOCK! #UNLOCK!"#PUTLIN!$#ERROR !&#WIND !(#PRINT !*#CLOSE 
 
"%2$0&b& PUTDAT< <		"	("@	"Qg		@9@AD
QKQg	%	"9@#ADQG; ;QacQ	@A@Q	@A@acQ	@	$#ADQK	C	@ QS9	"9@ADQK: :QS				in putdat:  datum doesn't fit in entry. HacC@I		!!b' '!!!f!
!0!#LENGTH!#SCOPY !#ERROR 
 
"%4&0&"$ PUTKEY9 9		QS	uQGQacQ	@A@Q	@A@acQ	@	"t"QK	C	@ QS 		!"!
!a!#LENGTH!#SCOPY 
 
"%,$0&$$ UNLOCK9 9	fatal error --- mutual exclusion failure. 	acA@A@"	"A
acC@		! !#SEM$NF!#ERROR 
 
"%$$0&y@& UPDENT: :"*s*n"*s*n	can't open scratch file for update. acQ@rA@ac9 9Q@rA@	"Cac C@#QK		@HCac",	:  can't open./ac$Q	@9 9A@	#C ac&ac(A@"ac*Q@rac,Q	@A@ac C@0@	A$	($@W	$; ;Qg	@9@ADQGQXac.A@"a@Q	@XX]	ac0Q@A@#	%BCac(A@"< <ac*Q@r	A$	($@	$Qg	@9@ADQGQXac.A@#a@Q	@X
ac(; ;A@#QK		@HCac&%		yQ	C	uQGQXac2Q	@XQ@	A
ac0; ;Q@A@#	%BCDQ	C;ac,Q@A@"ac4A@#A@"E:-ac,Q@9 9A@"pWac(A@#ac*Q	@ac(A@"ac6Q@rQ	@QK		@HCac&u		!: :!q!}y!y!y!fy!ay!,#OPEN!&#CREATE!8#GETLIN!:#EQUNAM< <!$#SCRATF!(#ERROR !*#LOCK!.#UNLOCK!0#CLOSE !2#REMOVE!4#PUTLIN!6#PRINT !<#FCOPY !>#RENAME
 
"%&0&

o$& ASK ; ;jMISCO0zCUCOM0dFILCO0"*p	,awgMISCO0,aKMISCO0	C,akgMISCO09 9,awgMISCO0,aKMISCO0	AacA@a@Q	@ac,a
@MISCO0A@	"B5 5	C#	@ t",aSMISCO0	A,aSgMISCO0,awgMISCO0,aKMISCO0	C6 6,akgMISCO0,,2         A#,akgMISCO0	@9,awgMISCO0,aKMISCO0	A$9 9,aKMISCO0	CCA	$	A	#@H%,aKMISCO0	t%QS	(#::J	#@HAD@ QS9 9,awgMISCO0,aKMISCO0	C,akgMISCO0	@bQK	C$jk: :l		!u!vo! o!;!?o!$MISCO0!"$MISCO0!$gMISCO0! #GETLIN !#PRINT 
 
"%,&0&C", GETCMD9 9jMISCO0zCUCOM0dFILCO0"*p"Please enter one of the follow: :	ing:*n*n"<
     *s*n"FUnrecognized command*n"^8 8#You must differentiate between*n*n"
     *s*n	; ;,awgMISCO0,aKMISCO0	C,akgMISCO0,awgMISCO0,aKMISCO0	A5 5acA@a@Q	@ac,a
@MISCO0A@	"BC#	@ t",aSMISCO0	A9 9,aSgMISCO0,awgMISCO0,aKMISCO0	C,akgMISCO0,,2           $78 8,aKgMISCO0	#,awgMISCO0,aKMISCO0	C,akgMISCO0<<B,awgMISCO09 9,aKMISCO0	C,akgMISCO0	@	acA@a@		"	("@YQK	B"C7 7	"@HADQK	$t$QGQ
acA@a@<Q	@
Za	acA@A@	@ ,awgMISCO09 9,aSMISCO0M,awgMISCO0,aKMISCO0	A,awgMISCO0,aKMISCO0	< <	C,akgMISCO0,awgMISCO0,aKMISCO0	A%,aKMISCO0	CC&,aKMISCO06 6	CC',aKMISCO0	CC	A	'A	&A	%	A,akgMISCO0/,awgMISCO06 6,aKMISCO0	(@ ,aSMISCO0	)	"	("@?QK	B"C	"@HADQK	$t#9 9,aGMISCO0Q
	t$QGQacQ	@
Q	@	A
	$@HADQK	*()@_@G	): :	AacA@a@F	@ ,awgMISCO0,aSMISCO0k	(,awgMISCO0,aSMISCO0	): :	@HC	*+	<	acA@a@^		"	("@QK	B"C	"@HADQK: :	$t#,aGMISCO0Q
	t$QGQacQ	@
Q	@	A
acA@a@Q	@-: :	acA@A@	@ ,awgMISCO0,aSMISCO0w!u!vC!C!	!
: :! C!;!?C!$MISCO0!$MISCO0!$gMISCO0!#GETLIN! #EQUNAM!#PRINT ! #PUTCH 
 
"%:,0&q($ GETYN : :"	*s (*c) 	QK	@HAD!QG	QracA@a@Q	@Q	@racA@Q@Q; ;	"QK	@HAD	QS	QK	@HAD	QS	$QK	@HADQKQS	,5	"A
6: :	#L7@AB-	"%I%	%L	%O-	%R%	%UC: :	Unacceptable input, please try again. UacC@V76mn		!. !uq. .!>!N!Yq!d!nq!y!"#PRINT !$#ASK !&#ERRMSG
 
"%$0&$ CTOFM  	A"acQ	@A@"QS		!#CTOL
 
"%*$0&|& EQUNAM; ;	A"#"@HADQK	C	("	#@HADQK	C	(#	"@HADQK; ;	A	A$	 	"@HADQK	A	@ $	*	"@HADQGQ	#@HADQGQacQ	@: :	%acQ	@	%CQK	%M	%PL	A
OQGR	("@(#..S; ;	"@HADQK	%a	%d`	A
ce	#@HADQK	%o	%rn	A
q( (	(#ggsf	@ $	w!	! |!#MAPDN 
 
"%0&0&$ FMTOC  	acQ	@Q	@A@	"	!f!#LTOC
 
"%*$0&" GETTIM: :		acA@Q	@		uQS	uQGQacA@Q	@		!!!!	
 
! !#DATE
 
"%("0&($ ITOC0F9 9	acQ	@Q@
A@	"A#	(#@QK	"@H#C	#@HAD	QSac' 'Q@
A@Q	@A@#		!!
!0!#ITOC!#SCOPY 
 
"%8$0&.( PWCRYP< <	acQ	@	"A#	(#@	#$"	@@H$"@H%t$QK	At%QO	&QK	At$QO( (A	&QS	%'	QS(			! !#LENGTH
 
"%,(0&0 $ RENAME9 9		acQ	@A@	"CacQ	@
	acQ	@A@	#CacQ	@ac: :A@"A@#acA@"acA@#acQ	@		!}0!!!#OPEN!#CREATE!#CANT !#FCOPY !#CLOSE !#REMOVE
 
"%*$0&J.$ SCRATF9 9"=temp=/mo$*s$*i		ac A@Q@	A"	("@		"%	@ac"9 9Q	@Q	@a@Q@A@"ac$Q	@A@	#C		%ac&A@#
	fatal error 9 9--- cannot generate scratch file name.,ac(C@-!}J!J!!
J!(#OPEN !$#DATE!&#ENCODE!*#CLOSE !,#ERROR 
 
"%$0&