$&": :LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEMac,aKPARCOM	%	Cac9 9	,aKPARCOM	Cac,a
@PARCOMA@,a
@CCOMac           ac9 9acac !!!!$!$PARCOM!$PARCOM!$CCOM!#INITI0 !#GETSYM!#ENTER ! #INSTR0!"#CLEAN0!$#SWT 
 
"%""0&(& ALPHA ; ;	QK	CA"	Q_	CA""QK	CA#	Q_	CA##QK	CC$QK	CCA	$A	#   A	"	%	!A!Z!_!`!a!z
 
"%*&0&b.& BREXPR5 5LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM	                                                                                                                    arget of branch must be a label. 8 8,aKPARCOM	%acC@	
branch out of range.ac,a
@PARCOM	"t"; ;,aKOSYMTAB	%3,aKSYMTAB,a_CCOM	@HQS	CD#QK	CA#AacC@6 6C2acA@	$t",aK oSYMTAB	t$,aS"DS$MEM,aKCCOM,aS$DS$MEM	$t"5 5,aS oSYMTAB	@ QSHac&		!b!!!b!b!*< <$DS$MEM!($DS$MEM!$PARCOM!$PARCOM!$OSYMTAB! $SYMTAB!&$oSYMTAB!"$CCOM!#LOCAT0 !$#DSGET !#ERRMSG!,#GETSYM
 
"%*&0&)$ CHAIN09 9	QK	""%%acQ	@A@"acA@"acA@#acA@"acQ	@	#"7 7QK	%&ac%		!)!#PUTREL!#XSEEK !#GETWO0!#PUTWO0!#SEEKE0
 
"%.$0&<& CLEAN0: :LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEMacA@,aKCCOM	M="acA@"	A7 7	#	(#@	#$"	@t#,aGRELMAPQacQ	@                           	A#	(#@#	#: :,ag@SYMTAB	@t#,aKSYMTAB	AD,aKDS$MEM	%
4acA@	t#,aKSYMTAB	AD; ;,aGDS$MEM	QacQ	@	$acA@$	t#,aG OSYMTAB	QacQ	@	t#,aG"SYMTAB; ;	QacQ	@	t#,aKSYMTAB	%	(%@`	t%,aGDS$MEMQQK	A
ac$Q	@; ;	$acA@$akacA@3$)	ac&A@ac,a
@CCOM,aK(LSTNG 	@HC9 9ac*ac,,a
@.LSTNG ac,,a
@0LSTNG ac,,a
@2CCOM		!!!!5 5!!!!_!$$DS$MEM!"$SYMTAB!($OSYMTAB!*$SYMTAB! 9 9$@SYMTAB!$RELMAP!$CCOM!:$CCOM!6$LSTNG !0$LSTNG !8$LSTNG !&#LENGTH!,#CTOA !#PUTBY0!#PUTWO0!.#SEEK!2#BUILD0!4#CLOSE 
 
"%(&0&&$ COMPA09 9	A"	("@	"@HADQKQg	A	@ #	           	"@HADQKQg 	A#		#!	#	!&
 
"%*$0&N"& COMPL09 9LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM	QK	"                                                                                                  branch to this label is out of r: :ange. 	"%	t",aKDS$MEM	#	acA@#QK	#@H$CD%$CA%AacC@9 92acA@$	"#t",aKDS$MEM	"acA@#QK	%KacJ		!9 9!N!N!$DS$MEM!$DS$MEM!#XSEEK !#ERRMSG!#PUTBY0!#DSFREE! #SEEKE0
 
"%,&0&" CPUTB0; ;LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM	acQ	@acQ	@,a
@CCOM,akCCOM 	@	!$CCOM!#PUTBY0!#PUTREL
 
"%("0&$ CPUTW02 2	QK	B`"acA@"Q	@QK	B("	acA@"A@		!!#CPUTB0
 
"%*$0&

$ CTOA 	QK	"	!
 
"%($0&2~* DOMACH9 9LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM"	IKDHHXGGW$%',."E/#-9 97+&* ()OO_
ACCSJJZ4	HLL\1NFNDDT@@P
J6723IIY9 9FFV;9BGO@?MM]05>"|888888889 9788x8888xx889 9 88888888	                                                                                                                      alue relocatable or larger than 1: : byte.QwaK	"aK{	#ach,aKjPARCOM	Cach	#8aclA@"A@9 9	acnA@$A@%	$CA&$CD'%@HCB'&AacpC@DaclA@$A@)	#9; ;aclA@"A@acnA@$A@%acrA@$A@%R	                                                                                                         mmediate addressing not allowed. facp9 9C@geO$	value is not a valid index. },aKjPARCOM	Cach	#;	": :	(aclA@(A@acnA@$A@%	$CA&$A'%@HCB'&AacpC@~2	aclA@$A@9 9,aKjPARCOM	Aach@	missing ']'.DacpC@EC	indexed addressi; ;
ng not permissible. PacpC@QO	#=aclA@"A@j	#>aclA@"; ;A@actA@$aclA@$A@t	#<	"(aclA@(A@acnA@$A@%acrA@$: :A@%	in do_mach: can't happen. acpC@ qg|		!2!2!9 92!2! 2!02!2!r$PARCOM!p#GETSYM!t#CPUTB0!v#EXPR!x#ERRMSG !z#CPUTW0!|#BREXPR
 
"%.*0& .( DOPSE0< <LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM	value relocatable or larger than 1 byte.ac9 9QK	AacA@"A@#	"CD$"CA%#@HCB%$AacC@0acA@"A@: :	def usage is 'def alias real'.<QK	@HC,aKPARCOM	%VacC@=U; ;	def usage is 'def alias real'.[ac,a
@PARCOMA@Q@A@ac,aKPARCOM	%|: :
acC@\{ac,a
@PARCOM	&ac Q@A@A@&acZPQK	@H: :	CacA@"A@#ac"A@"A@#	value must not be relocatable.#QK	C9 9	acA@"A@#	#@HCacC@$A	A'	('@H	'$"	@acA@A@I9 9M7	value must not be relocatable.WQK	CacA@"A@#	#@HCac: :C@Xu	backward origin not permitted.z	",ag$CCOM
acC@{,aK$CCOM	$": :acA@A@kV";		! !!!!! !: : ! $PARCOM!$$PARCOM!,$CCOM!&#LOCAT0!#GETSYM!#EXPR!#ERRMSG!#CPUTB0!"#SCOPY  !(#ENTER !*#CPUTW0
 
"%N(0&= $ ENTER 7 7LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM		symbol redefined. acQ	@	"t"6 6,aKOSYMTAB	%acC@	t",aGSYMTABQ
acQ	@
Q	@Q	@	t"6 6,aGoSYMTABQacQ	@Q	@QK	t",aSOSYMTABQKQS
		!=!, ,$OSYMTAB!$SYMTAB!$oSYMTAB!#LOCAT0!#ERRMSG!#CHAIN0!#COMPL0
 
"%2$0&" ERRMSG; ;LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM	*4i: *p*n.	acA@C@,a
@PARCOM Q	@		!q!$PARCOM!#PRINT 
 
"%&"0&

M$$ EXPR: :LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM	,aKPARCOM	@HC,aK.PARCOMQS8 8	@ QSac,aKPARCOM	Cac,a
@PARCOM	"t",aKOSYMTAB	C< <,aKSYMTABQS,aKCCOM,aSSYMTAB	@ QS	t",aKSYMTABQS,aKOSYMTAB9 9QS+ac	
missing expression. 8ac C@9	@ QSQS7		!!: :M!$PARCOM!$.PARCOM!$PARCOM!$OSYMTAB!$SYMTAB! $CCOM!#LOCAT0!#GETSYM !"#ERRMSG
 
"%*$0&$ GETBY0: :LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM		QGQac,a
@CCOM	"acA@5 5A@"Q@A@A@A@#A@#		!!$CCOM!#MAPFD !#PRWF$$
 
"%*$0&o2$ GETSYM9 9LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEMacA@"	"CC#"CCA	#	Aac9 9A@"	A
acA@"ac	"CE#	"CEA	#	AacA@"ac&	"C8 8ac1	"Cac8	"C		,aSPARCOM?	"C	@ : :,aSPARCOMG	"	C		
,aSPARCOMO	"C		,aSPARCOMW9 9	"C		,aSPARCOM,ak PARCOMe_	"BC		,aSPARCOMjf[SKC: :;4-		!!!
!o!	!
! !	#!$!%!0!9; ;!;![!]o!.$PARCOM!0$PARCOM!"#ALPHA ! #INCHAR!$#PUSHB0!&#SCANID!(#SCAND0 !*#SCANH0!,#SCANC0
 
"%$$0&$ GETWO0" "	acA@"acA@#	"B A	#QS		!#GETBY0
 
"%($0&/" INCHAR5 5LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM	,aKPARCOM	A,awPARCOM5 5,aK#PARCOMQS	A,aSPARCOM	acQ	@A@,awPARCOM,aS#PARCOM5 5,aKLSTNG 	@HCacQ	@,a
@LSTNG QK	%),aKPARCOM	@H9 9,aSPARCOM(		!v!/!$PARCOM!$#PARCOM!$LSTNG !$LSTNG !#GETCH  !#PUTCH 
 
"%&"0&HB$ INITI0; ;LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM".o	can't open output file. ac: :a@A@,aSCCOM	CacC@	@ ,aSLSTNG 	@ ,aSCCOM	acA@Q@9 9A@	%-Q	C,		"	("@4	t"QK	A
	%?	%B>; ;A	                                                                                                   an't open listing temporary file.C	A,aSLSTNG ac A@,aS"LSTNG 	C; ;acC@D`	                                                                                                   an't open source temporary file. eac A@,aS$LSTNG 	CacC@f9 9B	t"QK	%		%

	A,aSCCOM	Usage: as6800 [-; ;{l|d}]. acC@5;1	A,aS&PARCOM	@ ,aS(CCOM,aS*@SYMTAB,aS,PARCOM9 9ac.A@ac0ac2A@		"	("@;	"%	@ac2A@<@		!}!7 7!!!!H!!-H!
D!L!	d!lH!'H!46 6$PARCOM!:$PARCOM!8$@SYMTAB!6$CCOM!$$CCOM!*$CCOM!0$LSTNG !($LSTNG !20 0$LSTNG !"#CREATE!,#GETARG!.#MKTEMP!&#ERROR !<#DSINIT!>#GETSYM!@#PUTBY0
 
"%$$0&J($ INSTR0: :LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM	*8,i*8,i*n. ,aKLSTNG 	@HCac: :,a
@LSTNG C@,a
@CCOM,a
@PARCOMac,a
@PARCOMA@"	@HCacA@"9 9ac ,a
@PARCOMA@"	@HC
ac"A@",	unrecognized symbol in op field.: :2	ac$C@3ac&1#		!$PARCOM!$PARCOM!$CCOM!$LSTNG !$LSTNG !#PSEUD0% %! #MACHOP!#PRINT !#DOPSE0!"#DOMACH!$#ERRMSG!&#GETSYM
 
"%$$0&a($ LOCAT09 9LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM	A"	("@	",ag@SYMTAB	@8 8	t",aKSYMTAB	AD,aGDS$MEMQacQ	@Q	@	@HC	t",aKOSYMTAB	@HC9 9,aKSYMTAB	#!	"#%	#			too many symbols --- assembly stopped.+		; ;,ag@SYMTAB	@	acC@,acB,ak@SYMTAB	@ac Q	@,aw@SYMTAB,aSSYMTAB: :		,aSOSYMTAB		,aSSYMTAB,aS"oSYMTAB,aK@SYMTAB	#(!a!a!P: :a!$DS$MEM!$SYMTAB!$OSYMTAB!$SYMTAB!&$oSYMTAB!$@SYMTAB!#EQUAL !$#SDUP! 
 
#ERRMSG!"#SWT 
 
"%*$0&30( MACHOP9 9"5abaadcaadcbaddaaddbandaandbaslaslaaslbasr9 97asraasrbbccbcsbeqbgebgtbhibitabitbble9 97blsbltbmibnebplbrabsrbvcbvscbaclc9 97cliclrclraclrbclvcmpacmpbcomcomacombcpx9 97daadecdecadecbdesdexeoraeorbincincainc9 97binsinxjmpjsrldaaldabldsldxlsrlsralsr9 97bnegneganegbnoporaaorabpshapshbpulapulbrol9 97rolarolbrorrorarorbrtirtssbasbcasbcbsec9 97seisevstaastabstsstxsubasubbswisystab9 9/taptbatpatsttstatstbtsxtxswai	A"	#9 9	#"A?$9@ADaGQac,Q	@Q	@	%A	$B"	%A		$@H#	#$"+ +	%A	A&$QS(	@ &.	&	!!l3!.#COMPA0
 
"%0(0&H.$ PSEUD0; ;"byte"def"word" res"$org	A"ac(Q	@9 9a@	@HC	@ QS	ac(Q	@a@	@HC	AQS	ac(Q	@a@; ;	@HC		QS%	ac(Q	@a@ 	@HC		QS2	ac(Q	@a@$	@HC+ +		QS?	@ "C6)	"	!!!H!,#EQUAL 
 
"%*$0&&" PUSHB0< <LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM	too many characters pushed back.,akPARCOM9 9	@	,agPARCOMacC@QK,awPARCOM,aS#PARCOM		!
& !$PARCOM!$#PARCOM!#ERRMSG
 
"%&"0&"& PUTBY0: :LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM	QK	B("	A"Qac,a
@CCOM	#9 9acA@A@#Q@A@A@A@$A@$		!!!$CCOM!#MAPFD  !#PRWF$$
 
"%,&0&*& PUTREL9 9LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM	QK	M=B"QK	M=@A#Aac8 8A@#	$QK	@HC	t",aKRELMAPA	$,aSRELMAP	$At",aORELMAP# #,aSRELMAP!		!!*!$RELMAP!#F$LS
 
"%,&0&$ PUTWO0& &	QK	B`"	acA@"QK	B("acA@"		!#PUTBY0
 
"%($0&$ SCANC07 7LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEMacA@"	"C,akPARCOM	@	+ +,aSPARCOM		!!
!$PARCOM!$PARCOM!#INCHAR
 
"%$$0&#($ SCAND0< <LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM"0123456789	@ ,aS.PARCOMac: :A@"ac a@A@"	#%ac"A@",aK.PARCOM	9@#@H,aS.PARCOM7 7	A,aS$PARCOM		!!
#!&$PARCOM!$.PARCOM!"#INDEX ! #INCHAR!$#PUSHB0
 
"%$$0&'0& SCANH06 6LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM"0123456789abcdef	@ < <,aS".PARCOMac$A@"ac&A@"	#	ac(a@A@#	$%ac*A@",aK".PARCOM: :	C<$@H,aS".PARCOM	A,aS,PARCOM		!'!.$PARCOM!$$.PARCOM!(#MAPDN !*                                                                   INDEX !&#INCHAR!,#PUSHB0
 
"%&&0&3 & SCANID9 9LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM	A"acA@#		#CA$#CD$$acA@#6 6A	$	A	#t",aSPARCOM	("	@ t",aSPARCOM	#C		9 9,aSPARCOM&acA@#		,aSPARCOM*		!!3!0!9!:# #3!$PARCOM!$PARCOM!#ALPHA !#INCHAR!#PUSHB0
 
"%&&0&

& SDUP: :LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM	acQ	@	B"acA@"	#acQ	@4 4A@,a
@DS$MEMA@#	#$	!!$DS$MEM!#LENGTH!#DSGET !#SCOPY 
 
"%*&0&$ SEEKE0; ;LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM	AQac,a
@CCOM	"	acA@A@"6 6Q@A@A@A@#A@#		!!!$CCOM!#MAPFD !#PRWF$$
 
"%&$0&

 $ SEEK: :LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM	QK	MQAQac,a
@CCOM< <	"acA@A@"Q@A@Q@A@#A@#		! ! !$CCOM!#MAPFD !#PRWF$$
 
"%,$0&
$ XSEEK  	QK	"acA@"		!!#SEEK
 
"%($0&f(. BUILD09 9LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEMacA@acA@"A@#A@$A@	"B #%; ;	acA@ac,a
@LSTNG ac,a
@LSTNG 	@ &'())%'acA@*A@+	BC9 9	%*&B+	)/	+&@HC	*$'@	(@HC	*',acA@"A@#A@$A@,A@*9 9	'*,acA@&A@'A@"A@#A@$A@,Q@	@ (C	In build_listing: shouldn't happ9 9en. i	*',acA@"A@#A@$A@,A@*ac Q@,a
@LSTNG 	BCac"C@j9 9	*',acA@&A@'A@"A@#A@$A@,Q@h?	+&@H-	-@H-/	in build_listi9 9ng: shouldn't happen. 3	-Aac Q@,a
@LSTNG 	BCac"C@4Q	+-,ac9 9A@,A@'A@A@A@A@Q@0H;	'$*pm	Ao	+&#q	*; ;	$'y	&+Cx	(@HC	*',acA@"A@#A@$A@,A@*	'*,	acA@&A@'9 9A@"A@#A@$A@,Q@	In build_listing: shouldn't happen. $	A(*',acA@"; ;A@#A@$A@,A@*ac Q@,a
@LSTNG 	BCac"C@%P	*',acA@&A@'A@"< <A@#A@$A@,Q@#|	*',acA@"A@#A@$A@,A@*	(@HC	*'A,ac; ;A@&A@'A@"A@#A@$A@,Q@	@ ({	in build_listing: can't happen. ac Q@: :,a
@LSTNG 	BCac"C@,	*',acA@&A@'A@"A@#A@$A@,Q@hj	*: :	'+&#&ac Q@,a
@LSTNG 	%RacA@&A@'A@"A@#A@$A@Q@	(&; ;IIQ		!!!!f!$LSTNG !$LSTNG ! #GETIN0!$#GETLIN!#SEEK !#GETCO0!#XSEEK !#REWIND!"#LISTK0!&#ERROR 
 
"%.0&$ LISTK09 9	QK	"	         (*4,16,0j)  *2,16,0j*n.acA@C@Q	@Q	@	      9 9   (*4,16,0j)  *2,16,0j *2,16,0j*n. !acA@C@"Q	@Q	@Q	@	 	         (*4,16,0j)  *9 92,16,0j *2,16,0j *2,16,0j*n.DacA@C@EQ	@Q	@Q	@	Q	@C	*5,i    (*4,16,0j)  *2,19 9	6,0j          *s. macA@C@nQ	@Q	@Q	@Q	@l	                                          5,i    (*4,16,0j)  *2,16,0j *2,169 9,0j       *s. acA@C@Q	@Q	@Q	@Q	@	Q	@         *5,i    (*4,16,0j)  *2,16,0j *2,9 916,0j *2,16,0j    *s. <acA@C@=Q	@Q	@Q	@Q	@	Q	@Q	@;	"#LD9 9!m<s	*5,i                        *s. wacA@C@xQ	@Q	@j		 !u!!#PRINT 
 
"%:$0&"$ GETIN09 9LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM	acQ@,a
@LSTNG 	BC		"	: :		A#acQ@A@#QSacQ@A@#QS		"	!~!"!$LSTNG !#GETLIN !#CTOI
 
"%$0&2& GETCO09 9LSTNG CCOMRELMAPASYMTAB/PARCOM'DS$MEM	QK		"QGQac,a
@CCOM: :	##acA@A@#Q@A@A@A@$A@$QGQac,a
@CCOM	#	acA@A@#9 9Q@A@G@A@$A@$QGQac,a
@CCOM	#acA@A@#Q@A@G@3A@$; ;A@$QGQac,a
@CCOM	#!acA@A@#Q@A@G@LA@$A@$QGQac9 9,a
@CCOM	#!acA@A@#Q@A@G@fA@$A@$QGQac,a
@CCOM	#ac9 9A@A@#Q@A@G@A@$A@$Q	"LRacQ	@	@ 	QSQSQS( (		!0!$CCOM!#MAPFD !#PRWF$$!#XSEEK 
 
"%8&0&