$&"9 9CCOMRELMAPASYMTAB/PARCOM'DS$MEMac,aKPARCOM	%	Cac	9 9,aKPARCOM	Cac,a
@PARCOMA@,a
@CCOMac           ac: :acac !!!!$!$PARCOM!$PARCOM!$CCOM!#INITI0!#GETSYM !#ENTER ! #INSTR0!"#CLEAN0!$#SWT 
 
"%""0&(& ALPHA ; ;	QK	CA"	Q_	CA""QK	CA#	Q_	CA##QK	CC$QK	CCA	$A	#   A	"	%	!A!Z!_!`!a!z
 
"%*&0&)$ CHAIN09 9	QK	""%%acQ	@A@"acA@"acA@#acA@"acQ	@	#"7 7QK	%&ac%		!)!#PUTREL!#XSEEK !#GETWO0!#PUTWO0!#SEEKE0
 
"%.$0&6
( CLEAN09 9CCOMRELMAPASYMTAB/PARCOM'DS$MEMacA@,aKCCOM	M="acA@"	A#: :	(#@	#$"	@t#,aGRELMAPQacQ	@                           	A#	(#@#	#,ag@SYMTAB9 9	@t#,aKSYMTAB	$,aGOSYMTABQQK	CC%t$,aKDS$MEM	CCA	%	A8 8acA@	t#,aKSYMTAB	AD,aGDS$MEM	Qac Q	@	$acA@$acQ	@	t#: :,aG"SYMTAB	QacQ	@	t#,aKSYMTAB	&	(&@h	t&,aGDS$MEMQQK	A
: :ac$Q	@	$acA@$isacA@@$)	ac&A@ac,a
@CCOMac(9 9,a
@*CCOM		!!!!!!!!!_!($DS$MEM; ;!$$SYMTAB!&$OSYMTAB!,$SYMTAB!"$@SYMTAB! $RELMAP!$CCOM!4$CCOM!*#LENGTH!.#CTOA !#PUTBY0!#PUTWO0!0#SEEK!2#CLOSE 
 
"%,(0&
&$ COMPA09 9	A"	("@	"@HADQKQg	A	@ #	           	"@HADQKQg 	A#		#!	#	!&
 
"%*$0&" CPUTB09 9CCOMRELMAPASYMTAB/PARCOM'DS$MEM	acQ	@acQ	@,a
@CCOM,akCCOM	@	 !$CCOM!#PUTBY0!#PUTREL
 
"%("0&$ CPUTW02 2	QK	B("acA@"Q	@QK	B`"	acA@"A@		!!#CPUTB0
 
"%*$0&

$ CTOA 	QK	"	!
 
"%($0&)v* DOMACH9 9CCOMRELMAPASYMTAB/PARCOM'DS$MEM"KVXPNpn%4/?T,LD<$'qmss{Mvc: :6lk2R*JB:"rqx&@~[i)-XIxP@ph`/HhfBzy
j7`^kxvc: :	QwaK	M="9@a_	A#"B$acdA@#A@acfachA@%A@&	C; ;		#		%AM=@C=#'acdA@'A@achA@%A@&	C		=	%AM=@#'acd9 9A@'A@4achA@%A@&	C		V	achA@(A@)	C		`	(M=@'%: :	AM=@C='#'acdA@'A@MachA@%A@&	C				%AM=@C=#'acdA@': :A@achA@(A@)	C			(B('acdA@'A@)wacdA@#A@achA@%A@)< <	C		3	%B('acdA@'A@)$achA@%A@&	C		G		%AM=@C=#'acd9 9A@'A@achA@(A@)	C		`acjA@(A@)>acdA@#A@achA@%A@)9 9	C		wacjA@%A@)h         $L	5Nx%?i	end of lin: :e expected. ,aKlPARCOM	%
acnC@,aKlPARCOM	%	%acf $		!; ;})!)!)!)!h)!n#EXPR!r$PARCOM!j#CPUTB0!l#GETSYM!p#CPUTW0 !t#ERRMSG
 
"%.*0&$.( DOPSE09 9CCOMRELMAPASYMTAB/PARCOM'DS$MEM	QK	AacA@"A@#	C			: :reloc = *i; val = *i*n. 	"CD$"CA%#@HCB%$AacA@C@A@#A@"*acA@"9 9A@	def usage is 'def alias real'.<QK	@HCac,aKPARCOM	%X9 9acC@=W	def usage is 'def alias real'.]ac,a
@PARCOMA@Q@A@ac: :,aKPARCOM	%~acC@^}ac ,a
@PARCOM	&ac"Q@A@A@&ac9 9\P	acA@"A@#	C			ac$A@"A@#;		!!u!}$: :!!!$!$!$!#EXPR! $PARCOM!&$PARCOM!(#LOCAT0!#PRINT % %!#CPUTB0!#GETSYM!"#ERRMSG!$#SCOPY !*#ENTER !,#CPUTW0
 
"%N(0&2$ ENTER : :CCOMRELMAPASYMTAB/PARCOM'DS$MEM		symbol redefined. acQ	@	"t",aKOSYMTAB9 9	%acC@	t",aGSYMTABQ
acQ	@
Q	@Q	@QK	t",aSOSYMTAB2 2QKQS
		!2!$OSYMTAB!$SYMTAB!#LOCAT0!#ERRMSG!#CHAIN0
 
"%0$0&" ERRMSG: :CCOMRELMAPASYMTAB/PARCOM'DS$MEM	*4i: *p*n.	acA@C@,a
@PARCOMQ	@ 		!q!$PARCOM!#PRINT 
 
"%&"0&

"*( EXPR9 9CCOMRELMAPASYMTAB/PARCOM'DS$MEM	
expression expected.,aKPARCOM	C		9 9	"acC@	@ QSQS	"			"ac,aKPARCOM	@HC,aK.PARCOMQS9 9ac,aKPARCOM	CE#,aKPARCOM	C@A	#	A,aKPARCOM	$	acA@%Q	@< <	"$C	%QOQSG	$C	%QOQSQM9	@ QS&,aKPARCOM6 6	Cac,a
@PARCOM	&t&,aKOSYMTAB	C,aK SYMTABQS,aK"CCOM9 9,aS SYMTAB	@ QSj	t&,aK SYMTABQS,aKOSYMTABQSvac_	9 9
missing expression. 		"acC@	@ QSQS,aKPARCOM	%	acZ7 7!}!~"!!!!"!$PARCOM!$.PARCOM!"$PARCOM!$+ +$OSYMTAB!&$SYMTAB!($CCOM! #LOCAT0!#CALLE0!#ERRMSG!#GETSYM
 
"%.(0&	$ CALLE0 		acQ	@Q	@	"	!#EXPR
 
"%*$0&$ GETBY0; ;CCOMRELMAPASYMTAB/PARCOM'DS$MEM		QGQac,a
@CCOM	"acA@A@"Q@/ /A@A@A@#A@#		!!$CCOM!#MAPFD !#PRWF$$
 
"%*$0&i0$ GETSYM9 9CCOMRELMAPASYMTAB/PARCOM'DS$MEMacA@"	"CC#"CCA	#	AacA@"	A
9 9acA@"ac	"CE#	"CEA	#	AacA@"ac&	"Cac6 61	"Cac8		"CB#"CB#A	"C,akPARCOM	@I		: :,aS PARCOME	"	C		
,aS PARCOMT	"C		,aS PARCOM\9 9	"BC		,aS PARCOMd`XP;4-		!!!
!i!	!
!; ; !#!$!&!0!9!;!	|i!.$PARCOM!,$PARCOM! #ALPHA !#INCHAR !"#PUSHB0!$#SCANID!&#SCAND0!(#SCANH0!*#SCANC0
 
"%$$0&$ GETWO0" "	acA@"acA@#	#B A	"QS		!#GETBY0
 
"%($0&$" INCHAR< <CCOMRELMAPASYMTAB/PARCOM'DS$MEM	,aKPARCOM	A,awPARCOM,aK#PARCOMQS7 7	A,aSPARCOM	acQ	@A@,awPARCOM,aS#PARCOMQK	%5 5,aKPARCOM	@H,aSPARCOM		!v!$!$PARCOM!$#PARCOM!#GETCH 
 
"%&"0&\4$ INITI09 9CCOMRELMAPASYMTAB/PARCOM'DS$MEM".o"abcbcded9 97ehlhlmpswspABCBCDED9 9EHLHLMPSWSP"|: :	can't open output file. 	aca@A@,aSCCOM	CacC@	A: :,aSPARCOM	@ ,aSCCOM,aS @SYMTAB,aS"PARCOMac$A@ac&ac(A@		"	("; ;	@2	"%	@ac(A@37	A"	("@@	"%	@	A7	"aGQ	t"aG{9 9Qac*Q	@A@Q	@AE		!}\!!!!!\!\: :!'!#CREATE!$$PARCOM!*$PARCOM!($@SYMTAB!&$CCOM! $CCOM!"#ERROR !,#DSINIT!.                                                                   GETSYM!0#PUTBY0!2#ENTER 
 
"%($0&I"$ INSTR0: :CCOMRELMAPASYMTAB/PARCOM'DS$MEM	A"	("@	t",aGPARCOMQQK	A
; ;acQ	@QSac,a
@PARCOMA@#	@HC
acA@#ac,a
@PARCOM9 9A@#	@HC
acA@#+	unrecognized symbol in op field.1	acC@2ac 0"		9 9!$PARCOM!$PARCOM!#MAPDN !#PSEUD0!#MACHOP!#DOPSE0!#DOMACH!#ERRMSG! #GETSYM
 
"%&$0&_&$ LOCAT05 5CCOMRELMAPASYMTAB/PARCOM'DS$MEM	A"	("@	",ag@SYMTAB	@t"6 6,aKSYMTAB	AD,aGDS$MEMQacQ	@Q	@	@HC	t",aKOSYMTAB	@HC9 9,aKSYMTAB	#!	"#%	#			too many symbols --- assembly stopped.+		; ;,ag@SYMTAB	@	acC@,acB,ak@SYMTAB	@ac Q	@,aw@SYMTAB,aSSYMTAB6 6		,aSOSYMTAB		,aSSYMTAB,aK@SYMTAB	#(!_!_!P_!8 8$DS$MEM!$SYMTAB!$OSYMTAB!$SYMTAB!$@SYMTAB!#EQUAL !$#SDUP! #ERRMSG!"#SWT 
 
"%*$0&34( MACHOP9 9"5aciadcaddadianaanicallcccmacmc9 97cmpcmcnccnzcpcpecpicpoczdaadad9 97dcrdcxdieihexhltininrinxjcjm9 97jmpjncjnzjpjpejpojzldaldaxlhldlxi9 97movmvinoporaorgorioutpchlpoppushral9 97rarrcretrlcrmrncrnzrprperporrc9 97rstrzsbbsbisetshldsphlstastaxstcsub; ; suixchgxraxrixthl	A"	##"A?$9@AD	aGQac0: :Q	@Q	@	%A	$B"	%A		$@H#	#$"	%A	A&$QS( 	@ &.	&	!!S3!2#COMPA0
 
"%0(0&.$$ PSEUD0: :"byte"def"word	A"	ac Q	@a@	@HC	@ QS9 9	ac Q	@a@	@HC	AQS	ac Q	@a@	@HC		QS%	@  	")	"	!.!"#EQUAL 
 
"%*$0&&" PUSHB09 9CCOMRELMAPASYMTAB/PARCOM'DS$MEM	too many characters pushed back.,akPARCOM	@: :		,agPARCOMacC@QK,awPARCOM,aS#PARCOM		!
&! $PARCOM!$#PARCOM!#ERRMSG
 
"%&"0&"& PUTBY09 9CCOMRELMAPASYMTAB/PARCOM'DS$MEM	QK	B("	A"Qac,a
@CCOM	#ac< <A@A@#Q@A@A@A@$A@$		!!!$CCOM!#MAPFD !#PRWF$$
 
"%,&0&*& PUTREL9 9CCOMRELMAPASYMTAB/PARCOM'DS$MEM	QK	M=B"QK	M=@A#AacA@#	$: :QK	@HC	t",aKRELMAPA	$,aSRELMAP	$At",aORELMAP,aSRELMAP !		!!*!$RELMAP!#F$LS
 
"%,&0&$ PUTWO0& &	QK	B("	acA@"QK	B`"acA@"		!#PUTBY0
 
"%($0&$ SCANC09 9CCOMRELMAPASYMTAB/PARCOM'DS$MEMacA@"	"C		,aSPARCOM		! !
!$PARCOM!#INCHAR
 
"%$$0&#($ SCAND0: :CCOMRELMAPASYMTAB/PARCOM'DS$MEM"0123456789	@ ,aS.PARCOMacA@"9 9	ac a@A@"	#%ac"A@",aK.PARCOM	9@#@H,aS.PARCOM	A5 5,aS$PARCOM		!!
#!&$PARCOM!$.PARCOM!"#INDEX ! #INCHAR!$#PUSHB0
 
"%$$0&'0& SCANH09 9CCOMRELMAPASYMTAB/PARCOM'DS$MEM"0123456789abcdef	@ ,aS".PARCOM8 8ac$A@"ac&A@"	#	ac(a@A@#	$%ac*A@",aK".PARCOM	C<$@H: :,aS".PARCOM	A,aS,PARCOM		!'!.$PARCOM!$$.PARCOM!(#MAPDN !*#INDEX  !&#INCHAR!,#PUSHB0
 
"%&&0&3 & SCANID9 9CCOMRELMAPASYMTAB/PARCOM'DS$MEM	A"acA@#		#CA$#CD$$	acA@#A	$	A; ;	#t",aSPARCOM	("	@ t",aSPARCOM	#C		,aSPARCOM9 9&acA@#		,aSPARCOM*		!!3!0!9!:3!$PARCOM! $PARCOM!#ALPHA !#INCHAR!#PUSHB0
 
"%&&0&

& SDUP8 8CCOMRELMAPASYMTAB/PARCOM'DS$MEM	acQ	@	B"acA@"	#	acQ	@A@0 0,a
@DS$MEMA@#	#$	!!$DS$MEM!#LENGTH!#DSGET !#SCOPY 
 
"%*&0&$ SEEKE09 9CCOMRELMAPASYMTAB/PARCOM'DS$MEM	AQac,a
@CCOM	"acA@A@"Q@3 3A@A@A@#A@#		!!!$CCOM!#MAPFD !#PRWF$$
 
"%&$0&

 $ SEEK; ;CCOMRELMAPASYMTAB/PARCOM'DS$MEM	QK	MQAQac,a
@CCOM	"ac7 7A@A@"Q@A@Q@A@#A@#		! ! !$CCOM!#MAPFD !#PRWF$$
 
"%,$0&
$ XSEEK  	QK	"acA@"		!!#SEEK
 
"%($0&