n,(: :	Usage: imi <file> [ <hex start address> ].acA@acA@Q@A@	BCacC@9 9$	acQ@A@	"CacQ@2acA@Q@A@	BC	@ #A	A9 9	$acQ@A@$A@	#D$acA@"A@%A@&acA@"A@%A@&A@#ac A@%A@&: :	ac"A@"ac$!}n!!n!!f!'!#OPEN!#GETARG! #GCTOI !+ +#DSINIT!#ERROR !#CANT!"#LOAD!$#RELOC0!&#DUMP!(#CLOSE !*#SWT 
 
"%(0&

E$ LOAD9 9'DS$MEM		acA@"Q	@	%
	"@HC		badly formed code file. ac< <C@acQ	@Q	@acQ	@QS	@ #	(#@.	#
Qg4Q[	AD,aGDS$MEM9 9Q
acQ	@
Q	@/5		!E!$DS$MEM!#GETBY0!#DSGET !#ERROR !#GETWO0
 
"%0$0&l ( RELOC09 9'DS$MEM	QK		A			acA@"Q	@	%	"@HC	badly form; ;ed code file. acC@	acA@"Q	@	@ "	("@-	"Qg3	M=@A6 6	acA@#Q	@9	"M=@A$AacA@$	#A
	"Q[	$t$,aKDS$MEM	B 9 9,a[DS$MEMQ[		%$&%B`t&,aSDS$MEM	(&@%B(t&,aSDS$MEMN.4		!l0 0!!l!$DS$MEM!$DS$MEM!#GETBY0!#ERROR !#GETWO0!#F$LS
 
"%4(0&

*4$ DUMP9 9'DS$MEM":*n"*3,-16,0i *2,-16,0i*n"*/*n	ac.: :A@a@	@ "	("@		"
QgQ[	AD,aG0DS$MEMQac.A@a@A@"( (Q	@
	ac.A@a@*		!u*!2$DS$MEM!0#PRINT 
 
"%,$0&$ GETBY09 9	QGQacQ	@	"acA@A@"Q@A@A@A@#A@#		! !#MAPFD !#PRWF$$
 
"%,$0&$ GETWO0( (	acA@"Q	@acA@#Q	@	"B A	#QS		!#GETBY0
 
"%*$0&