7$$9 9LKSTUFRELMAPqSYMTAB'DS$MEM	Nothing to link.	acacA@"	%
acC@9 9           acacacA@"	%
!acA@"	@HCB#,aKLKSTUF	A
#Aac-ac; ; acac !~!7!$LKSTUF!#OPENS0!#SEGME0!#INITI0!#ERROR !#LINK !#NEXTS0! #CLEAN0!"#SWT 
 
"%$$0&*$ CHAIN0; ;LKSTUFRELMAPqSYMTAB'DS$MEM	QK	""%acQ	@A@"acA@",a
@LKSTUF: :acA@#,a
@LKSTUFacA@",a
@LKSTUFacQ	@,a
@LKSTUF	#"		!$ $*!$LKSTUF!#PUTREL!#XSEEK !#GETWO0!#PUTWO0
 
"%.$0&-8& CLEAN0; ;LKSTUFRELMAPqSYMTAB'DS$MEMacA@,a
@LKSTUF,awLKSTUF,aGLKSTUFQac6 6Q	@,a
@LKSTUF,awLKSTUF,aGLKSTUF	QacQ	@,a
@LKSTUFacA@: :,a
@LKSTUF,awLKSTUF,aKLKSTUF	M="acA@",a
@LKSTUF	A#	(#@4	#5 5	$"	@t#,aGRELMAP	QacQ	@,a
@LKSTUF59	A#	(#@I	#; ;,agpSYMTAB	@acA@,a
@LKSTUF	t#,aK SYMTAB	AD,aG"DS$MEM	Qac$Q	@9 9	$acA@$,a
@LKSTUF	t#,aG&OSYMTAB	QacQ	@,a
@LKSTUF	t#,aG(SYMTAB: :	QacQ	@,a
@LKSTUF	t#,aK SYMTAB	%	(%@	t%,aG"DS$MEMQQK	A
8 8ac*Q	@	$acA@$,a
@LKSTUFacA@,a
@LKSTUFJOac,7 7,a
@.LKSTUFac,,a
@LKSTUF		!!!!!!!-!*9 9$DS$MEM!($SYMTAB!.$OSYMTAB!0$SYMTAB!&$pSYMTAB!$$RELMAP!6$LKSTUF!$LKSTUF!. .$LKSTUF!,#LENGTH!2#CTOA!#SEEK!#PUTWO0! #XSEEK !"#PUTBY0!4#CLOSE 
 
"%(&0&&$ COMPA09 9	A"	("@	"@HADQKQg	A	@ #	           	"@HADQKQg 	A#		#!	#	!&
 
"%*$0&/$ CONNE08 8LKSTUFRELMAPqSYMTAB'DS$MEM	QK	BC
QKQSQK	"acA@": :,a
@LKSTUFacA@#,a
@LKSTUF	#BC	#"acA@",a
@LKSTUF- -acQ	@,a
@LKSTUF
		!$LKSTUF!#XSEEK !#GETWO0!#PUTWO0
 
"%*$0&=& COPYT0; ;LKSTUFRELMAPqSYMTAB'DS$MEM	acA@",a
@LKSTUF	%

acA@#,a
@LKSTUF9 9	$	#@H#         #A
acA@%,a
@LKSTUFacA@%,a
@LKSTUF	$		9 9	Unexpected EOF in text section. 'acC@(%!=!$LKSTUF!$LKSTUF!#GETBY0 !#GETWO0!#PUTBY0!#ERROR 
 
"%*&0&

$ CTOA 	QK	"	!
 
"%($0&Z"$ ENTER 9 9LKSTUFRELMAPqSYMTAB'DS$MEM	A"	("@		symbol redefined. 	",agpSYMTAB9 9	@t",aKSYMTAB	AD,aGDS$MEMQ
acQ	@Q	@
	@HCacC@%9 9	                                                                                                                    oo many symbols --- link stopped.+		,agpSYMTAB	@acC@,@,akpSYMTAB	@: :acQ	@,awpSYMTAB,aSSYMTABQK,aSOSYMTABQK,aSSYMTAB		!PZ!3 3$DS$MEM!$SYMTAB!$OSYMTAB! $SYMTAB!$pSYMTAB!#EQUAL !#SDUP!#ERROR 
 
"%0$0&,$ FIXCH0: :LKSTUFRELMAPqSYMTAB'DS$MEM	QK	%	"acA@",a
@LKSTUFacA@#; ;,a
@LKSTUF	#BCacA@",a
@LKSTUF	#,awLKSTUF,a[LKSTUF	"ac; ;A@",a
@LKSTUF		!,!$LKSTUF!$LKSTUF!#XSEEK !#GETWO0!#PUTWO0
 
"%($0&*& GETBY09 9	QGQacQ	@	"acA@A@"Q@A@A@A@#A@$	$AQK	%/ /		QS	% 	%	!'!'!#MAPFD !#PRWF$$
 
"%.&0&1$ GETNE0; ;!	acA@Q	@A@	%	)@acA@Q	@A@	"acQ	@9 9A@A@	#%	@	""	#@HAD@ QS	#"&	"	!v!1!1                                                                 !#GETARG!#GETLIN
 
"%($0&'& GETWO09 9LKSTUFRELMAPqSYMTAB'DS$MEM	,aKLKSTUF	@HCacA@"Q	@acA@#Q	@2 2acA@#Q	@acA@"Q	@	#B A	"QS	$	!#GETBY0!$LKSTUF
 
"%,&0&c& GETSY0; ;LKSTUFRELMAPqSYMTAB'DS$MEM	acA@",a
@LKSTUF	#acQ	@,a
@LKSTUFac5 5Q	@,a
@LKSTUF	A$""	"@H"	A$"	$@HADQGQ
acQ	@
: :,a
@LKSTUFQK
	QS
	($ 	$@HAD@ 	QSacA@%,a
@LKSTUF	%E9 9	%ADG	Can't happen: symbol section garbled. IacC@JH	#	!c!   !c!$LKSTUF!#GETBY0!#GETWO0!#ERROR 
 
"%2&0&2$ INITI0< <LKSTUFRELMAPqSYMTAB'DS$MEM"l.out	Can't create output file. 	@ ,aSpSYMTAB9 9acA@	@ ,aSLKSTUF,aSLKSTUF	A,aSLKSTUF	ac a@A@,aS"LKSTUF	C: :ac$C@'	@ ,aw"LKSTUF,aS&LKSTUFac(A@,a
@"LKSTUF		"	("@9	"9 9	%	@ac(A@,a
@"LKSTUF:>	Usage: lk -(6800 | 8080) {[-(i | l | n)] file}. G5 5ac*A@#	BC
ac$C@Hf	Usage: lk -(6800 | 8080) {[-(i | l | n)] file}. l7 7,aKLKSTUF	Aac$C@mk		!}!!!!!'!; ;$pSYMTAB!$$LKSTUF!"$LKSTUF! $LKSTUF!($LKSTUF!,$LKSTUF!&#CREATE!0#NEXTF0!#DSINIT !*#ERROR !.#PUTBY0
 
"%$$0&

8@, LINK7 7LKSTUFRELMAPqSYMTAB'DS$MEM,awLKSTUF,aGLKSTUF	QfacQ	@f,a
@LKSTUF: :,aKLKSTUF	@HC,awLKSTUF,aKLKSTUF	"A#	(#@	#%	@acA@$8 8,a
@LKSTUFacA@%,a
@LKSTUF	%""acA@",a
@LKSTUFacA@$: :,a
@LKSTUF	CacQ@A@&A@'	&%K	@ &acQ@	(C6T	t(: :,aK OSYMTAB	C,aG"SYMTABQfac$Q	@fA@'A@&	&t(,aS OSYMTAB	'QSf[: :J6>ac&A@)	*ac(A@*acA@$,a
@LKSTUF	CacQ@A@&; ;A@'	&%		'BCB+&CC+A	',aw*LKSTUF,a[LKSTUF	'acQ@9 9	(&%)	(Cac,Q@A@&A@',	t(,aK OSYMTAB	C,aG"SYMTAB8 8Qfac$Q	@fA@'A@&	&t(,aS OSYMTAB	'QSf;	Doubly defined: *s*n. P	t(9 9,aK.SYMTAB	AD,aG0DS$MEMQfac2A@C@QQ	@fO5(ac4A@'	(C9 9ac,Q@A@&A@'t	t(,aG OSYMTABQfQKf	%,aG"SYMTABQhac$7 7A@'Q	@hQ	@f	t(,aG"SYMTABQfac6A@'Q	@f	'QSf}lz	*5 5,aw*LKSTUF,a[LKSTUF,aSLKSTUFp,aw*LKSTUF,aGLKSTUF	Qfac8Q	@f: :,a
@*LKSTUF		!q!}8!!!8!6$DS$MEM!4$SYMTAB!&$OSYMTAB!(: :$SYMTAB!$LKSTUF!$LKSTUF!0$LKSTUF!$LKSTUF!,#COPYT0!$#LOOKUP!"#GETSY0!#GETBY06 6!#SEEK! #GETWO0!*#CHAIN0!.#UPDAT0!2#ENTER !8#PRINT !:#FIXCH0!<#CONNE0!>#XSEEK 
 
"%,0&.$ LOOKUP; ;LKSTUFRELMAPqSYMTAB'DS$MEM		"A#	(#@	#,agpSYMTAB	@t#,aKSYMTAB; ;	AD,aGDS$MEMQacQ	@Q	@	@HC	t#,aKOSYMTAB	@HC,aKSYMTAB	"9 9#	#"'*	"	!}.!$DS$MEM!$SYMTAB!$OSYMTAB!$SYMTAB! $pSYMTAB!#EQUAL 
 
"%*$0&e>$ NEXTF09 9LKSTUFRELMAPqSYMTAB'DS$MEM"-6800"-8080"-i" -l: :"$-n	ac(Q@	BC		"		ac*Q@a@	@HC	A,aS,LKSTUF7 7	ac*Q@a@	@HC		,aS,LKSTUF 	ac*Q@a@	@HC	@ 9 9,aS.LKSTUF$-	ac*Q@a@ 	@HC	A,aS.LKSTUF1:	ac*Q@a@$	@H: :	C		,aS.LKSTUF>GKL	ac0Q@A@,aS2LKSTUF	Cac47 7Q@X	@ ,aw2LKSTUF,aS6LKSTUF		"	!}!~!e!!e!81 1$LKSTUF!2$LKSTUF!4$LKSTUF!<$LKSTUF!0#EQUAL !.#GETNE0!6#OPEN!:#CANT
 
"%$0&R& NEXTS09 9LKSTUFRELMAPqSYMTAB'DS$MEM	Can't happen: no segment. ,awLKSTUF,aKLKSTUF	"< <acA@",a
@LKSTUFacA@#,a
@LKSTUF	BCacC@!acA@$,a
@LKSTUF; ;	$""acA@",a
@LKSTUFacA@#,a
@LKSTUF	BC>	#@HCacA@"6 6,a
@LKSTUF	",awLKSTUF,aSLKSTUF?C&O		!R!$LKSTUF! $LKSTUF!#GETBY0!#GETWO0!#SEEK!#ERROR 
 
"%&&0&4$ OPENS0; ;LKSTUFRELMAPqSYMTAB'DS$MEM	acA@",a
@LKSTUF	BCac,a
@LKSTUFac: :Q	@	BC		#			Format error in link segment. 	"%
-acC@,2 2		#	!~!!4!$LKSTUF!#GETBY0!#NEXTF0!#CLOSE !#ERROR 
 
"%($0&"& PUTBY0: :	QK	B("A"QacQ	@	#acA@A@#Q@A@A@A@$A@$		!! !#MAPFD !#PRWF$$
 
"%.&0&*& PUTREL9 9LKSTUFRELMAPqSYMTAB'DS$MEM	QK	M=B"QK	M=@A#AacA@#	$QK: :	@HC	t",aKRELMAPA	$,aSRELMAP	$At",aORELMAP,aSRELMAP!		 !!*!$RELMAP!#F$LS
 
"%,&0&0$ PUTWO0: :LKSTUFRELMAPqSYMTAB'DS$MEM	,aKLKSTUF	@HCQK	B("acA@"Q	@QK	B`8 8	"acA@"Q	@QK	B`"acA@"Q	@QK	B("	acA@"Q	@		! $LKSTUF!#PUTBY0
 
"%*$0&$ RELOC 9 9LKSTUFRELMAPqSYMTAB'DS$MEM	acQ	@,a
@LKSTUFacA@",a
@LKSTUFQK9 9	""acQ	@,a
@LKSTUFacA@",a
@LKSTUF		!$LKSTUF!#XSEEK !#GETWO0! #PUTWO0
 
"%*$0&

& SDUP< <LKSTUFRELMAPqSYMTAB'DS$MEM	acQ	@	B"acA@"	#	acQ	@A@,a
@DS$MEM( (A@#	#$	!!$DS$MEM!#LENGTH!#DSGET !#SCOPY 
 
"%*&0&

 $ SEEK: :	QK	MQAQacQ	@	"acA@A@"Q@A@Q@A@#A@#		!  !!#MAPFD !#PRWF$$
 
"%.$0&n$* SEGME0: :LKSTUFRELMAPqSYMTAB'DS$MEM	Can't happen: no segment. ,awLKSTUF,aKLKSTUF	"; ;acA@",a
@LKSTUFacA@#,a
@LKSTUF	BCacC@"	#%
+acA@$9 9,a
@LKSTUF	$""acA@",a
@LKSTUF*acQ@A@%A@&	$""%%L: :acQ@	'%T	t',aK OSYMTAB	C	A(	YSK;acA@#,a
@LKSTUF9 9	BCe	#@HC'f	@ (	!}n!n!"$OSYMTAB!$LKSTUF!$LKSTUF$ $!#GETBY0!#GETWO0!#GETSY0! #LOOKUP!#SEEK!#ERROR 
 
"%*0&v&* UPDAT0; ;LKSTUFRELMAPqSYMTAB'DS$MEM	acA@",a
@LKSTUF	%

acA@#,a
@LKSTUF9 9QK	$,awLKSTUF,aKLKSTUF	%	#@H#	#AacA@&,a
@LKSTUF		'9 9	'@H''	$A	('AA	(	A	AacA@'	&A
acA@A@%,awLKSTUF: :,aGLKSTUFQacA@%Q	@;	acA@A@%N	(%@$@H$(3			: :	Unexpected EOF in relocation section. ]ac C@^		!!!!v!#GETBY03 3!#GETWO0!$LKSTUF!$LKSTUF!$LKSTUF! #PUTREL!"#RELOC !#F$LS!$#ERROR 
 
"%0*0&$ UNRES0; ;LKSTUFRELMAPqSYMTAB'DS$MEM	@ "A#	(#@	#,agpSYMTAB	@t#,aKOSYMTAB+ +	C	A"	"	!!$OSYMTAB!$pSYMTAB
 
"%($0&$ XSEEK 5 5LKSTUFRELMAPqSYMTAB'DS$MEM	QK	"	acA@"Q	@		!!#SEEK
 
"%*$0&