l,(: :	Usage: mot <file> [ <start address> ].acA@acA@Q@A@	BCacC@"< <	acQ@A@	"CacQ@0acA@Q@A@	BC	@ #?	A$ac: :Q@A@$	#B-acA@"A@%A@&acA@"A@%A@&A@#ac A@%A@&A@#ac"A@"9 9ac$!}l!!l!f!'!#OPEN!#GETARG! #CTOI!#DSINIT!#ERROR ! !!#CANT!"#LOAD!$#RELOC0!&#DUMP!(#CLOSE !*#SWT 
 
"%(0&

E$ LOAD9 9'DS$MEM		acA@"Q	@	%
	"@HC		badly formed code file. ac< <C@acQ	@Q	@acQ	@QS	@ #	(#@.	#
Qg4Q[	AD,aGDS$MEM9 9Q
acQ	@
Q	@/5		!E!$DS$MEM!#GETBY0!#DSGET !#ERROR !#GETWO0
 
"%0$0&l ( RELOC09 9'DS$MEM	QK		A			acA@"Q	@	%	"@HC	badly form; ;ed code file. acC@	acA@"Q	@	@ "	("@-	"Qg3	M=@A6 6	acA@#Q	@9	"M=@A$AacA@$	#A
	"Q[	$t$,aKDS$MEM	B 9 9,a[DS$MEMQ[		%$&%B`t&,aSDS$MEM	(&@%B(t&,aSDS$MEMN.4		!l0 0!!l!$DS$MEM!$DS$MEM!#GETBY0!#ERROR !#GETWO0!#F$LS
 
"%4(0&

r( DUMP9 9'DS$MEM	acA@A@acA@	@ "acA@A@QK	"%	@#		#9 9	@ $#%acA@%A@$QK	"%B`&	acA@&A@$	%B(%acA@%A@$QK	"AD< <,aGDS$MEMQ
acQ	@
A@$	("@#@H#A	=	$A%acA@%A@$QK	$"	@ac9 9A@A@		!L.!ug!g!!g*nS1.   e*nS9*n. 
h !$DS$MEM!#PRINT !#SLEEP$!#OUTHEX
 
"%4(0&&&" OUTHEX; ;"0123456789ABCDEF	QK	A<ADaGQac"Q	@A@QK	ADaG. .Qac"Q	@A@QKQ[	B(QS		!u&!&!$#PUTCH 
 
"%*"0&$ GETBY09 9	QGQacQ	@	"acA@A@"Q@A@A@A@#A@#		! !#MAPFD !#PRWF$$
 
"%,$0&$ GETWO0( (	acA@"Q	@acA@#Q	@	"B A	#QS		!#GETBY0
 
"%*$0&