r(9 9FILCOMBUFCOMBLKCOMTARCOM"_detab.tar.files""x<f> v<f> t9 9<f> f<req str>"<#warning: couldn't create detabing c9 9ommand file*n"nshtrace ex*n"|-"~*s: couldn': :	t open*n"*s, *l bytes*n""*s linked to *s*n"49 9#couldn't make the directory '*s'*n"X*s> detab +8 | : :
cat >*s*n"r*s: couldn't create*n"
shtrace*n"9 9'use *s to remove tabs from new files*n	usage: ptar [-xvt] [-f; ; <file>]. 	ac:a@"Q@	Cac<C@Q	A
	A"!	@ "$Q: :	Aac>a@A@	#*Q	A	#C5ac@A@a@<9Q	Aac@; ;A@#a@nCQ	A
Q	ADQGQHacBQ	@Ha@|A'`]		,aSDFILCOM9 9_Q	ADQGQHacFQ	@HA@	@AY,aSDFILCOM	CQ	ADQGQH: :ac@A@a@~Q	@HacHwcM		,aSDFILCOM		A,aSJBUFCOM	A@D,aSLBLKCOM: :acNA@$	%,aKPTARCOM	AacNA@$	%&,aKPTARCOM	A); ;%	A%acR,a
@T|TARCOM	A@%A@QJ,aKVTARCOM	%<Q	AQ	A?< <C	ac@A@a@,a
@PTARCOMQ@JD;Q	AQ	ASWac@7 7A@a@",a
@PTARCOM,a
@XTARCOMX	@QJ	A"OacZ,a
@PTARCOM	&ac\; ;,a
@PTARCOMA@&acZ,a
@PTARCOM	&t&,aK^TARCOM		C	@ ,aS^TARCOM	&@H&Q9 9	Aac`,a
@PTARCOMA@
A@
	Cac@A@a@4,a
@PTARCOM	A"}; ;,aKPTARCOM	A
Q	Aac@A@#a@X,a
@PTARCOM,a
@PTARCOMac>,a
@PTARCOM9 9A@	'Cac@A@a@r,a
@PTARCOM	A"9	@ "D%	@QLQLA9 9QLJQLQ'JUacNA@$	"AQ	A]acbA@'Q@JQ@LaKV: :	"AacdA@'m!*Q	Aac@A@#a@acdA@#ac@A@a@a@9 9v,aKDFILCOM	%acd,a
@DFILCOMacH!q!u!v!}!!
9 9!!!!!	/!1\@N!j$TARCOM!\$TARCOM!`; ;$|TARCOM!b$TARCOM!d$TARCOM!X$BLKCOM!V$BUFCOM!P$FILCOM!Z#GETBUF!f#LENGTH!l#MKDIR$; ;!^#GCTOL !J#CREATE!F#PARSCL!H#ERROR !L#PRINT !N#EQUAL !R#OPEN!T#SWT !h#FIXNA0!n#PUTBUF !p#CLOSE 
 
"%v(0&H" PUTBUF; ;FILCOMBUFCOMBLKCOMTARCOM	QKQ_A'
GQ
		QKQ_Q
6 6	A@DQQAQQQ'
	@Qw,aKTARCOM,awBUFCOM: :,aSBUFCOM,akBUFCOM	@C	@ ,awBUFCOM,aSBUFCOMac,a
@BUFCOMQ	@9 9	A,aSBUFCOM3$		!
D!$TARCOM!$BUFCOM!$BUFCOM !$BUFCOM!#PUTLIN
 
"%0"0&\B$ GETBUF9 9FILCOMBUFCOMBLKCOMTARCOM"Error while reading block *l*n9 9		ac0Q@A@,a
@2FILCOM	"%	%ac4A@a@,a
@6BLKCOMac89 9		$"	#	,aK6BLKCOMA,aS6BLKCOM	A"	("@)	"%	@6 6	t"QK	B`A7",aS:~TARCOM	t"QK	B(A7",aS<TARCOM,aK:~TARCOM	A
< <,aK:~TARCOMA
,aS:~TARCOMCA7",aK<TARCOM	A
,aK<TARCOMA
,aS<TARCOM6 6O*.	@ #	!q!Z!Z!Z$!4#READF !>$~TARCOM!@ $TARCOM!:$BLKCOM!6$FILCOM!8#PRINT !<#SWT 
 
"%($0&@& CHECK0: :	acQ	@	"#	#@H#	#@HADQK	%	(#@#@HADQK	%9 9	%	@"@D"	"@H"%	"$#.,	@H$"@HADQK	t$QS&-	#@HAD! !		QS 		!/!0!9!_!#LENGTH
 
"%&0&$ FIXNA0: :	QK	CQK	B"	"@H"
	"%	@H#"@HADQK	t#QS9 9	acQ	@QSQK	C	uQK	C(		"	("@1QK	B"C9 9	"#"@HADQK	t#QS29acQ	@QS$.			QgSP	uQK	C9 9R	uQK	CX		"	("@aQK	B"C	"#"@HADQK	t#QSb9 9i		QSacQ	@QSM^acQ	@		!}!!!!.!/                                                                 \!#LENGTH!#CHECK0
 
"%*$0&