,0*: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM"9 9'-abcdefghlmpstvy -o<rs> -n<ign> -x<rs>"8=incl=/swt_9 9def.r.i"L	include "V/dev/stdout1"d.f	Usag: :e: rp [-abcdefghlmpstvy] [-o <outf>] [-x <ttable>] {<inf>}. acha@,a
@j^MISCOM	Cacl< <C@)acn,aKpcMISCOM	A acrA@acrA@acta@8acrA@acta@L3acv9 9	A@Q@A@	",aKxlMISCOM	A
,aKzMISCOM	AD,aG|]MISCOMQac~Q	@Q@9 9A@T	"%iQ	%nhmac~a@VQ@A@nacQ@	#: :	A$#	@t#QK	%	#@H#}	#B$	($@	#$C	t$QK	A
: :QGQQK	A
%acQ	@		CB&t$QK	
CBA	&A	%	A5aca@d9 9	A@Q@A@$wd	acQ@A@	'Cacac
Q@I	AQ	*s: can't op< <en*n. S	acQ@Q@	%facQ@A@	(CacA@C@TQ@Soac; ;A@(A@'acA@(Se	Missing 'end' statement.ac,aKMISCOM	@HCacC@9 9,aKaMISCOM	AacA@'acacA@'ac !q!}!,!!6 6,!,!!
,!'!-!
.!/,!	r,!&$MISCOM!
: :$]MISCOM!x$^MISCOM!*$aMISCOM!~$cMISCOM!$lMISCOM!$MISCOM!#GETARG!#OPEN!#CREATE< <!#GFNARG!#LENGTH!#MAPDN !v#PARSCL!z#ERROR !|#INITI0!#PUTBA0!#PUTBC0!#CTOC!#SCOPY 5 5!#CLEAN0!#CANT!#PRINT ! #PROCG0!"#CLOSE !$#ENDPR0!(#SYNERR!,#LISTL0!.#SWT 
 
"%0*0&H$$ PROCG0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	5 5	A,aSINCOM QK,awINCOM ,aS~INCOM 	@ ,aSyINCOM QK,aSOUTFIL9 9,aSOUTFILac	Unmatched }.,aKILEXCOM	CacC@ac 	PARSER: :
 FAILURE -- HELP!!. (ac A@"	"@HCacC@)=,aKILEXCOM	BC		!}H9 9!$ILEXCOM!$yINCOM !$INCOM !$~INCOM !$OUTFIL!$OUTFIL!#GETSYM! #SYNERR!" #RATFO0
 
"%*$0&/B$ LISTL0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM": :C ---- Long Name Map ----*n",C *30s *s*n	ac8Q	@9 9a@	@ "ac:,a
@<JLEXCOM	Q@Q@A@"	%Q	%	Q	AD7 7,aG>DS$MEMQPac8Q	@a@,Q@Q	@P			!/!/!>$JLEXCOM!@ $DS$MEM!<#SCTABL!:#PRINT 
 
"%v$0&