& SIMPL0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	9 9	@ "#acA@"A@#acA@A@A@A@"	$acA@$		QS		!! !!#MAKET0!#COLLF0!#EXPRT0
 
"%*&0&R$( CHECK0< <)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOMac5 5A@"	"acA@"	t",aKDS$MEM	%			t",aKDS$MEM	#$	t$7 7,aKDS$MEM	$	$A
	%acA@	&#t&,aSDS$MEM		,aSDS$MEM< <,aSDS$MEM	@ ,aSDS$MEM	&#t",aSDS$MEMacA@	&@ t&,aSDS$MEM		,aSDS$MEM: :,aSDS$MEM	@ ,aSDS$MEM	&t%,aSDS$MEM	%	acA@#A@%		!R!(!)9 9R!R!$DS$MEM!$DS$MEM! $DS$MEM!$DS$MEM!#EXPRS0!#DSGET !#EXPRT0!" #COLLF0
 
"%((0&z& COLLF0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	9 9	@ ",aKILEXCOM	Cac,aKILEXCOM	#	"A	missing right pa; ;renthesis.	"A

acC@#	("    *	"@H"A+(	#%6	$L: :*),;>?ABCDEFGHIJKLM	#$L< <	#$L
N0acQ	@QSQK	AQKQSoac: :	"A1		!z!
!%z!zz!gz!$ILEXCOM!#SAVES0!#GETSYM !#SYNERR
 
"%,&0&$ GENER0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	4 4acA@acA@"	"	acA@"Q	@		!o                                 #EXPRS0!#ENTEU0!#GENIF 
 
"%($0&|>$ GENIF : :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM"< <IF(")GOTO 		acQ	@Qw,aKDS$MEM	"Qw,aG DS$MEMQ9 9ac"Q	@Q	@Qw,aG$DS$MEM Qac"Q	@Q	@ac&Q	@ac(Q	@ac*A@	#; ;Qw,aG DS$MEMQac"Q	@A@#Qw,aG$DS$MEMQac"Q	@A@#ac,Q	@ac.9 9A@#A@ac&Q	@'
	"%\(	%_ac0A@ac2a@A@ac4Q	@ac26 6a@A@ac6Q	@ac8A@W		!|!|!h!p|!&#GENIF !": :$DS$MEM!$$DS$MEM!($DS$MEM!.#LABGEN! #PROPA0!*#DSFREE!,#NEGAT0!0#OUTGO !2#OUTNUM!4 #OUTTAB!6#OUTSTR!8#GENEX0!:#OUTGO0!<#OUTDON
 
"%,$0&.l
* GENEX0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM"9 9.NOT.".OR.".AND."".EQ."(.NE."..GE: :."4.LE.":.GT."@.LT.		acFQ	@Qw,aKHDS$MEM	"9 9	|| appears within argument of & or |. acJC@		Qw,aSHDS$MEM	&& a: :                                                                                                                pears within argument of & or |. )acJC@*		Qw,aSHDS$MEM(Qw,aKLDS$MEM	#9 9acNA@#Q@A@$	%W	$CacPQ@	%acRQ@A@%A@LZacT: :Q@A@LVacVQ	@		acXA@A@acTa@A@Qw,aGZDS$MEMQLac\: :Q	@LacXA@A@acVQ	@		
	"&L
) u	"%(G9 9!FacXA@A@Qw,aGZDS$MEMQLac\Q	@LQw,aKHDS$MEM	'acTa@9 97A@acTa@A@DacTa@"A@KacTa@(A@RacTa@.A@YacTa@49 9A@`acTa@:A@gacTa@@A@n=	in gen_expr: can't happen.v	'%E9 9	%>		(LLZhaoSac^C@wuQw,aG`DS$MEM	QLac\Q	@L9 9acXA@A@acVQ	@		!.!.!&!(!).!|.!g!	; ;h!!     .!f#GENEX0!R$DS$MEM!d$DS$MEM!j$DS$MEM!V$DS$MEM!X#RESTO0!Z#LENGTH+ +!P#PROPA0!T#SYNERR!\#OUTLIT!^#OUTSTR!`#DSFREE!b#OUTCH !h#FATAL0
 
"%x*0&
,(& PROPA0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	: :Qw,aKDS$MEM	%		Qw,aKDS$MEM	"t",aKDS$MEM	%9 9	t",aKDS$MEM	#acA@#Q	@acA@"acA@#	t",aKDS$MEM	$ac9 97Q	@A@"A@acQ	@acQ	@A@"A@acQ	@9acQ	@A@"A@acQ	@: :8FacQ	@A@"A@acQ	@SacQ	@A@"A@`acQ	@A@"A@iacQ	@9 92A@"A@racQ	@A@"A@{acQ	@A@"A@	acQ	@A@"A@
,	$%9 9T	%G	%L
:a|sj-)		!&,!|,!9 9g!h!i!j!
k!l!	m!n!o!p,!$DS$MEM!$DS$MEM!  #COPYT0!"#DSFREE!$#REPLA0!&#NEGAT0
 
"%*&0&" REPLA0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	4 4acQ	@Q	@acQ	@QKQw,aSDS$MEM		!$DS$MEM!#COPYT0!#DSFREE
 
"%,"0&&" NEGAT0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	; ;Qw,aGDS$MEMQacQ	@A@A@A@QSQw,aGDS$MEMQacQ	@A@- -	A@A@QS		!&!o&!$DS$MEM!$DS$MEM!#MAKET0
 
"%("0&"" COPYT0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	5 5Qw,aKDS$MEMQw,aSDS$MEMQw,aKDS$MEMQw,aSDS$MEMQw8 8,aKDS$MEMQw,aSDS$MEMQw,aKDS$MEMQw,aSDS$MEM		!$DS$MEM! $DS$MEM!$DS$MEM!$DS$MEM
 
"%("0&(& ENTEU0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	; ;QK	CacA@"	"@ #acA@#	#acA@"	"acA@"A@#Q	@. .A@	$acA@$		!(!o(!#MAKET0!#EXPRS0!#EXPRT0
 
"%*&0&" EXPRT0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	6 6	
expr stack overflow.		,agCODEG0	@acC@,akCODEG0	@QK- -,awCODEG0,aSCODEG0		!!$CODEG0!$CODEG0!#FATAL0
 
"%&"0&$$ EXPRS0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	: :	expr stack underflow. ,aKCODEG0	A	acC@,awCODEG0,aKCODEG0QS. .,aKCODEG0	@H,aSCODEG0QK	"	!$CODEG0!$CODEG0!#FATAL0
 
"%($0&, $ SAVES0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	; ;ac,a
@LEXCOM	"acA@"	#@ t#,aSDS$MEM,aKILEXCOM,aSDS$MEM	#@D"ac: :,a
@LEXCOMA@,a
@DS$MEMA@"QK	A
	#Qw,aSDS$MEM$	#	!,5 5!,!$LEXCOM!$ILEXCOM!$DS$MEM!$DS$MEM!#LENGTH!#DSGET !#SCOPY 
 
"%($0&-$ RESTO0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	< <QK	A		"Qw,aGDS$MEMQ
acQ	@
A@Q	@A@Qw,aKDS$MEM6 6QSQK	#,aKDS$MEM	QSacA@#		"	"	!~!-!-!   $DS$MEM!$DS$MEM!$DS$MEM!#SCOPY !#DSFREE
 
"%0$0&$ MAKET0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	< <acA@	"QK	t",aSDS$MEMQK,aSDS$MEMQK,aSDS$MEMQK	,aSDS$MEM- -	"#	!!$DS$MEM!$DS$MEM!$DS$MEM!$DS$MEM!#DSGET 
 
"%0$0&