f"" REMOV0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	9 9                                                                         dentifier must follow 'undefine'.acQ@	%
acC@				Right paren must f9 9ollow identifier in 'undefine'. acQ@Q@acQ@L	%
EacC@		Dac; ;Q@Q@H,a
@JLEXCOM	A
QH	CSX		YacQ@JacQ@,a
@JLEXCOM: :		!f!)f!f!$JLEXCOM!#SKIPW0!#LOOKUP!#SYNERR!#DELET0!#DSFREE ! #DELETE
 
"%6"0&"& INVOK0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	: :	@ "uQK	AacQ@A@"	A#uQK	$	($@	t$,aKDS$MEM	A
9 9	%	t#QS	(##	($@t$,aKDS$MEM	$"	@ADQK	AD,aGDS$MEM9 9Q4	t#QGQ6		#%acQ	@4Q	@6A@%	##+$	                                                                                                                  esult of define invocation too lo9 9ng. G		$#	@acC@Hc	@ t#	QSacQ@	A$	($@n	$$"	@9 9	t$QGQ4acQ	@4os		!!!!     !!$DS$MEM !#CTOC!#GETAC0!#SYNERR!#PUTBC0! #DSFREE
 
"%^&0&*& ENTER0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	: :only identifiers may be defined.acQ@	"%
acC@		acQ@Q@ac9 9Q@L	"CacA@#A@$	C		4acQ@L	"+	@ $#;	define< < identifer must be followed by a comma. ?	"%
[acC@@	#A
acA@#a		Zac9 9A@#	%C		n	acQ@Q@H,a
@JLEXCOM	@HCQH	Czac Q@J: :		QH	$QI	%QJac"Q@Q@H,a
@JLEXCOM		!}!!(!,: :!!$$JLEXCOM!#SKIPW0!#GETFO0!"#LOOKUP! #GETDE0!#SYNERR!#DELET0!#RMTABL !&#DSFREE!(#ENTER 
 
"%:&0&&& DGETS0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	: :,awyINCOM ,aKINCOM 	A
	",akyINCOM 
acA@"	"%< <	%	@	"%	%	@!	"QS	A#,awyINCOM ,aKINCOM 9 9	A
	",akyINCOM 0,acA@"1	"%;;	%:	@<	"%9 9DD	%C	@>E	"%MM	%L	@GN	"%UP	%XT8 8W	token too long. Y		$#	@acC@ZXd	"t#QS	(#@,awyINCOM 9 9,aKINCOM 	A
	",akyINCOM 66vacA@"6j	@ t#	QSacA@"			9 9	$		"QS	@ u
QS	"$	!
!$!0!9!A!H!Z!_1 1!a!z!	!$INCOM !$yINCOM ! #REFIL0!"#SYNERR!$#PUTBA0
 
"%*&0&"$ GETFO09 9		acA@QS	@ QS	define formal parameters must be identifiers. 
acQ@
	"%; ;*acC@acQ	@		#	)	commas must separate define formal parameters.5acQ@
; ;Q@
Qk	@QKQacQ@
Q@Q	@acQ@
	"%j	%miacC@6ac: :Q	@		#	l	"C
		#	!}!~!!)!,!!#SKIPW0! #MKTABL!#SYNERR!#RMTABL!#DELET0! #ENTER 
 
"%v$0&$ SKIPW0* *	acQ	@	"%		%	#	!
! !#DGETS0
 
"%($0&B(* GETDE0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	; ;	@ "	#A$@ 	QacQ@`	%	#C	("@	#C	"@H"A: :	#C		#!%	#C		#,(	#C		#/3	#C		#:; ;6	Missing right paren or EOF in define text.>acC@? acQ@`Q@QK	A
=ac: :	Q@Q@\Q	@	@HCb			Q`Q]Qa	@ Qbm	%%}>	&L	": :0	%%Yx	
definition too long.acQ@`	'$Cac: :C@X acQ@`A@Q@A@$	'$$
%QK	A
acQ	@7acQ@: :	(	!B!B! !!!"!'B!B!B!#DGETS0!#LOOKUP% %! #LENGTH!&#SDUPL !#SYNERR!#DELET0!"#SCOPY !$#RMTABL
 
"%R*0&Q$ GETAC0< <	acQ@	"%		%	@ 	QSacQ@			AQSQk	@QK9 9	%	@acQ@	"QK	@H#acQ@	t#QS	"BC			Too many act: :ual parameters specified. 5acC@6		QS		! ! !(Q!#DGETS0!#COLLE0 !#SDUPL !#PUTBC0!#SYNERR
 
"%$0&8 * COLLE0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	9 9	A"	#@ $,awyINCOM ,aKINCOM 	A
	%,akyINCOM acA@%         %: :	&	#C	($@	#C	$@H$A(#	#C		#*.	#: :	C		#51	#C		#8<	#C		#C?	#CF	$A	J: :)	unbalanced paren or EOF in define actual parameter list.OacC@PN	&%uO	9 9	'L+z{|9 }GM	                                                                                                    efine actual parameter too long. 	"@H: :	AD%QS	("@	$"	@acC@p &	"@HAD@ QS	%C		(	1		: :	(	!~!8! !!!"!'!,8!8!$INCOM !$yINCOM ! #REFIL0!#SYNERR
 
"%.*0&9& DELET0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	< <	A"#	(#@	#@HAD	QGQQK	A
	%,aKjMISCOM	A
	"@H$ac9 9Q	@	t$QS	"@H$#@HADQK	t$QS#	("@         "@HAD@ QS		!_ 9!$jMISCOM!#MAPDN 
 
"%.&0&