eD.0 GETSYM: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM"9 90123456789abcdef"".AND."(.OR."..EQ."4.L: :E.":.LT."@.GE."F.GT."L.NE."R.NOT.9 9	@ ,aSXHLEXCOM,aSZLEXCOM,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM 
: :ac`A@"	A#	"$	@ %,akXHLEXCOM	@",awXHLEXCOM,aSbLEXCOM: :,akXHLEXCOM	@",awXHLEXCOM,aSbLEXCOM	A%%	"%66	%5	@7: :	"%??	%>	@@	"%G	%KK	%J	@&L	"%S: :0R,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM ]Yac`A@"^1< <SacdA@"	@ ,awXHLEXCOM,aSZLEXCOM,aKfjMISCOM	A
	@ %ach,a
@ZLEXCOMA@9 9p	@ ,aSjLLEXCOM,aKlPRCCOM	&	&@H&	&A	t&,aGnPRCCOMQQK	A
: :acp,a
@ZLEXCOMQ@Q	@	@HCacr,a
@ZLEXCOMA@,a
@jLLEXCOMA@acr: :,a
@tDS$MEMQ@,a
@ZLEXCOMA@,aSXHLEXCOM			,aSvILEXCOM,aKxfPRCCOM	A
9 9acp,a
@ZLEXCOMQ@,a
@xfPRCCOM	@HC7Q,aSzePRCCOM		
,aSvILEXCOM36 6Bacp,a
@ZLEXCOMQ@,a
@|JLEXCOM	A,aKXHLEXCOM	%	@%%^X9 9,aK~LEXCOM	C,aKXHLEXCOM	Cb]h,aK_MISCOM	Agacr,a
@ZLEXCOM9 9A@,a
@jLLEXCOMA@acl			,aSvILEXCOMJTQ	'Q,aSvILEXCOM: :|acr,a
@ZLEXCOMA@,a
@jLLEXCOMA@acr,a
@tDS$MEMQ@,a
@ZLEXCOMA@: :,aSXHLEXCOM			,aSvILEXCOM
acQ@	in getsym/id:  can't happen (bad symtype).%6 6	'L acC@&	"%KK	%J	@,awXHLEXCOM,aSZLEXCOM: :,akXHLEXCOM	@,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM FFZac`A@"F8 8L	Radix must be between 2 and 16. e	@ ,awXHLEXCOM,aSZLEXCOM	"C	A&ac; ;,a
@ZLEXCOMA@&		(CA)(@HCD)Aac
C@f		(	@Q,aw\yINCOM ,aK^INCOM < <	A
	",ak\yINCOM #ac`A@"$	"%..	%-	@&/ac; ;A@"	*	aca@A@*	@H&3	&A	$(CEG	(MQ;	AQ	&MQ: :QFacQ@,a
@ZLEXCOMA@,aSXHLEXCOM~acdA@"		,aSvILEXCOM; ;		,aSvILEXCOM	"+,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM vrac`A@"; ;w	"+C	Quoted literal too long.,akXHLEXCOM	@	,agXHLEXCOM	@ac
; ;C@	Unmatched quote.	",awXHLEXCOM,aSbLEXCOM	                                                                   
ac
C@+m9 90	@ ,awXHLEXCOM,aSZLEXCOM,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM @; ;<ac`A@"A		#	"%Mk	%Pk	"%UU	%T	@acA@"9 9gVacdA@"\,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM kgac`: :A@"l	"C		,aSvILEXCOMat	"C		,aSvILEXCOM|acdA@"6 6	acra@"A@,a
@ZLEXCOMA@,aSXHLEXCOM		,aSvILEXCOMx,aw\yINCOM 9 9,aK^INCOM 	A
	",ak\yINCOM ac`A@"	"C		,aSvILEXCOM8 8'	"C		,aSvILEXCOM/acdA@"acra@(A@,a
@ZLEXCOMA@: :,aSXHLEXCOM		,aSvILEXCOM3+,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM 5 5QMac`A@"R	"Cacra@.A@,a
@ZLEXCOMA@,aSXHLEXCOM		5 5,aSvILEXCOMGZacdA@"		,aSZLEXCOM	@ ,aSLEXCOM	A,aSXHLEXCOM		9 9,aSvILEXCOMj,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM ac`A@"; ;	"C		,aSvILEXCOM	acra@4A@,a
@ZLEXCOMA@,aSXHLEXCOM{acd7 7A@"acra@:A@,a
@ZLEXCOMA@,aSXHLEXCOM		,aSvILEXCOM,aw\yINCOM 9 9,aK^INCOM 	A
	",ak\yINCOM <8ac`A@"=	"C		,aSvILEXCOM8 8	acra@@A@,a
@ZLEXCOMA@,aSXHLEXCOM2E		 ,aSvILEXCOM	acra@FA@5 5,a
@ZLEXCOMA@,aSXHLEXCOMacdA@"U,aw\yINCOM ,aK^INCOM 	A
	"< <,ak\yINCOM soac`A@"t	"C		!,aSvILEXCOM	acra@LA@,a
@ZLEXCOM: :A@,aSXHLEXCOMi|		",aSvILEXCOM	acra@RA@,a
@ZLEXCOMA@,aSXHLEXCOM: :acdA@"	",aSvILEXCOM,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM -): :ac`A@".	"%7,aKvILEXCOM,aSZLEXCOM	@ ,aSLEXCOM	A,aSXHLEXCOMacd: :A@" 6,aKvILEXCOM	,		#,aSvILEXCOM		$,aSvILEXCOMM		%,aSvILEXCOM9 9Q		&,aSvILEXCOMU		',aSvILEXCOMY		(,aSvILEXCOM]I	,-LZ6 6hijRJkNnV	,%)v^paE	",aSvILEXCOM,aSZLEXCOM	@ : :,aSLEXCOM	A,aSXHLEXCOMacdA@v	$*.L^h!bh!!: :8w!!FFFFFFFFFF$|H3%): :8*EF!GI: :6Jejg9 9	",aSvILEXCOM,aSZLEXCOM	@ ,aSLEXCOM	A,aSXHLEXCOMEt		H	"+C; ;,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM wwac`A@"wz	"/7 7,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM ac`A@"	",C9 9,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM *&ac`A@"+	"                                                                   ! ; ;	"%+8	%           ;	%>,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM 9 9HDac`A@"I	"                                                                   ?>	/%,W?	%ZR	"%+^w^	#: :	LI_!!e!e!e!        
!+ !*!!"!,#!$9 9!&!'e!0e!9!=!Ae!He!Z!)^!_!ae!9 9r!z!|e!h!i!j! k!l!m!!n!"o!p!	!9 9!
	!                                 #!$!%!&!'!(! !!e!$LEXCOM!$LEXCOM9 9!B$LEXCOM!,$LEXCOM!$LLEXCOM!$HLEXCOM!$$ILEXCOM!*$JLEXCOM!$INCOM !
$yINCOM : :!"$DS$MEM!$PRCCOM!$PRCCOM!($ePRCCOM!&$fPRCCOM!.$_MISCOM!$jMISCOM!<#INDEX !69 9#CTOI!>#LTOC!:#MAPDN !#LOOKUP! #SCOPY !#REFIL0!#PUTBA0!#MAPSTR!0#ENTET0!2#INVOK0 !4#FATAL0!8#SYNERR!@#CONVE0
 
"%800&.?>* CONVE0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	8 8QK	",aKHLEXCOM	@HCac,a
@LEXCOM	#acA@#,a
@LEXCOMA@; ;,aSHLEXCOM		,aSILEXCOM		Only one character allowed in a character constant. ac9 9C@ac,a
@LEXCOM	A@Q@A@	@ $A%	(%@K	Packed string constant too6 6 long.N	t%QK	A
	($@	$$	@acC@Och	t%QK	C		t$: :,aSLEXCOM	($@t	t%QK	t$,aSLEXCOMLn		t$,aSLEXCOM	@ ,aS LEXCOM	$6 6	B,aSHLEXCOM		,aSILEXCOM<	EOS-terminated string not allowed in this context.; ;,aK"OBUFC0	A&,aK$OBUFC0	A&AacC@		4ac&Q@,aKHLEXCOM	B'ac(9 9Q@A@'	A%	(%@J	t%,aGLEXCOMQLQKL	A
ac*Q@A@%Q	@LKU; ;ac*Q@A@%A@ac,acQ@A@,a
@LEXCOMA@,aSHLEXCOM		,aSILEXCOM9 9	Varying string not allowed in this context. y,aK"OBUFC0	A&,aK$OBUFC0	A&Aac: :C@z		ac&Q@,aKHLEXCOM	BM=	B'	ac(Q@A@'		
,awHLEXCOM,aSLEXCOM; ;	ac.Q@A@,a
@HLEXCOM	A%	%@D%?	%,agHLEXCOM	@t%,aGLEXCOMQL: :,aGLEXCOM	QNacQ	@N	'acQ	@L	B ''%M=	@D(ac.Q@A@(A@'@Fac,9 9	acQ@A@,a
@LEXCOMA@,aSHLEXCOM		,aSILEXCOMx	"%	): :	L(=	y
	")L=: :
 "y#	Unrecognizable string format indicator. %acC@&|		!!9 9!	?!
 !.!@!C!G!H!O!o?!!!     ?!,; ;$LEXCOM!"$LEXCOM!.$LEXCOM!$HLEXCOM!&$ILEXCOM!0$OBUFC0!2$OBUFC0!$#ITOC!*#SCOPY * *! #TLIT!(#SYNERR!4#VARGEN!6#GENIN0!8#GENCH0!:#GENDA0!<#GENDB0
 
"%z*0&="" REFIL0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	6 6,aKINCOM 	%		QS	@ ,aSINCOM 		,aSyINCOM 		,awINCOM : :,aG~INCOM Qac,a
@INCOM Q	@	%,awINCOM ,akyINCOM #: :,awINCOM ,aG~INCOM 	QacQ	@,aKINCOM 	@H,aSINCOM $,aKINCOM 7 7QS		,aSyINCOM 		!=!=!!     =!$INCOM !$yINCOM !   $yINCOM !$INCOM !$~INCOM !#GETLIN! #CLOSE 
 
"%("0&&" PUTBA0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	9 9,aKyINCOM 	@H,aSyINCOM 	@HCQK,awyINCOM ,aSINCOM 	too many c. .haracters pushed back.acC@                           		!$INCOM !$yINCOM !#FATAL0
 
"%&"0&$ PUTBC0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	; ;acQ	@	@H"	"@H"	"A	t"QGQacQ	@		!#LENGTH!#PUTBA0
 
"%*$0&$ PUTBB0/ /	acQ	@Q@A@	"@ t"	QSacQ@		!!#ITOC!#PUTBC0
 
"%($0&