u
( SYNERR: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM"9 9*5i" (*s): "
<NEWLINE>"&<EOF>",*s*s.*n9 9"4*s'*s' *s.*n"B*s'*s'*n*10x*s.*n"TRatfor e; ;	rror at 	A"#	(#@	#,agfINCOM 	@t"QGQ	t#,aGhyINCOM ; ;Q		"$acjQ	@A@$a@Q	@	""
	t"QGQ		"$acjQ	@A@$a@: :,a
@lKMISCOM	""acnQ	@A@Q@A@	%acp,a
@rMISCOM	&A,aKtILEXCOM	8 8	Cacv,a
@rMISCOMacp,a
@rMISCOM	&P,aKtILEXCOM	Cacxa@9 9,a
@rMISCOMA@	&_,aKtILEXCOM	BCacxa@&,a
@rMISCOMA@	&9 9n,awzHLEXCOM,aK|LEXCOM	Aacx,a
@|LEXCOM,a
@rMISCOMA@	&~xiZK	&< <	Aac~A@a@,Q@Q@
	"&%%	@ac~A@a@4Q@,a
@rMISCOMQ@: :ac~A@a@BQ@,a
@rMISCOMQ@(acA@acA@aca@TA@	A9 9	#	(#@E	#,agfINCOM 	@t#,aGhyINCOM QacQ	@A@acA@A@9 9FKacQ@A@acA@	@ ,aSrMISCOM,aK
^MISCOM	A
acA@	o		!7 7qu!	!u!Iu!!
! u!.u!Hu!u!9 9$LEXCOM!$HLEXCOM!~$ILEXCOM!r$yINCOM !p$INCOM !v$KMISCOM!|$MISCOM!$^MISCOM!t9 9#ENCODE!#CTOC!x#PTOC!z#LENGTH!#GETLO0!#PRINT !
#OUTDON!#OUTTAB!#OUTSTR!#OUTNUM !#OUTCH !#SETERR
 
"%0(0&
" FATAL05 5	
program terminated. acQ	@acacC@		!#SYNERR!#CLEAN0!#ERROR 
 
"%&"0&$ SDUPL : :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	5 5acQ	@	B"acA@"	#	acQ	@A@,a
@DS$MEMA@#	#	!! $DS$MEM!#LENGTH!#DSGET !#SCOPY 
 
"%($0&F&" ENTET0< <)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOMac9 9,a
@LEXCOMQ@	@HC		QacQ@Qac,a
@LEXCOMQ@,a
@JLEXCOM: :	acQ@A@,a
@KLEXCOM	acQ@A@,a
@LEXCOMA@,aSHLEXCOM	id6 6entifier cannot be made unique. /ac C@0.		!!!F!$LEXCOM!"2 2$HLEXCOM!$JLEXCOM!$KLEXCOM!#MAKEU0! #SCOPY !#SDUPL !#ENTER !$#SYNERR
 
"%n"0&t
& MAKEU0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	: :	A"	("@	"%	@@HADQK	A
	%	%	@QS	"9 9	@HADQKQS	("@	"%	@@HAD	QS#'	@ uQS		u	QSacQ	@9 9A@#,a
@KLEXCOM	@HC		"	"@H"D	"%MK	@HADQK	%UUE: :	%EE	BQS	("\	("@]	"%L	@@HAD	QS^b	"@HC7	@ $	A5 5	A$	!t!!t! t!0!At!Z!a!zt! $KLEXCOM!#LOOKUP
 
"%,&0&

$ LABGEN: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	! !,aKHMISCOM	"Q[,aSHMISCOM	"	!$HMISCOM
 
"%($0&9" VARGEN: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	; ;ac,a
@LEXCOMQ	@	@HCacQ	@A@,a
@KLEXCOMacQ	@,a
@LEXCOMA@9 9		in vargen:  cannot generate new variable. acC@	@ QS		!9!* *H9!$LEXCOM!$KLEXCOM!#MAKEU0!#ENTER !#CTOC!#SYNERR
 
"%&"0&" SAVEM0< <)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOMac5 5,a
@LEXCOMA@,a
@MISCOMA@ac,a
@KMISCOM		!!$LEXCOM! $MISCOM!$KMISCOM!#SCOPY !#GETLO0
 
"%""0&" GETLO0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	: :,aKLLEXCOM	Aac,a
@LEXCOMA@Q	@A@ac,a
@LLEXCOMA@Q	@# #A@		!!$LEXCOM!$LLEXCOM!#SCOPY 
 
"%&"0&$ GENCH0& &	acQ	@	"acQ	@Q	@A@"		!#TLIT!#GENDB0
 
"%.$0&a0" GENDB0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM"; ;DATA ")/"DATA 	,aK sMISCOM	A
ac"A@ac$a@A@; ;9ac$Q	@A@ac&A@A@ac(Q	@A@ac$a@A@ac(Q	@A@ac&A@A@ac*< <A@QK	@HC%ac"A@ac$a@A@ac$Q	@A@ac&A@A@<ac&; ;A@A@S	ac(Q	@A@7		!a!(a!,!/a!$$sMISCOM!&#OUTTAB !(#OUTSTR!*#OUTCH !,#OUTNUM!.#OUTDON
 
"%,"0&" GENDA08 8)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM: :,aKsMISCOM	AacA@A@acA@		!!/!$sMISCOM!#OUTCH  !#OUTDON
 
"%""0&,(" GENIN0; ;"	INTEGER 	acA@aca@A@acQ	@A@QK	AacA@A@; ;ac Q	@A@acA@A@ac"A@		!,!(!),!#OUTTAB! #OUTSTR !"#OUTCH !$#OUTNUM!&#OUTDON
 
"%("0&

$ TLIT: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	5 5QK	A,aK(MISCOM	"	QK	A	%	@ "	Qw   ,aK(MISCOM	"	!!$(MISCOM!$(MISCOM
 
"%($0&