C& OUTTAB: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	: :Qw,aKOBUFC0	%	""%	B"QK	C9"AD	,aSOBUFC0	QK; ;	C,aKJMISCOM	%	@# 		##	A$	($@(	$$#	@"@D"QK: :	C9"AD	,aS~OBUFC0,aSOBUFC0)-	"Qw,aSOBUFC0		!C!C) )!C! C!$~OBUFC0!$OBUFC0!$OBUFC0!$JMISCOM
 
"%*&0&? & OUTCH : :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	: :Qw,aKOBUFC0	%	B,aSOBUFC0QK	C9,a[OBUFC0	ADQK,aSOBUFC05 5	acQ	@QK	C9B"A$	t",aSOBUFC0	"B"A$%	.  QK	C9AD	9 9,aSOBUFC0QK,aSOBUFC0		Qw,aSOBUFC0		!?!?!H?- -! !*?!$OBUFC0!$OBUFC0!$OBUFC0!$OBUFC0!#OUTDON
 
"%,&0&T"( OUTSTR: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	: :	A"	("@	"@HADQK	A
	#%	%         @#Qw,aKOBUFC0: :	%	B,aSOBUFC0QK	C9,a[OBUFC0	AD#,aSOBUFC0	acQ	@QK: :	C9B$A&	t$,aSOBUFC0	$B$A&%	C55QK	C9AD	,aSOBUFC0	#,aSOBUFC0		: :Qw,aSOBUFC0		!`T!T!T!HT! !*T!a) )!zT!$OBUFC0!$OBUFC0! $OBUFC0!$OBUFC0!#OUTDON
 
"%.(0&p& OUTDON: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM"9 97                                                       ; ;                 	Qw,aKZOBUFC0	"A
QK	C,ak\'MISCOM< <	@,aK^iMISCOM	A
QK	C9#"AD@ ,aS`OBUFC0	t#,aG`OBUFC0QQw,aGbOUTFIL: :QacdQ	@Q	@	t"aGQacdQ	@Q	@	A$	($@;	$,agfINCOM A; ;Qw,aGbOUTFILQ	t$,aGhyINCOM QacjQ	@A@Q	@<BQw,aGbOUTFIL7 7Q	t$,aGhyINCOM QacjQ	@A@Q	@QK	C9#"AD	,aS`OBUFC0	@ 7 7,aSlOBUFC0	t#,aG`OBUFC0QQw,aGbOUTFILQacdQ	@Q	@j	@ Qw5 5,aSZOBUFC0		!!
g*i*n.   S*i,.!j$yINCOM !h$INCOM !b5 5$OBUFC0!n$OBUFC0!\$OBUFC0!d$OUTFIL!^$'MISCOM!`$iMISCOM!f#PUTLIN!l#PRINT 
 
"%.&0&::& OUTGO : :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM": :GOTO 	@ ",aKOBUFC0	A	A#ac,a
@OBUFC0A@#	",aKdMISCOM: :	A
		$"	@,aKGOCOM 	@HC,aKOBUFC0	@H,aSOBUFC0,aKOBUFC0: :	A	AD	,aS OBUFC0&QK	Aac"A@QS/	A$,aK$GOCOM ; ;	Aac&A@ac(a@A@QK	Aac"A@QSJ,aKdMISCOM	A
		$"T: :	@	$8Wac*Q	@ac,A@<	A,aS$GOCOM 		[	"M=@B#A%	(%@p	%9 9	%	@t#,aK.GOCOM 	A
u		$#	@A#q~	(#@q{		No more room in GO< <TO hash table -- leave off '-g' opt 	t#,aK.GOCOM 	A
ac0C@&	"t#,aS.GOCOM QK: :,aS2GOCOM 3	$Ld\4!!!:! :!:!':9 9!&$OBUFC0! $OBUFC0!$OBUFC0!*$GOCOM !$$GOCOM !4$GOCOM !8$GOCOM !"$dMISCOM* *!(#LABGEN!#CTOI!,#OUTTAB!.#OUTSTR!0#OUTGO0!2#OUTDON!6#FATAL0
 
"%*&0&C*$ OUTNUM: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM"; ;	CONTINUE	Qw,aKOBUFC0	CE",aKOBUFC0	A	A	"	AacQ	@ac5 5a@Q	@ac Q	@Qw,aKOBUFC0	AQK	A		&,aK"GOCOM 9 9,aS$GOCOM 	@ ,aS"GOCOM "ac&Q	@Q@A@	#@ t#QSacQ@Q	@		!5 5C!C!$OBUFC0!$$GOCOM !&$GOCOM !(#ITOC!#OUTTAB! #OUTSTR!"#OUTDON
 
"%*$0&O." OUTGO0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM": :     		Qg	@,aKdMISCOM	A
		,agOBUFC0aca@A@8 8	No more room in GOTO list -- leave off '-g' opt.		,aghGOCOM 	@acC@15 5,aK 'MISCOM,awhGOCOM ,aS"/GOCOM ,aKOBUFC0,aS$GOCOM QK,aS&
GOCOM 8 8,akhGOCOM 	@		ac(Q	@A@		!O!CO!h!'O!$OBUFC0!&; ;$/GOCOM !($GOCOM !*$
GOCOM ! $hGOCOM !$$'MISCOM!$dMISCOM!#OUTSTR!"#FATAL0!,#OUTNUM
 
"%&"0&0* CLEAO0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM		: :,awhGOCOM ,aS/GOCOM 	A"#	(#@	Line numbers out of order in GOTO list. ac9 9Q@,a
@OUTFIL	%)	t",aK/GOCOM 	$#
-acC@.	t",aK/GOCOM 	#: :	C,aK
GOCOM 	$A%	(%@>	%%	@	acA@$A@&	@HCC	&$?M9 9	
Circular GOTO chain.Q		$%
^acC@R_acA@$Q@A@	t",aK GOCOM 	B9 9	'A%t%QK	t'QS	'B'A%%rr	("338ac"Q@,a
@$OUTFIL	: :(	A,aShGOCOM 	%@ t%,aS&GOCOM 	A%%	A,aS('MISCOM		!!5 5!
!d!!!$OUTFIL!*$OUTFIL!,$GOCOM !$/GOCOM !&8 8$GOCOM ! $
GOCOM !$hGOCOM !.$'MISCOM!"#FINDGO!#GETLIN!#FATAL0!$#ITOC!(#PUTLIN
 
"%4*0&4& FINDGO: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	9 9QK	M=@B"A#	(#@
	t",aKGOCOM Qg		$#	$"	@A9 9	"	("@	t",aKGOCOM Qg)	@ $	(	t",aKGOCOM QS	A$ 		!4!$GOCOM !$GOCOM 
 
"%,&0&Z$ OUTLIT: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	; ;,aKeMISCOM	A
acQ	@Q	@acA@Q	@	A"	("@	"Qg	@@HADQG9 9Q
acQ	@
Q	@	acA@Q	@	A"	("@0	"Qg	@@HADQK	9 9	CacA@Q	@>	"@HADQGQ
acQ	@
Q	@16	acA@Q	@		! '!HZ!$eMISCOM!#OUTNUM!#OUTCH 
 
"%0$0&