H* OTHER0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM"9 9AND("OR("XOR(" MOD(	,aK&ILEXCOM	%	%9 9		%	AQS		,aK&ILEXCOM	%ac(	ac*Q@A@": :A@#,aK&ILEXCOM	$ac,A@A@ac.Q@A@,aK&ILEXCOM	%ac,A@A@9 9#ac,A@A@:ac,A@A@Aac,A@	A@H3	%
&L4;BIO9 9ac,A@A@ac,A@A@,aK&ILEXCOM	'ac.a@A@ac.a@A@p9 9ac.a@A@wac.a@ A@~i	'(Lxjqac.Q@A@ac,: :A@A@_	Missing right-hand side of assignment.ac0ac2Q	@A@ac,A@A@: :QK	@HCac4C@B	left-hand side of assignment too long.G		$"	@ac4C@H; ;]	String illegal on left-hand side of assignment. c	#@HC
ac4C@d#	$
)L	$9 9$$$````ac6A@		QS		!!!d!
!7 7(!)!*!+!,!-!	/!;!=!}!
!!66 6$ILEXCOM!8#BEGIP0!:#COPYL0!<#OUTCH !>#OUTSTR!@#GETSYM!B#OTHER !D#SYNERR!F#OUTDON
 
"%*0&" DECLO0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	9 9,aKILEXCOM	%	%		%	AQS		acQ	@A@ac0 0A@		!!!;!}!$ILEXCOM!#OTHER !#OUTDON
 
"%&"0&" EQUIV0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	9 9,aKILEXCOM	%	%		%	AQS		acQ	@A@ac2 2A@		!!!;!}!$ILEXCOM!#OTHER !#OUTDON
 
"%&"0&" DATAO0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	9 9,aKILEXCOM	%	%		%	AQS		acQ	@A@ac2 2A@		!!!;!}!$ILEXCOM!#OTHER !#OUTDON
 
"%&"0&" CODEO0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	9 9,aKILEXCOM	%	%		%	AQS		acQ	@A@ac2 2A@		!!!;!}!$ILEXCOM!#OTHER !#OUTDON
 
"%&"0&h(& OTHER : :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	: :	@ ",aKILEXCOM	#	unexpected EOF. acC@	("	"@H"A; ;	#%"	%%	$L	#%/$	%2.acQ	@,aKILEXCOM: :	Cac,a
@LEXCOM,a
@HLEXCOMQ	@:ac,a
@LEXCOMQ	@Cac	": :	A1	missing right parenthesis.O	"AacC@P_		QS		!h!: :h!
!'!;h!}h!     h! $LEXCOM!"$HLEXCOM!$ILEXCOM!#SYNERR! #OUTTAB!#OUTLIT!$#OUTSTR!&#GETSYM
 
"%,&0&",
& COPYL0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	9 9	@ "QSQS,aKILEXCOM	#	unexpected EOF. acC@	("	"@H"9 9	A
	#%&	%)!	$L	#%3(	%62	$L	< <5:;<=>?@ acA@,aKILEXCOM	Cac,a
@LEXCOM,a
@HLEXCOM9 9A@	AQSJac,a
@LEXCOMA@V		Q_,a_HLEXCOM	CQK	B; ;	%ac,a
@LEXCOMA@	Q	@A@%Q[QSc		QSvac 	"AAQK: :	%	@ QwQS	@ QS		unbalanced parentheses. 	"AacC@9 9		!"!	!"!d"!
!'!;"!}"!                                 ": :!"$LEXCOM!$$HLEXCOM!$ILEXCOM!(#SCOPY !#SYNERR!#OUTTAB! #OUTLIT!&#OUTSTR!*#GETSYM
 
"%0&0&

0
& ESCAP0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	: :acQ@	"	A#		#			#acQ@	"$L
: :		#	#Cac"ac%acA@A@#Q	CacQ@	%:: :	A%	(%@<	t%	QGQQK	A
3acQ	@A@#=2	acA@#Q	C: :	#C9AD	,aSOBUFC0acQ@W		t#,aSOBUFC0Q		C
acQ@fjQ: :	%uac Q@A@#acQ@pt9ac"A@#		QSac$		!
!!9 9
!
!
!	 !$!%!&!0
!&$OBUFC0!($OBUFC0!#DGETS01 1!#BEGIP0!#BEGIN0! #OUTNUM!"#OUTCH !$#OUTTAB!*#OUTSTR!,#OUTDON!.#GETSYM
 
"%,&0&
