0 " SETUP08 8)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM: :,aKPRCCOM	A			acQ@acQ@LacQ@LQ,awPRCCOM,aKPRCCOM	A9 9acA@,awPRCCOM,aSPRCCOM,awPRCCOM,aGPRCCOMQVacQ@Q@9 9Q	@V		!0!$PRCCOM!$PRCCOM!#SDUPL !#MKTABL!#GETLO0!#VARGEN!#ENTER 
 
"%z"0&D4" SETUQ0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	9 9acQ@acA@QS	@ Qw,aSDS$MEM,aSDS$MEM,aSDS$MEM	acA@Qw5 5,aSDS$MEM	@ ,aSDS$MEM,aS DS$MEM,aS"DS$MEM,aS$DS$MEM	ac&Q@Qw7 7,aS(DS$MEMQKQ,aK*fPRCCOM	Aac,A@,aS*fPRCCOM4	ac.Q@Q@9 9,a
@*fPRCCOM		!D!D!	D!$DS$MEM! $DS$MEM!$DS$MEM!$DS$MEM9 9!($DS$MEM!$$DS$MEM!&$DS$MEM!"$DS$MEM!,$DS$MEM!.$fPRCCOM!#LABGEN!#DSGET !0 #MKTABL!*#SDUPL !#GETLO0!2#ENTER 
 
"%r"0&7"$ ENTEV0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	: :acQ@acA@	"@ t",aSDS$MEMacQ@	t",aSDS$MEMacQ@acQ@	t"9 9,aSDS$MEMQw,aKDS$MEM	#A	",aSDS$MEM&	t#,aKDS$MEM	A
9 9	#+/	"t#,aSDS$MEM*		!7!$DS$MEM!$DS$MEM!$DS$MEM! $DS$MEM !#SDUPL !#DSGET !#GETLO0!#VARGEN
 
"%p$0&B$$ CREAT0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	: :Qw,aKDS$MEM	"	t",aKDS$MEM	"	"A
	t",aKDS$MEM	AD,aGDS$MEM9 9QacQ	@Q,awPRCCOM,aKPRCCOM	AacA@,awPRCCOM,aSPRCCOM; ;!	t",aKDS$MEM	AD,aGDS$MEMQ,awPRCCOM,aGPRCCOMQ
ac Q	@Q@Q	@
: :		!B!$DS$MEM! $DS$MEM!$DS$MEM!$DS$MEM!$PRCCOM!$PRCCOM!                                                                   MKTABL!#SDUPL !"#ENTER 
 
"%0$0&S(" GENPS0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM"; ;=1		acQ@Qw,aKDS$MEM	AacQ@Qw,aSDS$MEM	acQ@A@9 9
	acQ@Qw,aSDS$MEM,aGDS$MEMQacQ@Q	@acQ@acQ@9 9Qw,aSDS$MEM'acQ@A@ac A@ac"Q@A@ac"a@A@ac$A@		: :!S!S!$DS$MEM! $DS$MEM!$DS$MEM!#SDUPL !#VARGEN!#GENIN0!"#OUTTAB !$#OUTSTR!&#OUTDON
 
"%2"0& " ENTEW0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	< <Scopes nested too deeply. 		,agPRCCOM	@acC@                                            akPRCCOM	@@ ,awPRCCOM% %,aSPRCCOM		!d !$PRCCOM!$PRCCOM!#FATAL0
 
"%""0&D$ EXITS0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	9 9Scope stack underflow.,aKPRCCOM	A	acC@,awPRCCOM,aKPRCCOM	A
8 8	@ ",awPRCCOM,aGPRCCOMQLacQ	@LQ@Q@A@"	%/acQ@.9 9,awPRCCOM,aGPRCCOM	QLacQ	@L,aKPRCCOM	@H,aSPRCCOM		!D!% %$PRCCOM!$PRCCOM!#SCTABL!#FATAL0!#DSFREE!#RMTABL
 
"%r$0&C$$ GENPA0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	8 8	Not enough parameters.QK	AacC@			acA@Qw,aKDS$MEM	AD7 7,aGDS$MEMQacQ	@A@acA@A@acA@"	#acA@#ac A@Qw; ;,aKDS$MEMQS		!C!=C!$DS$MEM!$DS$MEM!#EXPRS0!#SYNERR!#OUTTAB !#OUTSTR!#OUTCH ! #GENEX0!"#OUTDON
 
"%*$0&2& GENPR0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	; ;acA@	"acA@	#"t#,aSDS$MEM	@ ,aSDS$MEM	A$Qw,aKDS$MEM	A: :	#,aSDS$MEMQw,aKDS$MEM	%($@t%,aKDS$MEM	A
	%($%%)	#: :	t%,aSDS$MEM	acA@Qw,aKDS$MEM	A,aKDS$MEM	AD,aGDS$MEMQ; ;ac Q	@A@;Qw,aK"DS$MEM	AD,aGDS$MEMQac Q	@A@ac$A@A@9 9Qw,aKDS$MEM	AD,aGDS$MEMQac Q	@A@ac$A@A@I	ac$A@A@9 9ac&A@$A@ac(A@Qw,aGDS$MEMQac*Q	@ac&A@"A@		!!: :!!(!)!=!$DS$MEM!$DS$MEM!$DS$MEM!$$DS$MEM!($DS$MEM!"6 6$DS$MEM!#LABGEN!#DSGET ! #OUTTAB!&#OUTSTR!*#OUTCH !,#OUTNUM!.#OUTDON!0#OUTGO 
 
"%,&0&&4& GENPV08 8)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM: :,aKfPRCCOM	A			@ "Procedure body not defined. ac,a
@fPRCCOMQ@Q@9 9A@"	%#Q	#t#,aKDS$MEM	@HC,aKDS$MEM	AD,aGDS$MEMQLac: :Q	@L,a
@MISCOM	A@acC@+ac A@#	t#,aK"DS$MEM	$	%$G	$A
< <	t$,aKDS$MEM	%ac$A@$HL	t#,aK&DS$MEM	$	%$Z	$A
	t$,aKDS$MEM5 5	%,aG(DS$MEM	QLac$Q	@L	t$,aG"DS$MEMQLac$Q	@Lac$A@$[_	t#8 8,aK*DS$MEM	A
,aG,DS$MEM	QLac$Q	@L~	t#,aG.DS$MEM	QLac$Q	@L	t#9 9,aGDS$MEMQLac$Q	@Lac$A@#"ac0,a
@fPRCCOM	@ ,aSfPRCCOM		!5 5&!H&!$DS$MEM!*$DS$MEM!$$DS$MEM!($DS$MEM!$DS$MEM!0$DS$MEM!.9 9$DS$MEM!,$DS$MEM!$DS$MEM!$fPRCCOM!$MISCOM!#SCTABL!#CTOC! #SYNERR!"#GENPU0 !&#DSFREE!2#RMTABL
 
"%t&0&w~$ GENPU0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM"9 9stop"-1"if (" .le.0)call error(24hcontrol: : stack underflow.)"Ngoto("T),	Qw,aKXDS$MEM	A; ;acZA@Qw,aSXDS$MEMQw,aGXDS$MEMQLac\Q	@LA@Qw,aK^DS$MEM9 9	Aac`A@acba@A@acdA@		 Qw,aKfDS$MEM	A
ac`A@Qw6 6,aKhDS$MEM	AD,aGXDS$MEMQLacbQ	@LA@acjA@A@Qw,aKhDS$MEM	AD7 7,aGXDS$MEM-QLacbQ	@LA@acba@A@acdA@ac`A@acba@A@Qw; ;,aKhDS$MEM	AD,aGXDS$MEMQLacbQ	@LA@acba@ A@acdA@5	ac`A@Qw9 9,aK^DS$MEM	"t",aKXDS$MEM	A,aGlDS$MEMQLacnQ	@L,aKpsMISCOM	A
9 9Qw,aKfDS$MEM	A
%acrQ@acbQ@A@acjA@A@Qw,aKtDS$MEM	AD; ;,aGXDS$MEMQLacbQ	@LA@acjA@A@Qw,aKhDS$MEM	AD,aGXDS$MEMQLacb: :Q	@LA@acjA@A@acdA@ac`A@+	acba@NA@	t",aGlDS$MEMQLacv; ;Q	@L	t",aKXDS$MEM	"	t",aKXDS$MEM	"	"A
acjA@A@	t",aGlDS$MEM; ;QLacvQ	@Lacba@TA@Qw,aKfDS$MEM	A,aKhDS$MEM	AD,aGXDS$MEM: :QLacbQ	@LA@$,aKpsMISCOM	A
acbQ@A@6Qw,aKtDS$MEM	AD; ;,aGXDS$MEMQLacbQ	@LA@acjA@A@Qw,aKhDS$MEM	AD,aGXDS$MEMQLacb: :Q	@LA@acjA@A@=2	acdA@Qw,aGXDS$MEM	QLacnQ	@L!		!w9 9!w!(!)!,w!=w!^$DS$MEM!r$DS$MEM!d$DS$MEM!n$DS$MEM!z: :$DS$MEM!l$DS$MEM!v$sMISCOM!`#LABGEN!b#OUTNUM!f#OUTTAB!h#OUTSTR!j#OUTDON!p#OUTCH !t                                                                   OUTGO !x#VARGEN!|#OUTGO0
 
"%r$0&yZ" GENPT0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM"9 9if(".ge."$)call error(23hControl stack overflo: :w.)"B+1	Qw,aGFDS$MEMQacHQ	@A@Qw,aGJDS$MEMQ; ;QK	A
acLA@acNa@A@Qw,aKPDS$MEM	AD,aGRDS$MEMQacNQ	@A@6 6*acNa@A@acHQ	@A@acNa@A@acTA@acLA@Qw,aKPDS$MEM	AD; ;,aGRDS$MEMQacNQ	@A@acVA@A@Qw,aKPDS$MEM	AD,aGRDS$MEMQacN7 7Q	@A@acNa@BA@acTA@		!y!=y!T$DS$MEM!H$DS$MEM!R+ +$DS$MEM!L$DS$MEM!J#OUTNUM!N#OUTTAB!P#OUTSTR!V#OUTDON!X#OUTCH 
 
"%*"0&