
" BEGIN08 8)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM- -,aKMISCOM	A	A,aSMISCOMac		!$MISCOM!#BEGIO0
 
"%""0&(2" BEGIP0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM"; ;call c$incr(,aKMISCOM	A	A,aSMISCOMac ,aK"`MISCOM	A
9 9ac$A@ac&a@A@ac(,a
@*zINCOM A@ac,A@A@ac.A@		!(: :!)(!,$zINCOM ! $MISCOM!$$`MISCOM!"#BEGIO0!&#OUTTAB!(#OUTSTR!*#OUTNUM!.#OUTCH  !0#OUTDON
 
"%""0&FB$ BEGIO0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM": :.data.".main." call t$init",call t$entr(9 9":.data."B.main."Jcall t$trac(3,0)"\call t$9 9trac(1,9h@.main@..)"xcall t$trac(1,".)".m7 7ain."call c$init,ak MISCOM	@,aK"mMISCOM	A
ac$a@< <,a
@&KMISCOM	Aac(,a
@&KMISCOM,a
@*MISCOMac,A@,a
@*MISCOMac$,a
@&KMISCOM5 5a@	@HCac.A@ac0a@ A@ac2A@#ac.A@ac0a@,A@ac49 9,a
@ MISCOMA@ac6A@A@ac2A@,aK8qMISCOM	A
ac$a@:,a
@&KMISCOM9 9	AOac$,a
@&KMISCOMa@B	@HC ac.A@ac0a@JA@ac2A@ac.A@ac0: :a@\A@ac2A@`ac.A@ac0a@xA@ac:,a
@&KMISCOM	B"	ac4A@"A@9 9ac6A@A@ac0,a
@&KMISCOMA@ac0a@A@ac2A@}W,aK<`MISCOM	A
9 9ac$,a
@&KMISCOMa@	@HCac.A@ac0a@A@ac2A@6-		!F!6 6
F!)F!HF!*$KMISCOM!$$MISCOM!.$MISCOM!@$`MISCOM!&$mMISCOM!<< <$qMISCOM!(#EQUAL !>#LENGTH!,#PUTLIN!0#PUTCH !2#OUTTAB!4#OUTSTR!6#OUTDON!8#OUTNUM!:#OUTCH 
 
"%$$0&" ENDMO0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	@  ,aSMISCOM		!$MISCOM
 
"%""0&7H" STOPM0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM"6 6call t$clup"call t$trac(2,0)".call c$end; ;,aK:mMISCOM	A
ac<A@ac>a@A@ac@A@,aKBqMISCOM	A
ac<A@ac>: :a@A@ac@A@,aKD`MISCOM	A
ac<A@ac>a@.A@ac@A@'		!* *7!F$`MISCOM!<$mMISCOM!D$qMISCOM!>#OUTTAB!@#OUTSTR!B#OUTDON
 
"%""0&%:" RETUR0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM"9 9call t$exit"call t$trac(2,0),aK.mMISCOM	A
ac0A@9 9ac2a@A@ac4A@,aK6qMISCOM	A
ac0A@ac2a@A@ac4A@		' '!%!0$mMISCOM!8$qMISCOM!2#OUTTAB!4#OUTSTR!6#OUTDON
 
"%""0&p$ ENDPR0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	9 97      SUBROUTINE T$INIT*n.      INTEGER**2 SP,NUMRTN*n.       INTEGER**4 RECORD*n.      INTEGER**4 STACK*n.   9 97    COMMON /T$PROF/NUMRTN,RECORD(4,*i)*n.       COMMON /T$STAK/SP,STACK(4,*i)*n.      NUMRTN=*i*n.      RETURN: :*n.       END*n.,aKmMISCOM	A
ac,a
@OUTFILC@ac,a
@OUTFILC@ac7 7,a
@OUTFILC@ac,a
@OUTFILC@*ac,a
@OUTFILC@7,a
@MISCOMac9 9,a
@OUTFILC@M,a
@MISCOMac,a
@OUTFILC@`,a
@MISCOMac,a
@OUTFIL9 9C@iac,a
@OUTFILC@qz	       SUBROUTINE C$INIT*n.      INTEGER LIMIT*n.      INTEGER**49 97 COUNT*n.       COMMON /C$STC/ LIMIT,COUNT(*i)*n.       INTEGER I*n.      DO 1 I=1,*i*n.    1   COUNT(I)=0*n. 6 6      LIMIT=*i*n.       RETURN*n.       END*n.7,aK`MISCOM	A
,aKzINCOM 	"ac: :,a
@OUTFILC@8ac,a
@OUTFILC@Eac,a
@OUTFILC@Pac,a
@OUTFILC@]8 8A@"ac,a
@OUTFILC@qac,a
@OUTFIL	C@zA@"ac,a
@OUTFILC@ac9 9,a
@OUTFIL	C@A@"ac,a
@OUTFILC@ac,a
@OUTFILC@ )		!$zINCOM # #!$OUTFIL!$MISCOM!$`MISCOM!$mMISCOM!#PRINT 
 
"%$$0&