6
& SETUR0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	< <Qw,aKDS$MEM	C,aKDS$MEM	"A
	t",aKDS$MEM	#	A$t",aGDS$MEM: :Q
acQ	@
A@$A@Q	A$t#,aGDS$MEMQ
acQ	@
A@$A@QA':: :    8A'9<G;Q=acA@##	A$t#,aGDS$MEMQ
acQ	@
A@$A@9 9	BQacA@#F]	Select alternative must be a short integer. ^acA@"acQ	@9 9Q	@QS	MQ'acC@_		QS		         t",aKDS$MEM	C	#9 9	A	t",aKDS$MEM	C	t#,aKDS$MEM	C,aKDS$MEM	A$$< <(	t",aKDS$MEM	C	t#,aKDS$MEM	C/,aKDS$MEM	A5G9		QS6 6acQ	@	%ac A@%	"@ t",aSDS$MEM		,aSDS$MEM	"@D%	ac"Q	@A@: :,a
@DS$MEMA@%ac$Q	@ac&A@A@A@A@"	%ac$A@%ac(A@	ac*Q	@QS9 9		!!{!{!!
{!-!:{!	i!!{69 9?!$DS$MEM!&$DS$MEM!$DS$MEM!$DS$MEM!(#LENGTH!4#EXPRS0!*#DSGET !0) )#MAKET0! #GCTOL !"#DSFREE!$#SYNERR!,#SCOPY !.#EXPRT0!2#ENTEU0
 
"%4&0&
J2, GENSE0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM	: :	@ ",aSSELGEN	A#	(#@	#Qg	@@HADQK		$	#@HAD	QGQQG8 8QacQ	@Q	@,akSELGEN	@#@H%t%QK,awSELGEN,aSSELGEN	t%QK9 9,awSELGEN,aSSELGEN	                                                                                                         n gen_select_code: can't happen. <	$%R	%U; ;
'acC@=,aKSELGEN	%
]acA@,a
@SELGENQ	@A@"acA@"A@9 9		^,aKSELGEN	M=&	&M=&u	&A	B#	(#@	#,agSELGENv6 6	@&'	'&'		'A	&(t',aKSELGEN	t(,agSELGEN	@	t'6 6,aKSELGEN	)t(,aKSELGEN	t',aSSELGEN	)t(,aSSELGEN	t',aKSELGEN	)t(9 9,aKSELGEN	t',aSSELGEN	)t(,aSSELGEN
|	A#	(#@:	Identical consta; ;nts in 'select' alternatives. =	#,agSELGENX	t#,aGSELGENQQK,a_SELGEN: :	C;ac Q	@Q@A@ac"Q@,a
@$MISCOMA@ac&C@>;Y	@ ,aS(SELGEN	A8 8	*	#B*	*,agSELGEN	@A+*#	(#@	#,agSELGEN	t*9 9,aKSELGEN	MQ	t#,aKSELGEN	MQQ	+9@MQ'++QA'*9 9	@1	(+/acA@*A@#Q	@A@"	acA@"A@		!!8 8!G!!
G!HG!!G.t!$SELGEN!&$SELGEN!: :$SELGEN!$SELGEN!0$SELGEN!,$MISCOM!#GENIF ! #FATAL0!"#GENSF0!$#OUTNUM!(#ITOC!*
 
#CTOC!.#SYNERR
 
"%L,0&Sd$ GENSF0: :)MISCOMiGOCOM gPRCCOMSELGENCODEG0OUTFILDS$MEMOBUFC0LOOPC0INCOM \LEXCOM"9 9IF(".EQ.")GOTO ""IF("&.GT.0.AND."2: :.LE."8GOTO(	#ac>A@ac@a@A@ac@Q	@A@ac@a@A@; ;Qw,aGBSELGENQacDQ	@A@ac@a@A@Qw,aGFSELGENQacHQ	@acJ9 9A@QKQg@@8Q_	@HCQw,aKBSELGEN	@HCacLQ	@A@: :Q@A@K,aKNSELGEN	AacP,a
@NSELGENacR,a
@NSELGENA@Zac>; ;A@ac@,a
@NSELGENA@acTA@A@ac@Q	@A@Qw,aKBSELGEN	%acT; ;A@A@	AQw,a_BSELGEN	"acDA@"A@acTA@A@Qw,aKBSELGEN5 5	@H"	acDA@"A@	acJA@acL,a
@NSELGEN	A@Q@A@Vac>A@; ;,aKVsMISCOM	A
/ac@a@"A@ac@Q@A@ac@a@&A@ac@Q@A@ac@a@2A@; ;Qw,aKBSELGENQw,a_BSELGEN	B"acDA@"A@acTA@A@<	ac@a@8A@9 9Qw,aGFSELGENQacHQ	@Qk	@Qw,aKX~SELGEN	B#	(#@
	#Qw9 9,agBSELGEN	@acTA@A@Qw,aKBSELGEN	$#	@,aGFSELGENQacH: :
Q	@QkQK		AacZA@QS	0acHQ	@	acTA@A@acT9 9A@A@ac@Q@A@acJA@?		!!!S!)!+!,!-: :S!=S!`$~SELGEN!J$SELGEN!N$SELGEN!V$SELGEN!^$sMISCOM!b#LABGEN!F#OUTTAB!H/ /#OUTSTR!L#OUTNUM!P#OUTGO0!R#OUTDON!T#SCOPY !X#VARGEN!Z#GENIN0!\#OUTCH 
 
"%<$0&