$*: :"ALL"'Message has been sent on system *,#h*n"<M: :'essage request failed on system *,#h*n	A"t"QS	""acd9 9	A@Q@
A@	%acfQ@
A@achQ@
a@	@HC	A#@ t"QS	("@A#%9 9/"" acjQ@
	#	(#@5	#%:		t#QS
6;	@ uQS
	A9 9	#t"QGQraclQ@
A@#Q	@rA@	BM=""/         A#@ t"QS	("@A#%j]: :][		#A$t$QG	Qr		$%acdA@#Q	@rA@%	&%	$$	t$QS		($9 9	
	(#nn	$@HCacnQ@
A@A@		$BC	A$         @ t$QS	acj9 9Q@
	t"QGQracpQ@
Q	@rA@		"@H&acrA@'Q@pQ@
Q
	AactA@; ;A@
a
@vCacxQ@
LaczA@'Q@pQ@A@&Q@
Q
	A		"&#"$#; ;h	t"QK	(	t"QGQrac|A@a@A@Q	@r	t"QGQrac|A@a@<: :A@Q	@r~n	()Lo	""f`acxQ@
iac~!u!v!9 9|! !!! !!!
 !	f!g! !  < <GCLEANUP$!#CLEAN0!r#GETARG!x#STRIM !z#CTOP!|#GETLIN!~#CTOC!v#EQUAL !t#MAPSTR!#RING$C !#MKON$F!#ERROR !#RING$T!
#PRINT !#SWT 
 
"%*0&" CLEAN0 	ac		!#X$CLRA
 
"%&"0&