,*9 9"ALL"&Phantom (*i) created on system *,#h*n":P< <(hantom creation failed on system *,#h*n	A"	t"QS	("@acd9 9	A@Q@
A@	%acfQ@
A@achQ@
a@	@HC	A#@ t"QS	("@A#%9 90##!acjQ@
	#	(#@6	#%;		t#QS
7<	@ uQS
	A9 9	#t"QGQraclQ@
A@#Q	@rA@	BM=""0	A#@ t"QS	("@A#%k^: :^\		#A$t$QG	Qr		$%acdA@#Q	@rA@%	&%	$$	t$QS		($9 9
	(#oo	$@HCacnQ@
A@A@		$BC	A$	@ t$QS	acj9 9Q@
	t"QGQracpQ@
Q	@rA@		"@H&acrA@'Q@pQ@
Q
	AactA@; ;A@
a
@vDacxQ@
MaczA@'Q@pQ@A@&Q@
Q
	A		"&#"$#; ;i	t"QK	(	t" QGQrQGQtac|A@a@Q	@rA@Q	@t	t"QGQr9 9ac|A@a@:A@Q	@ro	()Lp	""gaacxQ@
jac~9 9!u!v!|!'!!!'!!!
'!	f!g!< <'! 'HCLEANUP$!#CLEAN0!r#GETARG!x#STRIM !z#CTOP!|#GETLIN!~#CTOC!v#EQUAL * *!t#MAPSTR!#RING$C!#MKON$F!#ERROR !#RING$T!
#PRINT !#SWT 
 
"% *0&" CLEAN0 	ac		!#X$CLRA
 
"%&"0&