0,9 9"$Usage: setime [-d mmddyy] [-t hhmm]"4JanuaryFe9 97bruaryMarchAprilMayJuneJulyAugustSeptembe9 9rOctoberNovemberDecember"
"'-3;FOY"$d9 9
<rs>t<rs>"0*s has only *i days*n"FThe month mus: :$t be between 1 and *i (inclusive)*n"x*2,,0i*2,,0i9 9")The time has been reset on system *,#h*n"0Setime : : request failed on system *,#h*n	acXa@$Q@	CacZa@: :		QHQ	A
	A"Q	ADQGQJac\Q	@JA@"Q@IA@	%*acZ9 9a@)	The first day of the month must be at least 1..QI	"QJ	#QK	$"9 9	B(%"B`9@%"#B(%#B`9@%#$B(%$B`9@%$#%
oacZC@/p	$M=@A	$M=@: :	A	$M=@A
z	"@HC	#@H#A$	@ $                           	@ $	"%9 9a'	@t"aK	"t"aK3	$#
(aG4QJ	$a[3	%ac^A@	a@0Q	@J9 9A@%ac`ac^A@	a@Fa@ac`Q	AacZa@K)Q	A
	A9 9	"Q-	ADQGQJac\Q	@JA@"Q@LA@
	%
jacZa@iQL	"QM9 9	#"B(%"B`9@%"#B(%#B`9@%#"A	%
	@	The hour must be between 0 and9 9 23 (inclusive).acZC@	#A	%-	@/	The minute must be between 0 a: :	nd 59 (inclusive).2acZC@31SacbA@&Q@HQ@bQb	AacdA@A@a
@f9 9ZacZQ@bcQ	AachQ@RA@		
"A#t#QKQ	t"QSG	("@A#%u< <ukQ	AachQ@RA@QV	MQJQU	MA;	AQJ	EG?	CQL; ;GA;	ABQJacjQ@JachQ@RA@QU	M=@%QU	M='aclQ@bA@a@x; ;A@'A@%	A"ac\Q@bA@"Q@LA@
		(acnA@&Q@HQ@HA@(Q@bQb	A9 9		
"(                #"$#o	t"QKJ	)	t"QGGQJac^A@a@A@Q	@J	t"QGG< <QJac^A@a@0A@Q	@Ju	)*Lv	""mgacZQ@bpac`9 9!00!	q!u!        |!}'!!
!!!!!!
'9 9!'!'!;!<'!d!f'!'^CLEANUP$"<$9 9h!z#CLEAN0!p#CTOP!l#PARSCL!n#ERROR !r#PRINT !t#SWT !v#RING$C!x#MKON$F!|#TIMDAT!~                                                                   SLEEP$!#ENCODE!#RING$T
 
"%z,0&" CLEAN0 	ac		!#X$CLRA
 
"%&"0&