-* RING$C; ;	@ QSacA@A@"Q@
A@#Q@
A@$A@%A@&	%'acQ	@A@Q@
A@#Q	@: :QK	@HC
acA@%)	                                                                                     nable to connect to Ring process./QK	A
acC@0: :	A@Q	@A@D	Bad parameter in status call. PacC@QA@Q	@A@O	Ne9 9tworks are not configured.kacC@lA@Q	@A@j	Primenet name is unknown. ac9 9C@A@Q	@A@	'@D(L
k%P&()*		!-!( (!c!f-!.!#X$STAT!#X$CONN!#X$WAIT!#PTOC
 
"%4*0&1"( RING$T; ;	@ QSQK		C?"acQ	@A@Q	@A@"A@#	#@HC
acA@QK	A; ;acQ	@Q	@A@Q@Q	@HC
acA@+/	uQK	$acQ	@Q	@A@: :Q@Q	@HC
acA@DHQK	%SQ	BM=QS		@HADQK	%; ;acQ	@A@A@#QK	%macA@hl	System is not in the ring.sac9 9C@tA@Q	@A@r_	%@H&Ls`R	Connection has been term9 9inated. acC@A@Q	@A@	
Request is invalid. 2acC@3A@Q	@: :A@1	System is not in the ring.HacC@IA@Q	@A@G	
Request is unknown. a9 9acC@bA@Q	@A@`	Request is the wrong size.wacC@xA@Q	@A@v99 9	$L
:2Haw 	Cannot transmit request.acC@A@Q	@A@9 9		!!!1!!f1!.!!#X$TRAN!#X$WAIT!#X$RCV !
 
#X$CLR ! #PTOC
 
"%<(0&