,$ INITI09 9'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM".ma9 9in.".main." string"(stringtable"4linka9 9ge"<
procedure"F
recursive"Pforward"Xloca: :l"^if"belse"hfor"lwhile"rrepeat"z9 9until"case"do"
return"break"nex: :t"stop"$goto"*call"0end"4include9 9"<define"D	undefine"Nselect"Vwhen"\ifany9 9"b	continue"lcomplex"tlogical"|	implicit9 9"
parameter"	external"
dimension"$integer9 9",equivalence"8	function"Bsubroutine"Nco9 9mmon"Vdata"\trace"bsave"hreal"ndoub9 9leprecision"~
blockdata"stackheader"shortc8 8all"	stmtfunc	@ ,aS(MISCOM,aS*PRCCOM,aS,fPRCCOM,aS.MISCOM9 9,aS0MISCOM		,aS2yINCOM 	@ ,aw2yINCOM ,aS4INCOM 	A"@ t",aS61OBUFC0	A"%9 9	A"ac8A@	t",aS:OUTFIL	A"%.  	@ ,aS<LOOPC0,aS>CODEG0		9 9,aS@HMISCOM	@ ,aSBIMISCOM,aSDJMISCOM,aSFKMISCOM	acHa@A@,a
@JMISCOMA@: :	acHa@A@,a
@LLMISCOMA@acNA@acPA@,aSRJLEXCOMacPA@,aSTKLEXCOM; ;9acVa@ A@acVa@(A@acVa@4A@acVa@<A@	acVa@FA@
acVa@PA@acV; ;9a@XA@acVa@^A@acVa@bA@acVa@hA@acVa@lA@acVa@rA@acVa@z; ;9A@acVa@A@acVa@A@acVa@
A@acVa@A@acVa@A@acVa@A@; ;9acVa@$A@acVa@*A@acVa@0A@acVa@4A@acVa@<A@acVa@DA@acV; ;9a@NA@acVa@VA@ acVa@\A@!acVa@bA@"acVa@lA@#acVa@tA@#acVa@|; ;9A@$acVa@A@$acVa@A@%acVa@A@$acVa@$A@#acVa@,A@$acVa@8A@&; ;9acVa@BA@'acVa@NA@(acVa@VA@)acVa@\A@"acVa@bA@$acVa@hA@#acV: :*a@nA@#acVa@~A@*acVa@A@$acVa@A@$acVa@A@+		!!!9 9!!*q!r!s!t!)u!v!w!x!y!z!"{!|9 9!&}!~!!!!!!!$!!		!

!        !!9 9!+!!                                 !'!#!!! !!%!!("!'!a(9 9!~$JLEXCOM!$KLEXCOM!`$INCOM !^$yINCOM !h$LOOPC0!b$1OBUFC0!f$OUTFIL!j$CODEG09 9!V$PRCCOM!X$fPRCCOM!v$MISCOM!x$LMISCOM!\$MISCOM!l$HMISCOM!n$IMISCOM!p$JMISCOM4 4!r$KMISCOM!T$MISCOM!Z$MISCOM!|#MKTABL!d#MKTEMP!t#SCOPY !z#DSINIT!#ENTES0
 
"%$$0&," ENTES0: :'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM	AQ( (QKQacQ	@Q@,a
@JLEXCOM		!$JLEXCOM!#ENTER 
 
"%,"0&$ CLEAN07 7'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM	A"t"3 3,aGOUTFIL	QacQ	@	A"%    		!!$OUTFIL!#RMTEMP
 
"%&$0&