Lj$9 9'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM"[-f9 9m] [-n <ignored>]"&=incl=/swt_def.r.i	Usage: link [-fm: :	] [-n<filename>]. ac:a@,a
@<_MISCOM	Cac>C@	ac@acBA@	"acB< <A@	#,aKDdMISCOM	A	A,aSFINCOM 	acHa@&A@,awFINCOM ,aSJ~INCOM acL9 9A@".	AQacNQ@fQ@	%L	A,aSFINCOM 	acHQ@fA@,awFINCOM : :,aSJ~INCOM 	@ ,aSPyINCOM acLA@"CK	linkage  _*n. aacRA@"acTA@"A@#: :acVA@"acXA@C@bacRA@#acZQ@.A@#	%
acZQ@A@#	%ac\: :Q@.Q@	Aac^Q@.	AD	QS-acXA@A@Q@.ac`Q@A@Q@.A@
: :acXA@A@Q@.		acVA@#acb!u!}!D!!D!,D9 9(   *s*n.;   *s.  !V$yINCOM !L$INCOM !P$~INCOM !B$_MISCOM!J$dMISCOM!N#OPEN!H; ;#MKTEMP!T#GFNARG!`#GETLIN!b#EQUAL !d#LENGTH!@#PARSCL!D#ERROR !F#INITI0!R#GETLI0!X#REWIND !Z#SORT!\#RMTEMP!^#PRINT !f#SCOPY !h#SWT 
 
"%<$0&J2
$ GETLI09 9'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM	ac9 9,aKILEXCOM	%	"ac,aKILEXCOM	Cac		Left paren must fo9 9llow 'define'.acC@ac,aKILEXCOM	Cac0	Left paren mus: :
t follow 'undefine'.4acC@53)	Includes nested too deeply. K		,agINCOM : :	@acC@L]	can't open include file.c	acacQ@,akINCOM 	@@ ,awINCOM 7 7,aS yINCOM 	ac"Q@A@,awINCOM ,aS$~INCOM ,aK$~INCOM 	CacC@d; ;,aKINCOM 	@H,aSINCOM Jac,aKILEXCOM	CacQ@ac&Q	@A@Q@9 9	identifier expected in subprogram declaration.+acC@,*ac,aKILEXCOM: :	%O	CacQ@ac&Q	@G@'Q@QacJNGac,aKILEXCOM	9 9	Cac,aKILEXCOM	CacQ@ac&Q	@G@[Q@o		identifier expecte9 9d in named common statement.}acC@~|ha		"#L
 !"#$; ;
%'()K	"	#L            **2456789:;<=Hb>ac: :		!}!E!E!E!
!(!/E!u!!	E9 9y*s*n.   !$ILEXCOM!*$yINCOM !$$INCOM !.$~INCOM !,#OPEN!#GETSYM!#ENTER0!  #SYNERR!"#REMOV0!&#ERROR !(#GETLO0!0#PRINT 
 
"%p$0&
