f"" REMOV09 9'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM	Identi9 9fier must follow 'undefine'.acQ@	%
acC@			Right paren must follow 9 9identifier in 'undefine'. acQ@Q@acQ@L	%
EacC@		DacQ@: :Q@H,a
@JLEXCOM	A
QH	CSX		YacQ@JacQ@,a
@JLEXCOM		: :!f!)f!f!$JLEXCOM!#SKIPW0!#LOOKUP!#SYNERR!#DELET0!#DSFREE!  #DELETE
 
"%6"0&"& INVOK0< <'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM	@ "uQK9 9	AacQ@A@"	A#uQK	$	($@	t$,aKDS$MEM	A
	%< <	t#QS	(##	($@t$,aKDS$MEM	$"	@ADQK	AD,aGDS$MEMQ4	t#QG: :Q6		#%acQ	@4Q	@6A@%	##+$	result of define invocation too long. G		$#; ;	@acC@H]c	@ t#	QSacQ@	A$	($@o	$$"	@t$QGQ4< <acQ	@4pt		!!!!     !!$DS$MEM!#CTOC!#GETAC0 !#SYNERR!#PUTBC0! #DSFREE
 
"%^&0&*& ENTER09 9'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM	only i: :dentifiers may be defined.acQ@	"%
acC@		acQ@Q@acQ@\9 9	"CacA@#A@$	C		4acQ@\	"+	@ $#;	define identif; ;er must be followed by a comma. ?	"%
[acC@@	#A
acA@#a		ZacA@#; ;	%C		n	acQ@Q@X,a
@JLEXCOM	@HCQX	Czac Q@Z		QX: :	$QY	%QZac"Q@Q@X,a
@JLEXCOM		!}!!(!,!: :!$$JLEXCOM!#SKIPW0!#GETFO0! #GETDE0!#SYNERR!#DELET0!#RMTABL!"#LOOKUP!&#DSFREE !(#ENTER 
 
"%J&0&&& DGETS05 5'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM	: :,awyINCOM ,aKINCOM 	A
	",akyINCOM 
acA@"	"%9 9	%	@	"%	%	@!	"QS	A#,awyINCOM 9 9,aKINCOM 	A
	",akyINCOM 1-acA@"2	"%<<	%;	@: :=	"%EE	%D	@?F	"%NN	%M	@HO	"%VQ6 6	%YUX	token too long. Z		$#	@acC@[Ye	"t#QS	(#@< <,awyINCOM ,aKINCOM 	A
	",akyINCOM {wacA@"|7k	@ t#QS9 9acA@"			$	"	"QS	@ u
QS	"$	!
!$!0!9!A!H9 9!Z!_!a!z!	!$INCOM !$yINCOM ! #REFIL0!"#SYNERR!$#PUTBA0
 
"%*&0&"$ GETFO09 9		acA@QS	@ QS	define formal parameters must be identifiers. 
acQ@
	"%; ;*acC@acQ	@		#	)	commas must separate define formal parameters.5acQ@
; ;Q@
Qk	@QKQacQ@
Q@Q	@acQ@
	"%j	%miacC@6ac: :Q	@		#	l	"C
		#	!}!~!!)!,!!#SKIPW0! #MKTABL!#SYNERR!#RMTABL!#DELET0! #ENTER 
 
"%v$0&$ SKIPW0* *	acQ	@	"%		%	#	!
! !#DGETS0
 
"%($0&B(* GETDE09 9'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM	@ "	#: :	A$@ 	QacQ@`	%	#C	("@	#C	"@H"A9 9	#C		#%	#C		#,(!	#C		#3	#C		#; ;:6/	Missing right paren or EOF in define text.>acC@? acQ@`Q@QK	A
9 9acQ@Q@\Q	@	@HCb			Q`Q]Qa	@ Qbm=	%%}>	&L9 9	"0	%%Yx	
definition too long.acQ@`	'$: :	C
acC@X acQ@`A@Q@A@$	'$$
%QK	A
acQ	@7; ;acQ@	(	!B!B! !!!"!'B!B!B!#DGETS0+ +!#LOOKUP! #LENGTH!&#SDUPL !#SYNERR!#DELET0!"#SCOPY !$#RMTABL
 
"%R*0&R$ GETAC0< <	acQ@	"%		%	@ 	QSacQ@			AQSQk	@QK9 9	%	@acQ@	"QK	@H#acQ@	t#QS	"BC		3	To9 9o many actual parameters specified. 6acC@7		QS		! ! !(R!#DGETS0 !#COLLE0!#SDUPL !#PUTBC0!#SYNERR
 
"%$0&9 * COLLE09 9'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM	A"	#9 9	@ $,awyINCOM ,aKINCOM 	A
	%,akyINCOM acA@%         %&9 9	#C	($@	#C	$@H$A(#	#C		#.	#; ;	C		#51*	#C		#<	#C		#C?8	#C	$A	J; ;)MF	unbalanced paren or EOF in define actual parameter list.PacC@QN	&%v: :P	'L+{|}9 ~GO	                                                                                                    efine actual parameter too long. : :	"@HAD%QS	("@	$"	@acC@q!'	"@HAD@ QS	%C		(	29 9		(	!~!9! !!!"!'!,9!9!$INCOM !$yINCOM  !#REFIL0!#SYNERR
 
"%.*0&9& DELET0; ;'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM	A"#: :	(#@	#@HAD	QGQQK	A
	%,aKkMISCOM	A
	"@H$acQ	@	t$9 9QS	"@H$#@HADQK	t$QS#	("@         "@HAD@ QS		!_9! $kMISCOM!#MAPDN 
 
"%.&0&