9v( SYNERR9 9'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM"*5i9 9" (*s): "
<NEWLINE>"&<EOF>",*s*s.*n9 9"4*s'*s' *s.*n"B*s'*s'*n*10x*s.*n	A"#	(#@	#: :,agTINCOM 	@t"QGiQP	t#,aGVyINCOM QR		"$acXQ	@PA@$a@Q	@R	": :	"
	t"QGiQP		"$acXQ	@PA@$a@,a
@ZLMISCOM	""ac\Q	@A@Q@6 6A@	%ac^,a
@`MISCOM	&A,aKbILEXCOM	Cacd,a
@`MISCOMac^7 7,a
@`MISCOM	&P,aKbILEXCOM	Cacfa@,a
@`MISCOMA@	&_: :,aKbILEXCOM	BCacfa@&,a
@`MISCOMA@	&n,awhHLEXCOM,aKjLEXCOM	A: :acf,a
@jLEXCOM,a
@`MISCOMA@	&~xiZK	&AaclA@a@,Q@jQ@7 7
	"&%%	@aclA@a@4Q@j,a
@`MISCOMQ@aclA@a@BQ@j: :,a
@`MISCOMQ@(	@ ,aS`MISCOM		!q9!I9!f!
9!.9!7 7H9!9!r$LEXCOM!p$HLEXCOM!j$ILEXCOM!^$yINCOM !\$INCOM !b$LMISCOM!h( ($MISCOM!`#ENCODE!n#CTOC!d#PTOC!f#LENGTH!l#GETLO0!t#PRINT 
 
"%|(0&" FATAL03 3	
program terminated. acQ	@acacC@!#SYNERR!#CLEAN0!#ERROR 
 
"%&"0&$ SDUPL 9 9'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM	ac9 9Q	@	B"acA@"	#	acQ	@A@,a
@DS$MEMA@#	#	!!$DS$MEM!                                                                   LENGTH!#DSGET !#SCOPY 
 
"%($0&F&" ENTET07 7'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOMac9 9,a
@LEXCOMQ@	@HC		QacQ@Qac,a
@LEXCOMQ@,a
@JLEXCOM: :	acQ@A@,a
@KLEXCOM	acQ@A@,a
@LEXCOMA@,aSHLEXCOM	id6 6entifier cannot be made unique. /ac C@0.		!!!F!$LEXCOM!"2 2$HLEXCOM!$JLEXCOM!$KLEXCOM!#MAKEU0! #SCOPY !#SDUPL !#ENTER !$#SYNERR
 
"%n"0&x
& MAKEU0: :'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM	A": :	("@	"%	@@HADQK	A
	%	%	@QS	"@HADQK; ;QS	("@#	"%	@@HAD	QS$(	@ uQS		u	QSacQ	@9 9A@#,a
@KLEXCOM	@HC		"	"@H"E	"%NL	@HADQK	%VV9 9	%UW	BQS	("]	("@^	"%	@@HAD	QS_cMXFk	": :	@HC	@ $	p8B	A$	!x!!x! x!0!Ax!Z !a!zx!$KLEXCOM!#LOOKUP
 
"%,&0&

$ LABGEN5 5'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM	! !,aKHMISCOM	"Q[,aSHMISCOM	"	!$HMISCOM
 
"%($0&1" VARGEN9 9'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM	ac9 9A@Q	@	@HCacQ	@A@,a
@KLEXCOM		in vargen:  cannot generate new vari7 7able. acC@	@ QS		!1!$KLEXCOM!#MAKEU0!#ENTER !#SYNERR
 
"%&"0&" SAVEM07 7'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOMac5 5,a
@LEXCOMA@,a
@MISCOMA@ac,a
@LMISCOM		!!$LEXCOM! $MISCOM!$LMISCOM!#SCOPY !#GETLO0
 
"%""0&" GETLO05 5'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM	: :,aKLLEXCOM	Aac,a
@LEXCOMA@Q	@A@ac,a
@LLEXCOMA@Q	@# #A@		!!$LEXCOM!$LLEXCOM!#SCOPY 
 
"%&"0&