jB.0 GETSYM9 9'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM"0129 93456789abcdef"".AND."(.OR."..EQ."4.LE.8 8":.LT."@.GE."F.GT."L.NE."R.NOT.	@ ; ;,aSXHLEXCOM,aSZLEXCOM,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM 
ac`7 7A@"	A#	"$	@ %,akXHLEXCOM	@",awXHLEXCOM,aSbLEXCOM: :,akXHLEXCOM	@",awXHLEXCOM,aSbLEXCOM	A%%0	"%77	%6	@9 98	"%@@	%?	@A	"%H	%LL	%K	@&M	"%9 9T11,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM ^Zac`A@"_; ;TacdA@"	@ ,awXHLEXCOM,aSZLEXCOM,aKfkMISCOM	A
	@ %ach,a
@ZLEXCOM; ;A@q	@ ,aSjLLEXCOM,aKlPRCCOM	&	&@H&	&A	t&,aGnPRCCOMQQK9 9	A
acp,a
@ZLEXCOMQ@Q	@	@HCacr,a
@ZLEXCOMA@,a
@jLLEXCOMA@9 9acr,a
@tDS$MEMQ@,a
@ZLEXCOMA@,aSXHLEXCOM			,aSvILEXCOM8 8,aKxfPRCCOM	A
acp,a
@ZLEXCOMQ@,a
@xfPRCCOM	@HC9Q,aSzePRCCOM		
: :,aSvILEXCOM4Dacp,a
@ZLEXCOMQ@,a
@|JLEXCOM	A,aKXHLEXCOM	%	@9 9	%%`Z,aKXHLEXCOM	CC',aK~LEXCOM	CC'A_kacr,a
@ZLEXCOMA@; ;,a
@jLLEXCOMA@acl			,aSvILEXCOMLVQ	(Q,aSvILEXCOM|acr< <,a
@ZLEXCOMA@,a
@jLLEXCOMA@acr,a
@tDS$MEMQ@,a
@ZLEXCOMA@,aSXHLEXCOM: :			,aSvILEXCOM
acQ@	in getsym/id:  can't happen (bad symtype).%	(L9 9 acC@&	"CE'	"CEA	'	A	",awXHLEXCOM,aSZLEXCOM,akXHLEXCOM9 9	@,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM b^ac`A@"cFP	< <Radix must be between 2 and 16. i	@ ,awXHLEXCOM,aSZLEXCOM	"C	A&ac,a
@ZLEXCOM: :A@&		)CA')@HCD'AacC@j		)	@Q,aw\yINCOM ,aK^INCOM 	A
	": :,ak\yINCOM '#ac`A@"(	"%22	%1	@&3ac
A@"	*: :	aca@A@*	@H&7	&A	$)GIJK	)MQ;	AQ	&MQ: :QLacQ@,a
@ZLEXCOMA@,aSXHLEXCOMacdA@"		,aSvILEXCOM; ;		,aSvILEXCOM	"+,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM {wac`A@"; ;|	"+C	Quoted literal too long.,akXHLEXCOM	@	,agXHLEXCOM	@ac; ;C@	Unmatched quote. 	",awXHLEXCOM,aSbLEXCOM	                                                                   
acC@!0r9 95	@ ,awXHLEXCOM,aSZLEXCOM,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM E; ;Aac`A@"F		#	"%Rp	%Up	"%ZZ	%Y	@acA@"< <[acdA@"al,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM plac`: :A@"q	"C		,aSvILEXCOMy	"C		,aSvILEXCOMacdA@"7 7	acra@"A@,a
@ZLEXCOMA@,aSXHLEXCOM		,aSvILEXCOM}f,aw\yINCOM 9 9,aK^INCOM 	A
	",ak\yINCOM #ac`A@"$	"C		,aSvILEXCOM8 8,	"C		,aSvILEXCOM4acdA@"acra@(A@,a
@ZLEXCOMA@; ;,aSXHLEXCOM		,aSvILEXCOM80,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM 5 5VRac`A@"W	"Cacra@.A@,a
@ZLEXCOMA@,aSXHLEXCOM		5 5,aSvILEXCOM_acdA@"		,aSZLEXCOM	@ ,aSLEXCOM	A,aSXHLEXCOM		; ;,aSvILEXCOMoL,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM 
ac`A@"; ;	"C		,aSvILEXCOM	acra@4A@,a
@ZLEXCOMA@,aSXHLEXCOMacd9 9A@"acra@:A@,a
@ZLEXCOMA@,aSXHLEXCOM		,aSvILEXCOM#,aw\yINCOM 9 9,aK^INCOM 	A
	",ak\yINCOM A=ac`A@"B	"C		,aSvILEXCOM8 8	acra@@A@,a
@ZLEXCOMA@,aSXHLEXCOMJ		 ,aSvILEXCOM	acra@FA@8 8,a
@ZLEXCOMA@,aSXHLEXCOMacdA@"Z7,aw\yINCOM ,aK^INCOM 	A
	"< <,ak\yINCOM xtac`A@"y	"C		!,aSvILEXCOM	acra@LA@,a
@ZLEXCOM: :A@,aSXHLEXCOM		",aSvILEXCOM	acra@RA@,a
@ZLEXCOMA@,aSXHLEXCOM9 9acdA@"           n	",aSvILEXCOM,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM ; ;2.ac`A@"3	"%<,aKvILEXCOM,aSZLEXCOM	@ ,aSLEXCOM	A,aSXHLEXCOM5 5acdA@";,aKvILEXCOM	,		#,aSvILEXCOM		$,aSvILEXCOMR		%9 9,aSvILEXCOMV		&,aSvILEXCOMZ		',aSvILEXCOM^		(,aSvILEXCOMbN	,-5 5	L_mnoWOpSs[	,%){cufJ%	",aSvILEXCOM: :,aSZLEXCOM	@ ,aSLEXCOM	A,aSXHLEXCOMacdA@{	$*.L^
m&g: :8m&&|&&FFFFFFFFFF)M8*.: :8/JK&: :8LN; ;Ojol	",aSvILEXCOM,aSZLEXCOM	@ ,aSLEXCOM	A,aSXHLEXCOME$; ;y		M	"+C,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM 	ac`A@"; ;
|	"/,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM ac`A@"9 9	",C,aw\yINCOM ,aK^INCOM 	A
	",ak\yINCOM /+ac`A@"09 9	"                                                                   &%	"%+=	%           @	%C,aw\yINCOM ,aK^INCOM 	A
	"; ;,ak\yINCOM MIac`A@"N	"                                                                   DC	/%,\D	%_W	"%+c: :|c	#LNd!!j!j!j!        
!+ !*!!"9 9!,#!$!&!'j!0j!9!=!Aj!Hj!Z!)^!_9 9!aj!r!z!|j!h!i!j! k!l!m!!n!"o!p5 5!	!!
!!#!$!%!&!'!(!! j!9 9$LEXCOM!$LEXCOM!@$LEXCOM!,$LEXCOM!$LLEXCOM!$HLEXCOM!$$ILEXCOM!*$JLEXCOM!9 9$INCOM !
$yINCOM !"$DS$MEM!$PRCCOM!$PRCCOM!($ePRCCOM!&$fPRCCOM!$kMISCOM!:: :#INDEX !4#CTOI!8#MAPDN !#LOOKUP! #SCOPY !#REFIL0!#PUTBA0!#MAPSTR!.#ENTET0!0#INVOK0 !2#FATAL0!6#SYNERR!<#LTOC!>#CONVE0
 
"%800&.H2( CONVE09 9'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM	QK9 9	",aKHLEXCOM	@HC,aKLEXCOM	#acA@#,a
@LEXCOMA@,aSHLEXCOM; ;		,aSILEXCOM		Only one character allowed in a character constant. acC@9 9ac,a
@LEXCOM	A@Q@A@	@ $A%	(%@I	Packed string constant too long.L: :	t%QK	A
	($@	$$	@acC@Maf	t%QK	C		t$,aSLEXCOM	($: :	@r	t%QK	t$,aSLEXCOMJl		t$,aSLEXCOM	@ ,aSLEXCOM	$B,aSHLEXCOM7 7		,aSILEXCOM:	EOS-terminated string not allowed in this context.,aK 2OBUFC0	A&6 6,aK"3OBUFC0	A&AacC@		2ac$Q@acQ@A@,a
@LEXCOMA@9 9,aSHLEXCOM		,aSILEXCOM	Varying string not allowed in this context. L,aK 2OBUFC09 9	A&,aK"3OBUFC0	A&AacC@M		lac$Q@acQ@A@,a
@LEXCOMA@9 9,aSHLEXCOM		,aSILEXCOMK	"%
		'L;L9 9	"
'L; ()+L,	Unrecognizab9 9le string format indicator. .acC@/		!H!.!@!C!G!H!	5 5O!
oH!!!H!($LEXCOM!$LEXCOM!*$LEXCOM!$HLEXCOM!"+ +$ILEXCOM!,$2OBUFC0!.$3OBUFC0! #ITOC!&#SCOPY !$#SYNERR!0#VARGEN
 
"%t(0&="" REFIL05 5'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM	6 6,aKINCOM 	%		QS	@ ,aSINCOM 		,aSyINCOM 		,awINCOM : :,aG~INCOM Qac,a
@INCOM Q	@	%,awINCOM ,akyINCOM #: :,awINCOM ,aG~INCOM 	QacQ	@,aKINCOM 	@H,aSINCOM $,aKINCOM 7 7QS		,aSyINCOM 		!=!=!!     =!$INCOM !$yINCOM !   $yINCOM !$INCOM !$~INCOM !#GETLIN! #CLOSE 
 
"%("0&&" PUTBA05 5'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM	9 9,aKyINCOM 	@H,aSyINCOM 	@HCQK,awyINCOM ,aSINCOM 	too many c. .haracters pushed back.acC@                           		!$INCOM !$yINCOM !#FATAL0
 
"%&"0&$ PUTBC09 9'MISCOMgPRCCOMSELGENCODEG0OUTFILa(DS$MEM5OBUFC0LOOPC0INCOM LEXCOM	ac8 8Q	@	"	"@H"	"A	@HADQGQacQ	@		!#LENGTH!#PUTBA0
 
"%*$0&$ PUTBB0/ /	acQ	@Q@A@	"@ t"	QSacQ@		!f!#ITOC!#PUTBC0
 
"%$0&