c $9 9acA@Q@A@	BCac
Q	%	acQ	"ac: :Q@acQ@ac#	"#L4-0123456$7: :89:;<?@ABCDEFGHIJKMPQRST: :UV$WYZ[\ac&ac!c!f!-!@!#GETARG !#START0!#JOBST0!#CANCE0!#MODIF0!#SWT 
 
"%
$0&:0 START09 9"=varsdir=/=user=.=pid=.*i"*$$ JOB *s*n"6swt -: :*i*n"@*s*n"F
copyout*n"P=installation="`*9 9
n*n# *s*n"l# Batch job scheduled on *s" at *s.9 9*n"*n*n*n"*s*n" stop*n"(	JOB '*s'"29 9 -ACCT '*s'"> -HOME '*s'"J
 -HOME *s"T -QUEU9 9E *s"` -CPTIME *i"l -CPTIME NONE"z	 -ETIME *9 9i" -ETIME NONE" -PRIORITY *i"" -RESTART Y: :ES"0 -FUNIT *i"<*n"@	=GaTech="Jyes"ND9 9ELETE '*s'*n"\%COMO -NTTY*nDELETE '*s'*nCOMO -TTY*n9 9		"@ Q2QQ~Q	#$%&'A()	()@	"@DCB*acA@)Q@fA@	B: :	CCA	*	AQf	%
-acQ@2	A
		"2acQ@fA@Q@2A@,; ;Qh	A
		"CQg	+acQ@2	A
		"P	()@acA@)Q@2A@: :	BC		"_	@ (b	A&!eacA@)Q@A@"hacA@)Q@A@"qac
: :8A@)A@#A@"zac
A@)A@$A@"ac
A@)A@%A@"acA@)Q@~A@"ac
9 9A@)A@'A@"J	+,L5"r./0i35K68c9: :8f;{?ABCDEFGHIJKrLNOPiSUKVX9 9cYf[{_		"'F?'	"%hacg	can't create batch fil9 9e.jacQ@L	-acQ@dA@a@A@-acQ@dA@	.CacC@k	'A: :		'0acA@Q@LacA@.a@*Q@LacQ@dQ@LA@acQ@LQ@dacA@.9 9a@6A@'acQ@LacA@.a@@Q@L	(@HCacA@.a@FL	ac a@PA@	/; ;	C	@ QL\	ac"Q@LA@/	)BC	@ QLj	@ t)QSKnac$A@/: :`6acA@.a@`Q@LacA@Q@LacA@.a@lQ@LacA@	Q@LacA@.a@Q@L9 9acA@.a@acQ@2	Aac&A@
A@.&acA@.a@Q@2-acA@.9 9a@ ac$A@.acA@a@(Q@dacQ@	A
acA@a@2Q@MacQ@	A
: :acQ@Q@Lac(Q@LA@	A
acA@a@>Q@LiacA@a@JQ@Lr9 9[acQ@~	A
acA@a@TQ@~	#AacA@a@`A@#	#A9 9	acA@a@l	$AacA@a@zA@$ 	$AacA@a@,)	%A: :acA@a@A@%5	&@HCacA@a@"A	'%L	AKacA@a@09 9A@'MacA@a@<aca@@Q@LA@	%gac*Q@La@J	@HCfacA@9 9a@NQ@doacA@a@\Q@dx		!u!
v!}!~!!	!< <!!!f! !-!@!#GETARG!.#OPEN! #CREATE!0#GETLIN9 9!#GETSEQ!(#EXPAND!8#EQUAL !6#INDEX !#LENGTH!#SCOPY !#GRABS0!#GRABN0!#USAGE0!. .#ENCODE!"#ERROR !$#DATE!&#PRINT !*#MKTR$ !,#GETPA0!2#CLOSE !4#FCOPY 
 
"%z00&" GETPA03 3hSWT$CM	ac,a
@LSWT$CM	A@Q	@A@		!!$LSWT$CM!#SCOPY 
 
"%&"0&`D( GETSEQ9 9"=varsdir=/.batch_seq"&*i*n	A"	("@	"%	@: :	ac,a@A@	#%ac.A@		$"ac0a@A@	#C9 9ac2a@'	A$	ac4Q@A@#	BC	A$7	A"	ac6Q@A@"	$: ::.ac8A@#ac:A@#	$B%ac<A@#a@&A@%ac>A@#	$&	!}^!!; ;^t!8#GETLIN!4#CREATE!0#OPEN!:#CTOI!2#SLEEP$!6#CANT!<#REWIND!>#TRUNC !@#PRINT  !B#CLOSE 
 
"%(0&$" GRABS0< <	acQ	@	A
		QSQk	@acQ	@Q	@A@	BC		QSQK+ +	C		QS		!}$!f!-!#GETARG!#LENGTH
 
"%,"0&:$ GRABN0: :	QK	A
		QSQK	B"acA@"Q@
A@	#%	A
Q
	%; ;		QS	A#acQ@
A@#QS	t#QK		A
		QS2Qk$ $	@#		!}!:!f!-!#GETARG!#CTOI
 
"%$0&<" USAGE09 9"%Usage: batch -(s|d)[a|t] [<jobname>]"6       batc9 9h -(c|a|r) <jobname>"V       batch -m <jobname> {<o9 9	ptions>}"|)       batch [[-k] <command>] {<options>}9 9"&(    <options> ::= -a <acct> | -r | -n |"N    9 93    -h <home dir> | -t <cpu time> | -e <elapsed> |": :2        -p <priority> | -q <queue>    | -f <unit>ac85 5'a@ac8a@6ac8a@Vac8a@|ac8a@&ac8a@Nac:a@!8#REMARK!:#ERROR 
 
"%""0&jn" JOBST09 9"JOB *s -STATUS" JOB *s -DISPLAY"0in job_statu< <s: can't happen"L ALL"R TODAY		acZA@Q@	uQG9 9	Qjac\Q	@j	Cac^A@a@Q@	uQGQjac\Q	@j	Cac^: :A@a@ Q@'ac`a@00	uQK	Aac^A@a@L9	uQGQj: :ac\Q	@j	CL	uQGQjac\Q	@j	Cac^A@a@RYacb`: :M@	acdA@A@		!uj!!j!
j!aj!dj!s!t' 'j!d#MAPDN !b#GETJO0!f#PRINT !h#ERROR !j#USAGE0!l#PUTCH 
 
"%"0&Uf" CANCE09 9"JOB *s "	-ABORT*n""
-CANCEL*n",-RESTART*n; ;"8in cancel_job: can't happen	acTA@Q@acVQ@	A	< <acXacZA@a@Q@	uQGQjac\Q	@j	CacZA@a@"	uQG9 9	Qjac\Q	@j	CacZA@a@"5	uQGQjac\Q	@j	CacZA@: :a@,Hac^a@8O<)		!uU!!U!aU!cU!rU!\# ##LENGTH!b#MAPDN !Z#GETJO0!^#USAGE0!`#PRINT !d#ERROR 
 
"%"0&" MODIF0) )	Sorry, job modification not implemented.acC@		!#ERROR 
 
"%""0&>$ GETJO0; ;	acQ	@Q@A@	BC	@ QSQ	Cac	A"acQ@9 9A@"	t"QK	A		QSacQ@A@Q	@A@$acQ@A@Q	@A@2 22		!!!f!#!-!#GETARG!#USAGE0!#CTOI!#SCOPY 
 
"%$0&