v,: :"4040/10000"2030/120000!!!!}9 9"(5[-abdfnpvu] [-o<req str>] -s<ign> -m<ign> -l<ign>-i<i9 9gn> -t<ign>"jfile ..run*n"xcopy ..run *s -delet9 9e -nq*n"cname ..run *s*n"&.b"*.o".lo *9 9s*n"6*s*n"<vswtlb"Dlo *s*n"L.o"P.m9 9"Tma *s*n"\ma -undefined*n"l.o"p.m"t=9 9cm_loc="~	=tp_loc="sy swt$cm *s*nsy swt$tp *s*n9 9"&c$main".lo *s*n"6lo lib>ccmain*n"Fli 9 9	pl1glb*n"Rli paslib*n"^ciolib"flo *s*n"n9 9	vswtmath"xlo *s*n"vshlib"lo *s*n"li : :cclib*n"vswtlb"$lo *s*nli*n"0dynt -all*n9 9	ac<a@(Q@	C	A"	can't open temporary file.ac>A@	   C: :ac@C@!	A#,acBA@acDA@A@acFA@A@acDA@a@jacHQ@TA@; ;	A
acDA@a@xQ@TFacDA@a@Q@TO	acJA@Q(	AD	QGQ:acL: :Q	@:acN(Q	A	A$l	A%	(%@racPA@%Q@A@	%	9 9Q	%
Q(	ADQK	AacRQ@a@&Q@na@*Q	%
Q4Q(: :	ADQGQ:acTQ@nQ	@:A@	BQ4Q4	A&acVQ@Q@nacDA@a@.9 9Q@nQ
	A
		"FacXQ@		'	%B(acPA@(Q@A@; ;	%	_Q	%
d^c		"Id	(%@acDA@a@6Q@	%B(acPA@(9 9Q@A@	%	Q	%
acZa@<A@Q@A@	(%@         	&; ;3ac\Q@Q@nacDA@a@DQ@nr	%B(acPA@(Q@A@	%	4Q	%
9; ;38	@ Q9	(%@=Q	AQ(	ADQGQ:acRQ	@:a@LQ@na@P: :acVQ@nQ@nC	acVQ@Q@n[acDA@a@TQ@n%		$oj	A)n: :P	'*Lkys&z}~Qo		"grJBsQ	A; ;		)qQ	A
acDA@a@\Q	A
Q(	ADQGQ:acRQ	@:: :a@lQ@na@pacVQ@nQ@nacDA@A@Q@nQ(	ADQGQ:acVQ	@:Q@T: :mac^a@tQ@HA@	CacZa@A@Q@HA@Tac^a@~Q@hA@	C9 9acZa@A@Q@hA@iacDA@a@Q@HQ@hQ	A
		Aac\9 9a@&Q@nacDA@a@.Q@n	A  Q	A
		AacDA@a@6	A  9 9		AQ	A
acDA@a@F,Q	A
acDA@a@R6Q	A
; ;9ac\a@^Q@nacDA@a@fQ@nac\a@nQ@nacDA@a@xQ@nac\a@Q@nacDA@9 9a@Q@n@Q	A
acDA@a@nac\a@Q@nacDA@a@$Q@nQ	A
9 9acDA@a@0(	A		%
acJA@	Usage: bind -{a|b|f|n|p} [-o9 97 <output file>].          { <binary file> | -m [<map opt>] | -s <command>.             | -l [<library>] | -i |: : -t.ac`C@ac`C@/ac`C@LacbA@acN%	&L4r	"LJ9 9hx~	$LpnI)	)Lr!u!}!	!9 9!!!! !f!
-!>!H!h!        h: :2bind*n. 9ma *s*n.!b#GETARG!j#MAPDN !N#PARSCL!Z#INDEX !P#MKTEMP!f#CTOC!p#EXPAND< <!R#ERROR !T#REWIND!V#PRINT !X#FCOPY !\#RMTEMP!^#REMOVE!`#SWT !d#SUFFIX!h#MKTREE!l#SCOPY  !n#MAKEL0!r#REMARK!t#SETERR
 
"%h,0&>$ MKTREE; ;	acQ	@Q@A@acQ@A@	AacQ@A@	AacQ@A@Q	@A@: :				QS	uQGQlacQ@Q	@l	@D"@HAD	QS	@ t"QS		!>!f% %!'!/!\!#MKTR$ !#INDEX !#EXPAND!#SCOPY 
 
"%$0&"" MAKEL0; ;"=newlib=/*s	acQ@A@a@Q	@acQ@Q	@		!f!#ENCODE ! #MKTREE
 
"%"0&B$ SUFFIX9 9	acQ	@	A"acQ	@Q@A@"acQ@Q	@	@HCacQ@	A"acQ	@: :Q	@A@"acQ	@A@Q	@A@&acQ	@	B"acQ	@	A@Q	@A@"		% %!B!#LENGTH!#EQUAL !#STAKE !#SDROP !#SCOPY 
 
"%$0&