<&9 9"*s: too many object files*n!",*,#s"2.rfl; ;"8.sfl"> *s: not found in object files*nac^A@: :	A"	("@ac`A@"Q@A@	%		$"acbA@a@Q@acdA@: :	acfQ@A@	t"QS#	CachQ@/	"@H#A	acj9aclA@: :	$A"t"QG#Q.acnQ	@.A@$	A"$#TBBacpA@	a@,A@
Q@	%aacr: :8Q@A@actA@A@A@actA@A@A@pacvQ@"acxQ@Q@"A@$y: :g	aczQ@a@2	%haczQ@a@8	%qac|Q@Q@"A@$	%$zacb: :	A@a@>Q@T`actA@A@A@acj!q!u!	v!}!!9 9!!7!
7!
!!7!7vm!n#GETARG!~#INPUT : :!
#LOOKUP!#EQUAL !t#OPEN!z#MKTABL!l#DSINIT!p#PRINT !r#ERROR !v#CANT!x#SWT !|#LOADT0 !#MAPSTR!#WRBIN !#OUTPU0!#DELET0
 
"%V&0&$ LOADT0: :	acQ	@Q@Q@lA@"	%acQ	@Q@Q@lA@"Q	@		!! #GETMO0!#ENTER0
 
"%$0&
( GETMO09 9"&bad object file (block size mismatch)"6.main"<9 9.data"Bextraneous END block"Xbad object file (u9 9nrecognized block type)"bad object file (premature9 9 EOF)""&bad object file (block size mismatch)"Hb9 9 ad object file (bad block type)	acjQ	@QSaclQ	@Q@: :A@	"A
	%    		#		"AQ	B("C!	acnQ	@a@; ;"Q	A4$acpQ@	@HC	@ %AQS	acrQ@Q	@A@	Aacta@6A@: :Q	@A@aclQ	@Q@A@	"(%XaclQ	@Q@A@	"(%@YQ	A4%k9 9	CacrQ@Q	@A@	@HCmjxZyCQ	A4%	A&	%: :Q[	QS			#	4    acta@<A@Q	@A@		&		#	acnQ	@a@B-	$: :	'L.acnQ	@a@X#	AQS	aclQ	@Q@A@	"acn9 9Q	@a@@acnQ	@a@"GacnQ	@a@HN?	"A
@	AA	%^AQ	B(9 9	"CHQ	A4%j	%	mi	%plOoUQk		@"A
Q	A4%}9 9v6|~	&L!~!!!!!	!	
4 4!!f!!v#RDBIN !z#HASPR0!|#GETNA0!t#MARKF !x#ERR !~#SCOPY 
 
"%4(0&
!& HASPR0: :	QK	B("A#	t#QK	B(B##	#$"         t#QK	B`C	A$	 	@ $	!
 
"%*&0&y( GETNA0; ;	QK	B("A#	t#QK	B(B##	#$"         t#QK	B`$	#@DADQGQ
9 9	t#QK	B(C?@HacQ	@	%acQ	@
A@Q	@A@%	#BADQGQ
	t#QK	B(; ;	C?BacQ	@	%acQ	@
A@Q	@A@%5R	acQ	@A@	A&		$@H'L9 9	$'Ljklmnopqr6s	@ &	!y! ! !#PTOC!#F$MI11!#MAPSTR
 
"%4(0&="$ ENTER09 9DS$MEM	acA@	"QK		t",aSDS$MEMQK,aSDS$MEMQK,aSDS$MEM	u: :QK	t",aSDS$MEM	@ ,aSDS$MEMacQ	@Q@Q	@	@HCQ         AD",aSDS$MEM7 7&	"Q-	"QacQ	@Q@Q	@		!=!=!$DS$MEM!- -$DS$MEM!$DS$MEM!$DS$MEM!$DS$MEM!#LOOKUP!#DSGET ! #ENTER 
 
"%6$0&

&" ERR : :"	*s: *s*n	$acQ	@Q@A@acA@a@Q@Q	@acA@ac !q$ $!4!h!#GFNAM$! #PRINT !"#SETERR!$#SWT 
 
"%\"0&H>& OUTPU0< <DS$MEM"error copying object module	QK	"t",aG,DS$MEMQ< <,aG.DS$MEMQac0Q	@Q	@A@	A#	(#@	#t",ag2DS$MEM	@,aG.DS$MEM9 9Qac4Q	@Q@A@	$A	%2.1	t",aG.DS$MEMQac6Q	@a@: :2ac8A@Q@A@$		!u!!H!H!0$DS$MEM!6$DS$MEM!2 $DS$MEM!8#RDBIN !4#SEEKF !:#ERR !<#WRBIN 
 
"%.&0&$ DELET0: :DS$MEM	QK	"t",aKDS$MEM	AacQ	@Q	@	t",aKDS$MEMQSac" "	Q	@Q	@Q	@		!$DS$MEM!#DELETE!#ENTER 
 
"%.$0&IB$ RDBIN ; ;"'block size (*i) exceeds buffer space*n		"	ac8A@#A@: :Q	@	%	"		#QgQ_	MQ
ac:A@a@A@#QK	#: :	@Q
&ac8Q	@A@#Q	@	$#54Q
	ABac<Q@
Q	@A@	%6 6E9D	#"!q!~!I!I!<#READF !@#SEEKF !>#PRINT 
 
"%0$0& $ WRBIN ; ;		"acQ	@A@Q	@	@HCacQ	@Q	@Q	@Q_	C	"			" !}!~ ! !#WRITEF
 
"%.$0&