]&": :	-Your name: *,,`s. Name of problem software: *,,`s.Name of example file (<CR> if none): *s.acA@9 9C@Q@v	%9acA@C@
Q@	%D8acA@C@Q@	%OCN9 9	acA@acO	*s at *s*2n.By: *s (*s)*n.Re: *s*n. Ex: *s*n. VacA@Q@facA@; ;9Q@lacA@Q@\acA@C@WQ@fQ@lacA@C@]Q@vQ@\acA@C@dQ@Q9 9	A
acA@C@iQ@	"Description of bug (end with ctrl\c in column 1). *nDescription:*2n.9 9(acC@)acA@C@BacA@A@ac!u!v!]!!!/ /]!h!#INPUT !#SETERR!#SWT !#DATE! #PRINT !"#REMARK!$#FCOPY 
 
"% "0&