J$9 9gCCK2C "not referenced*n	@ ,aS"                                                   CCK2C 	A,aS$fCCK2C 	cck2: bogus ; ;line: *s. ac&,a
@(CCK2C A@A@	%,aK(CCK2C 	%"ac*A@C@8 8,a
@(CCK2C !		,aS,CCK2C ac.,a
@(CCK2C ,a
@,CCK2C ,a
@0CCK2C ac.< <,a
@(CCK2C ,a
@,CCK2C Q@ac.,a
@(CCK2C ,a
@,CCK2C ,a
@2MCCK2C ac.,a
@(CCK2C : :,a
@,CCK2C ,a
@4gCCK2C Q	"ac6ac8TQ	"#LR^_`U; ;a	cck2: unrecognized flag: *s*n cac*A@C@dQ@W,aK$fCCK2C 	Aac:9 9,a
@"                                                   CCK2C ,a
@<                                                                                                                               CCK2C ,a
@>                         CCK2C 	ac*A@a@ac@!q!u!v!7 7!!#!c!!0$CCK2C !4$CCK2C !8$CCK2C !<$gCCK2C !:: :$MCCK2C !*$                                                   CCK2C !F$                         CCK2C !D$                                                                                                                               CCK2C !,$fCCK2C !.#GETLIN!2#PRINT !6#GETWRD!>#FNDEF  !@#FNCALL!B#PUTWH0!H#SWT 
 
"%
$0&r$ FNDEF 9 9gCCK2C "defined twice*n" not referenced*n"2too m9 9any arguments*nacH,a
@JCCK2C ,a
@L                                                   CCK2C 	@HCacN,a
@JCCK2C 7 7,a
@PMCCK2C ,a
@RgCCK2C 	acTA@a@		,aKVfCCK2C 	AacN,a
@L                                                   CCK2C 8 8,a
@X                                                                                                                               CCK2C ,a
@Z                         CCK2C 	acTA@a@ ac\,a
@JCCK2C ,a
@L                                                   CCK2C A@ac\8 8,a
@RgCCK2C ,a
@Z                         CCK2C A@ac\,a
@PMCCK2C ,a
@X                                                                                                                               CCK2C A@	@ ,aSVfCCK2C 	A9 9,aS^eCCK2C ,ak^eCCK2C 	@H,aK^eCCK2C 	%	@,aw`CCK2C ,aKbCCK2C 	A
: :O	%ZVacd,a
@fCCK2C ,a
@`CCK2C Q@,aK^eCCK2C 	C<"t",aGhWCCK2C Qf; ;	"C?AD,aGjGCCK2C QhaclQ@Q	@fQ	@hIY,aw`CCK2C ,aKbCCK2C 	A
	%9 9acN,a
@JCCK2C ,a
@PMCCK2C ,a
@RgCCK2C 	acTA@a@2		!u! !5 5f!
!f$CCK2C !j$CCK2C !d$CCK2C !N$CCK2C !V$gCCK2C !T$MCCK2C !P< <$                                                   CCK2C !^$                         CCK2C !\$                                                                                                                               CCK2C !b$eCCK2C !Z$fCCK2C !l$WCCK2C !n$GCCK2C !L#EQUAL !R#PUTWH0 !X#PRINT !`#CTOC!h#GETWRD!p#CVTMO0
 
"%$0&c& FNCALL9 9gCCK2C "not defined*n"in call ('*s' *s), "2retu9 9	rn value"@arg *i"H types don't agree (warning)*9 9n"hin call ('*s' *s), "|return value"
arg *9 9i"# type mismatch -- call will fail*n"6in call ; ;('*s' *s), "Jvariable number of args*nacd,a
@fCCK2C 8 8,a
@h                                                   CCK2C 	Aacj,a
@fCCK2C ,a
@lMCCK2C ,a
@ngCCK2C acpA@a@acr	A9 9,aStfCCK2C 			A"	("@	",agveCCK2C 	@,awxCCK2C ,aKzCCK2C 	A
; ;$	%/+ac|,a
@~CCK2C ,a
@xCCK2C Q@ acQ@ Q@Q@	"C<#t#,aGWCCK2C < <Q	#C?AD,aGGCCK2C QacQ@Q@Q	@Q	@	$acj,a
@h                                                   CCK2C ,a
@                         CCK2C 9 9,a
@
                                                                                                                               CCK2C 	acpA@a@,a
@lMCCK2C ,a
@ngCCK2C 	"@HCacpA@a@2o	": :	@H#acpA@a@@A@#vacpA@a@Hacj,a
@h                                                   CCK2C ,a
@                         CCK2C ,a
@
                                                                                                                               CCK2C : :	acpA@a@h,a
@lMCCK2C ,a
@ngCCK2C 	"@HCacpA@a@|	"@H#acpA@9 9a@
A@#%acpA@a@Y	$L	Z7.,awxCCK2C ,aKzCCK2C : :	A
	%GCacj,a
@h                                                   CCK2C ,a
@                         CCK2C ,a
@
                                                                                                                               CCK2C 	acpA@a@6,a
@lMCCK2C 6 6,a
@ngCCK2C 	acpA@a@JF	A,aStfCCK2C 		!uc!
c!|$CCK2C !9 9$CCK2C !z$CCK2C !h$CCK2C !p$gCCK2C !n$MCCK2C !j$                                                   CCK2C !
$                         CCK2C !$                                                                                                                               CCK2C !x9 9$eCCK2C !v$fCCK2C !$WCCK2C !$GCCK2C !f#EQUAL !#CMPMO0!l#PUTWH0!r#PRINT !t#FNDEF  !~#GETWRD!#CVTMO0
 
"%@&0&$" PUTWH09 9"*s ('*s' *s):  	ac A@a@Q	@Q	@Q	@		!u!"#PRINT 
 
"%,"0&m& CVTMO0; ;	A"#	(#@	"@HADQK	A
acQ	@A@"	@$"@HADQK	C	("@ac: :Q	@A@"Q
	@Q
(	cck2: mode too complicated*n. ,		$#	@acA@9 9C@->	#@HAD$QS	#C?@HADQ
QS	"@HADQK	A
	("@[F	#@HAD0 0	@ QS	#C?@HAD@QS		!um!m!:m!#CTOL!#PRINT 
 
"%2&0&5, CMPMO09 9"59 979 979 979 97; ;		A"#$#@H%t%QK	A
	$@H&t&QK	A
	t%QK9 9	%	%	@t&QK	%&&	%%	@'		')	#@H%$@H9 9	ADQK	9@t%Q[	ADaK~	',	'(	@ )		)	A$"LI	)	K		)	(#9 9R	($SU	(#@($@@ "V		#C?@H%$C?@H&t%QK	t&	Qg	ol	@ )	n	A: :	$"wt	)	v		)	@	(B*LADGQTW^]	A$" 	)			)	!!!
 
"%8,0&