:,9 9".."4000"4000" 4001"&4001",4000: :"24040 10000">2030 120000!!!!}9 9"J3[-abdfhnpuvw] [-o<req str>] -s<ign> -m<ign> -l<ign>: :(-i<ign> -t<ign> -g<ign> -e<ign> -c<ign>"&vl #*n".9 9copy *s4000 *s -delete -nq*n"L.b"P.o"Tvswtl: :b"\.o"`.m"d.o"h.m"lco ab *s*n"x=9 9cm_loc="	=tp_loc="sy swt$cm *s*nsy swt$tp *s*n: :"*c$main"2ccmain.bin">ciolib"Flo *s*n9 9"Ns/lo *s 0 *s *s*n"`	vswtmath"jlo *s*n"rs/l9 9o *s 0 *s *s*n"vshlib"lo *s*n"
s/lo *s 0 : :*s *s*n"&li cclib*n"2s/li cclib 0 *s *s*n"Hv; ;swtlb	acPa@JQ@	C	A"Q	AQ	AacR; ;a@,A@a@&A@acRa@,A@a@ A@	can't open temporary file.)	acTa@Q@:: :	A@acVA@	   CacXC@*F	A#	swtseg*n. NacZA@ac\A@C@O9 9Q	A
"ac\A@A@Q@Tac^A@A@ac\A@A@a	
re*nsh*n*s*ndelete*n9 9q*n.cname *s4000 *s*n.w'ac\A@a@&ac^A@A@ac\A@C@xQ@:ac`Q@TA@		A: :ac\A@C@Q@:Q@T(ac\A@a@.Q@:Q@T3v	acbA@Q(	ADQG9 9Q acdQ	@ acfMQ	A	A$R	A%	(%@XachA@%Q@A@9 9	%
fQ	%kQ(	ADQK	AacjQ@a@LQ@na@PQ	%; ;Q4Q(	ADQGQ acTQ@nQ	@ A@	BQ4Q4q	A&aclQ@Q@nQ9 9	A
ac\A@A@Q@n#		s/lo *s 0 *s *s*n.-ac\A@C@.Q@na@a@,; ;jQ
	A
		"GacnQ@		'	%B(achA@(Q@A@	%
`: :Q	%e_d		"Je	(%@ac\A@A@Q@	%B(	achA@(Q@9 9A@	%
Q	%acRa@TA@Q@A@	(%@		&; ;acpQ@Q@nQ	A
ac\A@G@)Q@n!		s/lo *s 0 *s *s*n.+	ac\A@C@,< <	Q@na@a@*s	%B(achA@(Q@A@	%
PQ	%UOT	@ Q: :U	(%@YQ	AQ(	AD QGQ acjQ	@ a@\Q@na@`aclQ@nQ@n9 9_	aclQ@Q@nwac\A@A@Q@nA		$U	A)
	%B(achA@(; ;Q@A@	%
Q	%"!	@ Q"	(%@&Q	AacTa@: :Q@:A@,	string following -g must be 28 chars long or less.6acrQ@	Cacb: :A@acXC@7VacTQ@Q@:A@_5	%B(achA@(Q@A@	%
w< <Q	%|v{	@ Q|	(%@Q	AacTa@a@A@acT< <	Q@a@A@h	%B(achA@(Q@A@	%
'Q	%,&+	@ Q9 9,	(%@0Q	AacTa@&a@ A@6acTQ@a@ A@?	co ab : :*s*n. Hac\A@C@Ia@ Q	'*Li^`bdtBeh: :
ijkRl		                "hWKCYeQ	A		)vQ	A
ac\: :A@A@}Q	A
Q(	AD!QGQ acjQ	@ a@dQ@na@haclQ@nQ@nac\9 9	A@G@Q@nQ(	ADQGQ aclQ	@ Q@T	Q	Aac\A@a@l: :a@ 8acta@xQ@HA@	CacRa@2A@Q@HA@Kacta@Q@hA@	: :	CacRa@>A@Q@hA@`ac\A@a@Q@HQ@hQ	Aac\A@A@x: :Q	A
		Aacpa@*Q@nQ	A
ac\A@G@'Q@n	s/; ;lo *s 0 *s *s*n.ac\A@C@Q@na@a@	A  Q	A
		A5acpa@2; ;Q@nQ	A
ac\A@G@Q@nB		s/lo *s 0 *s *s*n.Lac\A@C@MQ@na@; ;a@K	A  8y	li pl1glb*n.e		AQ	A
Q	A
ac\A@C@f: :v	s/li pl1glb 0 *s *s*n.~ac\A@C@a@a@}r	li paslib*n.Q	A
9 9Q	A
ac\A@C@"	s/li paslib 0 *s *s*n.*ac\A@C@+a@a@; ;)Q	A
acpa@>Q@nQ	A
ac\A@a@FQ@nMac\A@a@NQ@n9 9a@a@Vacpa@`Q@nQ	A
ac\A@a@jQ@nlac\A@a@rQ@n9 9a@a@uacpa@Q@nQ	A
ac\A@a@Q@nac\A@a@Q@n9 9a@a@CQ	A
Q	A
ac\A@a@&Q@n(ac\A@a@2Q@n: :a@a@1$	lo *s*nli*n.>acpa@HQ@nQ	A
ac\A@C@?Q@nN	: :s/lo *s 0 *s *s*ns/li 0 *s *s*n.Xac\A@C@YQ@na@a@a@a@Wn	Aq		9 9	%
acbA@	&Usage: ld -{a|b|d|f|h|n|p|u|w} [-o <output file>].          { <binary file> 9 97| -m [<map opt>] | -s <command>.             | -l [<library>] | -i | -t | -g <seg name>.             | -e <seg9 9ment> | -c <segment> }. !acvC@acvC@acvC@;acvC@WacxA@acfd	&L9 9	"L
Kir
	$LV
4N{	)Lz9 9!u!}!
!!!!        !!! !f!9 9-!	>!H!b!hp*s*n.   Hlo *s*n.$ma *s*n.ma 6*n. : :~mi*n.   gvl *s*n.uq*n.!|#GETARG!#MAPDN !d#PARSCL!#LENGTH!t#INDEX !j#MKTEMP!h9 9#CTOC!#EXPAND!f#SCOPY !l#ERROR !n#REWIND!p#PRINT !r#FCOPY !v#RMTEMP!x#REMOVE!z#SWT  !~#SUFFIX!#MKTREE!#MAKEL0!
#REMARK!#SETERR
 
"%N,0&>$ MKTREE; ;	acQ	@Q@A@acQ@A@	AacQ@A@	AacQ@A@Q	@A@: :				QS	uQGQlacQ@Q	@l	@D"@HAD	QS	@ t"QS		!>!f% %!'!/!\!#MKTR$ !#INDEX !#EXPAND!#SCOPY 
 
"%$0&"" MAKEL0; ;"=newlib=/*s	acQ@A@a@Q	@acQ@Q	@		!f!#ENCODE ! #MKTREE
 
"%"0&B$ SUFFIX9 9	acQ	@	A"acQ	@Q@A@"acQ@Q	@	@HCacQ@	A"acQ	@: :Q	@A@"acQ	@A@Q	@A@&acQ	@	B"acQ	@	A@Q	@A@"		% %!B!#LENGTH!#EQUAL !#STAKE !#SDROP !#SCOPY 
 
"%$0&