f
*9 9`TOGET "-s"=extra=/clist""=ubin=/clist"0Can: :'t create clist file"HOverflow!!!!!!!! ARggggg...: :"dwritef returned an error"~writef died in loop"9 9seekf returned error"(writef died on last writef9 9acDA@Q@A@acFQ@a@	@HCacHa@A@	"Q	AacH9 9a@"A@	"		Usage: mkcl [-s]. %acJC@&$	"CacJa@06	A#; ;	$	acLA@Q@	%%%I	t#QSe	$QS=	A&	(&@Q	%B&C	t&QK9 9	t$QS	($RRX	(#@$%	@#%f	@jacJa@Hl	acLA@Q@< <	%EH	A&	(&@{	&%	@@A7&,aSN~TOGET 	@ t&,aSP?TOGET |acR: :,a
@TTOGET A@	A@"	CacJa@d	A&	(&@	&%	@@ 'acVA@": :A7&,aSN~TOGET 	A(	((@0	#@H(C	t(QKe	&CQK=	ADQGQ	&9 9	B)acRQ	@A@)A@"	CacJa@~R	&B''=17	't&,aSP?TOGET : :"	acXA@A@"	CacJa@iacR,a
@TTOGET A@	A@"	CacJa@(9 9xacZ!v!}!!!! !	`!!X!9 9d!X$~TOGET !^$TOGET !Z$?TOGET !P#EQUAL !V#GETNA0!R#CREATE!b#SEEKF !\ #WRITEF!`#MARKF !N#GETARG!T#ERROR !d#SWT 
 
"%B*0&
$ GETNA0: :		acQ	@Q	@	"%	@HAD@ QS
		#		acQ	@A@	"@H#	! !!#GETLIN!#MAPSTR
 
"%*$0&