@$: :"b<opt str> l<opt str> c<flag>".*s.b"4*s.l":9 9*s: can't open"JCC -NOCONVERT "ZCC -NOCONVERT -9 9
CHECKOUT "t-INPUT *s "-BINARY *s "-LISTIN: :G *s "*n	usage: xcc <file_spec> [-c] [-b [<path>]] [-l [<path>]].aca@9 9Q@	Cac C@%ac"A@Q@|A@	BCac"A@Q@|A@	%@49 9?	usage: xcc <file_spec> [-c] [-b [<path>]] [-l [<path>]].Aac C@B@	xcc: source : :program must be in a @.c file.bac$Q@|	"	ac&Q@|A@	#"@H#C	t"QK{	%: :
ac C@c	#A
	@ t"QSzac(Q@HA@a@.Q@|ac(Q@0A@a@4: :Q@|	#A	"@D"1		t"QSz		QS{	@ QS|Q	%
DQ4Q	ADQG9 9Qac*Q@HQ	@A@	BQ4Q4CQ	%
_Q4Q%	AD	QGQac*9 9	Q@0Q	@A@	BQ4Q4^Q	A
Q	ADQGQac*Q	@Q@HA@x: :Q	A
Q%	ADQGQac*Q	@Q@0A@ac,Q@|A@A@A@A@A@; ;A@A@	Aac.A@	a@:Q@|ac A@
.Q	Aac.A@a@J>Q< <	AQ	AIac.A@a@ZM	xcc: -c disallows -b and -l.Uac C@VTEac0: :*Q@|Q@dac.A@a@tQ@dac0Q@HQ@dac.A@a@Q@dQ	A
ac0Q@0Q@d9 9ac.A@a@Q@dac.A@a@ac2!
. !	q!u!}!!!; ;!!.!4!H!c!.#GETARG!0#LENGTH!2#INDEX !8#FILTST!*#PARSCL# #!6#CTOC!,#ERROR !4#ENCODE!:#PRINT !<#TREEN0!>#SWT 
 
"%>$0&" TREEN09 9	!acQ	@Q@A@acQ@Q@lacQ@lQ	@A@		!f!#EXPAND!#MKTR$ ! #CTOC
 
"%t"0&