G2AT$SWT9 9!%B&!AT$SWT	#AAAEAAA>AA@C1A8A>< <A;A8As,Ac.A	@&A	@)A	@,A	@/A	@2A	@5		FAS5		BAD_PASSWORD$ !%9; ;!$AT$.BP_UNIT 9	AC-	AAc0A@!+#MKONU$#ATCH$$#PL1$NLG 0S8CALL$$; ;!%V&hSWT$CM!CALL$$	AAAAA	@ATAcC@3C@1C@B; ;AcA@=A	@&A	@)A@/	/
CA
qCCA
'D		AcA@=A	@&A	@)A@/	/CA
qECA
99 9D		AcC@FAcC@GA	@&A	@)A@RA@SA@/	/CA
TAcC@HD		AcC@I: :A@RA@/ATAcC@JC@KC@HA@RA@SA@S	/CA
D		ADCABAACA: :/ALMCA
ACAAcC@FAK CA
ATCABAc"A@TAcC@HD		AK$A	0; ;	AAS&CW	-AS$Ac(A@PA,CAAALAANC,AFALAIAFAs*Ac: :C@HAc,A@/ATCACS	tB&A@AcDWAc.A@TAcC@FATCABcAc"A@TAc0A@P9 9Ac2C@NO	/AK4PA	/	/Ac2A@/Ac6C@,A	0AS$AcC@HQ		CCA; ;$C/ADAwA4ADAA>AARAA	@ AAAA	CA; ;ANY$0 }@ \o; ;~
!#MOVE$ #REST$$#LDSEG$#BREAK$#SRCH$$#R$RUN $`SWT$CM#R$DEL $`SWT$CM$`SWT$CM#IOFL$ #MKONU$ #AT$HOM#R$INVK#COF$#DUPLX$$aSWT$CM#RVONU$S(0CHKINP: :!%!CHKINP	AAAA	A		qD@ AS		 0

'CTOC: :!%!CTOC	AAA%At&AKCA
#	AEAkAoAKAS   &CA
#	@LCAT	@@&AS	B	 0vDGETL$; ;!%*hSWT$CM!DGETL$	AAAmAAkAK	@Hn	ADAo9 9	AADACA*	AEo	Q%CAT%AwCB\*fCB\AwfAA	AA	!AwCO; ;A(	"CA=0EAw!C+O	AE$RA	B`$p	e	Q$q	
SCB\RXA; ;	B($p		Q$q	SCB\aCBT[[CBTE0EA	B(Aw	"	AEo	QCATzAw"< <CB\v(	@[CBTE0ECB\lAw	#Aw"(	@
[CBT0A	B`Aw	"	AEo	QCAT9 9Aw"CB\RXCB\Aw	#Aw"XAw	%	4&CcMC@rA@A@(A@ C@kA@'C@Q	t&CKQ9 9CA
?sCA
;	@ 'm	tA	$	$'"CA
`	!AEC+O	'AAE%#PRWF$$$SWT$CM: :$
SWT$CM	@L@CBT[[	$A@]	$@@$Aw	"AkA	!Au	QB	  

(0!DPUTL$; ;!%,hSWT$CM!DPUTL$	 AAAAAkAA	AA	C; ;	'tCG{A%	tAk%AwtAot	!@P 	CA
0CCE[A	)CCE6A	)E	I: :$	V$		B $	N	)CB\E	I$	$		B()A; ;
CBTS0OCB\6	( @CB\[b	I$	V$		, 	CAv$vm	@ , B(N< <
ACBTs0O	@ , =	@L$$ACBT0O	B(CAc	, =	( @CB\; ;	I$	$		, 	CA7$7+	@ , B ,)
ACBT$0O	)$	N; ;CB\E	)
ACBT20O	@ , B(N	@L)
ACBT?0O	A$$	B )B`< <CA	, B()NA#	4"!Aw	(CcyC@A@A@%A@C@A@*C@}CK}CAs	AEA+%< <	AAEt"A#AG'A	!	! #PRWF$$$SWT$CM$
SWT$CM	!@@	)A	!A@!Aw		B. .	AkA	A		 
   }(0"EQUAL : :!%!EQUAL 	$AAAAAkAot AKAg$  	CB\!		 		 0rFILE$P; ;!%
!FILE$P	%AAAAAAtCw	AKA_CCA: :*ACCAB5ACACA\Ac\C@
C@C@
C@
C@C@	4	ADI<Ac^; ;A@	Ac`A@AcbA@	 CArAcdA@ C@A@ C@Ak	
CCbA	@ ; ;AnAAtASJCA\j	 AAk	
CCA	@ A: :AAtASJCA\AAKA	@ AAJ	@DACA< <tAS	CA\!AcfA@A@"C@$	vAchA@KC@A@VC@AcjA@"A@V$	k; ;AchA@FC@A@VC@AcjA@"A@V$	kAclA@"A@V	!AcnA@VA@!A	; ;A@
C@		AcpA@YA	A@
C@			AcpA@PA	A@
C@		!
STDIN   STDIN1  STDI; ;9N2  STDIN3  ERRIN   STDOUT  STDOUT1 STDOUT2 STDOUT3 ERROUT  vvtrruusqq/dev/null./dev/tty. path unobtaina; ;ble TTY 2
FILE$Pdt  fv@; ;4}.	![#ERRPR$#MAPSU #FLUSH$#MAPFD #ATTDEV#GFNAM$#PTOC#EQUAL #MKTR$ #CTOP#MOVE$   0INDEX 9 9!%!INDEX 	#AAAAAktAK$Ag CB\	BB	@ 	 0LENGTH; ;!%!LENGTH	AAAAAktAgCB\	B	  0ZMOVE$ 9 9!%!MOVE$ 	AAAVAAK	 	ADAkAo	AAD@; ;	AKASCB\		B>*AKAS	@LCB\)		B=
4AKAS
W	 	AD<BAKAS
9 9AKAS
X	 	ADAKAS
AKAS
AKAS
AKAS
YCAA		(0

aPTOV; ;!%"!PTOV	AAA_A	@ 	ASAKCA
-	@HCA
-	AK9 9	@ !AD@H@LAAE	C3Q$`$(	$    *-*C3QC30AK		 !CA?	A! B`A: :Ak	@A	@ ! 	AAAk	@BT$--	BAEA	@ @HCA]AK	@LB(B`@L A@ 0!REONU$< <!%!REONU$	CAB AA+	AkAC'		 ACACA	 	AAcA@!#PL1$NL! 0RTN$$ 9 9!%	hSWT$CMSWT$TP!RTN$$ AkAkACAAcA
@Ac ! $SWT$TP#PL1$NL$`SWT$CM#EXIT 0 SCOPY : :!% !SCOPY 	$AAAAAwAkAwAotAKAS$ CB\	B	 0I6SYS$$ 9 9!%>&hSWT$CM!SYS$$ 	AAA:A	A,Ac$A	@&A@,A@<: :C@;	@ -AK&	0Ac(C@<AK)=CA
OAc*A	@)CAB	.Ac,A	@)	/Ac.A@/	.: :AS&Ac0C@>C@AA@.A@1O	@ !AK&Ac0C@BC@EC@FA@1AA2AA4C; ;!A6A2A9A6As2Ac(C@FAc4A@<A@,A@-	0AS&CA
Ac0C@>C@AA@0A@1< <    	Ac0C@BC@EC@FA@1	,CA
GCA	-CA	H		=		CLEANUP$!%
: :	AA0AS&CA
/Ac0C@>C@AA
@&A@		Ac0C@BC@EC@FA@		: :}CONTINPAUSE <~!$#CTOV$`SWT$CM#BREAK$#MAPFD #MAPSU #FLUSH$#COMI$$ #MKONU$#CP$ I 0

4VTOP: :!%!VTOP	AAA2AAK	CA
0	@ACCE	BADAK7 73AS	BAg ''AK	CCA0	AADAkAKASCA\*		 0 ZMEM$ : :!%!ZMEM$ 	AAAAAkA	A	ABA	AD Ak	@ ASCA\		 0