" 	acacac!#INITI0!#MEMO!#SWT 
 
"%""0&EJ( INITI09 9hDS$MEM>MEMOC0"sunday"sun"monday"$mon"(t: :uesday"0tue"4
wednesday">wed"B	thursday: :"Lthu"Pfriday"Xfri"\	saturday"fsat"jj: :anuary"rjan"v	february"feb"march"
m9 9ar"april"apr"may"june""jun"&: :july",jul"0august"8aug"<
september"Fs9 9ep"Joctober"Roct"V	november"`nov"dde9 9cember"ndec"rmonth"xday"|year"dow; ;"hour"minute"always"always	ac$A@ac&; ;A@,aS(=MEMOC0	ac*a@A@,a
@(=MEMOC0	ac*a@A@,a
@(=MEMOC0	ac*a@A@7 7,a
@(=MEMOC0	ac*a@$A@,a
@(=MEMOC0	ac*a@(A@,a
@(=MEMOC0	ac*a@0A@7 7,a
@(=MEMOC0	ac*a@4A@,a
@(=MEMOC0	ac*a@>A@,a
@(=MEMOC0	ac*a@BA@7 7,a
@(=MEMOC0	ac*a@LA@,a
@(=MEMOC0	ac*a@PA@,a
@(=MEMOC0	ac*a@XA@7 7,a
@(=MEMOC0	ac*a@\A@,a
@(=MEMOC0	ac*a@fA@,a
@(=MEMOC0	ac*a@jA@7 7,a
@(=MEMOC0	ac*a@rA@,a
@(=MEMOC0	ac*a@vA@,a
@(=MEMOC0	ac*a@A@7 7,a
@(=MEMOC0	ac*a@A@,a
@(=MEMOC0	ac*a@
A@,a
@(=MEMOC0	ac*a@A@7 7,a
@(=MEMOC0	ac*a@A@,a
@(=MEMOC0	ac*a@A@,a
@(=MEMOC0	ac*a@A@7 7,a
@(=MEMOC0	ac*a@"A@,a
@(=MEMOC0	ac*a@&A@,a
@(=MEMOC0	ac*a@,A@7 7,a
@(=MEMOC0	ac*a@0A@,a
@(=MEMOC0	ac*a@8A@,a
@(=MEMOC0	ac*a@<A@	7 7,a
@(=MEMOC0	ac*a@FA@	,a
@(=MEMOC0	ac*a@JA@
,a
@(=MEMOC0	ac*a@RA@
7 7,a
@(=MEMOC0	ac*a@VA@,a
@(=MEMOC0	ac*a@`A@,a
@(=MEMOC0	ac*a@dA@: :,a
@(=MEMOC0	ac*a@nA@,a
@(=MEMOC0	ac,A@Q@	A"	ac.Q@A@"	#	"ac.< <Q@A@"	$	"	ac.Q@A@"	%	ac*a@rA@#,a
@(=MEMOC0	ac*a@xA@$,a
@(=MEMOC0; ;	ac*a@|A@%,a
@(=MEMOC0ac0A@#A@$A@%	&	ac*a@A@&,a
@(=MEMOC0ac,A@9 9Q@	A"	ac.Q@A@"	&	ac*a@A@&,a
@(=MEMOC0		"	ac.Q@A@"	&ac*8 8a@A@&,a
@(=MEMOC0ac,A@,a
@22MEMOC0ac4,a
@22MEMOC0A@ac6a@A@: :,a
@8MEMOC0A@ac6a@A@,a
@:fMEMOC0A@		!!!!!!8 8!!!		!

!!E!h!F$MEMOC0!H$fMEMOC0!@$2MEMOC0!64 4$=MEMOC0!<#CTOI!>#GETDOW!4#MKTABL!2#DSINIT!8#ENTER !:#DATE!B#MAPSTR!D#SCOPY 
 
"%2(0&" ERRMSG% %	acA@A@Q	@		!q
*s*n.   !#PRINT 
 
"%&"0&

=D$ EVAL: :hDS$MEM>MEMOC0"bogus character in expression		ac.Q	@A@8 8,a
@0LMEMOC0A@	A,aS29MEMOC0	@ ,aS48MEMOC0	ac6ac8A@"	"@HC		#	; ;,aK::MEMOC0	%#	A
"ac<a@		#	$	"@HC		#	/,aK>MEMOC0	A
9 9	A#	6	@ #	!}=!=!
=!4$LMEMOC0!B$MEMOC0!8$8MEMOC0!6$9MEMOC0   !>$:MEMOC0!2#SCOPY !:#GETSYM!<#BEXPR !@#ERRMSG
 
"%($0&'( GETDOW: :	QK	@H"QK	#QK	$"A		"$@H$	$M=%"9@@HM=%#$M=@B&	! !!
!!!"
 
"%2(0&L
$ GETSYM: :hDS$MEM>MEMOC0"always"never"undefined variable: :,aw29MEMOC0,aK4KMEMOC0	%	%
	,ak29MEMOC0
,aw29MEMOC0: :,aK4KMEMOC0	%	%	@A"	("@,aw29MEMOC0,aK4KMEMOC0	%''7 7	%&	@t"QS,ak29MEMOC0(	@ t"QSac6Q@a@	@HC	A< <,aS8:MEMOC0=	ac6Q@a@	@HC		,aS8:MEMOC0Jac:Q@,a
@<;MEMOC06 6,a
@>=MEMOC0	@HC	@ ,aS8:MEMOC0Yac@a@]NA,aw29MEMOC09 9,aK4KMEMOC0	%kk	%j	@@ ,aS<;MEMOC0,ak29MEMOC0	@q,aw29MEMOC09 9,aK4KMEMOC0	%}}	%|	@,aK<;MEMOC0	9@,a[4KMEMOC0	,aS<;MEMOC0r6 6~	@ ,aS8:MEMOC0l,aw29MEMOC0,aK4KMEMOC0,aS8:MEMOC0	%	A
9 9,ak29MEMOC0	@b		!!
!	!
! !0!9!a!: :z!>$KMEMOC0!<$9MEMOC0!B$:MEMOC0!F$;MEMOC0!H$=MEMOC0!D#LOOKUP!@#EQUAL !J#ERRMSG
 
"%
$0&


C:$ MEMO; ;hDS$MEM>MEMOC0"-t"-d"-e	A"	("@acA@"Q@A@9 9	%acQ@A@ac Q@a@	@HC	("@acA@",a
@"2MEMOC0A@	BC; ;ac$+		illegal user name..ac,a
@"2MEMOC0A@ac&,a
@"2MEMOC0	Cac(; ;C@/D	ac Q@a@	@HC	("@acA@",a
@*MEMOC0A@	BCac$9 9_ac,a
@*MEMOC0A@R	ac Q@a@	@HC	("@acA@",a
@,fMEMOC0: :A@	BCac$~ac,a
@,fMEMOC0A@qac&Q@	@DCac.Q@A@9 9,a
@"2MEMOC0A@	illegal user name or improper argument syntax.	ac0C@ac$9 9hI	A$"	;ac2<ac4?		!}C!C!C!fC: :!.$MEMOC0!0$fMEMOC0!&$2MEMOC0! #GETARG!$#EQUAL !*#VFYUSR!"#MAPSTR!(#USAGE !,#ERROR  !2#SCOPY !4#REMARK!6#SENDM0!8#SCANM0
 
"%
$0& F( SCANM0; ;hDS$MEM>MEMOC0"=extra=/memo/=user=	can't open memo file. ac$a@9 9A@	"Cac&C@ac(A@	#	ac*Q@A@"	%(ac*,a
@,MEMOC0; ;A@"	%1ac*,a
@.fMEMOC0A@"	%:09	badly-formed memo file. ;ac09 9A@"ac2A@#ac&C@<:ac4,a
@,MEMOC0	$ac4,a
@.fMEMOC0	%A	$A_; ;ac6Q@A@#ac6,a
@,MEMOC0A@#ac6,a
@.fMEMOC0A@#ac*Q@A@"	&ac6Q@: :A@#Q	Cub	%@HC	$Aac*Q@A@"	&Q	C	: :*n*n*s*n. 	%A	$@HC$ac8A@C@Q@ac6Q@A@#ac6,a
@,MEMOC0A@#: :ac6,a
@.fMEMOC0A@#ac*Q@A@"	&ac6Q@A@#ac6Q@A@Q	CC; ;(	*n*n*s*n. \	A$%gd	$Cfac8A@C@]Q@ac*Q@A@"	&ac6Q@: :A@Q	Cri['!ac:A@"ac:A@#ac<A@#A@"ac>A@"ac0A@"9 9ac2A@#		!u!}! ! !. !2$MEMOC0!4$fMEMOC0!*#OPEN!0: :#GETLIN!:#EVAL!,#ERROR !.#MKTEMP!6#CLOSE !8#RMTEMP!<#PUTLIN!>#PRINT !@#REWIND!B#FCOPY  !D#TRUNC 
 
"%(0&FL& SENDM09 9hDS$MEM>MEMOC0"=extra=/memo/ac,a
@ MEMOC0	"C		ac; ;,a
@"fMEMOC0	"C			memo file not available.ac$A@	#ac&A@A@#ac(: :A@#ac*a@A@Q@pA@	"B$ac*,a
@,2MEMOC0	A@Q@pA@$	"	ac.Q@pA@: :	%Cac0C@O	Memo from *s at *s *s*n.Tac2A@%ac4A@Q@`ac6Q@`A@; ;-ac4A@Q@fac4A@Q@Vac8A@%C@UQ@`Q@VQ@fac8A@%A@,a
@ MEMOC0ac8; ;A@%G@,a
@"fMEMOC0	ac:Q@A@#	%"ac<A@A@%ac>Q@A@%!ac8: :A@%A@ac@A@%acBA@#		!v!}!>!!!>! >9 9*s*n.   4@.*n.   !($MEMOC0!*$fMEMOC0!4$2MEMOC0!6#OPEN!2#SCOPY !,#MKTEMP!B#GETLIN: :!&#EVAL!.#FCOPY !0#REWIND!8#ERROR !:#WIND!<#DATE!>#MAPSTR!@#PRINT !D#PUTCH !F#PUTLIN !H#CLOSE !J#RMTEMP
 
"%(&0&!" USAGE 0 0	Usage: memo {[-t] user|-d display_cond|-e erase_cond}.acC@		!#ERROR 
 
"%""0&%0$ APRIM ; ;hDS$MEM>MEMOC0"Stack overflow	A",aK :MEMOC0	A		",ak"8MEMOC09 9	@	,ag"8MEMOC0
ac$a@		QS		,aK&;MEMOC0,aw"8MEMOC0,aS(MEMOC06 6ac*	"QS		!!%! %!,$MEMOC0!&$8MEMOC0!$$:MEMOC0!* $;MEMOC0!(#ERRMSG!.#GETSYM
 
"%($0&/j* RELAT09 9hDS$MEM>MEMOC0"missing relational opr"(relop missing r; ;ight operand"Drelation can't happen	acZA@"	"#9 9		QS			#%	"Cac\A@"	"$		QS		ac^a@; ;	$L#	"%-		QS		,acZA@"	"%		QS		ac^a@(7 7,aK`<MEMOC0	&,awb8MEMOC0,aKdMEMOC0,a_fMEMOC0	CC',awb8MEMOC05 5,aKdMEMOC0,a_fMEMOC0	CB'M,awb8MEMOC0,aKdMEMOC0,a_fMEMOC0	C@'V9 9,awb8MEMOC0,aKdMEMOC0,a_fMEMOC0	CA'_,awb8MEMOC0,aKdMEMOC0,a_fMEMOC0	CE: :	'h,awb8MEMOC0,aKdMEMOC0,a_fMEMOC0	CD'qD	&@H(LENW`ir9 9ac^a@Dz,aKb8MEMOC0	@H,aSb8MEMOC0	'A
	A)         @ )	),awb8MEMOC09 9,aSfMEMOC0@7	%L<8A	"%'		QS		&	"QS		!7 7!/!f$MEMOC0!h$MEMOC0!d$8MEMOC0!b$<MEMOC0!\#APRIM !^#RELOP !`#ERRMSG
 
"%.*0&W8& RELOP 9 9hDS$MEM>MEMOC0"'~' must be monadic	A",aK$:MEMOC0	C		"9 9,aS&<MEMOC0ac(	"C	A",aK$:MEMOC0	C		"ac(	"#		": :	#%' "	"%+		QS		*         "@HC,aK$:MEMOC0	C		9 9	"ac(7	"C	A",aK$:MEMOC0	C		"	,aS&<MEMOC0ac(Fac*; ;a@N	"%W		QS		V?	"@HC,aK$:MEMOC0	C		"	,aS&<MEMOC08 8ac(c	"C	A",aK$:MEMOC0	C		"	,aS&<MEMOC0ac(u	"@HC: :,aK$:MEMOC0	C		"		,aS&<MEMOC0ac(	"$		"	$%9 9	"%		QS		n	"@HC,aK$:MEMOC0	C		"	
,aS&<MEMOC0ac(9 9'	"C	A",aK$:MEMOC0	C		"	,aS&<MEMOC0ac(9	"%		"9 9C	%%KDF	"%O		QS		N2"^2	"QS		!!!!9 9!!	!
!W!<!=!>W!~W!0$:MEMOC0!2$<MEMOC0!4 #GETSYM!6#ERRMSG
 
"%*&0&D& BPRIM 9 9hDS$MEM>MEMOC0"missing parenthesized expr",missing exp9 9ression in parens"Jmissing right paren"^missing9 9 expression in parens"|missing right paren"Sta9 9ck overflow" Stack overflow	A",aK0:MEMOC0	C		"9 9ac2	"C	A",aK0:MEMOC0	C		"ac2ac4a@	"%$: :		QS		#ac6A@"	"#		QS		ac4a@,.	#L3/79 9	"%A		QS		@	A",aK0:MEMOC0	C		",aw88MEMOC0,aK:MEMOC0	A
: :	@ ,aS:MEMOC0S	A,aw88MEMOC0,aS:MEMOC0Wac2Kac4a@J_	"; ;	%h		QS		g	"@HC,aK0:MEMOC0	C		"ac2t	"Cac6: :A@"	"$		QS		ac4a@^	$L	"%		QS		: :	A",aK0:MEMOC0	C		"ac2 ac4a@|%	"%.		QS		-: :|	"@HCac<A@"	"%		QS		<	%%E=	A$"JG,a_0:MEMOC0; ;	C		",ak88MEMOC0	@	,ag88MEMOC0
Vac4a@		QS		W	A,aw88MEMOC0: :,aS:MEMOC0ac2M	"@HC,aK0:MEMOC0	@HC		",ak88MEMOC0	@	,ag88MEMOC0: :
xac4a@ 		QS		y	@ ,aw88MEMOC0,aS:MEMOC0ac2ojI5o	"QS		< <!!! !(!)!~!@$MEMOC0!>$8MEMOC0!6$:MEMOC0!8#GETSYM !:#ERRMSG!<#BEXPR !B#RELAT0
 
"%*&0&

v<& BSEC9 9hDS$MEM>MEMOC0"'|' missing right operand	ac*A@"	"#; ;		QS			#%	"C	A",aK,:MEMOC0	C		"ac.	"C< <ac*A@"	"$		QS		ac0a@,aw28MEMOC0,aK4MEMOC0	A,aK6MEMOC05 5	A8<	A,aw28MEMOC0,aS4MEMOC0=	@ ,aw28MEMOC0,aS4MEMOC0C9 9,aK28MEMOC0	@H,aS28MEMOC02)	$L.*3N	"%Y		QS		X"9 9	"%a	%		"b	%%jce	"%n		QS		m	"QS9 9		!!!v!|v!8$MEMOC0!:$MEMOC0!6$8MEMOC0!0$:MEMOC0!.#BPRIM  !2#GETSYM!4#ERRMSG
 
"%*&0&s<& BEXPR 9 9hDS$MEM>MEMOC0"'&' missing right operand	ac*A@"	"#; ;		QS			#%	"C	A",aK,:MEMOC0	C		"ac.	"C< <ac*A@"	"$		QS		ac0a@,aw28MEMOC0,aK4MEMOC0	A
,aK6MEMOC0; ;	A
8	A,aS4MEMOC0<	@ ,aw28MEMOC0,aS4MEMOC0@,aK28MEMOC0	@H,aS28MEMOC0: :2)	$L.*3K	"%V		QS		U"	"%^	%		": :_	%%g`b	"%k		QS		j	"QS		!!!s!&0 0s!8$MEMOC0!:$MEMOC0!6$8MEMOC0!0$:MEMOC0!.#BSEC!2#GETSYM!4#ERRMSG
 
"%*&0&