"% %acacacac!#INITI0!#GETOP0!#TRANS0!#SWT 
 
"%""0&l"* INSTR0: : DS$MEM(aTLANG0	acA@"	"#		QS			#%	"$		"9 9	$%	"C	A",aK(TLANG0	C		"ac$	"@HCacA@"9 9	"%		QS		,akTLANG0:3	%@H&L48;	"@HCacA@": :	"'		QS		,akTLANG0	@,akTLANG0WM	'@H(LNRXF,	"8 8	%d		QS		c	"QS		!!!l!Gl!$TLANG0! % %$TLANG0!$(TLANG0!#LABEL0!#GETSYM!#LITER0!#NANOI0
 
"%.*0&>$ LABEL06 6 DS$MEM(aTLANG0	acA@"	"#		QS			#%	"C	A"; ;,aK(TLANG0	C		"ac	"%#		QS		"	A",aK(TLANG0	C9 9		"ac-	"%6		QS		5	"QS		!!>! !!> !$(TLANG0!#LABEM0!#GETSYM
 
"%($0&4.* LITER0; ; DS$MEM(aTLANG0	@ ,awTLANG0,aSTLANG0acA@"	"#		QS			#%9 9	"C	A",aK(TLANG0	C		",awTLANG0,aGTLANG0	QacA@9 9	A@Q	@A@,awTLANG0,aGTLANG0QacA@A@Q	@,a
@(TLANG0ac9 9	"@HC,aK(TLANG0	C		",awTLANG0,aGTLANG0QacA@A@Q	@; ;,a
@(TLANG0,awTLANG0,aGTLANG0QacA@A@Q	@A@acL	"Cac: :A@"	"$		QS		,awTLANG0,aGTLANG0QacA@A@Q	@A@{: :	$@H%L|	"C	A",aK(TLANG0		C		",awTLANG0,aGTLANG07 7QacA@
A@Q	@,a
@(TLANG0ac"	"@HC,aK(TLANG0	C		": :,awTLANG0,aGTLANG0QacA@
A@Q	@,a
@(TLANG0ac?:	"%X		9 9QS		W	"&		"^	&%f_a	"%j		QS		it	"@HC5 5,aK(TLANG0		C		",awTLANG0,aGTLANG0QacA@
A@Q	@8 8,a
@(TLANG0,awTLANG0,aGTLANG0QacA@A@Q	@A@acv	"@HC: :,aK(TLANG0	C		",awTLANG0,aGTLANG0QacA@
A@Q	@,a
@(TLANG09 9,awTLANG0,aGTLANG0QacA@A@Q	@A@ac#	"CacA@"	"9 9	'		QS		,awTLANG0,aGTLANG0QacA@A@Q	@A@R	'@H(; ;	LSWg	"C	A",aK(TLANG0	C		",awTLANG0,aGTLANG0Q; ;acA@A@Q	@,a
@(TLANG0acy	"%		QS		 r	")		"; ;	)% 	"%$		QS		#KqG	"%,		QS		+	"QS9 9		!!!!!!!!!
	!!!	&!A!9 9E4!$TLANG0! $TLANG0!($(TLANG0!,$(TLANG0!$$(TLANG0!"#LITES0!&#SETF!*#GETSYM
 
"%0*0&B& LITES09 9 DS$MEM(aTLANG0	acA@"	"#		QS			#%	"CacA@"9 9	"$		QS			$%#	"%'		QS		&	A",aK(TLANG0	C: :		"ac1	"%:		QS		9	"QS		!!B!B! $(TLANG0!#LITET0!#LITEU0!#GETSYM
 
"%*&0&c,& LITEU0< < DS$MEM(aTLANG0	A",aK(TLANG0	C		",aK(TLANG0,aS(TLANG0ac,a
@(TLANG07 7,aS(TLANG0ac	"@HC,aK(TLANG0	C		"ac	"C	A"6 6,aK(TLANG0	C		",aK(TLANG0	A,aS(TLANG0,aK(TLANG0	A#acA@#; ;,aS(TLANG0ac-	missing constant after COMP.BacC@CA	"%Y		QS7 7		X&	undefined label.]	"@HC,aK(TLANG0	C		"ac,a
@ (TLANG0: :,a
@(TLANG0,a
@"(TLANG0	AacC@^zac,a
@(TLANG0,aS(TLANG0acn	"9 9	C	A",aK(TLANG0	C		"ac         "C	A",aK(TLANG0	C: :		",aK(TLANG0,a_(TLANG0,aS(TLANG0ac,a
@(TLANG0,aS(TLANG0ac 	: :missing constant after '-'. 2acC@31	"%I		QS		H	"$		": :O	$%WPR	"%[		QS		Z
i	"QS		!!!c!6 6!! !-c!$(TLANG0! $(TLANG0!$(TLANG0!$(TLANG0!*$(TLANG0!( $(TLANG0!#INSER0!&#LOOKUP!"#GETSYM!$#ERRMSG
 
"%*&0&n,( NANOI06 6 DS$MEM(aTLANG0	@ ,a7TLANG0,aSTLANG0,aSTLANG0,aSTLANG0,aSTLANG0; ;,awTLANG0,aGTLANG0QacA@A@Q	@A@,awTLANG0,aGTLANG0Qac: :	A@A@Q	@,a
@TLANG0ac A@"	"#		QS		2	#%;3	"$		9 9	"=	$%E>@	"Cac"A@"	"%		QS		O	%%XP	"9 9	&		"Z	&%b[]	"%f		QS		eH	"QS		!!7 7!!!!!n!"$TLANG0!$TLANG0!$$TLANG0!$TLANG0!% %$TLANG0!$TLANG0! $TLANG0!&#SETF!(#UNCON0!*#CONDI0
 
"%.(0&f&& UNCON08 8 DS$MEM(aTLANG0	A,aS(                                                                                    LANG0	@ ,aSTLANG0,aS	TLANG0,aS
TLANG0,a7TLANG09 9,aGTLANG0QacA@A@Q	@A@,a7TLANG0,aGTLANG0QacA@A@9 9Q	@A@acA@"	"#		QS		1	#%:2	"CacA@"	"$: :		QS		D	$%ME	"%Q>	%		"R	%%ZSU	"%^5 5		QS		]=	"QS		!!!f!!f!$TLANG0!- -$	TLANG0!$
TLANG0!$TLANG0! $TLANG0!$(                                                                                    LANG0!"#SETF!$#COMPO0
 
"%,&0&*( COMPO09 9 DS$MEM(aTLANG0	acA@"	"#		QS			#%	"@HCacA@"7 7	"$		QS		,a7TLANG0,aGTLANG0QacA@A@Q	@,a
@(TLANG09 9,aK(                                                                                    LANG0	@HC,a7TLANG0,aGTLANG0QacA@A@Q	@,a
@(TLANG039 9	$@H%LD	"@HCacA@"	"&		QS		adder may not be6 6 used twice.[,aK(                                                                                    LANG0	%o,aK 
TLANG0	A
ac"C@\r,a7TLANG0; ;,aGTLANG0QacA@A@Q	@A@n	A,aS 
TLANG0V	&@H'LW5 5[O	"QS		!!!!!!!&$
TLANG0!8 8$TLANG0!$TLANG0! $(TLANG0!"$(                                                                                    LANG0!#EXTER0!#SUCCF0!#SETF!$#LOGIC0!(#ERRMSG
 
"%.(0&,. EXTER07 7 DS$MEM(aTLANG0	acA@"	"#		QS		                                                                                                             em dev op may not be used twice. 9 9,a7TLANG0,aGTLANG0QacA@A@Q	@,a
@(TLANG0,aKTLANG0	A
ac9 9C@1,aK(                                                                                    LANG0	%;,a7TLANG0,aGTLANG0QacA@A@Q	@A@9 9:	A,aSTLANG0	#@H$LN	"Cac A@"	"%		QS9 9		cond@. adj@. may not be used twice. e,a7TLANG0,aGTLANG0QacA@A@Q	@5 5,a
@(TLANG0,aK"	TLANG0	A
acC@f,aK(                                                                                    LANG0	%,a7TLANG09 9,aGTLANG0QacA@A@Q	@A@	A,aS"	TLANG0`	%@H&Lae; ;(	"'		"2	'%:35	"%>		QS		=Y	"@HCac A@"9 9	"(		QS		cond@. adj@. may not be used twice. Q,a7TLANG0,aGTLANG0Q: :acA@A@Q	@,a
@(TLANG0,aK"	TLANG0	A
acC@Rw,aK(                                                                                    LANG0	%9 9,a7TLANG0,aGTLANG0QacA@A@Q	@A@	A,aS"	TLANG0L	(@H)9 9	LMQ	"CacA@"	"*		QS		mem dev op may not be used twice: :. +,a7TLANG0,aGTLANG0QacA@A@Q	@,a
@(TLANG0,aKTLANG0	A
9 9acC@,P,aK(                                                                                    LANG0	%Z,a7TLANG0,aGTLANG0QacA@A@Q	@: :A@Y	A,aSTLANG0&	*@H+L'+m	",		"w	,%x9 9z	"%		QS		E	"QS		!!!!!!!: :3!"$TLANG0!*$	TLANG0!$TLANG0!$TLANG0! $(TLANG0!&$(                                                                                    LANG0!#MEMOR0!#SETF !$#ERRMSG!(#SETOP 
 
"%4.0&E$ MEMOR09 9 DS$MEM(aTLANG0	@ ,aS(TLANG0	A",aK(TLANG0	C		"	,aS(TLANG0ac
9 9	"@HC,aK(TLANG0	C		",aS(TLANG0ac	"@HC,aK(TLANG0	C; ;		"	,aS(TLANG0ac)	"@HC,aK(TLANG0	C		"	,aS(TLANG0ac9 994$	"QS		!!E!!!/!0!2!3E!$(TLANG0 !$(TLANG0!#GETSYM
 
"%($0&M"$ SETOP : : DS$MEM(aTLANG0"	@ ,aS(TLANG0	A",aK(TLANG0	C		"ac
	"8 8	CacA@"	"#		QS		missing condition bit after SET.acC@: :,aw(TLANG0aK,aS(TLANG03	#L4:	"%E		QS		D; ;	"QS		!!M!CM!$(TLANG0!$(TLANG0!#GETSYM!#CONDJ0! #ERRMSG
 
"%($0&2$ CONDJ06 6 DS$MEM(aTLANG0	A",aK(TLANG0	C		"A,aS(TLANG0ac	"@HC9 9,aK(TLANG0	C		"	,aS(TLANG0ac	"@HC,aK(TLANG0	C		": :,aS(TLANG0ac'"	"QS		!!2!"!#!$2!$(TLANG0! $(TLANG0!#GETSYM
 
"%($0&M". LOGIC09 9 DS$MEM(aTLANG0	acA@"	"#		QS			#%	"CacA@": :	"$		QS		,a7TLANG0,aGTLANG0QacA@A@Q	@,a
@(TLANG09 9	$@H%L/	"&		"9	&%A:<	"%E		QS		: :DacA@"	"'		QS		O	'%XP	"(		"Z	(%b[]7 7	"%f		QS		e	"@HCacA@"	")		QS		,a7TLANG0; ;,aGTLANG0QacA@A@Q	@,a
@(TLANG0t	)@H*Luy		"C: :acA@"	"+		QS			+%$	",		"&	,%.')	": :	%2		QS		1	"@HCacA@"	"-		QS		@	-%IA9: :m	"QS		!!!M! M!$TLANG0!$TLANG0!$(TLANG0!#ADDER0 !#SHIFU0!#SETF! #DESTI0
 
"%4.0&+.
& ADDER09 9 DS$MEM(aTLANG0	acA@"	"#		QS			#%	"CacA@"9 9	"$		QS			$%#	"%'		QS		&	"@HCacA@"9 9	"%		QS		5	%%>6	"@HC,aK(TLANG0	C		",a7TLANG09 9,aGTLANG0QacA@A@Q	@A@,a7TLANG0,aGTLANG0QacA@A@: :Q	@A@,aK(TLANG0	A,a7TLANG0,aGTLANG0QacA@A@Q	@A@: :l,aK(TLANG0	@HC,a7TLANG0,aGTLANG0QacA@A@Q	@A@	: :constant must be 0 or 1.ac C@}ac"FA.	"QS		!+!!!; ;!!                                 !!+!"$TLANG0!$$TLANG0! $(TLANG0!($(TLANG0!#BINAS0 !#BINAT0!#UNARY0!&#SETF!*#ERRMSG!,#GETSYM
 
"%,&0&
^., UNARY09 9 DS$MEM(aTLANG0	A",aK(TLANG0	C		"ac	"CacA@"	"#< <		QS		,a7TLANG0,aGTLANG0QacA@A@Q	@A@,a7TLANG0,aGTLANG0: :QacA@A@Q	@,a
@(TLANG0,aKTLANG0	A
,a7TLANG0,aGTLANG0Q: :acA@A@Q	@A@>,a7TLANG0,aGTLANG0QacA@A@Q	@A@	O7 7	#@H$L`	"@HCac A@"	"%		QS		,a7TLANG0; ;,aGTLANG0QacA@A@Q	@,a
@(TLANG0,a7TLANG0,aGTLANG0	QacA@9 9	A@Q	@A@,a7TLANG0,aGTLANG0QacA@A@Q	@A@
r	%@H&L7 7sw'k	"%3		QS		2	"@HCacA@"	"'		QS		; ;,a7TLANG0,aGTLANG0QacA@A@Q	@A@,a7TLANG0,aGTLANG0Qac: :	A@A@Q	@,a
@(TLANG0,aKTLANG0	A
,a7TLANG0,aGTLANG0	QacA@9 9A@Q	@A@	i,a7TLANG0,aGTLANG0QacA@A@Q	@A@zA: :	'@H(LBF	"@HCac A@"	")		QS		,a7TLANG0,aGTLANG09 9QacA@A@Q	@,a
@(TLANG0,a7TLANG0,aGTLANG0QacA@A@Q	@: :A@,a7TLANG0,aGTLANG0QacA@A@Q	@A@	)@H*L"R: ::	"QS		!!
!!!!!!	!                                 !!9 97^!*$TLANG0!"$TLANG0!$$TLANG0!($(TLANG0!$(TLANG0!#GETSYM! #YSELE0!&#SETF !,#XSELE0
 
"%2,0&s"$ XSELE0; ; DS$MEM(aTLANG0		X input must be 0.	A",aK(TLANG0	C		",aK(TLANG0	A
: :acC@	@ ,aS(TLANG0ac         "@HC,aK(TLANG0	A		"	,aS(TLANG07 7ac(	A$"52,a_(TLANG0	C		"	,aS(TLANG0ac8	"@HC9 9,aK(TLANG0	@HC		"	,aS(TLANG0acH	"@HC,aK(TLANG0	C		"9 9,aS(TLANG0acX	"@HC,aK(TLANG0	C		"A,aS(TLANG0acgbSC5 54$	"QS		!s!!!!!!&s!$(TLANG0! $(TLANG0!$(TLANG0!#ERRMSG! #GETSYM
 
"%($0&(
$ YSELE09 9 DS$MEM(aTLANG0	@ ,aSTLANG0	A",aK(TLANG0	C		",aK(TLANG0	A	@ 9 9,aS(TLANG0,aK(TLANG0	@HC		,aS(TLANG0	Y-select must be 0 or : :1.acC@ac
	"@HC,aK(TLANG0	C		"	,aS(TLANG0ac9 99	"@HCacA@"	"#		QS		K	#%TL	"@HC,aK(TLANG0	9 9	C		"	,aS(TLANG0ac\	"@HC,aK(TLANG0	C		"	,aS(TLANG09 9acl	"@HC,aK(TLANG0	C		"		,aS(TLANG0ac|wgWD4	"QS8 8		!!!!                                 !	!!&!,!1!$TLANG0! % %$(TLANG0!$(TLANG0!$(TLANG0!"#ERRMSG!$#GETSYM!&#BMCL
 
"%($0&
SH4 BINAT07 7 DS$MEM(aTLANG0"
		ac A@"	"#		QS		: :,a7"TLANG0,aG$TLANG0Qac&A@A@Q	@,a
@((TLANG0	#@H$L9 9	"C	A",aK*(TLANG0	C		"ac,.	"C	A",aK*(TLANG0	C< <		"A%ac,=	@ %D	"&		"I	&%QJL	"%U		QS: :		Tac.A@"	"'		QS		,a7"TLANG0,aG$TLANG0Qac&A@A@Q	@9 9,a
@((TLANG0,aK0TLANG0	A
	%A%w_	'@H(L`d{	"%		9 9QS			A",aK*(TLANG0	C		"%A
,a7"TLANG0,aG$TLANG0Qac&; ;A@A@	Q	@A@
,a7"TLANG0,aG$TLANG0Qac&A@A@	Q	@A@'ac,; ;         %A
,a7"TLANG0,aG$TLANG0Qac&A@A@	Q	@A@=,a7"TLANG0: :,aG$TLANG0Qac&A@A@	Q	@A@N:	adder op must be 'x+y+1'. _	"C	A9 9	",aK*(TLANG0	C		",aK2(TLANG0	%
ac4C@`~ac,w	adder : :
op must be 'x+y+1'. ac4C@	"%		QS		p	")		""	)9 9	%*#%	"%.		QS		-6	"@HC,aK*(TLANG0	C		"ac,9 9:	"C	A",aK*(TLANG0	C		"A%ac,I	@ %P	"*		"< <U	*%]VX	"%a		QS		`ac.A@"	"+		QS		,a7"TLANG09 9,aG$TLANG0Qac&A@A@Q	@,a
@((TLANG0,aK0TLANG0	A
	%A%k: :	+@H,Llp	"%		QS			A",aK*(TLANG0	C		"%A
< <,a7"TLANG0,aG$TLANG0Qac&A@A@	Q	@A@",a7"TLANG0,aG$TLANG0Q; ;ac&A@A@	Q	@A@3ac,	%A
,a7"TLANG0,aG$TLANG0	Qac&A@9 9A@	Q	@A@I,a7"TLANG0,aG$TLANG0Qac&A@A@	Q	@A@
ZF	ad: :der op must be 'x-y-1'. k	"C	A",aK*(TLANG0	C		",aK2(TLANG0	%; ;ac4C@l
ac,	adder op must be 'x-y-1'. ac4C@         "%(		QS; ;		'|	"-		".	-%6/1	"%:		QS		9B	"@HCac69 9A@"	".		QS		,aK((TLANG0	/H	.@H0LIMP	"C	A9 9	",aK*(TLANG0	C		"A%ac,b	@ %i	"1		"n	1%vo: :q	"%z		QS		yac.A@"	"2		QS		,a7"TLANG0,aG$TLANG0: :Qac&A@A@Q	@,a
@((TLANG0,aK0TLANG0	A
	%A%	%A
	t/aK	/: :",a7"TLANG0,aG$TLANG0Qac&A@A@	Q	@A@/	2@H3L	7	": :	%C		QS		B[A5	"%K		QS		J'	"QS		!!!9 9!!	S!S!S!
S!                                 !!!-!7!: :;S!@$TLANG0!2$TLANG0!4$TLANG0!8$(TLANG0!:$(TLANG0!B$(TLANG0!0#XSELE0!6#SETF !<#GETSYM!>#YSELE0!D#ERRMSG!F#OPERA0
 
"%:40&C,$ OPERA06 6 DS$MEM(aTLANG0	A",aK(TLANG0	C		"	,aS(TLANG0ac	"@HC9 9,aK(TLANG0	C		"	,aS(TLANG0ac	"@HC,aK(TLANG0	C		": :		,aS(TLANG0ac'	"@HC,aK(TLANG0	C		"A,aS(TLANG0ac7	"9 9	@HC,aK(TLANG0	C		"		,aS(TLANG0acG	"@HC,aK(TLANG0	
C; ;		"	,aS(TLANG0acW	"@HC,aK(TLANG0	C		"	,aS(TLANG0ac9 9g	"@HC,aK(TLANG0	C		"	,aS(TLANG0acw	"@HC,aK(TLANG0: :	C		"	,aS(TLANG0ac	"@HC,aK(TLANG0	                                                                   		"	,aS(TLANG07 7ac	"@HC,aK(TLANG0	C		"	,aS(TLANG0ac'	"@HC		: :,ag(TLANG096	"	,aS(TLANG0ac82"rbRB2"	"QS		!!9 9!!!!!	!	!
!!!!        !!4!
1 15!6!8!9!:!>!KC!($(TLANG0!&$(TLANG0!*#GETSYM
 
"%($0&5$ SHIFU09 9 DS$MEM(aTLANG0	@ ,aS(TLANG0	A",aK(TLANG0	C		"A,aS(TLANG0ac
9 9	"@HC,aK(TLANG0	C		"	,aS(TLANG0ac	"@HC,aK(TLANG0	9 9	C		",aS(TLANG0ac*%	"QS		!!5!!)!?5 !$(TLANG0!$(TLANG0!#GETSYM
 
"%($0&z ( DESTI09 9 DS$MEM(aTLANG0	@ ,aSTLANG0,aSTLANG0,aSTLANG0	A",aK(TLANG0	C		; ;	"ac	"CacA@"	"#		QS			#%&	"%*	$9 9		"+	$%3,.	"%7		QS		6	"@HCacA@"	"%: :		QS		E	%%NF	"CacA@"	"&		QS		X	&%aY	"9 9	%eR	'		"f	'%ngi	"%r		QS		qQ>	"QS9 9		!!!z!z!$TLANG0!$TLANG0!$TLANG0!$(TLANG0!#GETSYM !#DESTJ0
 
"%,(0&>* DESTJ09 9 DS$MEM(aTLANG0	A",aK(TLANG0	A		",a7TLANG0,aGTLANG0	QacA@: :A@Q	@A@ac	A$" ,a_(TLANG0	C		",a7TLANG0,aGTLANG09 9QacA@A@Q	@A@ac#	"@HC,aK(TLANG0	@HC		",a7TLANG09 9,aGTLANG0QacA@A@Q	@A@ac@	"@HC,aK(TLANG0	C		"9 9,a7TLANG0,aGTLANG0QacA@A@Q	@A@ac]	BR may not be used with MA: :R.r	"@HC,aK(TLANG0	C		",aKTLANG0	A
acC@s,a7TLANG09 9,aGTLANG0QacA@A@Q	@A@,a7TLANG0,aGTLANG0QacA@	A@: :Q	@A@
	A,aSTLANG0ac		BR may not be used with MAR.9	"@HC,aK(TLANG09 9	C		",aKTLANG0	A
acC@:V,a7TLANG0,aGTLANG0	QacA@< <	A@Q	@A@,a7TLANG0,aGTLANG0QacA@	A@Q	@A@
	A,aSTLANG0ac; ;P	"@HC,aK(TLANG0	C		",a7TLANG0,aGTLANG0QacA@A@Q	@9 9A@ac	"@HCac A@"	"#		QS		,a7TLANG0,aGTLANG0Q9 9acA@A@Q	@,a
@"(TLANG0'	#@H$L(,<	"@HCac$A@"	"%9 9		QS		N	%%WO	"@HCac&A@"	"&		QS		a	&%j9 9b	"@HCac(A@"	"'		QS		,a7TLANG0,aGTLANG0	QacA@9 9A@Q	@,a
@"(TLANG0t	'@H(Luy	mZG KX;	"QS		!
9 9!!!!        !!!!"!#!$!%!)!*!+8 8!,!	-!.!1!.$TLANG0!2$TLANG0!&$TLANG0!($TLANG0!6$(TLANG0!$/ /$(TLANG0!*#SETF!,#GETSYM!0#ERRMSG!4#INPUTB!8#INPUT0!:#INPUU0!<#INPUV0
 
"%0*0&s 
$ INPUTB6 6 DS$MEM(aTLANG0	A",aK(TLANG0	C		"	,aS(TLANG0ac	"@HC9 9,aK(TLANG0	C		"	,aS(TLANG0ac	"@HC,aK(TLANG0	C		": :		,aS(TLANG0ac'	"@HC,aK(TLANG0	C		"	,aS(TLANG0ac7	"9 9	@HC,aK(TLANG0	C		"	,aS(TLANG0acG	"@HC,aK(TLANG0	C; ;		"	,aS(TLANG0acW	"@HC,aK(TLANG0	C		"		,aS(TLANG0ac9 9gbRB2"	"QS		!s!!	!
!!!!!	!      s!$(TLANG0!$(TLANG0!#GETSYM
 
"%($0&
.*
$ INPUT05 5 DS$MEM(aTLANG0	CTR may not be used with a MAR. 	A",aK(TLANG0	C		"9 9,aKTLANG0	A
acC@,a7TLANG0,aGTLANG0QacA@A@Q	@A@; ;	A,aSTLANG0ac	LCTR may not be used with a MAR.8	"@HC,aK(TLANG0	C9 9		",aKTLANG0	A
acC@9W,a7TLANG0,aGTLANG0QacA@A@Q	@< <A@	A,aSTLANG0acQ	INC may not be used with CTR or LCTR. q	"@HC,aK(TLANG09 9	C		",aKTLANG0	A
acC@r,a7TLANG0,aGTLANG0	QacA@: :A@Q	@A@acL	"QS		!!!.!!!!%!9 9.!/.!$TLANG0!&$TLANG0! $TLANG0!"$TLANG0!$(TLANG0!#ERRMSG!$#SETF!( #GETSYM
 
"%*$0&
O,
$ INPUU0< < DS$MEM(aTLANG0	MAR may not be used with CTR. 	A",aK(TLANG0	C		",aKTLANG08 8	A
acC@	MAR may not be used with BR.",aKTLANG0	A
acC@#4	A9 9,aSTLANG0,a7TLANG0,aGTLANG0QacA@A@Q	@A@ac 	MAR may no9 9
t be used with CTR. N	"@HC,aK(TLANG0	C		",aKTLANG0	A
acC@O5 5l	MAR may not be used with BR.q,aKTLANG0	A
acC@r	A,aSTLANG0; ;,a7TLANG0,aGTLANG0QacA@A@Q	@A@,a7TLANG0,aGTLANG0Qac9 9A@A@Q	@A@ac f	MAR may not be used with CTR. -	"@HC,aK(TLANG0	C9 9		",aKTLANG0	A
acC@.K	MAR may not be used with BR.P,aKTLANG0	A
9 9acC@Qb	A,aSTLANG0,a7TLANG0,aGTLANG0QacA@A@Q	@A@; ;ac E	MAR may not be used with CTR. |	"@HC,aK(TLANG0	C		",aKTLANG08 8	A
acC@}	MAR may not be used with BR.,aKTLANG0	A
acC@ 1	A: :,aSTLANG0,a7TLANG0,aGTLANG0QacA@A@Q	@A@ac @a	"QS9 9		!!!O!!'!*!+!,!-O!"$TLANG0! $TLANG0. .!$TLANG0!$$TLANG0!&$TLANG0!$(TLANG0!#ERRMSG!(#SETF!*#GETSYM
 
"%*$0&
#$ INPUV06 6 DS$MEM(aTLANG0	A",aK(TLANG0	C		"	,aS(TLANG0ac	"@HC: :,aK(TLANG0	C		"A,aS(TLANG0ac	"QS		!!#!! A#!$(TLANG0!$(TLANG0!#GETSYM
 
"%($0&$$ SUCCF0: : DS$MEM(aTLANG0	A,aS(TLANG0	",aK(TLANG0	C		"@ ,aS(TLANG0ac		"9 9	@HC,aK(TLANG0	C		"A,aS(TLANG0ac	"@HC,aK(TLANG0	C: :		"	,aS(TLANG0ac)	"@HC,aK(TLANG0	C		",aS(TLANG0ac9 99	"@HC,aK(TLANG0	C		"	,aS(TLANG0acH	"@HC,aK(TLANG0: :	C		"		,aS(TLANG0acX	"@HC,aK(TLANG0	
C		"	,aS(TLANG0; ;ach	"@HC,aK(TLANG0	C		"	,aS(TLANG0acxscSC4$	"QS9 9		!!!!	!!!
!!!=!B!D!F! I!$(TLANG0! $(TLANG0!"#GETSYM
 
"%($0&* CONDI09 9 DS$MEM(aTLANG0	acA@"	"#		QS			#%	"CacA@"9 9	"$		QS			$%#	"%		"%	%%-&(	"%1: :		QS		0acA@"	"&		QS		;	&%D<	"'		"F	': :	%NGI	"%R		QS		Q	"@HCacA@"	"(		QS		`< <	(%ia	"CacA@"	")		QS		s	)%|t	"%		QS5 5		lY	"QS		!!!!#IFCLA0!#THENC0!#ELSEC0!#WHENC0
 
"%.*0&+$ IFCLA09 9 DS$MEM(aTLANG0	A",aK(TLANG0	C		"ac	"CacA@"	"#: :		QS			#%	"%#		QS		"	"QS		!!+! +!$(TLANG0!#GETSYM!#CONDK0
 
"%($0&x(& CONDK0: : DS$MEM(aTLANG0	A",aK(TLANG0	C		",a7TLANG0,aGTLANG0	QacA@9 9A@Q	@A@ac,a7TLANG0,aGTLANG0QacA@A@Q	@A@	"9 9	#		"/	#%702	"CacA@"	"$		QS		missing : :condition.FacC@G,a7TLANG0,aGTLANG0QacA@A@Q	@,a
@(TLANG09 9TA	$LFBUe	"%p		QS		o:	"QS		!!!< <!!!!7x!$TLANG0!$TLANG0!&$(TLANG0!$(TLANG0!#SETF! #GETSYM !"#BASIC0!$#ERRMSG
 
"%,&0&*& BASIC09 9 DS$MEM(aTLANG0"	A",aK(TLANG0	C		"	,aS(TLANG0ac	"9 9	@HC,aK(TLANG0	C		"	,aS(TLANG0ac	"@HC,aK(TLANG0	C; ;		"	,aS(TLANG0ac'	"@HC,aK(TLANG0	C		"	,aS(TLANG0ac9 97	"@HC,aK(TLANG0	C		"	,aS(TLANG0acG	"@HC,aK(TLANG0: :		C		"	
,aS(TLANG0acW	"@HC,aK(TLANG0	C		"	,aS(TLANG09 9acg	"@HCacA@"	"#		QS		,aw(TLANG0aK,aS(TLANG0: :y	#@H$Lz~rbRB2"	"QS		!!!!!!!9 9!
	!
!!(!1!<!	@!$$(TLANG0!"$(TLANG0!&#GETSYM!( #CONDJ0
 
"%*&0&;& THENC0: : DS$MEM(aTLANG0		,aS(                                                                                    LANG0	A",aK(TLANG0	C		"ac
	"Cac: :A@"	"#		QS			#%"	"%&	$		"'	$%/(9 9*	"%3		QS		2	"QS		!!!;!H;!$(TLANG0 !$(                                                                                    LANG0!#GETSYM!#COMPO0
 
"%*&0&?"& ELSEC09 9 DS$MEM(aTLANG0	A",aK(TLANG0	C		"ac	"CacA@"	"#9 9		QS		,a7TLANG0,aGTLANG0QacA@A@Q	@,a
@(TLANG0	#@H: :	$L+	"%7		QS		6	"QS		!!?!!0 0?!$TLANG0!$TLANG0! $(TLANG0!$(TLANG0!#GETSYM!#SUCCF0!#SETF
 
"%,&0&;"$ WHENC0: : DS$MEM(aTLANG0	A",aK(TLANG0	C		",a7TLANG0,aGTLANG0	QacA@; ;A@Q	@A@ac	"CacA@"	"#		QS		&	#%/'	"%3: :		QS		2	"QS		!;!!;!!J;!$TLANG0! $TLANG0!$(TLANG0!#SETF!#GETSYM! #CONDK0
 
"%*$0&`&& BINAS09 9 DS$MEM(aTLANG0	AQS,aK(TLANG0	C,aK(TLANG0	A
		,aK(TLANG09 9	%	A
	%	%	%	%!		 ac,a
@(TLANG09 9	A@Q@A@,aK(TLANG0	",aK(TLANG0	#,aK(TLANG0	$acacQ	@QK	@HC9 9,aK(TLANG0	%E	%HDG		QSH?	acQ@A@,a
@(TLANG09 9A@	",aS(TLANG0	#,aS(TLANG0	$,aS(TLANG0		!!!`!!9 9!&!-!;`!$(TLANG0!$(TLANG0! $(TLANG0!$(TLANG0!#SCOPY !"#GETSYM !$#OPERA0
 
"%&0&G( BITFI0: :	QK	@H"M=B#t#QK	$#@HADQK		#"M=@A%#acA@%	&%	Qg&&9 9Q_	"&acA@"	'	%QK	%"&acA@"	&	""$acA@"	$A	&	'	 !!#F$RT!#F$RS!#F$LS
 
"%2(0&

t2& BMCL: : DS$MEM(aTLANG0"0tf1	AQS,aK(TLANG0	C,aK(TLANG0	C: :		aca@,a
@(TLANG0	"aca@,a
@(TLANG0	#aca@,a
@ (TLANG0	$9 9	"A
	#A
'	$A
*,aK"(TLANG0	A-1		2	
"@H"#@H#$@H$	QS	"6 6	C;A	$,aS$(TLANG0,aK(TLANG0	C,aK$(TLANG0A
,aS$(TLANG0J9 9,aK(TLANG0	C,aK$(TLANG0	A,aS$(TLANG0	A,aS&TLANG0V,aK(TLANG0: :	C,aK$(TLANG0	AA
,aS$(TLANG0	A,aS&TLANG0e`Qac(		!t!6 6! !ct!1!b!f!tt!.$TLANG0!,$(TLANG0!$(TLANG0! . .$(TLANG0!$$(TLANG0!&$(TLANG0!($(TLANG0!*$(TLANG0!"#INDEX !0#GETSYM
 
"%*&0&L@$ ERRMSG: : DS$MEM(aTLANG0"	******  "*i:  " """"  *p*n	7 7,aK*TLANG0	A,aK,TLANG0	Aac.a@A@		ac0A@a@: :,a
@2(TLANG0	ac0A@a@ ,aK4(TLANG0	ac6A@	"	("@'	t",aK8(zTLANG0< <	%0,aK4(TLANG0	"C/,aw4(TLANG0,aG8(zTLANG0Qac:Q	@A@(5ac05 5	A@a@"Q	@		!uL!L!L!
L!.$TLANG0!0$TLANG0!6, ,$(TLANG0!8$(TLANG0!<$(zTLANG0!2#PUTLIN!4#PRINT !:#F$MA11!>#PUTCH 
 
"%*$0&5,$ FINDL0; ; DS$MEM(aTLANG0	@ ,aSTLANG0ac,a
@({TLANG0,a
@TLANG0	%ac,a
@({TLANG0; ;A@	A,aS(TLANG0	acacA@"	"Cac ,a
@"(TLANG0,a
@TLANG0,a
@$(TLANG0: :acac,aK&(TLANG0	%0,akTLANG0	@/		!5!!5 55!G5!$TLANG0!$TLANG0!*$(TLANG0!$(TLANG0!($(TLANG0!&$(TLANG0!$ $$({TLANG0!#GETLIN!#MAPSTR! #GETSYM!"#LABEM0!$#ENTER 
 
"%$$0&)
$ GETOP09 9 DS$MEM(aTLANG0"+Usage: translang [-{l|b}] <input_file> [-h : :<hex_file>]"Hl<flag> b<flag> h<req str>"d.h"h: :.h	acla@HQ@	Cacna@acpA@Q@HA@	BCacna@; ;	acrQ@HA@,aStTLANG0	CacvQ@H&acpA@A@"A@	%
6acna@9 95Q	A
Q!	ADQGQ|acxQ	@|A@Q@HA@=aczQ@H	"	"9 9	@H"U	A$"	@t"QKG	%c[Vb	"%
faczQ@H	B#	acxa@dA@: :Q@HA@#gacxa@hA@Q@HA@"xO	ac|Q@HA@,aS~TLANG0	Cacv6 6Q@HQ	A
	A,aSTLANG0	@ ,aSTLANG0Q	A
	A: :,aSTLANG0 	@ ,aSTLANG0$		!}!)!!)!.!4): :!z$TLANG0!$TLANG0!$TLANG0!$TLANG0!x#OPEN!#CREATE!v#GETARG!#LENGTH!r#PARSCL !t#ERROR !|#CANT!~#SCOPY 
 
"%"$0&t& GETSYM9 9 DS$MEM(aTLANG0"+a1a2a3aadabtampcrandaovb	9 97bad
bbabbebbibexbmibr1br2ccallGcommen9 97tGcommntcompcovcsarctrelseGendeqvexec9 97ifimpincjump)l"lc1#lc2$lc3%lctr&lit'lmar(9 97lst,mar*mar1+mar2.mir/mr10mr21mst2mw13mw24nan9 975nim6nor7not8nri9oad:or?r<rdc=retn>rim@saiA9 97sarBsaveCsetDskipEslitFstepHthenIwaitJwhenKxor9 9"1H	#(+05:?DINSV\emsx~	"'-05:?EJPUZ`fkpu: :z	"&).49>CINTZ`flr,awP(TLANG0,aKR(zTLANG0	C,akP(TLANG09 9,awP(TLANG0,aKR(zTLANG0	"	A#,awP(TLANG0,aKR(zTLANG0	%7 7	%	@,awP(TLANG0,aKR(zTLANG0	%''	%&	@(*< <,awP(TLANG0,aKR(zTLANG0	t#,aST(TLANG0	(#@,akP(TLANG0+	@ t#,aST(TLANG0acV5 5	a@a@A@,a
@X(TLANG0	#BC		,aSZ(TLANG0J	t#aK	ADaK9 9,aSZ(TLANG0N		,aSZ(TLANG0ac\,a
@^({TLANG0,a
@P(TLANG0,aS`(TLANG0W		7 7,aSZ(TLANG0c			,aSZ(TLANG0,akP(TLANG0gm		
,aSZ(TLANG0,akP(TLANG0	@: :,awP(TLANG0,aKR(zTLANG0	C		,aSZ(TLANG0,akP(TLANG0	@{n		,aSZ(TLANG09 9,akP(TLANG0		,aSZ(TLANG0,akP(TLANG0	,akP(TLANG0: :	"%d	$LX*dd !"#ho$XXXXXXXXX: :8X)5
689:;<=>?@ABCDEFGHIJKLM: :8NOPQRSTUVWXY: :                           Z	illegal character encountered.uacbC@v	9 9		!!!! !!!
-!	;!G!
9 9! !#!0!9!>!a!z!j$(TLANG0!p$(TLANG05 5!`$(TLANG0!d$(TLANG0!h$(TLANG0!b$(zTLANG0!n$({TLANG0!l#CTOI!f#STRBSR!r#ERRMSG
 
"%&&0&" INITI09 9 DS$MEM(aTLANG0acA@acA@,aS(TLANG0		!! !$(TLANG0!#MKTABL !#DSINIT
 
"%""0&$ INSER0$ $	QK	"QK	C?A	"	#	!|!
 
"%($0&? & LABEM09 9 DS$MEM(aTLANG0	,aK(TLANG0	%	AQS		ac,a
@(TLANG0A@Q@; ;A@,aK(TLANG0	",aK(TLANG0	#,aK(TLANG0	$ac,aK(TLANG0	C		QS: :#	AQS'	acQ@A@,a
@(TLANG0A@	",aS(TLANG0	#,aS(TLANG0	$6 6,aS(TLANG0		!!?! !!?!$(TLANG0!$(TLANG0!$(TLANG0! $(TLANG0!#SCOPY !#GETSYM
 
"%&0&U&& LITET07 7 DS$MEM(aTLANG0	ac,a
@(TLANG0	A@Q@A@,aK(TLANG0	",aK(TLANG0	#6 6,aK(TLANG0	$acA@%	%C,aK(TLANG0	%!	AQS ac9 9,aK(TLANG0	%,	%/+	%2.	%514		QS5	AQS; ;9$	AQS=	acQ@A@,a
@(TLANG0A@	",aS(TLANG0	#,aS(TLANG06 6	$,aS(TLANG0		!!U!!!&!A!EU!$(TLANG0!& &$(TLANG0! $(TLANG0!$(TLANG0!#SCOPY !"#LITEU0!$#GETSYM
 
"%&0&2 MICRQ09 9 DS$MEM(aTLANG0"*4i|  *4,-16,0i  *s*n"&*13x*16,-2,0i*n9 9"6"*13x*3,2,0u*4i *i *i *i *i *i *8i"X*x*4,2,0u*i 9 9*2i *3i *i *2i *i *i *i*1n"*n"*n*nHex Transla9 9
tion:*n*n"*4,-16,0u*i   *i"0*4,-16,0u   *i *i 8 8*i *i"H*n	@ ,aSL(TLANG0,aSNTLANG0,aSPTLANG0acR,a
@T({TLANG06 6,a
@VTLANG0	%acX,a
@T({TLANG0A@,akL(TLANG0	@,aKZTLANG0	A: :,aK\TLANG0	A 	ac^A@a@,a
@L(TLANG0,a
@NTLANG0,a
@T({TLANG0!	un; ;recognizable or incomplete statement. .,aKNTLANG0	",aKPTLANG0	#A,aS`(TLANG0acbacd: :A@$,aKf(TLANG0	%
WachC@/V,aK\TLANG0	A
	",agNTLANG0d^	t": :,aGjTLANG0Qac^A@a@&Q	@c,aK\TLANG0	A
	#,agPTLANG0ztA7	#9 9,aGlTLANG0Q,aGlTLANG0Q,aGlTLANG0Q,aGlTLANG0Q,aGlTLANG0: :Q,aGlTLANG0Q
,aGlTLANG0QacnA@A@Q	@	%acnA@A@Q	@
	&; ;acnA@A@Q	@	'acnA@	A@Q	@	(acnA@A@Q	@	)acnA@
A@Q	@< <	*acnA@A@Q	@	+!ac^A@a@6A@+A@*A@)A@(A@'A@&A@%A7	#,aGlTLANG05 5Q,aGlTLANG0Q,aGlTLANG0Q,aGlTLANG0Q,aGlTLANG0Q: :,aGlTLANG0Q
,aGlTLANG0Q,aGlTLANG0QacnA@A@Q	@	%acnA@; ;A@Q	@	&acnA@A@Q	@
	'acnA@A@Q	@	(acnA@A@Q	@	)acn; ;	A@A@Q	@	*acnA@A@Q	@	+acnA@A@Q	@	,ac^A@a@XA@,A@+< <A@*A@)A@(A@'A@&A@%y,aK\TLANG0	A
	#,a_PTLANG0	C	",a_NTLANG09 9	Csnx	ac^A@a@y,aKZTLANG0	A
ac^A@a@		-A.: :,aKpTLANG0	-	.			@ /	(/@	/,agNTLANG0	t/,aGjTLANG0: :Qac^A@-a@A@/Q	@	t/,aGjTLANG0QacnA@A@Q	@	CacnA@
: :A@Q	@	0A7	0,aGlTLANG0Q,aGlTLANG0Q,aGlTLANG0Q,aGlTLANG0; ;QacnA@A@Q	@	%acnA@A@Q	@	&acnA@A@Q	@	'	acnA@A@: :Q	@	(ac^A@-a@0A@(A@'A@&A@%?ac^A@-a@H 	.L: :!u!!!!!!
!!	!!!!9 9!                                 !! !!!"!        %!)!+!/!1!3!8 8G!p$TLANG0!
$TLANG0!t$TLANG0!v$TLANG0!h$TLANG0!j$TLANG0!$TLANG0!: :$TLANG0!$(TLANG0!f$(TLANG0!z$(TLANG0!n$({TLANG0!l#GETLIN!#BITFI0!r#MAPSTR!x#PRINT  !|#GETSYM!~#INSTR0!#ERRMSG
 
"%B20&

k( SETF9 9!	QK	@H"M=B#	QK	acQ	@	$"M=@A%Q_	C	#@H"%Q_< <	&$acA@&	'	acQ	@acA@&	At"QOA	'QS	#@H"QK	%&$ac9 9A@&	'	acA@%	At"	QOA	'QS		&"$acA@"	"	acA@&	At#QO$ $A	"QS9		!!#F$RT!#F$LS!#F$RS!#F$LT
 
"%4(0&	" TRANS09 9 DS$MEM(aTLANG0acac,a
@TLANG0ac		!$TLANG0!#FINDL0!#REWIND!#MICRQ0
 
"%""0&