z@,9 9"5Usage: last [-t ] [ -c] [-l<#>] [-v] [-n<#> | -n | {<9 9pathname>}]"Rl<ri>v<f>t<f>c<f>n<ign>"j*s: "p; ;error in "last"."*6l" lines | *s"*nQ9 9	%		Q%	aca@RQ@	Caca@Q	A
Q%	": :		"Q	A
#$Q	A
%#AA	%	&AQb	@ '	acQ@.Q@b	BCac; ;:	acQ@.A@	(Cac Q@.Fac"A@(	@HCac$A@	)	ac&A@(A@); ;	)(A'Q	error in mapfd. aac(A@(ac*A@(ac,A@(	*CacC@byac.9 9	A@*A@"Qf	Aac0A@a@jQ@.aca@p	$A
ac0A@a@Q@fQ; ;	A
ac0A@a@Q@."	ac0A@a@Q	AA	$	Aac0A@A@Q@.; ;7	&A
	"Aac&A@(A@Eac(A@(	A)	()@S	")Cac2Q@H: :A@(A@	BCYdac4Q@HA@TeLB	'@HCac6A@(p0!q!; ;u!}v!!!v!v!fv= *s*n.  !&#OPEN!4#MAPFD !*#ISATTY: :!"#GFNARG!,#MKTEMP!:#GETLIN!6#LAST!#PARSCL! #ERROR !$#SWT !(#CANT!.#FCOPY !0#REWIND !2#FLUSH$!8#PRINT !<#PUTLIN!>#RMTEMP
 
"%,0&