H
&9 9"=vars=/*s/.vars" can't open *s*n"0*s*n"6_: :eof"<_erase"D_escape"L_kill"R	_newline9 9"\_retype"d*s*n"j*s*n"p_kill_resp"|*s<L9 9F>*n"*s*n"*s*n"*s*n"<*s>*n	can't ; ;
open temporary file ac A@	"Cac"C@ac$Q@A@A@	%%ac&9 9Q@	AD@ QSac(Q@fA@a@Q@ac*Q@fA@	#Cac,A@a@ Q@f; ;@$ac,A@a@0Q@ac.A@"ac0A@"ac$Q@A@#A@	%
eac&Q@	ADQK; ;	Cac&Q@	AD@ QSn$ac$Q@fA@#A@ac$Q@fA@#A@ac$Q@f: :2A@#A@	ac$Q@fA@#A@ac$Q@fA@#A@ac$Q@fA@#A@$-ac,9 9A@"a@dQ@w	ac2a@6Q@	%@xac2a@<Q@	%Iac2a@DQ@; ;	%R
ac2a@LQ@	%[ac2a@RQ@	%dac2a@\Q@	%m%ac,< <A@"a@jQ@ac$Q@fA@#A@ac&Q@f	ADQKe	Cac&Q@f	AD@ QSeac29 9a@pQ@	@HCac,A@"a@|Q@fac,A@"a@Q@f Z6ac&Q@f9 9	ADQKe	Cac&Q@f	AD@ QSe3ac&Q@f	%	@ac,A@"a@Q@fZ; ;A	A$ac4Q@fA@$A@		%Aac,A@"a@Q@fXac,A@"a@Q@faZ9 9dac.A@#ac.A@"ac6A@"A@#ac8A@#$	ac:A@"ac<!q!u!v: :!}!!	!!!f!
!>#MNTOC !4#OPEN!*#MKTEMP!<#EQUAL !0; ;#LENGTH!.#GETLIN!,#ERROR !2#ENCODE!6#PRINT !8#REWIND!:#TRUNC !@#FCOPY !B#CLOSE !D#RMTEMP !F#SWT 
 
"%r&0&
