X6&9 9VCGCM3}hVCGCM2zVCGCM1=VCGCOM"[-m<rs>][-s<os>][-b<os>]"**s.9 9s"0*s.b"6/dev/stdout1"D/dev/stdout1"R*s9 9.ct1"Z*s.ct2"b*s.ct3"j*s.b"p/dev/stdout9 91	"Usage: vcg [-m <file_basename>] [-b [<obj_file>]] [-s [<asm_file>]].	ac~a@Q@	9 9	CacC@+	Vcg: input is STDIN, but no object file named@..0Q	AQ	A< <LQ	APacC@1TQ	A
Q&	ADQGQHacQ	@HQ@bA@	@ "Q: :	A
acQ@HA@a@*Q@bQ	%
Q4Q,	ADQGQHacQ@HQ	@HA@; ;	BQ4Q4qQ	A
acQ@HA@a@0Q@bQ	%
*Q4Q	ADQG9 9QHacQ@HQ	@HA@	BQ4Q4)	@ QH\	Vcg: input is STDIN, but no ob9 9	ject file named@..D	A"Q	A
Q	ADQGQHacQ	@HQ@HA@QH	A< <acC@EubQ	A
	%
Q4Q,	ADQGQHaca@6Q	@HA@	BQ4: :Q4}C	@ ,aSVCGCOM	A,aS<VCGCOMQ	A
	A,aS
;VCGCOM	@ ,aS<VCGCOM5 5 Q	A
	A,aS<VCGCOM*	"@HC		,aSVCGCOM		,aSVCGCOM		: :,aSVCGCOM,aK<VCGCOM	@HCQ	ADQGQHacQ	@HQ@HA@acQ@HA@	#; ;	CacQ@HXacA@#acA@#?,aK
;VCGCOM	@HCQ,	AD	QGQHac9 9Q	@Ha@DA'|y		,aSVCGCOM{Q,	ADQGQHacQ	@HQ@HA@; ;	acQ@HA@,aSVCGCOM	CacQ@Hac,a
@VCGCOMi1acQ@H: :A@a@RQ@bacQ@HA@,aSVCGCOM	CacQ@H7acQ@HA@a@ZQ@b: :	acQ@HA@,aSVCGCOM	CacQ@HPacQ@HA@a@bQ@bacQ@HA@9 9,aSVCGCOM	CacQ@Hi,aK<VCGCOM	@HCQ	A
Q	ADQGQH; ;acQ	@HQ@HA@vacQ@HA@a@jQ@b	acQ@HA@	#CacQ@H: :acA@#acA@#r,aK
;VCGCOM	@HCQ	A
Q,	ADQGQHacQ	@H; ;a@pG'xA/@		,aSVCGCOMAQ,	ADQGQHacQ	@HQ@HA@ac6 6Q@HA@,aSVCGCOM	CacQ@H_ac,a
@VCGCOME+",aKVCGCOM9 9,aSVCGCOMac A@$		Cac",aKVCGCOM,aSVCGCOMlr	expected MODULE 9 9in ENT stream, found *i*n.z	$A
	%
ac$C@{A@$	Not all of IMF consumed*n.9 9ac&Q@|,a
@VCGCOM	%
3ac$C@2	Code generation terminated abnormally.7: :,aKVCGCOM	A
acC@8Nac(!r!t!u!v!}!U!!9 9U!	 !
'U!fU!HU>@!$VCGCOM!($VCGCOM!*$VCGCOM!: :$VCGCOM!$VCGCOM!$VCGCOM!$;VCGCOM!$<VCGCOM!2#GETLIN!,#GET !#OPEN!
#PARSCL!8 8#CTOC!#ERROR !#ENCODE! #CANT!"#TRUNC !$#INITO0!&#EQUAL !.#MODULE!0#WARNI0!4#SWT 
 
"%p&0&