$" INITO06 6OOTGCOM	QK,aS@OTGCOM	@ ,aSNOTGCOM,aSIOTGCOM,aSJOTGCOM,aSKOTGCOM6 6,aSLOTGCOMacacac ac"		!$@OTGCOM!$IOTGCOM!$JOTGCOM!$KOTGCOM!% %$LOTGCOM!$NOTGCOM!#CLEAU0!#CLEAW0! #CLEAS0!"#CLEAR0
 
"%&"0&

 $ OTG 9 9	QK	"	
otg: missin parm*n. acQ	@		A
acC@	acQ	@Q	@; ;Q	@	acQ	@Q	@"acQ	@)	
otg: missin parm*n. /acQ	@	A
acC@09 9?acQ	@.acQ	@		A
acQ	@Q	@HNacQ	@Q	@Q	@	U	otg: m9 9issin parm*n. _acQ	@	A
acC@`oacQ	@^	otg: bad instr type *i*n< <. y	"L#*/I_acC@zQ	@x		!#MISSIN!#PANIC !#OTGBR0!#OTGMR  !#OTGLA0!#OTG$L0!#OTGMI0!#OTGPS0
 
"%0$0&M$ OTGBR09 9OOTGCOM	QK	C	uQK	A
	otg_branch: bad addr descr*n. ac: :C@QK	C%acQ	@Q@
A@"A@acQ	@A@A@Q@A@"$ac9 9Q	@Q@
A@"acQ	@Q@A@";		!!!M!
M!I!#PANIC  !#GETLA0!#OTG$M0!#OTG$D0
 
"%4$0&j"& OTGLA05 5OOTGCOM	otg_label: bad addr descr*n.QK	%
acC@	uQK	"; ;,aKKOTGCOM	#	acA@"Q@	A	AQ	#Q	A$	AQacA@"Q@9 9'Q	AacQ@Q@acA@"		$0	AQacA@"Q@>U:9 9		K	#A,aKIOTGCOMQY,aKJOTGCOMQ^c	$L1Ld!: :j!
j!$IOTGCOM! $JOTGCOM!$KOTGCOM!#LOOKV0!#PANIC !#ENTET0!#OTG$U0! #DELEU0
 
"%0&0&g ( OTGMR 9 9OOTGCOM	uQK	"uQK	#@ $QK	%	@ &		&         	&		&9 9		&	@ &#acQ	@acQ	@Q@A@$A@Q	"	@ &acQ	@Q@A@$; ;Q	#Q	"2	%L3C	$A
	#@HCS9 9	@ #WacQ	@A@&A@#A@"A@$		!!g!! !@!`!p g!#ZEROL0!#GETLI0!#GETLA0!#OTG$M0
 
"%4(0&dT( OTGMI0: :OOTGCOM	QK	"	                                                                                                               tg_misc: IP to undef EXT name*n. QK	CacQ	@Q@
9 9A@#	A
acC@%acQ	@*acA@acQ	@	otg_misc: IP to : :bad obj descr*n.8QK	%
NacC@9MacQ	@Q@
A@#Q	AacQ@: :A@]	acQ@A@d7,aKJOTGCOM,aS MOTGCOM		Q	@ 	QQKQ; ;acQ@Q@
A@#	uQGQ	uQGQ	uQGQ	uQGQac"Q@Q	@9 9Q	@Q	@Q	@Q	@kQK	AQ[	$ac$A@$$ac&Q	@Q@
	Aac(Q	@9 9Q	@ac*Q	@A@	08ac*Q	@Q@E		Q
		Q,aKJOTGCOMQac,9 9Q	@Q@
LQK	%)ac.Q	@ac0Q	@Q@
A@#A@
ac2Q	@Q@Q@A@	A@#: :"]acQ	@Q@
A@#ac2Q	@Q@Q@A@	A@#|a	%&L
bbbb}	u9 9QGQ	u*QGQac2Q	@Q	@Q	@ac4Q	@A@.ac4A@	Q	@5	ot: :g_misc: bad DAC base*n. =acQ	@Q@
A@#A@Q	A
acC@>X	ac6Q@A@#; ;<QK,a[8IOTGCOM	$)ac:A@A@A@	A@$A@cac<Q	@Q@
A@#ac:A@A@9 9+Q@Q@A@#uac<Q	@Q@
A@#ac:A@A@Q@Q@A@#
	"L1l9 9 M/6%*+^d,=/12v	%8	%;%	%           >%	%; ;A%	%D%	%G%	%J%3	otg_misc: bad instr opcode *,-8i*n. JacC@K9 9Q	@		!d!	!!!!!!
!'!(!?d6 6!!!G!
!@!        @@!A!A@!B!C!!N$IOTGCOM!49 9$JOTGCOM!6$MOTGCOM!&#LOOKU0!<#LOOKV0!(#PANIC !*#DELET0!,#OTGPS0!.#OTG$X0!0#GETLA0!2; ;#OTG$IP!8#OTG$G0!:#OTG$L0!>#ENTER0!@#OTG$J0!B#ENTES0!D#ZEROL0!F#GETLI0!H#OTG$AP!J#OTG$F0 !L#OTG$E0!P#OTG$M0!R#GETEX0
 
"%F(0&