R( RESOL0: :ENTCOM	,aKENTCOM	"A
	A#"$	(#@($@
	#%	@@H%t$,aKENTCOM	t%9 9QS         resolve_ent: obj *i not found*n.	t",aK"ENTCOM	&	acA@&Q@
	A: :	acC@A@&8QQSQQS	t",aKENTCOM,aSENTCOM	A'		@ '	!!$ $R!$ENTCOM!$ENTCOM!$"ENTCOM!#LOOKV0!#PANIC 
 
"%8(0&$ CLEAU0< < LABCOM	A"	("@	"%	@@ t",aSLABCOM	@ ,aS LABCOM		,aS LABCOM" "		!+!,!$LABCOM!$ LABCOM!$ LABCOM
 
"%$$0&l & ENTET09 9 LABCOM	acQ	@A@"A@#	A,aK LABCOM	A
	",aw LABCOM,aKLABCOM< <,aS LABCOM	!enter_lab: out of space*nincrease MAX_LAB_MEMORY in vcg_def@.i*n. ,aK LABCOM< <	CacC@>,aK LABCOM	",aS LABCOM	@ t",aSLABCOMQK,aSLABCOM9 9	"t#,aSLABCOM
	"@D"A$	($@("@Z	$%	@@HADQK	t",aSLABCOM[9 9a		!!! !$LABCOM!$LABCOM!$ LABCOM!$ LABCOM!#LAB$01!#PANIC 
 
"%,&0&0$ LAB$019 9 LABCOM	QK	AM=@BQSQw,aKLABCOMQSQK	A
Qw,aKLABCOM: :QgQKQS,aKLABCOMQS                           QK	A	@ "	)	A"	!+0! $LABCOM!$LABCOM
 
"%.$0&(( LOOKV09 9 LABCOM	acQ	@A@"A@#	A	@ $	
	"@D"A%	(%@("@	%%	@@H- -	&t",aKLABCOM	t&QS	A$	!(!$LABCOM!#LAB$01
 
"%.(0&$ DELEU09 9 LABCOM	acQ	@A@"A@#	@HC	t",aKLABCOM	t#,aSLABCOM,aK LABCOM	t"+ +,aSLABCOM	",aS LABCOM		!$LABCOM!$ LABCOM!#LAB$01
 
"%($0& & GETLA09 9OOTGCOM	@ 	QSacQ	@		AQK		A
		A"	@ "         uQK	#: :	%	%	                                                                                                       et_label_addr: bad base reg@.*n. acC@ 	uQK	$< <	acA@$Q@	A	AQ	#Q	",a[IOTGCOMQ	@ Q	uQS	AQS; ;acA@$Q@@Q	AacA@$Q	uQS	",a[IOTGCOMQ	AQS: :acA@$Q@_Q	uQSw[Q	u	QSQQS		!!!( (!#MISSIN!$IOTGCOM!#PANIC !#LOOKV0!#ENTET0!#DELEU0
 
"%8&0&