m2* LDFIE06 6VCGCM3}hVCGCM2zVCGCM1=VCGCOM	ld_field: bit field base must be in memory*n. Qw: :,aKVCGCM2	",aKVCGCM2	#,aGVCGCM2QacQ	@Q	@A@$Q@	%$A
ac; ;C@	@ &	2	"#CacA@Q@	'	acA@%A@'	%"%RP	A'ac: :	A@"A@'Q@	"#A'ac A@'	'	acA@%A@'	%#A
ac"Q@	'acA@%9 9A@'	%pQ		"'ac$A@"A@'A@(		"#A'ac&A@'	'	acA@%A@'	%#9 9	A
ac(A@(	'	acA@%A@'	%}QKA
QS>		"'	ac$A@"A@': :A@(	"#A'ac*A@'	'	acA@Q@	)acA@%A@)A@'	%#A
ac(A@(9 9	'	acA@%A@'	%W	QKA
QS/	%&	!m! !%!&!!9 9m!$VCGCM2!$VCGCM2!$VCGCM2!#REACH !"#SEQ ! #GENMR !&#RSHIG0!,#LSHIG0!0# ##RSHIF0!.#ANDAW0!(#ANDLW0!#WARNI0!$#LFIEL0!*#AFIEL0
 
"%:*0&8b, STFIE09 9VCGCM3}hVCGCM2zVCGCM1=VCGCOM"!st_field: field base addr not lva; ;lue	Qw,aK6VCGCM2	",aK8VCGCM2	#"$C	"%	@$$ac:A@$; ;	%	"#A$ac<A@$	%ac>A@"A@#Q@	#A
ac@Q@	$acBA@%: :A@$	%/acDA@Q@Qw,aGFVCGCM2QacHQ	@Q	@A@&Q@	$acJA@: :Q@	'acBA@%A@'A@$	%&A
acLA@a@	@ (	e	acJA@Q@	$acJ; ;A@Q@	'QAQac@Q@	)	acJA@Q@	*acBA@%A@*A@)A@'A@$9 9	%acNQ@QKA
QS	"#A$acPA@$	%acRA@"A@#A@+acDA@: :Q@	#A
acTA@+	$	acBA@%A@$	%AQw,aGFVCGCM2QacHQ	@Q	@9 9A@&Q@	$	acJA@Q@	'acBA@%A@'A@$	%&A
acLG@ia@	@ (	q; ;	acJA@Q@	$	acJA@	Q@	'+A)acTA@)	)	acJA@
Q@	*	acBA@%A@*9 9	A@)A@'A@$	%acNQ@QKA
QS&	%(	!!2!!	!8 82! !
%!&!/!02!!2u*s*n.   !D$VCGCM2!B< <$VCGCM2!R$VCGCM2!V#GENMR !N#SEQ !T#REACH !F#RSHIG0!H#LSHIG0!\#LSHIF0!`#ANDAW0!L#ANDLW0 !J#LFIEL0!P#ALLOC0!X#WARNI0!Z#FREET0!^#AFIEL0
 
"%B,0&>F" AFIEL0: :"@`px|~@`px|~" a_field_mask: bad bit field 	9 9QK	%	%	@	*slength *i*n.ac>C@a@ Q	@
QK: :	A	%	@ 	*soffset *i*n.#ac>C@$a@ Q	@"QwaKac@Q	@   QS		!!!>!B#PANIC !D#F$RS
 
"%,"0&>v" LFIEL09 9"5@`px|~@`px|~@`px|~@9 9`px|~"Pl_field_mask: bad bit field 	QK	%: :	%	@	*slength *i*n.acnC@a@PQ	@
QK	A	%: :	@ 	*soffset *i*n.#acnC@$a@PQ	@"Q7aKacpQ	@QS		! >!! >!r#PANIC !t#F$RS71
 
"%,"0&7& ANDAW09 9	QK	"acA@	#	acA@	#	acA@	#	@ #		"%         @D$: :	L	"%(		QQKQacA@Q@	#	!7!!! !!	!7!#GENMR !#GENGE0
 
"%0&0&& ANDLW09 9	acA@	"	acA@	"	acA@	"	@ "	acA@	"	acA@	"< <			QQK	@D@QacA@Q@	"		QQK	@D@QacA@Q@	#ac9 9A@	$	acA@$A@#	"	QKA'WA'[	ABA'aA'e9 9	A'i	@ 
Q
G'Tp#	AB4		QQK	@D@QQ
	@Qac9 9A@Q@	"	!!!!!!	!
!f^X mb!#GENMR !#GENGE0!#SEQ 
 
"%2&0&Z2 LOADU09 9VCGCM3}hVCGCM2zVCGCM1=VCGCOM"load_field_asg_op: 	*sfield base a9 9ddr must be lvalue*n. Qw,aK$VCGCM2	"t",aG&VCGCM2Qac(Q	@A@#A@$Q@: :	%$A
ac*C@a@	@ &	+	@ '%A
ac,A@Q@ac.A@	'	ac0A@'Q@; ;	ac2A@Q@	(	ac2A@Q@	)ac4A@%A@)A@(	%ac6A@	*	t*,aS8VCGCM25 5		,aS:VCGCM2ac6A@	+	t+,aS8VCGCM2		,aS:VCGCM2	',aS$VCGCM2	+t*7 7,aS$VCGCM2	*t",aS&VCGCM29ac6A@		,		t,,aS8VCGCM2Qw,aK:VCGCM2	t,9 9,aS:VCGCM2	",aS$VCGCM2ac6A@	-Qw,aK8VCGCM2	.		/		/%; ;		/(		
/+		/.		/1		/4		/7		/:		/="	.L#: :&	%           J)	0L'&,EOP/QSTUVWX2Y;#;#[9 9&`abc5df8gijkl;mopq>r	*sbad field assg op *i*n6 6. tQw,aG8VCGCM2Qac*C@ua@Q	@	@ &	@	/t-,aS8VCGCM2Qw6 6,aK:VCGCM2	t-,aS:VCGCM2	",aS$VCGCM2Qw,aK<VCGCM2	t-,aS<VCGCM2	-t,: :,aS<VCGCM2	@ ,aS&VCGCM2Qw,aK8VCGCM2	%6	%958ac6A@	1< <Qw,aK8VCGCM2	C		t1,aS8VCGCM2E		t1,aS8VCGCM2JQw,aK:VCGCM2; ;	t1,aS:VCGCM2	,,aS$VCGCM2Qw,aK<VCGCM2	t1,aS<VCGCM2	ac>A@1Q	@	(ac4; ;A@%A@(	%9	ac>A@,Q	@	(	ac4A@%A@(	%n	#QOQS	'A
ac@9 9	Q@acBA@'	%&	!!!!!	!!!        !     7 7!!
!"!(!*!+!,!0!5!8!>!C!N: :$VCGCM2!P$VCGCM2!:$VCGCM2!R$VCGCM2!<$VCGCM2!>#REACH !T#LOAD!H#GENMR !J#SEQ !L) )#TALLOC!D#MKLAB0!@#WARNI0!B#ALLOC0!F#ENTEV0!V#FREET0!X#DELEW0
 
"%F20&PX2 VOIDF09 9VCGCM3}hVCGCM2zVCGCM1=VCGCOM"void_field_asg_op: 	*sfield base a9 9ddr must be lvalue*n. Qw,aK$VCGCM2	"t",aG&VCGCM2Qac(Q	@A@#A@$Q@: :	%$A
ac*C@a@	@ &	+	@ '%A
ac,A@Q@ac.A@	'	ac0A@'Q@; ;	ac2A@Q@	(	ac2A@Q@	)ac4A@%A@)A@(	%ac6A@	*	t*,aS8VCGCM25 5		,aS:VCGCM2ac6A@	+	t+,aS8VCGCM2		,aS:VCGCM2	',aS$VCGCM2	+t*7 7,aS$VCGCM2	*t",aS&VCGCM29ac6A@		,		t,,aS8VCGCM2Qw,aK:VCGCM2	t,9 9,aS:VCGCM2	",aS$VCGCM2ac6A@	-Qw,aK8VCGCM2	.		/		/%; ;		/(		
/+		/.		/1		/4		/7		/:		/="	.L#: :&	%           J)	0L'&,EOP/QSTUVWX2Y;#;#[9 9&`abc5df8gijkl;mopq>r	*sbad field assg op *i*n6 6. tQw,aG8VCGCM2Qac*C@ua@Q	@	@ &	@	/t-,aS8VCGCM2Qw6 6,aK:VCGCM2	t-,aS:VCGCM2	",aS$VCGCM2Qw,aK<VCGCM2	t-,aS<VCGCM2	-t,9 9,aS<VCGCM2	@ ,aS&VCGCM2	ac>A@,Q	@	(	ac4A@%A@(	%#QOQS	'A
: :ac@Q@acBA@'D	%&	!!!!!	!P!!        !8 8P!!
P!"!(!*!0!5!8!>!CP!L$VCGCM2!N9 9$VCGCM2!8$VCGCM2!P$VCGCM2!:$VCGCM2!<#REACH !F#GENMR !H#SEQ !R#VOID!J#TALLOC!># ##WARNI0!@#ALLOC0!B#MKLAB0!D#ENTEV0!T#FREET0!V#DELEW0
 
"%F20&T0* FLFIE05 5VCGCM3}hVCGCM2zVCGCM1=VCGCOM	fl_field: bit field base not addressable*n. Qw: :,aKVCGCM2	",aKVCGCM2	#,aGVCGCM2QacQ	@Q	@A@$Q@	%$A
ac: :C@	@ &	1	"#CacA@Q@	'	acA@%A@'	%acA@"A@#Q@ac < <Q@	'	acA@%A@'	%QK	A
ac"A@Q	@		'	acA@%A@'	%cac"9 9A@Q	@		'	acA@%A@'	%rQKA
QS=	acA@Q@	'acA@%: :A@'	%ac$A@"A@#A@(ac&A@(	'	acA@%A@'	%QK	A
ac"A@Q	@	: :	'	acA@%A@'	%-	ac"A@Q	@		'	acA@%A@'	%<	QKA
QS9 9	%&	!!!!T!%!&!!T!$VCGCM2!$VCGCM2!; ;$VCGCM2!#REACH !$#SEQ !"#GENMR !.#ANDAW0!(#ANDLW0!*#GENBR0! #WARNI0!&#LFIEL0!,#AFIEL0
 
"%@*0&