tL* OTGPS0; ;OOTGCOM	QK	"	A#	A$		#acQ@,Q@	@HCacQ@Q@: :,aKIOTGCOMQ	AQ	%acQ@,acQ@,Q@		#acQ@,Q@	@H9 9	CacQ@Q@		%%<acQ@
Q@A'QN		$
acQ@Q@9 9acQ@
FPacA@ac ac"ac$A@ac&,a
@IOTGCOM,a
@(JOTGCOMA@A@: :A@ac*Q@
A@&A@'	@HC	&Aac,Q@
A@'w	&@HCac.Q@
A@'9 9	otg_pseudo: bad ENT base reg*n. ac0C@wac&A@A@A@A@9 97A@ac$A@ac2A@ac4ac6ac$A@ac&A@A@A@A@A@Eac$A@	: :V	otg_pseudo: bad instr code *i*n.\	"L1FWac0C@]Q	@[		: :EQ,	(0ac8Q@-A@
ac8Q@-A@
ac8Q@.A@
ac8Q@-A@
ac8Q@.9 9+A@
ac8Q@-A@
ac8Q@.A@
ac8Q@/A@
ac8Q@0A@
!	()L5 5":3,aK:KOTGCOM	@HC	@ ,aS:KOTGCOMac<,a
@IOTGCOMIS9 9,aK:KOTGCOM	A		,aS:KOTGCOMac>,a
@(JOTGCOMU]	$L|T^Q	#: :	L|4dD	%L&4k!!
!!q!!	!	
; ;!!!! q!'qM@! $IOTGCOM!4$JOTGCOM!F$KOTGCOM!#RESON09 9!6#RESOL0!#OTG$U0!"#DELEV0!$#ENTEU0!&#RESOM0!(#OTG$X0!*#OTG$V0!,#CLEAS0!.#CLEAW0!0; ;#OTG$C0!2#OTG$P0!8#OTG$K0!:#OTG$J0!<#PANIC !>#OTG$I0!@#FLUSH !B#CLEAU0!D#OTG$F0!H#OTG$S0 !J#OTG$O0
 
"%\*0&