#" PANIC 9 9VCGCM3}hVCGCM2zVCGCM1=VCGCOM	ac,a
@VCGCOMacA@Q	@Q	@Q	@Q	@	Q	@9 9Q	@Q	@Q	@Q	@Q	@acA@ac!q#!h#!$VCGCOM!#FLUSH$!#PRINT  !#SETERR!#SWT 
 
"%@"
0&" WARNI09 9VCGCM3}hVCGCM2zVCGCM1=VCGCOM	!acA@Q	@Q	@Q	@Q	@	Q	@Q	@Q	@Q	@Q	@# #Q	@,akVCGCOM	@	!q!$VCGCOM!#PRINT 
 
"%@"
0&