" CLEAY00 0KFRAME0	@ ,aSFRAME0		,aSeFRAME0		!"!$FRAME0!$eFRAME0
 
"%""0&" CLEAV0 KFRAME0		,aSJFRAME0		!!$JFRAME0
 
"%""0&j"& RSVST0: :KFRAME0		"A#	(#@	#,agFRAME0	@t#,aKFRAME0	@HC,aKeFRAME0: :Q_	C	@ ,aSFRAME0	"$	QK	M@ Q	t#,aKeFRAME0	M@ Q'/: :-,aKFRAME0	B%	%@H%3	#$%9	t%,aKdFRAME0,aSeFRAME0,aKFRAME0: :,aSFRAME04:,akFRAME0	@@ t#,aSFRAME0QK,aSeFRAME0,aKfFRAME0Q_7 7,aSfFRAME0	"$	.	"t#,a[eFRAME0	",aKFRAME0	A
,awFRAME0; ;,aKFRAME0	@HCb	",a_eFRAME0	"QK,a_eFRAME0,a[eFRAME0,aSeFRAME0QK6 6,aSeFRAME0	@ ,aSFRAME0	"$	i	too many objects allocated in stack frame*n.		< <,agFRAME0	@acC@	@ $		stack frame too small to meet storage request*n.#QK; ;	M@ Q	"M@ QA'LJacC@$	@ $	K,akFRAME0	@QK,a[eFRAME09 9,aSeFRAME0QK,awFRAME0,aSeFRAME0	@ ,aSFRAME0	"$	!"!dhH: :!$FRAME0!$FRAME0!$FRAME0!$eFRAME0!$dFRAME0!$eFRAME0!$fFRAME0! #WARNI0
 
"%,&0&>$ RSVLI09 9KFRAME0	link frame too small to meet storage request*n. QK	M@ Q,aKJFRAME0	M9 9	@ QA'+)acC@	@ "	*,aKJFRAME0	"Q[,aSJFRAME0	"	'                                        !$JFRAME0!#WARNI0
 
"%*$0&$ STACK0 KFRAME0	,aKeFRAME0QS	"	!$eFRAME0
 
"%($0&$ LINKS0$ $KFRAME0	,aKJFRAME0	QS	"	!!$JFRAME0
 
"%($0&"& FREES0: :KFRAME0		"A#	(#@	#,agFRAME0	@"Q_	C	At#,aSFRAME0	#; ;,agFRAME0,aKFRAME0	@HC,aKeFRAME0,a[fFRAME0,aSeFRAME0	#B$: :	($@)	$,agFRAME0/	t$,aKfFRAME0,aSeFRAME0,aKFRAME0,aSFRAME0*7 70,aKFRAME0	@H,aSFRAME0	A$#B	t#,aKFRAME0	@HCC,aKdFRAME05 5,a[eFRAME0,aSdFRAME0	#$	($@R	$,agFRAME0X	t$,aKfFRAME09 9,aSeFRAME0,aKFRAME0,aSFRAME0SY,aKFRAME0	@H,aSFRAME0I		         "t#9 9,a[eFRAME0	"	attempt to free bogus local object at *,-10i*n. p	acC@qQ	@		: :!"!$FRAME0!$FRAME0!$FRAME0!$FRAME0!$dFRAME0!$eFRAME0!$fFRAME0!  #WARNI0
 
"%*&0&" ALLOC07 7	AQS	u	QSacQ	@	uQS	AuQS		!!!!#RSVST0
 
"%("0&" FREET0 	uQGQacQ	@		!!#FREES0
 
"%("0&