2$ IALLOC9 9MEMCOM	out of instr storage memory*n.,aKMEMCOM	M@ QQK	M@ QA'"; ;
 acC@!,aKMEMCOM	"Q[,aSMEMCOM	"	z!$MEMCOM!#PANIC 
 
"%*$0&2$ TALLOC9 9MEMCOM	out of tree storage memory*n. ,aKMEMCOM	M@ QQK	M@ QA'"; ;
 acC@!,aKMEMCOM	"Q[,aSMEMCOM	"	}h!$MEMCOM!#PANIC 
 
"%*$0&" CLEAT0 MEMCOM	A,aSMEMCOM		!$MEMCOM
 
"%""0&" CLEAZ0- -VCGCM3}hVCGCM2zVCGCM1=VCGCOMMEMCOM	A,aSMEMCOM		!$MEMCOM
 
"%""0&" CLEBA0 MEMCOM	A,aSMEMCOM		!$MEMCOM
 
"%""0&" IFREE  		
 
"%&"0&" TFREE  		
 
"%&"0&6$ STRSA09 9VCGCM3}hVCGCM2zVCGCM1=VCGCOMMEMCOM	out of string storage memory*n. acQ	@	": :,a[MEMCOM	BCacC@	acQ	@A@,a
@VCGCM3,a
@MEMCOM,aKMEMCOM: :	#"B,a[MEMCOM,aSMEMCOM	#	!6!6!$MEMCOM!$VCGCM3!#LENGTH! #PANIC !#SCOPY 
 
"%($0&$ CLEAX0< <MEMCOM	A"	("@	"%	@@ t",aSMEMCOM	@ ,aSMEMCOM		,aSMEMCOM" "		!+!,!$MEMCOM!$MEMCOM!$MEMCOM
 
"%$$0&l & ENTEV09 9MEMCOM	acQ	@A@"A@#	A,aKMEMCOM	A
	",awMEMCOM,aKMEMCOM< <,aSMEMCOM	!enter_obj: out of space*nincrease MAX_OBJ_MEMORY in vcg_def@.i*n. ,aKMEMCOM< <	CacC@>,aKMEMCOM	",aSMEMCOM	@ t",aSMEMCOMQK,aSMEMCOM9 9	"t#,aSMEMCOM
	"@D"A$	($@("@Z	$%	@@HADQK	t",aSMEMCOM[9 9a		!!!!$MEMCOM!$MEMCOM!$MEMCOM!$MEMCOM!#MEM$01!#PANIC 
 
"%,&0&0$ MEM$019 9MEMCOM	QK	AM=@BQSQw,aKMEMCOMQSQK	A
Qw,aKMEMCOM: :QgQKQS,aKMEMCOMQS                           QK	A	@ "	)	A"	!+0! $MEMCOM!$MEMCOM
 
"%.$0&(( LOOKX09 9MEMCOM	acQ	@A@"A@#	A	@ $	
	"@D"A%	(%@("@	%%	@@H- -	&t",aKMEMCOM	t&QS	A$	!(!$MEMCOM!#MEM$01
 
"%.(0&$ DELEW09 9MEMCOM	acQ	@A@"A@#	@HC	t",aKMEMCOM	t#,aSMEMCOM,aKMEMCOM	t"+ +,aSMEMCOM	",aSMEMCOM		!$MEMCOM!$MEMCOM!#MEM$01
 
"%($0&