$ CLEAW0< <LITCOM	A"	("@	"%	@@ t",aSLITCOM	@ ,aSLITCOM		,aSLITCOM" "		!+!,!$LITCOM!$LITCOM!$LITCOM
 
"%$$0&~& ENTEU09 9LITCOM	acQ	@A@"A@#	A,aKLITCOM	A
	",awLITCOM,aKLITCOM5 5,aSLITCOM	"enter_lit: out of space*nincrease MAX_LIT_MEMORY in otg_def@.r@.i*n.: :,aKLITCOM	CacC@?,aKLITCOM	",aSLITCOM	@ t",aSLITCOM	": :	t#,aSLITCOM	B$A%	(%@($@V	%%	@@HADQK	t$,aSLITCOMW]
	"9 9	$A%	(%@($@l	%%	@@HADQK	t$,aSLITCOMms		!!~* *!!!$LITCOM!$LITCOM!$LITCOM!#LIT$01!#PANIC 
 
"%,&0&Z"$ LIT$019 9LITCOM	uQK	uQ[	"AM=@BQSQw,aKLITCOMQSQK	A
Qw; ;,aKLITCOMQ_	C,aKLITCOM	uQ_	C!Qw,aKLITCOM	uQ_	C(9 9Qw,aKLITCOM	uQ_	C1Qw,aKLITCOM	uQ_	C:CQKQS: :Qw,aKLITCOMQSDQK	A	@ #	S	A#	!!!!Z1 1!+Z!$LITCOM!$LITCOM!$LITCOM!$LITCOM!$LITCOM! $LITCOM
 
"%.$0&(( LOOKW09 9LITCOM	acQ	@A@"A@#	A	@ $	
	"%A&	(&@(%@	&%	@@H1 1	't%,aKLITCOM	t'QS	A$	!!(!$LITCOM!#LIT$01
 
"%.(0&$ DELEV09 9LITCOM	acQ	@A@"A@#	@HC	t",aKLITCOM	t#,aSLITCOM,aKLITCOM	t"+ +,aSLITCOM	",aSLITCOM		!$LITCOM!$LITCOM!#LIT$01
 
"%($0&R( RESON0: :LITCOM	A"	("@	"%	@t",aKLITCOM	##A
	t#,aKLITCOM	@HC9 9,aKLITCOM	#	#A
	At#,aSLITCOM	##A$	($@(#@&	$%	@@H< <	%t#,aKLITCOM	t%QS'-	A$	($@(#@:	$%	@@H%t#,aKLITCOM	t%QS* *;A	A&		@ &	!R!+R!$LITCOM!$LITCOM
 
"%.(0&^" GETLI09 9OOTGCOM	@ QSacQ	@Q@	A	AQ	@ Q,aKIOTGCOMQQK		C9 9Q+	@	@ Q	uQS	AQSacQ	@Q@Q	AacQ	@: :Q	uQS,aKIOTGCOMQQK		CQ+	@C	AQSacQ	@Q@1: :Q	uQSP-	@ uQS	AQS		!!^!^!$IOTGCOM!#LOOKW0 !#ENTEU0!#DELEV0
 
"%4"0&$ CLEAS0< <EXTCOM	A"	("@	"%	@@ t",aSEXTCOM	@ ,aSEXTCOM		,aSEXTCOM" "		!!!$EXTCOM!$EXTCOM!$EXTCOM
 
"%$$0& ( ENTES09 9EXTCOM	acQ	@A@"A@#	A,aKEXTCOM	A
	",awEXTCOM,aKEXTCOM5 5,aSEXTCOM	"enter_ext: out of space*nincrease MAX_EXT_MEMORY in otg_def@.r@.i*n.9 9,aKEXTCOM	CacC@?,aKEXTCOM	",aSEXTCOMacQ	@	B$"B9 9	%A&	(&@(%@U	&$$	@@HADQK	t%,aSEXTCOMV\	"%A&	(&@(%: :	@k	&%	@@HADQK	t%,aSEXTCOMlr	@ t",aSEXTCOM	"t#,aSEXTCOM
< <		!!"!'!!$EXTCOM!$EXTCOM!$EXTCOM!#EXT$01!#LENGTH!#PANIC 
 
"%.(0&$ DELET09 9EXTCOM	acQ	@A@"A@#	@HC	t",aKEXTCOM	t#,aSEXTCOM,aKEXTCOM	t"+ +,aSEXTCOM	",aSEXTCOM		!$EXTCOM!$EXTCOM!#EXT$01
 
"%($0&F& EXT$015 5EXTCOM	@ "A#	(#@	#@HADQK	A
	"M=@B"	"QS	t": :,aKEXTCOMQSQK	A
Qw,aGEXTCOMQ
acQ	@Q	@
	%
1!QKQS9 9Qw,aKEXTCOMQS0QK	A	@ $	?	A$	!!F!$EXTCOM !$EXTCOM!#STRCMP
 
"%2&0&(( LOOKU09 9EXTCOM	acQ	@A@"A@#	A	@ $	
	""A%	(%@("@	%%	@@H3 3	&t",aKEXTCOM	t&QS	A$	!(!"(!$EXTCOM!#EXT$01
 
"%.(0&T( RESOM0: :EXTCOM	A"	("@	"%	@t",aKEXTCOM	##A
	t#,aK&EXTCOM	@HC: :,aKEXTCOM	#	#A
	A$#"	($@("@"	$%	@@H%t",aKEXTCOM	t%< <QS#)	##At#,aSEXTCOM	$	($@(#@<	$%	@@H%t#,aKEXTCOM	t%QS7 7=C	A&		@ &	!!!!!"T!$EXTCOM!$EXTCOM!$&EXTCOM
 
"%.(0&N" GETEX09 9OOTGCOM	@ QSacQ	@Q@
	A		Q
		Q,aKIOTGCOMQ	@ Q: :	uQS	AQSacQ	@Q@
Q	AacQ	@Q	uQS,aKIOTGCOM: :Q	AQSacQ	@Q@
)Q	uQS@%		uQS		QS		!!" "!N!$IOTGCOM!#LOOKU0!#ENTES0!#DELET0
 
"%2"0&" CLEAR00 0ENTCOM	@ ,aSENTCOM		,aSENTCOM		!!$ENTCOM!$ENTCOM
 
"%""0&e( ENTER0: :ENTCOM	"enter_ent: out of space*nincrease MAX_ENT_MEMORY in otg_def@.r@.i*n.	acQ	@A@"	A9 9,aKENTCOM	CacC@1,aKENTCOM	#,aSENTCOMacQ	@	B$#; ;	B%A&	(&@(%@G	&$$	@@HADQK	t%,aSENTCOMHNQK	t#,aS"ENTCOM9 9	@ ,aSENTCOM	#t",aSENTCOM+		!#!!$ENTCOM!$ENTCOM!$"ENTCOM!                                                                   ENT$01!#LENGTH!#PANIC 
 
"%.(0&)$ ENT$01: :ENTCOM	AQS,aKENTCOM	""A
	t",aGENTCOMQacQ	@Q	@	%	7 7	"QS	t",aKENTCOM	"	"A	@ #	"	A#	!)!$ENTCOM! $ENTCOM!#STRCMP
 
"%,$0&