 (& REACH 9 9VCGCM3}hVCGCM2zVCGCM1=VCGCOM	QK	A	@ "QS	AQSQS		@ uQS		u; ;QS		"	Qw,aKVCGCM2	#    acQ	@Q	@Q	@Q	@		"acQ	@Q	@Q	@; ;Q	@		"    (acQ	@Q	@Q	@Q	@		"    4acQ	@Q	@Q	@Q	@		"@acQ	@Q	@9 9Q	@Q	@		"    LacQ	@Q	@Q	@Q	@		"    XacQ	@Q	@Q	@Q	@		"d	#: :	$L*ewxy{|}~5M	#%): :	$LAY		ac Q	@Q	@	"AQSp!! ! !(!; ;9 !$VCGCM2!#REACI0!#REACL0!#REACJ0!#REACM0! #REACK0!&#LOAD!"#REACN0!$#REACH0
 
"%2&0&U0
& REACI08 8VCGCM3}hVCGCM2zVCGCM1=VCGCOM	@ 	QSQSQw,aKVCGCM2	"		QS	Qw9 9,aKVCGCM2	uQS		@ #		QS	Qw,aKVCGCM2	uQS	Qw,aKVCGCM2	u9 9QS		@ #		QS	Qw,aKVCGCM2	uQS	Qw,aKVCGCM2	uQS		@ #,: :		QS	Qw,aKVCGCM2	uQS	Qw,aKVCGCM2	uQS	Qw,aKVCGCM2	uQS	; ;Qw,aKVCGCM2	uQS		@ #@	AQS			uQS	Qw,aGVCGCM2	QacQ	@: :	u	QS	acA@	#A$	($@~	$Qw,agVCGCM2	@Q[	AD,aGVCGCM2: :	Qac Q	@	%	ac"A@#A@%	#acA@		%	ac"A@#A@%	#b	: :reach_const: bad constant mode (*i)*n.)	"L-AcQw,aGVCGCM2Q: :	ac$C@*Q	@(	#	!!!!U!!!!	U!5!	: :EU!$VCGCM2!$$VCGCM2!$VCGCM2!$VCGCM2! $VCGCM2!"$VCGCM2!&#RSVLI0!,#SEQ  !*#GENDA0!(#GENGE0!.#PANIC 
 
"%4&0&
$ REACL09 9VCGCM3}hVCGCM2zVCGCM1=VCGCOM	@ 	QSQSQw,aGVCGCM2QacQ	@Q	@		A2 2		QS	QK	uQS		@ "	!!
!$VCGCM2!#LOOKX0
 
"%2$0&*"( REACJ0; ;VCGCM3}hVCGCM2zVCGCM1=VCGCOM	Qw,aKVCGCM2	AD,aKVCGCM2	C,aGVCGCM2: :QacQ	@Q	@Q	@Q	@		"	
Qw,aGVCGCM2QacQ	@A@#A@$Q@	%9 9	A$$	1.Q	@ Q		QacA@Q@	&	acA@%A@&	"AQS			u; ;QS		@ uQS		#A
QS0Q	@HC		QS	Q	uQS	Q	uQS	9 9	#QS	%"\Q	@HC		QS	Q	uQS	Q	uQS		#QS	%; ;	"t	acA@Q@	&	acA@%A@&	"	QS		uQS		@ uQS		#A
QS6 6oW	@ QS	"	!!!!*!!*!1!3*! $VCGCM2!$VCGCM2!#REACH ! #SEQ !#GENMR 
 
"%B(0&L&
( REACM09 9VCGCM3}hVCGCM2zVCGCM1=VCGCOM	Qw,aGVCGCM2QacQ	@A@"A@#Q@	$A: :	$#	Q	@ Q		QacA@Q@	%	acA@$A@%	&"A
QS	A: :QS			uQS	Qw,aKVCGCM2	uQS	Qw,aKVCGCM2	A	"QS	@ ; ;QSacQ@Q	@		$&	FQ	%[	%^Z]	$&"QSQQS	Q: :	u	QS	QQw,a[VCGCM2	uQS	^Q	C		QQw,aKVCGCM2< <QacA@Q@	%	acA@$A@%	&"A
QS		QS	Q	uQS	Q	uQS	6 6{	acA@	Q@	%	acA@$A@%	&"A
QS	AQS			uQS	Qw: :,aKVCGCM2	uQS	%v@	@ QS	&	!!!!L!L!!	8 8L!(!1!@L!"$VCGCM2!$VCGCM2!#REACH ! #SEQ !#GENMR !$#ADCOPY
 
"%B(0&
r8. REACK0: :VCGCM3}hVCGCM2zVCGCM1=VCGCOM	@ QSQw,aGVCGCM2QacQ	@A@"A@#Q@9 9	$Qw,aGVCGCM2QacQ	@A@%A@&Q@	'&@HCQw,aGVCGCM2Q9 9acA@	(acQ	@	)acA@'A@)A@(	')Q	CQ	A9 9	acQ@Q	@		"QS	$*	LQ	%^	%a]`	QQS	Q	u: :	QS	QQw,a{VCGCM2	@Q	uQS		"QS	$*	aQQw,a{VCGCM29 9	@Qac A@Q@	'HQ	%	%Qw,aKVCGCM2; ;	@HCac A@Q@	(	acA@'A@(	'Qw,aKVCGCM2	@HCac A@9 9Q@	(	acA@'A@(	'3Qw,aKVCGCM2	Cac A@Q@	(ac: :A@'A@(	'IQw,aGVCGCM2	QacA@	(acQ	@	)	ac A@	Q@: :	+acA@'A@+A@)A@(	'%A

	%XB,Qw,aGVCGCM2	QacA@; ;	(acQ	@	)	ac A@	Q@	+acA@'A@+A@)A@(	'%A

	%C	#A9 9Q	@HC			Q'41	%A
3	A,6	acA@$A@'	*%A	"A
9 9QS		QS	Q	uQS	Q	uQS	-		Q'\YQ'a^	%A
; ;`		,9c	acA@$A@'	*%	A	"A
QS		QS	Q	uQS	Q	uQS	; ;[	%A
		,f	ac A@Q@	(acA@$A@(A@'	*%	A	"A
A
9 9QS		QS			uQS		@ uQS	U(	%A	AQ	@ Q		Q9 9	ac A@Q@	(acA@$A@(A@'	*%A	"A
A
QS		QS			uQS		@ : :	uQS	2ac"A@Q@ac A@Q@	(acA@$A@(A@'	*		Qac A@9 9Q@	(	acA@*A@(	*ac$Q@	%A	"A
A
QS	AQS			uQS		@ u; ;QS	`.	*		ac"A@Q@ac A@Q@	(	ac A@Q@	)acA@$A@)A@(9 9A@'	*	Qac A@Q@	(	acA@*A@(	*ac$Q@	%A	"A
A
QS9 9	AQS			uQS		@ uQS	j	,L ..k!!!!r9 9!r!!!                                 !r!	%!(!0!1!@!_!
; ;r!"$VCGCM2!&$VCGCM2!($VCGCM2!$#REACH !.#SEQ !2#GENMR !*#GENGE0!,#MULABY!0#ADCOPY !4#ALLOC0!6#FREET0
 
"%N.0&A& REACN0: :VCGCM3}hVCGCM2zVCGCM1=VCGCOM	Qw,aKVCGCM2	A,aGVCGCM2	QacQ	@: :	Q	@Q	@Q	@		"Qw,aGVCGCM2Q,aGVCGCM2QacQ	@Q	@Q	@5 5Q	@		#	acQ	@A@$	%	acA@%A@#	"$QOQS	"	!$VCGCM2! $VCGCM2!#VOID!#REACH !#SEQ 
 
"%6&0&{V8 REACH09 9VCGCM3}hVCGCM2zVCGCM1=VCGCOM"reach_assign: 	Qw,aK VCGCM2	AD: :,aK"VCGCM2	CQw,aG$VCGCM2Q*ac&Q	@*A@"	#Qw,aK(VCGCM2	$; ;ac*A@Q@$Qw,aG VCGCM2Q*ac,A@Q@$	%	ac.Q	@*A@&	'	ac,A@Q@$; ;	(ac0A@#A@(A@'A@%	#ac2Q@$	"A	&QS	AQS	#	ac*A@Q@$Qw: :,aG VCGCM2Q*ac,A@Q@$	%	ac.Q	@*A@&	'	ac,A@Q@$	(	ac0A@#A@(: :A@'A@%	#ac2Q@$	"A	&QS	AQSV	                                          sbad data mode in bit field *i*n.6 6	$LXXQw,aG(VCGCM2Q*ac4C@a@Q	@*	@ #V
Qw9 9,aK(VCGCM2	)		*A+		*	+E			*	+J		
*	+OQw,aK6VCGCM29 9	,		*A+T		*	+_		
*	+dZ	,L[`eo	*sleft struc; ;	t op not lvalue*n.qac*A@Q@ac*A@Q@Qw,aG VCGCM2Q*ac8Q	@*A@&A@-; ;Q@	.-A
ac4C@ra@	@ #V Q	/	@ 0Q	%6	%9: :58	@ 009	A0<	A0?B	0@HCac,A@Q@	%	ac0A@.A@%9 9	.ac:Q@Q@ac,A@Q@	%	ac0A@.A@%	.	QF-		*sbad left op addr: : mode *i*n. m	/L 1@1@@.....ac4C@na@Q@	@ #Vl	: :*sright struct op not lvalue*n. Qw,aG$VCGCM2Q*ac8Q	@*A@"A@1Q@	21A
9 9	ac4C@a@	@ #V9Q	3	@ 4Q	%O	%RNQ	@ ; ;	4IR	A4U	A4X[	4@HCac,A@Q@	%	ac0A@2A@%	2ac:Q@9 9Q@ac,A@Q@	%	ac0A@2A@%	2	Q_F	*sbad right op addr mode *i*n.8 8	3L JYJYYGGGGGac4C@a@Q@	@ #V		QSQw< <,aG6VCGCM2Q*ac<Q@Q@Q	@*	%ac0A@.A@2A@%	#4@HCac2Q@Lac:9 9Q@Q	@		@ QSV@	*sbad data mode *i*n. [	)LAFAFKPUQw: :,aG(VCGCM2Q*ac>C@\a@Q	@*iQw,aG$VCGCM2Q*ac8Q	@*A@"A@1Q@9 9	2ac*A@+Q@$Qw,aG VCGCM2Q*ac8Q	@*A@&A@-Q@	.	A5		59 9*ac@A@&A@"	A
	A65	A7'	ac@A@*A@&	A
ac@A@*9 9A@"	A
D(L	ac@A@*A@&	A
ac@A@*A@"	AU+]	ac@A@*A@&9 9	Aac@A@*A@"	A
f.n		7;<ac2Q@$	"	A	&A	*QS	AQS< <V-	acBA@*Q@	%acDA@*A@1Q@	'ac0A@2A@'A@.A@%	#8acB: :A@*Q@	%acDA@*A@1Q@	'ac0A@.A@2A@'A@%	#sr	acDA@*A@1: :Q@	%	ac0A@2A@%	#	acBA@*Q@	%acDA@*A@Q@$	'	acBA@*Q@$	(9 9ac0A@#A@(A@.A@'A@%	#	5Lsson	7L<su!9 9!!!!{!     {!%!&!/!0!E!
{!	!: :!!C{!2$VCGCM2!8$VCGCM2!0$VCGCM2!4$VCGCM2!F$VCGCM2!P#SAFE!@#SEQ : :!T#LD!R#ST!H#REACH !6#LOAD!>#STFIE0!<#GENMR !L#GENCO0!:#ALLOC0!B#FREET0!D#WARNI0!J #ADCOPY!N#PANIC 
 
"%d80&