

!,( VOID: :VCGCM3}hVCGCM2zVCGCM1=VCGCOM	QK	A	@ "QS	"	Qw,aKVCGCM2	#9 9acQ	@Q	@	"acQ	@Q	@	"acQ	@Q	@	" acQ	@Q	@	"9 9(acQ	@Q	@	"0acQ	@Q	@	"8acQ	@Q	@	"@ac Q	@Q	@	": :Hac"A@	$	ac$Q	@Q	@	%ac"A@	&ac&A@&A@%A@$	"P	#L: :pqrtuvwxyzQ	%!	'L)1{9	9 9
AI	ac$Q	@Q	@	"k	!!!9 9*!5!E!!$VCGCM2!(#LOAD!#VOIDA0!#VOIDP0!#VOIDQ0!"#VOIDS0! #VOIDR0! #VOIDB0!#VOIDIF!$#VOIDT0!*#SEQ !&#GENGE0
 
"%.(0&t*& VOIDA09 9VCGCM3}hVCGCM2zVCGCM1=VCGCOM	Qw,aKVCGCM2	AD,aKVCGCM2	CacQ	@< <Q	@	"	
	ADDAA left operand is not an lvalue*n.Qw,aKVCGCM2	@HC,aKVCGCM2: :	AD,aKVCGCM2	C-,aKVCGCM2	@HC5Qw,aGVCGCM2QacQ	@Q	@A@#: :Q@	"#A
acC@	@ "	NacA@	$	ac A@Q@	%ac"A@"A@%A@$7 7	"	:	ac$Q	@Q	@	"	!	t!!E!Gt!$VCGCM2!$VCGCM2!5 5$VCGCM2!$VCGCM2!$#GENMR !"#GENGE0!(#LOAD!&#SEQ !#REACH !#VOIDF0! #WARNI0
 
"%4&0&k"( VOIDB06 6VCGCM3}hVCGCM2zVCGCM1=VCGCOM	Qw,aKVCGCM2	AD,aKVCGCM2	CQw; ;,aKVCGCM2	"Qw,aGVCGCM2Q,aGVCGCM2QacQ	@A@#	$acQ	@: :A@%	&	acA@&A@$	'%A	#QS	'		*i:  bad data mode used with bit field*n. 79 9	"LQw,aGVCGCM2QacC@8Q	@	@ '5
	acQ	@Q	@: :	'5!Ek!$VCGCM2!$VCGCM2!$VCGCM2!$VCGCM2!#STFIE0!#LOAD!#SEQ !  #WARNI0
 
"%2(0&e*, VOIDIF< <VCGCM3}hVCGCM2zVCGCM1=VCGCOM	Qw,aKVCGCM2	AacA@	"Qw,aGVCGCM2: :QacQ	@A@#A@A@"	$Qw,aGVCGCM2	QacA@"	%	acQ	@A@&	'< <acA@$A@'A@%	$@ (Qw,aKVCGCM2	AacA@	"Qw,aGVCGCM2: :QacQ	@A@#A@A@"	$Qw,aGVCGCM2	QacA@"	%	acQ	@A@(	'7 7acA@$A@'A@%	$@ &@acA@	)acA@	"	Q	"QQw: :,aGVCGCM2QacQ	@A@#A@A@)	$Qw,aGVCGCM2	QacA@)	%ac 8 8A@	'	ac"A@Q@	*	acQ	@A@&	+acA@$A@+A@*A@'A@%	$Qw9 9,aGVCGCM2	QacA@"	%	acQ	@A@(	'acA@$A@'A@%	$t:	(A	&9 9A	#QS	$	!e!
!e! e!!e!$VCGCM2!$VCGCM2/ /!$VCGCM2!"#VOID!#FLOW!&#GENGE0!(#GENMR ! #GENLA0!$#SEQ !#MKLAB0
 
"%:,0&0
2 VOIDP09 9VCGCM3}hVCGCM2zVCGCM1=VCGCOM	Qw,aKVCGCM2	AD,aKVCGCM2	CacQ	@; ;Q	@	"	
Qw,aKVCGCM2	#		$	%		$	%		$	%"		$	%': :	*i: bad POSTDEC data mode*n.-	#L#(Qw,aGVCGCM2Qac< <C@.Q	@	@ QS	"	,	right POSTDEC operand is not constant*n.VQw,aGVCGCM2Q: :acQ	@A@&A@'Q@	(Qw,aGVCGCM2QacQ	@A@)A@*Q@	+*@HC9 9acC@W	@ QS	"	Q	,	right POSTDEC operand is not constant*n.	,: :		-L89:acC@	@ QS	"	;	left POSTDEC operand is not an lvalue*n.E; ;	'@HCacC@F	@ QS	"	]	acA@$Q@	.	ac A@%Q@	/	ac"A@$A@': :Q@	0ac$A@(A@0A@/A@.	"&A	$QS	"	!	!!!.!: :4!E!!!!!$VCGCM2! $VCGCM2!$VCGCM2!&$VCGCM2!.#SEQ ! !!,#LD!(#ST!*#GENMR !$#REACH !#VOIDF0!"#WARNI0
 
"%F20&
542 VOIDQ09 9VCGCM3}hVCGCM2zVCGCM1=VCGCOM	Qw,aKVCGCM2	AD,aKVCGCM2	CacQ	@; ;Q	@	"	
Qw,aKVCGCM2	#		$A%		$	%		$	%"		$	%': :	*i: bad POSTINC data mode*n.-	#L#(Qw,aGVCGCM2Qac< <C@.Q	@	@ QS	"	,	right POSTINC operand is not constant*n.VQw,aGVCGCM2Q: :acQ	@A@&A@'Q@	(Qw,aGVCGCM2QacQ	@A@)A@*Q@	+*@HC9 9acC@W	@ QS	"	Q	,	right POSTINC operand is not constant*n.	,: :	-L89:acC@	@ QS	"	;	left POSTINC operand is not an lvalue*n.E< <	'@HCacC@F	@ QS	"	]	AQw,agVCGCM2	olQ	Cn	&QS; ;acA@		.	ac A@
Q@	/ac"A@(A@/A@.	"	r	ac$A@$Q@	.ac A@%9 9Q@	/ac&A@$A@'Q@	0ac"A@(A@0A@/A@.	"&A	$QS	"	!56 6!!5!!
!E!	G!!!!5!$VCGCM2!"9 9$VCGCM2!$VCGCM2!($VCGCM2!.#SEQ !2#LD!0#ST!,#GENMR !&#REACH !*#GENGE0! #VOIDF0 !$#WARNI0
 
"%F20&)& VOIDS06 6VCGCM3}hVCGCM2zVCGCM1=VCGCOM	Qw,aGVCGCM2QacQ	@A@"	#Qw8 8,aGVCGCM2QacQ	@A@$	%	acA@#A@%	#$A	"QS	#	!$VCGCM2! $VCGCM2!#VOID!#SEQ 
 
"%.&0&u*& VOIDR09 9VCGCM3}hVCGCM2zVCGCM1=VCGCOM	Qw,aKVCGCM2	AD,aKVCGCM2	CacQ	@5 5Q	@	"	
	PREINC left operand is not an lvalue*n. Qw,aKVCGCM2	@HC9 9,aKVCGCM2	AD,aKVCGCM2	C.,aKVCGCM2	@HC6Qw,aGVCGCM2Qac: :Q	@Q	@A@#Q@	"#A
acC@	@ "	OacA@	$	ac A@Q@	%ac": :	A@"A@%A@$	"	;	ac$Q	@Q	@	"	!	u!!E!Gu!$VCGCM2!< <$VCGCM2!$VCGCM2!$VCGCM2!(#LOAD!&#SEQ !"#GENGE0!$#GENMR !#REACH !#VOIDF0! #WARNI0
 
"%4&0&&* VOIDT09 9VCGCM3}hVCGCM2zVCGCM1=VCGCOM	acQ	@Q@A@"Q	@	#@ $Qw,aKVCGCM2	%9 9	%A
	t%,aKVCGCM2	C	($@t$QGQ	t%,aGVCGCM2QacQ	@A@&6 6	'acQ	@	(acA@#A@(A@'	#&QOQS	t%,aKVCGCM2	%	t%: :,aGVCGCM2QacQ	@A@&	'acA@"	(acA@#A@(A@'	#&QOQS	t%8 8,aKVCGCM2	%,aw VCGCOM,aG"VCGCOM	QacQ	@	'	acA@#A@'	#: :,aK VCGCOM	@H,aS VCGCOM	#	!!$VCGCM2! $VCGCM2!$VCGCM2!$VCGCM2!"# #$VCGCOM!$$VCGCOM!#VOID!#SEQ !#GENLA0!#GENSW0
 
"%4*0&