

>D( FLOW: :VCGCM3}hVCGCM2zVCGCM1=VCGCOM	QK	A	@ "QS	"	Qw,aKVCGCM2	#; ;    acQ	@Q	@Q	@Q	@		"    acQ	@Q	@Q	@Q	@		"    acQ	@Q	@Q	@Q	@	: :	"    (acQ	@Q	@Q	@Q	@		"    4acQ	@Q	@Q	@Q	@		"@acQ	@Q	@Q	@; ;Q	@		"    LacQ	@Q	@Q	@Q	@		"    Xac Q	@Q	@Q	@Q	@		"dac"Q	@Q	@; ;Q	@Q	@		"    pac$Q	@Q	@Q	@Q	@		"    |ac&Q	@Q	@Q	@Q	@		"ac(Q	@: :	Q	@Q	@Q	@		"    ac*Q	@Q	@Q	@Q	@		"     ac,Q	@Q	@Q	@Q	@		",	9 9*i: questionable operator in flow context*n.9Qw,aGVCGCM2Qac.C@:Q	@ac0Q	@; ;Q	@	"	QQK	Qac2A@Q@	$	ac4A@"A@$	"8ac0Q	@Q	@	"Qw: :,aK6VCGCM2	%QK	A
		&			&QK	A
		&		&9 9QK	A
		&		& 	*i: bogus operator data mode*n. $	%L: :Qw,aG6VCGCM2Qac8C@%Q	@#	ac:A@&Q	@		$	ac4A@"A@$: :	"x	#LF,yyyyy9yy9b99yyy99)9: :85qyg9AyyMuyyy9Ye9yyyyyyy{y
9 9&yyy9yy}y	yy!99yy-	*i:  bogus operator in f9 9low*n.!Qw,aGVCGCM2Qac8C@"Q	@X	!
!!!                                 ; ;!>! !&>!$VCGCM2!>$VCGCM2!<#SEQ !:#GENMR !8#LOAD!.#FLOWT0!*#FLOWIF9 9!#FLOWC0!2#FLOWV0!B#GENBR0!,#FLOWS0!0#FLOWU0!#FLOWEQ!#FLOWGE! #FLOWGT!"#FLOWLE!$# ##FLOWLT!&#FLOWNE!(#FLOWN0!4#FLOWF0!6#WARNI0!@#PANIC 
 
"%<(0&g & FLOWC09 9VCGCM3}hVCGCM2zVCGCM1=VCGCOM		acQ	@Q	@	"Qw,aKVCGCM2	#QK	A
: :		$         	$QK	A
		$		$QK	A
		$!%		8 8	$(	*i:  bad convert destination mode in flow*n.,	#L""Qw9 9,aGVCGCM2QacC@-Q	@+	acA@$Q	@		%	acA@"A@%	"	!!2 2!                                 !g!&g!$VCGCM2!#LOAD!#GENBR0!#SEQ !#PANIC 
 
"%4&0&h(0 FLOWIF< <VCGCM3}hVCGCM2zVCGCM1=VCGCOM	Qw,aKVCGCM2	AacA@	"Qw,aGVCGCM2; ;Q,aGVCGCM2	QacA@"	#acQ	@A@$Q	@Q	@		%acQ	@A@&A@A@"6 6	'acA@'A@%A@#	(@ )Qw,aKVCGCM2	AacA@	"Qw: :,aGVCGCM2Q,aGVCGCM2	QacA@"	#acQ	@A@)Q	@Q	@		%acQ	@: :	A@&A@A@"	'acA@'A@%A@#	(@ $BacA@	*acA@	"	Q: :	"QQw,aGVCGCM2Q,aGVCGCM2Q,aGVCGCM2	QacA@"	#ac; ;Q	@A@)Q	@Q	@		%acA@*	'acA@	+	ac A@Q@	,acQ	@A@$Q	@9 9Q	@		-acQ	@A@&A@A@*	.acA@.A@-A@,A@+A@'A@%A@#	(x<	)7 7	A	$A	&QS	(	!h!
!h! h!!h!$VCGCM2!/ /$VCGCM2!$VCGCM2! #FLOW!$#GENGE0!&#GENMR !#GENLA0!"#SEQ !#MKLAB0
 
"%H00&k ( FLOWS0; ;VCGCM3}hVCGCM2zVCGCM1=VCGCOM	QK	A
acA@	"Qw,aGVCGCM2Qac: :Q	@A@#A@A@"	$Qw,aGVCGCM2	QacA@"	%acQ	@A@&A@Q	@		': :acA@$A@'A@%	$Qw,aGVCGCM2QacQ	@A@#A@Q	@		$Qw: :,aGVCGCM2QacQ	@A@&A@Q	@		%	acA@$A@%	$:	&A	#QS	$	!3 3k!!k!$VCGCM2!$VCGCM2!#FLOW!#SEQ !#GENLA0!#MKLAB0
 
"%6(0&A& FLOWT0; ;VCGCM3}hVCGCM2zVCGCM1=VCGCOM	Qw,aGVCGCM2QQK	A
,aGVCGCM2Q; ;	acQ	@A@"	#acQ	@A@$Q	@Q	@		%	acA@#A@%	#$A	"QS
Qw; ;,aGVCGCM2QacQ	@Q	@Q	@Q	@		#-	#	!$VCGCM2!$VCGCM2!#VOID!#FLOW !#SEQ 
 
"%6&0&k ( FLOWU0; ;VCGCM3}hVCGCM2zVCGCM1=VCGCOM	QK	A
Qw,aGVCGCM2QacQ	@A@"A@9 9Q	@		#Qw,aGVCGCM2QacQ	@A@$A@Q	@		%	acA@#A@%	#; ;acA@	&Qw,aGVCGCM2QacQ	@A@"A@A@&	#Qw,aGVCGCM2Q9 9acA@&	%acQ	@A@$A@Q	@		'acA@#A@'A@%	#.	$A	"QS	#	5 5!k!!k!$VCGCM2!$VCGCM2!#FLOW!#SEQ !#GENLA0!#MKLAB0
 
"%6(0&d"& FLOWV09 9VCGCM3}hVCGCM2zVCGCM1=VCGCOM		acQ	@Q	@	"Qw,aKVCGCM2	#QK	A
: :		$         	$QK	A
		$		$QK	A
		$!%		< <	$(	*i:  bad switch data mode in flow*n.,	#L""Qw,aGVCGCM29 9QacC@-Q	@+acA@$Q	@	QacA@"Q@	"	!!!                                 1 1!d!&d!$VCGCM2!$VCGCM2!#LOAD! #SEQ !#PANIC !#GENBR0
 
"%6&0&OD< FLOWEQ9 9VCGCM3}hVCGCM2zVCGCM1=VCGCOM	Qw,aKVCGCM2	",aKVCGCM2	#,aKVCGCM2	$9 9	t#,aKVCGCM2	C,aKVCGCM2	AQK	A%acA@"Q	@A@%Q	@		&: :			t",aKVCGCM2	C,aKVCGCM2	A,QK	A%acA@#Q	@A@%Q	@		&9 9		0		'	(A)	t#,aKVCGCM2	C,aKVCGCM2	AM,aKVCGCM2	AQ: :QK	A%acA@"Q	@A@%Q	@		&	U	t",aKVCGCM2	C,aKVCGCM2	Ak5 5,aKVCGCM2	AoQK	A%acA@#Q	@A@%Q	@		&	s		'	(	)G	t#9 9,aKVCGCM2	C,aKVCGCM2	A,aKVCGCM2	AQK	A%	acA@"Q	@: :A@%Q	@		&		t",aKVCGCM2	C,aKVCGCM2	A.,aKVCGCM2	A2QK; ;	A%acA@#Q	@A@%Q	@		&	6		'	(	)
	t#,aKVCGCM2	C,aKVCGCM2: :	AS,aKVCGCM2	AW,aKVCGCM2	A[,aKVCGCM2	A_QK	A%acA@": :	Q	@A@%Q	@		&	c	t",aKVCGCM2	C,aKVCGCM2	Ay,aKVCGCM2	A}9 9,aKVCGCM2	A,aKVCGCM2	AQK	A%acA@#Q	@A@%Q	@		&				'; ;			(	
)M	*i: bad flow EQ data mode*n.!	$LHHNQw,aGVCGCM2; ;Qac C@"Q	@ Qw,aGVCGCM2Qac"Q	@A@*A@+Q@	,	ac$A@)Q@9 9Qw,aGVCGCM2Qac"Q	@A@-A@.Q@	/	A0	A1		0pm: :	ac&A@(A@-	A
ac&A@(A@*	A
~n	ac&A@(A@-	A
ac&A@(A@*9 9	Aq	ac&A@(A@-	Aac&A@(A@*	A
 t(	A2ac(Q@	*: :	A	-A	(QS	&	vQw,aKVCGCM2	3QK	A
	A4C		4FQK: :	A
		4IM		4PQK	A
		4SW		4Z?	3L@@JJ9 9TT]	ac*A@4Q	@		5	ac,A@'Q@	6ac.A@(A@.Q@	7	ac0A@/A@79 9	A@,A@6A@5	&sQw,aKVCGCM2	8QK	A
	A4		4: :QK	A
		4		4"QK	A
		4%)		4,         8L: :&&/	ac*A@4Q	@		5	ac,A@'Q@	6ac.A@(A@+Q@	7ac0A@,9 9A@7A@/A@6A@5	&-,Qw,aKVCGCM2	9QK	A
	A4g		4: :jQK	A
		4mq		4tQK	A
		4w{		4~c	9Ld9 9
dnnxxac.A@(A@+Q@	5	ac0A@,A@5	&	ac*A@4Q	@		5ac,; ;A@'Q@	6ac.A@(A@.Q@	7	ac2A@(Q@	:ac0A@&A@:A@/A@7A@6A@5: :	&-	0L--I!O!
O!!	O!!!                                 5 5O! !%!.!4!	!!!O!&$VCGCM2!$$VCGCM2! 9 9$VCGCM2!"$VCGCM2!*$VCGCM2!,$VCGCM2!.$VCGCM2!@#SEQ !<#GENMR !:#GENBR0!>#LD!B% %#ST!2#REACH !(#FLOW!6#SAFE!0#PANIC !4#ALLOC0!8#FREET0
 
"%\<0&?X": FLOWGE9 9VCGCM3}hVCGCM2zVCGCM1=VCGCOM	Qw,aKVCGCM2	",aKVCGCM2	#,aKVCGCM2	$; ;	t#,aKVCGCM2	C,aKVCGCM2	AQK	A
acA@Q	@		%acA@": :Q	@	&	acA@&A@%	'		acA@Q	@		%	acA@"Q	@	&	acA@&A@%	'9 9			t",aKVCGCM2	C,aKVCGCM2	ALQK	A
acA@Q	@		%ac; ;A@#Q	@	&	acA@&A@%	'	T	acA@Q	@		%	acA@#Q	@	&	acA@&A@%; ;	'	P		(	)A*	t#,aKVCGCM2	C,aKVCGCM2	AQK	A
		Q: :QK	QacA@Q@	%	ac A@"Q	@	&	acA@&A@%	'		ac A@"Q	@	'9 9		         t",aKVCGCM2	C,aKVCGCM2	A@QK	A
acA@	Q	@		%ac; ;A@#Q	@	&	acA@&A@%	'	H	acA@
Q	@		%	acA@#Q	@	&	acA@&A@%: :	'	D		(	)A*	t#,aKVCGCM2	C,aKVCGCM2	A,aK"VCGCM2	A: :QK	A
acA@Q	@		%	acA@"Q	@	&	acA@&A@%	'		acA@Q	@	; ;	%	acA@"Q	@	&	acA@&A@%	'			t",aKVCGCM2	C,aKVCGCM2	A?9 9,aK"VCGCM2	ACQK	A
acA@Q	@		%	acA@#Q	@	&	acA@&A@%	'8 8		K	acA@Q	@		%	acA@#Q	@	&	acA@&A@%	'	G		(	)	                *{	t#: :,aKVCGCM2	C,aKVCGCM2	A,aK"VCGCM2	AQK	A
		QQK	: :QacA@Q@	%	ac A@"Q	@	&	acA@&A@%	'		ac A@"Q	@	'	9 9	t",aKVCGCM2	C,aKVCGCM2	A;,aK"VCGCM2	A?QK	A
acA@: :Q	@		%	acA@#Q	@	&	acA@&A@%	'	G	acA@Q	@		%	acA@#Q	@	&7 7	acA@&A@%	'	C		(	)A*~	t#,aKVCGCM2	C,aKVCGCM2	A9 9,aK"VCGCM2	AQK	A
acA@Q	@		%	acA@"Q	@	&	acA@&A@%	'9 9			acA@Q	@		%	acA@"Q	@	&	acA@&A@%	'		t",aKVCGCM2	C; ;,aKVCGCM2	A>,aK"VCGCM2	ABQK	A
acA@Q	@		%	acA@#Q	@9 9	&	acA@&A@%	'	J	acA@Q	@		%	acA@#Q	@	&	acA@&A@%	'	F5 5		(	)	                *z	t#,aKVCGCM2	C,aKVCGCM2	A,aK"VCGCM2	A: :,aK$VCGCM2	A,aK&VCGCM2	AQK	A
acA@Q	@		%	acA@"Q	@	&9 9	acA@&A@%	'		acA@Q	@		%	acA@"Q	@	&	acA@&A@%	'		t"6 6,aKVCGCM2	C,aKVCGCM2	AI,aK"VCGCM2	AM,aK$VCGCM2	AQ9 9,aK&VCGCM2	AUQK	A
acA@Q	@		%	acA@#Q	@	&	acA@&A@%	': :		]	acA@Q	@		%	acA@#Q	@	&	acA@&A@%	'	Y		(	)	*}	9 9*i: bad flow GE data mode*n.         $L|{~Qw,aGVCGCM2	Qac(C@5 5Q	@Qw,aGVCGCM2Qac*Q	@A@+A@,Q@	-ac,A@*Q@Qw9 9,aGVCGCM2Qac*Q	@A@.A@/Q@	0	A1	A2		                1`]ac.9 9A@)A@.	A
ac.A@)A@+	A
n^v	ac.A@)A@.	A
ac.A@)A@+	A; ;a	ac.A@)A@.	Aac.A@)A@+	A
d	A3ac0Q@	+A	.9 9A	)QS	'	fQw,aKVCGCM2	4QK	A
		                53		56QK	A
: :		59=		5@QK	A
		5CG		5J/	4L
00::D: :DM	acA@5Q	@		%	acA@(Q@	&ac2A@)A@/Q@	6acA@0A@6A@-9 9A@&A@%	'cQw,aKVCGCM2	7QK	A
		5		5QK: :	A
		5		 5QK	A
		5		5	7L9 9	acA@5Q	@		%	acA@(Q@	&ac2A@)A@,Q@	6	acA@-A@69 9	A@0A@&A@%	'Qw,aKVCGCM2	8QK	A
		                5W		5Z: :QK	A
		5]a		5dQK	A
		5gk		5nS	8LTT: :^^hhqac2A@)A@,Q@	%	acA@-A@%	'	acA@5Q	@		%acA@(: :Q@	&ac2A@)A@/Q@	6	ac4A@)Q@	9acA@'A@9A@0A@6A@&A@%	': :{	1L9!        !!!?!	!
!	!!!9 9!!!!!!!!!!!! !!! 9 9"!#!$!
&!.!4!!!!?!8$VCGCM2!6$VCGCM2!29 9$VCGCM2!4$VCGCM2!D$VCGCM2!F$VCGCM2!H$VCGCM2!>#SEQ !@#GENMR !:#GENBR0!T#LD!V* *#ST!L#REACH !<#LOAD!B#VOID!P#SAFE!J#PANIC !N#ALLOC0!R#FREET0
 
"%Z:0&"