 " CLRAR09 9ARGCOM,aKARGCOM	@H,aSARGCOM,aKARGCOM	@H,aSARGCOM,aKARGCOM	A7 7,a7ARGCOM,aGARGCOMQacQ	@A@	A,aSARGCOM		!'! $ARGCOM!$ARGCOM!#LSFREE
 
"%$"0&-$ PUTARG9 9ARGCOM	
too many arguments. 		,agARGCOMacQ	@A@C@		": :QK,a7ARGCOM,aSARGCOMQK,aSARGCOM,akARGCOM	@	"	"	!}!~( (-!-!@!$ARGCOM!$ARGCOM!$ARGCOM!#ERRMSG
 
"%*$0&" INITA0 ARGCOM	A,aSARGCOM		!$ARGCOM
 
"%""0&N& SETUP09 9ARGCOMfHSWT$CM		"@ ,aS`SWT$CM,aKARGCOM	@H#	#@H#
	#A	"	: :QKA7#,agARGCOM,agARGCOM	@	#A	#	#@H$	$7 7	@H$(	$AA7$,aKARGCOM	Qg7).7	($9	($@:	$$#	@7 7,ak`SWT$CM	@A7$,aKARGCOM,aw`SWT$CM,aS`SWT$CM;?!~N!" "$`SWT$CM!$`SWT$CM!$ARGCOM!$ARGCOM!$ARGCOM
 
"%*&0&U( ACCES09 9/CICOM                                                                                 SAVCOM		",aKCICOM Q_	#%,agCICOM 	@	": :			t#,aK                                                                     SAVCOM	$A%	(%@	%t#,ag                                                           SAVCOM 	#C:%C?AD$,ag;SAVCOM9 9	@!,	@ &	(%@/	%t#,ag                                                           SAVCOM6	#C:%C?AD,aK;SAVCOM	$$B: :                           A	&Q_	C	#C:%C?AD,aK:SAVCOM	"                           G	(&007                                 U* *!U!$                                                           SAVCOM!$                                                                     SAVCOM!$CICOM !$:SAVCOM!$;SAVCOM
 
"%.(0&