:F" START09 9/CICOM "=statistics="yes""=statsdir=/sh=pid=8 8	can't open record file*n. ac6a@Q@A@ac8Q@a@	@HCac:a@"A@9 9,aS<	CICOM 	Cac>A@C@)ac@,a
@<	CICOM 0		,aS<	CICOM 59 9		!}:!!:!f:!@$	CICOM !>#OPEN!<#EQUAL !:#EXPAND!B#PRINT !D #WIND
 
"%"0&
" STOPL07 7/CICOM ,aK	CICOM 	%ac,a
@	CICOM 		!}
!$	CICOM !#CLOSE 
 
"%""0&)D" LOGIN0: :/CICOM "#=date= =time= =pid= =user=*51t*2i 	,aK4	CICOM 	%9 9ac6a@Q@A@ac8,a
@4	CICOM Q@,a
@:CICOM ac8,a
@4	CICOM Q	@5 5	Q	@ac<A@,a
@4	CICOM ac>,a
@4	CICOM 		!})!f!
)!>% %$CICOM !8$	CICOM !:#EXPAND!<#PRINT !@#PUTCH !B#FLUSH$
 
"%"0&$&$ PROCE0: :/CICOM "_helloaca@Q@A@	%Q	A

acA@"Q@ac: :A@",aKCICOM 	0ac A@",a
@"CICOM 		!$!f$!$$CICOM !  $CICOM !#SVGET !#LSMAKE!#PUTBA0!"#NETTR0
 
"%
$0&'V
> SHELL 9 9HISTCMfHSWT$CM/CICOM "ANY$"Shell Recursion Limit Exceeded9 9!*n"6=varsfile="B
_nottyeof"Luse 'stop' to e: :xit the subsystem*n"p=varsfile="|=histfile=	9 9aGQaQQQQas
		,agCICOM 	@	acA@a@		:	8 8,akCICOM 	@@ ,awCICOM ,aSCICOM QK,aS
CICOM ,aKCICOM 	@HC	@ 6 6,aSCICOM ,aKCICOM 	A
;aca@6A@;ac/,awCICOM ,aKCICOM : :,aSCICOM ac ac"@		<ac$A@=	%T,aK&`SWT$CM	A,aKCICOM 	5: :Wac(A@<[	<%d,aK&`SWT$CM	Acac*A@=A@<	%qgac,A@=A@<; ;	%zpac.A@=A@<	%yac*A@=A@<	%ac0A@=A@<	%ac*: :A@=A@<	%ac2A@=A@<ac4A@=A@ac6ac8A@,aK&`SWT$CM	A
< <		<3	<Cac:A@A@A@	A,agCICOM E,awCICOM ,aG
CICOM Q9 9ac<Q	@	%TFac8A@SS9		<@ ,aS&`SWT$CMac8A@MX,aK>SWT$CM5 5	A,aKCICOM 	%f	@ac@a@BQ@A@	AacA@a@LKuj; ;,aKCICOM 	@HC,aKCICOM 	A
;	acBa@pA@;,aKDHISTCM	@HC,aK>SWT$CM9 9	A
acFa@|acHacJ,aKCICOM 	@H,aSCICOM 	<:	!}!~!: :!!!'!'!
'!''!$CICOM !$
CICOM ! $CICOM !&< <$CICOM !($CICOM !$CICOM !$CICOM !H$SWT$CM!0$`SWT$CM!N$HISTCM!.#GETCL !4#EVALN09 9!8#EVALFN!:#EVALIT!6#EVALCN!J#SVGET !F#ISATTY!#SHANY$!#MKONU$!#PRINT !"#SVREST!$; ;#PROCE0!*#SVPUSH!,#SAVES0!2#SINGL0!<#PARSE !>#LSFREE!@#REMOV0!B#BREAK$!D#ERRMSG!L#SVSAVE !P#HISTT0!R#RESTO0!T#SVPOP 
 
"%L>0&
9$ SINGL09 9	continue? . acA@C@acA@"A@	C	"%	%: :	%"!		QS"		QS&	"%.	%1-acA@"A@*01 1		!}!~!!9!
! !N!n!#GETCH !#PRINT 
 
"%($0&'," NETTR0: :"[*2i] "
[*2i:*s] 	ac"Q	@	A
ac$A@a@Q	@: :ac$A@a@Q	@Q	@ac&Q	@A@ac(A@A@		!'!
'!$#MISSIN !&#PRINT !(#LSPUTF!*#PUTCH 
 
"%,"0&\( SEARC0: :fHSWT$CM	@ QSQS	"QK	#A$	%%    	%	%&	$	%< <	$&	A
	%A
		$	%A		*	%Q_	C	"QS9 90	%Q_		C	"QS		94
&		t#,agaSWT$CM	@,a_aSWT$CM9 9	A#?C	t#,aKaSWT$CM	%A
	(#@O	("ST	$L'U! !\!"!'\!,\!$aSWT$CM
 
"%8(0&J& NEXTU09 9fHSWT$CM	A"QK	%		%QK	#	"QK	$#	A
7 7QK	A
		"QK	$	!		Qw,agaSWT$CM	@9 9,a_aSWT$CM	AQS',Qw,aKaSWT$CMQS	A
Qk	@;QkAB0 0	"L"C!!J!"!'J!,J!$aSWT$CM
 
"%0&0&+b> GETCL ; ;fHSWT$CM/CICOM "] "QUIT$ "_prompt" QUIT$ 	ac$A@: :,aw&CICOM ,aG(
CICOM 	Qjac*Q	@j	A
aG,QjaQlQjQoQlas.; ;,aw&CICOM ,aK0CICOM QS	@ ,aS0CICOM ac2a@Q@A@	BCac4a@A@: :Q@A@4		4QK	A,aK6`SWT$CM	AD,aw&CICOM ,aG(
CICOM Qjac*8 8Q	@j	A
ac8ac:ac<Q@A@T	A55A
,aK6`SWT$CM	Ac,aw&CICOM < <,aG(
CICOM Qjac>A@6Q	@j	7BCgwac@A@6A@7A@QK	A	6QS9 9	acBQ	@A@6,aKDCICOM 	0acFA@6,a
@&CICOM 	A$7	7; ;	A8	acHA@6A@8	Cac@A@6A@A@a(	@ 5axQK	A		4H; ;8acJQ	@A@A@9A@A@:	:Aac@Q	@A@:A@JQK	;A<		<X9 9	=%	`Y	%
cYc	=AacLQ	@A@f,aw&CICOM ,aG(
CICOM Qj9 9ac*Q	@j	A
AacNQ	@	CacLQ	@A@A;acPa@ ac$A@	4	9 9[		t;,agRaSWT$CM	@,a_RaSWT$CM	A;                           	t;,aKRaSWT$CM	=A
	(;@!9 9$	<L\\%!}!~!!!!+!f+!
	!	 !5 5#+!_+!,+!'+!4$CICOM !6$
CICOM !R$CICOM !>$CICOM !D9 9$`SWT$CM!`$aSWT$CM!L#LSGETF!@#SVGET !V#LSPOS !\#HISTS0!8#ISATTY!<#MKONU$!:#LSQUIT!2; ;#BREAK$!B#SCOPY !F#GOSSIP!H#MAILC0!J#PUTLIN!N#LSDEL !P#LSJOIN!T#NETTR0!X#SEARC0!Z#LSFREE !^#RVONU$
 
"%0>0&,$ PUTBA0< </CICOM ";	,awCICOM ,aKCICOM 	AQK,aSCICOM ,awCICOM 9 9,aGCICOM QacA@"a@	#	acA@#Q	@	#acQ	@A@#QS	@ QS 		!$CICOM !$CICOM !#LSJOIN!#LSMAKE
 
"%*$0&"
. EVALN09 9fHSWT$CM	@ "#QK	$@ %A&	'%	%	'(	&	'$(: :	A
	'A
		&	')	("+	"@H",	(#02	#; ;	@H#3	#A7	"A:)	)A
>	%E8	*L*-	)*L1: :J4R=	A	'C	%@H+acQ	@A@+A@,acA@,A@A@acA@,X9 9		QS	-	%			t$,agaSWT$CM	@,a_aSWT$CM	A$uy	t$,aKaSWT$CM	'A
: :	($@	(%	
	&L&!~!!!!"!2 2'!;!Z!z!	,! $aSWT$CM!#LSCUT !#LSDEL !#PUTBA0
 
"%4.0&
sn2 EVALFN9 9fHSWT$CMFPORTCM/CICOM "_quote_opt"YES" """ "$9 9""&fn		QS	"#ac*Q	@A@A@$A@A@%		unpaired right bra; ;cket. ac,Q	@A@%C@	unpaired left bracket.)ac,Q	@A@$C@*(		QS: :=	$A	%A
DG	$A
	%AK)N	$A	%AR>U	ca: :n't create temp for function output.W	#Cac.A@	#Cac,Q	@A@%C@XAn: :ac0A@#ac2A@#v	can't create function temp. 	"Cac.A@	"Cac,; ;Q	@A@%C@	ac0A@"ac2A@""		%$B&@H'$B(ac4Q	@A@(A@'	)ac6: :*Q	@A@$A@&ac8A@)A@"ac:A@A@"ac0A@"ac<A@)A@	#,aS>SWT$CMac@; ;A@"	Cac,A@A@A@+mac0A@#acBa@Q@A@	%	
acDQ@9 9a@	A
	A*	@ *acFA@+A@acHA@
acJA@,A@#	%	&	@ : :	-,.A/		/,	0A
	C	*A
5acLA@,A@-,a
@NCICOM A@
A@9 9	---8	0Cac6A@,A@-A@
	-@H-L-2	*A
acPA@.a@ 	'; ;	acRA@'A@,	,[	acPA@.a@"	'	acRA@'A@,	,	acRA@+A@,	*@HCacP9 9A@.a@$	'acRA@+A@'%acHA@ac6A@+A@
A@
	$@H'	acLQ	@A@'< <A@+A@
A@ac<A@+A@v	"%
6acTA@"5	#%
>acTA@#=QK< <	@DC,aKVCICOM 	2FacXQ	@,a
@ZCICOM a@&JQK	1	/		t.,ag\aSWT$CM9 9	@,a_\aSWT$CM	A.W[	t.,aK\aSWT$CM	0A
	(.@g	(-kl	/L: :00m!}!~!	!!
!!!!s!
s!"s5 5![!]s!,s!'s!j$CICOM !f$CICOM !^$CICOM !N$SWT$CM!l< <$aSWT$CM!Z#LSGETF!P#SHELL !R#SVGET !T#EQUAL !>#MKTEMP!:#SEARC0!<#ERRMSG!@#REWIND!B#TRUNC 9 9!D#LSSUBS!F#LSDEL !H#LSPUTF!J#PUTCH !L#LSFREE!V#LSALLO!X#BREAK$!\#LSINS !b#LSJOIN!`                                                                   LSMAKE!d#RMTEMP!h#NETTR0
 
"%>20&3B0 EVALIT9 9fHSWT$CM/CICOM " ";"it	@ "	QSacQ	@A@A@#A@9 9A@$	unpaired right paren. acQ	@A@$C@	
unpaired left paren.(ac9 9Q	@A@#C@)'		QS;	#A	$A
BE	#A
	$AI(L	#9 9	A	$AP<S	too many iteration groups.U		$"	@acQ	@A@#C@V?9 9e		("@$#B%#@Ht"	QSQGQ$	%@H&#B'acQ	@A@'A@&QS$acA@(a@	&: :ac Q	@$A@&ac"Q	@A@#A@%o	"AQK	%-		)	()@/	ne9 9sted iteration not supported. 2	)$"	@t)QKQg00QGQ$acQ	@$A@C@3: :		QSE],		QgcQSac$A@*A@	A)t)QK	(A+	,C	t); ;QGQ&ac"Q	@&A@A@QK&	(	+sw	t)QGQ&QGQ(acQ	@&A@	A@-9 9A@Q	@(	A)$"	&llQ	A		)	()@,	unbalanced iteration groups./9 9	)$"	@t)QK	A
-QGQ$acQ	@$A@C@0@		QSS)		)9 9	()@Z	unbalanced iteration groups.]	)$"	@t)QK	A[acQ@A@C@^W< <n	@ .ac&Q	@A@A@.A@	")	)@H)	A$)	@t)	QGQ$QK	@H&ac(9 9	Q	@$A@&A@(	t)!QGQ*ac*A@.Q	@*Q	@$A@A@
ac,Q	@$A@
	(QS$9 9	acA@(a@	&ac A@*A@&ac A@*A@.k}b	A)t)QGQ&ac,Q	@&A@
9 9	A)$"	gUUQK	%lac"A@*A@A@ac,Q	@A@
	*QSkac,; ;A@*A@
}'QK	%	,aK.CICOM 	3ac0Q	@,a
@2CICOM a@QK9 9	/	
		t(,ag4aSWT$CM	@,a_4aSWT$CM	A(	t(,aK4aSWT$CM	,A
	((@: :),	+Ltt-!}!~3!!!3!
3!	
! !< <(!)3!,3!
'3!>$CICOM !:$CICOM !@$aSWT$CM!$#SEARC0!&#ERRMSG!(#LSSUBS7 7!,#LSJOIN!*#LSMAKE!.#LSDEL !0#LSALLO!2#LSCOPY!4#LSCUT !6#LSINS !8#LSFREE!<#NETTR0
 
"%\00&00$ INITI0; ;HISTCMFPORTCMARGCOM/CICOM "'"'"	@ ,aSHISTCM,aSCICOM 	A,aSARGCOM; ;	"At",aSPORTCM,aS	PORTCM	A"%	A"At",aS ?PORTCM	A"%	!ac"6 6ac$,a
@&CICOM a@ac(ac*ac,		!!
0!$CICOM !($CICOM !: :$ARGCOM!$PORTCM! $	PORTCM!"$?PORTCM!$HISTCM!$#LSINIT!&#LSMAKE!*#SVINIT!,#HISTI0 !.#MAILI0
 
"%$$0&}:" SAVES09 9fHSWT$CM                                                                                SAVCOMFPORTCMUPARCOM/CICOM ARGCOM,aKCICOM 	C9AD,aG<SAVCOMQac: :,a
@ARGCOMQ	@A@,aKARGCOM,awCICOM ,aS                                                           SAVCOM	A,aSARGCOM,aKCICOM ; ;	9@AD,aGvSAVCOMQac,a
@PORTCMQ	@A@,aKCICOM 	9@AD,aG ZSAVCOMQ; ;ac,a
@"
PORTCMQ	@A@,aKCICOM 	9@AD,aG$2SAVCOMQac,a
@&PORTCMQ	@9 9A@,aKCICOM 	9@AD,aG(SAVCOMQac,a
@**PORTCMQ	@A@,aKCICOM 	99 9	@AD,aG,zSAVCOMQac,a
@.@PORTCM	Q	@A@ac,a
@0SWT$CM,a
@.@PORTCMA@: :,aK2PARCOM,awCICOM ,aS4                                                                     SAVCOM		!}!
}!!}!$ARGCOM!9 9$ARGCOM!$CICOM !6$PARCOM!"$PORTCM!&$
PORTCM!*$PORTCM!.$*PORTCM!2$@PORTCM! 9 9$vSAVCOM!$$ZSAVCOM!($2SAVCOM!,$SAVCOM!0$zSAVCOM!$<SAVCOM!$                                                           SAVCOM!8$                                                                     SAVCOM!4 $SWT$CM!#MOVE$ 
 
"%$"0&z:" RESTO07 7fHSWT$CM                                                                                SAVCOMUPARCOMFPORTCM/CICOM ARGCOM,awCICOM ,aK                                                           SAVCOM,aSARGCOM6 6,aKCICOM 	C9AD,aG<SAVCOM	QacQ	@,a
@ARGCOMA@,aKCICOM 	9@AD: :,aGvSAVCOM	QacQ	@,a
@PORTCMA@,aKCICOM 	9@AD,aG ZSAVCOMQac; ;Q	@,a
@"
PORTCMA@,aKCICOM 	9@AD,aG$2SAVCOM	QacQ	@,a
@&PORTCMA@6 6,aKCICOM 	9@AD,aG(SAVCOM	QacQ	@,a
@**PORTCMA@ac,a
@,@PORTCM7 7,a
@.SWT$CMA@,aKCICOM 	9@AD,aG0zSAVCOM	QacQ	@,a
@,@PORTCMA@: :,awCICOM ,aK2                                                                     SAVCOM,aS4PARCOM		!z!
z!!z!$ARGCOM!9 9$ARGCOM!$CICOM !"$PORTCM!&$
PORTCM!*$PORTCM!.$*PORTCM!0$@PORTCM!8$PARCOM! 9 9$vSAVCOM!$$ZSAVCOM!($2SAVCOM!,$SAVCOM!4$zSAVCOM!$<SAVCOM!$                                                           SAVCOM!6$                                                                     SAVCOM!2 $SWT$CM!#MOVE$ 
 
"%$"0&:(" ERRMSG9 9/CICOM "E *p	acQ	@Q	@QK	A
acA@A@Q	@aca@Q	@: :
,awCICOM ,aG
CICOM 	Q
ac Q	@
,awCICOM ,aG"CICOM Q
ac$Q	@
A@: :	@ ,awCICOM ,aS"CICOM 		!5!'5*p*n.   !$CICOM ! $
CICOM !$# #$CICOM !#CONTE0!#PRINT !#LOGIN0!"#WIND!&#LSFREE
 
"%."0&8($ CONTE0< </CICOM "C *s	QK	A		acQ	@A@acA@A@QK	A"ac: :A@A@A@"A@,aK	CICOM 	%%acQ	@Q@A@ac a@Q@$		!}9 94!4!<!
4!^4*#c*n.  !"$	CICOM !#LSPUTF!#PUTCH ! #PRINT  !$#LSEXTR!&#LOGIN0
 
"%f$0&
( GOSSIP9 9fHSWT$CM"=gossip=/=user=" =gossip=/*=pid="0_pause9 9_gossip">_vth_gossip"Jgossip [*i+]? "Zgossi9 9
p [*i$]? 	A#acja@0A@"A@	%	@ #acja@>A@"A@	%9 9	#@D#	@ $aclA@	%C		&,aKnSWT$CM	Aacpa@A@	&9 9	%6	A$acrA@&A@%actA@&acva@5+	acpa@ A@	&%P	A$: :acrA@&A@%actA@&acva@ O	$AacxA@%		baczA@%,aKnSWT$CM	A: :ac|A@%a@Ja@ZA@A@A@#o	acrA@%A@~acxA@%		!}!9 9
!
!
!
!t$SWT$CM!p#SVGET !v#OPEN!r#MKTEMP!x#FCOPY !z#CLOSE  !|#REMOVE!~#RMTEMP!#REWIND!#PAGE
 
"%((0&}X
, EVALCN: :/CICOM "=temp=/cn=pid=*i""^cn/*i"*cn		QSac.9 9Q	@A@A@"A@A@#	unpaired right brace.            ac0Q	@A@#C@	unpaired9 9 left brace.&ac0Q	@A@"C@'%		QS9	"A	#A
@                           C	"A
8 8	#AG&J	"A	#AN:Q	can't create compound node temp.S,aw2CICOM ; ;,aG4CICOM QQk	@ac6Q@A@a@Q	@ac8Q@A@	$Cac0Q	@A@"9 9C@T=,aw2CICOM ,aG4CICOM Qac6Q@A@a@"Q	@	#"%@H&"B'ac:: :	Q	@A@'A@&	(ac<A@(A@$ac>A@A@$ac@A@$	%B%acBQ	@A@"A@%acD9 9A@)Q@	"@H%&acFQ	@A@%A@)A@A@acHA@)A@acHA@(A@	QK9 9	@DC,aKJCICOM 	1lacLQ	@,a
@2CICOM a@*pQK	*	!}!~}: :!!}!!
}!{!}!'}!<$CICOM !T$CICOM !>$CICOM !B; ;#CREATE!D#LSSUBS!8#SEARC0!:#ERRMSG!@#ENCODE!F#LSPUTF!H#PUTCH !J#CLOSE !L#LSDEL !N#LSMAKE !P#LSINS !R#LSFREE!V#NETTR0
 
"%H,0&
/.$ REMOV0: :/CICOM "=temp=/cn=pid=*i,aK"CICOM 	%	@@ ",aw"CICOM : :,aK$CICOM 	",aw"CICOM ,aG&CICOM Q	"Qgac(Q@A@a@Q	@7 7ac*Q@,aw"CICOM ,aK&CICOM 	@H,aS&CICOM 		!/!/!$   $CICOM !&$CICOM !($CICOM !*#ENCODE!,#REMOVE
 
"%:$0&V8& MAILI07 7/CICOM "=mail=/=user=ac,a
@ -CICOM ,aK -CICOM ,aS")CICOM 	@: :,aS$+CICOM ac&a@Q@A@"	%ac(A@A@		ac(A@A@ac*Q@: :,a
@")CICOM 	ac,a@A@	#C		2ac.A@#	$Cac0A@#		;ac2: :A@$,aS$+CICOM 	A'LI	@,aS$+CICOM Kac0A@#		!}!~T!: :!TH}!&$)CICOM !($+CICOM !$$-CICOM !0#OPEN!6#SZFIL$!*#FINFO$!2#MAPFD !" #GETTIM!,#FOLLOW!.#CV$DQS!4#CLOSE 
 
"%F&0&$`& MAILC09 9/CICOM "=mail=/=user="_mail_check"*You have new9 9 mail*nac>a@Q@A@	BC		
	A"	ac@Q@A@"	EA?Q: :	ACAQ	acBQ@Q,a[D-CICOM 	Q',*		+Q,aSD-CICOM 8 8acFa@Q@fA@#	%<,aKD-CICOM QA,aSH)CICOM 	acJA@A@	@7 7,aSL+CICOM 		;acJA@A@acNQ@zQ@Q,agH)CICOM 	@	^Q: :,aSH)CICOM 	acPa@A@	$C		nacRA@$	%CacTA@$		wacV; ;A@%Q,agL+CICOM 	@,aSL+CICOM acTA@$		Q,aSL+CICOM acTA@$: :	acXA@a@*		!}!~!!!fA!N< <$)CICOM !R$+CICOM !J$-CICOM !V#OPEN!\#SZFIL$!F#CTOL!L#FINFO$!X#MAPFD !D#SVGET !H#GETTIM !P#FOLLOW!T#CV$DQS!Z#CLOSE !^#PRINT 
 
"%0&0&