g
: INVOL09 9fHSWT$CM"0aargaargs*aargstoccasedcdhdatehday,9 97xdbgvdeclare	vdeclared
mdropbdumphechocelif9 97celsecesachevalcexitcfisforgetcgoto3hhist9 97cifmindexhinstallationclabelhlinehlogin_name9 97anargscout-xprimos)aquote1crepeatsset ssh!bs9 97htrace"qstop#msubstr$mtake%cthen&htime2cuntil'vv9 9ars.xvpsd(cwhen+xx"j.#*06@KRY`gnu|$,;C9 9JW_env
$+29AHOV"ANY$"ANY$	ac"Q	@Q@A@ac$9 9Q@A@ac&a@ja@A@Q@	4BC		5	QK	C	uQGQn	t49 9aKi	ADaGQpac(Q	@nQ	@p	A
$		5	9		6ac*A@,aK,`SWT$CM	A
9 9ac*A@		5	Fac.Q@l,aK0`SWT$CM	Q	rac2A@,a
@4`SWT$CM	aG6Qna: :QvQnQyQvas8ac*A@	t4aKi	ADaK	7ac:ac<zac>}ac@9 97acBacDacF	acHacJacLacNacPacRacTacT9 97!acV$acX'acZ*ac\-ac^0ac`3acb6acd9acf<ach?acj9 97BaclEacnHacpKacrNactQacvTacxWaczZac|]ac~`ac: :cacfaciaclacow	7@H8L3x{
: :8"r%(+.47:	=@CFRUX[^adgmL9 9~pIj%O1&	no subroutine for internal command!!. *ac
C@+		9 9	6(ac*A@aca@Q	r,aS0`SWT$CMacQ@lac*A@	t4aKi	ADaK	C: :ac`	65	YD!}!~!!!!g!"g!fg!9 9/g!6$`SWT$CM!>$`SWT$CM!0#STRBSR!2#INDEX !:$`SWT$CM!B#MKONU$!@#ONANY$!,#CTOC!.; ;#MAPSTR!4#BREAK$!8#IOFL$ !<#MKLB$F!D#ARGCMD!F#ARGSC0!H#ARGST0!J#CASEC0!L#CDCMD !N#DATEC09 9!P#DAYCMD!R#DBGCMD!T#DECLA0!V#DECLB0!X#DROPC0!Z#DUMPC0!\#ECHOC0!^#ELSEC0!`#EVALC0!b; ;#EXITD0!d#FORGE0!f#GOTOC0!h#HISTC0!j#IFCMD !l#INDEX0!n#INSTA0!p#LINEC0!r#LOGIO0!t#NARGS09 9!v#OUTCMD!x#PRIMO0!z#QUOTE0!|#REPEA0!~#SETCMD!#SHCMD !#SHTRA0!#STOPC0!#SUBST0!8 8#TAKEC0!
#TIMEC0!#VARSC0!#VPSDC0!#WHENC0!#XCMD!#REMARK!#RVONU$!#COF$!#SWT 
 
"%6:0&
