H$ ENTER0< <=LABCOM	acQ	@	"BCacQ	@	"%	#	         "9@ADQK,aSLABCOM9 9	multiply defined label. 	"9@AD,aKLABCOM	A
acC@		#	1	"9@9 9	ADQK,aSLABCOMacA@"		#	!}!~H!H!$LABCOM!#FINDL0 !#CREAT0!#SYNERR!#FWDREF
 
"%*$0&e"( LOOKU09 9UPARCOMFPORTCM=LABCOM	,awPARCOM,aK	PORTCM	@H"acQ	@	#BCacQ	@9 9	#%	$		#9@AD@ ,aSLABCOM,aKPARCOM	B ",aSLABCOM,aKPARCOM8 8	9@"9@AD@ ,aSPORTCM	#9@%t%,aKLABCOM	A,aKPARCOM	9@"9@&9 9,aKLABCOM	t&,aSPORTCM,aKPARCOM	B "t%,aSLABCOM;,aKPARCOM	9@"97 7	@%#9@AD,aKLABCOM	t%,aSPORTCMP2		$	!}!~e!!e!. .$LABCOM!$LABCOM!$	PORTCM! $PORTCM!$PARCOM!#FINDL0!#CREAT0
 
"%,(0&!$ FINDL0: :=LABCOM	A"	("@	",agLABCOM		9@AD,aG~LABCOMQacQ	@Q	@5 5	C	"#	
		#	!!!!!=!$LABCOM!$~LABCOM!#LSCMPK
 
"%*$0&0& CREAT09 9=LABCOM	too many labels.,aKLABCOM	"CacC@		#	,akLABCOM	@9 9	acA@$Q	@	C		#	"	"9@AD$,aS~LABCOM	"#	!}0!!! $LABCOM!$~LABCOM!#LSMAKE!#SYNERR
 
"%*&0&#& FWDREF9 9=LABCOMFPORTCM	QK	9@AD,aKLABCOM	",aKLABCOM	##A
	
B`$#B(%$9@%98 8	@AD,aKPORTCM	#",aSPORTCM		!!#!$PORTCM!$LABCOM! $LABCOM
 
"%*&0&" INITL0 =LABCOM	A,aSLABCOM		!$LABCOM
 
"%""0&!" CLRLA09 9=LABCOM,aKLABCOM	@H,aSLABCOM,aKLABCOM	@H,aSLABCOM,aKLABCOM	A9 9	9@AD,aG~LABCOMQacQ	@A@	A,aSLABCOM		!!!'! $LABCOM!$~LABCOM!#LSFREE
 
"%$"0&= $ CHECK09 9=LABCOM		QS	A"	("@	*s: undefined label*n.		",agLABCOM	9; ;	@AD,aKLABCOM	A		QS,aG~LABCOMQjacQ	@jQ@A@acA@C@
Q@7 7QK	#	!}!~=!=!=!f!$LABCOM!$~LABCOM! $LABCOM!#LSEXTR!#PRINT 
 
"%$0&