6( LSGETF: :QUITCMfHSWT$CM"SHQUIT$ 	acA@,a
@QUITCM	@ ,aSQUITCM	acQ	@A@9 9QK	"@ #A$	Q	@ QacA@ac Q@Q	@	$acA@,aKQUITCM	@HC: :ac"Q	@A@A@		Q	@ Q	A$@ #QK	"ac$a@A@A@G@KA@: :A@0	$BCac&A@"A@ac(Q	@A@		%W	t$QK	Cac*A@&: :Q@ac,A@"A@&	$#%flac*A@&Q@ac,A@"A@&	$##ac.A@"A@9 9|	%	(!!!!!
!'O! $QUITCM!< <$QUITCM!&#GETLIN!#MKLB$F!"#LSALLO!$#BREAK$!(#LSDEL !*#SIGNL$!,#LSPUTC!.#LSFREE!0#LSMAKE !2#LSJOIN!4#LSPOS 
 
"%(0& " LSQUIT< <fHSWT$CMQUITCM	A,aSQUITCM,aSSWT$CM	@ ,aSSWT$CM,awSWT$CM,aSSWT$CMac5 5,a
@aSWT$CMac,a
@QUITCM		!$QUITCM!$QUITCM!$SWT$CM!$SWT$CM! $SWT$CM!$aSWT$CM!#DUPLX$!#PL1$NL
 
"%&"0&$ LSPUTF: :fHSWT$CM	QK	"acA@"Q@A@acQ@Q	@acA@"A@	A		!f !#LSEXTR!#PUTLIN!#LSPOS 
 
"%$0&$ LSJOIN9 9fHSWT$CM	QK	"acA@"A@QK	t",aSaSWT$CMQK	#	!,!' !$aSWT$CM!#LSPOS 
 
"%*$0&U( LSCMPK9 9fHSWT$CM	QK	"A#@HADQK	$	t",agaSWT$CM	@,a_aSWT$CM	A"	t"7 7,aKaSWT$CM	%A
	("@	%$$# 	A		&	$	(#@#@HADQK	$	t"9 9,agaSWT$CM	@,a_aSWT$CM	A"04	t",aKaSWT$CM	%A
	("@"	%A
: :	$A
	%CIFM		&L		&P	&	!<!=!>U!,U! $aSWT$CM
 
"%.(0&o( LSCOMP9 9fHSWT$CM	QK	"	t",agaSWT$CM	@,a_aSWT$CM	A"	t",aKaSWT$CM	#: :	A
	("@QK	$	t$,agaSWT$CM	@,a_aSWT$CM	A$	t$,aKaSWT$CM9 9	%A
	($@*	#$%2/	A		&	3		t",agaSWT$CM	@,a_aSWT$CM9 9	A"7;	t",aKaSWT$CM	#A
	("@G		t$,agaSWT$CM	@,a_aSWT$CM	A$: :JN	t$,aKaSWT$CM	%A
-	($@-1	#A
	%A
	#Cc`g		&& &f		&j	&	!<!=!>o!,o!$aSWT$CM
 
"%.(0&J( LSCUT : :	QK	"QK	A	QKQS	#acQ	@A@	acA@"Q	@	Aac9 9	Q	@A@QK	#	acA@$A@	"BQS	#"%	acA@"A@&	$'ac; ;A@%A@'acA@$A@&%	#	!!!,!#LSALLO!#LSPOS !#LSGETC!#LSPUTC
 
"%2(0&s"& LSINS ; ;fHSWT$CM	QK	A			QK	A	@ "acQ	@Q	@	A@"A@QK	@D#ac; ;A@"A@#A@acA@"A@QK	$	acA@$Q	@	%AQK	$acA@$	#ac9 9A@$A@#	%3	%t",aSaSWT$CM	"t$,aSaSWT$CM	acA@"A@	$t",aSaSWT$CM9 9	acQ	@Q	@	Q	@	"QK	$"QSacA@"A@	$t",aSaSWT$CMW		: :!!s!,!-s!'s!$aSWT$CM!#LSCOPY!#LSDEL !#LSPOS !#LSLEN  ! #LSSUBS
 
"%6&0&( LSTAKE9 9fHSWT$CM	QK	"	acA@#Q	@	$	acA@"A@%	&	acA@#A@&	A
 	$	!#LSALLO!#LSPUTC!#LSGETC
 
"%.(0&& LSDROP0 0fHSWT$CM	@ "QK	B#acA@$A@#A@"A@	"	!!#LSCOPY
 
"%,&0&L( LSSUBS; ;fHSWT$CM		Qg	@	acQ	@Q_	@D"QK	"	acA@#A@"	$QK8 8	%	acA@%Q	@	&A'	('@%	'Qg	@&A
+		t%,agaSWT$CM	@9 9,a_aSWT$CM	A%04	t%,aKaSWT$CM	&A
	(%@@acA@#A@&&/	$	!* *,L!'L!$aSWT$CM!#LSLEN !#LSALLO!#LSPOS !#LSPUTC
 
"%2(0&%$ LSDEL : :fHSWT$CM	QK	A			QK	"	acA@"Q	@	"#	acA@#Q	@	#A	@ 9 9	t",aSaSWT$CM	#t",aSaSWT$CM		!,%!$aSWT$CM!#LSPOS !#LSFREE
 
"%.$0&U& LSCOPY< <fHSWT$CM	QK	"acA@"Q	@QK	AacA@"Q[		@H#	acQ	@A@#QK9 9	$	acA@$Q	@			t",agaSWT$CM	@,a_aSWT$CM	A"%)	t",aKaSWT$CM	%: :	A
	("@5	acA@$A@%	A
		t",agaSWT$CM	@,a_aSWT$CM	A"@D: :	t",aKaSWT$CM	%A
8	("@8?		!,U!$aSWT$CM!#LSPOS !#LSALLO!#LSLEN  !#LSPUTC
 
"%2&0&6$ LSPOS 9 9fHSWT$CM	A"	("@	"Qg			Qw,agaSWT$CM	@,a_aSWT$CM	A9 9QSQw,aKaSWT$CM	A
Qk		Qw,agaSWT$CM1 1	@,a_aSWT$CM	AQS#(Qw,aKaSWT$CM	#	!,6!$aSWT$CM
 
"%*$0&5& LSMAKE9 9fHSWT$CM	acQ	@	"acQ	@A@"QK	#A$	($@         $@HADQK	A
		9 9	t#,agaSWT$CM	@,a_aSWT$CM	A#	$@HADQK	t#,aSaSWT$CM	(## #QK	%	!,5!$aSWT$CM!#LSALLO!#LENGTH
 
"%,&0&8& LSEXTR: :fHSWT$CM	QK	"A#	(#@	#Qg		t",agaSWT$CM	@,a_aSWT$CM9 9	A"	#@H$t",aKaSWT$CM	t$QS	A
	("@#	#@HADQK	A-	# 	@HAD@ QS	#@H%	!,8!$aSWT$CM
 
"%0&0& & LSLEN : :fHSWT$CM	QK	"@ #	(#@		t",agaSWT$CM	@,a_aSWT$CM	A"		t", ,,aKaSWT$CM	A	("	#$	!, !$aSWT$CM
 
"%*&0&+$ LSGETC< <fHSWT$CM		Qw,agaSWT$CM	@,a_aSWT$CM	AQSQw,aKaSWT$CMQS9 9	",aKaSWT$CM	A
Qk	@	Qw,agaSWT$CM	@,a_aSWT$CM	AQS! 	"	!,+!$aSWT$CM
 
"%*$0&.$ LSPUTC: :fHSWT$CM		Qw,agaSWT$CM	@,a_aSWT$CM	AQSQw,aKaSWT$CM	A
: :QK,aSaSWT$CMQk	@AQK	"	acA@"A@QK	#	@ #) 	#	!,.!'.!$aSWT$CM!#LSFREE
 
"%*$0&N&& LSALLO; ;/CICOM fHSWT$CM	@ "QK,a[aSWT$CM	B,agaSWT$CM
,aKaSWT$CM	BQSQK; ;	B,a[aSWT$CM,aSaSWT$CMQK	#	(#@	#,agaSWT$CM!		t#,aSaSWT$CM8 8"	@ ,awaSWT$CM,aSaSWT$CMQK	$		@ %,aKaSWT$CM	#	(#@6	t#: :,aKaSWT$CM	A
		t#,agaSWT$CM	@,a_aSWT$CM	A#>B	t#,aKaSWT$CM	A< <=M	(%@QK	$%77,aKaSWT$CMQS	@ t#,aSaSWT$CM	#B,aSaSWT$CMQK9 9	$	N	Too many linked strings*n.f	"@HCacA@C@gacw		Begin linked strin; ;g garbage collection:*n.Request: *i  Avail: *i  Open: *i*n. 	A",aKCICOM 	;acA@C@7 7acA@C@Q	@A@%,a
@aSWT$CM-ac,a
@aSWT$CMA@,aKaSWT$CM	@H5 5,aSaSWT$CMF,awaSWT$CM,aKaSWT$CM	BCGR	Open reduced to *i*n. T9 9,aKaSWT$CM	#B,aSaSWT$CM	@ ,awaSWT$CM,aSaSWT$CM,aKCICOM 	;acA@; ;C@U,a
@aSWT$CMn,aKaSWT$CM,aSaSWT$CM	@ %A$#	#@H#	t#,aKaSWT$CM9 9	%	#%	@
,aKaSWT$CM	t#,aSaSWT$CM	(%@#@H#	#@H#	A9 9	$#!	t#,aKaSWT$CM	BC"		,aSaSWT$CM	(%(	#B,aSaSWT$CM}: :	Storage reclaimed: *i*n.4,aKCICOM 	;acA@C@5A@%D!~!: :N!N!,N!'N!$aSWT$CM!$aSWT$CM!$aSWT$CM!$aSWT$CM!"$CICOM ! #PRINT ! #SWT !$#LSFREE
 
"%,&0&C& LSFREE9 9fHSWT$CM	QK	A
Qw,aKaSWT$CM	%			@ "QK	#	(#9 9	@	"Qg		t#,agaSWT$CM	@#$t$,aKaSWT$CM	#	,aSaSWT$CM: :	t#,aKaSWT$CM	A		,aSaSWT$CM	@ QS		0		t#,aSaSWT$CM	(" 	#QS		!C!,C!$aSWT$CM
 
"%,&0&" LSINIT6 6fHSWT$CM		,aSaSWT$CM	A,aSaSWT$CM,aSaSWT$CM	@ ,aSaSWT$CM		!?! $aSWT$CM!$aSWT$CM!$aSWT$CM!$aSWT$CM
 
"%""0&$&
& LSDUMP: :fHSWT$CM	Top=*i  HO=*i  NA=*i*n. 	acQ	@C@,a
@aSWT$CM,a
@aSWT$CM,a
@aSWT$CM9 9	A"	("@	",agaSWT$CM	@acQ	@A@A@"	@ #	@ $	("@1: :	",agaSWT$CM	@t",aKaSWT$CM	@DC7	($22>	VOID (*i)*n.BacQ	@: :C@CA@$	"@H"	@ $	("@W	",agaSWT$CM	@t",aKaSWT$CM	BC]	($9 9XXd	NULL (*i)*n.hacQ	@C@iA@$	"@H"acA@Q	@	("@	; ;" _*n       ".	",agaSWT$CM	@t",aKaSWT$CM	%		$#acQ	@C@9 9	@ #	t",aGaSWT$CMQQK	%..	%-/acQ	@Q	@	(#0: :	t",aGaSWT$CMQQK	A
acQ	@A@Q	@	##BacQ	@A@N: :U	acA@Q	@		t",agaSWT$CM	@,a_aSWT$CM	A%acQ	@A@A@%a: :acA@Q	@.	t",aKaSWT$CM	%|/	%U	%{	%acQ	@: :A@A@%"		!~!!!<!
! !"!!: :,l -> *i. )*5i: .  
-> *i*n.H<*3,8i>.T<EOS>.  !$aSWT$CM!$aSWT$CM!  $aSWT$CM!"$aSWT$CM!#PRINT !$#PUTCH 
 
"%,&0&
