]>$ PARSE : :/CICOM UPARCOM"ex	,aKCICOM 	?acQ	@,a
@CICOM a@ac: :acac	A,aS PARCOM	@ ,aS"PARCOMQK,aS$PARCOM,aS&PARCOM	ac(ac*Q	@; ;	%('	semicolon or newline expected.),aK,PARCOM	%
>ac.C@*		QS: :=ac0Q	@E(ac2QK	@DCac4Q	@P	ac6ac8QK	"	!}!~5 5]!]!$$PARCOM!&$PARCOM!0$PARCOM!($PARCOM!*$PARCOM!$CICOM !; ;$CICOM !.#NET !4#CHECK0!#NETTR0!#INITP0! #INITA0!"#INITL0!,#GETSYM!2#SYNERR!6#CLRLA0 !8#EXECU0!:#CLRPO0!<#CLRAR0
 
"%*$0&

c"$ NET : :UPARCOM"$	,akPARCOM	@,aKPARCOM	%	@acQ	@	@DC; ;acQ	@	BCacQ	@	@DCQK	C&QK	BC: :		QS+	too many nodes in net./		,agPARCOM>,aKPARCOM	%Eac< <C@0		QSD,aKPARCOM	@H,aSPARCOML?QK	@DCaca@,a
@PARCOM9 9QSVQK	"	!}!~c!c!
c!$PARCOM!$PARCOM!#NODE!                                                                   NODES0! #ENTER0!#SYNERR
 
"%($0&b($ NODES09 9UPARCOM	,aKPARCOM	@HC		QS,aKPARCOM	C,aKPARCOM	C9 9ac,a
@PARCOMA@,a
@PARCOMA@,a
@PARCOM	%#ac,a
@oPARCOM7 7	%*")		QS*		QS.,aKPARCOM	A,aKPARCOM	B9 9,aSPARCOM6ac,a
@PARCOMA@,a
@PARCOM,a
@PARCOM,a
@PARCOMQS2: :,aKPARCOM	C		QSO		QSSJ	QK	@DCac [QK	"6 6		!}!~!!b!!b!$PARCOM!$PARCOM! $PARCOM!& &$PARCOM!$PARCOM!$$oPARCOM!#MAKEO0!"#LOOKU0!&#GETSYM
 
"%($0&

n$( NODE: :UPARCOM	@ "#	QS,aKPARCOM	Cac,a
@oPARCOM,a
@PARCOMQS	%9 9	$	ac,aKPARCOM	%	("@acQ	@	C	(#@ac9 9Q	@	C)*		QS43ac 	%&L
!!++++8G5: :H;J	missing command name. LQK	@DC	"A\	#A
		QSac5 5C@Mb_QK	$	!}n!n!!n!$PARCOM!$PARCOM!$ $$oPARCOM!#ENTER0! #REDIR0!#ARGUM0!#GETSYM!"#SYNERR
 
"%,(0&& ARGUM08 8UPARCOM	acA@",a
@	PARCOM	#acA@#,a
@PARCOMQS	$	!$PARCOM! $	PARCOM!#PUTARG!#LSMAKE
 
"%*&0&6$$ REDIR0; ;UPARCOM	,aKPARCOM	%
acA@",a
@oPARCOM,aKPARCOM	%    	%6 6ac,a
@PARCOM,a
@PARCOM,a
@PARCOMA@"A@QSac: :,a
@PARCOM,a
@PARCOM,a
@PARCOM	A@"A@QS#QK	#	!!!66 6!$PARCOM!$PARCOM!$PARCOM!"$PARCOM!$oPARCOM!#MAKEI0! #MAKEO0!#LSMAKE
 
"%($0&T0 GETSYM: :/CICOM UPARCOM"$ac,a
@PARCOMA@",akPARCOM	@"%	%; ;	@ ,aSPARCOM,aSPARCOM,aSPARCOM,aSPARCOM,aS PARCOM,aS"oPARCOM	A#"$; ;	#A	%,aSPARCOM,aKPARCOM	@H,aSPARCOM$	"&		,aSPARCOM: :	A,aSPARCOM40	&A
5	%?1	%B58	A,aSPARCOM	",aS$	PARCOM9 9-,aKPARCOM	A		,aSPARCOM,aKPARCOM	B'L	whitespace needed arou; ;	nd pipe connector.Uac&C@V	A(T,aKPARCOM	A		,aSPARCOM,aKPARCOM9 9	B'qu,aKPARCOM	C		,aSPARCOM	whitespace needed around redirec9 9tor.ac&C@		(p},aKPARCOM	A!%		,aSPARCOM&	")6 6	token too long. -ac,a
@PARCOMA@"	$)?	"A
>,akPARCOM	@		; ;,agPARCOM	@ac&C@.		( H,akPARCOM	@",awPARCOM,aS(PARCOM-: :A	missing quote.Z,akPARCOM	@"Aac&C@[		(Pg,aKPARCOM	%ac: :,a
@PARCOMA@",akPARCOM	@@ #!	$A
"	%H	
*L +	: :6+" ""!$r	$6 6	%+I%*	token too long. +			,agPARCOM	@ac&C@,		(n76 6,akPARCOM	@",awPARCOM,aS(PARCOM,aKPARCOM	%ac,a
@PARCOMA@"; ;,akPARCOM	@@ #	@ ,awPARCOM,aS$	PARCOM,aKPARCOM	A		,aSPARCOM9 9_,aKPARCOM	+	non-alphanumeric label. gac*,a
@$	PARCOM,a
@"oPARCOMA@9 9ac,,a
@"oPARCOM	Aac&C@h		(?	non-numeric output port.
	'@H,ac.: :,a
@$	PARCOM,a
@"oPARCOMA@,ac0,a
@"oPARCOM,aS PARCOM	Cac&C@		(9 9*	'B-.	(.@6	t.,aK(PARCOM	A
	%           A=7@	destination is neither l9 9abel nor node number. B	.-,ac2,a
@$	PARCOM,a
@"oPARCOM	A@-A@,ac0,a
@"oPARCOM9 9,aSPARCOM	Cac,,a
@"oPARCOM	Aoac4,a
@"oPARCOMa@	Auac&C@C< <		(1}	non-numeric destination input port. 	t.,aK(PARCOM	                                                                   ,aG$	PARCOMQ; ;ac0Q	@,aSPARCOM	C	ac&C@		(*	@ ,aSPARCOM2	'@H,ac.9 9,a
@$	PARCOM,a
@"oPARCOMA@,ac0,a
@"oPARCOM,aS PARCOM	%K		,ag$	PARCOM9 9QN,a_6
PARCOM	CPac0,a
@8PARCOM	%\TJ\	('@t',aK(PARCOM	9 9	C,aK"oPARCOM	A		,aSPARCOM	('mh	pathname not allowed on CMDSRC r9 9edirector.oac&C@p		(1nd		,aSPARCOM	non-numeric input port. 	t'; ;,aG(PARCOM	Qac0Q	@,aSPARCOM	C6ac&C@         	(*[	t',aK$	PARCOM9 9	C	('@	,aSPARCOM8		,aSPARCOM>	missing pathname in redirector. B9 9ac*,a
@$	PARCOM,a
@"oPARCOMA@',aK"oPARCOM	Aac&C@C		(1^2f6 6	+@H/L

gnopq77rf,aK:CICOM 	9ac<x		e		: :,aSPARCOM,aK:CICOM 	9ac<		(Lq!Qo@	222f: :!}!!!!!!!!!	!
!!6 6!	e!	!
! !,!        .!;!>!|!,$PARCOM!.9 9$PARCOM!4$PARCOM!6$PARCOM!2$PARCOM!0$PARCOM!>$PARCOM!:$	PARCOM!L$
PARCOM!N9 9$PARCOM!8$oPARCOM!*$PARCOM!P$CICOM !F#CKNUM !B#CKALF !J#EQUAL !(#LSGETC!<#SYNERR !@#SDROP !D#STAKE !H#SUBSTR!R#SYMBO0
 
"%200&$ CKNUM 0 0	A"	acQ	@A@"	#"@HADQK	A
		#	#	!}!#CTOI
 
"%($0&V$ CKALF : :	QK	A
	%			%	@
QK	%	%	@< <	@ "			#	(#@	#@HADQK	A
	%**	%)	@+	#@HADQK; ;	%77	%6	@8	#@HADQK	%DD	%C	@E	#@HADQK3 3	%P	@ "	%	A"	!!0!9!A!Z!_!a!z
 
"%($0&
" SYNERR6 6UPARCOM	ac,a
@PARCOM,a
@PARCOMQ	@		!$PARCOM!$PARCOM!#ERRMSG
 
"%&"0&
" SEMERR 	acA@A@Q	@		!
!#ERRMSG
 
"%&"0&:$ SYMBO09 9UPARCOM"0NETTERM_SYMCOMMA_SYMPIPE_SYMLABEL_SYMAR9 97G_SYMCMDSRC_SYMFROM_SYMTOWARD_SYM	APPEND_SYMER9 9R_SYMUNKNOWN"#.7CMYen	A"	("@	"a': :	t"aK	AD,aKPARCOMa_	C		                                                                                   ym_type = *s, Sym_text = '*s'*n. 	t"aK: :	ADaGQacA@C@Q	@,a
@	PARCOM		!:!$PARCOM!$	PARCOM!#PRINT 
 
"%&$0&