?"$ MAKEI0: :FPORTCM	too many input ports. Qw,aKPORTCM	"CacC@		#	Qw: :,akPORTCM	@QK	9@"9@ADQK,aSPORTCMQK,aSPORTCMQK	,aSPORTCM: :QK,aSPORTCM	A,aSPORTCM		#	!}!~?!?!?!$PORTCM!( ($PORTCM!$PORTCM!$PORTCM!$PORTCM! $PORTCM!#SYNERR
 
"%4$0&?"$ MAKEO0: :FPORTCM	too many output ports.Qw,aK	PORTCM	"CacC@		#	Qw: :,ak	PORTCM	@QK	9@"9@ADQK,aSPORTCMQK,aSPORTCMQK	,aSPORTCM: :QK,aSPORTCM	A,aSPORTCM		#	!}!~?!?!?!$	PORTCM!( ($PORTCM!$PORTCM!$PORTCM!$PORTCM! $PORTCM!#SYNERR
 
"%4$0&$ INITP05 5FPORTCM	A"At",aSPORTCM,aS	PORTCM	A"%		!
!$PORTCM! $	PORTCM
 
"%$$0&_&$ CLRPO09 9FPORTCM	A"A#	(#@	#t",agPORTCM	"9@#9@AD,aKPORTCM	C: :,aGPORTCMQacQ	@A@	At",aSPORTCM	#	(#@)	#t",ag	PORTCM< <0	"9@#9@AD,aKPORTCM	%>	%A=*@	"9@#9@AD,aGPORTCMQ9 9acQ	@A@*1	At",aS	PORTCM	A"%^		!!_!!9 9!	!
!'!$PORTCM! $	PORTCM!$PORTCM!$PORTCM!"$PORTCM!$$PORTCM! #LSFREE
 
"%&$0&2$ ASSII09 9UPARCOM	A"	("@	",agPARCOM	@acA@"	C		QS	#		9 9	A"	("@	",agPARCOM	@acA@"	C		QS	#			QS! !	#	!}!~2!$PARCOM!#ASSIH0!#ASSIG0
 
"%($0&9.& ASSIH0: :dEXECCM/CICOM UPARCOMFPORTCM		acQ@A@	A"	("@		"Qw,ag	PORTCM9 9QK	9@"9@AD,aGPORTCMQQK	A

acQ	@Q@A@	C		#: :		-
	A"	("@4	"Qw,ag	PORTCM<QK	9@"9@AD,aKPORTCM9 9	AacQ@A@	$%UR	#	TQK	9@"9@AD$,aSPORTCMI	pipe9 9 destination not found. bQK	9@"9@AD,aKPORTCM	C5,aKPARCOM,agPORTCM9 9
ac C@c		#	QK	9@"9@AD,aKPORTCM	%,aG"PORTCM	Qac$A@%: :A@Q	@Q	@A@"	C		#	(	%9@Q[	ADA,aS&uEXECCM5=		#	!}7 7!~9!9!9!
9!$	PORTCM! $PORTCM!$PORTCM!$$PORTCM!(2 2$PORTCM!"$PARCOM!,$uEXECCM!#RESER0!*#MAKEI0!#SELEC0!#MAKEP0!&#SEMERR
 
"%0&0&G&( ASSIG09 9FPORTCM		acQ@A@	A"	("@		"Qw,agPORTCMQK	9@"9@: :	AD,aGPORTCMQQK	A

acQ	@Q@A@	C		#	-
	A"9 9	("@4	"Qw,agPORTCM<QK	9@"9@AD,aKPORTCM	C5,aKPORTCM8 8	A5,aKPORTCMQg55acQ@A@	$C		#	^QK	9@"9@AD$: :,aSPORTCM,aKPORTCM	%,aKPORTCM		&%9@&9@AD$,aS PORTCM5=	A"	(": :	@	"Qw,agPORTCMQK	9@"9@AD,aKPORTCM	AacQ@A@	$9 9	%!	#	 QK	9@"9@AD$,aSPORTCM,aKPORTCM	C,aKPORTCM: :	%,aKPORTCM		&%9@&9@AD$,aS PORTCM2			#	!}!~G!G!; ;G!$PORTCM!$PORTCM!$PORTCM!$PORTCM!"$PORTCM!$$PORTCM!#RESER0! #SELEC0 !#MAKEP0
 
"%2(0&$ MAKEP0 	A"@HAD"QS	A"	Qg		
 
"%*$0&D$ RESER09 9	
illegal port number.QKQgacC@		"         port referenced more tha: :n once. QK	@HADQK	AacC@		"1QK	@HAD@ QS		"8	" 		!}!~D!#SEMERR
 
"%.$0&+$ SELEC09 9	A"@HADQK	A
	#@ QS	#		A"	Qg	too many ports referenced. acC@		#!}+!#SEMERR
 
"%*$0&YF, SETUQ0: :fHSWT$CM/CICOM FPORTCM		"A#t#,aK?PORTCM,aS
SWT$CM	A#%	A#	(#7 7	@	#Qw,agPORTCMQK	9@#9@AD,aKPORTCM	$,awCICOM : :,aK
CICOM 	%	: can't open. .QK	9@#9@AD,aGPORTCMQjacQ	@jQ@: :A@ac Q@A@	%C-ac"Q@A@ac$C@/	"	QK	9@#9@AD,aK&PORTCM: :	&,aKPORTCM	'9@&9@AD,aK(PORTCM	%ac*A@%S'	$@H(L
`(.9 9{QK	9@#9@AD%,aS,PORTCM,aK.PORTCM	C?@H&%t&,aS
SWT$CM	A#9 9	(#@	#Qw,ag0	PORTCM%QK	9@#9@AD,aK2PORTCM	)	: can't crea9 9te. 3QK	9@#9@AD,aG4PORTCMQjacQ	@jQ@A@ac6Q@A@	%C9 9ac"Q@A@ac$C@4^	: can't open. eQK	9@#9@AD,aG4PORTCMQjac9 9Q	@jQ@A@ac Q@A@	%Cac"Q@A@ac$C@f^
ac8A@%Y	9 9can't open pipe temporary.ac:A@	%C
ac$C@^2	)@H*L<=9 9>3e?0QK	9@#9@AD%,aS(PORTCM,aK<PORTCM	C?&%t&,aS
SWT$CM&8 8		"^!}!~Y!!!Y!!Y!fY!$PORTCM!89 9$	PORTCM!$PORTCM!6$PORTCM!$$PORTCM!.$PORTCM!4$PORTCM!:$PORTCM!D$PORTCM!<: :$PORTCM!0$PORTCM!$?PORTCM! $CICOM !"$
CICOM !$
SWT$CM!(#OPEN!>#CREATE!B#MKTEMP !&#LSEXTR!*#PUTLIN!,#SEMERR!2#REWIND!@#WIND
 
"%,0&(( CLEAN0< <fHSWT$CMFPORTCM	A"	("@	"Qw,agPORTCMQK	9@"9@AD,aKPORTCM: :	#QK	9@"9@AD,aGPORTCMQacQ	@QK	9@"9@AD,aGPORTCMQ6 6acQ	@	#@H$L
*ABC	A"	("@H	"Qw; ;,ag	PORTCMPQK	9@"9@AD,aKPORTCM	%QK	9@"9@AD,aGPORTCMQ9 9acQ	@I]	%&L^^IQ	A"t",aK ?PORTCM,aS"
SWT$CM	A"%x8 8x		!!!!!$PORTCM!$	PORTCM!$PORTCM!$PORTCM! ' '$PORTCM!"$PORTCM!$$?PORTCM!&$
SWT$CM!#CLOSE !#RMTEMP
 
"%.(0&02* DUMPP0; ;fHSWT$CMFPORTCM	#STDIN*i   . command source*n. pipe from node *i port *i*n.defaulted*n.	A"ac9 9A@C@A@"A7",aK	SWT$CM	@HCacA@A@5A7",aG	SWT$CMQ8 8acA@A@Q	@<	A#	(#@M	#Qw,agPORTCMUQK	9@#9@AD9 9,aKPORTCM	"CN,aKPORTCM	$acA@C@acA@A@QK	9@#9@7 7	AD,aGPORTCMQacQ	@A@acA@A@nQK	9@#9@AD,aKPORTCM	%; ;,aK PORTCM	&%9@&9@AD,aG"PORTCMQacA@C@A@%Q	@g	$@H'L9 98ho91V	acA@C@<	A"%I&&	STDOUT*i  . append to . pipe9 9                                to node *i port *i*n.defaulted*n.I	A"acA@C@JA@"A7",aK$
SWT$CM	@HCac; ;A@G@;yA7",aG$
SWT$CMQacA@G@HQ	@	A#	(#@         #Qw9 9,ag&	PORTCMQK	9@#9@AD,aK"PORTCM	"C,aK(PORTCM	(acA@; ;A@QK	9@#9@AD,aG*PORTCM#QacQ	@A@acA@A@acA@C@PQK: :	9@#9@AD,aG*PORTCMQacQ	@A@acA@A@JQK	9@#9@AD,aG*PORTCM: :Q,aG,PORTCMQacA@C@VQ	@Q	@i+	(@H)Lj,K9 9	acA@C@c         A"%jj		!!!!
6 6*3i  .  TTY  .  tfrom .  1toward .!$PORTCM!*$	PORTCM!$PORTCM!9 9$PORTCM!$PORTCM!$$PORTCM!,$PORTCM!&$PORTCM!.$PORTCM!0$PORTCM!$	SWT$CM!( $
SWT$CM!#PRINT ! #LSPUTF!"#PUTCH 
 
"%2*0&