52( SVSAVE9 9ASVCOM 	acA@acQ	@A@A@"A@	#CacA@		$		Saving var8 8iables in *s*n. QK	A
acA@C@Q	@+	A%	(%@6	%%	@C;AD: :,aKaSVCOM 	&	t&,aK SVCOM 	&B	&A
7	t&,aK!SVCOM 	AD,aG SVCOM Q7 7acQ	@A@#acA@A@#	t&,aK "SVCOM 	AD,aG SVCOM Qac"Q	@A@'	t'; ;,aG SVCOM QacQ	@A@#acA@A@#QK	A
	t&,aK!SVCOM 	AD,aG SVCOM : :'QacQ	@A@acA@A@acQ	@A@acA@A@ac$A@'C;ac&9 9A@#ac(A@#acA@		$	!}!~5!!!5!5!5: :!
5!$aSVCOM ! $ SVCOM !"$!SVCOM !($"SVCOM !#OPEN!#BREAK$!#PRINT !$#PUTLIN !&#PUTCH !*#SVCTMN!,#SVFREE!.#TRUNC !0#CLOSE 
 
"%2(0&$(( SVREST9 9ASVCOM 	acA@acQ	@A@A@"A@	#CacA@		$		Restoring : :
variables from *s*n.QK	A
acA@C@Q	@-	acA@%A@#	&BC?9 9	&%AD@ ,aSSVCOM 	acA@'A@#	&BCacA@#acA@		$	P	*s = *s*n.; ;\	&'AD@ ,aSSVCOM QK	A
	t%,aG SVCOM Q	t',aG SVCOM 	QacA@; ;	C@]Q	@Q	@k	t%,aG SVCOM Q	t',aG SVCOM QacQ	@Q	@ac A@'ac 6 6A@%6@acA@#acA@		$	!}!~$!!$!$!6 6$SVCOM !"$ SVCOM !#SVGETL!#OPEN!#BREAK$!#PRINT ! #CLOSE !$#SVMAKE!&#SVFREE
 
"%2(0& & SVSCAN: :ASVCOM 	QK	A	AQS	@ u	QSacQ	@		A
	@ uQS           QK		u: :QS	@ QS	AQg%#QS$		Qg*		"	+	uQK	A9 9	@ QS3,aKSVCOM 	uQg	@@HQS<	uQK	A	@ QSEQK9 9	C;,a[SVCOM 	uQ_	AD,aK`SVCOM 	#A$	($@W	$uQg	@#A
^	t#; ;,aK SVCOM 	#Xb	#A
	uQk	@t#,aK!SVCOM 	AD,aG SVCOM 	QacQ	@: :Q	@Q	@	"	jQk	@		Qg	@ uQSQK	C;,a[SVCOM 	uQ_5 5	AD,aK`SVCOM 	#h			"	!!!!!$SVCOM ! $`SVCOM !$ SVCOM !$!SVCOM !#CTOC!#MISSIN
 
"%4&0&b.* SVMAKE; ;ASVCOM 	acQ	@	B"	acQ	@A@#,agSVCOM     acA@acA@	#ac: :A@"	$acQ	@A@%acQ	@	&$t#,aS!SVCOM 	%,aS "SVCOM 	&C;,a[SVCOM 	': :	t',aK"`SVCOM 	t#,aS$ SVCOM 	#t',aS"`SVCOM 	t$,aG$ SVCOM Qac&Q	@Q	@A@": :	t%,aG$ SVCOM Qac(Q	@Q	@,a
@SVCOM acA@,aKSVCOM 	(	!!: :b!b!$SVCOM !&$`SVCOM !($ SVCOM !"$!SVCOM !$$"SVCOM !#LENGTH!#SVFIND$ $! #SVHASH!#SVMNTC!#SVALLO!#BREAK$!*#CTOC!,#SVFIX 
 
"%2*0&="& SVPUT : :ASVCOM 		acQ	@A@"	#BCacQ	@Q	@	#
acA@	t",aG"SVCOM : :QacQ	@acQ	@A@$	$QS	t$,aG SVCOM QacQ	@Q	@A@#acA@9 9	#%	!!=!$ SVCOM !$"SVCOM !#SVMNTC!#SVFIND!#SVMAKE!#BREAK$! #SVFREE! #SVFIX 
 
"%.&0&]$( SVDEL 9 9fHSWT$CMASVCOM "+_eof_erase_escape_kill_kill_resp_newli: :ne_retype_prt_dest_prt_form"Z
	&/7A	@ "acd5 5Q	@	#C;,a[fSVCOM 	AD,aKh`SVCOM 	$	t$,aKj SVCOM 	$	$A
	t$5 5,aKl!SVCOM 	AD,aGj SVCOM QacnQ	@Q	@	@HCacpA@	"A	#C;9 9,a[fSVCOM 	%t$,aKj SVCOM 	t%,aSh`SVCOM .	t$,aKj SVCOM 	t",aSj SVCOM :; ;	t$,aGl!SVCOM 	QacrQ	@	t$,aGt"SVCOM QacrQ	@acrA@$acva@Za@A@6 6Q	@	&%e	@H',awfSVCOM ,aKx                                SVCOM ,aSzSWT$CM,awfSVCOM 7 7,aK|                                                                SVCOM ,aS~SWT$CMn,awfSVCOM ,aK                                                                                                SVCOM ,aSSWT$CMu,awfSVCOM : :,aKSVCOM ,aSSWT$CM|,aKfSVCOM 	9@AD,aG@SVCOM 	Qac
Q	@,a
@                                                                                   WT$CM: :A@,awfSVCOM ,aK SVCOM ,aSSWT$CM,awfSVCOM ,aK@SVCOM ,aSSWT$CM: :,aKfSVCOM 	9@AD,aGpSVCOM 	Qac
Q	@,a
@LSWT$CMA@#,aKfSVCOM 	9: :	@AD,aGSVCOM 	Qac
Q	@,a
@LSWT$CMA@5g	'L
hov}: :$6GdacpA@'	$"X		!!!]!	]!     ]!8 8!]!l$SVCOM !n$`SVCOM !p$ SVCOM !r$!SVCOM !z$"SVCOM !~$                                SVCOM !$                                                                SVCOM !9 9$                                                                                                SVCOM !
$SVCOM !$ SVCOM !$@SVCOM !$@SVCOM !$pSVCOM ! $SVCOM !$SWT$CM!9 9$SWT$CM!$SWT$CM!$SWT$CM!$SWT$CM!$SWT$CM!$                                                                                   WT$CM!$LSWT$CM!"$LSWT$CM!t" "#EQUAL !j#SVHASH!|#STRLSR!v#BREAK$!x#SVFREE!#CTOC
 
"%.(0& $ SVGET ; ;ASVCOM 		acQ	@A@"	BC		#		t",aK"SVCOM 	AD,aG SVCOM Q
ac1 1	Q	@
Q	@Q	@	#	#	! !$ SVCOM !$"SVCOM !#CTOC!#SVFIND
 
"%0$0&<& SVFIND9 9ASVCOM 	acQ	@	",aKSVCOM 	#	#@H#		#A	"C;#AD,aK`SVCOM 	$9 9	t$,aK SVCOM 	$	$A

	t$,aK!SVCOM 	AD,aG SVCOM QacQ	@Q	@: :	@HC	$QS	#%		@ QS		%	!<!$SVCOM !$`SVCOM !$ SVCOM ! $!SVCOM !#EQUAL !#SVHASH
 
"%.&0&'$ SVHASH9 9	QK	%	%	@QK	%        	%	@
QK7 7	M=@B"	uQK	M=@B"	"	!'!!A!Z!a!z
 
"%($0&
J& SVPOP : :fHSWT$CMASVCOM acA@	A"C;,a[SVCOM 	AD,aK`SVCOM 	#	$#	#A
	t#9 9,aK SVCOM 	$,aG!SVCOM 	QacQ	@	t#,aG"SVCOM QacQ	@acA@#6 6	A"%3,awSVCOM ,aK                                SVCOM ,aS SWT$CM,aK"                                                                SVCOM ,aS$SWT$CM9 9,aK&                                                                                                SVCOM ,aS(SWT$CM,aK*SVCOM ,aS,SWT$CM,aK. SVCOM ,aS0SWT$CM,aK2@SVCOM ; ;,aS4SWT$CM,aKSVCOM 	9@AD,aG6@SVCOM 	Qac8Q	@,a
@:                                                                                   WT$CMA@,aKSVCOM ; ;	9@AD,aG<pSVCOM 	Qac8Q	@,a
@>LSWT$CMA@,aKSVCOM 	9@AD,aG@SVCOM Q9 9ac8Q	@,a
@BLSWT$CMA@,aKSVCOM 	@H,aSSVCOM acA@		!!
7 7!	
!
!     
!!
!$SVCOM !$`SVCOM !$ SVCOM !$!SVCOM !"9 9$"SVCOM !$$                                SVCOM !($                                                                SVCOM !,$                                                                                                SVCOM !0$SVCOM !4$ SVCOM !8$@SVCOM !<$@SVCOM !B9 9$pSVCOM !F$SVCOM !*$SWT$CM!2$SWT$CM!6$SWT$CM!&$SWT$CM!.$SWT$CM!:$SWT$CM!@% %$                                                                                   WT$CM!D$LSWT$CM!H$LSWT$CM!#BREAK$! #SVFREE!>#CTOC
 
"%*&0&lD& SVPUSH9 9fHSWT$CMASVCOM acA@,akSVCOM 	@,aKSVCOM 	"A$@ t",aS`SVCOM 	""A$: :	%,aKSWT$CM,awSVCOM ,aS                                SVCOM ,aKSWT$CM,aS                                                                SVCOM ,aKSWT$CM9 9,aS                                                                                                 SVCOM ,aK"SWT$CM,aS$SVCOM ,aK&SWT$CM,aS( SVCOM ,aK*SWT$CM,aS,@SVCOM 7 7,aKSVCOM 	9@AD,aG.@SVCOM Qac0,a
@2                                                                                   WT$CMQ	@A@,aKSVCOM 	9@AD: :,aG4pSVCOM Qac0,a
@6LSWT$CMQ	@A@,aKSVCOM 	9@AD,aG8SVCOM Qac0: :,a
@:LSWT$CMQ	@A@acA@		!!l!	l!l!     l! !8 8!l!$SVCOM !$`SVCOM ! $                                SVCOM !$$                                                                SVCOM !($                                                                                                SVCOM !,$SVCOM !0$ SVCOM !49 9$@SVCOM !6$@SVCOM !<$pSVCOM !@$SVCOM !"$SWT$CM!*$SWT$CM!.$SWT$CM!$SWT$CM!&- -$SWT$CM!2$SWT$CM!:$                                                                                   WT$CM!>$LSWT$CM!B$LSWT$CM!#BREAK$!8#CTOC
 
"%(&0&$ SVINIT5 5ASVCOM 	@ ,aSSVCOM 		"@ t",aS SVCOM 		,aS!SVCOM 	"	t",aS SVCOM 	@ 6 6,aS!SVCOM 		,aS!SVCOM ac		!!!}!!$SVCOM ! $ SVCOM !$!SVCOM !#SVPUSH
 
"%$$0&"& SVDUMP9 9ASVCOM 	A"	("@		Scope level *i:*n.	",agSVCOM 	@	acQ	@C@9 9A@"	A#	(#@	
   Hash list *i:*n. "	#%	@acQ	@C@#A@#	#C;"AD6 6,aK`SVCOM 	$	t$,aK SVCOM 	$@	*6i: *s (*i) = *s (*i)*n. E	$A
 	t$: :,aG"SVCOM QQK	AD,aG SVCOM QacQ	@A@%	t$,aG!SVCOM QQK	AD9 9,aG SVCOM Q	t%,aG SVCOM !Q
acQ	@C@FA@$Q	@Q	@Q	@
Q	@acA@%9 9A		!!$SVCOM !$`SVCOM !$ SVCOM !$!SVCOM !$"SVCOM !#PRINT ! #SVCTMN! #SVFREE
 
"%2&0&J"( SVALLO9 9ASVCOM "NO_SVMEM	QK	@D"	#t#,aK!SVCOM 	$AacA@aca@A@9 9A@G@A@A@	"t$,ag SVCOM 	@#	$#%	t$,aK SVCOM 	"9 9	%%22,aS SVCOM 	$&"t&,aS SVCOM 1	t$,aK!SVCOM 	t#,aS!SVCOM : :	$&:	&@D'	!G!G!G! $ SVCOM !$!SVCOM !#BREAK$! #SIGNL$
 
"%,(0&r( SVFREE9 9ASVCOM 	QK	@H"t",aK SVCOM 	#	$t$,aK!SVCOM 	%A
	$"	@	%; ;	$	in svfree: attempt to free unallocated block. 	$t$,a[ SVCOM 	"CacC@: :		6	%A&#"%CBA	&	A	#t%,a[ SVCOM 	#,aK!SVCOM 	t",aS!SVCOM F; ;	%t",aS!SVCOM Q	$t$,a[ SVCOM 	"C	#,a[ SVCOM ,aS SVCOM 	t",aK!SVCOM 9 9	t$,aS!SVCOM \	"t$,aS!SVCOM 	#t",aS SVCOM h		!r!$ SVCOM ! $!SVCOM !#REMARK
 
"%,(0&c 0 SVMNTC; ;ASVCOM 	acQ	@	B"	acA@"QS	A#@ $	(#@         #@HADQK	A
	%< <	A&	A'	%(L
 )*+	$Q[	"#@HADQK	t",aS SVCOM : :	($@	$Q[	AD@ ,aS SVCOM 	$)		t#QK	A
	(#@J	#@HADQK	*: :	$Q[	AD	,aS SVCOM 	$Q[	AD	,aS SVCOM [S	*+LT: :
jklm\n	$Q[	"#@HADQK	t",aS SVCOM c	($"	A,	(,: :	@	,#@H"t"QK	%	%    	A
	,%	@QK	t,QS	@ 9 9	t,QS	,#@HADQK	%*	$Q[	"#@HADQK	t",aS SVCOM 	($): :	A-acQ@A@-A@	.C	$Q[	"#@HADQK	t",aS SVCOM 	($TF9 9	$Q[	AD.,aS SVCOM 	($@,##U!}c!c!	!
!;!<$ $!>!mc!$ SVCOM !#SVALLO!#MNTOC !#LENGTH
 
"%>00&"( SVCTMN; ;ASVCOM 	A"#	("@	"@HADQK	A
	%	%    	##; ;	(#@	acA@#QS	A"@ #	("@$##'	"@HAD	QGQ
QK
	A
ac5 5Q	@
Q@	$%BQK
	%GAF	"@HADQK	C	#Q[	AD	7 7,aS SVCOM 	(#XO	"@HADQK	C	A$aY	#Q[	%"@HADQK	t%: :,aS SVCOM (G	#Q[	%	t%,aS SVCOM ,aG!SVCOM Q
	$B&	acQ@Q	@
: :A@&	$%AD	,aS!SVCOM 	#@D#(7	#Q[	AD@ ,aS SVCOM 	#'	!!9 9!! !<!>!@!!$ SVCOM !$!SVCOM !#SVALLO!#CTOMN !  #CTOC
 
"%4(0&( SVFIX 9 9fHSWT$CMASVCOM "+_eof_erase_escape_kill_kill_resp_newli; ;ne_retype_prt_dest_prt_form"Z
	&/7A	acda@Z< <	a@A@Q	@	"BC			"@H#QK,aSfSWT$CMQK	"QK	t",aSh                                SVCOM 7 7	A",agjSVCOM 'QK,aSlSWT$CMQK	"QK	t",aSn                                                                SVCOM 	A"< <,agjSVCOM ;..'QK,aSpSWT$CMQK	"QK	t",aSr                                                                                                SVCOM 	A",agjSVCOM 9 9OBB;QK,aStSWT$CMQK	"QK	t",aSvSVCOM 	A",agjSVCOM cV; ;
VOacxQ	@,a
@z                                                                                   WT$CMA@QK	9@$QK	"t$,aG|@SVCOM Q
acxQ	@Q	@
; ;A@	$$A",agjSVCOM sscQK,aS~SWT$CMQK	"QK	t",aS SVCOM 7 7	A",agjSVCOM QK,aSSWT$CMQK	"QK	t",aS@SVCOM 	A": :,agjSVCOM 3&&acxQ	@,a
@LSWT$CMA@QK	9@&QK	"t&,aGpSVCOM : :Q
acxQ	@Q	@
A@	A",agjSVCOM XCC3acxQ	@,a
@
LSWT$CMA@QK: :	9@&QK	"t&,aGSVCOM Q
acxQ	@Q	@
A@	A",agjSVCOM }hhX7 7	#L
(<Pd 4Y}		!!	!     !!!n9 9$SVCOM !l$                                SVCOM !r$                                                                SVCOM !v$                                                                                                SVCOM !z$SVCOM !$ SVCOM !$@SVCOM !$@SVCOM !9 9$pSVCOM !$SVCOM !p$SWT$CM!x$SWT$CM!$SWT$CM!j$SWT$CM!t$SWT$CM!$SWT$CM!~ $                                                                                   WT$CM!
$LSWT$CM!$LSWT$CM!h#STRLSR!|#CTOC
 
"%4(0&Y( SVGETL9 9ASVCOM 	A"	acA@"QS	@ Qw,aS SVCOM 	acQ@Q	@	#BC		$	: :	#"%acA@%	&Qw,aG SVCOM Ql	t&,aG SVCOM QnacQ	@lQ	@nA@"	"9 9	&AD,aGSVCOM QnacQ@Q	@nA@#acQ	@	&QS	#""t#QK	C	"6 6	@H$	!Y!
Y!$SVCOM !$ SVCOM !#GETLIN!#SVALLO!#CTOC!#SVFREE
 
"%(0&$ SVLEVL ASVCOM 	,aKSVCOM QS	"	!$SVCOM 
 
"%($0&