define (COLS_BETWEEN_CHARS,1)
define (COLS_PER_CHAR,5)
define (MAXLINE,133)
define (MAX_OUT,1024)   # >= MAXLINE*(COLS_PER_CHAR+COLS_BETWEEN_CHARS)
define (ROWS_BETWEEN_LINES,3)
define (ROWS_PER_CHAR,9)
define (ROWS_PER_WORD,3)
define (WORDS_PER_CHAR,3)
define (INTERVAL,1)     # update interval (in seconds)
define (MASK_DECL,"wallclock_masks.r.i")
define (START_ROW,8)

include ARGUMENT_DEFS
