}Z:9 9SDP$COM"c<ri>jl<ri>n<ign>sx"$Usage: dprint {-c <copi9 9#es>|-j|-l <length>|-s|-x} [<file>]"^QUIT$ "b*s: ca5 5n't open*n"t*s: can't open*n"QUIT$ ac
a@: :,a
@DP$COM	Caca@$,aKDP$COM	%	A,aS'DP$COM                                            aKDP$COM9 9	%		,aS0DP$COMacA@,a
@DP$COMaGQja^QlQjQoQl; ;	asac A@	4A
	5ac A@5	6ac"A@A@A@	A,aS$DP$COM,aS&DP$COM; ;	@ ,aS(DP$COM,aS*DP$COM	@ ,aS,DP$COMac.A@,ak(DP$COM	@,aK0"DP$COM	A9 9ac.A@,ak(DP$COM	@,aK2DP$COM	A
,aK,DP$COM	A
ac4A@6	%	v; ;oun	@ ,aS(DP$COM	@ ,aS,DP$COMac.A@
ac4A@6	%	j_	AQf5 5	ac6Q@Q@f	7ac8Q@A@,aS:DP$COM	%	A8	(8@!	8: :,ag'DP$COM	@ac<ac>,a
@:DP$COM"'ac@,a
@:DP$COMacBA@9 9a@bQ@4acBA@a@tQ@=	79L>FN	acDA@acF6 6a@,aK,DP$COM	A
ac4A@6	%	c\b[,aK:DP$COM	%iac@9 9,a
@:DP$COMhac"A@A@A@ac A@4	6acH T!@}!q!v!9 9}!!!!}!}!B!Z}!	!
!!}!8 84}!$DP$COM! $DP$COM!$$DP$COM!B$DP$COM!@$"DP$COM!"$'DP$COM!&$0DP$COM!4< <$DP$COM!6$DP$COM!8$DP$COM!J$DP$COM!:$DP$COM!<$DP$COM!*$DP$COM!0#DUPLX$!F#GFNARG: :!H#OPEN!,#QUITU0!.#MKONU$!#PARSCL!D#T1IN!#ERROR !(#MKLB$F!2#SETDE0!>#T1OU!L#DPRINT$ $!N#REWIND!P#CLOSE !R#PRINT !T#OUTCH !V#RVONU$!X#SWT 
 
"%,:0&I,* DPRINT9 9SDP$COMacQ@A@"A@#A@$	%	$A
acA@	$,a_DP$COM	%8 8,aKDP$COM	#%CacA@acA@,aKDP$COM	@D,aSDP$COM	A,aSDP$COM6 6,aKDP$COM	$$4acA@acA@acA@$,aKDP$COM	,aSDP$COM	$: :,aSDP$COM3	"&	&@H&J	#$&	@@ '&(	(@H(V	t(QK	C	('8 8WW_		$'eacA@acA@,aKDP$COM	'%acA@%,aKDP$COM	9 9,aSDP$COM,aKDP$COM	',aSDP$COM	(&f,aKDP$COM	A	t&	QGQhac6 6Q	@h	t&QK	C,akDP$COMKK	t&QK	% 	%	#: :,aKDP$COM	@H,aSDP$COM"KPacA@acA@acA@
,aKDP$COM6 6	@D,aSDP$COM	@ ,aSDP$COM,aKDP$COM	$#CacA@acA@acA@#9 9,aKDP$COM	,aSDP$COM	#,aSDP$COMB	#&	(&@Y	&$"	@@ '&(9 9	((@d	t(QK	C	('eel		$'racA@acA@	',a[DP$COM; ;	%acA@%,aKDP$COM	,aSDP$COM	',a[DP$COM,aSDP$COM	(&s,aKDP$COM: :	A	t&QGQhacQ	@h	t&QK	C,aKDP$COM	@H,aSDP$COMZ"< <	t&QK	%/	%	2.,akDP$COM	@1Z^acA@-,aKDP$COM9 9	A
	A,agDP$COM
>BacA@C		!I!!
!	!!	9 9!
!!! !
5!6I!($DP$COM! $DP$COM!*$DP$COM!$$DP$COM!& $DP$COM!#INBUF !#OUTCH !"#T1OU
 
"%*0&& INBUF ; ;SDP$COM	acQ	@,a
@DP$COM	"%		#		"@HADQK	%	"%; ;	t"QGQacQ	@,a
@DP$COM	$BC(	$"")	"@HQSQK: :	@HQS2QK	A	@HADQK	%C3;C	AQSQk	@GQKQg: :	@@HADQK	%XHOX	@ QS		A%	(%@^	%Qg	@@HADQK	9 9	CQK		@HQS	_l	%@HADQK	%{	%~zQk		@}_d	"#	2 2!!
!!!
! !!$DP$COM!#GETLIN
 
"%4&0&mN& OUTCH 9 9SDP$COM!"c  ("B

|  "$o<

",9 9/


-    -\"@c
-"Fn  


|"T) /9 9"Z|  -


  `"lc    o"x|'  `



: :

'`  "\


'
'  "$/    \"09 9u


|  ">\-    -


/"R	-  ,
"\9 9	(   /"f	u   u"pO

-  -"|
o 
```9 9 
"
o|"o[]"/-

  ''  "$[]-
  ': :

`  "6-


"
""B[]    []-


"V9 9o

|  "b	o
  ~"l>

--


"zt
  ~9 9~ "O-"
O="c 
,c
` 
"c 
,9 9<

		,ag*DP$COM	@ac,A@,aK.DP$COM	A
ac0A@"	%6 6	A,aS.DP$COMac2A@	@ ,aS*DP$COMac,A@QK	C9 9,ak*DP$COM	@ac2A@,aK4DP$COM	A
,aK.DP$COM	A
ac0A@"	%?6 68>7	@ ,aS*DP$COM	@ ,aS.DP$COMac2A@ac0A@"	%QJP3	A: :,aS6DP$COM	@ (QK	C,ak6DP$COM	@,aK80DP$COM,ag6DP$COMd9 9,ak*DP$COM	@ac2A@,aK4DP$COM	A
,aK.DP$COM	A
ac0A@"	%|6 6u{t	@ ,aS*DP$COM	@ ,aS.DP$COMac2A@ac0A@"	%p	A: :,aS6DP$COM	@ e	A\		A
	@ ac2A@	ac2A@
ac2,a
@6DP$COM9 9,aK*DP$COM	,aS*DP$COMQK	#ac:a@ac:a@6ac:a@$;ac:: :8a@,@ac:a@@Eac:a@FJac:a@TOac:a@ZTac:a@lYac:a@x^ac:: :8a@cac:a@$hac:a@0mac:a@>rac:a@Rwac:a@\|ac:a@fac:: :8a@pac:a@|ac:a@
ac:a@ac:a@ac:a@$ac:a@6$ac:: :8a@B)ac:a@V.ac:a@b3ac:a@l8ac:a@z=ac:a@Bac:a@
Gac:5 5a@Lac:a@Qac2A@	,aK<DP$COM	A
ac2A@^ac2A@c: :,aK*DP$COM	@D,aS*DP$COMVac2A@	,aK<DP$COM	A
ac2A@uac2A@: :z,aK*DP$COM	@D,aS*DP$COMm1	#$LWn	#$LU_: :8%*Z !"#$%&'(A)+UH,/0i: :81345798:;< >@ABsCE27F<FIPC7 7,LOPdQKSU/4>n}MRWabxcac2Q	@9 9,ak*DP$COM	@W		!!m!m!	m!*!H!!!8 8!
!
!!	m!Dm!Um!D$DP$COM!H$0DP$COM!F$DP$COM!:* *$DP$COM!L$DP$COM!>$DP$COM!@#T1IN!<#BREAK$!B#T1OU!J#PLOTS0
 
"%*&0&!,& PLOTS0: :SDP$COM	acA@acA@acA@,aKDP$COM	@D,aSDP$COM	A"	("@	": :	@HADQK	A
		,agDP$COM	@,aKDP$COM	A
acA@#	%.'&; ;	A,aSDP$COM-acA@	@ ,aSDP$COM!	"@HADQK	$,aKDP$COM	@HC9 9acA@DacA@I,aKDP$COM	@HC
acA@NSacA@Xac: :	A@acA@	,akDP$COM]hacA@	i?	$
%L@j^	$%|O8 8u	"@HADQGQacQ	@n,akDP$COMacA@acA@acA@: :,aKDP$COM	,aSDP$COMacA@		!!!!!
!!	
!: :! !H!!!! !3!4!!$$DP$COM!*$DP$COM!&$DP$COM!( #T1IN! #BREAK$!"#T1OU
 
"%,&0&
" QUITU04 4SDP$COM		acA@ac,a
@DP$COM		!

!$DP$COM!#T1OU!#PL1$NL
 
"%&"0&*" SETDE0; ;"*,-8udelay *i *i *i	ac$Q@
A@a@Q	@Q	@Q	@ac&Q@
A@ 		!}!f!&#ENCODE!(#SYS$$ 
 
"%"0&