.
/S!lH
)J
$LM
c~@@L@J@	@@H@@@A
/	c|@m@l@Hcz@I@H@@3@	c|@
@	@J@JHvJ@DMYMc|@m@l@Hcx@I@H@@3@	c|@
@	@Jcv@K@J@7@4@wvMQHKOC5@ ct@@v@A
5
@HHKMcr@H@@vcp@	@ A$@ %6GHIJK-0@.H%.@DMYM?0@@H6@@DMYMQ0BR0KA&EF8@ADGBHkH@K     HMQHKOC6K8@ADG;HtGBJcn@-@3	J@	@J@Lcv@M@L	@H@4B: c
`s0tI@ 
U$Hcl@@H@7@@@@YH@ @Dcj@@@@@H@A?@.HHKMcr@H@@ch@H'IK"9	Lcr@L@@K@ch@H
sJK=L
Ncr@L@@K@ch@H
VHKk@L
oNcr@L@@K@cf@H
9HMNB	Ncr@N@@M@cf@H
IM4FNcr@N@@M@@ S!cp@	                                                                                   PH > Can't attach to %v. (SPH)%. . Phantom is user %d %$ on %a/%$%a/%$ %a %at %a:%$%a%.IOA$R$SPAWN$c@p@tc	@
	@c	
****  AT$HOMCL$PIXERRPR$EXITTNOUATTNOUA AT$ VTP$CMVVP$CDATP$CTIMP$CCATP$CREVP$CAFTP$CBFR~CR\`p~\vX*&"z/tree; -u id; -p id; -c; -g 32 * id; -v oct; end                                 ~`
~T
)).A@i~t$@AT$                              @vAT$HOM                          8@zCL$PIX                          P@~ERRPR$                          h@EXIT                            @~TF$ERX                           @`F192QFP5                        0@XIOA$                            H@&P$CAFT                          `@*P$CBFR                          x@P$CCAT                          @P$CDAT                          (@P$CMVV                          @@"P$CREV                          X@P$CTIM                          p@\SPAWN$                          @~CSPH                              A@ SWT$CM                          h!8A@SWT$TP                          h!P@TNOU                            h@
TNOUA         @AHHWW~CS~`~TT~T~ijTt0@@<@@ H @-..s