

            bye (1) --- log out from the Subsystem                   03/20/80


            _U_s_a_g_e

                 bye


            _D_e_s_c_r_i_p_t_i_o_n

                 'Bye'  is  a shell program which may be used to log out from
                 the Subsystem.  It contains

                      stop -

                 For details on the action of 'stop', see its documentation.


            _E_x_a_m_p_l_e_s

                 bye


            _S_e_e _A_l_s_o

                 stop (1), Primos logo$$



































            bye (1)                       - 1 -                       bye (1)


