

            copy (1) --- copy standard input to standard output      02/22/82


            _U_s_a_g_e

                 copy


            _D_e_s_c_r_i_p_t_i_o_n

                 'Copy'  is Kernighan and Plauger's copy command from chapter
                 two of _S_o_f_t_w_a_r_e _T_o_o_l_s.  It simply copies its standard  input
                 to its standard output until end-of-file.


            _E_x_a_m_p_l_e_s

                 file1> copy >file2
                 list_file> copy
                 copy >data
                 copy


            _S_e_e _A_l_s_o

                 cat (1), cp (1), print (1), fcopy (2)



































            copy (1)                      - 1 -                      copy (1)


