

            date (1) --- print date                                  03/20/80


            _U_s_a_g_e

                 date


            _D_e_s_c_r_i_p_t_i_o_n

                 'Date'  prints  the  Gregorian  date in the form mm/dd/yy on
                 standard output one.


            _E_x_a_m_p_l_e_s

                 date
                 echo "Run at" [time] "on" [date]


            _S_e_e _A_l_s_o

                 day (1), time (1), date (2)






































            date (1)                      - 1 -                      date (1)


