

            installation (1) --- print Subsystem installation name   02/22/82


            _U_s_a_g_e

                 installation


            _D_e_s_c_r_i_p_t_i_o_n

                 'Installation' merely prints the Subsystem installation name
                 on standard output.

                 The     installation    name    resides    in    the    file
                 "=extra=/installation" and may be changed at the  discretion
                 of the Subsystem manager.


            _E_x_a_m_p_l_e_s

                 echo Run at [installation]


            _F_i_l_e_s

                 =extra=/installation



































            installation (1)              - 1 -              installation (1)


