

            source (1) --- print source for a command or subroutine  07/19/84


          | _U_s_a_g_e

          |      source { <command> | <subroutine> }


            _D_e_s_c_r_i_p_t_i_o_n

          |      The 'source' command writes a copy of the source code of the
          |      named  commands  or  subroutines to standard output, in 'cat
          |      -h' format.


            _E_x_a_m_p_l_e_s

                 source help


            _F_i_l_e_s

          |      =src=/misc/srcloc for locations of all source code files


          | _M_e_s_s_a_g_e_s

          |      "Usage: source ..."  if called with no arguments


          | _B_u_g_s

          |      Not exactly blindingly fast.


            _S_e_e _A_l_s_o

          |      cat (1), locate (1)























            source (1)                    - 1 -                    source (1)


