

            time (1) --- print time-of-day                           03/20/80


            _U_s_a_g_e

                 time


            _D_e_s_c_r_i_p_t_i_o_n

                 'Time'  prints  the  time  of  day in the format hh:mm:ss on
                 standard output one.


            _E_x_a_m_p_l_e_s

                 echo Run at [time]


            _S_e_e _A_l_s_o

                 date (1), day (1), ctime (1), date (2)







































            time (1)                      - 1 -                      time (1)


