

            us (1) --- list users of the Prime                       03/25/82


            _U_s_a_g_e

                 us


            _D_e_s_c_r_i_p_t_i_o_n

                 'Us'  is a shell file that invokes the Primos STATUS command
                 to print a listing of the users currently logged  in,  along
                 with  their  line number and any devices they have assigned.
                 Output is always to the user's terminal.


            _E_x_a_m_p_l_e_s

                 us


            _S_e_e _A_l_s_o

                 who (3)





































            us (1)                        - 1 -                        us (1)


