

            which (1) --- search _search_rule for a command          08/27/84


          | _U_s_a_g_e

          |      which <command>


          | _D_e_s_c_r_i_p_t_i_o_n

          |      'Which' steps along the path indicated in the shell variable
          |      '_search_rule'   to   locate  the  <command>  named  as  its
          |      argument.  It knows  which  commands  are  internal  to  the
          |      shell.


          | _E_x_a_m_p_l_e_s

          |      which cd
          |      which (fmt se)


          | _M_e_s_s_a_g_e_s

          |      "Usage:  which ..."  for improper arguments.


          | _B_u_g_s

          |      Ignores all arguments but the first.


          | _S_e_e _A_l_s_o

          |      sh (1), svget (2)


























            which (1)                     - 1 -                     which (1)


