# build --- rebuild 'se'

   declare _search_rule = "^int,^var,=bin=/&"

   sep se -all    # be absolutely sure that 'se' is compiled
                  # with "-q1"; otherwise the line buffer kluge
                  # ("$" in the common name) will not work!
