p$@ GETCMD6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES"MARGIN"INSERT" CASE"&WHA?9 9",NOCHAR	ac4Q	@	"A	@HADQK	C	("@	A#9 9	"#QK	%	%	$A%	#&ac6,aK8COPT	'< <ac:A@,a
@<CLINESA@ac:A@,a
@>CLINESA@6ac:A@,a
@@CSCRN A@6 6?-	'(L@7PQRSTUVW.X	acBA@A@H	#; ;,agDCOPTcacBA@A@d	@ QS			)	*QK	+QK		A	"@HAD@ QS5 5	)C
acFA@		*CacBA@A@
	)*	)	#+	#< <,a_HCSCRN 	+	#$+%%,a_HCSCRN 	$+	@acJA@,a
@LCSCRN 9 9A@acJA@,a
@LCSCRN A@4acJA@,a
@LCSCRN A@=+	+QgL; ;,Qg5	@Q_	C>F	+@HADQGQacNQ	@,a
@LCSCRN A@,a
@HCSCRN : :,aKDCOPT	$#kh	&CjacFA@	m,aKDCOPT	$#	@ac:A@A@#A@9 9u,aKDCOPT	$&	@	acBA@A@	#+,acP,a
@LCSCRN A@,	#&: :,aKRCMISC 	A
acTA@-,aKRCMISC 	-@ ,aSRCMISC 	-.	-C9 9acTA@-,,aKV	CSCRN 	A
	-%;;	%           :	@<	-%DD5; ;	%C	@>G	--E1,aKXCSCRN 	A
	A/0N		$#	@	)acBa@: :A@
U	)%cu	#@HAD-QS	(#@#$"pn	"o	-C		QS	tu9 9	#@H$	
%%		1A2	)%u	3#u	A#u	-4A56	)%u	7; ;	#u	#@H$	%~	)%%u	A89u		1	
2	)%3u	3#&A8	
9(9 9u	A#&A8	9:	-4@ 5	
6	)%Ou	7#&A8	9Cu	#B$	% 		: :	1	2.	)%gu	3$	%]u	"#QK	+u	-4A5	6J	)%~u	79 9	#u	A8	9V		1	2b	)%u	3#8	9u	"#8	9	-4@ 5	6; ;y	)%'u	7#8	9u	"#-QS	u	#"-QS	u	-QS	u	A/	
0R9 9	)%Gu	#@HAD	QSu	A/	0B	)%Wu	#@HAD	QS		QS	u	#@HAD9 9QK	C	(#aah		1	2
	)%u	3#/	0Rt	)%; ;	(#@	#$3	@HAD	QS~	&#u	A,a_XCSCRN ,aSXCSCRN 	AacB: :A@A@uacBa@A@u	A,a_V	CSCRN ,aSV	CSCRN 	AacBA@A@u9 9*acBa@ A@u	A"#uacZu(	.:L>::Xy^4: :8:DmQ=s.a<$)*TN))))))): :8)))))))))))))))))))))))))))): :8)))))))))))))))))))))))))))): :8))))))))))))))))))))))))))))5 5
))))9a		)acBa@&A@
ux	"@HAD	QS	@ t"	QSacJA@; ;,a
@LCSCRN A@	"Qg	@acNA@,a
@LCSCRN A@,a
@HCSCRN bQK9 9	@HADQGQacNQ	@,a
@LCSCRN A@,a
@HCSCRN n,aKDCOPT	$#	@ac:; ;G@zA@#A@,aKDCOPT	$&	@	acBA@A@	#QS		"acTA@;: :,aKV	CSCRN 	A
	;%++	%           *	@,	;%44%	%3	@.79 9	;;5	;4C,aK\CMISC 	;>	;,aS\CMISC 	4% I	%!LHK		"9 9	<L	A<O	#77%V	5AZ	"7W	"$7a	5A[9 9e	A7b	<77i^	7A	$"oq	@HADQK	;Crfy	7#CTz9 9	7A	$"	@HADQK	;C		)acBa@,A@
p	1C		"9 9	=#@H3	A=#3	=33$	3A	%*	@t3,aK^COPT	A
%,3	3; ;	%99	%8:;		)acBa@A@
<,	8#"C		)	acBa@A@
9 9J	8A	#,ac`Q	@A@,Q	@A@#	"8"VSz	/"C		)acB9 9a@A@
k	">/?	>@H>?@H?y	#$>	@?@H,>@HADQK	t,QSz9 9	/""tk	$%	%		)acBa@A@
	$#	("@: :(	"$#-	@HAD	QS).%5	%L&u!ul6	0L_C: :S{?f	9L	);uWuu-GE	2L/cqS	6: :	L
Kz#\!}!~!"!!!
!!!!!9 9!!	! d!!!!	!	!
! !!!!9 9! !"!<!>d!Ad!        Z!a!z!|d!!d	co: :l .   1line .  C#=. :$=. !`$CLINES!b$CLINES!$CMISC !v$CMISC !$COPT!\: :$COPT!h$COPT!l$CSCRN !p$CSCRN !d$CSCRN !|$CSCRN !z$	CSCRN !X#LENGTH!Z#WATCH 3 3!^#LITNN0!f#MESG!j#T1OU!n#LOAD!r#LOADS0!t#POSIT0!x#C1IN!~#RESTO0!#SCOPY 
 
"%N@0&$

8"" SEND6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES	,aKCSCRN ,a_CSCRN 	C,aKCSCRN ,a_CSCRN 	C9 9		acQ	@,aKCSCRN ,a_CSCRN 	C,aKCTERM 	%	% 	%: :#	%&"	%)%	%,(	A,aSCSCRN ,a[CSCRN ,aSCSCRN +9 9,akCSCRN 	@3		!!!!!!"8! $CTERM !$CSCRN ! $CSCRN !$CSCRN !$CSCRN !#T1OU
 
"%&"0&nF$ POSIT06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE ; ;CTXTCPATCLINES	QK,agCSCRN 	@@HCQK,agCSCRN 		@@HC9 9QK,a_CSCRN 	CQK,a_CSCRN 	C,aKCTERM 	"acQ	@9 97Q	@acQ	@Q	@*acQ	@Q	@1ac Q	@Q	@8ac"Q	@Q	@?ac$Q	@9 97Q	@Fac&Q	@Q	@Mac(Q	@Q	@Tac*Q	@Q	@[ac,Q	@Q	@bac.Q	@9 97Q	@iac0Q	@Q	@pac2Q	@Q	@wac4Q	@Q	@~ac6Q	@Q	@ac8Q	@9 97Q	@ac:Q	@Q	@ac<Q	@Q	@ac>Q	@Q	@!ac@Q	@Q	@(acBQ	@: :Q	@/acDQ	@Q	@6#	"L- $+9@GNNNNU\cjqx: :82jjjj2U92NN)007jj"2U+j; ;=		!$CTERM !$CSCRN !$CSCRN !$CSCRN !$CSCRN !#ADDSP0!#REGEN0!#HPPOS 9 9! #PEPOS !"#TVTPOS!$#GT40P0!&#BEEPOS!(#HAZPOS!*#CGPOS !,#ISCPOS!.#ADMPOS!0#IBMPOS!2; ;#ANPPOS!4#NETPOS!6#H19POS!8#TRSPOS!:#BEE2P0!<#TERAK0!>#INFOP0!@#NBYPOS!B#ANSIP0!D#FORSY0
 
"%*$0&& B200C0* *	QK	@H"M=#9@"A$#C<$"acA@"		!
!#T1OU
 
"%*&0&I,$ BEEPOS6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	,aKCSCRN 	BQ_	CQK	@HC,aKCTERM 	%: :acA@	A,aSCSCRN ,a[CSCRN ,aSCSCRN          AQg$!Q_	C8 8#acA@acA@	A,aSCSCRN ,aSCSCRN 'QK,a_CSCRN 	C6 6,aKCSCRN Qg;@	Q_	CA,aKCSCRN QgM,aKCSCRN 	C9: :,a[CSCRN 	AD,aGCSCRN 	QacQ	@,akCSCRN GGFQK,a_CSCRN 	C6 6,aKCSCRN 	Qgldj	Qgk	@,aKCSCRN QgwacA@9 9,aKCSCRN 	@H,aSCSCRN qoacA@acA@,aKCTERM 	%	%: :acQ	@acQ	@                                            aKCTERM 	%	 	%
#	%&"%< <QK	"	acA@"QK	"acA@"&acQ	@acQ	@7QK,aSCSCRN : :QK,aSCSCRN vL5		!!	!!!	!
!I!!
< <!!I!F!HI! $CTERM !&$CSCRN !$CSCRN !$$CSCRN !"#T1OU!(#B200C0 !*#SBEEC0
 
"%,$0&B$ BEE2P06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE ; ;CTXTCPATCLINES	,aKCSCRN 	Qg	"	"@H"	QK	$"ac9 9A@
,aKCSCRN Qg	"	("@	"Qg$acA@%: :QK,aSCSCRN QK	@HC
acA@3acQ	@8QK,aSCSCRN 		!% %
!!B!$CSCRN !$CSCRN !#T1OU!#UHCM
 
"%*$0&#"$ REGEN06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES	,aKCSCRN Q_	A%	@,aKCSCRN Q_	C7 7acA@acA@QK	"	acA@"QK	"	acA@"QK,aSCSCRN QK: :,aSCSCRN QK,agCSCRN 
6acA@,aKCSCRN 	@H,aSCSCRN 29 97,aKCSCRN QgFacA@,akCSCRN 	@A,aSCSCRN BG,aKCSCRN 9 9
QgWQK,agCSCRN _,aKCSCRN 	C9,a[CSCRN 	AD,aGCSCRN Q5 5acQ	@,akCSCRN YYX,aKCSCRN Q_	C?,a_CSCRN 	CQK8 8,agCSCRN 
acA@,aKCSCRN ,a_CSCRN 	C	A,aSCSCRN z	9 9,akCSCRN 	@zyQK,agCSCRN 
acA@,aKCSCRN 	@H,aSCSCRN : :^1		!#!!!
!!!#!Y#!$CSCRN !  $CSCRN !$CSCRN !$CSCRN !#T1OU
 
"%,$0&/&& HPPOS 6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE < <CTXTCPATCLINES	,aKCSCRN 	BQ_	CQK	@HCacA@	A,aSCSCRN 8 8,a[CSCRN ,aSCSCRN 	AQgQ_	CacA@acA@	A9 9,aSCSCRN ,aSCSCRN "QK,a_CSCRN 	C,aKCSCRN Qg6;	: :Q_	C<,aKCSCRN QgH,aKCSCRN 	C9,a[CSCRN 	AD,aGCSCRN Q: :acQ	@,akCSCRN BBAQK,a_CSCRN 	C,aKCSCRN 	Qgg_e8 8	Qgf	@,aKCSCRN QgracA@,aKCSCRN 	@H,aSCSCRN lj; ;,aKCSCRN Q_	A",aKCSCRN Q_	AC?"%	@,aKCSCRN 
Qgac7 7	A@acA@,akCSCRN QK,agCSCRN $acA@acA@9 9,aKCSCRN 	@H,aSCSCRN  %QK,agCSCRN 
8acA@,aKCSCRN 	@H: :,aSCSCRN 49,aKCSCRN QgH,aKCSCRN 	C9,a[CSCRN 	AD,aGCSCRN 9 9	QacQ	@,akCSCRN DDacA@acA@acA@	QK	@H"M=
@#"M9 9	=
$A
	"acA@"u	#"acA@"acA@QK	@H"M=
@#"M=
$A
	9 9	"acA@"	#"acA@"acA@QK,aSCSCRN QK,aSCSCRN IqG09 9		!!!

/!!
!!&!0!A!B!C!H!	# #a!y/!$$CSCRN !$CSCRN !"$CSCRN ! #T1OU
 
"%.&0&Y$ IBMPOS6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 5 5CTXTCPATCLINES	QK,a_CSCRN 	CQK,a_CSCRN 	A%7 7,aKCSCRN Qg,aKCSCRN 	C9,a[CSCRN 	AD,aGCSCRN 	QacQ	@9 9,akCSCRN QK,agCSCRN 
,acA@,aKCSCRN 	@H,aSCSCRN < <(acA@acA@QK	"	acA@"QK	"	acA@"QK,aSCSCRN QK7 7,aSCSCRN -		!Y!!!Y!YY!$CSCRN !$CSCRN ! $CSCRN !#T1OU
 
"%,$0&7$ INFOP06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES	,aKCSCRN Q_	CQK,a_CSCRN 	A%	@9 9acA@acA@QK	"	acA@"QK	"acA@"acQ	@)QK6 6,aSCSCRN QK,aSCSCRN 		!7!!7!f7!$CSCRN ! $CSCRN !#T1OU!#UHCM
 
"%*$0&o $ H19POS6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	QK	%	@,aKCSCRN 	B	Qg,aSCSCRN 	A7 7,aSCSCRN acA@QK,a_CSCRN 	CQK,a_CSCRN 	A%$7 7,aKCSCRN Qg*,aKCSCRN 	C9,a[CSCRN 	AD,aGCSCRN 	QacQ	@9 9,akCSCRN &&+QK,agCSCRN 
BacA@,aKCSCRN 	@H,aSCSCRN < <>%acA@acA@QK	"	acA@"QK	"	acA@"QK,aSCSCRN QK8 8,aSCSCRN C		!!o!!
!!o!Yo!$CSCRN ! $CSCRN !$CSCRN !#T1OU
 
"%,$0&g $ PEPOS 6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE ; ;CTXTCPATCLINES	,aKCSCRN Q_	C,aKCSCRN 	@HQ_	Cac; ;	A@acA@,aKCSCRN 	@H,aSCSCRN ,aKCSCRN 	BQ_	CacA@< <acA@,akCSCRN .#acA@acA@QK	"	acA@"QK,aSCSCRN 5 5/QK,a_CSCRN 	ACacA@acA@QK	"	acA@"QK9 9,aSCSCRN LacQ	@a		!g!!g!A!B!X!Y g!$CSCRN !$CSCRN !#T1OU!#UHCM
 
"%*$0&M$ ADMPOS6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	QK	%	@,aKCSCRN 	B	Qg,aSCSCRN 	A: :,aSCSCRN acA@,aKCSCRN Q_	CQK,a_CSCRN 	A%	@; ;$acA@acA@QK	"	acA@"QK	"acA@"&acQ	@?QK: :,aSCSCRN QK,aSCSCRN 		!M!
!!M!=M!$CSCRN ! $CSCRN !#T1OU!#UHCM
 
"%*$0&

*" UHCM6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE < <CTXTCPATCLINES	,aKCSCRN Qg,aKCSCRN 	C9,a[CSCRN 	AD,aGCSCRN 9 9	QacQ	@,akCSCRN QK,agCSCRN 
acA@,aKCSCRN 2 2	@H,aSCSCRN 		!*!$CSCRN !$CSCRN !$CSCRN !#T1OU
 
"%("0&Y$ HAZPOS6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 5 5CTXTCPATCLINES	QK,a_CSCRN 	CQK,a_CSCRN 	A%7 7,aKCSCRN Qg,aKCSCRN 	C9,a[CSCRN 	AD,aGCSCRN 	QacQ	@9 9,akCSCRN QK,agCSCRN 
,acA@,aKCSCRN 	@H,aSCSCRN < <(acA@acA@QK	@H"	acA@"QK	@H"	acA@"QK,aSCSCRN QK; ;,aSCSCRN -		!Y!!                                 Y!$CSCRN !$CSCRN !$CSCRN !#T1OU
 
"%,$0&"$ NETPOS6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES	acA@acA@QK	@H"	acA@"QK	@H"	acA@"QK4 4,aSCSCRN QK,aSCSCRN 		!!="!$CSCRN !$CSCRN !#T1OU
 
"%*$0&`$ GT40P06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES	QK,agCSCRN QK,agCSCRN acA@QK8 8	"	acA@"QK	"	acA@"QK,aSCSCRN QK,aSCSCRN QK5 5,agCSCRN 0acA@QK	"	acA@"QK,aSCSCRN /QK; ;,a_CSCRN 	A%HacQ	@I	acA@QK	"	acA@"QK,aSCSCRN 7 7N@)		!`!!!!`!$CSCRN !$CSCRN !#T1OU!#UHCM
 
"%*$0&'$& ADDSP06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE < <CTXTCPATCLINES	,aKCSCRN Q_	C,aKCSCRN 	Qg	@ac9 9A@QK	"	acA@"QK,aSCSCRN 	A,aSCSCRN ,aKCSCRN 	@DQg9 9'QK	BM=#9@B$,aKCSCRN 	@HM=#A#$Q_	A#%	@	#@H#D	#: :	A
acA@EJ	$,aSCSCRN B(,aKCSCRN 	
QgXQK,a_CSCRN 8 8	$acA@acA@	$M=	"acA@"	$M=@	"	acA@"QK,aSCSCRN Y7 7,aKCSCRN Qg,aKCSCRN 	C9,a[CSCRN 	AD,aGCSCRN 	QacQ	@9 9,akCSCRN ~~QK,agCSCRN 
acA@
,aKCSCRN 	@H,aSCSCRN : :		!!!!
'!!
!	!!!	0!?'!" $CSCRN !$CSCRN !$CSCRN ! #T1OU
 
"%.&0&B 
$ ANPPOS6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	QK,a_CSCRN 	CacA@acA@acA@: :acA@acA@acA@,aKCSCRN 	BQg+,aKCSCRN 	@DQg9 92,aKCSCRN 	@HQg9,aKCSCRN 	@HQg@acA@acA@QK; ;	"acA@"#QK,a_CSCRN 	CacA@acA@acA@\ac9 9A@eacA@acA@jW,aKCSCRN 	BQg{X,aKCSCRN 	@DQg9 9],aKCSCRN 	@HQg	f,aKCSCRN 	@HQgkacA@acA@QK	< <	"acA@"sVacA@acA@QK	"	acA@"QK	"acA@" PQK9 9,aSCSCRN QK,aSCSCRN 		!!	!
!!!B!C!P !RB!$CSCRN !$CSCRN !#T1OU
 
"%*$0&
0& CGCOO09 9	QK	M=@"QK	M=QS	M=@#QK	M=QS	M=@$%acA@%	#%$ $acA@%	"%acA@%		!
0!0!#T1OU
 
"%*&0&"
& CGPOS 6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE < <CTXTCPATCLINES	,aKCSCRN 	BQ_	CQK	@HCacA@	A,aSCSCRN : :,a[CSCRN ,aSCSCRN 	AQgQ_	CacA@	A,aSCSCRN : :,aSCSCRN "QK,a_CSCRN 	C,aKCSCRN Qg27	Q_	C8; ;,aKCSCRN QgDacA@,akCSCRN >>=,aKCSCRN 	Q_	CE"QK9 9,a_CSCRN 	CD#QK,a_CSCRN 	CBA	#A	"	A,aKCSCRN 
Qgjac9 9A@,aKCSCRN 	@H,aSCSCRN dcacA@acA@QK	@H9@A$QK	@H: :	9	@%acA@%acA@$QK,aSCSCRN QK,aSCSCRN iC,		!	!!: :
!!!
!!!U!!$CSCRN !$CSCRN !#T1OU!  #CGCOO0
 
"%,&0&
-$ ISCPOS6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	AQgQ_	C
acA@
	acA@QK	@H9 9	"	acA@"QK	@H"acA@"QK,aSCSCRN QK,aSCSCRN 		!! -!$CSCRN !$CSCRN !#T1OU
 
"%*$0&$ SBEEC08 8		acA@QK	@H"M=#acA@#	"M=@#acA@#		!
!0!#T1OU
 
"%($0&3$ TERAK06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES	,aKCSCRN Q_	CQK,a_CSCRN 	A%	@; ;	acA@QK	"	acA@"QK	"acA@"acQ	@%QK,aSCSCRN 7 7QK,aSCSCRN 		!3!!3!$CSCRN !$CSCRN !#T1OU!#UHCM
 
"%*$0&c" TRSPOS6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 8 8CTXTCPATCLINES	,aKCSCRN 
QgQ_	CacA@,aKCSCRN 	@H5 5,aSCSCRN 
acA@,akCSCRN 	@QK,agCSCRN #; ;,a_CSCRN 	C,aKCSCRN Qg+acA@,akCSCRN ''&,aKCSCRN ; ;	M=Q_	CacA@	A,aSCSCRN ,aKCSCRN QgHacA@,akCSCRN 9 9DD<QK,agCSCRN 
VacA@,aKCSCRN 	@H,aSCSCRN RWI,"2 2		!c!!!!!c!$CSCRN !$CSCRN !#T1OU
 
"%("0&u( TVTPOS6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	QK,a_CSCRN 	A"QK	@H#,aKCSCRN 	Qg9 9Q_	$QK,a_CSCRN ,a_CSCRN 	A$QK	@H,a_CSCRN 	A%$"&9 9	%#B$&	@acA@	A,aSCSCRN ,aSCSCRN -,aKCSCRN 
Qg>ac7 7A@,aKCSCRN 	@H,aSCSCRN 	%88,aKCSCRN ,aSCSCRN 8=QK: :,agCSCRN S,aKCSCRN 	@H,aSCSCRN U,aKCSCRN QgaacA@9 9V,akCSCRN 	@T,aKCSCRN QgoacA@fn`		!u!!' '	!!u!$CSCRN !$CSCRN !$CSCRN !#T1OU
 
"%.(0&I$ NBYPOS6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	QK	%	@,aKCSCRN 	B	Qg,aSCSCRN 	A: :,aSCSCRN acA@,aKCSCRN Q_	CQK,a_CSCRN 	A%	@5 5$	acA@QK	"	acA@"QK	"acA@"&acQ	@;QK9 9,aSCSCRN QK,aSCSCRN 		!I!
!!I!$CSCRN !$CSCRN  !#T1OU!#UHCM
 
"%*$0&N& ANSIP06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE ; ;CTXTCPATCLINES	acA@acA@QK	M=@"QK	M=#A
	$acA@$< <	"$acA@$acA@QK	M=@"QK	M=#A
	$acA@$3	"$ac: :A@$acA@QK,aSCSCRN QK,aSCSCRN 		!
N!!0!;!H ![N!$CSCRN !$CSCRN !#T1OU
 
"%,&0&"$ FORSY06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES	acA@acA@QK	"	acA@"QK	"	acA@"QK: :,aSCSCRN QK,aSCSCRN 		!!"!C"!$CSCRN !$CSCRN !#T1OU
 
"%*$0&