% $ WARND06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES"gone	,aKCSCRN 	"	("@	",agCSCRN : :	@,a[CSCRN ,a_CSCRN QgQg	@aca@A@"A@A@
		( (!%!%!$CSCRN !$CSCRN !$CSCRN !#LOADS0
 
"%*$0&0$ ALLOC 6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 6 6CTXTCPATCLINES	,aKCBUFR$	BC,aKCBUFR$	MAQA'	@: :,aKCBUFR$QS	,aSCBUFR$		QS,aKCBUFR$QS,awCBUFR$9 9,aKCBUFR$,aSCBUFR$QK	"	!+!+p
!$CBUFR$ !$CBUFR$!$CBUFR$
 
"%*$0&K$( INJECT6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	A"	"@HADQK	A
acQ	@A@"A@#	"C		: :	$	,aSCMISC 
ac,a
@CLINES	%t%,aKCBUFR$	&acA@%A@#A@#A@&9 9acA@#A@&A@%A@#ac,a
@CLINESA@,akCLINES	@,akCLINES	@	$: :	$	!}!~K!K!K!$CLINES!"$CLINES!$CBUFR$!$CMISC ! #MAKLIN!#GETIND!#RELINK! #SVINS 
 
"%,(0&m,& MAKLIN6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES		"acA@#	BC	"		QK	$	($@	$@HADQK9 9	A
	C	($	$Q_	CQK	$$	$Q_	B%QK	@HAD9 9QGQ
acQ	@
Q@
A@%	@ t%QS	,aKCSCRAT	t#,aSCBUFR$	%,aSCBUFR$	@ 9 9,aSCBUFR$		,aS	CBUFR$ac,a
@CSCRAT,a
@ CSCRAT	ac"Q@
A@%,a
@ CSCRAT: :	%M,a[CSCRAT,aSCSCRAT	A,aS$CMISC 	#QS	$"
!}m!
! m7 7!!m! $CBUFR$!$CBUFR$!$CBUFR$!"$	CBUFR$!&$CSCRAT!$CSCRAT!* $CMISC !#ALLOC !#MOVE$ !$#SEEKF !(#WRITEF
 
"%2&0&-$ SVINS 6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 6 6CTXTCPATCLINES	,aKCSCRN QgQ[,aSCSCRN QK: :,a_CSCRN 	B"A#	(#@	#,agCSCRN 	@t#,aKCSCRN 	%#	$"'4 4Q[,aSCSCRN 		!-!$CSCRN !$CSCRN !$CSCRN 
 
"%*$0&V* APPEND6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES"apd>	QK,aSCLINESQK	C	uQGQ7 7acQ	@	"	,aKCLINES,a_CSCRN ,a[CSCRN 	B,aSCSCRN 	@ Q9 9,aK COPT	A	QK	A$(,aK COPT	@Hac"A@	#)ac$Q	@	$9 9	A#	(#@:	t#,aK&CTXT	C;B2	#%A"H	"@HCac(A@	A7 7,aK*CSCRN ,agCSCRN W,aKCSCRN 	B,aSCSCRN ac,,a
@*CSCRN : :,a
@CSCRN ac.,a
@CLINES,a
@CLINES,aKCSCRN ,ag0
CSCRN n,aS0
CSCRN ; ;oXac2,a
@CSCRN ,aKCSCRN ,ag*CSCRN z	B&ac2A@&{R,aKCSCRN 9 9,ag*CSCRN 
	@H,aSCSCRN ac4,a
@CSCRN A@ac6,a
@CSCRN A@9 9,akCSCRN 	ac4,a
@*CSCRN A@ac6,a
@CSCRN A@ac8a@9 9ac:Q@,a
@<COPTA@#A@'	'%;-	%>-	%A-	@ (Q	C9 9Q	CGQ	AL	A(P	A)	()@U	)$%Z	t)QK	C[V9 9a	)%C	t%QK	CfQK	ClQK	Aq	A(u	(@HCac(A@9 9	@HCac4,a
@CSCRN A@ac6,a
@*CSCRN A@			"{acQ@	
C9 9		
"ac8A@                                            akCSCRN 	@'%'I,aK COPT	A	@H#5 5*	A#	(#@0	t#QK	C18-	#%@ QIL,aK>CSCRN 	@H; ;,aSCSCRN ac(A@	@HC,aKCSCRN ,aS@CSCRN 	A)	()@R	),agBCSCRN : :	@,a[@CSCRN 	@H,agDCLINES	@)t),aSFCSCRN S_		t),aSFCSCRN S: :XK,aKCLINES	A,aKDCLINES	An	A,aSCLINESrQK,ag0
CSCRN 9 9z,aS0
CSCRN {	"	!
}!	~!!!!!!
!!: :! !.!:!$$CLINES!R$CLINES!4$CTXT!J$COPT!.$COPT!L$CSCRN !*9 9$CSCRN !8$CSCRN !,$CSCRN !($CSCRN !>$
CSCRN !P$CSCRN !N$CSCRN !T$CSCRN !&; ;#INJECT!6#HWINS0!2#GETTXT!0#F$MA11!:#CPROW !<#ADJUS0!@#CLRROW!B#DELLI0!D#INSLI0!F#PROMPT !H#GETCMD
 
"%2*0&" CLRROW6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES	acA@Q	@A@A@acA@Q	@A@,a
@CSCRN 		! !!!!$CSCRN !#LOADS0
 
"%&"0&$ CKCHAR9 9	QK		@HADQKQgQg
Qk		@AQS	@ QS		 QS	"	!~
 
"%6$0&2, DELETE6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 8 8CTXTCPATCLINES	QK	"QK	#"A			QS		,aSCMISC 		"9 9,ag
CSCRN ,aS
CSCRN acA@"	$acA@$	%t%,aKCBUFR$	&ac: :A@#	't',aKCBUFR$	(#"B,a_CLINES	A,aSCLINESacA@",aSCLINESac7 7A@%A@(A@%A@(,aK CUNDO 	%L,aw CUNDO ,aK"CBUFR$	),aK$CBUFR$9 9,aS"CBUFR$	),aS$CBUFR$K,aK&CUNDO ,a[(CSCRAT,aS(CSCRAT	&,aS CUNDO 	#< <	"B$,aS&CUNDO acA@'A@&A@'A@&ac*A@"A@$		QS	A,aS,CMISC QK6 6	*	!}!~!!     ! $CLINES!$CLINES!($CBUFR$!&$CBUFR$!< <$CBUFR$!$$CUNDO !*$CUNDO !,$CSCRAT!0$CMISC !$CMISC !$
CSCRN !#PREVLN!#GETIND !"#RELINK!.#SVDEL 
 
"%6,0&q& SVDEL 6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE ; ;CTXTCPATCLINES	QKQ[,agCSCRN 	@,aKCSCRN Q_,aSCSCRN : :QK,agCSCRN Q[,a_CSCRN 	"A#	(#@	#,agCSCRN 	@6 6	t#,aKCSCRN 	BC*	t#,aKCSCRN 	$"	@	,aSCSCRN 0	t#9 9,aKCSCRN 	",aSCSCRN 5#QK,aSCSCRN QK,a_CSCRN 	$: :Q[	"A#	(#@L	#,agCSCRN 	@t#,aKCSCRN 	%ZM	$CM]; ;	t#,aKCSCRN 	$"	@	,aSCSCRN b	t#,aKCSCRN Q_,aSCSCRN gM" "RA		!q!$CSCRN !$CSCRN !$CSCRN 
 
"%,&0&& DOPRNT6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE ; ;CTXTCPATCLINES	QK	"QK	#A			$	,aSCMISC 	acA@#A@"7 7	",aSCLINES		$	$	!}!~!     !$CLINES!$CMISC !#ADJUS0
 
"%,&0&R
, OVERL06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES"
		QS,aKCLINES	A	@ ,aSCLINESaca@; ;QS	C			A,aS
CSCRN ,aSCLINES,a[CLINES,aSCLINES,aKCLINES7 7	"	("@!	",agCLINES	@,aSCLINES,aKCOPT	#ac,a
@CLINES9 9,a
@CLINESac ,aK"CSCRN ,a[CLINES,a_$CSCRN ,aS&CSCRN ac(,a
@CLINES8 8	$t$,aK*CBUFR$	%t%,aK,~CTXT	C	%@H%L	#A		%#R	%$#W		t%: :,aS.CTXT	(%UUX		t%,aS.CTXT	@ ,aS0CTXT	%B&ac2,a
@0CTXTQ@A@&9 9ac4,a
@0CTXT,a
@6COPTA@#A@',aKCLINES,ag
CSCRN ,aS
CSCRN 8 8	'C'ac8,a
@0CTXTQ@	A	t$,aK:	CBUFR$	(ac<,a
@CLINES; ;,a
@CLINESQ	@,aKCLINES	)QK	@DCac,a
@0CTXTQS$QK	C9 9/ac>A@)	&ac@A@&	$(t$,aS:	CBUFR$	'*	A,agCLINESE; ;,a_CLINES	A,aSCLINESF,aKBCLINES,aSCLINESL,aKCLINES,agBCLINES9 9V	B,aSCLINESQW,aKBCLINESacDA@,aSCLINES[	A#dA	*9 9	+LBnopqrRseug	'%{.	%~.	%	."09 9,aKFCSCRN 	@H,aS&CSCRN 		!}!~!!!!!
!5 5!	! !$CLINES!$$CLINES!$CLINES!L$CLINES!6$~CTXT!8$CTXT!:6 6$CTXT!4$CBUFR$!D$	CBUFR$!&$COPT!@$COPT!P$CSCRN !,$CSCRN !0$CSCRN !.9 9$CSCRN !"$
CSCRN ! #INJECT!H#NEXTLN!B#EQUAL !J#GETIND!2#GETTXT!(#ADJUS0!*#UPDSC0!< #MOVE$ !>#GETCMD!F#DELETE!N#F$MI11
 
"%0,0&
:&& PTSCAN6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES	,aKCLINES	QSacQ	@	"acQ	@A@"Q	@acA@"ac9 9,a
@CTXT,a
@CPAT	@HC		#	QK,agCLINES
(acA@$	A'
7 7-,aK CMISC 	C		,aS CMISC 3		#	!}!~:!!:!5 5$CLINES! $CPAT!$CTXT!$$CMISC !#MATCH !#GETIND!"#INTRPT!#BUMP!#GTXT
 
"%,&0&

." BUMP6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE ; ;CTXTCPATCLINES	QK	AQw,aKCBUFR$QS,a_CBUFR$	C	@ QS< <Qk	@QK,a_CBUFR$	C,aKCLINESQSQK	@HQS3 3!Qw,aKCBUFR$QS		!$CLINES!$CBUFR$!$CBUFR$!$CBUFR$
 
"%,"0&xD. SUBST 6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE < <CTXTCPATCLINES	A,ag	COPT	Q_	C		"
		",aKCLINES8 8	A			,aSCMISC 	"	ac,a
@CPATA@	A
		,aSCMISC  9 9,aKCLINES	#	(#@(	#,agCLINES	@acA@$	A
		"5	A%9 9	@ &acA@#	'@ (A)F	t),aK CTXT	A
		*@ t*QS	QS	A*%ZM: :MQK	%_	&A
^aac",a
@$CTXTA@),a
@CPATQ@Q@	*: :b	@ *p	*A	$(yu	A&)Q
	*Qac&,a
@$CTXTQ@
Q@Q	@Q@
: :A@%A@	*(x	*A
	$)	t),aG CTXTQac(Q	@Q@
A@%A@: :	+()GG	*)GK	&@HCac(A@	Q@
A@%A@	A		"	
,aSCMISC : :.?	t',aK*	CBUFR$	,ac,A@#A@#A@-ac.Q@
	",aK0CLINES,ag2
CSCRN 5 5[,aS2
CSCRN \	"CEbac4,a
@0CLINES	',t',aS*	CBUFR$		"A: :,aS6CMISC )3		,aSCMISC )c!}!~x!	!!!6 6!
!
!                                 x!
x!x!$CLINES!&$CLINES!<$CLINES!$9 9$CPAT!,$CTXT!0$CTXT!6$	CBUFR$!B$CMISC ! $CMISC !$	COPT!>$
CSCRN !4#ADDSET1 1!.#AMATCH!*#GETTXT!:#INJECT!@#GETIND!(#INTRPT!"#INDEX !2#CATSUB!8#DELETE
 
"%N.0&\$ OPTPAT6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE < <CTXTCPATCLINES	QK	@HADQK	A		QSQwQK	A		QS9 9QK	@H"QwQK	t"Q_	C	Qk&#QK	@HAD	QGQQK; ;	B"acQ	@A@"Q	@,a
@CPATQS',aKCPAT	A		#	,aSCMISC : :CQK	C	@ ,aSCPAT		#	,aSCMISC N		#WI	#	!}!~\ !!\!$CPAT!$CMISC !#MAKPAT
 
"%,$0&,( GETRHS6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE < <CTXTCPATCLINES	,aKCUNIX0	@HC		"		"		,aSCMISC 		#QK9 9	@HADQK	A	#	QwQK	"CQK	B$QK	@H%t$QK	t%Qg1; ;	%40 3ac,a
@CPAT	Q	@A@QK	@DQS	@H$t$QK	CQK: :	ADQK	t$QS			QwQSQK	BAD@ QS		,aSCMISC I4QwQK	9 9	CQK	@HADQKQwQSQK	BAD	QSQK	@DAD@ QS		,aSCMISC : :iQK	&	(&@		&@HADQK	A

	&@H&@HADQK	%	%!9 9 	&@H&@HADQK	%	,	%
/+.QK	B$&	@&@H$QK	@H%t$: :QK	t%Q_	C4	&ADQK,a_CUNIX0	C	&ADQK,agCUNIX0WM: :DW	&@D&@H$QK	@HADQK	t$QS		t&QS	&BAD@ QS		,aSCMISC V9 9/QK	B$&	@&@H$QK	@H%t$QK	t%Q_	Cx	&@HADQK,a_CUNIX09 9	C	&ADQK,agCUNIX0    	&@D&@H$QK	@HADQK	t$QS		t&9 9QS	&BAD@ QS		,aSCMISC s!	&@HADQK	%	@	%
C?B; ;	&@H&QK	B$&	@&@H$QK	@H%t$QK	t%Q_	CK	&@HADQK,a_CUNIX09 9	C	&ADQK,agCUNIX0nd[n	&@D&@H$QK	@HADQK	t$QS		t&9 9QS	&BAD@ QS		,aSCMISC mC	&@H$QK	@H%t$QK	t%	Qg: :Q_	C	&@HADQK,a_CUNIX0	C	&ADQK,agCUNIX01'1	(&: :	@&@H$QK	@HADQK	t$QS		t&QS	&BAD@ QS		,aSCMISC 0
7QK5 5	@HAD	QGQQK	B$acQ	@A@$Q	@Q	@QS	CgacQ	@< <,a
@CPATA@bQwQK	%	x	%
{wzQk	@AQS	{	@ QS	9 9		,aSCMISC 		#!|!}!~!!!
!!%!6 6&!
G!P!	g!p!!$$CPAT! $CMISC !&$CMISC !$CUNIX0!(                                                                    CUNIX0!*#MAKSUB!"#CTOC
 
"%6(0&" REMARK 		acQ	@A@		!!#LITME0
 
"%&"0& $ LITNN0: :	acQ	@A@Q@
A@	"t"QG
Q
acQ	@Q	@
A@acQ@
Q	@		!
! !.!#PTOC!#ITOC!#MESG
 
"%0$0&

+$ CKP 9 9	QK	"@HADQK	%	%
	("@AQS	@ QS	"@HAD: :QK	C		QS			QS	#QK		#	!}!~+!
!P!p +
 
"%0$0&y0& DELLI06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES"(                                        9 97                                                       9 9!                                 		acQ	@A@	A"	(": :	@		"Qg	@,aKCTERM 	#acA@acA@	@ $acA@acA@9 9	@ $acA@acA@		$*acA@acA@		$5acA@acA@		9 9	$@acA@acA@		$KacA@acA@			$    VacA@acA@
ac9 9	A@acA@	@ $a	#L, A6z{|}+~: :6+WL+	 b6L ; ;	in dellines: shouldn't happen.#acC@$t	$A


acA@$
,aKCSCRN 	": :	("@BQK	",agCSCRN 	@C9AD,aGCSCRN Q	"C9AD,aGCSCRN Qac ; ;Q	@Q	@,a
@"CSCRN C	("@J	",agCSCRN 	@C9AD,aGCSCRN 	Qac a@: :Q	@,a
@"CSCRN bg		!!! y!@y!!y!1!	4< <!M!R!
[!ly!$CTERM !*$CSCRN !($CSCRN !.$CSCRN !&$CSCRN !#POSIT0 ! #T1OU!"#ERROR !$#SENDD0!,#MOVE$ 
 
"%0&0&}0& INSLI06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES"(                                        9 97                                                       9 9!                                 		acQ	@A@	A"	("; ;	@		"Qg	@,aKCTERM 	#	@ $acA@acA@	@ $	acA@ac; ;A@		$acA@acA@*		$acA@acA@5		$acA@acA@; ;@		$acA@acA@K	@ $acA@acA@	acA@
acA@V		$ac9 9A@acA@i	#L,$A6z{|}+~+: :2jL+	 W6L 	in: : inslines: shouldn't happen.#acC@$t	$A


acA@$
,aKCSCRN 	"	": :	@H"B	"Q_,agCSCRN NN	C9AD,aGCSCRN Q	"C9AD,aGCSCRN Q< <	ac Q	@Q	@,a
@"CSCRN C	"@H"M	",agCSCRN mm	C9AD,aGCSCRN Q: :	ac a@Q	@,a
@"CSCRN dl		!!! }!@}!!}!
7 71!4!E!L!M!	[}!$CTERM !*$CSCRN !&$CSCRN !.$CSCRN !(# #$CSCRN !#POSIT0! #T1OU!"#ERROR !$#SENDD0!,#MOVE$ 
 
"%0&0&