

^x@ EDIT6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 5 5CTXTCPATCLINES"LOGOUT$ "cmd>acac		88@DCac ; ;,a
@"CMISC Q@A@	%
	ac$Q@,a
@"CMISC A@,a
@&CSCRN 	@ ,aS(CLINES8 8Q	Cac*Q@	B9	t9QS	@ QS	A9	ac,Q@A@9	8&ac.: :,a
@0CLINESQ@	8=,ak"CMISC 	8Cac2L,aK0CLINESac49 9A@,aS6CLINESO	@ ,aS8CMISC 	A,aS:
CSCRN ac<	8%d	@ Qc	@ 9 9	:aG>QaQQQQas@acBA@;		,agDCSCRAT,aKFCUNDO : :,a[0CLINES	M,aDCSCRAT	%		@acH
acJ,aKLCSCRN 	@H,aSNCSCRN acP9 9a@acRQ@A@A@:A@<acTA@
A@	<%-	%0,	%3/2	<< <	=	A,ag6CLINES:,a_6CLINES	A,aS6CLINES;,aK0CLINES,aS6CLINES7 7A,aK6CLINES,ag0CLINESK	B,aS6CLINESFL,aK0CLINESac4A@: :,aS6CLINESPYacV,a
@6CLINES,a
@6CLINESac<6	=>L	7ij; ;klmGnbacRQ@A@A@:A@<)3acPA@
,aK6CLINES	?	,aSXCMISC : :	A9acZQ@A@9A@8	@DCac\Q@A@9A@8	@DCac^Q@A@9A@?A@87 7	8%,ac`Q@A@9A@
A@8+'         8Cac2,aK0CLINESac4A@?: :,aS6CLINES9	<%I	@ :QHDacV,a
@6CLINES,a
@6CLINESac<	89 9	BCyacbacd		!}!~!!
!!	^!!^!!5 5!!
!!!-^!}^!P^!:$CLINES!H$CLINES!B9 9$CLINES!X$CUNDO !V$CSCRAT!J$CMISC !j$CMISC !4$CMISC !^$CSCRN !8$CSCRN !`9 9$CSCRN !L$
CSCRN !n#CKGLOB!r#DOCMD !p#DOGLOB!@#DOREAD!2#GETARG!l#GETLST!>#DOOPT !<: :#LENGTH!T#INTRPT!P#DOLOG0!R#MKONU$!.#WATCH !0#SERC!6#LOADS0!D#PRINT0!F#F$MI11!N#UPDSC00 0!Z#GARBA0!\#MSWAIT!b#PROMPT!d#GETCMD!f#MESG!h#ADJUS0!t#CLRSC0!v#CLRBUF
 
"%H@0&$ INTRPT6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES		acQ	@QK	"A
		,aSCMISC acacA@A@#	) )	"	!!@!$CMISC !#QUIT$ !#RESTO0!#TTY$RS
 
"%($0&c"$ GETLST6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	@ ,aSCLINES,aSCLINESacQ	@Q	@A@"Q	@	@DC: :,aKCLINES,aSCLINES	",aSCLINES,akCLINES	@QK	@HADQK	%'5 5	%*&)QK	@HADQK	C	",aSCLINES3Qk*		9 9,agCLINES>,aSCLINES?,aKCLINES	%	@,aKCLINES,aSCLINESE9 9,aKCLINES,agCLINESO		QS	A,aSCMISC PQK	%\		QS8 8[QK	#	!}!~c!!c!,!;c!$CLINES!$CLINES! $CLINES!$CLINES! $CMISC !#GETONE
 
"%.$0&KB( GETNUM6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE < <CTXTCPATCLINES		"QK	@HADQK	CQkQK	@HAD,aKCSCRN Q[7 7,a_CSCRN ,a_CSCRN 	BQS,aKCLINESQS,aKCLINES	@HQS$: :,aKCLINESQS*	A#Q[	$	($@5	$@HADQK	A
,a_CUNIX0	C9 9QK	@H%t$QK	t%Q_	CB	($66N	$@H%QK	@H&t%QK	t&Q_	C: :	@ #>`6c	#@HC	($@i	$@HADQK	A
jr	$@H$@H%QK: :	@HADQK	t%QS		t$QS	$BAD@ QS		,aSCMISC h	acQ	@Q	@	C; ;		"/QK	@HADQK	Cac A@Q	@	"#	ac A@Q	@	"+; ;QK	'BQSac"Q	@Q	@,a
@$CMARK ,a
@$CMARK 	C		"F	'@HADQK; ;	Cac&A@Q	@	"Q	ac&A@Q	@	"YIQK	@HQS3ac(Q	@Q	@: :QSQK	@HQSf,aKCSCRN QStQK	@HADQK,agCSCRN 9 9,ag*CSCRN 	@,aK,COPT	AQK	@HADQK	%	 	%
%	%: :%	% +	%#0,ag.CUNIX0'0	%*4	%-4	%11	%: :0	@g2QK	@HADQK	%>u		"y	"@DCQk	@C	"QS			!9 9}!~!!K!
!! !#!$!-!	.!/!0!9: :!<!>!
^K!($CLINES!*$CLINES!.$CMISC !6$CMARK !>$COPT!$$CSCRN !"9 9$CSCRN !&$CSCRN !<$CSCRN !@$CUNIX0!,$CUNIX0!:#CTOI!0#OPTPAT!2#PTSCAN!8#KNSCAN !4#GETKN 
 
"%4(0&& GETONE6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE < <CTXTCPATCLINES		"@ QSacQ	@Q	@Q	@Q	@		@DC		"	#QK	@HADQK: :	C	QkQK	@HADQK	%-	%0,/QK	@HADQK	#9 9Qk	@0acQ	@Q	@A@$Q	@		@DC	#CQK	$QSK	$Q[9 9QSQG			Qg	]Z	$#`\		QS	_QK		%hQK	A: :,agCLINESk	@n		QS			,aSCMISC p			Qg	}z	"|	"5 5QS	~	"	!}!~!!     ! !+!-!$CLINES! $CMISC !#GETNUM
 
"%2&0&D
* CKGLOB6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE < <CTXTCPATCLINES"GLOB		QS		"#Q[	ADQK	%,agCUNIX08 8QK	@HADQK	C	A#	@ #Qk	@	acQ	@Q	@9 9,a
@CMARK ,a
@CMARK QSQK	@DCQK	@HADQK	$	A"	@ "9 9@CQk	@	acQ	@Q	@	C		QSOQk	@S=	$%\>9 9	%_A	%b>	%eAW5QK	@DC		$"iol	$#	nspQS< <rQK	@DCacA@,a
@ CLINESzuQK	@DCac"a@A@,aK$CBUFR$9 9	%@ &	(&@         &,ag&CLINES	@ t%,aS(CBUFR$,aK*CBUFR$	%	(&@9 9	&,ag,CLINES	@ac.A@'	A
		QS	(	-	@ )#%9	@HC	t%9 9,aK0	CBUFR$,a_CMARK 	C;8B	#A	t%,aK0	CBUFR$,agCMARK NFC9 9N	"BC	A)R	ac2A@%ac4,a
@6CTXT,a
@8CPAT	"C	A)bUM	)8 8	t%,aS(CBUFR$,aK*CBUFR$	%!	t%,aK*CBUFR$	%&	%,ag$CBUFR$v	@ t%9 9,aS(CBUFR$mu	ac"A@	A@QK	(	!}!~!!	!!6 6'!G!X!g!x!0$CLINES!6$CLINES!*$CLINES!B$CPAT!@; ;$CTXT!.$CBUFR$!4$CBUFR$!2$CBUFR$!:$	CBUFR$!$$CMARK ! $CUNIX0!(#DEFALT!>#MATCH  !&#OPTPAT!"#GETKN !8#INTRPT!,#MESG!<#GTXT
 
"%4*0&
T*4 DOCMD 6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES			QS	acA@"	A
	QK	@HADQK	#QwQK7 7	%	%ac,a
@CLINES,a
@CLINESQwQK	Cac; ;,a
@CLINES,a
@CLINESac*QwQGQac,a
@CLINESQ	@QS	QwQK9 9	CAac,a
@CLINES,a
@CLINESac ,a
@CLINES		QS	Hac,a
@CLINES9 9,a
@CLINESQwQK	CVac"Q	@	cac,a
@CLINES,a
@CLINES,aKCLINES; ;	A			,aS$CMISC hrQwQK	%~	%}QwQK	C7 7ac,a
@CLINES,a
@CLINESac,aKCLINESac&,a
@(
CSCRN ,aS(
CSCRN 8 8,a_CLINES	C,aKCLINES,aS(
CSCRN QwQK	Cac*,a
@CLINES< <,a
@CLINES'QwQGQac,a
@CLINESQ	@QS		%?,aKCLINES	$ac,: :,a
@CLINES,a
@CLINESQ	@	,aKCLINES,a_CLINES	B$A,aSCLINES>vQK9 9	B%ac.Q	@A@%A@&Q	@		@DCSac,a
@CLINES,a
@CLINESac,,a
@CLINES: :,a
@CLINESQ	@		@DC,aK0COPT	Auac2,a
@CLINES	A
yac2,a
@CLINES; ;,aSCLINESdac,a
@CLINES,a
@CLINES,aKCLINES	A			,aS$CMISC < <QwQK	%	%QwQK	Cac,a
@CLINES,a
@CLINES9 9ac&QwQGQac4,a
@CLINES	%acA@%Q	@QS	Qk	@ac6; ;Q	@Q	@A@$Q	@		BC		QS	RQK		@DCBac.Q	@Q	@A@&Q	@		@DCZ9 9ac,a
@CLINES,a
@CLINESac8A@$QS	g,aK:CUNIX0	@HCyQk	@: :ac6Q	@Q	@A@$Q	@		BC		QS	
QK		@DCtac.Q	@Q	@A@&Q	@		@D; ;	Cac,a
@CLINES,a
@CLINESac<A@$QS	Qk	@QK	@HADQK	C; ;			QSQwQS,aK:CUNIX0	AQK	BAD	QSCQK	BAD	QSKQK: :	@DAD	QSQK	AD	QSQK		AD@ QS		
,aS>CMISC 8	A'Q[	(; ;	((@q	(@HADQK	A
,a_@CUNIX0	CQK	@H%t(QK	t%Q_	C~	((r9 9r
	(@H%QK	@H)t%QK	t)Q_	C	@ 'zr	'@HC	((9 9	@%	(@HADQK	A
&.	(@H(@H%QK	@HADQK	t%QS		t(QS	(BAD@ : :QS		
,aS>CMISC $k	acBQ	@Q	@	@DC,acDQ	@Q	@Q@A@*	@DCSQK: :	B%ac.Q	@A@%A@&Q	@		@DC`ac,a
@CLINES,a
@CLINESacFQ@A@*Q	@: :QS	q,aK:CUNIX0	@HC{zQk	@QK	@HADQK	C		QSQw; ;QS,aK:CUNIX0	AQK	BAD	QSQK	BAD	QS'QK	@DAD	QS: :QK	AD	QSQK		AD@ QS		
,aS>CMISC 	A'Q[	(	((@M	(9 9	@HADQK	A
,a_@CUNIX0	CQK	@H%t(QK	t%Q_	CZ	((NNf9 9	(@H%QK	@H)t%QK	t)Q_	C	@ 'VxN{	'@HC	((@	(: :	@HADQK	A

	(@H(@H%QK	@HADQK	t%QS		t(QS	(BAD@ QS		
9 9,aS>CMISC G	acHQ	@Q	@,a
@JCPATA@A@+	@DCacLQ	@Q	@Q@A@: :	@DC5QK	B%ac.Q	@A@%A@&Q	@		@DCBac,a
@CLINES,a
@CLINESacN; ;Q@A@+QS	SQk	@acPQ	@Q	@Q@A@	@DCbQK	B%ac.Q	@A@%A@&< <Q	@		@DCrac4,a
@CLINES	%acA@%,a
@CLINESacRQ@QS	Qk	@ac9 9,a
@CLINES,a
@CLINESacTA@A@Q	@Q	@A@,Q	@		@DCac.Q	@Q	@A@&: :Q	@		@DC/acVA@,Q	@	QS	<Qk	@,aKXCLINES	A
		,aS$CMISC EL9 9acZQ	@Q	@A@Q	@		@DCQK	@H%ac\Q	@A@%Q@	@DCac^Q@A@: :,a
@`CFILE A@acbQ@A@acdacfachA@Q@QS		@ ,aS(
CSCRN ,aKjCLINES: :ac&A@,aSCLINES	@ ,aSlCMISC l		QS	]P,aKXCLINES	A
		9 9,aS$CMISC ac\Q	@Q	@Q@	@DCac^Q@A@,a
@`CFILE A@acb< <Q@A@         	QS	.#ac\Q	@Q	@Q@	@DCBac,a
@CLINES,a
@CLINESach9 9,a
@CLINESQ@QS	MQk	@@ ,-acTA@A@Q	@Q	@A@,A@.	,AacT6 6A@A@Q	@Q	@A@-A@.sQK	@H%ac\Q	@A@%Q@	@DC\acA@; ;,a
@jCLINESacn,a
@CLINES,a
@CLINESQ@A@,A@-QS	QwQK	C%ac7 7A@,a
@pCSCRN acr,a
@CLINES,a
@CLINESQS	,,aKpCSCRN ,a[tCSCRN ; ;,a_vCSCRN ac&,a
@jCLINES	%	acA@A@%,aKCLINES	A			,aS$CMISC ;; ;PQwQK	C,aKCLINES,aSpCSCRN ,aSCLINES,aS(
CSCRN 		QS	[T9 9Qk	@acxQ	@Q	@A@/A@	%xgQK	@HADQK	CwaczA@/Q	@	9 9Qk	@acxQ	@Q	@A@/A@	%QK	@HADQK	Cac,a
@CLINES7 7,a
@CLINESac|A@/QS	 ac2,a
@CLINES	$acA@$A@$acr,a
@CLINES9 9,a
@CLINESQS	-QwQK	CAac~		QS	Hac,a
@CLINES,a
@CLINES; ;acQ	@Q	@QS	NQk	@,aKXCLINES	A
		,aS$CMISC ]d	acZQ	@Q	@9 9A@Q	@		@DCQK	@HADQK	C		QS	~		QS	uhQk	@; ;,aKXCLINES	AacQ	@Q	@Q	@			,aS$CMISC Qk	@QK	@HADQK: :	0ac,a
@CLINES,a
@CLINESQk	@acQ	@Q	@QS	%	0%<&	%: :?&		,aS$CMISC 7	in docmd: can't happen. C,aK:CUNIX0	@HCacC@DT: :Qk	@ac,a
@CLINES,a
@CLINESacQ	@Q	@QS	B,aK:CUNIX0	@HCY: :o		,aS$CMISC j	#%y.	%|k	1LF<B: :8iTFcBChO&^C-W]u!"#: :8$%&iTF(cBChO&^C-W]-u: :>ABCC		,aS$CMISC t
QK		@DC	@ ,aS
CMISC LQK		2	!}9 9!~!!!T!!	T!        !                                 ! T!
!
!9 9 !!!%!&!+!/!9!:!>!B!D!b!d!e!9 9q!T!6$CLINES!8$CLINES!v$CLINES!2$CLINES!$CLINES!h$CPAT!~$CFILE : :!
$CMISC !B$CMISC !($CMISC !\$CMISC !N$COPT!$CSCRN !$CSCRN !$CSCRN !F< <$
CSCRN !X$CUNIX0!^$CUNIX0!<#APPEND!r#CKCHAR!L#CKP !x#CKUPD !Z#COPY!J#DELETE!#DOMARK9 9!#DOOPT !#DOPRNT!#DOREAD!l#DOTLIT!t#DOUNDO!#DOWRIT!z#GETFN !#GETKN !T#GETONE!f9 9#GETRA0!b#GETRHS!n#GETSTR!p#JOIN!j#MAKSET!V#MOVE!P#NEXTLN!`#OPTPAT!R#PREVLN!d#SUBST 9 9!"#DRAWB0!&#DOSHE0!.#INTRPT!0#DEFALT!4#ADJUS0!:#UPDSC0!>#SAYNUM!@#OVERL0!D#F$MI11!H4 4#WARND0!|#SCOPY !#MESG!#CLRBUF!#SETBUF!#UNIQU0!#WHERE0! #DOHELP!$#ERROR 
 
"%B40&" DEFALT6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES	,aKCLINES	AQK,aSCLINESQK,aSCLINES		! $CLINES!$CLINES!$CLINES
 
"%("0&6>$ MSWAIT9 9"
=gossip= "=user=""*=pid="*Messageac29 9a@A@	%	ac4a@A@	"Cac4a@"A@	"	ac2A@A@	"%: :$ac6A@"ac8a@*A@		#	ac8A@A@		!}6!!6! 6!6#FOLLOW!8#OPEN!:#CLOSE !<#MESG
 
"%$$0&" RELINK6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	QKQw,aSCBUFR$QK	Qw,aSCBUFR$		!$CBUFR$! $CBUFR$
 
"%."0&" WATCH 0 0	acA@Q@	@ QacQ@A@		!!!#DATE!#MESG
 
"%,"0&

&( MESG6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE ; ;CTXTCPATCLINES	A"	("@	",agCSCRN 	@t",aKCSCRN Q_	C8 8		"#	(#@	#,agCSCRN 	@t#,aKCSCRN 	Qg$#	@ t#9 9,aSCSCRN 	"@H"$	A$"/	t",aK~CSCRN 	A0*5acQ	@	@D$@HC; ;	#"$C	"%D	A%	&%J	%,agCSCRN P	%,agCSCRN 6 6U	t%,aKCSCRN 	A
V	(%RR[	%&	(&@a	t&,aKCSCRN 	A9 9,aKCSCRN 	$&b	@hn	&%$CKQtG	$%,a_CSCRN 	C	A%&; ;	(&@~	&,agCSCRN 	@t&,aKCSCRN 	A
,aKCSCRN 	C9&AD,aGCSCRN Q9 9acQ	@,a
@CSCRN A@%	t&,aKCSCRN 	t%,aSCSCRN 	(%@	%&	(&@9 9'	&,agCSCRN 	@@ t&,aSCSCRN (-zacA@,a
@CSCRN A@%	%B': :acQ	@,a
@CSCRN A@'A@	$%@H'acA@,a
@CSCRN A@'	%&	(&@W; ;	$%@Hac ,a
@CSCRN 	&CQK	t&,aSCSCRN Xc?	A%t%,aKCSCRN 	A: :acA@,a
@CSCRN A@%p	A%,agCSCRN kk		!! !.; ;!$CSCRN !$~CSCRN !$CSCRN !$CSCRN !$CSCRN !#LENGTH! #LOAD!"#LOADS0!$#F$MI11
 
"%0(0&$ NEXTLN6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 3 3CTXTCPATCLINES	QK	B",a_CLINES	C	@ "	"	!$CLINES
 
"%($0&$ PREVLN6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 1 1CTXTCPATCLINES	QK	@H"A,aKCLINES	"	"	!$CLINES
 
"%($0&

i<& SERC6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE < <CTXTCPATCLINES"=home=/.serc	aca@A@	"C					#ac : :	Q@A@"A@	%	#%Q	%!	%$$	A$,aK"CLINES9 9	%ac$Q@A@$A@#	@DCac&Q@A@$A@#	@DCac(Q@A@$A@%A@#: :?ac*Q@A@$A@A@#J4	#Cac,,aK.CLINESac0A@%,aS"CLINES8 8ac2A@"		!}i!!!i!i!
!#i!i!*< <$CLINES!6$CLINES!&#OPEN!(#GETLIN!,#GETLST!.#CKGLOB!0#DOGLOB!2#DOCMD !4#PRINT0!8#F$MI11 !:#CLOSE 
 
"%&&0&