m$( ADJUS06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE < <CTXTCPATCLINES	,aKCSCRN Qg	@,aKCSCRN ,a_CSCRN ,a[CSCRN Q_9 9	C	A"	("@	",agCSCRN 	@t",aKCSCRN 	BC!	"5 5,agCSCRN 	@,aKCSCRN 	t",a[CSCRN 	@H#&,aKCLINES	B#/< <,aKCSCRN 	"	"@H"7	"A	t",aKCSCRN 	BC=8C	"A,aKCSCRN : :	t",a[CSCRN 	@H$G	@ $OacA@	%,aKCSCRN ,a_CSCRN 	&QKQ_7 7	&CQK	&,aSCSCRN b	%@HC	#Qgl	@$	Qgxxp	#: :,a[CSCRN ,a_CSCRN 	M=,aSCSCRN w	%@HCQK	$#	,aKCSCRN 9 9,a_CSCRN 	BM=&#Q_	$&
QK,aSCSCRN 	%@HC	$Qg!< <%,aKCSCRN ,a_CSCRN 	&BM='QK	$$'&4QK	&,aSCSCRN 5QK< <Q[,a[CSCRN ,a_CSCRN 	M=,aSCSCRN ;h	%@HC,aKCSCRN ,a_CSCRN 9 9	&,a[CSCRN ,a_CLINES	CK,aKCLINES	&,aSCSCRN V	A,agCSCRN b: :`,aSCSCRN a,aKCSCRN ,ag 
CSCRN h,aS 
CSCRN i         	!m!8 8m!$CLINES!$CSCRN !$CSCRN !$CSCRN !"$
CSCRN !$CSCRN !$CSCRN ! $CSCRN ! #HWINS0
 
"%.(0&D$ HWINS06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	,aKCTERM 	"	A#		,agCOPT	@@ #		A#	9 9	"L,2 !"#$%'): :$-0135789:;=>	@ #	!	`D!$COPT! $CTERM 
 
"%($0&	\
& UPDSC06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES"1"$".  ->".  ->" 1; ;""$ac$,aK&CSCRN 	"ac(A@"	#,aK*CSCRN 	$	($@	$,ag,CSCRN 9 9	@",ag.CLINES	@@HCac0A@A@$A@A@ac2A@A@$A@9 9ac0A@A@$A@,a
@4CSCRN 	",a_6CLINES	Cac0a@A@$A@A@; ;?	"@HCac0a@ A@$A@A@N	",a_.CLINES	Cac0a@"A@$A@: :A@^,aK8COPT	A	$%m	@,a[:CSCRN 	@HQ
	@ Qac0Q@
A@$; ;A@A@pac<A@"Q@A@ac0Q@A@$A@A@iYJ	t#,aG>	CBUFR$Q: :ac2Q	@A@$A@ac2A@A@$A@,aK@
CSCRN 	$"	@acBA@#	t#,aKDCBUFR$9 9,agFCOPT	@ac0A@A@$A@,a
@4CSCRN :,awFCOPT,aGHCTXTQ5 5ac0Q	@A@$A@,a
@4CSCRN F/:	("@t#,aKJCBUFR$	#,aK.CLINES9 9,aS@
CSCRN ,aK&CSCRN ,aSLCSCRN ,aK,CSCRN ,a_*CSCRN 	B,aSNCSCRN 	A%9 9	(%@o	%,agNCSCRN 	@,a[LCSCRN 	@H,ag.CLINES	@%t%,aSPCSCRN p9 9|			t%,aSPCSCRN pu		!	!!	!!!!!		8 8!	!|	!@$CLINES!8$CLINES!R$CTXT!T$CBUFR$!N$CBUFR$!H$	CBUFR$!B7 7$COPT!P$COPT!>$CSCRN !4$CSCRN !6$CSCRN !0$CSCRN !J$
CSCRN !D$CSCRN !X5 5$CSCRN !V$CSCRN !Z$CSCRN !2#GETIND!.#FIXSC0!:#LOADS0!<#LOAD!F#ITOC!L#GTXT
 
"%<&0&
]$* FIXSC06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES,aKCSCRN ,a_CSCRN 	B,a_CSCRN 	CacA@	A
9 9			A"	("@	",agCSCRN 	@t",aKCSCRN 	%!,a[CSCRN 6 6	@H#,a_CSCRN 	C ,aKCSCRN ,a_CSCRN ,a[CSCRN 	#C(1		t"9 9,aSCSCRN 2,aKCSCRN ,a_CSCRN 	t",a[CSCRN ,aSCSCRN 	A"$: :	($@E	$,agCSCRN 	@",agCSCRN 	@t",aKCSCRN 	BCP	("M< <MW	",agCSCRN 	@$t",agCSCRN ^gd	t$QS	("FFf		t$QS; ;FK	@ %$A"	("@w	",agCSCRN 	@t",aKCSCRN 	Qg	%
9 9		(%@
	t"QK	BCx	($@x}	$@D%C		,aKCSCRN 	"$": :	A		$A	"%	@ &	(&@)	"A	t",aKCSCRN 	BC.	"@H"*4< <	@ '	('@;	$A	t$QK	BC@	$@H$<F	&$'PN	'#,aKCSCRN 6 6	"'(	acA@(A@#O	"A 	t",aKCSCRN 	%f 	$A 	t$QK	t": :,a_CSCRN 	C 	"@H"$@H$]&	A"$,aKCSCRN 	$"~	$$	$: :	)@ &	(&@	",agCSCRN 	@t",aKCSCRN 	BC	("			@ '6 6	('@	$,agCSCRN 	@t$QK	BC!	($(	'$&1/	&#9 9,aKCSCRN 	)&@H(	ac A@(A@#0	",agCSCRN {	@t",aKCSCRN 	%J{9 9	$,agCSCRN {	@t$QK	t",a_CSCRN 	C{	("@($??		!!9 9]!$CSCRN !$CSCRN !$CSCRN !$CSCRN !$CSCRN !$CSCRN !#HWINS0! #DELLI0 !"#INSLI0
 
"%^*0&,$ SENDD06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES"	QK	MQ,aKCOPT	MQ;	AEA?	@9 9	"	$"aca@A@	""                           	"Aaca@A@"!		!
) '!$COPT!#TNOUA 
 
"%*$0&& GETIND6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	,aKCBUFR$	"@ #	t",aKCBUFR$	"(#@	#Qg          "$	!$CBUFR$!$CBUFR$
 
"%*&0&$ GETTXT" "	acQ	@	"acA@"	"#	!#GETIND!#GTXT
 
"%($0&

$ GTXT6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES	Qw,aGCBUFR$	QacQ	@,a
@CSCRATQw,aGCBUFR$5 5Qac,a
@CTXTQ	@,a
@CSCRAT	@H"	!$CTXT!$CBUFR$!$CBUFR$! $CSCRAT!#READF !#SEEKF 
 
"%*$0&8& READF 9 9	QGQ
acA@Q	@Q@
Q	@A@A@"A@#	#A	"Q_	C	9 9Fatal scratch file read error.acC@	"$	!5!#PRWF$$!#ERROR 
 
"%2&0&/$ SEEKF ; ;	Fatal scratch file seek error.AQacA@Q	@Q@A@Q	@A@A@"	"A
* *acC@'		#	!~/!/!!#PRWF$$!#ERROR 
 
"%,$0&8& WRITEF9 9	QGQ
acA@Q	@Q@
Q	@A@A@"A@#	#A	"Q_	C	8 8Fatal scratch file write error. acC@	"$	!6!#PRWF$$!#ERROR 
 
"%2&0&E8( CLEAR06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	,aKCTERM 	"	A#	"@H$L,: :8: :&,aKCTERM 	@HCQK,agCSCRN <A	A#: :B	@ #E	@ %QK	&QK	C9&AD	,agCSCRN W,aSCSCRN 	A$#^[: :	%]acQ	@A@&acA@_V	A&,agCSCRN qLL	%@HCacQ	@: :Q	@,aKCTERM 	'*acA@acA@acA@acA@acA@acA@: :acA@acA@,ak CSCRN 	@A,aS"CSCRN acA@acA@(acA@; ;acA@1acA@	A&acA@		A&%
K@@:acA@KacA@acA@9 97PacA@YacA@^acA@cacA@hacA@acA@acA@ac9 9'A@macA@acA@acA@~acA@acA@~	'L-: :8) "#2;LQQQQ$i: :nQQd_QZ2t		!!
3!	!!
!!9 9!!!!!! !        0!I!K!L!T!Z![E; ;!$$CTERM !($CSCRN !&$CSCRN !.$CSCRN !4$CSCRN !6$CSCRN !*#POSIT0!,#SEND!0#T1OU !2#SENDD0
 
"%.(0&

B $ LOAD6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES	QK	"%	%	
,aKCOPT	"QK	%9 9,agCSCRN 	@QK	%,agCSCRN 	@QK	C9Q[: :	AD,aKCSCRN 	$".!acQ	@Q	@QK	C9Q[	AD",aSCSCRN acA@"-		7 7!B! !B!$COPT!$CSCRN !$CSCRN !$CSCRN !#POSIT0!#SEND
 
"%.$0&$& LOADS06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	QK	%,agCSCRN 	@QK	%        		": :	A#	(#@	#@HADQK	A
,aKCSCRN 	$"!"	#@HADQK	$%.: :.	%-/0,aKCOPT	$1QK	C9"AD$,agCSCRN ?,aSCSCRN : :acQ	@A@"acA@$>	("#,aKCSCRN Qg		@"CRacQ	@A@"; ;V,aKCSCRN acQ	@		%	("@e	"$%	@QK	C9"AD	,agCSCRN v6 6f,aSCSCRN acQ	@A@"acA@fj]		!! !!1 1$COPT!$CSCRN !$CSCRN !$CSCRN !#POSIT0!#SEND! #CLEAR0!"#F$MI11
 
"%2&0&" PROMPT6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	acQ	@,a
@CSCRN A@A@		!!!$CSCRN  !#LOADS0
 
"%&"0&