$ CLOSEF) )	acA@A@A@Q	@A@"A@"		!!!#SRCH$$
 
"%($0&" CLRBUF6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	A,agCLINES
acA@,a
@CLINESac,a
@CSCRAT< <ac,a
@CSCRAT		!!$CLINES!$CSCRAT!$CSCRAT!#SVDEL !#CLOSEF!#REMOVE
 
"%""0&H.& MAKSCR9 9"=temp=/se=pid=	ac a@A@Q@A@	"	#	(#@	#%9 9	@t"QS	@ QSac"Q@A@	$%%ac$A@$QSac Q@A@Q	@A@		< <	can't create scratch file.6ac&C@7!}H!H!0!9H!!&#SCOPY  !(#CREATE!*#MAPFD !,#ERROR 
 
"%,&0&52$ SETBUF6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 6 6CTXTCPATCLINESac,a
@CSCRAT,a
@CSCRAT	@,aSCSCRAT	@ ,aSCLINES; ;,aSCLINES	A,aSCBUFR$		,aSCBUFR$,aS CUNDO 	@ ,aS"CUNDO ,aS$CSCRATac&9 9A@A@A@"ac(A@"A@"A@"A@"	@ t",aS*	CBUFR$	",aS,CBUFR$		!!: :!5!$CLINES!$CLINES! $CBUFR$!"$CBUFR$!0$CBUFR$!.$	CBUFR$!$$CUNDO !&4 4$CUNDO !$CSCRAT!$CSCRAT!$CSCRAT!($CSCRAT!#MAKSCR!*#MAKLIN!,#RELINK
 
"%$$0&T.& SPINJ06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 8 8CTXTCPATCLINES	acA@"	#"BC		,aSCMISC 	#		,aKCSCRAT	t"8 8,aSCBUFR$QK	B$,aSCBUFR$	@ ,aSCBUFR$		,aS	CBUFR$ac,a
@CSCRAT9 9,a
@ CSCRAT	ac"Q	@A@$,a
@ CSCRAT	$M,a[CSCRAT,aSCSCRAT,ak$CLINES	@A: :,aS&CMISC Qw,aK(CBUFR$	% ac*Q	@A@"A@"A@%ac*A@"A@%Q	@A@"!7 7T! T!&$CLINES!*$CBUFR$!$CBUFR$!$CBUFR$!$CBUFR$!$	CBUFR$!"3 3$CSCRAT!$CSCRAT!($CMISC !$CMISC !#ALLOC ! #SEEKF !$#WRITEF!,#RELINK
 
"%0&0&54$ DOLOG06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES"=home=/se.logout	                                                                                                                   aving buffer because of pending l: :ogout.ac"C@ac$A@,a
@&CLINESa@A@A@ac(ac*,a
@,CTTYac.A@9 9ac0A@"		!!5!($CLINES!.$CTTY!$#REMARK!&#DOWRIT!*#CLRBUF!,#DUPLX$ !0#BREAK$!2#CNSIG$
 
"%($0&>* DOREAD6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 6 6CTXTCPATCLINES"reading	QK	",aKCFILE 	AacQ	@; ;,a
@CFILE A@ac,a
@CFILE A@	acQ	@A@	#C		$	,aS CMISC 9 9	"Bac",a
@$
CSCRN ,aS$
CSCRN ac&A@"	%	$	aca@A@		&ac(: :	Q@A@#A@	'@ (	((@H	'%O	&@H&A	ac*A@)	A
		$NY: :		&Sac,Q@A@'A@%	%BC		$\jac(Q@A@#A@	'Imac.9 9	A@#ac0A@(	(",aS2CLINES	ac4Q	@A@(%	$	!}!~!!: :!!d!!:$CLINES! $CFILE !($CMISC !,$
CSCRN !0#GETLIN!&#OPEN5 5!4#SPINJ0!.#GETIND!2#INTRPT!"#CTOC!$#MESG!*#F$MI11!6#CLOSE !8#SAYNUM!<#SVINS 
 
"%0*0&CP* DOWRIT6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES"writing		",aKCLINES	A			,aSCMISC ; ;QK		@HCacQ	@A@	#acQ	@,a
@ CFILE 	%!QK	%&; ; ,aK"CMISC 	%+%ac$Q	@A@A@A@A@A@A@A@	A
*>ac&: :Q	@A@	#?		,aSCMISC 		,aS"CMISC 	"	G	#C		,aSCMISC 9 9S			"ac(a@A@QK		@HCac*A@#d		
$ac,Q	@	%QK	&: :	t%,aK.CBUFR$	%(&@s	&Qg	@$@H$A	ac0A@'	A
		"}			
$; ;	ac2A@%ac4,a
@6CTXTA@#tac8A@#	(%"ac:A@A@(!ac<A@#9 9	&Q_	)ac>A@)	A	Qg:7	&,a[@CLINES	C9	@ ,aSBCMISC >W
: :N!}!	~C!!!!C!                                 !!C!
dC!wC: :!$$CLINES!L$CLINES!B$CTXT!,$CFILE !:$CBUFR$!N$CMISC !&$CMISC !.$CMISC !29 9#CREATE!(#OPEN!D#MAPFD !*#EQUAL !0#FILTST!8#GETIND!<#INTRPT!4#MESG!6#WIND!>#GTXT!@ #PUTLIN!F#FORCEW!H#CLOSE !J#SAYNUM
 
"%:*0&-$ CKUPD 6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	acA@A@Q	@Q	@A@"Q	@	QS		"A,aKCMISC 	@H: :	C,aKCMISC Qg		QS			,aSCMISC QK,aSCMISC QK		#0 0		!}-!-!!-!$CMISC !$CMISC !$CMISC !#CKCHAR
 
"%0$0& ( GETFN 6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES		"QwQK	CQK	@D##@HADQK	C	(#; ;	A$	($@(#@	#@H%t%QK	%)	$@H&QK	t&QS(	$@HAD@ QS: :	A$$:		";	QwQK	C,aKCFILE 	A
Eac,a
@CFILE A@9 9Q	@A@		"IQwQK	C		,aSCMISC ]		,aSCMISC aV; ;>	"@DC,aKCFILE 	AhacQ	@A@,a
@CFILE A@ac,a
@CFILE A@7 7l	"	!}!~!!!!!
! !$CFILE !                                                                    CMISC !#SCOPY !#MESG
 
"%2(0&|l( SENDM06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES"=temp=/se.ms=pid=""=gossip=/***3,,0i; ;"4=gossip=/*s	QK	A			,aS@CMISC 		"		A#acBQ	@9 9A@#	$#%	$%	@@HC		,aS@CMISC 		"		acDQ@A@9 9a@"A@$acFQ	@	C		,aS@CMISC 		"	7acDQ@A@a@4Q	@: :06acHA@Q@>acHA@Q@dacHA@Q@`acHA@	Q@
acJQ@
Q
acLa@A@; ;	%C		"	o	*2nFrom *s (*s) at *,5s on *s@.*2n. sacNA@%C@tQ@>Q@`Q@dQ@
9 9acPA@%acRQ	@Q	@a@A@A@
	%
'acTa@		"	&	acVa@A@	%: :	C		"	7	@ #	(#@=	#%BacVQ@A@	&%NacXA@&acZ: :A@%A@&acPA@&acPA@%acTa@		"	Mac\A@>CacPA@%acTa@		9 9,aS@CMISC 		"	!}!~z!
!!!!!	z!
z!< <     z!%!&!*z!zjt!N$CMISC !X#MAPUP !d#OPEN!Z#CREATE!T#VFYUSR: :!P#CTOI!`#DOWRIT!R#ENCODE!V#DATE!\#PRINT !^#CLOSE !b#REMOVE!f#WIND!h#FCOPY !j#SLEEP$
 
"%(0&lV$ RECVM06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES"=gossip=/=user=" =gossip=/*=pid="09 9No messagesac<a@A@Q@A@ac>Q@A@	"Cac<a@ A@9 9Q@A@ac>Q@A@	"	"Cac@a@0A@(acBA@"	BCacD9 9A@"acFQ@6acHA@	#acJA@"A@#acLA@#acDA@"acNQ@A@	": :	%]acJA@#A@"acDA@"\acPA@#?/		!}l!!l!B#OPEN< <!R#CREATE!L#MKTEMP!F#DISPL0!@#SCOPY !D#MESG!H#CLOSE !J#REMOVE!N#FCOPY !P#REWIND!T#RMTEMP
 
"%$$0&