

V,( COPY6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 5 5CTXTCPATCLINES		"acQ	@	#t#,aKCBUFR$	$,aKCLINES	A			: :,aSCMISC 		"QK,aSCLINESac,a
@CLINES	%,aKCLINES	&	(&9 9	@"	&,agCLINES	@	acA@%ac,a
@ CTXT	%
5ac"A@'	A45 5:		"(;	%#C	$%#B	t%,aKCBUFR$	%#>QK	Bac$6 6,a
@&
CSCRN ,aS&
CSCRN 	"	!}!~V!     V!$CLINES!$CLINES!: :$CLINES!$$CTXT!$CBUFR$!$CMISC !*$
CSCRN !"#INJECT!#GETIND!&#INTRPT! #GTXT!( #F$MI11
 
"%,(0&$ CPROW 6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	A"	("@	",agCSCRN 	@QK	C9"AD,aGCSCRN * *QacQ	@Q	@A@"			!$CSCRN !$CSCRN !#LOAD
 
"%,$0&
L& DOHELP6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES"=doc=/se_h/elp" =doc=/se_h/",*s_9 9unix	QK	@HADQK	C	Qk	QK	@HADQK	Cac49 9a@A@Q@
A@ac4a@ A@Q@
A@	"B#ac4Q	@Q	@Q@
A@#	"": :	@ t"QS	!ac6Q@
A@a@,Q@
,aK8CUNIX0	@HCac:Q@
A@A@A@A@: :	A@A@A@	@HCMac4Q@
A@Q@
A@b		QSac<Q@
A@	$C		9 9QS		,aS>CMISC yac@A@$acBA@$		!}!~
!!
: :!
!!
! 
!F$CMISC !@$CUNIX0!D#OPEN!<#SCOPY !B#FILTST!>#ENCODE !H#DISPL0!J#CLOSE 
 
"%0&0&Tj( DISPL06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES" M O R E  T O  C O M E "(Enter o- to9 9 restore display	A,agDCSCRN ,a_DCSCRN ,a[FCSCRN acH9 9A@,aSFCSCRN 	A,aSDCSCRN 	@ ",aKDCSCRN 	#	(#@,aKJCSCRN 	#9 9	CacLQ@Q	@,a
@NCSCRN 	BC	A" +,akDCSCRN 	@,akFCSCRN 	@9 9acPQ@A@#A@,a
@NCSCRN .	"AacRa@,a_NCSCRN 	M=A$A%: :	(%@O	%$$	@acTA@A@#A@%PT	A$	($@(%@a	t$	aGQQK	A
7 7acTQ	@A@#A@%b	(%@n	%,agNCSCRN 	@acTA@A@#A@%x}9 9,akDCSCRN 	@,akFCSCRN 	@(#@B	A%acTA@A@#A@%	A%,agNCSCRN !; ;                                            akDCSCRN 	@,akFCSCRN 	@,aKVCLINES,agFCSCRN 
+acXA@,a
@VCLINES7 7,,aKFCSCRN ,agZCLINES	:8ac\,a
@VCLINES,aSZCLINES9,aKFCSCRN : :,aS^
CSCRN 	ac`a@(A@	"@HC		&	M		&	!~!T!!!6 6!
T!*!-T!b$CLINES!^$CLINES!V$CSCRN !L$CSCRN !R$CSCRN !N; ;$CSCRN !f$
CSCRN !T#GETLIN!Z#LENGTH!P#F$MA11!X#LOADS0!\#LOAD!`#ADJUS0!d#F$MI11!h#MESG
 
"%.(0&2"& DOMARK6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE ; ;CTXTCPATCLINES	,aKCLINES	A			,aSCMISC 		"ac,a
@CLINES; ;	#,aKCLINES	$	t#,aKCBUFR$	#($@	$,agCLINES	@acA@%	A
9 9		"	$QK	t#,aS	CBUFR$		"
	"	!}!~2!     2!$CLINES) )!$CLINES!$CBUFR$! $	CBUFR$!$CMISC !#GETIND!#INTRPT
 
"%*&0&$82. DOOPT 6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES"UNIX!"+3!"7+3"C9 9ASE	Qk	@	"QK	@HADQK	#	failed global substitutes continue. 9 9QwQK	C		"A,a_$	COPT,aS$	COPT	@HC
ac&C@1	failed globa: :
l substitutes stop. 7ac&C@86',aK(CLINES	A
		,aS*CMISC LP	no9 9t saved.UQwQK	C		",aK,CMISC 	@HC
ac&C@Vhac&A@m< <aTQk	@QK	@HADQK	C,aK(CLINES	A
		,aS*CMISC rac.; ;		"~ac0A@A@Q	@Q	@A@$A@%	@DCQK	@HADQK	Cac2Q	@: :Q	@Q@A@	QK	@HADQK	Cac4Q@,a
@6CLINES,a
@8CLINES	"@DC	$5 5	ADac:,a
@6CLINES,a
@8CLINESA@%	"G8%		"QwQK	&8 8,aK<CUNIX0	@HC^_	@ ,aS<CUNIX0		
,aS>CUNIX0		,aS@CUNIX0		8 8,aSBCUNIX0		,aSDCUNIX0`	A,aS<CUNIX0		,aS>CUNIX0		,aS@CUNIX0		; ;,aSBCUNIX0		
,aSDCUNIX0pacF,a
@<CUNIX0,aK<CUNIX0	@HCacHa@A@: :Q	acHA@A@Y	&A
Z	%Z	                'Laq	&'La#; ;q+		,aS*CMISC 		"Qk	@,aK(CLINES	A
		,aS*CMISC 29QK: :	@HADQK	CacH,a
@JCOPTA@		"FQK	@HADQGQ
acLQ	@
	": :	@DCacNQ	@Q	@,a
@JCOPTA@_	acNa@A@,a
@JCOPTA@jO=7 7Qk	@,aK(CLINES	A
		,aS*CMISC u|QK	@HADQK	CacP: :,a
@RCOPT		"		acTQ	@Q	@	%QK	@HADQK	C	%A	%#%6 6		"%,aSRCOPT&		,aS*CMISC , Qk	@,aK(CLINES	A
		; ;,aS*CMISC 07QK	@HADQK	CacP,a
@VCOPT		"D	acTQ	@Q	@6 6	%QK	@HADQK	C	%%aa	%`	@	"%,aSVCOPTb		; ;,aS*CMISC i[K;Qk	@,aK(CLINES	A
		,aS*CMISC mt	acXQ	@Q	@: :A@(A@)	BCacHA@A@	A,agZCSCRN ,a_ZCSCRN ,a[\CSCRN ac^9 9A@,aS\CSCRN 	A,aSZCSCRN ,aK\CSCRN ,aS`
CSCRN 		"	)%)9 9QK	@HADQK	C(	(,a_\CSCRN 	B*,a[ZCSCRN 	+,agbCSCRN <	*%: :CC=	+,aSZCSCRN 	(B,aS\CSCRN 	A%,aKZCSCRN 	@H,acdA@A@,A@%	A7 7	%,agfCSCRN _KK,aKhCLINES,ag\CSCRN 
cacjA@,a
@hCLINESd7 7,aK\CSCRN ,aglCLINES	rpacn,a
@hCLINES,aSlCLINESq		"B		9 9,aS*CMISC z1$x,aK(CLINES	A
		,aS*CMISC ~QwQK	C9 9	A,a_pCOPT,aSpCOPT		",aK(CLINES	A
		,aS*CMISC Qw9 9QK	C		"A,a_r	CSCRN ,aSr	CSCRN ,aKtCSCRN 	C		,aStCSCRN 		7 7,aSvCSCRN 0		,aStCSCRN 		,aSvCSCRN 7$,aK(CLINES	A
		: :,aS*CMISC >BQwQK	C,aKxCOPT	A
ac&A@ Qac&A@!V9 9		"MQK	BADQK	%g		",aS*CMISC fQwQK	#C		9 9	"@ ,aSxCOPTqQwQK	$C		"	%,aSxCOPT~		",aS*CMISC : :wj]FQk	@,aK(CLINES	A
		,aS*CMISC QK	@HADQK	C9 9,aKzCOPT	A
ac&A@& acP,a
@zCOPT%		"QK	@HADQK	': :	CQwQK	C5	@ ,aSzCOPT		"<	acTQ	@Q	@	%QK	@HADQK5 5	C	%A	%	UW,aSzCOPT		"X		,aS*CMISC ]RB,9 9,aK(CLINES	A
		,aS*CMISC aeQwQK	C		"	(Q,aK|COPT: :Q		(Q	@ Q	acHQ@A@pQK	BADQK	CQwQK	%6 6	%)		,aS*CMISC 		"QwQK,ag|COPT*: :,aS|COPT,aK\CSCRN ,aS`
CSCRN )i,aK(CLINES	A
		,aS*CMISC 0: :4QwQK	C	@ ,aS~COPT		"?QK	BADQK	CQwQK	%*: :V	%'YU	%+\XN[QwQK,aS~COPT		"\QwQK	%,m: :	%-ploQk	@QwQK	CacP,a
@COPT		"zQk	@; ;	acTQ	@Q	@	%QK	@HADQK	C	%A	%	,aK\CSCRN ,aS`
CSCRN 5 5	%,aSCOPT		"		,aS*CMISC $peE8,aK(CLINES	A
		; ;,aS*CMISC (,QwQK	C		"	,aStCSCRN 		,aSvCSCRN 	A,aSr	CSCRN ; ;	acNa@A@,a
@JCOPTA@acL,a
@JCOPT		.,aSRCOPT70,aK(CLINES	A
; ;		,aS*CMISC TXQwQGQ
acQ	@
	"\Qk	@QK	@HADQK	C5 5		"tQK	@HADQK	%	%QwQK	C	@ 9 9,aSCOPT		"	acTQ	@Q	@	%QK	@HADQK	%"	A
!#	%: :	A	%/')		"%,aSCOPT*		,aS*CMISC 0$    w	"@DCh,aKCOPT: :	AacP,a
@COPT;ac&A@@7	#%Jn	-L8?: :8O)1iRM1sW[R\^U3b	v_efghijkl< <.m?o)1irM1sw{R|~U3b	v		,aS*CMISC 9 9E,aKr	CSCRN 	@HCacHa@A@0	acHA@1A@0	"	!&$.!!<.! >.9 9!}!~!%!1!!0!
!!"!                                 !! 9 9!2!.H!
! !!!("!+#!'$!-!*.!$<!#>9 9!?!@!A!D!-M!        R!Z!
\!^!a!d!,m5 5!r!z!~!)!}!/~!	!KDauto.   qsaved.  !h8 8$CLINES!j$CLINES!Z$CLINES!$CLINES!$CLINES!^$CMISC !\$CMISC !|$COPT!.7 7$COPT!*$COPT!"$COPT!0$COPT!,$COPT!$COPT!2$COPT!$COPT!6$COPT!V8 8$	COPT!$CSCRN !$CSCRN !$CSCRN !$CSCRN !$$	CSCRN !$
CSCRN !&$CSCRN !(: :$CSCRN !n$CUNIX0!p$CUNIX0!r$CUNIX0!t$CUNIX0!v$CUNIX0!#CTOI!
#GETNUM!~#SETTAB< <!4#DOSOPT!f#SENDM0!l#DELETE!b#CKCHAR!X#REMARK!`#RECVM0!d#GETWRD!x#SETPAT!z#MESG!#SCOPY  !#SAYNUM!#F$MA11!#LOAD!#ADJUS0! #F$MI11
 
"%:.0&2f& DOSOPT6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES"ff77ftnpmas"("0+; ;3"47+3"813 22 37+3	A"acDQ	@A@"Q@A@	"@HADQK: :	%		#	acFQ@A@acHa@(a@A@Q@	"BC		,aSJCMISC 		6 6	#	+	t"aK'	ADaK	$		,aSLCOPT		,aSNCSCRN 		,aSPCSCRN 	@ 6 6,aSR	CSCRN 	acTa@0A@,a
@VCOPTA@acX,a
@VCOPT		,aSLCOPT			5 5,aSNCSCRN 		
,aSPCSCRN 	A,aSR	CSCRN 	acTa@4A@,a
@VCOPTA@acX9 9,a
@VCOPTT		,aSLCOPT			,aSNCSCRN 		
,aSPCSCRN 	A,aSR	CSCRN acTa@89 9A@,a
@VCOPTA@acX,a
@VCOPTo9	$L:Up
		#	!}!~9 9!!!#!H!J!
!A!Z!	a!
z; ;!V$CMISC !b$COPT!X$COPT!^$	CSCRN !Z$CSCRN !\$CSCRN !T#STRBSR!P#GETWRD!R#MAPSTR !`#SCOPY !d#SETTAB
 
"%2&0&o6. DOTLIT6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 6 6CTXTCPATCLINES		",aKCLINES	A			,aSCMISC 	"	,aKCLINES9 9,ag
CSCRN ,aS
CSCRN            acQ	@	#ac,a
@CPAT	$#	@QK	%< <%$	A$%	@ $(,aKCLINES	%	(%@.	%,agCLINES	@ac; ;A@&	A
		"
;acA@%	'A()	()@G	t),aG CTXTQQK  	A
9 9	%VRac",a
@CPAT	Q	@Q	@A@#	*$@HC	#$*d	@Ag	@HADQK	t(9 9QS	((@()u	()@v	t),aG CTXTQQK  	A
	%ac",a
@CPAT9 9	Q	@Q	@A@#	*$#wwj	t),aK CTXT	A
U	%	*A	#: :	A	*@HADQK	t(QS	((HH"	*A	t),aK CTXT	t(QS	((@0H9 9		t),ag CTXTA>	t(QS	((@@	@ t(QS	t',aK$	CBUFR$	+ac&A@%5 5A@%A@,ac(Q@	"C4]ac*,a
@,CLINES	'+t',aS$	CBUFR$		"A6 6,aS.CMISC /^
!}!~o!o!     o!
o!$CLINES! ; ;$CLINES!2$CLINES!$CPAT!&$CTXT!*$	CBUFR$!4$CMISC !$CMISC !$
CSCRN !#LENGTH% %!(#XINDEX!.#INJECT!0#GETIND!$#GETTXT!"#INTRPT!,#DELETE
 
"%6.0&e& GETRA06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES		,aSCMISC QK	B"@HADQK	C	AQS	""9 9	@ QS	A#	$QK	@HADQGQacQ	@Q	@A@"Q	@A@#Q	@		"@HADQK: :Qg;	@ QS	$	:QK	A		,aSCMISC >C	A$#
JacA@: :	Q	@A@#Q	@		AK	@ QS>W	"QS		,aSCMISC 		$>!}!~e. .!e!!!e!~e!$CMISC !#ADDSET!#FILSET
 
"%8&0&%$ XINDEX9 9	QK	A	@ "QK	AacQ	@Q	@	"	acQ	@Q	@	A   	@ "QK		B"	"	!#INDEX 
 
"%0$0&f,* MAKSET6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES	,aKCUNIX0	A		"		"		#	,aSCMISC QK9 9	@HADQK	A	#	QwQK	"CQK	B$QK	@H%t$QK	t%Qg0; ;	%3/2ac,a
@CPAT	Q	@A@QK	@DQS	@H$t$QK	CQK: :	ADQK	t$QS			QwQSQK	BAD@ QS		,aSCMISC H3QK	&9 9	(&@e	&@HADQK	A
fn	&@H&Q_	CQK	@HADQKQwQSQK	B: :	AD	QSQK	@DAD@ QS		,aSCMISC v	&@HADQK	%	%5 5	&@H&QK	B$&	@&@H$QK	@H%t$QK	t%Q_	C&	&@HADQK: :,a_CUNIX0	C	&ADQK,agCUNIX0I?6I	&@D&@H$QK	@HADQK	t$: :QS		t&QS	&BAD@ QS		,aSCMISC H	&@H$QK	@H%t$QK	t%Q_9 9	C	&@HADQK,a_CUNIX0	C	&ADQK,agCUNIX0}t	(&@&@H9 9	$QK	@HADQK	t$QS		t&QS	&BAD@ QS		,aSCMISC e	A'Q[9 9	(QK	@HADQGQacQ	@Q	@A@(Q	@A@'Q	@		(@HADQKQgGF6 6acA@	Q	@A@'Q	@		ASacQ	@,a
@CPATA@	(QSa		
9 9,aSCMISC 		#!}!~f!	f!
!f!
!!%!&9 9!P!p!f!"$CPAT!$CMISC !$$CMISC !$CUNIX0!&$CUNIX0!*#ADDSET! 
 
#CTOC!(#FILSET
 
"%8*0&2* DOUNDO6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES		QSQK	A,aKCLINES	A			,aSCMISC 5 5,aKCUNDO 	BC		,aSCMISC ,aKCLINES,agCLINES	A8 8,aSCMISC ,aKCLINES,agCLINES'		,aSCMISC (		QS6 6,aKCLINES,aSCLINESac,a
@CLINES	"ac,a
@CLINES	#acA@#	$8 8,aKCUNDO 	%t%,aK CBUFR$	&!ac"A@"A@%A@&A@$ac"A@&A@$A@"A@%ac$8 8,a
@CLINES,a
@&CUNDO ,aK&CUNDO 	'@ ,aS&CUNDO 		,aSCUNDO 	',a[CLINES5 5,aSCLINESQK	Aac(,a
@CLINES,a
@CLINESQ	@u	',a[CLINES9 9,aSCLINES,aKCLINES,ag*
CSCRN ,aS*
CSCRN ,"QK	(	!}!5 5~!!!                                 !$CLINES!$CLINES! $CLINES!$CLINES!&: :$CBUFR$!$CUNDO !,$CUNDO !$CMISC !0$
CSCRN !$#NEXTLN!"#GETIND!(#RELINK!*#SVINS  !.#DELETE
 
"%0*0&">
, DRAWB06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES		acQ	@Q	@	"A	%			,aSCMISC 		#	: :QK	@HADQK	CQk	@QK	@HADQK	C	Qk  (acQ	@< <Q	@	$A	%57	"C8;		,aSCMISC 		#		"$<QK	@HADQK: :	C	QkEEMQK	@HADQK	C		%ZQK	@HADQK	%Qk6 6	@]QK	@HADQK	%q		,aSCMISC 		#	p,aKCLINES	A			6 6,aSCMISC 		#	z,aKCLINES,aSCLINES,akCLINES	@,aKCLINES9 9,agCLINES	@ac,a
@CLINES	&t&,aKCBUFR$	'ac,a
@ CTXTQ@A@'9 9	t'QK	C	'@H(%	'()	($$	@	t(QS	((,,.		t(QS: :	@ QS,aKCLINES,agCLINESD,agCLINESHCG	"(	((@K	(6 6	$$	@%t(QSLH	%t"QS	t$QSPac"Q@,a
@ CTXT	A	t&9 9,aK$	CBUFR$	)ac&,a
@CLINES,a
@CLINESA@*	%
uac(Q@	%|t8 8{		#	|ac*,a
@CLINES	&)t&,aS$	CBUFR$	A,aS,CMISC ,aKCLINES: :,aSCLINES,ag.
CSCRN ,aS.
CSCRN ac0,a
@CLINES,a
@CLINESac2		9 9	#	!}!~"!!                                 ""!
! !,"!~"!$CLINES!"; ;$CLINES! $CLINES!*$CTXT!&$CBUFR$!.$	CBUFR$!6$CMISC !$CMISC !8$
CSCRN !#CTOI1 1!,#EQUAL !2#INJECT!0#DELETE!4#GETIND!$#GETTXT!(#MOVE$ !:#ADJUS0!<#UPDSC0
 
"%2,0&
M$( GETSTR6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	QK	"	#	,aSCMISC 	"@H$t$QK	%C		QS		: :	t"QS	"BAD	QS	"@DAD	QS	"AD@ QS	t$QK	%	,aSCMISC 	%9 9	%8	%;7:	t"QK	C;	"@H$	t$QS		t"QS	"BAD	QS9 9	"@DAD%QS	"AD	QS	"AD@ QS	t$QK	%	,aSCMISC A3	t"QK	C9 9	@ QS			,aSCMISC 		
#	q	"B&	(&@~	&@HADQK	%	5 5	&@H&@HADQK	%	%	&@H&@HADQK	%C	&@HADQK9 9,a_CUNIX0	C	&ADQK,agCUNIX04*!4	&@D&@HAD%QS		t&QS9 9	&BAD@ QS		,aSCMISC 3	&@HADQK	%C	&@HADQK,a_CUNIX0	C: :	&ADQK,agCUNIX0e[Re	(&@&@HAD%QS		t&QS	&BAD@ QS		9 9,aSCMISC dJ	"B&	(&@~	&@HADQK	$%		%	A
	%9 9	C	#	acQ	@A@&	&"Q_		C"	A'""	('@7 7	("@(	"$&/	'@H$	acQ	@A@"	t$QS)0	'@HAD@ QS	"QS		9 9,aSCMISC 		
#!}!
~M!!M!!	M!
!! ) )!/!P!pM!$CMISC !$CMISC ! $CUNIX0!"#ESC 
 
"%4(0&;& GETWRD: :	QK	@HADQK	C	Qk		A"QK	@H#t#QK	%	%9 9	A
	"Qg	"	@H$QK	t$QS	("@#Qk	"@HAD@ QS	"@H% 		!
! 
 
"%2&0&

'4( JOIN6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 8 8CTXTCPATCLINES		",aKCLINES	A			,aSCMISC 	"	acQ	@	B#: :,aKCLINES	$acA@$	%acA@%	t%,aGCBUFR$Qac,a
@CTXTQ@Q	@9 9QK  	&($/	($@0	$,ag CLINES	@ac"A@'	A

=	t&QK	< <	C	&@H&D	t%,aK$CBUFR$	%acA@%	&t%,a[CBUFR$	#@HC		,aSCMISC 9 9
X	t&QGQacQ	@Q	@A@#	#@H&&t&QGQ	t%,aGCBUFR$Qac9 9,a
@CTXT	Q	@Q	@QK  	@H&&16,aK CLINES,aS&CLINESac(Q@	"@DC: :ac*,a
@CLINES,a
@ CLINESA@"	"                                            ak&CLINES	@,aK&CLINES,ag,
CSCRN 6 6",aS,
CSCRN #
!}'!!     '!
'!'!$CLINES!&; ;$CLINES!,$CLINES!$$CTXT!*$CBUFR$! $CBUFR$!$CMISC !2$
CSCRN !.#INJECT!0#DELETE !#LENGTH!#GETIND!(#INTRPT!#GTXT!"#MOVE$ 
 
"%0(0&" LITME00 0	acQ	@A@Q@A@acQ@Q	@		!!.!#PTOC!#MESG
 
"%("0&

** MOVE6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE : :CTXTCPATCLINES		",aKCLINES	A			,aSCMISC QK,agCLINES: :,agCLINES         @	,aSCMISC ac,a
@CLINES	#acA@#	$9 9	t$,aKCBUFR$	%ac,a
@CLINES	&t&,aKCBUFR$	'acA@$A@'A@$A@'QK8 8,agCLINESB@,aSCLINES,aKCLINES,a_CLINES	BQ_	AQSA9 9,aKCLINES,a_CLINES	BQ[,aSCLINESNacQ	@	(t(,aKCBUFR$	)ac5 5A@(A@%A@&A@)acA@&A@)A@(A@%		"A,aS CMISC ,aKCLINESac"9 9,a
@$
CSCRN ac"Q	@,aS$
CSCRN 
	"	!}!~!
!     !$CLINES9 9!$CLINES!"$CLINES!$CBUFR$!$$CMISC !$CMISC !($
CSCRN !#PREVLN!#GETIND!  #RELINK!&#F$MI11
 
"%.*0&<$
* SETTAB6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	A"	("@	"%	@@ t",aSCOPT		#@ $A%""9 9	@HADQK	C	("	"@HADQK	A
	%+'	C	("@A&< <-	@ &2	acQ	@A@"	'A	%=?@		#	,aSCMISC *A	"@HADQK: :	%P	%SO	%VR	A
U		#	,aSCMISC GW	&@HC	'%(: :	'((e	(%k	At(,aSCOPT	$acA@(	$fa	At',aSCOPT	'%ac: :A@$	$l	"@HADQK	C!	("]	#C	@ $         $A		"	"9 9		"	"%	At",aSCOPT 	"	$	A,aSCOPT	$"	("@.	"9 9	%	@At",aSCOPT/3	#	!}!~<!	!!	!<!
/ /! !+<!<!$CMISC !$COPT!"$COPT!#CTOI! #F$MA11
 
"%.*0&
;&$ UNIQU06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES	ac,a
@CLINES,a
@CLINES,aKCLINES	A			QS		; ;,aSCMISC 		
		QS	@ ",aKCBUFR$	#("@t#,aKCBUFR$	#",a_CLINES	C< <QK	t#,aS	CBUFR$$	t#,aK	CBUFR$Q_	C		,aS	CBUFR$1*,aK CLINES6 6	$"	@	!}!~;!     ;! ;!$CLINES! $CLINES!$CLINES!$( ($CLINES!$CBUFR$!$CBUFR$!"$	CBUFR$!$CMISC !#DEFALT
 
"%*$0&#$ GETKN ; ;	QK	@HADQK	%
	A
	QK	QS		"QK	@HADQKQS Qk	@	"	"	!~!#!

 
"%0$0&%$ PRINT06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES,aKCMISC 	"	Line numbers in backward order. acC@: :	No room for any more lines!.acC@	Bad syntax in pattern..acC@/-	Ba9 9d syntax in string parameter. ?acC@@>	                                                                  ad syntax in substitution string.UacC@V: :T	File is not readable. lacC@mk	File is not writeable.}acC@~|	Ga9 9rbage after your command. acC@	Bad syntax in file name."acC@#!	Can'9 9t move a group into itself. 4acC@53	No line has that mark name. JacC@KI	9 9                                                                                  esultant line too long to handle.^acC@_]	No match for pattern. uacC@vt	9 9
No error to report. acC@		No lines in limbo.acC@	Expected "<", ">9 9", or nothing after "od". %acC@&$	Line number out of range. @acC@A?	Ca9 9n't recognize option. SacC@TR	No line contains that pattern.eacC@fd	Bu9 9ffer hasn't been saved. zacC@{y	No command recognized.acC@	Last lin9 9e number beyond end of file.acC@	
You interrupted me. 6acC@75	No sav: :
ed pattern -- sorry.FacC@GE	                                                                              o saved character list -- sorry. YacC@ZX	No9 9 saved filename.pacC@qo	Bad syntax in character list. acC@~	Unreason9 9able value. acC@		No help available.$acC@%#	Line numbers not allowed9 9. 3acC@42	
Bad tabstop syntax. FacC@GE	
File already exists.Vac9 9C@WU	Improper column number specification. facC@ge	Unknown source language.: :acC@~	No saved replacement -- sorry.           acC@	
Bad user identifier.&ac; ;C@'%	User is busy -- try again later.6acC@75	
Shell returned ERR. LacC@M: :K	No saved shell command -- sorry.\acC@][	"L)F.?Ul": :8F4J^%@Sez6}upY$3Vf: :&6L\acA@q		,aSCMISC 		!?.%!%!$CMISC !#REMARK
 
"%$$0&" SAYNUM- -	acQ	@Q@A@acQ@A@		!!
!#ITOC!#MESG
 
"%0"0&5"& KNSCAN6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE ; ;CTXTCPATCLINES	,aKCLINES	QSacQ	@	"acQ	@A@"Q	@	t",aK	CBUFR$7 7,a_CMARK 	C		#	QK,agCLINES
"acA@$	A!
'		#9 9,aKCMISC 	C		,aSCMISC /	#	!}!~5!!5!$CLINES' '!$	CBUFR$! $CMISC !$CMARK !#GETIND!#INTRPT!#BUMP
 
"%,&0&U$( DOGLOB6 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE < <CTXTCPATCLINES		QS	QK	",aKCBUFR$	#@ $($@t#,aKCBUFR$	#t#,aKCBUFR$: :	@HC	@ ,aSCBUFR$	$,aSCLINESQS	"QSacQ	@Q	@Q	@		@DCac5 5Q	@Q	@A@Q	@	-	@ $,aKCBUFR$	#acA@%	A
		QS	B	$5 5,agCLINES	@QK		@DCIOQK		&	!}!~U!U!4 4$CLINES!"$CLINES!$CBUFR$!$CBUFR$!$CBUFR$!#DOCMD !#GETLST! #INTRPT
 
"%4(0&1h* DOSHE06 6CTTYCUNIX0BCSCRN CTERM 
COPTCMARK CMISC CSCRATCUNDO tCBUFR$CFILE 9 9CTXTCPATCLINES"*n*n"*s*n"type return to conti: :nue: 	@ ",aK6CLINES	Aac8,a
@:CSCRN A@QK	@HADQK	C9 9	A#	@ #QK	@HADQK	C,aK<CMISC 	A
	A$	($@*	t$6 6,aK>CMISC 	A
QS+1	t$QK	C	$@H$:Qk	@A"'		9 9,aS@CMISC 		%	#	A$CQK	&	(&@O	&@HADQK	A
,a_BCUNIX0	C9 9	t&QK	%c,aKBCUNIX0	t$QS	t&QK	t$QS	$@D$(&PPb	(&; ;	@&@HADQK	t$QS	($@P\	&@HADQK	C	A'	('@	t',aKDCFILE ; ;	A
	t$QS	($	A"	&@HADQK	t$QS	($@PX	t$QK: :	C	$@H$,	@ t$QSacFQ@A@,a
@<CMISC A@acH,a
@JCTTYacLA@; ;	acNA@a@	#@HCacPA@	(O	"@HCacNA@a@Q@YacRQ@9 9	(U	#A	(@DCiacNA@a@acTA@)	)%|	%	{t~macH< <A@
acLA@acV	(C		,aS@CMISC 		%			%		Not implemented.acX9 9C@	(%(		,aS@CMISC 		%	'		%	!
@!u!v!}!~!	5 5!!1!'!(1!
1!!!%1!D$CLINES!R$CFILE !N: :$CMISC !L$CMISC !J$CMISC !H$CSCRN !P$CUNIX0!X$CTTY!^#SHELL !`#SUBSYS!F#POSIT0* *!T#SCOPY !V#DUPLX$!Z#BREAK$!\#PRINT !b#T1IN!d#RESTO0!f#REMARK
 
"%0*0&H:$ WHERE09 9"unknown"=installation=	ac(a@A@	"Cac*a@9 9A@Q@A@	ac,Q@A@"A@	#%!	%$ #	ac*a@A@9 9Q@A@$ac.A@"ac0Q@	#t#QK	C	@ QS=	ac2Q@A@: :		!}!H!H!
H!!.#OPEN!2#GETLIN!6#LENGTH!0#SCOPY !4#CLOSE  !8#MESG
 
"%$$0&