1*" SETPAT: :PATCOM	QK	@HC		,aSPATCOM		,aSPATCOM,aSPATCOM		,aSPATCOM		8 8,aSPATCOM		,aSPATCOM	A,aSPATCOM		,aSPATCOM		,aSPATCOM		9 9,aSPATCOM		,aSPATCOM			,aSPATCOM		
,aSPATCOM	@ ,aSPATCOM		!%9 9!(!)!.!?!
@!\!^!{!	}!~!$PATCOM!$PATCOM! " "$PATCOM!"$PATCOM!$$PATCOM!&$PATCOM!($PATCOM
 
"%&"0&!$ MATCH 9 9PATCOM	A"	("@	"@HADQK	A
acQ	@A@"Q	@Q@Q@	A	A# 			@ #	!#AMATCH
 
"%4$0&"( AMATCH9 9PATCOM	@ "QK	#A$acQ	@A@$	$$	$@HADQK	A
	C	$": :	$#%!	%@HADQK	A
acQ	@A@%Q	@A@$	A"(5	%#t"QS	"9 9	@DAD#QS	%#		$@HADQK,a_PATCOM	C	t$QK	%@HAD#QS	L9 9	$@HADQK,a_PATCOM	C	t$QK	%@HAD#QS_acQ	@A@#Q	@A@$; ;	A	"BADQK	"v	"A	t"QK	Aw	"A		@ &		t"QK9 9	@HQS	"$"@DADQK	t"Q[	#uiV		#&	!"!*"!#OMATCH !#PATSIZ!$PATCOM!$PATCOM
 
"%8(0&'6( OMATCH9 9PATCOM"in omatch: can't happen	@ "QK	@HADQK	A	"9 9		
		#Q[		ADQK	$QK	@H%t%	QKQw	Q_	C	A#"QK	@HC: :%	@ #*QK	@HADQK	%7-	A#6QK	@HADQK	C9	@ #BQK: :	@HAD	QGQQK		B%ac(Q	@Q	@A@%	@HCE	A#\QK	@HAD	QGQQK7 7	%m_QK		B%ac(Q	@Q	@A@%	Al	A#z	$,ag*PATCOM&; ;,ag,PATCOM.	%
:	&LF	$%`ac.a@7 7}	#AQ[QS	A"!'!
'!$'!Z'!n'!2 $PATCOM!0$PATCOM!.#LOCATE!4#ERROR 
 
"%6(0&"$ LOCATE9 9PATCOM	QK	@HADQKQ[	"	"@H"
	"	Qg	@HADQKQ_	C 	A#		@ #	
 
"%.$0&Q:$ PATSIZ7 7PATCOM"in patsiz: can't happen	QK	@HADQK	%
: :,ag(PATCOM	,ag*PATCOM         	"QK	@HADQK,ag,PATCOM: : 	%#,ag.PATCOM'"&	A"'QK	@HADQK	%4	%9 9736QwQK	@D"7QK	@HADQK	C		"Gac0a@8 8J>*	"	!!Q!$Q!*Q![!aQ!nQ!6$PATCOM!4 $PATCOM!0$PATCOM!2$PATCOM!8#ERROR 
 
"%*$0&G,, MAKPAT8 8PATCOM	A"#@ $%&QK	'	('@	'@HAD
QKQg	A
	"(QK: :,a_PATCOM	Cac,a
@PATCOM	Q	@	A@"A@	) 	'@HADQK,a_PATCOM; ;	C	'Q_	C5ac,a
@PATCOM	Q	@	A@"A@	):	'@HADQK	C9 9	t'QKQ_	CNacA@Q	@	A@"A@	)U	'@HADQK	CacQ	@8 8	A@'Q	@	A@"	C		*	i	'@HADQK	CQK	$'	#(@HADQK	: :,agPATCOM    	%	%,agPATCOM,agPATCOM9 9acQ	@	A@"A@#A@$	$	acQ	@A@'	A
		$%	@6	(%@(&@: :	%t&QSac,a
@PATCOM	Q	@	A@"A@	)acA@%Q	@	A@"A@	)3ac ; ;Q	@A@'	A
	&A_ac,a
@PATCOM	Q	@	A@"A@	)t&QGQacQ	@Q	@	: :A@"A@	)&@H&bacA@Q	@	A@"A@	)	ac"Q	@A@'	+	acA@+Q	@	; ;A@"A@	)W+vaF,	(#8	'@HAD
QKQg+		**	acA@Q	@	9 9A@"A@	A		*9	&A
		*?	'*B<-	*	!}G!G9 9!	G!$!*![!a!!$PATCOM!$PATCOM! $PATCOM!"$PATCOM!*" "#ESC !#ADDSET!#GETCCL!$#STCLOS!&#START0!(#STOPT0
 
"%D,0&]& GETCCL; ;PATCOM	Qk	@QK	@HADQK,a_PATCOM	CacA@Q	@Q	@	A@	"Qk; ;acA@Q	@Q	@	A@	"QK		#acA@Q	@Q	@	A@	"acA@: :Q	@Q	@Q	@Q	@	A@	#@HADQK		#@HQSQK	@HADQK	C		$U		; ;	$X	$	!}!~]!]![!]!n!!$PATCOM!#ADDSET!#FILSET
 
"%2&0&Z& STCLOS: :PATCOM	QK	@H"	"@H"	"	Qg	#"@HADQGQacQ	@Q	@: :A@#A@	$QK	QSQK	%acA@Q	@Q	@A@	$	acA@Q	@: :Q	@A@	$acQ	@	Q	@Q	@A@	$acA@Q	@Q	@A@	$%	!Z! !*!!#ADDSET
 
"%4&0& ( MAKSUB; ;PATCOM	A"QK	#	(#@	#@HAD
QKQg	A
         CacA@Q	@	< <A@"A@	$acA@Q	@	A@"A@	$	#@HADQK,a_PATCOM	C	t#QG: :	QacQ	@	C6	(#@acA@Q	@	A@"A@	$#@HADQK	%	acA@%Q	@	< <A@"A@	$B	acQ	@A@#	%acA@%Q	@	A@"A@	$b	#@HADQK9 9Qg		&~acA@Q	@	A@"A@	A		&	#&	&	!6 6F!v!}!!&!0!!$PATCOM!#ESC !#TYPE!#ADDSET
 
"%6(0&O& CATSUB: :PATCOM	A"	("@	"@HADQK		A
	C	("@"@HADQK		#@HADQK	$9 9	($@	#@HAD$Qg	@HADQGQacQ	@Q	@Q	@Q	@	%	"@H4 4	ADQG	QacQ	@Q	@Q	@Q	@	%		!}O!O!#ADDSET
 
"%>&0&C`$ FILSET: :PATCOM"0123456789"abcdefghijklmnopqrstuvwxyz"8A: :BCDEFGHIJKLMNOPQRSTUVWXYZ	Qk	@QK	@HADQKQg< <	A
,a_TPATCOM	CacVQ	@Q	@	"acXA@"Q	@	Q	@Q	@	#QK; ;	@HAD	QGQQK	%5acXQ	@Q	@	Q	@Q	@	#4	AQgDQwQK: :	A
EKacXA@Q	@	Q	@Q	@	#LQK	@HADQG	QacZa@Q	@	A9 9ac\a@Q	@Q	@Q	@	Q	@Q	@hQK	@HADQG	QacZa@Q	@	A: :ac\a@Q	@Q	@Q	@	Q	@Q	@QK	@HADQG	QacZa@8Q	@	Aac\9 9a@8Q	@Q	@Q	@	Q	@Q	@&acXA@Q	@	Q	@Q	@	#5wX@		!# #-C!V$PATCOM!X#ESC !Z#ADDSET!\#INDEX !^#DODASH
 
"%8$0&@& DODASH: :PATCOM	Qk	@QK	@HQSacQ	@Q	@	"	acQ	@A@"	#QK	@HADQG	: :QacQ	@Q	@	$	($@&	$$#	@@HADQGQacQ	@Q	@	Q	@Q	@	% '+		!#ESC !#ADDSET!#INDEX 
 
"%:&0&$ ADDSET5 5PATCOM	
QK	Qg	@ "QK	@HAD	QKQSQk	@A"		"	
 
"%0$0&

;$ ESC ; ;PATCOM	QK	@HADQK,agPATCOM	"
QwQK	A,aKPATCOM: :	"Qk	@QK	@HADQK	C		""QK	@HADQK	C		4 4	".QK	@HADQK	"1%	"	!	!
!n!t!$PATCOM
 
"%*$0&1$ START0; ;PATCOM	,aKPATCOM	@HCQK	@HADQK,a_PATCOM	CQwQK,a_PATCOM: :	CQk	@A"		@ "	QK	@HADQK,a_PATCOM	C	A"	*	@ "	! $PATCOM!$PATCOM!$PATCOM
 
"%*$0&1$ STOPT0; ;PATCOM	,aKPATCOM	@HCQK	@HADQK,a_PATCOM	CQwQK,a_PATCOM: :	CQk	@A"		@ "	QK	@HADQK,a_PATCOM	C	A"	*	@ "	! $PATCOM!$PATCOM!$PATCOM
 
"%*$0&