`*9 9CBANER"0P9PIP9P9PJP9P9PPP9PPPPP7PPP9PPP9PJPPP9P9P9P7P7P79 9)P7P7PPPPPPPPPPF0P7PPP@PPPPPPPXPP//PPLP"j	9 97hhhuhh!9 9=yw))acD,a
@FCBANER,a
@HCBANERQ@		"	: :	#@ $A%	(%@	t%	QGQNQKN	A
acJ,a
@LCBANERQ	@N	&A		&$: :	t&aK	$".,	"-	t&aKi	$#3	#4A7&,aKN^CBANER	EA?A9 9QN	$MQN	@$&t%QS                           		"#B'M=#A,aSPCBANER	$AZA?A	@AY9: :	@$M=(	acRA@(A@	A&	(&@n	&$%s	t&QGQNacTQ	@Not	(9 9	)acRA@)A@acV!
!
!
!2
!B
!Y!d!7 7
ZB\`><'!N$CBANER!P$CBANER!X$CBANER!T$CBANER!V! !$^CBANER!R#INDEX !L#DOARGS!Z#BAXX!\#PRNT!^#SWT 
 
"%z*0&

h6 PRNT9 9CBANER"09 9)	
		acjA@A@: :QK	CacjA@A@		QK	"aclA@A@aclA@A@acl: :(A@A@$acnA@+acpA@0acpA@5acrA@:	"L+1DE: :8FG;,1H6%LO11%1,1PY1Z;,1\;`5 5bc16%1;,d?QK	%r	%	uq	%
xtQ7: :,aKt^CBANER	EA?	CA	@#,aKv`CBANER	EG?~	C@$QwaK	%@ &'acj: :A@A@	(#@$$#	@A7#,aKxCBANERQ	EA?	@(Q	EA?9 9	EA?	C@)Q	EA?	EG?3	C@*Q	EA?	EG?>	C@+Q	E: :G?F	C@,)$(ZZ	$*Y	@*$+[	@_	(-+(-+)-*)-*a	A$,: :sp	##A7#,aKxCBANERQ	EG?)	@&Q	EG?0	EG?I	C@.Q: :	EG?;	EG?	C@'Q	EG?Q	EG?	C@/Q	EG?	C@,.$&..: :	$'-	@'$//	@3	&-/&-/.-'.-'5r	,A	A,D	(A	); ;	AIacjA@,A@L	)%0(%1	aczA@1A@0	*A
	+%0*%1	aczA@1A@0: :	&A
	.%0&%1	aczA@1A@0	'A
	/%0'%1	aczA@1A@0qb	A2ac|: :,a
@~CBANER	A2$,S                            wQK	3acnA@ac"acrA@%9 9	34L#.&23#467#8:&;=>?@ABDE9 9FGHIJKLMNOP*	acjA@A@		!!!!!: :!!!Y!	!
!!2!YY%
d9 9h' }!$CBANER!$^CBANER!$`CBANER!$CBANER!x#BAXX!z#LEGL   !|#OHAV!~#LEGU!#OHAF!#FRNT!
#OUTPUT!#ACHN
 
"%<60&

RV( ACHN9 9CBANER"0cIp)J+$}V};Tp>@>@ePePeP~!}=$iKq@d|dpPo@! S6@9 9T@_8                                                                                                                j`j`	A"acLA@A@A7"aKQ	EA?	@#Q	EA?9 9	EA?	C@$Q	EG?	EG?"	C@%Q	EG?%	C@&	acNA@#A@$	%: :	A
acNA@%A@&9acP,a
@RCBANER	A"%J		!K!K-% %d'B@!T$CBANER!N#BAXX!P#FRNT!R#OUTPUT
 
"%*(0&

dX* OHAF9 9CBANER"0ow`g&P:T@`}h_1 A{@,tqk}Q(mt9^e"NU?Et?H/6] Mr &F //p.D: :	QK	@HC	@ "	#		"	#
	A$	acLA@A@9 9QK	""	A7"aKQ	EA?	@%Q	EA?	EA?	C@&Q	EG?-8 8	EG?5	C@'Q	EG?8	C@(	acNA@%A@&	'A
acNA@'A@(LacP9 9,a
@RCBANER	A$$#]		!^!                                 !^@d*'#B@ !V$CBANER!P#BAXX!R#FRNT!T#OUTPUT
 
"%0*0&

0* LEGL: :CBANER"03/0	./	+.		ac A@A@		Q_	$QK	A%ac"9 9A@%A@$QKQ_	$%$$ac"A@$A@%ac$,a
@&CBANERac$,a
@&CBANER	A": :	&"'t'aKQ_	(aKQ_	)ac"A@)A@(QK	t'a[Q_	(	QKa[Q_: :	)ac"A@)A@(ac$,a
@&CBANER	""A&%e//QKQ_	$	Q_	%ac": :A@%A@$	A'ac$,a
@&CBANER	A'%vv		!!!!* *!+!1!7!.$CBANER!(#BAXX!*#FRNT!,#OUTPUT
 
"%0*0&

`>( OHAV9 9CBANER""6RPzeM.] '@rp`cU0Og(?
9/z" k[t4H%1%1~	QK	@HC: :	@ "		"	A#ac2A@A@QK	""	A7"aKQ	EA?	@$Q	E; ;A?	EA?	C@%Q	EG?)	EG?1	C@&Q	EG?4	C@'	ac4A@$A@%9 9	&A
ac4A@&A@'Hac6,a
@8CBANER	A#%Y		!Z!                                 ) )Z<d&'B@!<$CBANER!6#BAXX!8#FRNT!:#OUTPUT
 
"%.(0&

{4& LEGU9 9CBANER"HI	GH	
FG
CF	ac A@A@ac"A@A@ac"A@A@< <	A"ac$,a
@&CBANER	A"%ac"A@A@ac"A@A@	A"ac$,a
@&CBANER; ;	A"%7,,	A#"#%t%aGQaGQac"Q	@Q	@	t%aGQaGQac"9 9	Q	@Q	@ac$,a
@&CBANER	##A"%g99ac"A@	A@
	A"ac$,a
@&CBANER: :	A"	Qgznn		!!{!!!!{!	{!
C{!$ $I!J!P{!2$CBANER!,#BAXX!.#FRNT!0#OUTPUT
 
"%.&0&

"$ BAXX; ;CBANER	A",aKCBANER	t",aSCBANER	A"%	QK	@HC			A"ac9 9,a
@CBANER	A"	Qg!		!"!$CBANER!$CBANER!$CBANER!#OUTPUT
 
"%*$0&

& FRNT9 9CBANER	,aKCBANERQ[	",aKCBANERQ[	@H#"$,aKCBANER	t$,aSCBANER# #	A$$#		!$CBANER!$CBANER!$CBANER
 
"%,&0&4 
( DOARGS9 9	Usage: banner { - | -c <char> } <string>. acA@Q	@A@	BCacC@!	@ < <	"	#A$	($@,acA@$Q@A@	%:Q	CQ	A>	$B%ac9 9	A@%Q@
A@	%Q	A"PBQ	CQ	CB&Q	CB&AX; ;Q	Ad	$@D%acA@%Q@
A@	%w	($@acA@$Q@
A@	@HCQ
: :	#vh	$B%acA@%Q@
A@	BC9S-acQ@A@Q	@: :A@	"@HC		QS	#QS%	#QS		QS,		!4!!- -4!N! !-!C!c!!#GETARG!#ERROR !#SCOPY 
 
"%(0&
$ OUTPUT9 9	A"@HADQK	t"QS	A"%		Q	@ Q	acQ@A@		!u                                                                 !
!#PUTLIN
 
"%.$0&"9 9CBANERCBANER-EeTtAaOoIiNnSsHhRrDdLlUuBbCcFfGgJjKkMmPpQqVvW9 9,wXxYyZz0123456789+-|=/%^_<>()*?&$#!,.;:'"`@`CBANERz9 9708Hx[G
M>O1%@
:<i[7{nR	l>jof?V4ux~AM	F2kqAvU0=8|f9 97O/&:B9	yiI	H=	LwwAwx;
3A	}]&
>K	T*<d8gdc#AxBWmSPpK9 97IsIvTh?gekOqNuO^99$D D?!~"@Pam 8%)	j!j*j3j:jE9 9
jLJeFD^z,YCBANER%	=i;i	=i;i	:;f	2O;d	&5;d	;d	|+;g
KpRUJ^ 9 97]pb`k$x.T                                                                                 H,b4;ZCGt[[L{*[P"_TCc[X(?\&8{\ %2[\*;`9 97	`(	`#+;\*#+;\ %2[\?O{XYlTs	;P"&[L)KNChdy)0*V[!,            ::b9 97;;(;<;F;P;\
H
KrRY2_PfpzP8zPfp_PY2R
Kr
H;\;P;F;<;(;:b9 97:PrTZXB\*`hbrjF4(          n}.v'.(NGKN-NNpNIaNsZ@#(*x2H9 97:BhN YXeqHhf              |	b		uH 	uTereHee$te0Je< eHvePdeLe@Xe5 e)T9 97ee6e`	uy	us	n	F`
ldX hu0eYXN Bh:.`'#(@[9 9sNpZ
CBANER*	!r$ZrfC^2Ee\eX@\2G\<i"`s`&%.}`&&9`09 97?Sm`0Yp`0s                               `0.?`0'OQ\>Alq\4]#\*zBuX.hG	XS,O0K>Cd;
+`#(B#29 97+YvZ
ZCtA<@%gX$eN(^xVPTQ`N+
Ks	iPln>qwpy,T]TY&T]Ta`Ti9 97.`#(@XrI4DlBv|Alj?]f?V?N(>C>;2>3N,0{Lsrlh`8XTTXLtD9 97<68:0V(|%BF
Xt	$X40U|l!B,Q\\%Tle|@d@SCC C*C4CACK^2pG^$9 97#G7FJKEH31+VE!k/\CA3X)z/3b]7Tu?e7^s5]7hY3;ZX                   ;Z?{;d=p;d%Z;d#9 9+Sk;f<k;d<a;d	6A;f	6A;Z<a7r<a7h8o7h?3v%V3v%V/nCBANER&X=+9 97@u]' Bx'\['_A'n{+I+B=o
Tw.&Dv	DyB1:SAS9LS2MrF4kXu\ s9 97\*Yh[`?GI`&%*)`&%*)`0	`0`0	`2	\>	\4EXBeX8(,TF+5kT29 97b+y+^)MV@]6n}v^.lI;Xi;<QI;FK);PD	;]	=i;g-a-b	=i;gD	;]K);PQI9 97;FXi;<lI;8^xVPTQ`N+
Ksp;;d\[;dU;;dO;dH{;g	A[;g;Sl%PSP:xP9 97#dr7                 `@	;'xh2;NdG7kHP(432([                                                                                                                           v{
z#('.tR&]h^^$:DF$OBXV	9 97Y	atX8\65
*q
`$`\2XTPA
Ku
Ku	q2sj$
`%?&G;dA(;d\De;Zx`K;P,';F9 9K4};(8.`#(@Xr
0
<P
@8
D 
H
KsXCBANERvZB'*x2H>YXu49 97.`#(@Xr;g;];P;F;<;9f94998n8Z8PQEX3 yzY@^9hDHC((|p'vRC9 97[wZJ'vP@PAp[,(]3HwPh                                                                                                          -	xJ/pk88n99 9R;;<;F;P;];g`(``9 97``j_*_^n^Z^P^<Br2R*x'#(@[dT?2YO2shj(B][:cj^B6D+'$#<9 97V	A[;j	A[;j	A[;kD;\G_;PJ!;FLm;2+hq76.msv0vMS6Pndlx*5"^L:cN8                                                                                                                     *X9 977zqh;f;Z;P;F;(888<8Z|a|,&x`J\DdA(~?&F%$
`sj	q2CtA<@%gX$e
KvN(9 97$e%gV%gL@A2[ju6OF)htEdy6TRN2mh"T	1^{",O	q4	mJ$
j$%e\?{X[&v:~^4,9 9	{@_3>(zX(lI>CBANER&;dXi;dQI;dK);dD	;g	=i;gSR%o`?pU`0bS;g;\;P9 97;<;(;
:N: 	iQopv              r0@$x,H00               7@}/7^v;Zoo;doo;n	iO;z	9 97iO(\e`&+8773/>'x2vCtA<@%gX$eN(
KtR$i%B;Z%B7r?_97h@eY3Z9 973vu1/5i+*UA+GwQ'5x-D(KG|NheP$.8EOB`c35`U6DT\W+9 97x@:aF?8"4%I*%I.v#                         w?\                         q4                         V 	YS0	O8z	O7wJ	O`T	O^!	O`T	O9 977wJ	O8zS0V #q4%?U\%?.
?7w*,@:/&X\V&lnN)x@W4WsV(5?;Z|De9 9#;Z:X6r3+BJ0VJZ]r]h]^]T&}~$$
i7;dCBANER
Kr
HN*%g`(q8D                9 97I888(828F8P8n9 ;;<;F;P;];g3:J>B|Bt0	Ka;Z$a@%cyvC!9 97~NE)D];fhf@DqJ"S,^LM;<_;<>;F;k;P8=;Z</;Z@+;Z	=};d	EW;d	II;dA9 97H\L:PTbX6\
cF                 f][;d	 wP	3!(p	{O!B1
z"]Qh
r'"wnw$, x0>H-5p*,'"@$P!9 97x
 Hwpj0d^ [hUHR
Kpr"*$:		!XBRN;n&.]Bf	s1X.	k}X@	_'9 97XT
^YXh(N%I"?F6n-#>f&N}.op	iNp^xG04X@pJ	^T	R~	B6{h9 97oc2StH<>, *Ty6m`]@RFPB|NR^ipy.L!,0j<J	6h	F&	Q|hd9 9tDx(x?V[8^xVPTQ`N+
Ks

CBANERar]<bhd"	at	efXB\6`	ib	9 97ezh2jji0mpVXOK CP;7ar]<bhd"	at	efXB\6`	ib	ezh2jji0mpVXO9 97K CP;+`.`#(@Xr
+;d\[;dU;;dO;dH{;g	A[;g;T>
A@	CxIh'eN,9 97mv6(2J.l&0"R|NC'd6S+t'O3X37T	;P	;Z2GZ1E".,+t~l8TI|9 97qD.^#f@]	EfJDv-j2Bpj>Bl/j<Bh=j<B`mj<BT+j<Y1 pAvV n	O.U                                                                                                                             ST2LozHO[ZV,9 97,%ZL            aVPRTyNX
}iJHoFB>6&3B^|bX|B4H                                                                                                   *Ll+t.,1E"2GZ	;Z9 97	;P37T'O3X6S+tNC'd8\@TQ`N(
Kr;i;\;P;F;<;(;:v:X:::9 9	:~:`:B:$&=prCBANER&Ta (86HibPpM4
~\0	0Pb-p	}<qfeYXN FPBhFxRN9 97^$mby8oP=v0           MZ$p(|PvOHF-H@dS:t::::X:v;;(;<;F;P;\;iXEX:9 97X$XX|XhXJX,XWfWHW*
{d~	-      ^>f.BNs7nYXN Bh6:BJ~VTMu.	L
j#n8wfH&9 97T           [NXX6XTXrXX$X.X8XE;h;\;P;F;<;(;;:X::::j:B:9r#>9 97L`U\HmgHw0040e6P}BP-dPa(RN N4]|mD}T,d<,Lt\<l{L\+$:X9 97::::t*,LFo~c(S`D8B(z2R}
m`]@RR&^:U0	"I0>0s20\'0D0-9 9!H|jHeVxOJH:t::D:l;;(;<;P;\;iXDX:X.LCBANERX$XXrXTX6XWp9 97WRW4
yV	+~]3`&kX."SNJ8>:JLZif}^0,x@(PpX6XWzH2<\0|9 97 >v uXixYXN :>Jt$nO{N	7lfCFT>$mnWzXX@X^XrXX$X.X:XD;d
Kp9 97
HN*J@Q`TVP                                                                                         ^x]Hg lk` pP#z(v:&t:
y1:~49Xh	KLL(	/09 97,Pig;d     1M;d[vT:P\HDDHZL.St	\	7tUP	{E(	sa\Fh
r zpY!+`rW"bY9 97-)8* `'p% "0X
 Hwpu8k`                                                                                                     @b[hUHRr	iP	efhd6fni&                                                                                                                  ~u6t}^9 97|.VgkX"
emX	cI#}	k#qMN	o!XB(n                                                                                          "	ox	kXB
j                  fn
fPd[mA%)^9 9"  !6^6~2CBANER!V  yFr&on	iP;g;];P;F;<;(;;:l
                                                                                        
9 97	
8tPmkE;PcW;Z^+;Z\g;dhc;dS	pP|0CP;/H'z`TUb[;db};d9 97dA;dl%;dwq;Z	y?;P
-;2
	:N:l;;;;2;<;F;P;\;h;f^>H gYXO;O9 97/P64{@	K	::	}P	rm%z&tS;<[#);PxA3;Z`=;dK                                                                                               ;d@C0rP H.                                                                                                    j!@-%o9 97sFpC$p                                                                                                                       h`OH."@~xp:0:N:l;
;(;F;P;Z;g@P                              p,0Lxq(
 !0$4@'Eh*S(	Oi9 97;d	WM;d	_1;d	g;d	oy;d	w];d	A;d	=;d	!;d	;d	_;d	"C;d	*';d	2;d	:o9 97;d	BS;d	J7;d	R;d	V;d	]{;d	eU;d	m9;d	u;dp@0"7                                                                      W(rX$)-X-9 9`h-h81n>.                                                                           nhN(CBANER$                                                                                                      &v7 HF#Yn&g.	HXB	OsXB	WWXB	_;XB	gXB	oXB9 97	wgXB	KXB	/XB	XB	wXB		&f5VCFR6                                                                                                       Fv"?F"G"Of8bPcloz \
9 97                                                                                    2vFPT
5~4bN}C0a'JGD	,*o~(mFTQbN-QbT(mF*o~D	,Ga'J}C0bN5~4T
vFP29 97                                                                                    
\z oclP8bb/+01R8p47J<D!$x(`,H88.`'#*BZ9 97.*B4B =."@z%MD&Sc'nvhw/"QF"tC[/&"5"iN&;P*;P.;P.;P2}9 97;R6o;P6y;P:k;F:u;F>g7TBY7JBc7@F_3NJQ3:Jo3U/Zk\#'Z#: :/+8#3t#?{VZde~bfnD>?,&{XebsHLZD'
@*I*r'+/z%,33lMdQLO7h              CBANER9 97H{7h	A[7r	A[;_H{;ZD;ZK3;PQ];P(k;F)mW;<+p;2,se7@G'7,Km30h0s9 97P7!.N5leI*zV>*dX/4q^}\,	                                                                                                    L$l(TK8jK@DKD@KLTU3KWzK_TKcPKk*}hN9 97}lJt$|==^]Z&4@($x(`008&\>~bHqJu9 97yrv+H]H,gHJ(voW:$\Zsq,@BE$``A%;('U;('G;(%	';(r';(v;,}9;*q;*9 97);(+a;(-;(G7G;(H6;(dR};(hZ%;(t+;(KU@be yu`7r06(z H                                                                                                    @vW4cN9 97nhzH
                                                                          (;*=\#^|`q'daA#+`^;=+tD"/f*	a3X()3bm{7Tqc7^jM9 97hjM;PjW;Ph;]jW;Zqw;Pm;P(
/;PvCBANER*];FE-57TG/c$C(~bKS6fnY9 972jw2j=1+wC6'j<w k$x:I:v;;(;7GHmlD`(0^6x;h? HD4(a^~h~9 97-+;2c~aH}e(dSJ:H :::N:l;;;(;<;Pj"y$A#(tp|\TeI 5b$pFd#*G9 97/*E~7/R)b33N(_q3X&\/7JF%7TCm7^Cc;FGK;P@+;VGK;PCc;FCm7^F%7T&9 97\/7J(_q3X)b33NE~7/RG/*d#*pF$5beI |\TtpA#(y$j"p{L-HfML7&R9 97i#"mNk'<T4e+B9)/H)gR`(?C3N"7J7T;F};F                                                                                             ;P                                                                                   ;]};Pe9 97;P%2e;P&<m;F(C;FBd)7TCkS7J^e3Xx-w/f{>3/Rfe+V4K'Plg#,<                                                                                                        
,p9 9z>o$VCBANER+c
P><F<G                                                                                                                                                                                  <G<F<I<I<I<I~U~ULWLWLWLW.`:FP9 97R]@iub8d$:0<fH<T_hk>wj@&l2B:0:N:l;
;(T4\zl|9 97 |7h%u;d[LK;n)$+;nw{;dFVq7h2
cZ1pT<fH<T_h)nPdKMF|${@	_9\9 97&l\2B	_9:0${:NMd5()p#$/>3$D;V$)p$':$)p$D;V3/>#$
\d>
\dH
\d\
\r
\
J
\b
\#9 97M
\M
\#M
\/M
\MV&
\|b
\|X
\-|D
\
\-A 
\E
\I
\dH
\h<
\Ph
\9 97P^
\-Lb
\~
\t
\V
\,
\
\!.%-H1&8b<@D|HZPSt
@8p'
;u.!\
m)$
Sv	^Dl9 9Q6ybGh-X4{|bNf/rLDdha0\@                                                                                         ,CBANERTT                                                                                         \@a0dhLDf/rbN4{|h-X9 97G6ybQDl	^
Sv
m)$!\;u.p'

@8StPHZD|<@8b1&-H%!.@Stcloz :v9 97\Fj01vWnw8PZ2$e\vA>X>XA\v$eZ2w8PWn1vj0\Fv:z oclSt@19 97b&
l&l
U.	=p	%hz	&k2	(nl	B
\ F
u7<'f`@}V_[0WR*Uk#j>	/0DS9f76J7S9f0Dj>	/9 97*Uk#WR[0_@}V'f`
u7<
\ F	B	(nj	&k2	%hz	=p
U.
l&l1b&$H&&v*^.P28 s,"V 9 977^7h;P;ZtC(E^;Z.F;Z2};Z6y;ZBE;P.fA;PEc;Fs);<(d`DPb"&62@.b*9 9&&0"RZ@fDu2V	Nr P$.K~H
.y](,||CBANER	+yl                                                                                                HQbEm9 973D=u7J.{7T'5;Fo;P1A`&)5]:8((qxV( tFB5?2.C8c.Pyf>va:eB8@.52n#9 97	fs&_7,/B.G56:NF                                                                                                                                                              n                                                                                           >eF-NM>npN!0Naxb*LaxLRvLJDwYpJr	P^	?@	-Q9 97Nb|	}Nvz~aRr`a7R|^[VnD:Vn,#Vxwwe]Zj]H3Zj]H3Z`]H3Vxw_FoOydKzf=9 97GuG0CFtL;3F`i^9J*&~z	>d	S=p,($l            zET<eT<=T<dET<%eT<49 97a,rLSrS.[0oL<3IP3]
zE:Le>N =>b(dE>y%e> 4;a,rLSrS.[0oL<9 9*3IP3]
3a3`:03`:b3`;3`;P3`;t'(EE.sV84 8.sVEEBCBANERt'(R9 97ZPFh	Kba(a2]^ZRN+ 2\6::6:2\+ xTnJ,rFi4z	Kc8X&$v?:vne4xrL6nxTnJ,r9 9734y34J,rxTn+~2.6<:::6<2.+~/p6:::6/p/p6:::9 976/p<6L.WH_g@n|T64\R7wxsDp>V-4XG.`l6Dcu*Z*mI(zc)X)"`)6Cf`9 97CrDQW+$^g+0zl	&D	1Jz
Kg~HfXx`8bP[0k(
R>	S:c&-
Y`                                                                               e\v-XAZ1<'9 970s^0|[D.sj?vS@YI#!)RW>"\BZ=u"vcl=##|Y$)~#xg$C8 	WU%]Y6#xg$C8 #|Y$)~=#=u"vcl. .(W>"\BZYJ=/pRM+T=' #[<E
CEL_c&	S:
R>k([0P8b0&