C     MACHAR.F77.I --- INSERT FILE FOR FORTRAN 77 TESTS
C
C        Eugene Spafford
C        SWT Math Library Test Support
C        School of Information and Computer Science
C        Georgia Institute of Technology
C        Atlanta, GA  30332
C
      INTEGER IBETA,IT,IRND,NGRD,MACHEP,MAXEXP,MINEXP,NEGEP,IEXP
      DOUBLE PRECISION EPS,EPSNEG,XMAX,XMIN
      COMMON /MACHCM/ IBETA,IT,IRND,NGRD,MACHEP,MAXEXP,MINEXP,NEGEP,
     $EPS,EPSNEG,XMAX,XMIN,IEXP
C
      INTEGER I,I1,K1,K2,K3,N,J
      DOUBLE PRECISION ZERO,ONE,TWO,THREE,FIVE,HALF,AIT,PI,A,B,BETA,
     + ALBETA,Z,ZZ,Y,X,XN,R6,R7,W,TEN,EIGHT,TENTH,C,X1,XL,FOUR,DEL
      LOGICAL WHICH
      COMMON WHICH
C
      PARAMETER (ZERO=0.0D0,ONE=1.0D0,TWO=2.0D0,THREE=3.0D0)
      PARAMETER (FIVE=5.0D0,HALF=0.5D0,PI=3.14159265D0)
      PARAMETER (N=5000,XN=5000.0D0,I1=0,TEN=10.0D0)
      PARAMETER (EIGHT=8.0D0,TENTH=0.1D0,FOUR=4.0D0)
C
      DOUBLE PRECISION XEXP,XALOG,XSQRT,RANDX,RANDL,XPOWER
      DOUBLE PRECISION DABS,DMAX1,DBLE$M,DSIGN,DINT$M
      INTEGER LT,INT
      INTRINSIC DABS,DMAX1,DSIGN,LT,INT
      EXTERNAL XEXP,XALOG,XSQRT,RANDX,RANDL,XPOWER,DBLE$M,DINT$M
