n*9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO"t: :imer_dictionaryac"	A,aS$gCTRACE	ac&A@A@,a
@(CTRACEA@	A9 9	"	t"QS	A"%	Usage: rf [-{c|p|t}] [ [-o outf] inf {inf} ]. 	@ QQ8 8QQ	A#	ac*A@#Q@	$CCA
ac,C@HQ	AA
ac.a@A@9 9,aS0iCTRACE	CCA
ac2a@]	@.main@.*n. b	A,aS4fCTRACE,aS6hCTRACEac88 8,a
@0iCTRACEC@cQ	@ ,aS4fCTRACEtQ	AA
	A,aS:jCTRACE|	@ : :,aS:jCTRACEQ	AA
	A,aS<kCTRACE	@ ,aS<kCTRACE	$BCCA
		5 5,aS>CLINE 	@ ,aS@CLINE 		,aSBCOUTLNacD,aK4fCTRACE	@HCCA
acF%: :,aK<kCTRACE	@HCCA
acH-acJacLA@#Q@A@Q	AA
	#B%9 9?acNQ@	""@HCDA
	t"QK		CCA
MT	"@H"IU	"B&"
&CEA
9 9	t&QK	AA
h	t&	QGQQK	A'acPQ	@	CC(t&QK	CC('A
; ;ib	(&]]		t&QS		QS	@ QS	#%C	ac.Q@A@,aSBCOUTLN: :	CCA
,aK4fCTRACE	@HCCA
acR,a
@0iCTRACE$ac2Q@acLA@%Q@A@; ;	BCBA
acTQ@A@	)CBA
	),aS>CLINE 	@ ,aS@CLINE 	A,aSVCLINE acD: :acRA@)C		*s: can't open*n. Tac8A@C@UQ@S	(%--8,aK4fCTRACE; ;	@HCCA
acFacR,a
@0iCTRACEn,aK<kCTRACE	@HCCA
acHzacJacR,a
@BCOUTLN: :2acX	@ acZA@!ST!q!u!v!}!!!!: :!!
!!*!.!	/!f!r_main_* !b#MAPDN 5 5!^#GETARG!`#LENGTH!@#CREATE!f#OPEN!<#CHKARG!h$CLINE !R$CLINE !P$CLINE !T9 9$COUTLN!:$CTRACE!F$fCTRACE!6$gCTRACE!H$hCTRACE!B$iCTRACE!L$jCTRACE!N$kCTRACE!49 9#INITKW!8#PTOC!>#ERROR !D#CANT!J#PRINT !V#PARSE !X#O0TPUT!Z#O0TSTC!\#O0TPUU!d#CLOSE  !j#SWT !l#F$HT
 
"%F*0&$$ ALLDIG9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO	@ ": :QK	AA
	"		A##@HADQK	A
A
QK	AD,aKTYPCOM	CBA
	(# 	A"!0$!$TYPCOM
 
"%($0&" ANDCOD 		acacQ	@		!#S0MTCO!#IFGO
 
"%&"0&~ ( BALPAR9 9	
missing left paren. 	acQ@A@	CBA
acC@		acQ@	A"ac9 9Q@A@	#BCC$#CC%#CC&#CC	A	&A	%A	$	A

acQ@<	#CCA
: :	@ QF	#CCA
	("QO	#CCA
	"@H"WRJacQ@	"A	A
 : :A	                                                                                                             issing parenthesis in condition. c	"A
A
acC@dx		!f!
!(!)% %!;!{!}!#GETTOK!#SYNERR!#OUTSTR!#PBSTR 
 
"%(0&@*
* BRKNXT; ;		acQ@A@	"CC#"CCA	#	A
	A$           acQ@	@HCCA
	A%ac9 9Q@A@%	$t%QK	A
A
	@ $+	@ $.	illegal level number. 1	$AA
9 9acC@2@QK	%%AA
	%@H&t&QK	CC#QK	CC'QK	CC(QK9 9	CC	A	(A	'A	#	A
	$@H$A	A
acQK		CCA
	t&QK	B&acA@&9 9x	%@HADQGQracQ	@racA@	&acA@&		p	%@H%j	%: :	@H%HK	illegal break. QK		CCA

acC@!-	illegal next. 3ac; ;C@42		!@!f!
!;!(!(!(!(!(!#GETTOK!#ALLDIG$ $!#CTOI!&#LABGEN! #SYNERR!"#S0MTCO!$#OUTGO !(#OUTCON
 
"%*0&
"$ BUMPCH9 9	QK	CE"QK	C@A	"	A
		QSQK	CDA
	@ #	A# Q[QS	#	!`!a!z
 
"%($0&@6
$ CASEC : :2HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO	ca9 9
se nesting too deep.,aKCCASE 	CDA
acC@		,akCCASE 	@,aKCCASE ; ;	B,awCCASE ,aSCCASE acQ@	CBA
)acQ@	CEA
2Q< <	AD,aKTYPCOM	CBA
3*	illegal case variable.=acQ@acC@>	@ ,awCCASE 9 9,aS CCASE ,aKCCASE 	,aSCCASE 		<	too many case labels. \,aKCCASE 	; ;	CEA
acC@]		n	compound statement must follow case.t,aKCCASE 	B"ac"Q@: :A@,a
@ CCASE A@",aKCCASE 	,aSCCASE ac$A@QSacQ@		CBA
9 9acC@u		'acQ@ac&ac(Q	@QK	@D"ac*A@"		!@!@!: :!!!
@!a!	{@!@!(@!"#LEX !$#LENGTH!.#LABGEN!: :$CCASE ! $CCASE !$CCASE !*$CCASE !&$TYPCOM!#SYNERR!(#PBSTR !,#SCOPY !0#S0MTCO !2#OUTGO !4#OUTCON
 
"%$0&
3" CASEI : :2HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO	to9 9
o many case labels. ,aKCCASE 	BCDA
acC@		,akCCASE 	@acA@: :,awCCASE ,aSCCASE acQ	@,awCCASE ,aGCCASE 	QacQ	@		!3- -!3!#LABGEN!$CCASE !$CCASE !#SYNERR!#OUTGO !#OUTCON
 
"%("0&t0$ CASES 9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO"g; ;oto (	case stack underflow. ,aKCCASE 	CE",aKCCASE 	@HC@A	"	A
9 9acC@		acQ	@acac a@,awCCASE ,aK"CCASE 	#,aK$CCASE 	@H9 9	#CEA
	t#,aG&CCASE QacQ	@ac(A@	(#//5	t#,aG&CCASE Q9 9acQ	@ac(A@ac(A@,awCCASE ,aK"CCASE 	#t#,aG&CCASE 	Qac Q	@9 9ac*,awCCASE ,aK"CCASE 	@H,aS$CCASE ,aKCCASE 	@H,aSCCASE 		!!9 9
t!)!,t!$CCASE !&$CCASE !($CCASE !*$CCASE !#SYNERR! #OUTNUM!" #OUTTAB!$#OUTSTR!,#OUTCH !.#OUTDON
 
"%*$0&c2& DEFTOK9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO"d9 9efine		acQ	@Q	@	""BCBA
	"CBA
           	acQ	@a@	@HCCA
: :acQ	@Q	@Q@A@acQ	@Q@	ac Q	@A@#,a
@"TABCOM	AA
; ;8	t#,aG$DS$MEM	QNac&Q	@N-	acQ	@Q	@	"9	"CCA
ac(Q	@ac*< <Q	@ac,Q	@ac.Q	@O	"$	!Hc!'tc!#GTOK!$$TABCOM!&$DS$MEM!"#LOOKUP0 0!#EQUAL !#GETDEF! #INSTAL!(#PBSTR !*#LETDIG!,#FOLD!.#G0TSPN!0#MKUNIQ
 
"%v&0&"" DOCODE9 9"DO 	acaca@acA@QSacQ	@acac		!!#LABGEN !#OUTTAB!#OUTSTR!#OUTNUM!#EATUP ! #S0MTCO
 
"%&"0&$ DOSTAT 		acQ	@QK	B"acA@"		!#OUTCON
 
"%($0&$*, EATUP 9 9	@ "#"$	acQ@fA@	"CCA
	"CCA
	$CC%$CC&$CC'$CC($CC9 9	)$CC*$	CCA	*A	)A	(A	'A	&A	%	A
>	"
CCA
acQ@f: :@E	unexpected brace or EOF.K	"BCC%"CCA	%	A
acC@LacQ@fJb	": :	CCA
?p	"CCA
	(#xv	"CCA
	#@H#~y	acacQ@fq	#9 9	AA
k	unbalanced parentheses. 	#A
A
acC@ac		!f!
!; ;&!(!)!*!+!	,!-!;!_!{!|!
}!#GETTOK! #PBSTR  !"#SYNERR!$#OUTTAB!&#OUTSTR!(#OUTDON
 
"%x,0&$ ELSEIF% %	QK	B"acA@"acQ	@		!#OUTGO !#OUTCON
 
"%($0&$" ENDSTC9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO"c: :
all c$end,aKkCTRACE	@HCCA
acac a@ac"		!$kCTRACE!#OUTTAB ! #OUTSTR!"#OUTDON
 
"%""0&j" E0TERS9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO"c9 9all t$entr ("call t$trac (",call t$init"8_9 9main_"@call c$init,aKLfCTRACE	@HCCA
acN,a
@PCTRACEa@87 7	@HCCA
acRacTa@,acVacRacTa@acX,a
@ZhCTRACE	ac\A@acV; ;,aK^jCTRACE	@HCCA
acN,a
@PCTRACEa@8	@HCCA
acRacTa@ac\A@ac\A@: :ac\A@ac\A@acV7acRacTa@ac\A@ac\A@ac\A@acT,a
@PCTRACE9 9ac\A@ac\A@ac\A@acV-,aK`kCTRACE	@HCCA
acN,a
@PCTRACEa@8	@H9 9	CCA
yacRacTa@@acV		!'!)!,!.!0!1!3!X: :$CTRACE!T$fCTRACE!b$hCTRACE!f$jCTRACE!h$kCTRACE!V#EQUAL !Z#OUTTAB!\#OUTSTR!^#OUTDON !`#OUTNUM!d#OUTCH 
 
"%""0&:" E0ITSU9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO"c9 9all t$exit"call t$trac (2, 0),aK0fCTRACE	@HCCA
ac25 5	ac4a@ac6,aK8jCTRACE	@HCCA
ac2ac4a@ac6		!0$fCTRACE!8 $jCTRACE!2#OUTTAB!4#OUTSTR!6#OUTDON
 
"%""0&%D" E0ITPR9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO"c6 6all swt"call t$clup"&call t$trac (2, 0) 9 9,aK:fCTRACE	@HCCA
ac<ac>a@ac@,aKBjCTRACE	@HCCA
ac<ac>a@&ac@2 2ac<ac>a@ac@		!:$fCTRACE!B$jCTRACE!<#OUTTAB!>#OUTSTR!@#OUTDON
 
"%""0&

 $ FOLD: :	A""@HADQK	A
A
QK	CDA
QK	CAA
QK	QS	("
                                         	! !A!Z 
 
"%($0&uD
* FORCOD9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO"I9 9	F(.NOT.(	
missing left paren. acA@QSacA@acQ@A@	CB9 9	A
ac C@		ac"acQ@A@	"CCA

acQ	@1	ac$Q	@ac&9 9	ac(ac*a@	@ ##AA
	"CCA
HM	"CCA
	(#US	"CCA
9 9	#@H#[V		"CB$"CB$A
ac*Q@h	acQ@A@	"EN	invalid for clau9 9se. uac,A@ac,A@QK	@D%ac.A@%	#AA
ac C@v6,ak0CFOR	@5 5	A&'',a_0CFOR	C@A
	t&,aG2CFOR	Qjac4Q	@j	&B&('#	@ t&9 9,aS2CFOR	##AA
acQ@A@	"CCA
	(#HF	"CCA
	#@H#NI: :	"CB$"CB(#A($A
ac6Q@A@,a
@8CFOR	A@&ac4Q@	&&_8;Qk: :	@	!!u!u!f!
!(!)u!;u!_u!(#GETTOK!>; ;#LENGTH!$#LABGEN!:$CFOR!<$CFOR!B$CFOR!&#OUTCON!*#SYNERR!,#EATUP !.#OUTNUM!0#S0MTCO !2#OUTTAB!4#OUTSTR!6#OUTCH !8#OUTGO !@#SCOPY 
 
"%*0&


G"& FORS; ;2HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO	ac8 8Q	@	A"##,a_CFOR	C@A
	t",aGCFOR	QacQ	@	"B"(#	t"9 9,aGCFOR	QacQ	@	AA
acacQ	@ac(QK	@H$	acA@$QK	B: :	$ac A@$,aKCFOR	@H,aSCFOR		!#LENGTH!$CFOR!$CFOR!#OUTNUM!#OUTTAB !#OUTSTR!#OUTDON!#OUTGO ! #OUTCON
 
"%,&0&.$ GETDEF; ;	
missing left paren. 	acQ@A@	CBA
acC@	non-alpha name. ac; ;Q	@Q	@	CBA

acC@,	missing comma in define.2	acQ@A@	CBA
9 9acC@3H1	@ "A#
definition too long.Q	"AA
	#Q_		CEA
acC@R		: :e	
missing right paren.l	#@HADQGQracQ	@r	BCCA
acC@m		: :	#@HADQK	CCA
	("	#@HADQK	CCA
	"@H" k	(#QQ_1 1	#@HAD@ QS		!f!(!)!,!'t!#GTOK!#NGETCH!#SYNERR
 
"%$0&C<$ G0TSPN9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO!; ;"subroutine"	function		@HCCA
ac&Q	@A@,a
@(CTRACE; ;A@,aK*fCTRACE	@HCCA
ac,Q	@,a
@.iCTRACEac0A@,a
@.iCTRACE,ak2hCTRACE: :	@A,aS4gCTRACE	@ 	ac6Q	@a@	@HCC"	ac6Q	@a@	@HCCA	"	A
	A9 9	?*		!C!
C!,$CTRACE!.$fCTRACE!8$gCTRACE!6$hCTRACE!2$iCTRACE!: #EQUAL !*#SCOPY !0#PUTLIN!4#PUTCH 
 
"%($0&58
( GETTOK9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO"i9 9nclude	,aKCLINE 	AA
acQ	@Q	@	""BCBA
acQ	@a@	AA
: :	"		includes nested too deeply. 	acQ@A@	#,aKCLINE 	CDA
ac: :C@8	#CC$#CCA	$	A
ac Q@A@Q@A@ac"Q@A@#	%@ t%QS; ;H	can't open include. file name: *s*n.^	ac$Q@A@	&CCA
acC@_ac&A@C@i: :Q@{,akCLINE 	@	@ ,awCLINE ,aS(CLINE 	&,aS*CLINE =acQ	@7 7Q	@	"                                            aKCLINE 	@HCEA
,awCLINE ,aG*CLINE 	Qlac,Q	@l!: :,aKCLINE 	@H,aSCLINE 		"!q!}!5!!5!8 85!f!"!'5!&#EQUAL !.#OPEN!,#INDEX !$#DEFTOK!"$CLINE !2$CLINE !4 $CLINE !(#SYNERR!*#SCOPY !0#PRINT !6#CLOSE 
 
"%(0&


YB, GTOK9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO"o9 9rif ("andif (	ac A@"	"%		%	BCCA
		#9 9	t",aK"TYPCOM	#	"QS	#CCA
	A$#CBA
	#CBA
%	#CBA
9 9*	#CBA
/4	"CCA
	$@H$:	$Q_	C@A
	$@HAD"QSD>; ;ac A@"	BCCA
		#R	t",aK"TYPCOM	#U	($!!5ac$A@"		#: :	#CCA
	A$#CCA
	$Q_	C@A
	$@HAD"QSuac A@"	BCCA
; ;		#	t",aK"TYPCOM	#	($kkoac$A@"		#h	#	CC%#
CCA	%9 9	A
	#QS		$missing quote.%	$@HADQGQac Q	@	#CBA
QK	@H$CA9 9	A
ac&C@&	#QSac$A@;B	$@HADQK	CCA
	$@HADQK	CCA
9 9X	$@H$$@HADQGQac Q	@	CCA
es	contin of literal must begin with quot9 9e.u	$@H&t&QKQ_	CBA
ac&C@vQK	t&QSac$A@N	$@H$a: :	missing quote.'	$@H&t&QK	CCA
ac&C@(QK	t&QSac$A@"8&O	($9 9%%F	($K	#CCA
ac A@"	CBA
RY		#QS		$Q; ;	#CCA
ac A@"	CCA
		#ac(a@		QS		$nac$A@"ac*Q	@9 9A@$zf	#CCA
ac A@"	CCA
		#ac(a@		QS		$9 9ac$A@"ac*Q	@A@$
	#                                                                   C%#CC'#CC(#CC)#CCA	)A	(A	'A	%9 9	A
ac*Q	@A@$F		$M)aLc	$@HAD@ QS	#*	!Y!Y!9 9	!
! !        !!	"!#!$!&!
'Y!)!0!<!=!>: :Y!_!aY!|!~Y!'t!'uY!6#NGETCH!8$TYPCOM!:#PUTBAK!<#SYNERR !>#PBSTR !@#RELATE
 
"%4,0&'& HASHFN: :	QK	@HADQK		"CA#"CD#A
	"$		"CA#"CD#A
	"$( (		$"	$	! !@'!!A!Z!a!z
 
"%,&0&" IFCODE- -	acacA@QSacQ	@		!!#LABGEN!#S0MTCO!#IFGO
 
"%&"0&

&" IFGO: :"	IF(.NOT.	acaca@acac A@ac"Q	@		!)!#OUTTAB! #OUTSTR! #BALPAR!"#OUTCH !$#OUTGO 
 
"%&"0&" INITDF1 1	acQ	@A@Q@A@acQ@Q@		!!.!#PTOC!#MKDEF 
 
"%:"0&^8$ INITKW9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO"s9 9top"subroutine""	function",integer"4rea9 9l":double"Bcomplex"Jlogical"R
dimension9 9"\equivalence"hcommon"p
parameter"zexterna9 9l"data"
trace"goto"return"strin: :g"&case",for"0repeat"8until">do"B9 9if"Felse"Lwhile"Rbreak"Xnext"^andif: :"dorif"j	implicit"tsaveaczA@	@ ,aS|COUTLN	A; ;,aS~CLINE 	@ ,aSCDEFIO,aSCFOR,aShCSTR		""CAA
	"t",aSTYPCOM	("9 9		""CAA
		t",aSTYPCOM	("!!%		""CAA
		t",aSTYPCOM; ;	("//3		""CAA
		t",aSTYPCOM	("==AacA@	,aS
TABCOMac; ;a@BA@
,a
@
TABCOM	aca@FA@,a
@
TABCOM	aca@LA@,a
@
TABCOMaca@>; ;A@,a
@
TABCOM	aca@RA@,a
@
TABCOM	aca@XA@,a
@
TABCOM	aca@,A@7 7,a
@
TABCOM	aca@0A@                                            a
@
TABCOM	aca@A@,a
@
TABCOM	aca@&A@7 7,a
@
TABCOM	aca@8A@,a
@
TABCOM	aca@dA@,a
@
TABCOM	aca@^A@7 7,a
@
TABCOM	aca@A@,a
@
TABCOM	aca@A@,a
@
TABCOM	aca@A@7 7,a
@
TABCOM	aca@,A@,a
@
TABCOM	aca@4A@,a
@
TABCOM	aca@:A@7 7,a
@
TABCOM	aca@BA@,a
@
TABCOM	aca@JA@,a
@
TABCOM	aca@RA@7 7,a
@
TABCOM	aca@\A@,a
@
TABCOM	aca@hA@,a
@
TABCOM	aca@pA@7 7,a
@
TABCOM	aca@zA@,a
@
TABCOM	aca@A@,a
@
TABCOM	aca@
A@7 7,a
@
TABCOM	aca@A@,a
@
TABCOM	aca@"A@,a
@
TABCOM	aca@jA@9 9,a
@
TABCOM	aca@tA@,a
@
TABCOMacA@	,aSTABCOM	A#@ t#,aSCSYM	A#9 9	%aVV	,continue. precision.implicit. parameter.external. dimension.equivalence.function. subrou; ;tine. a		,aSpCSYM*acC@bacA@acC@gacA@acA@acC@lacC@q: :$acC@vacC@{acA@acC@acC@acC@	@ ,aSCCASE ,aSCCASE 		9 9!	N!!N!!0!9!AN!Z!aN!z!N!
9 9(!(!(!(!(!(!(!        (!(!(!( !(!!("!(#!6 6($!(%!((!2HNcomplex.'include.;integer.#logical.!$CDEFIO! 5 5$CFOR!$CLINE !$COUTLN!.$CSYM!0$pCSYM!4$CCASE !6$CCASE !"$hCSTR!,, ,$TABCOM!($TABCOM!$$TYPCOM!&#MKTABL!#DSINIT!*#ENTER !2#INITDF
 
"%$$0&$ INSTAL; ;2HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO	ac: :Q	@	B"acA@"	#	acQ	@A@,a
@DS$MEMA@#acQ	@A@#,a
@TABCOM		- -!!$TABCOM!$DS$MEM!#LENGTH!#DSGET !#SCOPY !#ENTER 
 
"%*$0&3$ LABELC9 9	                                                                                       arning: possible label conflict. acQ	@	CCA
	uQK	CC"QK	CC"A
9 9acC@'	acQ	@ac		!3!!2!3!#LENGTH!#SYNERR! #OUTSTR!#OUTTAB
 
"%($0&$ LABGEN !YX		"Q[	"	
 
"%($0&&$ LETDIG9 9	uQK	A
A
		acQ	@	CBA
		QK	CCA
	uQK	CCA
9 9	uQK	CCA
	uQK	CDA
$QK	CAA
+QK		"1QK	
; ;	CCA
	uQK	CCA
<	uQK	CCA
C	uQK	CDA
JQK	CAA
QQK: :	"WQK	CCA
	uQK	CCA
a	uQK	CCA
h	uQK	CDA
o: :QK	CAA
vQK	"|		[6acA@"Q	@A@	#	!!!!9 9!	 !f!0!9!A!
B!D!E!G!I!L!T!Z !$#ITOC!"#LENGTH
 
"%($0&

<& LEX ; ;2HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO	ac9 9Q	@A@	""CBA
	"CC#"CC$"CC%"BCC	A	%A	$A	#	A
	"	#	"CC9 9	A
		"*	acQ	@A@",a
@TABCOM	AA
		"8-$!f!
!0 0;<!{!}<!'u!(!(<!$TABCOM!#GETTOK!#LOOKUP
 
"%*&0&"( MKDEF : :2HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO	un: :
ique table overflow.,aKpCSYM	CEA
acC@		acQ	@	"	acQ	@A@"6 6	#$t#,aKCSYM	%%A
A
	%$t%,aKCSYM	%*-	@ ,awpCSYM,aSCSYM9 9,aSCSYM,aKpCSYM	@D"	acQ	@A@,a
@CSYMA@",aKpCSYM	t$,aSCSYM	&5 5acQ	@,a[pCSYM	,aSpCSYMacQ	@	"	acQ	@A@"	#t#,aKCSYM7 7,awpCSYM,aSCSYM	&,aSCSYM,aKpCSYM	@D"	acQ	@A@,a
@CSYMA@": :,aKpCSYM	t#,aSCSYMacQ	@,a[pCSYM	,aSpCSYM		!!!P3 3!p!#HASHFN!$CSYM!$CSYM!$pCSYM!#SYNERR!#LENGTH! #SCOPY 
 
"%.(0&$ MKSEEN< <	A""CAA
	"@HADQK	AA
	"@HADQK	t"QSk	("	@ t"QSk: :	"@H#@HCDA
		Qm&acQ@lA@#Q@A@	@HCCA
	#""@HCEA
	t"QGk: :	QRacQ	@R	@HCCA
	("@"#CAA
		t"QSk	("NNR>K	"@H":Z9 9	can't make name unique. _	"@HCCA

acC@`7p*uacQ	@Q@lacQ@l: :	A@Q	@A@		!!!0!a!#SEEN!#BUMPCH!#SYNERR!#MKDEF ! #SCOPY 
 
"%x$0&,$ MKUNIQ; ;	acQ	@	"uQK	CC#"CC##"CEA	#	A
acQ	@A@"Q	@A@	AA
5 5	acQ	@A@"$		!,!,!!0!#SEEN!#LENGTH!#MKSEEN
 
"%($0&H & NGETCH7 72HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO	< <,aKCDEFIO	A	A
,awCLINE ,aGCLINE QjacQ@Q	@j,aSCDEFIO,awCLINE 9 9,akCLINE 	@BCCA
	A,aSCDEFIO		,aSCDEFIO	A",aKCDEFIO	##A7 7	A
	t#QK	t",aSCDEFIO	("@#@H#),#,awCDEFIO,aKCDEFIOQS6 6,aKCDEFIO	@H,aSCDEFIOQK	$	!H!#GETLIN!$CDEFIO!$CDEFIO! $CDEFIO!$CLINE !$CLINE !$CLINE 
 
"%&0&$ ORCODE: :		acA@QS	@D"acA@"acQ	@acacQ	@		!!#LABGEN!#OUTGO ! #OUTNUM!#S0MTCO!#IFGO
 
"%*$0&
" OTHERC$ $	acacQ	@ac		!#OUTTAB!#OUTSTR!#EATUP 
 
"%&"0&%$ OUTCH 7 72HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO	7 7,aKCOUTLN	CDA
ac	A"	t",aSCOUTLN	A"%

		,aSCOUTLN		9 9,aSCOUTLN,akCOUTLN	@QK,awCOUTLN,aSCOUTLN		!!%!H( (%! !*%!$COUTLN!$COUTLN!$COUTLN!#OUTDON
 
"%($0&"" OUTCON: :"	CONTINUE	QK	AA
acQ	@acaca@ac 		!#OUTNUM!                                                                   OUTTAB!#OUTSTR! #OUTDON
 
"%&"0&" OUTDON5 52HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO; ;,aKCOUTLN	AA
				,awCOUTLN,aSCOUTLN	@ ,aSCOUTLNac,a
@COUTLN9 9,a
@COUTLN	@ ,aSCOUTLN		!
!$COUTLN!$COUTLN!$COUTLN!$COUTLN! #PUTLIN
 
"%""0&" OUTGO : :"GOTO	acaca@acQ	@ac		!#OUTTAB!#OUTSTR!#OUTNUM!#OUTDON
 
"%&"0&$ OUTNUM: :	acQ	@Q@A@	"A#t#QGQacQ	@	A#$"		!
!#ITOC! #OUTCH 
 
"%4$0&G"& O0TPUU9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIOac; ;A@ac	A""CAA
	t",aKCSYM	##A
A
	t#,aKCSYM	A
A
acA@ac; ;	t#,aGCSYMQacQ	@acA@	t#,aKCSYM	@D$t$,aGCSYMQacQ	@ac6 6	t#,aKCSYM	#                           	("		!G! !CG!$CSYM!# #$CSYM!$CSYM!#OUTCH !#OUTDON!#OUTTAB! #OUTSTR
 
"%(&0&]B" O0TPUT9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO"s9 9ubroutine t$init""integer*2 sp, numrtn"8integer9 9*4 record (4, "Ninteger*4 stack (4, "d	common /t9 9$prof/ numrtn, record"common /t$stak/ sp, stack; ;"
numrtn = "(return"0endac4ac6a@ac8ac4ac6a@"; ;ac8ac4ac6a@8ac:,a
@<hCTRACEac>A@ac8ac4ac6a@Nac:,a
@<hCTRACEac>; ;*A@ac8ac4ac6a@dac8ac4ac6a@ac8ac4ac6a@ac:,a
@<hCTRACEac8ac4: :ac6a@(ac8ac4ac6a@0ac8		!)]!>$hCTRACE!6#OUTTAB!8#OUTSTR!:#OUTDON!< #OUTNUM!@#OUTCH 
 
"%""0&e$" O0TSTC9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO"S9 9UBROUTINE C$INIT""INTEGER LIMIT"0INTEGER*4 COUN9 9T("BCOMMON /C$STC/ LIMIT, COUNT"^
INTEGER I"h9 9
DO 1 I=1,"r   COUNT(I)=0"	LIMIT = "
RETURN9 9"END$acaca@acacaca@"acacaca@0ac,a
@CLINE ; ;-ac A@acacaca@Bacacaca@^acacaca@hac,a
@CLINE ac; ;acA@acaca@racacaca@ac,a
@CLINE acacaca@
acac: :	aca@ac		!e!)e! $CLINE !#OUTTAB!#OUTSTR!#OUTDON!#OUTNUM!" #OUTCH 
 
"%""0&S( OUTSTR9 9	A""@HADQK	A
A
QK		#CB$#CB$A
acA@#	%acA@%	("@"; ;	&&@HADQK	#CBA
	(&%%-	&"%acA@%acA@	"&C@A
	"@HADQG: :	QacQ	@	("<<@ 	("
		!"!'!H!#MAPUP !#OUTCH ! #OUTNUM
 
"%.(0&" OUTTAB5 52HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO: :,aKCOUTLN	C@A
,akCOUTLN	@	,awCOUTLN,aSCOUTLN		!!  !$COUTLN!$COUTLN
 
"%""0&r^* PARSE 9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO	A"	9 9QJ	@ #acQ@d	$$BCBA
	$CCA
ac	Probable unmatched '(' or '{' ; ;in last routine.,aKgCTRACE	@HCC%$CB%A
acac	@ ,aSgCTRACE	"@HCEA
ac: :C@	A"G;		$CB%$CB%A
	t"QK	&t"QKI	CCA
QK	@D'acA@'9 9	"@H"\b	&t"QSW	"@HCEA
	#CB%t"QKI	CC(QKH	CC(%A
wQK~: :	B'acA@'		$CCA

ac A@)	$	CCA
	t"QKI	CCA
QGQ.; ;ac"Q	@.'	illegal else. 1	t"QKI	CBA
acC@2?0 	$
CCA
; ;ac$A@)I	$CCA

ac&A@)S	$CCA

ac(A@)]	$CCA
ac*: :A@)g	$CCA
	t"QKI	CC%QKI	CCA	%	A
QGQ.ac,Q	@.ac9 9Q@d	$	illegal andif.acC@q	$CCA
	t"QKI	CC9 9	%QKI	CCA	%	A
QGQ.ac.Q	@.A@).	illegal orif. :acC@;; ;9 	$CCA

ac0A@)K	$CCA
ac2Q@d
UPFlbXND	$CCA
9 9^	$	CCA
d	$
CCA
j	$CCA
p	$CCA
v	$9 9	CCA
|	$CCA
	$CCA
	$CCA
	$CCA
; ;	}wqke_	stack overflow in parser. 	("@"CEA
ac4C@)	$t"QSI	)QS9 9	$#acQ@d	$	$CCA

ac6Q@dA	$CCA
ac8ac6Q@dK: :	$CCA
	t"QKI	CCA
	"@H"^	
illegal right brace.cacC@db; ;W	$                                                                   CA
ac:ac8ac6Q@dac<A@	'acA@'w	$CC%$CCA	%	A
; ;ac>A@"Q@JQ@A@$	$CCA
ac8ac@acBac6Q@dac<A@	'acA@': :$	$CCA
ac8ac6Q@dac<A@	'acA@'=8	rRF	$#acQ@d	$9 9acDA@"Q@JQ@A@$<	unexpected EOF. _	"@HCBA
acC@`l		!9 9r!r!dr!{!}r!(!(!	(!(!(!(!(!: :(!
(!(!(!( !(!!("!(#!        ($!(%!((r!(#LEX !T#LABGEN!,< <$gCTRACE!*#S0RING!.#S0RINH!0#E0TERS!2#SYNERR!4#OUTCON!6#CASEI !8#IFCODE!:#ELSEIF!<#FORCOD9 9!>#WHILEC!@#DOCODE!B#REPCOD!D#ANDCOD!F#ORCODE!H#CASEC !J#LABELC!L#ERROR !N#OTHERC!P# ##S0MTCO!R#E0ITSU!V#BRKNXT!X#ENDSTC!Z#E0ITPR!\#UNSTAK
 
"%Z*0&6$ PBSTR ; ;2HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO	ac; ;Q	@	"too many characters pushed back.	"AA
,akCDEFIO	@,aKCDEFIO	CEA
9 9acC@#	"@HADQK,awCDEFIO,aSCDEFIO	"@H"		!6!#LENGTH !$CDEFIO!$CDEFIO!#ERROR 
 
"%($0&." PUTBAK: :2HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO	to; ;o many characters pushed back.,akCDEFIO	@,aKCDEFIO	CEA
acC@ac	@ ac9 9A@!QK,awCDEFIO,aSCDEFIO		!ST.!.!$CDEFIO!$CDEFIO                                                                 #SYNERR!#SWT !#F$HT
 
"%&"0&Mh$ RELATE9 9" .GE. " .GT. "  .LT. "( .LE. "0 .NE.: : "8 .EQ. "@ .OR. "H .AND. "P .NOT. 	: :	uQGQacXQ	@	CBA
acZQ	@QK	CCA
	uQK	CCA
ac\: :a@A@Q	@A@ac\a@A@Q	@A@)QK	CCA
	uQK9 9	CCA
ac\a@(A@Q	@A@Aac\a@ A@Q	@A@L:QK	CC: :	"QK	CCA	"	A
	uQK	CCA
ac\a@0A@Q	@A@kac\a@P9 9	A@Q	@A@vdQK	CCA
	uQK	CCA
ac\a@8A@Q	@A@9 9	@ uQSQK	CCA
ac\a@HA@Q	@A@$QK	CC: :	A
ac\a@@A@Q	@A@5	@ uQS@/W4ac^Q	@	BQS		!; ;M!!!&M!<!=!>M!|!~!`#NGETCH!f#LENGTH!b#PUTBAK!d#SCOPY 
 
"%,$0&" REPCOD: :	acA@acA@QSacQ	@acQk	@	!!!#LABGEN!#OUTCON! #S0MTCO
 
"%&"0&

F( SEEN; ;2HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO	ac; ;Q	@Q	@	"t",aKCSYM	##A
A
	t#,aGCSYMQQK		@HCC$,aKCSYM	A
A	$: :	$	acQ	@Q	@	@HCC$A
	A%t#,aKCSYM	@D&ac,a
@CSYM	A@&Q	@A@	%5 5		*	t#,aKCSYM	#	@ %<!F!#HASHFN!#EQUAL !$CSYM!                                                                    CSYM!$CSYM!#SCOPY 
 
"%6(0&." S0MTCO9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO"C; ;ALL C$INCR (,aKkCTRACE	@HCCA
ac ac"a@ac$,a
@&CLINE ac(A@; ;ac*		!)!($CLINE ! $kCTRACE!"#OUTTAB!$#OUTSTR!&#OUTNUM!*#OUTCH !,#OUTDON
 
"%""0&<& S0RING9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO"i: :nteger	string declared after executable statement. ,aKgCTRACE	AA
acC@9 9			variable must follow string declaration.!acQ@	"Q	AD,aKTYPCOM	CBA
: :acC@"		C	too many string definitions.Iac ac"a@ac"Q@ac$A@ac&9 9Q@	B#,a[(hCSTR	BCEA
acC@J	@ ,aS(hCSTR		r	quoted string must follo: :w string decl.{,aK(hCSTR	B$	ac*Q@A@,a
@,CSTRA@$	#,a[(hCSTR,aS(hCSTR5 5acQ@	"Q	CB%Q	CB%A
acC@|,ak(hCSTR	@@ ,aw(hCSTR9 9,aS.CSTR		2	too many string definitions.@ac&Q@	@H#ac0A@#ac$A@ac29 9	#,a[(hCSTR	BCEA
acC@A	@ ,aS(hCSTR		f,aK(hCSTR	B$	ac*Q@A@: :,a
@,CSTRA@$	#,a[(hCSTR,aS(hCSTR	@ ,aw(hCSTR,aS.CSTR		!!!8 8"!'!(!)!a!h!.#LENGTH! $gCTRACE!6$CSTR!4$CSTR!0; ;$hCSTR!&$TYPCOM!"#SYNERR!$#LEX !(#OUTTAB!*#OUTSTR!,#OUTCH !2#SCOPY !8#OUTNUM!:#OUTDON
 
"%&0&H*$ S0RINH9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO"d; ;ata	A"",a_hCSTR	CAA
acaca@	t",aGCSTRQacQ	@acQ	@; ;	"B"ac A@	t",aGCSTRQQK	A
A
ac"Q	@ac A@	("""+ac"9 9A@ac A@ac$	("@	@ ,aShCSTR		!H!,!/H!"#LENGTH! ) )$CSTR!$hCSTR!#OUTTAB!#OUTSTR!$#OUTCH !&#OUTNUM!(#OUTDON
 
"%&$0&+$ SYNERR9 92HDS$MEMTYPCOMTABCOMiCSTRlCTRACECCASE qCSYMhCOUTLNCLINE ICFORCDEFIO	A"9 9	",a_CLINE 	CAA
	t",aGCLINE QacQ	@A@A@	("	 (*s5 5): *p*n.	acA@C@,a
@CTRACEQ	@		!q+!+!$CLINE ! $CLINE !$CTRACE!#PUTDEC!#PRINT 
 
"%*$0&`$$ UNSTAK9 9	QK	@HCEA
QK	@HADQK	CCA
QK	@HADQK		CC"QK	CC: :	"A
                           !QK	@HADQK		CC"QK	CC"A
QGQacQ	@"2QK; ;	@HADQK	CCA
QGQacQ	@EQK	@HADQK	CCA
QK	@HCEA
; ;QK	@HQS^QK	@HADQK	B#acA@#XQK	@HADQK	CCA
QG< <QacQ	@zQK	@HADQK	CCA
QGQacQ	@QK	@HADQK9 9	CCA
QGQacQ	@ QK	@HADQK	CCA
QGQacQ	@Q	@	9 93QK	@HADQK	CCA
QGQacQ	@QK	B#acA@#H>)pN9 9QK	@HQS;		!{!(!(!(!(!(!(!("!#CASES ! #OUTCON!#DOSTAT!#WHILES! #FORS!"#UNTILS
 
"%2$0&'$ UNTILS< <		acQ	@QK	CCA
acQK	@H"acA@"
QK	@H"acA@"QK. .	B"acA@"		!(!#OUTNUM!#S0MTCO!#IFGO!#OUTGO !#OUTCON
 
"%*$0&$ WHILEC; ;	acA@acA@QSacQ	@acQK	B"acA@"		!!!#LABGEN !#OUTCON!#OUTNUM!#S0MTCO!#IFGO
 
"%($0&$ WHILES% %		acQ	@QK	B"acA@"		!#OUTGO !#OUTCON
 
"%($0&