": :zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUTacacQ@A@	%9 9
acQ@
acac!!.!#READLN!#INITI0!#PROCE0!#RESET0 !#SWT 
 
"%P"0&KX$ OPTIO09 9zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT"Usage: fmt [-s9 9] [-p first[-last]] {pathname}">sp<rs>	acFa@>Q@9 9	CacHa@Q	A
	A,aSJCOPTS Q	A
Q)	ADQGQf9 9acLQ	@fQ@HA@	A"	acNQ@HA@",aSPCPAGE 	t"QKG	C	("@acNQ@H9 9A@",aSRCPAGE 6	t"QKG	A
acHa@E		!}K!K!-K!T* *$CPAGE !V$CPAGE !N$COPTS !R#CTOI!J#PARSCL!L#ERROR !P#CTOC
 
"%$0&X&$ INITI09 9zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT"finfbrl9 97sbp-spin)rm0tice2ulhefo%plbf,sode9 97en.ta/tcccc2hy nhne'polmerlt1tl(rc9 97adna!ns*rs&pnex"nx3xb+sbm1m2m3m4	dv9 91mcmoeh
ef$oh#of4ps5oo6eo7if8am9it"t99 97	!%)-159=AEIMQUY]aeimquy}	!%)-159=AEIMQUY9 9]a".06nsplpn	lnpo
lsinrmtilmccc29 97tcml!m1"m2#m3$m44ltdaydatetimetcpnnum9 97setaddldaternRNletterLETTERvertspace%e9 97ven&odd'cap(small)plus*minus+header,evenheader-9 97oddheader.footer/evenfooter0oddfooter1cmp5icmp2bo9 9$ttom3topbfulcusubsup7it"^6	!%)-19 9)59=AEIMRX^dinsz~
#(-4:AIU`ht
#(-"	aalphaAA9 97LPHAbbetaBBETAggammaGGAMMAddeltaDDELTAeepsilonE9 97EPSILONzzetaZZETAnetaNETAhthetaHTHETAiiotaIIOTA9 97kkappaJKAPPAllambdaLLAMBDAumuUMUvnuVNUxxiXXI9 97oomicronOOMICRON3pi4PIrrhoRRHOssigmaSSIGMAttau9 97TTAUqupsilonQUPSILONpphiPPHIcchiCCHIypsiYPSIwo9 97megaWOMEGA8infinity;integral9INTEGRAL0largerbrace9 971largelbrace2tilde5backslash6uparrow7downarrow^nab9 97la~not:partial=proportionalbsBS bl
hlfhlr<p9 97sset>sset?le]ge@imp[exist}nexist`univ{or_and\9 97ne|isoMapeqflfloorjrfloormlceilFrceil!small0"sm9 97all1#small2$small3%small4&small5'small6(small7)s9 9&mall8*small9+scolon,dquote.dollar""`")07@I9 97OUZ_fmsy#'+/8AEINSZafkt} ")3=GTahs|*.26;; ;@GMQUZaiosx|%-5=EMU]emu}acA@acA@,aSTABCOMac< <A@,aS
TABCOMacA@,aSTABCOM	A"	("@	"a't	@t"aKt	ADaG; ;QaGQacQ	@Q	@,a
@TABCOM	A"	("@7	"a'^	@t"aK^9 9	ADaG.QaG-QacQ	@Q	@,a
@
TABCOM8=	A"	("@V	"a'"9 9	@t"aK"	ADaGQaGQacQ	@Q	@,a
@TABCOMW\	A,aSCPARAM		9 9,aSCPARAM		,aSCMISC 		,aSCMISC 	A,aSCMISC ,aSCMISC 	@ ,aSCPARAM7 7,aSCPARAM	A,aS 	CPARAM		,aS"
CPARAM,aS$CPARAM	@ ,aS&CPARAM,aS(CPARAM5 5,aS*CPARAM,aS,CPARAM	A,aS.CPARAM,aS0CPARAM	@ ,aS2CPARAM,aS4                                                                   PARAM7 7,aS6CPARAM,aS8CPARAM,aS:CPAGE ,aS<CPAGE 	A,aS>CPAGE 	@ ,aS@CPAGE 		9 9,aSBCPAGE 		,aSDCPAGE 		,aSFCPAGE 			,aSHCPAGE ,aSJCPAGE 		,aSL	CPAGE 5 5,a_DCPAGE ,a[JCPAGE 	A,aSN
CPAGE 	@ ,aSPCPAGE ,aSR9CPAGE ,aSTgCPAGE : :,aSV                     CPAGE 	A,aSXCOUT	@ ,aSZCOUT,aS\COUT	A"@ t",aS^8CMISC 	A"%
g\\6 6	A"M=@@HC	At",aS`2CMISC n	@ t",aS`2CMISC s	A"%~hh		9 9,aSbCMISC 		,aSdCMISC 	@ ,aSfCMISC 		,aShCMISC ,aSjCMISC 	@ ,aSlCPARAM; ;	A,aSnCMISC 	@ ,aSpCOPTS 	A,aSrgCMACRO		,aStfCMACRO	A,aSveCMACRO,aSxCMACRO7 7,aSzCMACRO		                                            aS|1CMISC 	A"	t",aS~LCMISC 	A"%1&&	@ ,aSCMISC 	A5 5,aS2CMISC acac,a
@2CMISC ,a
@CMISC A@	BC,akCMISC 	@	: :,awCMISC ,aS
CMISC 	A,aShCMISC C,ak2CMISC 	@ac,a
@CMISC O		9 9!        u!v!}X!!	!X!X! X!<X!BX!d9 9X!X!	X! X!.X!4X!
HX!`X!bX!z!5 5'X!n$COUT!p$COUT!r$COUT!V$CPAGE !X$CPAGE !R$CPAGE !T$CPAGE !P9 9$CPAGE !Z$CPAGE !\$CPAGE !^$CPAGE !`$CPAGE !b$	CPAGE !d$
CPAGE !f$CPAGE !h9 9$9CPAGE !j$gCPAGE !l$                     CPAGE !F$CPARAM!&$CPARAM!($CPARAM!2$CPARAM!:$CPARAM!>9 9$CPARAM!$CPARAM!4$CPARAM!<$CPARAM!6$	CPARAM!8$
CPARAM!N$CPARAM!H$CPARAM!L9 9$CPARAM!D$CPARAM!@$CPARAM!B$CPARAM!J$                                                                   PARAM!.$CMISC !0$CMISC !|$CMISC !9 9$CMISC ! $CMISC !"$hCMISC !$LCMISC !$1CMISC !$2CMISC !v$2CMISC !t$8CMISC !9 9$CMISC !~$CMISC !$CMISC !*$CMISC !,$CMISC !z$CMISC !x$CMISC !$CMISC !9 9$CMACRO!$CMACRO!$eCMACRO!
$fCMACRO!$gCMACRO!$COPTS !$TABCOM! $TABCOM!"* *$TABCOM!#GETARG!#MKTABL!#DSINIT!$#ENTER !#OPTIO0!$#NEWINP
 
"%($0&