l2, COMAND: :zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT	acQ	@	"acQ	@; ;A@#	$acQ	@	@DC	"%ac	A,aSCPARAMac	@ ,aSCPARAM< <	@ ,aSCMISC ac#ac,a
@CPARAMA@$A@#A@A@A@)ac,aK CPAGE 5 5	Aac"A@>ac,a
@$CPAGE A@$A@#,a
@$CPAGE A@A@8ac: :,aK CPAGE 	Aac"A@W	A&&@HADQK	%f	%ie	%lh	A
k: :	(&^^m	&@HADQK	C	(&qqx	ac&Q	@A@&	$&@HADQK	C9 9	(&
	ac&Q	@A@&	'A	,aK$CPAGE 	',aK$CPAGE 	M<'@&	(&@; ; 	&$$Q%ac"A@!ac,aK(CPARAM	A&acA@(A@$A@#A@A@A@ac"9 9A@(1ac,aK*
CPARAM	@H)ac,a
@,CPARAMA@$A@#A@A@A@),aK,CPARAM6 6,aS.CPARAMDac,aK.CPARAM	B)ac,a
@*
CPARAMA@$A@#A@A@)A@; ;,aK*
CPARAM,a_0	CPARAM	B)ac,a
@2CPARAMA@)A@	,a
@2CPARAMA@A@]ac: :ac,a
@.CPARAMA@$A@#A@A@,a
@*
CPARAMacac,a
@4CPARAMA@$A@#9 9A@A@A@ac,a
@6                                                                   PARAMA@$A@#A@A@A@(ac,a
@8CPARAMA@$9 9A@#A@A@A@7ac:Q	@,a
@<CPAGE A@
ac>,a
@<CPAGE A@,a
@@9CPAGE 6 6A@Fac:Q	@,a
@BgCPAGE A@
ac>,a
@BgCPAGE A@,a
@D                     CPAGE A@Y: :,aKFCPAGE ,a[HCPAGE ,a[JCPAGE ,a[L	CPAGE 	B)ac,a
@NCPAGE 	A@$A@#A@: :A@)A@,aKNCPAGE ,a_JCPAGE ,a_L	CPAGE ,aSP
CPAGE lac,a
@RCPARAMA@$; ;A@#A@A@A@ac:Q	@,a
@TCMISC A@	AacV,a
@TCMISC &acXQ	@: :+acZQ	@0ac\Q	@,a
@^CMISC A@5ac\Q	@,a
@`CMISC A@>ac\Q	@9 9,a
@bCMISC A@G	A,aSdCMISC P	@ ,aSdCMISC T,aK(CPARAM	AXac; ;	@ *acA@*A@$A@#A@A@A@	*,a[ CPAGE 	@H,a_P
CPAGE 	C,aK CPAGE 7 7	Avac"A@z\acac,a
@fCPARAMA@$A@#A@A@A@acac9 9,a
@hCPARAMA@$A@#A@A@A@acac,a
@jCPARAMA@$A@#A@A@A@9 9!acac,a
@0	CPARAMA@$A@#A@A@,a
@*
CPARAM,aK*
CPARAM,a_0	CPARAM	B: :	)ac,a
@2CPARAMA@)A@	,a
@2CPARAMA@A@2	A&&@HADQK	%b	%: :ea	%hd	A
g	(&ZZi	&@HADQK	C	(&mmt	&@HADQK; ;	%	%	(&@	(&@	&@HADQK	%    W	A
aclQ	@A@&; ;	)acnA@)A@    ac,a
@2CPARAM A@$A@#A@A@A@acac:Q	@Q@2A@
9 9acpQ@2,a
@rCPAGE Q@A@
actQ@/ac\Q	@,a
@vCMISC A@Hac\Q	@9 9,a
@xCPARAMA@,aKxCPARAM	%_Q	%b^	%ea		,aSxCPARAMd		8 8,aSxCPARAMh	A,aS(CPARAMl	@ ,aS(CPARAMpac,a
@$CPAGE A@$A@#8 8,a
@$CPAGE A@A@tacaczac|aczac:Q	@,a
@TCMISC A@	AacV; ;,a
@TCMISC ac~,a
@2CMISC ,a
@TCMISC 
A@A'',ak2CMISC 	@acV9 9,a
@TCMISC &ac|.	A,aSCMISC 1	@ ,aSCMISC 5,aKNCPAGE : :,a_FCPAGE ,a_JCPAGE ,a_L	CPAGE 	@H)ac,a
@HCPAGE A@$A@#A@A@A@)9: :,aKNCPAGE ,a_HCPAGE ,a_JCPAGE ,a_L	CPAGE 	@H)ac,a
@FCPAGE 	A@$A@#A@9 9A@A@)R,aKNCPAGE ,a_HCPAGE ,a_FCPAGE ,a_L	CPAGE 	@H)ac,a
@JCPAGE < <A@$A@#A@A@A@),aKNCPAGE ,a_JCPAGE ,a_L	CPAGE ,aSP
CPAGE k,aKNCPAGE 8 8,a_HCPAGE ,a_FCPAGE ,a_JCPAGE 	@H)ac,a
@L	CPAGE A@$A@#A@A@A@)9 9,aKNCPAGE ,a_JCPAGE ,a_L	CPAGE ,aSP
CPAGE acac:Q	@,a
@TCMISC A@< <	A	A,aSCPARAMac,a
@TCMISC -9	@ ,aSCPARAMAac\Q	@,a
@CMISC < <A@,aKCMISC 	C	A,ag
COUTYY,a_CMISC 	CXR],aKCMISC ; ;,aSCMISC \	@ ,aSCMISC Eac,a
@CPARAMA@$A@#A@A@A@eac:Q	@: :,a
@@9CPAGE A@
tac:Q	@,a
@D                     CPAGE A@
}ac:Q	@,a
@<CPAGE A@
ac:9 9Q	@,a
@BgCPAGE A@
acQ	@acQ	@	%L:R9$H?: :8,."XZGQE3*!:SlFfiYUm
~9 9,umuI^q6,16082R")	"BCb: :acQ	@c1		!Xp!        qi!!!!i! !<!Bi!9 9i!	!
! !"!'!.!	0!4i!`!b!c!l!5 5ri!
.i!'i$!$$COUT!$CPAGE !>$CPAGE !:$CPAGE !h9 9$CPAGE !b$CPAGE !`$CPAGE !d$CPAGE !f$	CPAGE !j$
CPAGE !V$CPAGE !Z$9CPAGE !\9 9$gCPAGE !^$                     CPAGE !2$CPARAM!B$CPARAM!$CPARAM!$CPARAM!L$CPARAM!$CPARAM!*9 9$CPARAM!F$CPARAM!H$CPARAM!J$	CPARAM!D$
CPARAM!l$CPARAM!N$CPARAM!R$CPARAM!89 9$CPARAM!$CPARAM!$CPARAM!P$                                                                   PARAM!~$CMISC !$CMISC !4$CMISC !$2CMISC !&9 9$CMISC !"$CMISC !($CMISC !z$CMISC !|$CMISC !$CMISC !x$CMISC !n$CMISC !*9 9#COMTYP!,#GETVAL!.#DOMAC !#ESC !T#GETSTR!@#CTOI!0#BRK !6#SET !<#SPACE !X#SCOPY !p: :#NEWINP!r#DEFMAC!t#SETTAB!v#GETSC !#PUTCH !
#MKTL!#PUT !#RESET0!#SWT !#GETARG!  #NEWOUT!,#CHKIF !.#APNDM0!0#TEXT
 
"%,0&$$ COMTYP; ;zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT	uQKQ	uQKQ9 9	@ QacQ@A@",a
@TABCOM	AQ	C		"		"	"	!& &~!$!!$!#$!$TABCOM!#LOOKUP
 
"%,$0&"" PROCE07 7zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT	@ ,aSCMISC QK: :,agCMISC 
,agCMISC 	QK,a_CMISC 	C	A,aSCMISC 9 9acQ	@acQ	@		!$CMISC !$CMISC !$CMISC !#COMAND!#TEXT
 
"%&"0&

!6$ TEXT; ;zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT	,aKCPARAM	@HCac: :Q	@,a
@1CMISC 		QK	%	%    acQ	@,aK                                                                   PARAM	A; ;acQ	@Q@A@A@acQ@Q	@A@,aK                                                                   PARAM	@H,aS                                                                   PARAM,aKCPARAM5 5	Aac Q	@Q@A@A@acQ@Q	@A@,aKCPARAM	@H,aSCPARAM8: :,aK"CPARAM	Aac$Q	@Q@A@acQ@Q	@A@,aK"CPARAM	@H,aS"CPARAMS; ;,aK&CPARAM	Aac(Q	@ac*Q	@,aK&CPARAM	@H,aS&CPARAMlQK	C: :ac*Q	@,aK,CPARAM	A
ac*Q	@	A"ac.Q	@A@"Q@	A9 9
ac0Q@                           z		!!!
! !!.!!0$CPARAM!$CPARAM!&: :$CPARAM!*$CPARAM!"$CPARAM!$                                                                   PARAM!$1CMISC !2#GETWRD!#PUTLIN!#LEADBL!#ITALIC# #! #CTOC!$#UNDERL!(#BOFACE!,#CENTER!.#PUT !4#PUTWRD
 
"%V$0&