& APNDM09 9zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT"macro (*s) can9 9%not be appended, it does not exist*n"Dnot enough sp: :ace to append to macro	achQ	@Q@acjQ@	"CaclA@8 8	a@Q@acn,aKpfCMACRO	"C	t",aKrjCMACRO,aSpfCMACRO	"@H,aStgCMACRO; ;,aKvlCMACRO	#	"t",a_vlCMACRO	$,aKtgCMACRO	MAQ	$MQ	C9 9	acxacjQ@	"t",a_vlCMACRO	$,aKtgCMACRO	MG5Q	$MQ	Cacz9 9a@DV=,aKtgCMACRO	#t",aKvlCMACRO	%	(%@,aktgCMACRO	@b	"%C	t%9 9,aK|gCMACRO,awtgCMACRO,aS|gCMACROclac~A@"*	acQ@A@#		!q!9 9}!!NCP!t$fCMACRO!x$gCMACRO!$gCMACRO!v$jCMACRO!z$lCMACRO0 0!n#FINDM0!l#GETNAM!p#PRINT !r#SWT !|#MACGC !~#ERROR !#MACREL!#MACINP
 
"%0&0&$ DEFMAC< <zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT		acQ	@Q@,aKgCMACRO9 9	"acQ@	#%
acA@#           	acQ@A@"		!}!$gCMACRO!#FINDM0 !#GETNAM!#MACREL!#MACINP
 
"%,$0&U.$ DOMAC 9 9zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT		",aKfCMACRO	#: :	t#,aKjCMACRO	#	Too many macros/input files.	#%	t#,aKgCMACRO	uQ_9 9	C	t#,aKhCMACRO	uQ_	C,akCMISC 	@	,agCMISC 
4acac; ;Q	@A@acC@5	t#,aK lCMACRO,awCMISC ,aS"CMISC 	@ ,aS$hCMISC ac&Q	@: :	"			"P!q!}!~U!!U!dU!$CMISC !($CMISC !*; ;$hCMISC !$fCMACRO!$gCMACRO!$hCMACRO!$jCMACRO!&$lCMACRO! #RESET0!"#PUTLIN!$#ERROR  !,#EMARGS
 
"%($0&Jj& EMARGS9 9zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT"missing quote9 9"Too many macro arguments"8Too many nested macro; ; calls	A"	##@HADQK	C	(#	#@HADQK	%	A
; ;	#@HADQK	C	(#$	(#@%	#@HADQK	%0	%3	A
29 94acTacVQ	@A@acXa@5	#@HADQK	t"QS	("&&/	(#@#@HAD	: :	QgX	t"QS	("@	(#@"	#@H$t$QK	%i	%lh	%ok9 9	%rn	A
q	t"QS	("^^s	#@HADQK	%	@ t"QS	(": :	",a[ZeCMACRO	CacTacVQ	@A@acXa@,ak\CMACRO	@	,ag\CMACRO: :!acTacVQ	@A@acXa@8",aKZeCMACRO,aw\CMACRO,aS^CMACRO	A%	(%: :	@7	%$"<	t%QK,awZeCMACRO,aS`C7CMACRO,akZeCMACRO88=		!qJ5 5!J!dJ!	!
! !"J!hJ!d$CMACRO!f$CMACRO!b $eCMACRO!h$C7CMACRO!\#RESET0!^#PUTLIN!`#ERROR 
 
"%0&0&" ENDMAC8 8zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT,awCMACRO,aKCMACRO2 2,aSeCMACRO,aKCMACRO	@H,aSCMACRO		!$CMACRO!$CMACRO!$eCMACRO
 
"%""0& @ EVALF09 9zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT"<==<<9 9&===~=<>><>==>>"D"',19 9"P"`fmt error:  illegal verticle s9 9pacing"in eval_fcn: can't happen	ac Q	@Q@
A@9 9	A"t"QK		C	("	A#	(#@("@	t"QK		A
	%#	t#; ;QS7"	@ t#QS7	A#	ac"Q@8A@#	$t#QK7	A	A,ag$CMACRO8<ac&9 9	A@$Q	@Q	@	%	=	t"QK		C	("HHM	ac(Q@8A@&,a
@*TABCOM	A; ;ac(Q@8A@&,a
@,TABCOM	@HCac"Q@
A@"	#QK	@H'#ac.A@ac0A@'9 9	#A(@HAD&QS	A($#||	@ t#QS	#%	e		QS	u	QGQ*QK	@H'8 8ac2Q@
Q	@*A@'	@D#@HAD	QS	@ t#QS	#%	Z	&),aK4CPARAM	*5 5,aK6CPAGE 	*7,aK8CPAGE 	*;,aK:CPAGE 	*?,aK<CPARAM	*C5 5,aK>CPARAM	*G,aK@CPARAM	*K,aKB
CPARAM	*O,aKDCPARAM	*S5 5,aKF	CPARAM	*W,aK$CMACRO	*[,aKHCPAGE 	*_,aKJCPAGE 	*c: :,aKLCPAGE 	*g,aKN	CPAGE 	*k,aKPCPARAM	*oacRQ@
A@"A@	+acR5 5	Q@
A@"A@	,+*sacRQ@
A@"A@	+acRQ@
A@"A@	,+A*; ;,aKT
CPAGE 	*,aKJCPAGE ,a[HCPAGE 	B*"	t"QK		-	A.		.1: :4	("6.	-/L/2>	@ .7	ac"Q@
A@"	$%MM	%L: :	@.t$,a[V8CMISC ,aSV8CMISC 	*t"QK		0	t$,akV8CMISC )_	t$,aKV8CMISC : :	@H,aSV8CMISC `[	01L\angN	@ *psacXA@*Q@BA@	9 9	(%
~	&C		#	#@H#(@H(	#A	(A	t(QKB	t#QSA9 9			t#QSAac2Q@BQ	@Q	@	%3	)2L2LX@H\*: :88<DP/9<T:=>?@ABCDEFG`dhlHMNO< <t	PSTUVWX#pY4]	&3,aKZCMISC QB,aK\CMISC 9 9QBf,aK^CMISC QBkac"Q@
A@"	*?		QBpy		QB}ac": :Q@
A@"	*?		QB
		QB	A#	("@(#@	t"QK		% : :	t#QSo	@ t#QSo	t"QK		C	("((-	A#	("@(#@3	t"QK	9 9	%>	t#QS=4=	@ t#QS=	t"QK		C	("FFK	A#	("@(#@: :Q	t"QK		%\	A
[	t#QSuR]	cmp: bad relational operator. b	@ t#QSu: :ac`a@Da@A@Q@>	4BCacbC@c	acdQ@pQ@v	5t4aKC	AD5ag9 9aK	$5		QB		QB!acRQ@
A@"A@	6t"QK		9 9	C	("//4	A#	("@(#@:	t"QK		%E	t#QS=;D	icmp: 9 9bad relational operator.I	@ t#QS=acRQ@
A@"A@	7ac`a@Da@A@Q@>	4BC: :acbC@Js	4@H8	6$7	@	QB%~		QB	6$7
		QB9 9		QB	67C		QB		QB	6$7$		QB#: :		QB'	7$6	@	QB+.		QB3	7$6:		QB7;		QB: :?{	8L||   ,,8CR	@ QCac2Q@BQ	@Q	@	%9 9a	3@H9Lgb	3%kl	                9Lqqrstuvwxy9 9
z|}&~	&:'acfA@Q@BachQ@BQBacfA@Q@BacfA@9 9Q@BacfA@Q@BacjQ@BA@	'aclQ@BQ@BA@'ac"Q@
A@"	*acn9 9	A@*Q@BA@		&C3acpQ@BA@Fac"Q@
A@"	*	acrA@*Q@B	&CM; ;acpQ@BA@^ac"Q@
A@"	*%qq	%p	@racba@`t	t*aKO9 9QB	@ QCeac"Q@
A@"	*?		QB
		QB	@ QCac"8 8Q@
A@"	*?		QB		QB"	@ QC,aK8CPAGE 	?ac < <,a
@tCPAGE Q@|A@-ac ,a
@v9CPAGE Q@|A@6acxQ@|,a
@8CPAGE Q@B; ;A@)ac ,a
@tCPAGE Q@|A@acxQ@|,a
@8CPAGE Q@BA@Iac ,a
@v9CPAGE ; ;Q@|A@acxQ@|,a
@8CPAGE Q@BA@\,aK8CPAGE 	?ac ,a
@zgCPAGE Q@|9 9A@sac ,a
@|                     CPAGE Q@|A@|acxQ@|,a
@8CPAGE Q@BA@oac 9 9,a
@zgCPAGE Q@|A@acxQ@|,a
@8CPAGE Q@BA@ac ,a
@|                     CPAGE Q@|A@9 9acxQ@|,a
@8CPAGE Q@BA@"5ac2Q@BQ	@Q	@	%	:;L.: :8GIJKLMNOPQRST44UYZ[\NNf]9 9 abcdehij*J]p#k	&<	t"QG	Q*ac~Q	@*9 9Q	@Q	@	%	t"QG	Q*acQ	@*Q	@Q	@	%	t"QG	Q*acQ	@*Q	@9 9Q	@A@	%	t"QG	Q*acQ	@*Q	@Q	@A@	%#		QS	t"QG	Q*< <	u	QGQ,QK	@H'ac2Q	@*Q	@,A@'	@D%@HAD	QS	@ t%QS4		QS	t"QG	: :Q*	u	QGQ,QK	@H'ac2Q	@*Q	@,A@'	@D%@HAD	QS	@ t%QSY	t"QG	: :Q*acpQ	@*A@ac2Q	@*Q	@Q	@	%~	t"QG	Q*acpQ	@*A@ac2Q	@*Q	@: :Q	@	%t	<=L!&u$5Z3456789:;<?9 9@ABCDEFGHIJKL	&>ac"Q@
A@"	$	acRQ@
A@"8 8A@	*$%ff	%e	@&C	*t$,aSV8CMISC l	*t$,a[V8CMISC ; ;,aSV8CMISC qgx	@ QS	%P	>%Q	%Q	@ QS	%aca@: :}(?_(	%	!!!!!!
!!!
!!9 9!                                 !!!!	 !        $! !*!0!15 5!H![!]!.!R$CPAGE !T$CPAGE !P$CPAGE !b$CPAGE !d9 9$CPAGE !f$CPAGE !h$	CPAGE !n$
CPAGE !$CPAGE !$9CPAGE !$gCPAGE !$                     CPAGE !N9 9$CPARAM!j$CPARAM!V$CPARAM!Z$CPARAM!^$CPARAM!`$	CPARAM!\$
CPARAM!X$CPARAM!p; ;$8CMISC !t$CMISC !v$CMISC !x$CMISC !>$CMACRO!D$TABCOM!F$TABCOM!#MAPUP !r#ITOC; ;!<#CTOI!l#GCTOI !B#LOOKUP!L#CTOC!#ITOROM!@#TRNARG!#INDEX !z#STRLSR!~#STRCMP!#UNDERL< <!#BOFACE!#ITOLET!#ITALIC!:#MASSIN!H#F$MA11!J#F$MI11!|#ERROR !#DATE!#SDROP !
#MAPSTR !#MKTL!#REMARK
 
"%n@0&Z* EXTRA0: :	A"#Q[	$	($@	$@HADQK	A
	%	%	t$QK	A
	%9 9	($@	(# "	#@H#A	#	%%.	&L!$3(	"9 9Qg	)8	@H'$@HADQK	t'QS	("9	"@HAD@ QS	#A	$QS		& &	(O		(U	(	!}!~Z!
!@!Z
 
"%6*0&"$ FINDM09 9zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT		",aKfCMACRO	#: :	t#,aKjCMACRO	#	#%	t#,aKgCMACROQ_	C,aKhCMACRO	uQ_	C7 7	#"	"	!}"!"!$fCMACRO!$gCMACRO!$hCMACRO!$jCMACRO
 
"%($0&U& GETNAM9 9	A""@HADQK	%	%
	%    	A
	("	"@HADQK	: :	C	("	A#	(#@#	#%	@"@H$t$QK	%3(	%62	%: :95	#@H%QK	t%QS	("$$	(#@8	#%	@@HAD	QSDH	@ uQS 		!U!	!
! 
 
"%,&0&" ITOLET9 9	QK	%	%	@		QS
QK	QS	@ uQS 		!!!?!`
 
"%("0&k$& ITOROM; ;	A"QK	A#QK	A	"Qg	@HAD	QS	("@		$#	@"Qg: :	@HAD	QS	("@ 	##		$#	@"Qg3	@HAD	QS	("@4: :	"Qg?	@HAD	QS	("@@	##.		$#	@"QgS	@HAD	QS9 9	("@T	##NK		$#	@"Qgf	@HAD	QS	("@g	"Qgr	@HAD	: :QS	("@s	##a		$#	@"Qg	@HAD	QS	("@	##: :~			$#	@"Qg	@HAD	
QS	("@	"Qg&	@HAD	QS	("@'	#; ;		#		$#	@"Qg:	@HAD	QS	("@;	##52		$#	@"Qg9 9M	@HAD	
QS	("@N	"QgY	@HAD	QS	("@Z	##H		$#< <	@"Qgm	@HAD	
QS	("@n	##fhe		$#	@"Qg	@HAD	QS9 9	("@	"Qg	@HAD	
QS	("@	##|		                                    #	@"Qg!	@H: :	AD	QS	("@"	#                #		$#	@"Qg4	@HAD	QS	("@5	"Qg: :@	@HAD	QS	("@A	##/	A$#	@"QgT	@HAD	QS	("@U	#: :	@H#MOL	"@HAD@ QS	"@H$	!!        !	!
!(!2!	Z!d!/ /-!c!d!i!l!m!v!
x!!t!!h
 
"%0&0& Z$ MACINP9 9zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT": missing end 9 9of definition		ac,Q@
A@	"BCac.ac0Q	@A@ac2a@
9 9Q
,ag4CMISC ,ag6CMISC ! Q	C!Q	C&ac8: :Q@
Q@QKQ	C	uQKQ	C7>+	",a[:gCMACRO	MA'I: :Gac<H	ac>Q@
A@,a
@@hCMACRO,a
@:gCMACRO	B,a[:gCMACRO,aS:gCMACRO?; ;,aK:gCMACRO	MG'Edbac<c		,aw:gCMACRO,aSBgCMACRO	@ ,aS@hCMACROQK9 9,aSDiCMACRO	uQK,aw:gCMACRO,aSFjCMACRO	@ ,aSHkCMACRO,aKJfCMACRO,aSLlCMACRO: :		,aSNmCMACROQK,aSPnCMACRO,aKLlCMACRO	%	AD,aK:gCMACRO	@D,aSHkCMACRO9 9,aK:gCMACRO	@D,aSJfCMACRO,aK:gCMACRO	,aS:gCMACRO		!q!}!!9 9!!e!n!.`CP!<$CMISC !>$CMISC !R$fCMACRO9 9!B$gCMACRO!J$gCMACRO!H$hCMACRO!L$iCMACRO!N$jCMACRO!P$kCMACRO!T$lCMACRO!V$mCMACRO2 2!X$nCMACRO!4#READLN!F#SCOPY !6#RESET0!8#PUTLIN!:#ERROR !@#GETNAM!D#MACGC 
 
"%\$0&HV* MACGC 9 9zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT"space for macr< <os exhausted",macro area exceeded	A"	("@	"MA'9 9	@t",aK@gCMACRO	A
		"MG'acBa@	"B#	(#@; ;	t#,aK@gCMACRO	A
 &	#B$$%	(%@-	%MG'	@t%,aK@gCMACRO	%<9 94.;	t%,aK@gCMACRO	BC	%%B,aKDgCMACRO	@H%F	"&$'	(&@7 7	('@O	'$%	@t',aK@gCMACRO	t&,aS@gCMACROPV	"(&"%MG'3g	t%: :,aKFhCMACRO	Ah	%@D#	(#@q	t#,aK@gCMACRO	A
rm	%#x,aKDgCMACRO: :	@H%C	%,agHfCMACRO	'',aKDgCMACRO	@H$%	',aSHfCMACRO9 9         (t',aSJlCMACRO,aKLjCMACRO	%	AD',aSNkCMACRO	t',aKNkCMACRO	%(: :	AD',aSLjCMACRO'	'$,aKDgCMACRO	@H%C+,aKDgCMACRO	M	G'f=;7 7acBa@,<	",aSDgCMACRO		!}!E!!!
E9CP!N6 6$fCMACRO!J$gCMACRO!F$gCMACRO!L$hCMACRO!R$jCMACRO!T$kCMACRO!P$lCMACRO!H#ERROR 
 
"%**0&H& MACREL8 8zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT	Qw,aKjCMACRO	"8 8,aKkCMACRO	#"%	#t",aSkCMACRO	#%	"t#,aSjCMACROQw: :,aKlCMACRO	$%!	t$,aKfCMACRO	A 		,aSfCMACRO%	@ t$,aSgCMACRO7 7)QK	$MA'5	t$,aKgCMACRO	A6		,aSgCMACRO;	@ Qw: :,aSlCMACRO?		!}F!F!F! F4CP!$fCMACRO!$gCMACRO! $jCMACRO!$kCMACRO!$lCMACRO
 
"%*&0&f& MASSIN9 9	A"#	(#@	#@HADQK	A
	CacQ	@A@#Q@
A@	@DC	"@H; ;	AD	QGQQK	"B$acQ@
Q	@A@$	""	#@HAD		Qg>;	t#QK: :	%D	%GC=F	(#@G	"QgM	@H$#@HADQK	t$QS	("@N) )	"@HAD@ QS	"@H%	!!@![!#EXTRA0!#EVALF0
 
"%8&0&$ RDMAC : :zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT	Qw,aGgCMACROQ
: :acQ	@
Q	@Q	@	"BQ[QS			Qg	"	"	!!$gCMACRO! #CTOC
 
"%0$0&9& TRNARG7 7zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT	@ "QK	A	#; ;,awCMACRO,aKCMACRO	$	#@H#	$,ageCMACRO	#A	t$,aKC7CMACRO; ;	A
	($	($	$,ageCMACRO'	t$,aGC7CMACRO	Q
acQ	@
1 1Q	@Q	@	"(	"	!$CMACRO!$CMACRO!$eCMACRO!$C7CMACRO!#CTOC
 
"%2&0&