S* BOFACE9 9	A"Q_	A#A$	($@		$@HADQK	A
	C	A%"$#	@H&$@HAD9 9QK	t&QS	("@"@HAD	QS	("/0	A%%7	"Qg:	@H3 3	'$@HADQK	t'QS	("

;	"@HAD@ QS	"@H(	!!! 
 
"%4*0&

b." BRK : :zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT,aKCMISC 	@HC		6 6	A,agCOUT	,aKCOUT	@H,aSCOUT,aKCOUT	@H,aSCOUT,awCOUT6 6,aKCOUT	%	%	A,agCOUT	@#,akCOUT	@9 9,akCOUT	@,aKCPARAM	C,aK
CPARAM,a_	CPARAM,a_COUT	B,aSCPARAM9 90,aKCPARAM	C,aK
CPARAM,a_	CPARAM,a_COUT	BM=,aSCPARAM?; ;:		,awCOUT,aSCOUT	@ ,aS COUTac",a
@ COUT
	A,aSCOUT	@ ,aSCOUT8 8,aS$COUT,aS&CMISC 		!! b!
! b!c!rb!$COUT!5 5$COUT!*$COUT!$COUT!&$COUT!$CPARAM!$$CPARAM!"$	CPARAM! $
CPARAM! $CMISC !,$CMISC !(#PUT 
 
"%""0&" CENTER7 7zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT	acQ	@acQ	@5 5,a_
CPARAM,a[	CPARAM	@HM=AacA@,aSCPARAM		!!!& &$CPARAM!$	CPARAM!$
CPARAM!#WIDTH !#TAILBL!#F$MA11
 
"%&"0&Kz. DIVOK 9 9""*"        wm"+7@"vm",7@"u}"-7@"".9 9"sm"/'@"vy"07@"w}"1w@""2"w}9 9"3w@"w}"4w@"w}"5s@"w}"6w@"Uu"7G@9 9""8"vm"97@" w}":w@"!wT";'@""VL"<9 9c@"#V}"=@"$">"%w}"?w@"&vm"@7@"'w}9 9"Aw@"("B")w}"Cw@"DeaoiuyEAOIUY"Reao9 9
iuyEAOIUY		"@ #A$	($@QK	@H$C	$@HADQK	%%: :	%	%	%"	%%!	%($	%+'*	"	+	%%39 93	%	2	@4	%%
<<	%	@6?	(#@	@ &QK	$: :	($@H	$@HADQK	A
	%%V	%YU	%\X	%_[	%b^: :	%ea	%hdg,h	%%oo	%	n	@p	%%
xxI	%9 9I	@r{	(&@IQ		$#	@$&	@,	A$	($@
	$@H; ;	ADQGQac`a@DQ	@	A
QK	@H$$	@,!QK	$9 9	($@(	$@HADQGQac`a@RQ	@	A
9	$@HADQK	A,A):9 9QK	@HADQGQacbQ	@	@HCQK	'QK	@H(t'QK	t(QgcR		9 9	",bQK	@HADQGQacdQ	@	)QK	@HADQGQacdQ	@	*)%9 9	%		@	)%
	%	@         *%	%		@9 9	*%
  	%	@!,#	)+*
'M=B,'M=@B-,9@+AD	-9 9	'	aKuacfA@'	                                                G,F		",! !}!~K!        K!!9 9
!K!!!-!/!<!>!AK!	Z!_!
aK!z K!t#SUFFIX!r#INDEX !v#MAPDN !x#F$RS
 
"%6.0&b& GETWRD: :zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT	QK	@HADQK	%
9 9	%	QK	@HADQK,agCMISC Qk	A"QK	@H< <	ADQK,a_CMISC 	C	"@HAD,aKCMISC QSQk	@("3'QK	@HADQK9 9	#%?	%B>,agCMISC FA	%IE	A
HK	"@HAD#QSQk/ /	@("55J4	"@HAD@ QS	"@H$	!	!
! b!$CMISC 
 
"%0&0&
( HYNATE: :zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT	,aKCMISC 	"A		9 9acQ	@	#@H$	$@H$		$$acQ	@A@$	@DC	A%	(%@!; ;	%$$&	@HADQKQS"'	%@HAD	QS	@ t%QSacQ	@Qg	@acQ	@9 9	A@$Q	@	A@	"		$@HADQK	C	#$@HC	A%	(%@\	%$$	@: :	@HADQKQS]a	%@HAD@ QSacQ	@Qg	@$B&acQ	@A@&Q	@	A@K9 9vYT	@ "K!!
!-
!$CMISC !#DIVOK !#LENGTH!#WIDTH  !#SCOPY 
 
"%4(0&>& LEADBL9 9zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT	ac	A"	("@9 9	"@HADQK	C	"@HADQK	%,aKCPARAM	"@H,aSCPARAM	A9 9	#	(#@!	"@H$t$QK	A
	#@H%QK	t%QS	("""+	#@HAD@ QS   		!
! >!$CPARAM!$CPARAM!#BRK 
 
"%*&0&P
$ NXBLNK: :zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT	,aKCMISC 	"A		: :QK	@HADQK	%	%	%	%	A"QK: :	@HADQK	%&	%)%	%,(	%/+	%2.	%	514QK9 9	@HADQK	%?	%B>	%EA	%HD5G	A"H	@ "K	"	6 6!!!"!'!)!.P!:!	>!?P!]!}P!$CMISC 
 
"%*$0&
2&$ PFOOT < <zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUTac,a
@CPAGE ,aK	CPAGE 9 9	A,aKCPAGE 	?ac,a
@gCPAGE Q@A@ac,a
@                     CPAGE Q@6 6A@acQ@,a
@CPAGE ,aK	CPAGE 	@H"acA@"	@ ,aS CPAGE 	A6 6,aS"CPARAM		!.2!$CPAGE !"$CPAGE !$CPAGE !$	CPAGE !$gCPAGE ! $                     CPAGE !$$CPARAM!#SKIP!#MASSIN! #PUTTL 
 
"%R$0&V2$ PHEAD : :zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT,aKCPAGE ,aSCPAGE 	B: :,aSCPAGE ,aKCPAGE ,a[CPAGE 	B,aSCPAGE ,aKCPAGE ,agCPAGE 9 9,agCPAGE 	@		,aKCOPTS 	@HCac A@A@ac"A@"A@9 9,aKCPAGE 	A	@H#ac$A@#,aKCPAGE 	?ac&,a
@(CPAGE Q@A@9 99ac&,a
@*9CPAGE Q@A@Bac,Q@,a
@CPAGE /ac$,a
@CPAGE 		!: :q!rV!V!.V!$CPAGE ! $CPAGE !$CPAGE !$CPAGE !$CPAGE !9 9$CPAGE !$CPAGE !,$CPAGE !.$9CPAGE !"$COPTS !$#PUTCH !&#GETCH !(#SKIP!*#MASSIN !0#PUTTL 
 
"%R$0&

UH( PUT ; ;zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT	@ ,aSCPARAM,aKCPAGE 5 5	A
,ag
CPAGE 	@
ac,aKCPAGE ,agCPAGE 5 5,agCPAGE 	@,aKCPARAM	",aKCPAGE 	?,aK CPARAM	"" ; ;,aK"CPARAM	""%,aK$	CPARAM	",a[&CPARAM,a[(CPARAM	@H#A$	($@5	$$#: :	@	t$QS6:	@ t$QS,aK(CPARAM	A,aK*CMISC 	t"QSH	#Aac,8 8Q@A@P,aK.CPARAM,aS&CPARAM,aK0CMISC ,aS*CMISC 	A,aS2CMISC 	%&9 9,aKCPAGE ,agCPAGE kk,agCPAGE j	@A$	($@q	$@HADQK	A
: :,a_4CMISC 	C,aK6CMISC 	t&QS	(&@(%@t%,aK82CMISC 	%	%%9 9	@r~	$@HADQK	C	%@H%	(%@	$@HADQK	t&QS	(&: :	@rz	@ t&QSac,Q@A@m,aK
CPAGE ,a_CPAGE 	',aK:CPARAM	@Hac<: :A@'	'ac>A@',aK:CPARAM,a[CPAGE ,aSCPAGE ,a_
CPAGE 	Cac@Q		9 9!uU!U!!! U! $CPAGE !"$CPAGE !$CPAGE !$CPAGE !9 9$
CPAGE !$CPARAM!$$CPARAM!.$CPARAM!4$CPARAM!,$CPARAM!*$	CPARAM!@$CPARAM!&9 9$CPARAM!($CPARAM!>$2CMISC !8$CMISC !6$CMISC !0$CMISC !<$CMISC !:$CMISC ! #PHEAD !2#PUTLIN!D#SKIP!F#PFOOT !B#F$MI11
 
"%Z(0&<&$ PUTTAB8 8zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT,aK
CPARAM,a_CPARAM5 5,a_	CPARAM	B"A#	(#@
	#,agCOUT	t#,aKCOUT	C		6 6,aSCOUT         ",agCOUT	@,aKCMISC ,awCOUT,aSCOUT5 5,akCOUT	@,akCOUT	@,awCOUT,aK3CMISC 	@HC!	A,aS COUT	@ 8 8,aS"CMISC 		! <! <!$COUT!$COUT!"$COUT!$COUT!$CPARAM!" "$	CPARAM!$
CPARAM!$$CMISC ! $3CMISC !$CMISC 
 
"%$$0&<,$ PUTTL ; ;zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT"*#x	,aKCPAGE 6 6,agCPAGE ,agCPAGE 	@
		,aKCPARAM,a[CPARAM: :,a[	CPARAM	@H",aKCPAGE 	?,aK CPARAM	"",aK"CPARAM	""ac$: :!A@a@A@"ac&Q	@Q	@Q@A@ac(Q@A@		!u<!.<!$CPAGE !; ;$CPAGE !$CPAGE !$CPARAM!$CPARAM! $	CPARAM!"$CPARAM!$$CPARAM!&#PRINT !(#MKTL !*#PUTLIN
 
"%X$0&

="$ PUTW8 8zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT	A,agCMISC 8 8,agCOUT
	,akCOUT	@
	acQ	@A@,a
@COUT,a
@COUTQK: :,a[COUT,aSCOUTQK,a[COUT,aSCOUT,aKCOUT	@H"ac,a
@COUTA@"9 9	@HC		,awCOUT,aSCOUT,akCOUT	@,akCOUT	@0		!! =!0 0$COUT!$COUT!$COUT! $COUT!$COUT!$CMISC !#NXBLNK!#SCOPY 
 
"%.$0&I8( PUTWRD; ;zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT	QK,a_CMISC 	C; ;ac,aK
CPARAM,a_CPARAM,a_	CPARAM	B"acQ	@	#,aKCMISC 	@HC; ;		,awCOUT,aS COUT,akCOUT	@,ak"COUT	@	",a_"COUT	$#Cac$Q	@9 9	%ac&Q	@A@#A@%-ac(Q	@A@$Q@Q@x	@HCac$Q@	%acQ@; ;	&ac&Q@A@&A@%,aK*CPARAM	C	",a_"COUT	%ac,,a
@.COUT,a
@COUT; ;A@%,a
@0COUT_	ac2ac$Q@x	%acQ@x	&ac&Q@xA@&A@%H,aKCOUT; ;	@H,aSCOUT,aK"COUT	@H,aS"COUT	A,agCOUT	@,awCOUT,aK COUT	%: :	%,akCOUT	@,ak"COUT	@,aK*CPARAM	C	",a_"COUT	%9 9ac,,a
@.COUT,a
@COUTA@%,a
@0COUT'	ac2ac$Q	@	%ac&Q	@A@#A@%8 8;	A,aSCMISC 			! I! I!bI!"$COUT!&$COUT!4$COUT!$; ;$COUT!2$COUT!.$CPARAM!$CPARAM!$	CPARAM!$
CPARAM! $CMISC !$CMISC !#WIDTH # #!(#LENGTH!,#HYNATE!#PUTTAB!*#PUTW!0#SPREAD!6#BRK 
 
"%(0&

:" SET ; ;	QK	C
QK	QSQK	CQKQ[QSQK	CQK9 9Q_QSQKQS"
QKQg+QS,QKQg75QS 6/		!
!+!-
 
"%4"0&X& SETTAB; ;zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT	A"#	(#@	#%: :	@@ t#,aS2CMISC 		A#	(#@	#@HADQK	%	% 	%#9 9"	acQ	@A@#	$A	#@HADQK	C4	(#$$,	$%>>6 6	%=	@At$,aS2CMISC 	$$"JH	"I?$	("@5	"%	@At"4 4,aS2CMISC LP		!X!!	!
! X!$2CMISC !#CTOI
 
"%*&0&)$ SPACE : :zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT	,aK
CPAGE ,agCPAGE ; ;		,aKCPAGE 	Aac,aK
CPAGE ,a_CPAGE 	BacQ	@	"ac5 5A@"QK,a[CPAGE ,aSCPAGE ,a_
CPAGE 	Cac%		!$CPAGE ! $
CPAGE !#PHEAD !#SKIP!#PFOOT !#F$MI11
 
"%($0&d( SPREAD9 9!	QK	A	A	Qg				
	AQK	"QK		@H#QK9 9	@H$"acA@	%%$$%#	@H&$@HADQK	t&QS	C		A	"@HM<#B9 9	'4	"M<#';	"'"#@H#	'@H'F	'A	%@H%@HAD	QSGL1	$@H$& &	%@H% $	QKQ[QS		! !,d!#F$MI11
 
"%4(0&1$$ SUFFIX9 9"	ingtion"	A"	("@	"@HAD	QGQ
QK
	A
ac9 9Q	@
	t"QS	@ t"QSac a@a@A@Q@	%*	A#)	@ #, 	#	!!1!"#STRBSR! #MAPDN 
 
"%0$0&s(( ITALIC9 9zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT"<<*s>> <<*i>>*: :n	ac A@a@Q	@Q	@	A"Q_	A#A$	($@	$@H%t%QK	A
9 9,ag"CMISC "	%&&!	%)%	"$#+	@H&QK	t&QS	("@"@HAD: :		QS	("=>(	"Qg,B	$@H%t%QK	C	"@H&QK	t&QS	("9 9L	$@HAD	Qg	@"@HAD	QS	("@^C	"@HAD@ QS	"@H'	!q   s!! s!_s!&$CMISC !$#PRINT 
 
"%2(0&,
( UNDERL: :zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT"#$%&'=-~^@+*9 9	A"Q_	A#A$	($@		$@HADQK	A
,agCMISC 	CQK	9 9	AQK	%$$	%#	@%	$@HADQK	%11	%0	@'9 92	$@HADQK	%>>	%=	@4?	$@HADQGQac a@Q	@	AA9 9P	"$#T	@HAD	QS	("@"@HAD	QS	("deQ	"QgUi	@H%$9 9	@HADQK	t%QS	("

j	"@HAD@ QS	"@H&	!! !0!9* *!A!Z!_!a!z!($CMISC !*#INDEX 
 
"%6(0&
