6F$ NEWINP9 9zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT": too many mac; ;ros/input files		ac.Q	@A@	"%,ak0CMISC 	@	,ag0CMISC < <ac2A@"ac4ac6Q	@A@ac8a@	",aw0CMISC ,aS:CMISC 	A,aS<hCMISC 5 5ac>A@"		
	ac4ac@Q	@!q!}6!6!d6!4$CMISC !>6 6$CMISC !@$hCMISC !2#XOPEN !6#XCLOSE!8#RESET0!:#PUTLIN!<#ERROR !B#REWIND!D#CANT
 
"%($0&<$ NEWOUT9 9zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT": can't open d: :ivert output		ac,Q	@A@	"Cac.ac0Q	@A@ac2a@
	"; ;,aS41CMISC ac6A@"		!q!}!!8$1CMISC !0#XOPEN !2#RESET0!4#PUTLIN !6#ERROR !:#WIND
 
"%($0&t4$ READLN: :zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT	,awCMISC ,aKhCMISC 9 9	A,aGCMISC Q4acQ@Q	@4A@	",awCMISC ,aGCMISC Q4; ;acQ@Q	@4A@	"	"%(acQ@Q	@Q	@	"	',awCMISC ,aKhCMISC : :	A
,aGCMISC Q4acQ	@47ac@,aKCMISC 	@H,aSCMISC 	@HC: :Jac ,a
@"2CMISC ,a
@$CMISC A@	BC	@ ,aS&CMISC ac(,aK*CPAGE 5 5	Aac,A@_	A,agCMISC 	@g	"	V,ak"2CMISC 	@ac.9 9,a
@$CMISC !t!4t!.t!'t!.$CPAGE !*$CMISC !$CMISC ; ;!$CMISC !$hCMISC !&$2CMISC !($CMISC !#GETLIN!$#GETARG!#MASSIN!#RDMAC ! #XCLOSE !"#ENDMAC!,#BRK !0#SPACE !2#NEWINP
 
"%Z$0&2$ RESET05 5zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT,aKCMISC 	@H< <,aSCMISC 	A,agCMISC 	@,awCMISC ,aKhCMISC 	@HC,aGCMISC Q9 9acQ	@		A"t",aGLCMISC QQK	%
'acQ	@&	A"%17 7		!}2!d2!$CMISC !$CMISC !$hCMISC !$LCMISC !#XCLOSE!#RMTEMP
 
"%($0&$ XCLOSE: :zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT	A"QK	t",a_LCMISC 0 0	C				A"%    acQ	@		!d!$LCMISC !#CLOSE 
 
"%($0&:& XOPEN < <zDS$MEMTABCOMCOPTS G CMACRO<CMISC CPARAMCCPAGE 1COUT	A"	acQ	@A@"	#QK: :	C	uQK	A		$	#%	%	@t#,aKLCMISC 	C9 9acA@	t#,aSLCMISC $	t#,aKLCMISC 	$	acQ	@Q	@	$0	$	!8 8v!}:!:!:!d:!-:!$LCMISC !#OPEN!#CTOI!#MKTEMP
 
"%,&0&