

            tmark$ (6) --- return the current position of a terminal file  03/23/80


            _C_a_l_l_i_n_g _I_n_f_o_r_m_a_t_i_o_n

                 file_mark function tmark$ (f)
                 file_des f

                 Library:  vswtlb (standard Subsystem library)


            _F_u_n_c_t_i_o_n

                 'Tmark$'  is  used  to  obtain  the  current  position  of a
                 terminal file.  Since this concept doesn't have much meaning
                 at the present, 'tmark$' always returns zero.


            _S_e_e _A_l_s_o

                 markf (2), seekf (2)








































            tmark$ (6)                    - 1 -                    tmark$ (6)


