#  build --- build version 9.0 shared shell library

   declare _search_rule = "^int,^var,&,=bin=/&"

   compile        # compile the shell routines

   maklib         # create the library entries

   linklib        # load the shell and create the shared lib
