

            ap (3) --- Generate Object Tape for A & P M6800 Monitor  07/19/84


          | _U_s_a_g_e

          |      ap <file> [<start_address>]


          | _D_e_s_c_r_i_p_t_i_o_n

          |      'Ap'  reads  the  relocatable  binary  file  in  <file>, and
          |      produces absolute code, in hexadecimal, on its  first  stan-
          |      dard  output.  The optional <start_address> is where it will
          |      relocate the code to.  The default starting address is zero.


          | _M_e_s_s_a_g_e_s

          |      "Usage: ap ..."  if called improperly.


          | _B_u_g_s

          |      Locally supported.

          |      This description may not be entirely  accurate,  since  this
          |      command has long been undocumented.


          | _S_e_e _A_l_s_o

          |      Whatever  other  programs  are  used for the "Allen and Paul
          |      Model 1" terminal.




























            ap (3)                        - 1 -                        ap (3)


