

            bug (3) --- report a bug with system software            02/23/82


            _U_s_a_g_e

                 bug


            _D_e_s_c_r_i_p_t_i_o_n

                 'Bug' allows users to report any problems they may encounter
                 with  system  commands  or libraries.  It creates a standar-
                 dized report whose existence  is  announced  to  the  system
                 administrator  at  each  login until the report is examined.
                 'Bug' prompts for such information as  the  user's  name,  a
                 description  of  the  bug,  and  the name of any file (e.g.,
                 program  source  code  or  comoutput   file)   which   helps
                 illustrate the bug.


            _E_x_a_m_p_l_e_s

                 bug


            _F_i_l_e_s

                 =bug=/r???  for storage of the bug report
                 =bug=/s???   for  storage  of  the user's environment at the
                      time the bug was reported


            _S_e_e _A_l_s_o

                 raid (3)


























            bug (3)                       - 1 -                       bug (3)


