

            focld (3) --- send FOCAL-GT/RT programs to the GT40      02/23/82


            _U_s_a_g_e

                 focld <filename>


            _D_e_s_c_r_i_p_t_i_o_n

                 'Focld'  is  used  to  prepare a FOCAL program stored on the
                 Prime for acceptance by FOCAL-GT/RT.  'Focld' is  used  from
                 FOCAL in the following manner:

                     Type control-f.
                     Type your "kill" character.
                     Without hitting return, type: focld <filename>
                     Type control-t.
                     Hit return.
                     Wait while the program loads.
                     Type control-t and control-f and you will be talking
                        to FOCAL.

                 It  is  advisable to study section 3.1 and figure 3-1 of the
                 _F_O_C_A_L_-_G_T/_R_T _U_s_e_r_'_s _M_a_n_u_a_l to understand the above  procedure
                 and to develop the procedure for saving FOCAL programs.


            _E_x_a_m_p_l_e_s

                 focld life
                 focld chess


            _B_u_g_s

                 Locally supported.


            _S_e_e _A_l_s_o

                 as11 (3), _F_O_C_A_L_-_G_T/_R_T _U_s_e_r_'_s _M_a_n_u_a_l



















            focld (3)                     - 1 -                     focld (3)


