

            kill (3) --- log out a user                              01/13/83


            _U_s_a_g_e

                 kill <pid>


            _D_e_s_c_r_i_p_t_i_o_n

                 'Kill'  logs  out the user (process) whose process number is
                 given  as  the  first  argument.   It  is  a  shorthand  for
                 "x lo -<pid>".


            _E_x_a_m_p_l_e_s

                 kill 19


            _M_e_s_s_a_g_e_s

                 "Usage:  kill ..."  for a missing argument.


            _S_e_e _A_l_s_o

                 x (1), ph (1)

































            kill (3)                      - 1 -                      kill (3)


