

            nodes (3) --- print network nodes                        01/15/83


            _U_s_a_g_e

                 nodes


            _D_e_s_c_r_i_p_t_i_o_n

                 'Nodes'  prints  all  network  node  names  in  the  current
                 Primenet configuration, if networks are enabled.


            _M_e_s_s_a_g_e_s

                 "network not configured" for no network.
                 "x$stat error.  Shouldn't  happen"  for  unexpected  network
                 errors.


            _E_x_a_m_p_l_e_s

                 nodes


            _B_u_g_s

                 Locally supported.


            _S_e_e _A_l_s_o

                 ns (3), nstat (3)



























            nodes (3)                     - 1 -                     nodes (3)


