

            phone (3) --- find someone's telephone number            06/12/82


            _U_s_a_g_e

                 phone [<person> | <business>]


            _D_e_s_c_r_i_p_t_i_o_n

                 'Phone' finds the telephone number (or numbers) belonging to
                 a  given  person  or  business, provided the number has been
                 placed in the on-line phone directory.

                 If no person or business is given, the entire  phone  direc-
                 tory is listed.


            _E_x_a_m_p_l_e_s

                 phone ack radio
                 phone ed rupp
                 phone


            _F_i_l_e_s

                 =phonelist= for directory of telephone numbers


            _B_u_g_s

                 Locally supported.




























            phone (3)                     - 1 -                     phone (3)


