

            pwd (3) --- print working directory name                 03/23/80


            _U_s_a_g_e

                 pwd


            _D_e_s_c_r_i_p_t_i_o_n

                 'Pwd'  is  supplied  for  Unix users who have not learned to
                 type "cd -p".


            _E_x_a_m_p_l_e_s

                 pwd


            _S_e_e _A_l_s_o

                 cd (1)







































            pwd (3)                       - 1 -                       pwd (3)


