

            sol (3) --- play a friendly game of solitaire            01/15/83


            _U_s_a_g_e

                 sol


            _D_e_s_c_r_i_p_t_i_o_n

                 'Sol'  uses  the Subsystem virtual terminal handler (VTH) to
                 play a standard or casino version of solitaire on the screen
                 of a video terminal.  When 'sol' is  executed,  it  displays
                 the commands used for playing the game.

                 It is included to demonstrate the use of the VTH package.


            _F_i_l_e_s

                 =vth=/?*


            _E_x_a_m_p_l_e_s

                 sol


            _M_e_s_s_a_g_e_s

                 "Terminal type '<term_type>' not supported" when <term_type>
                      is not supported by VTH.


            _B_u_g_s

                 Only works on video terminals that are supported by VTH.

                 Can be mildly addictive.






















            sol (3)                       - 1 -                       sol (3)


