**=	V$CIRNG -V$CIUPB @V$CILWB SV$VIRNG V$VIUPB V$VILWB 9 9	RANGE_ERROR A'	
C#1A@
A@A@A	A@A' 	@A	
C#v: :A@
A@A@A	A@A'3	@A	
C#vA@
A@A@A	A@A'QQ	
9 9C#1A@
A@A@A	A@AAwAgii	
AK	C#1A@
A@A@A	< <A@AwAgq	@A	
AK	C#vA@
A@A@A	A@AwAg		@A; ;	
AK	C#vA@
A@A@A	A@AwAg//	
AK	C#1A@
A@A@9 9	A	A@A%Y"
ARange check failed (*i < *i) on line *i of *v*n.		AcC@;C@A; ;!A	@
A	@A	@A	@AcC@C@C@<C@C@<C@<%"Range check failed (*i > *i); ;
 on line *i of *v*n.	,AcC@;C@A	@A	@A	@A	@AcC@C@C@<C@C@<C@< !#PRINT #SIGNL$= 0