**K	V$CURNG .V$CUUPB BV$CULWB VV$VURNG V$VUUPB V$VULWB ; ;	RANGE_ERROR 	
ACCFC#7A@
A@A@A	A@	
ACCH"	
	AC#A@
; ;A@A@A	A@	
ACCH6	
AC#A@
A@A@A	A@	
	ACCFSC#7; ;A@
A@A@A	A@	
A	
AwA_CCFlAK	C#7A@
A@A@A	A@: :Aw	
A_CCHv	
AAK	C#A@
A@A@A	A@Aw	
A_CCH	
; ;AAK	C#A@
A@A@A	A@	
AwA_CCF4AK	C#7A@
A@A@: :A	A@	
A%c"
GRange check failed (*,-10i < *,-10i) on line *i of *v*n.	Ac; ;'C@IC@GA	@
A	@A	@A	@AcC@C@C@JC@C@JC@J%,"Range check fail: :ed (*,-10i > *,-10i) on line *i of *v*n.	!AcC@IC@A	@A	@A	@A	@AcC@C@C@J C@C@JC@J!#PRINT #SIGNL$K 0