**]	V$CVRNG 1V$CVUPB GV$CVLWB ]V$VVRNG                                                                                       $VVUPB -V$VVLWB 9 9	RANGE_ERROR -A
ACCFC#IA@
A@A@A	A@A
ACCH%A
AC#; ;9A@
A@A@A	A@A
ACCH;A
AC#A@
A@A@A	A@A
ACCFY; ;9C#IA@
A@A@A	A@A
AA
AwA_CCFuAKAC#IA@
A@A@A	; ;9A@A
AwA_CCHA
AAKAC#A@
A@A@A	A@A
AwA_CCH; ;9A
AAKAC#A@
A@A@A	A@A
AwA_CCFEAKAC#IA@
A@9 9A@A	A@A
A%u"
YRange check failed (*,-10l < *,-10l) on line *i of *v*n.	; ;*AcC@[C@YA	@
A	@A	@A	@AcC@C@C@\C@C@\C@\%>""Range chec: :k failed (*,-10l > *,-10l) on line *i of *v*n.	AcC@[C@"A	@A	@A	@A	@AcC@C@   C@\C@C@\C@\!#PRINT #SIGNL$] 0